### ISSUE TITLE
Is there any way to make CardField displayed along the vertical axis?

### ISSUE THREAD

**Issue by mike392** [flutter-stripe/flutter_stripe#100]
Hi, Team,

Can you, please advise me how can i customize the CardField? Now it looks like it is aligned to horizontal

![image](https://user-images.githubusercontent.com/16647651/120190912-8407b280-c219-11eb-8ef4-b63fd66654bc.png)

And - is it possible to expose the setters for the fields? So that, for example, there could be used custom solution like `flutter_credit_card` or whichever and be still compliant with the `createPaymentMethod` method.

Thank you so much in advance!

**Comment by jonasbark** [comment]
You can see all the available customizations here:
https://github.com/flutter-stripe/flutter_stripe/blob/main/packages/stripe/lib/src/widgets/card_field.dart#L12

Please file a new ticket if you'd like specific adjustments. It will be limited to what the Android & iOS views provide:
https://stripe.com/docs/mobile/android/basic#customize-ui

Support for custom card details is already tracked here: https://github.com/flutter-stripe/flutter_stripe/issues/40

**Comment by raviganwal** [comment]
or better please provide three separate widget for card number, card expiration and cvc code, because I see custom payment layouts in every project.
