### ISSUE TITLE
Jcenter is down

### ISSUE THREAD

**Issue by BetterB0y** [flutter-stripe/flutter_stripe#1001]
**Describe the bug**

`  > Could not resolve com.stripe:stripe-android:20.12.+.
     Required by:
         project :app > project :stripe_android
      > Failed to list versions for com.stripe:stripe-android.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/stripe/stripe-android/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/com/stripe/stripe-android/maven-metadata.xml'.
               > Read timed out
`

**Additional context**

Jcenter was shut down. It was read only until today. Today jcenter is returning 403. I cannot run my app now. Please update your project to something different than jcenter.

https://stackoverflow.com/questions/74258160/is-jcenter-down

**Comment by jonasbark** [comment]
https://github.com/flutter-stripe/flutter_stripe/issues/1000
