### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by PrinceGoyal** [flutter-stripe/flutter_stripe#1002]
I am using flutter_stripe: ^6.0.0,
Unable to run, getting this error tried so many solution-
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.stripe:stripe-android:20.12.+.
     Required by:
         project :app > project :stripe_android
      > Failed to list versions for com.stripe:stripe-android.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/stripe/stripe-android/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/com/stripe/stripe-android/maven-metadata.xml'.
               > Read timed out

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 32s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by jonasbark** [comment]
https://github.com/flutter-stripe/flutter_stripe/issues/1000#issuecomment-1296951754
