### ISSUE TITLE
Unable to build app due to jcenter being down

### ISSUE THREAD

**Issue by daviddavis83** [flutter-stripe/flutter_stripe#1004]
**Describe the bug**
For the last 24 hours I have not been able to build my app due to jcenter being down. 

**To Reproduce**
1. flutter build appbundle

**Expected behavior**
Build apk for android

**Additional context**
I thought maybe I had jcenter specified somewhere in my build.gradle but I am using mavenCentral(). I also checked the build.gradle for flutter_stripe and I do not see jcenter. I'm not really sure why it's trying to hit jcenter. Here is the error

`* What went wrong:
Execution failed for task ':app:checkReleaseDuplicateClasses'.
> Could not resolve all files for configuration ':app:releaseRuntimeClasspath'.
   > Could not resolve com.stripe:financial-connections:20.12.+.
     Required by:
         project :app > project :stripe_android
      > Failed to list versions for com.stripe:financial-connections.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/stripe/financial-connections/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/com/stripe/financial-connections/maven-metadata.xml'. Received status code 502 from server: Bad Gateway`

Flutter version: 3.3.6
Dart Version: 2.18.2
flutter_stripe version: 5.1.0

**Comment by jonasbark** [comment]
https://github.com/flutter-stripe/flutter_stripe/issues/1000
