### ISSUE TITLE
Exception is thorn when ser click on cancle button in butomsheet

### ISSUE THREAD

**Issue by rddewan** [flutter-stripe/flutter_stripe#1007]
**Describe the bug**
Why do we need to have a exception on user close the bottom sheet? should it not just return the status as cancelled ? 
![Screen Shot 2565-11-01 at 4 19 56 PM](https://user-images.githubusercontent.com/13164167/199201448-9fd83043-f4a3-436f-a507-d216e94141e8.png)

**Comment by remonh87** [comment]
This is in accordance with the Stripe sdk which throws a stripe exception. It works as expected.  We want to keep it as simple as possible and now every user can decide to map it to their own status instead of being tied to some model we enforce.
