### ISSUE TITLE
Unable to presentGooglePay

### ISSUE THREAD

**Issue by rddewan** [flutter-stripe/flutter_stripe#1008]
`googlePaySupported` is true but still unable to show the google play
Code:
```
     final amount = items.map((e) => e.amount).reduce((value, element) => value + element);
      Map<String, dynamic> paymentIntent = await  _createPaymentIntent(amount);    
      final googlePaySupported = await Stripe.instance.isGooglePaySupported(const IsGooglePaySupportedParams());
      if (googlePaySupported) {
        await Stripe.instance.initGooglePay(
          const GooglePayInitParams(
            testEnv: true, 
            merchantName: "Richard", 
            countryCode: 'th'),
        );
        
        await Stripe.instance.presentGooglePay(
          PresentGooglePayParams(clientSecret: paymentIntent['client_secret']),
        );
      }
```

Exception:
```
I/flutter (17983): exception:StripeException(error: LocalizedErrorMessage(code: FailureCode.Failed, localizedMessage: presentForPaymentIntent() may only be called when Google Pay is available on this device., message: presentForPaymentIntent() may only be called when Google Pay is available on this device., stripeErrorCode: null, declineCode: null, type: null))#0      MethodChannelStripe.presentGooglePay
```

**Comment by remonh87** [comment]
@rddewan  I spend some time today but cannot reproduce it can you provide some more information about it?  For example what is the device and the android version. Tested on Pixel 4a with Android 13.

**Comment by rddewan** [comment]
@remonh87  here you can see i am using api 33 and 31 but it does not show the google play button. Any specific setting or configuration need to be done to enable this button ?
![Screenshot 2565-11-15 at 12 08 20 PM](https://user-images.githubusercontent.com/13164167/201831387-7d1728a0-bf31-4e0d-a9cb-cbda1cb3115f.png)

**Comment by remonh87** [comment]
I tried with version 7.0 and I could see the google pay item. Can you update the version of flutter stripe to the latest release (we shipped a new version today).

**Comment by rddewan** [comment]
just updated but still not showing. Any configuration i need to check ?
![Screenshot 2565-11-16 at 11 57 52 AM](https://user-images.githubusercontent.com/13164167/202087573-246fc490-a7b8-4fce-b8fe-df492efc6ab7.png)

**Comment by remonh87** [comment]
Ah please try to use a real Android device for testing Google pay because I am not sure if this works on emulators. I have run latest Flutter_Stripe example app on my phone and I get this. Can you try running the example app?

![Screenshot_20221116-205420](https://user-images.githubusercontent.com/20230599/202292830-b0ff2294-e04e-42a4-920f-b11f04ed2213.png)

**Comment by rsavani800** [comment]
i'm also having the same problem please the give me solution for how to enable google pay in payment intent shet
