### ISSUE TITLE
Thailand PromptPay

### ISSUE THREAD

**Issue by rddewan** [flutter-stripe/flutter_stripe#1009]
How do we add the prompt pay support to app ?  I can see only the checkout is showing the prompt pay ? any way we can add it to bottom sheet or any other option ?

**Comment by remonh87** [comment]
I don't know enough about PromptPay but it looks like collecting data will happen outside the client. I would recommend contacting stripe and read: https://stripe.com/docs/payments/promptpay . 

If some client code is needed for collecting payment information we need to wait for Stripe to provide it in their native sdks which is not the case. Hope this will help
