### ISSUE TITLE
Cannot create Stripe token from Apple Token

### ISSUE THREAD

**Issue by loicgeek** [flutter-stripe/flutter_stripe#1014]
**Describe the bug**
I was implementing Apple pay on IOS, but it fails when I want to create Stripe token using the Apple token

**To Reproduce**
1. Using the plugin https://pub.dev/packages/pay to render Apple pay button.
2. Click on the pay button.
3. With the payment result, try to create the Stripe token 
```
final token = await fstripe.Stripe.instance.createApplePayToken(paymentResult );
```
5. You will observe this error 
![image](https://user-images.githubusercontent.com/33604660/199719250-50690566-41d8-4fac-899e-39928819675e.png)

**Expected behavior**
Create Stripe token.

**Smartphone / tablet**
 - Device: Iphone 12
 - OS: IOS 16
 - Package version: ^5.1.0
 - Flutter version: 3.3.5

**Additional context**

**Comment by remonh87** [comment]
This is normally that something is wrong in your configuration. I would recommend checking the following: 
-  stripe logs in the dashboard. They normally give you a better overview
-   Also check https://github.com/flutter-stripe/flutter_stripe/blob/main/example/assets/apple_pay_payment_profile.json example. 
- Did you fullfill all requirements for setting up apple pay like:  creating payment processing  certificate from stripe + uploading it, adding merchant id.

**Comment by loicgeek** [comment]
Hi @remonh87 , thanks for your response.
I checked Stripe logs, I can notice this 

``
We couldn't fully decrypt your request. Please make sure you've uploaded your Apple Pay certificate at https://dashboard.stripe.com/settings/apple_pay. For help troubleshooting, see https://stripe.com/docs/apple-pay/apps#troubleshooting.
``

This is my apple profile
```
{
    "provider": "apple_pay",
    "data": {
      "merchantIdentifier": "merchantId",
      "displayName": "DisplayName",
      "merchantCapabilities": ["3DS", "debit", "credit"],
      "supportedNetworks": ["amex", "visa", "discover", "masterCard"],
      "countryCode": "US",
      "currencyCode": "USD",
      "requiredBillingContactFields": [],
      "requiredShippingContactFields": [],
      "shippingMethods": [
        
      ]
    }
  }
```

and yes I followed all steps for certificate, I will try again starting from Scratch.

**Comment by remonh87** [comment]
this is not a library problem but really related to the Stripe platform. I would recommend contacting support if the problem persist

**Comment by VStudio4125** [comment]
Hello
Did u manage to get a fix for this ?
I am facing the same issue.
Thanks

**Comment by Aarush-Acharya** [comment]
Hey @remonh87  I face the same issue please guide what is to be done

**Comment by Aarush-Acharya** [comment]
Hey @VStudio4125  did u manage to solve this issue ??
