### ISSUE TITLE
Flutter project with no kotlin folder!!!

### ISSUE THREAD

**Issue by vivekInfoskies** [flutter-stripe/flutter_stripe#1017]
Hi team. I am having flutter project with no kotlin folder inside it. In flutter stripe plugin it says i have to extend FlutterFragmentedActivity() in mainActivity.kt file which is not available for me. In this case what can  I do to use this plugin in my project?

**Comment by remonh87** [comment]
you can go to the java folder open `mainactivity.java` and extend Flutter fragment activitiy:  https://api.flutter.dev/javadoc/io/flutter/app/FlutterFragmentActivity.html.
