### ISSUE TITLE
Incorrect Payment Sheet Dark Mode Styling

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter-stripe/flutter_stripe#1021]
**Describe the bug**

The success indicator in the payment sheet uses the wrong icon color in dark mode.

<img width="306" alt="image" src="https://user-images.githubusercontent.com/19204050/201607287-7fb8e56a-298b-4f34-b378-db230ac54cc8.png">

In light mode, the button looks correct (white icon on green background):

<img width="202" alt="image" src="https://user-images.githubusercontent.com/19204050/201607407-5970c8cc-e352-43fd-bee6-2cb9ee85179c.png">

No matter which parameters are passed to the `appearance` parameter (either `colors` or `primaryButton`):

```dart
await stripe.initPaymentSheet(
    appearance: PaymentSheetAppearance(
      colors: PaymentSheetAppearanceColors(
        primary: Colors.black,
        background: Colors.white,
        componentBackground: Colors.white,
        componentBorder: const Color(0xfff2f2f2),
        componentDivider: const Color(0xfff2f2f2),
        componentText: Colors.black,
        primaryText: Colors.black,
        secondaryText: Colors.black.withOpacity(1 / 3),
        placeholderText: Colors.black.withOpacity(1 / 2),
        icon: Colors.black.withOpacity(1 / 2),
        error: const Color(0xffff3b30),
      ),
    ),
  ),
);
```

**Smartphone / tablet**
 - Device: iPhone 14 Pro Max
 - Package version: `6.0.0`
 - Flutter version: `3.3.8`

**Comment by remonh87** [comment]
Thanks for reporting but this is the standard design made by the Stripe sdk and there is nothing we can change as you can only change the idle appreance in this app. Feel free to raise an issue in the ios and android native repository's to make them fix it.
