### ISSUE TITLE
Pass timer to PaymentSheet

### ISSUE THREAD

**Issue by R70YNS** [flutter-stripe/flutter_stripe#1025]
**Is your feature request related to a problem? (please describe)**

Limited items require locking whilst the user inputs their payment details. This ensures the item cannot be sold to someone else as the user enters their input details. It's normal for a locking mechanism to last X amount of minutes, if the user hasn't input their details by the expiry time of the lock, the items goes back onto the market and is available for everyone.  

**Describe the solution you'd like**

I would like a datetime / unix timestamp parameter relevant to paymentSheet. This would be displayed within the paymentSheet and provide a visible countdown of the remaining time the window will remain open. It would also have a callback function onClose. 

**Describe alternatives you've considered**

The alternative seems to be to build an entirely custom widget.

**Comment by remonh87** [comment]
Hi I would recommend issuing an issue in: https://github.com/stripe/stripe-android. and https://github.com/stripe/stripe-ios . We have no control over the paymentsheet (for security reasons) and are reliant on what stripe provides us. 

That said what you can do is that when a payment intent is created you extend the timer a bit more (on the backend). Normally you can assume that when a user presses pay they made up their mind and accept the few times the payment fails .
