### ISSUE TITLE
CardFormField doesn't show validation error messages on iOS

### ISSUE THREAD

**Issue by omar-selo** [flutter-stripe/flutter_stripe#1027]
**Describe the bug**
On Android if a user enters invalid data into `CardFormField` a validation error message is printed under the field explaining the error. On iOS however the message seems to be cut off.

<img width="349" alt="Screenshot 2022-11-17 at 9 53 29 AM" src="https://user-images.githubusercontent.com/4087200/202377461-fb7c5e6f-c7ce-45b9-a9ea-f15bc690fd1d.png">

**Smartphone / tablet**
 - Device: iPhone 14 simulator
 - OS: iOS 16.1
 - Package version: 7.0.0
 - Flutter version 3.3.8

**Comment by jonasbark** [comment]
The flutter_stripe plugin cannot alter anything in the UI of the CardFormField itself. Your best bet is to create an issue at https://github.com/stripe/stripe-ios/

**Comment by omar-selo** [comment]
@jonasbark if you look closely at the image you can see that the validation message is actually there but it seems to be cut off. So I was wondering if somehow flutter stripe is cropping the native UI element resulting in this behavior?

**Comment by jonasbark** [comment]
Indeed we do - thanks for clearing it up
