### ISSUE TITLE
Setting countryCode on CardFormField doesn't do anything on iOS

### ISSUE THREAD

**Issue by omar-selo** [flutter-stripe/flutter_stripe#1028]
**Describe the bug**
On Android setting `countryCode` on `CardFormField` preselects the country in the form. On iOS however it doesn't do anything.

**Smartphone / tablet**
 - Device: iPhone 14 simulator
 - OS: iOS 16.1
 - Package version: 7.0.0
 - Flutter version 3.3.8

**Comment by remonh87** [comment]
You are right this is issue is related to a ticket on the Stripe iOS native library: https://github.com/stripe/stripe-ios/issues/1932. Summary: Cardform iOS is not on par with Android.

**Comment by remonh87** [comment]
Stripe will not be adding functionality to the form field and recommends everyone to use the paymentsheet. Closing this unfortunately. See official comment stripe: https://github.com/stripe/stripe-ios/issues/1932#issuecomment-1868445798
