### ISSUE TITLE
Sepa Debit not showing up when setup_future_usage: 'off_session' on PaymentSheet

### ISSUE THREAD

**Issue by geosebas** [flutter-stripe/flutter_stripe#1032]
**Describe the bug**
As long as you set `setup_future_usage: 'off_session'`  when creating your payment intent on backend, PaymentSheet will not show option for SepaDebit.

And saved SepaDebit PaymentMethod will never show up (even without `setup_future_usage: 'off_session'` )

Got the exactly the same problem when tryng to save for future usage sepa_debit with setupintent. Option will not show up

**To Reproduce**
on Flutter : 
```
await Stripe.instance.initPaymentSheet(
      paymentSheetParameters: SetupPaymentSheetParameters(
        merchantDisplayName: 'Padel bocage',
        paymentIntentClientSecret: paymentIntent,
        customerEphemeralKeySecret: ephemeralKey,
        customerId: customer,
        allowsDelayedPaymentMethods: true,
        style: themeManager.currentThemeMode,
      ),
    );
```

on server: 
```
  const paymentIntent = await stripe.paymentIntents.create({
    amount: amount,
    currency: 'eur',
    customer: customer.id,
    payment_method_types: ['card', 'sepa_debit'],
    setup_future_usage: 'off_session',
  });
```

**Expected behavior**
Saved sepa account will show up and you can create a new sepa payment method even with `setup_future_usage: 'off_session'`

**Smartphone / tablet**
 - Device: [Simulated Android API level 33]
 - OS: [Android Tiramisu]
 - Package version: [7.0.0]
 - Flutter version [3.3.8]

**Additional context**

**Comment by geosebas** [comment]
When trying to set up a PaymentSheet with Sepa Debit only, got this error on Flutter : 
```
 Payment method type 'card' is required.
 Accepted payment methods: ([sepa_debit]).
```

**Comment by geosebas** [comment]
Does anyone have any solutions to this ?

**Comment by jamesblasco** [comment]
Hi, currently the Payment Sheet only supports saving the payment method for cards:

<img width="725" alt="Screenshot 2022-12-10 at 18 49 44" src="https://user-images.githubusercontent.com/19904063/206868475-54d22d60-1ae0-41d2-8351-e7d441c03e48.png">

https://stripe.com/docs/payments/save-during-payment?platform=ios&ui=payment-sheet#add-server-endpoint

If this changes in the future we will add support for it
