### ISSUE TITLE
Missing "primaryButtonLabel" parameter to "initPaymentSheet()"

### ISSUE THREAD

**Issue by omar-selo** [flutter-stripe/flutter_stripe#1035]
**Describe the bug**
Looking at the [feature list of release 7](https://github.com/flutter-stripe/flutter_stripe/releases/tag/7.0.0). I see the following: 

> Added support for customizing the call to action button label in Payment Sheet by providing the primaryButtonLabel property to initPaymentSheet()

But I don't see `primaryButtonLabel` parameter option in `initPaymentSheet()` or `SetupPaymentSheetParameters`. Looking at the [diff](https://github.com/flutter-stripe/flutter_stripe/compare/stripe_platform_interface-v6.0.0...7.0.0) I can see that it was added to `stripe_ios` and `stripe_android` plugins but not to `stripe_platform_interface`.

**Comment by LazyBun** [comment]
+1, I'm having the same issue - was really stoked that this got added!
