### ISSUE TITLE
How to show popup after the payment is successful or cancelled on FLUTTER WEB

### ISSUE THREAD

**Issue by debjeetproso** [flutter-stripe/flutter_stripe#1037]
on my flutter web, I want to show a popup of my website when payment has been successful or failed 

'price': pd.priceId,
      'quantity': pd.quatity,
      'mode': 'payment',
      'line_items': [
        {
          'price_data': {
            'currency': 'usd',
            'product_data': {
              'name': 'flutter web',
            },
            'unit_amount': totalPrice,
          },
          'quantity': 1,
        },
      ],
       'success_url': 'http://localhost:5000/success_url',  //todo need live url
       'cancel_url': 'http://localhost:5000/cancel_url',   //todo need live url  });
       
       how can I added popup on success_url and cancel_url as they take only urls or there is other way to handle it ?

**Comment by debjeetproso** [comment]
this my url launcher code 

if (kIsWeb) {
            //open url in new tab

            launchUrl(Uri.parse(url));
          }

**Comment by jamesblasco** [comment]
Hi @debjeetproso,

If I understood well you launch a checkout session from your flutter app no?
The success/cancel url are used in the stripe checkout session page. So if the payment succeeds or is canceled the tab where the checkout is open will redirect to one of those urls. To open a popup there you can define a custom url in the MaterialApp that goes to the dialog you want to display.

Notice if you launch the session in a new tab, the previous tab won't be updated at all. The best way to do it is to redirect your active tab to the checkout session. If you still need to use multiple tabs, you would have to subscribe to your custom backend to detect when the payment is completed

**Comment by debjeetproso** [comment]
i have used shared pref for this
