### ISSUE TITLE
Sync with stripe sdk

### ISSUE THREAD

**Issue by remonh87** [flutter-stripe/flutter_stripe#104]
The sdk team of Stripe made an significant improvement that we should consider integrating.  https://github.com/stripe/stripe-react-native/pull/273 

We should plan for syncing with the latest updates

**Comment by thorsten-stripe** [comment]
There are a couple more things I'm working on for the v0.1.3 release later this week. Maybe wait for the sync until then?

**Comment by joknjokn** [comment]
Perfect - Thanks for the quick response.

**Comment by gocal** [comment]
Hi @remonh87 0.1.4 has been released, so do you have some expected timeline when these changed will be integrated ? [(](https://github.com/flutter-stripe/flutter_stripe/issues/131) specifically )

**Comment by remonh87** [comment]
We expect to ship a new version next week!

**Comment by SebghatYusuf** [comment]
Hi @remonh87, 
Any update, when will be the next release?

**Comment by jonasbark** [comment]
New version is released, so closing this issue

**Comment by joknjokn** [comment]
@jonasbark In the example in github I see ".createToken"-method in the legacy example. I assume that's the one to use, right? However, that function is not available from Stripe.instance in the new flutter_stripe 1.1.0 version.

Am I missing something?

**Comment by remonh87** [comment]
@joknjokn  it is part of the Stripe instance see: https://github.com/flutter-stripe/flutter_stripe/blob/e58bdadfb4e47b74f53d850e4ac98e955aabd770/packages/stripe/lib/src/stripe.dart#L146

**Comment by joknjokn** [comment]
@remonh87 , but it's not in the 1.1.0 version you released to pub.dev yesterday. I can see that you updated your dependency from 1.0.2 to 1.1.0 in you main branch an hour ago, despite releasing 1.1.0 yesterday. So I guess your 1.1.0-version in pub.dev is broken?

**Comment by joknjokn** [comment]
At least this looks like a package-problem to me, but I'm unsure. Android studio reports "The method 'createToken' isn't defined for the type 'Stripe'."

I have triple checked by pubspec.yaml, and did flutter clean and pub get multiple times, but it still can't find that function.

**Comment by jonasbark** [comment]
You can also run `flutter packages upgrade` and double-check your pubspec.lock file.
If you see one dependency being outdated you can upgrade it specifically by running `flutter packages upgrade stripe_platform_interface`

**Comment by joknjokn** [comment]
Sure, did all of that. I guess it was some Android Studio caching or similar, since a full reboot helped.
