### ISSUE TITLE
Update to newer react native stripe dependency

### ISSUE THREAD

**Issue by asaarnak** [flutter-stripe/flutter_stripe#1040]
To fix issue #1022 
https://github.com/stripe/stripe-react-native/blob/master/CHANGELOG.md#0210---2022-11-15
@remonh87

**Comment by remonh87** [comment]
We already fixed issue #1022 with stripe_android 2.0.1. Did you still have problems?

**Comment by asaarnak** [comment]
Oh, it was transitive dependency update. Seems ok now with "7.0.1" stripe_android.
