### ISSUE TITLE
CardFormField with billingDetails

### ISSUE THREAD

**Issue by isaacsuazo7** [flutter-stripe/flutter_stripe#1041]
A suggestion for improvement in CardFormField would be to add additional fields for the billingAddress (country, state, city, Street, etc), since in some cases (for example United States the United Kingdom) apart from the zip code the exact address of the card is also validated as Street Address and it is a limitation when creating payment methods through the sdk.
Thank you.

**Comment by remonh87** [comment]
You can also build an address validation yourself and supply it as billingdetails when confirming the paymentintent. As far as I know, it is only required to provide zipcode for US payments.
