### ISSUE TITLE
Buggy completion from suggestions/predictive text bar for postal code field

### ISSUE THREAD

**Issue by kcruzat** [flutter-stripe/flutter_stripe#1043]
**Describe the bug**
Using the CardFormField widget, filling in the postal code field with the predictive text bar on iOS is buggy. Sometimes it is filled and sometimes it is partially filled or the suggestion is not used. I'm not sure if it has something to do with a mask in the field as the behaviour doesn't seem to be consistent.

**To Reproduce**
1. Start entering text in the postal code field
2. Tap a suggestion on the predictive text bar
3. Observe the suggestion not being filled in correctly.

https://user-images.githubusercontent.com/35256345/204246948-46a170b3-94e7-4dca-9cb1-38254b854746.mp4

**Smartphone / tablet**
 - Device: iPhone X
 - OS: 15.5
 - Package version: 6.0.0
 - Flutter version 3.3.6

**Additional context**

**Comment by remonh87** [comment]
@jamesblasco  you know the most about iOS platformfields I think this looks like an issue in the flutter platformviews to me.
