### ISSUE TITLE
App Rejected Due To Outdated Google Pay Logo in Payment Sheet 

### ISSUE THREAD

**Issue by gspuzic** [flutter-stripe/flutter_stripe#1055]
**Describe the bug**
Trying to move through Google Pay review for my production app and received the following:

```
Hi,

We have an update on your recent Google Pay API integration submission.

Our brand guidelines for Android have recently been updated. The [Google Pay button](https://developers.google.com/pay/api/android/guides/brand-guidelines#payment-buttons) is now only available in one color and is rounded.  

Please make the appropriate updates, and re-submit your integration again through the Google Pay & Wallet Console. 

Note, the Google Pay button will need to be updated in your already active integrations as well, but those do not need to be resubmitted to the Google Pay & Wallet Console. 

Thank you for submitting your integration through the Google Pay & Wallet Console. It’s been a pleasure working with you.

```

Is there a way I can manually replace this image in my local build in the meantime?

**To Reproduce**
1. Create Android app with Google Pay with a payment sheet
2. Attempt to clear the Google Pay API review process to get app published

**Expected behavior**
Google Pay button to adhere to recent standards

**Smartphone / tablet**
 - Device: Andrdoid
 - OS: All
 - Package version:4.0.0
 - Flutter version 3.3.8

**Additional context**
None

**Comment by jonasbark** [comment]
you need to update flutter_stripe.

**Comment by gspuzic** [comment]
To what version? I looked at some other issues and they also have the same
img as me. Have you passed the Google pay review?
