### ISSUE TITLE
Missing PaymentMethodParams for other payment methods

### ISSUE THREAD

**Issue by albertus-stripe** [flutter-stripe/flutter_stripe#106]
Looking at `stripe_platform_interface/lib/src/models/payment_methods.dart`, seems like currently we are not having the `PaymentMethodParams` for these payment methods:
- OxxoParams
- Sofort
- SepaDebit
- AfterpayClearpay
- Eps
- AuBecsDebitParams
- FPX (created a PR for this)

We should create `PaymentMethodParams` for these payment methods following the React Native types declaration here:
https://github.com/stripe/stripe-react-native/blob/master/src/types/PaymentMethods.ts

**Comment by s-talkanova-fraiss** [comment]
Do you know approximately when the other missing PaymentMethodParams, or at least SepaDebit, get implemented?

**Comment by jonasbark** [comment]
SepaDebit and a lot more already exist: https://github.com/flutter-stripe/flutter_stripe/blob/main/packages/stripe_platform_interface/lib/src/models/payment_methods.dart#L35

**Comment by albertusdev** [comment]
@jonasbark ideally we should keep this in sync with https://github.com/stripe/stripe-react-native/blob/master/src/types/PaymentMethods.ts
