### ISSUE TITLE
Incorrect iOS build version in documentation

### ISSUE THREAD

**Issue by jaween** [flutter-stripe/flutter_stripe#1064]
**Describe the bug**
[Documentation for iOS says the minimum iOS version is 12.0](https://github.com/flutter-stripe/flutter_stripe/blob/main/README.md#ios). The minimum version is [actually 13.0](https://github.com/flutter-stripe/flutter_stripe/blob/ac1275055afa06b354f03e958ad3c466e6f76802/packages/stripe_ios/ios/stripe_ios.podspec#L25).

**To Reproduce**
1. Try updating pods with minimum iOS version set to 12.0
2. See the error:
```
[!] CocoaPods could not find compatible versions for pod "stripe_ios":
  In Podfile:
    stripe_ios (from `.symlinks/plugins/stripe_ios/ios`)

Specs satisfying the `stripe_ios (from `.symlinks/plugins/stripe_ios/ios`)` dependency were found, but they required a higher minimum deployment target.
```

**Expected behavior**
The pods should update.

**Package info**
 - OS: iOS
 - Package version: 7.0.0
 - Flutter version 3.3.10

**Additional context**
[See this line](https://github.com/flutter-stripe/flutter_stripe/blob/ac1275055afa06b354f03e958ad3c466e6f76802/packages/stripe_ios/ios/stripe_ios.podspec#L25) for the current minimum iOS version. It appears to have been updated [in this commit just over a month ago](https://github.com/flutter-stripe/flutter_stripe/commit/7866c4dbc0d9de177d8fc81a1380249b513dfe5e#).

**Comment by remonh87** [comment]
Thanks for bringing this to our attention. I will update the readme.

**Comment by MahmoudSalem94** [comment]
thank you.

**Comment by mselmanyildirim** [comment]
I was struggling to build for `ios 12` regarding the documentation, but turns out that the documentation should be updated. I created a [PR for the issue](https://github.com/flutter-stripe/flutter_stripe/pull/1100). Thanks
