### ISSUE TITLE
Google Pay throws OR_BIBED_01

### ISSUE THREAD

**Issue by bilalsammour** [flutter-stripe/flutter_stripe#1070]
**Describe the bug**
Google Pay throws OR_BIBED_01 without more info.

**To Reproduce**
1. Run the sample code in the example folder.
2. Use a real device or an emulator.
3. You will get a dialog error.

**Comment by remonh87** [comment]
are you using the test environment or the prod environment? Normally this issue happens when you are not using the test environment keys and do not have the approval from Google to use Google pay

**Comment by remonh87** [comment]
closed due to inactivity
