### ISSUE TITLE
ANDROID CRASH ON Stripe.instance.initPaymentSheet

### ISSUE THREAD

**Issue by alaindixon** [flutter-stripe/flutter_stripe#1073]
**Describe the bug**
When I use the method: Stripe.instance.initPaymentSheet
My APP crash

`        await stripe.Stripe.instance.initPaymentSheet(
          paymentSheetParameters: stripe.SetupPaymentSheetParameters(
            merchantDisplayName: _shopInfo!['stripe']['displayName'],
            customerId: user!.uid,
            paymentIntentClientSecret: paymentIntentData!['client_secret'],            
            style: ThemeMode.light,
            customerEphemeralKeySecret: paymentIntentData!['ephemeralKey'],
          ),
        );`

`D/AndroidRuntime(10651): Shutting down VM
E/AndroidRuntime(10651): FATAL EXCEPTION: main
E/AndroidRuntime(10651): Process: fr.adixon.kiosk, PID: 10651
E/AndroidRuntime(10651): java.lang.NoSuchMethodError: No direct method <init>(Ljava/lang/String;Lcom/stripe/android/paymentsheet/PaymentSheet$CustomerConfiguration;Lcom/stripe/android/paymentsheet/PaymentSheet$GooglePayConfiguration;Landroid/content/res/ColorStateList;Lcom/stripe/android/paymentsheet/PaymentSheet$BillingDetails;Lcom/stripe/android/paymentsheet/addresselement/AddressDetails;ZLcom/stripe/android/paymentsheet/PaymentSheet$Appearance;Ljava/lang/String;ILkotlin/jvm/internal/DefaultConstructorMarker;)V in class Lcom/stripe/android/paymentsheet/PaymentSheet$Configuration; or its super classes (declaration of 'com.stripe.android.paymentsheet.PaymentSheet$Configuration' appears in /data/app/fr.adixon.kiosk-u09huAO822bdcIDw1u6lZA==/base.apk!classes8.dex)`

**To Reproduce**
1 - Initiate the payment (CRASH)

**Expected behavior**
Display Payment Sheet

**Smartphone / tablet**
 - Device: OPPO CHP2185
 - OS: ANDROID 10
 - Package version: 7.0.0
 - Flutter version: 3.0.1 

**Additional context**
`E/AndroidRuntime(10651): 	at com.reactnativestripesdk.PaymentSheetFragment.onViewCreated(PaymentSheetFragment.kt:121)
E/AndroidRuntime(10651): 	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3128)
E/AndroidRuntime(10651): 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:552)
E/AndroidRuntime(10651): 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
E/AndroidRuntime(10651): 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
E/AndroidRuntime(10651): 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
E/AndroidRuntime(10651): 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
E/AndroidRuntime(10651): 	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
E/AndroidRuntime(10651): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime(10651): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime(10651): 	at android.os.Looper.loop(Looper.java:240)
E/AndroidRuntime(10651): 	at android.app.ActivityThread.main(ActivityThread.java:7829)
E/AndroidRuntime(10651): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(10651): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:512)
E/AndroidRuntime(10651): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1027)
I/Process (10651): Sending signal. PID: 10651 SIG: 9
Lost connection to device.
Exited`

**Comment by remonh87** [comment]
I cannot reproduce this at the moment can you check if this happens in our example app?

**Comment by alaindixon** [comment]
For some reasons, I have added the line below inside the gradle 
`implementation 'com.stripe:stripe-android:20.17.0'`  
This library makes my app crashed, sorry for the inconvenience.
