### ISSUE TITLE
Stripe Connect

### ISSUE THREAD

**Issue by ruhul080** [flutter-stripe/flutter_stripe#1076]
Hi,
I am using flutter_stripe module in one of my project. I need to use Stripe connect to charge a fee. Does your module support Stripe connect? If so can you provide an example how to use it? If not will you consider adding Stripe connect to your module.

Thanks

**Comment by remonh87** [comment]
What I understood from Stripe connect is that it uses payment links and the flow will be handled externally. See: https://stripe.com/docs/connect/collect-then-transfer-guide?platform=no-code .  Our sdk handles collection of payment information and this is not needed in the connect scenario so it works out of the box. Hope this answers your question

**Comment by ruhul080** [comment]
Thank you very much for your reply.
