### ISSUE TITLE
bug: cannot add web verison

### ISSUE THREAD

**Issue by ollydixon** [flutter-stripe/flutter_stripe#1077]
I'm using both the latest, as the documentation doesn't tell us what to use.

```
  flutter_stripe: ^7.0.0
  flutter_stripe_web: ^2.1.0
```

Because flutter_stripe_web >=2.0.0 depends on stripe_platform_interface ^6.0.0 and flutter_stripe 7.0.0 depends on stripe_platform_interface ^7.0.0, flutter_stripe_web >=2.0.0 is incompatible with flutter_stripe 7.0.0.
And because no versions of flutter_stripe match >7.0.0 <8.0.0, flutter_stripe_web >=2.0.0 is incompatible with flutter_stripe ^7.0.0.
So, because vegiano depends on both flutter_stripe ^7.0.0 and flutter_stripe_web ^2.1.0, version solving failed.
pub get failed (1; So, because vegiano depends on both flutter_stripe ^7.0.0 and flutter_stripe_web ^2.1.0, version solving failed.)
exit code 1

**Comment by sleewok** [comment]
I just encountered the same issue. Can we please get this fixed?

**Comment by remonh87** [comment]
should be fixed now in version 2.1.1
