### ISSUE TITLE
Can't run on platform :ios, '11.0' 

### ISSUE THREAD

**Issue by aris-1** [flutter-stripe/flutter_stripe#1078]
I used to be able to run on IOS 11, but now I get the error 
[!] CocoaPods could not find compatible versions for pod "stripe_ios":
  In Podfile:
    stripe_ios (from `.symlinks/plugins/stripe_ios/ios`)

Specs satisfying the `stripe_ios (from `.symlinks/plugins/stripe_ios/ios`)` dependency were found, but they required a higher minimum deployment target.

I don't know if this is because I tried using 
flutter_stripe: ^7.0.0
and when I realized it needed IOS 13 I tried  the one that was working before 
flutter_stripe: ^2.4.0
but I keep on getting the above error.

Every time I do a clean run with following commands:
rm pubspec.lock
flutter clean
flutter pub get
pod cache clean --all
cd ios
rm -rf Pods Podfile.lock .symlinks Flutter/Flutter.framework Flutter/Flutter.po$
pod repo update
pod install

**Comment by remonh87** [comment]
We support versions of iOS 12 and higher. See: https://github.com/flutter-stripe/flutter_stripe#ios . This is a requirement made by the Stripe iOS sdk. I wouldn't be too affraid to bump your min iOS version to 12 as most people will have an updated iPhone

**Comment by manandhar-aarya** [comment]
Hello, I have minimum iOS version as 12 but i still keep getting this error: 
_Specs satisfying the `stripe_ios (from `.symlinks/plugins/stripe_ios/ios`)` dependency were found, but they required a higher minimum deployment target._

I have the minimum version in the Podfile like so:
platform :ios, '12.0'

And as a minimum deployment in xcode:

<img width="633" alt="Screenshot 2023-02-07 at 10 53 01 AM" src="https://user-images.githubusercontent.com/34571548/217211290-34531ef2-635f-43dd-b23b-21c2f63cdc2a.png">

Only if i set the minimum to 13 it works.
