### ISSUE TITLE
kotlin.UninitializedPropertyAccessException: lateinit property stripe has not been initialized at com.reactnativestripesdk.StripeSdkModule$mActivityEventListener$1.onActivityResult(StripeSdkModule.kt:45)

### ISSUE THREAD

**Issue by bringbackthedog** [flutter-stripe/flutter_stripe#108]
**Describe the bug**
App crashes after user logs in. I'm using Google login via Firebase Auth. 

**Smartphone / tablet**
 - Device: Android Nexus 5X emulator
 - OS: Android 11
 - Package version:  1.0.1+3
 - Flutter version 2.2.0.
<details>
<summary> logs </summary>
<br>

    D/AndroidRuntime(14020): Shutting down VM
    E/AndroidRuntime(14020): FATAL EXCEPTION: main
    E/AndroidRuntime(14020): Process: ca.neolabs.swale, PID: 14020
    E/AndroidRuntime(14020): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=53293, result=-1, data=Intent { (has extras) }} to activity {ca.neolabs.swale/ca.neolabs.swale.MainActivity}: kotlin.UninitializedPropertyAccessException: lateinit property stripe has not been initialized
    E/AndroidRuntime(14020): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5015)
    E/AndroidRuntime(14020): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5056)
    E/AndroidRuntime(14020): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
    E/AndroidRuntime(14020): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
    E/AndroidRuntime(14020): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
    E/AndroidRuntime(14020): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
    E/AndroidRuntime(14020): 	at android.os.Handler.dispatchMessage(Handler.java:106)
    E/AndroidRuntime(14020): 	at android.os.Looper.loop(Looper.java:223)
    E/AndroidRuntime(14020): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
    E/AndroidRuntime(14020): 	at java.lang.reflect.Method.invoke(Native Method)
    E/AndroidRuntime(14020): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
    E/AndroidRuntime(14020): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
    E/AndroidRuntime(14020): Caused by: kotlin.UninitializedPropertyAccessException: lateinit property stripe has not been initialized
    E/AndroidRuntime(14020): 	at com.reactnativestripesdk.StripeSdkModule$mActivityEventListener$1.onActivityResult(StripeSdkModule.kt:45)
    E/AndroidRuntime(14020): 	at com.facebook.react.bridge.BaseActivityEventListener.onActivityResult(BaseActivityEventListener.kt:15)
    E/AndroidRuntime(14020): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:739)
    E/AndroidRuntime(14020): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:426)
    E/AndroidRuntime(14020): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:677)
    E/AndroidRuntime(14020): 	at io.flutter.embedding.android.FlutterFragment.onActivityResult(FlutterFragment.java:769)
    E/AndroidRuntime(14020): 	at io.flutter.embedding.android.FlutterFragmentActivity.onActivityResult(FlutterFragmentActivity.java:509)
    E/AndroidRuntime(14020): 	at android.app.Activity.dispatchActivityResult(Activity.java:8310)
    E/AndroidRuntime(14020): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5008)
    E/AndroidRuntime(14020): 	... 11 more
    I/Process (14020): Sending signal. PID: 14020 SIG: 9
    Lost connection to device.

</details>

**Comment by jonasbark** [comment]
See https://github.com/flutter-stripe/flutter_stripe/issues/101#issuecomment-851631194
