### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method dangerouslyUpdateCardDetails on channel flutter.stripe/card_field/0)

### ISSUE THREAD

**Issue by nzkn** [flutter-stripe/flutter_stripe#1083]
I can't test CardField - updating cardController.details throws:
Unhandled Exception: MissingPluginException(No implementation found for method dangerouslyUpdateCardDetails on channel flutter.stripe/card_field/0).
I see that this [CardField test is commented out in your integration_tests](https://github.com/flutter-stripe/flutter_stripe/blob/main/example/integration_test/card_field_test.dart). I am trying to test on iPhone 14 simulator, latest version of ios.

**Comment by nzkn** [comment]
Setting initialDetails for the CardEditController doesn't work too, so there is no way to test adding card at the moment.

**Comment by jonasbark** [comment]
@remonh87 can you have a look when you get the chance? `dangerouslyUpdateCardDetails` should indeed not be called on the platform view method channel, but on the main Stripe.platform method channel.
