### ISSUE TITLE
Create a Sofort payment

### ISSUE THREAD

**Issue by JethroG** [flutter-stripe/flutter_stripe#1084]
I create a payment through sofort, ideal, pass the specified parameters and every time I get an error-
Error from Stripe: Invalid Payment Intent client secret: src_client_secret_**********************

final paymentIntent =  await Stripe.instance.confirmPayment(
        paymentIntentClientSecret: clientSecret,
        data: PaymentMethodParams.sofort(
          paymentMethodData: PaymentMethodDataSofort(country: 'de'),
        ),
      );
clientSecret-the key is generated without any problems

payment by card is fine

What am I doing wrong?

I am using the latest versions of the libraries

**Comment by remonh87** [comment]
I did test it for android and could create a sofort payment without issues. Did you happen inject the correct secret coming from the backend? Also check in the stripe dashboard if the payment is correct and there are no events. If this doesn't help I would recommend contacting stripe helpdesk.

**Comment by JethroG** [comment]
please show what response you get when you create a payment intent

**Comment by remonh87** [comment]
you can run our example app I just have integrate an example

**Comment by JethroG** [comment]
In order to test, do I have to start a test server, because I send requests to my own server to generate a payment intent?
