### ISSUE TITLE
UPI for India

### ISSUE THREAD

**Issue by davidjeba** [flutter-stripe/flutter_stripe#1087]
I Think i have to use RazorPay for India and Stripe for International.

If Stripe can add UPI support to enable payments via Google Pay[Not Wallet] Amazon Pay, PhonePe, PayTm, etc
it would be very helpful.

![image](https://user-images.githubusercontent.com/70262709/212256784-0489d05c-645a-4fd4-9f69-29438457d1bf.png)

**Comment by remonh87** [comment]
@davidjeba can you explain a bit more what is missing?  Stripe supports upi you can create a UPI payment through this SDK.

**Comment by davidjeba** [comment]
UPI and Wallets are different
Google Pay has both Wallet [for International} and UPI [For India]

Razorpay has clear UPI section
https://razorpay.com/upi/

I could not find similar UPI section in Stripe India

**Comment by remonh87** [comment]
you can create a payment intent or payment method  https://stripe.com/docs/js/payment_methods/create_payment_method and use confirm payment intent to collect the customer data. Also check with stripe support they can help you out.

Our library at least supports this use case :)
