### ISSUE TITLE
Installation  failed

### ISSUE THREAD

**Issue by JethroG** [flutter-stripe/flutter_stripe#1093]
Error

`
Running "flutter pub get" in...                         
Because flutter_stripe >=7.0.0 depends on stripe_ios ^7.0.1 which doesn't match any versions, flutter_stripe >=7.0.0 is forbidden.
So, because depends on flutter_stripe ^7.0.0, version solving failed.
pub get failed (1; So, because depends on flutter_stripe ^7.0.0, version solving failed.)
Process finished with exit code 1`

Help me pls, I have no more options why the library won't install.
The only option when I can install the library is if I use
flutter_stripe: any , accordingly, I don't really want to use 4.0.0.

I repeatedly performed all possible operations for cleaning the cache, re-establishing the library

P.S. now  Today, I cannot import the 4th version of the library

```
Because no versions of flutter_stripe match 4.0.0 and no versions of flutter_stripe match >4.0.0 <5.0.0, flutter_stripe ^4.0.0 is forbidden.
So, because depends on flutter_stripe ^4.0.0, version solving failed.
Running "flutter pub get" in...                                 
pub get failed (1; So, because depends on flutter_stripe ^4.0.0, version solving failed.)
```

`
environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_native_splash: ^2.1.6

  flutter_svg: ^1.0.1

  form_field_validator: ^1.0.1

  http: ^0.13.4

  device_preview: ^1.0.0

  intl: ^0.17.0

  flutter_rating_bar: ^4.0.0

  shared_preferences: ^2.0.8

  web_socket_channel: ^2.1.0

  flutter_native_timezone: ^2.0.0

  flutter_launch: ^0.3.0

  step_progress_indicator: ^1.0.2

  flutter_local_notifications: ^9.5.2

  rxdart: ^0.27.2

  flutter_launcher_icons: ^0.9.2

  uni_links: ^0.5.1

  connectivity_plus: ^2.3.3

  url_launcher: ^6.1.3

  sign_in_with_apple: ^4.0.0

  google_sign_in: ^5.3.3

  flutter_secure_storage: ^5.0.2

  flutter_facebook_auth: ^4.3.4+2

  firebase_dynamic_links: ^4.2.6

  firebase_core: ^1.20.0

  get: ^4.1.4

  firebase_core_platform_interface: ^4.4.3

  firebase_messaging: ^11.4.4

  app_tracking_transparency: ^2.0.2+4

  intl_phone_field: ^3.1.0

  pin_code_fields: ^7.4.0

  dio: ^4.0.6

  image_picker: ^0.8.5+3

  uuid: 3.0.6

  google_place: ^0.4.7

  flutter_dotenv: ^5.0.2

  google_maps_flutter: ^2.1.12

  full_screen_image: ^1.0.2

  photo_view: ^0.14.0

  package_info_plus: ^3.0.0

  equatable: ^2.0.5

  flutter_bloc: ^8.1.1

  html: ^0.15.1

  new_version_plus: ^0.0.4

  pay: ^1.0.10

  font_awesome_flutter: ^9.2.0

  platform: ^3.0.0

  flutter_stripe: ^7.0.0`

**Comment by zinchenko1** [comment]
Hi there, I also have the same trouble, after when I tried update libs - I can't install "flutter_stripe", I can install only old version, then the situation repeats - now I'm currently on v5

soon I will run out of attempts 😅

**Comment by JethroG** [comment]
I have been trying to install version 7.0.0 for 2 days, now I already have 3.3.0 in the project, now even 4.0.0 does not want to install

**Comment by jonasbark** [comment]
Can you provide a reproducible example?

> flutter_stripe >=7.0.0 depends on stripe_ios ^7.0.1 

That part doesn't make sense. flutter_stripe does not depend on stripe_ios 7.0.1 but on 7.0.1.

**Comment by jonasbark** [comment]
Closing this due to lack of response
