### ISSUE TITLE
Incorrect comment text for customer property on SetupIntent

### ISSUE THREAD

**Issue by PaulZaczkowski** [flutter-stripe/flutter_stripe#1095]
https://github.com/flutter-stripe/flutter_stripe/blob/f4e03def3573c72cb24e2df120adce7ff22cd3e7/packages/stripe_js/lib/src/api/setup_intents/setup_intent.dart#L109

This is using the comment for the client_secret. Should likely read (to match stripe docs):

```dart
// ID of the Customer this SetupIntent belongs to, if one exists.
// If present, the SetupIntent’s payment method will be attached to 
// the Customer on successful setup. Payment methods attached
// to other Customers cannot be used with this SetupIntent.
```

**Comment by remonh87** [comment]
Thanks for addressing this . I updated the comment and it will be fixed in the next released.
