### ISSUE TITLE
Apple Pay Not Working with Pay and Flutter Stripe Packages

### ISSUE THREAD

**Issue by VStudio4125** [flutter-stripe/flutter_stripe#1101]
So I have been stuck around with getting apple pay to work.... I have followed all the setup with stripe needed and my card payments work fine. Now i am using the pay package to show the ApplePayButton and on payment result i am getting the complete map object. I try to make the token from it using flutter stripe method and then create a payment intent and lastly use the intent secret and token id to process the payment on stripe but i cant get it to work.
Here is the code which seems to be written fine.

ApplePayButton(
        paymentConfigurationAsset: 'applepay.json',
        paymentItems: _paymentItems,
        style: ApplePayButtonStyle.black,
        type: ApplePayButtonType.buy,
        width: 200,
        height: 50,
        onPaymentResult: (value) {
              final token = await Stripe.instance.createApplePayToken(value);
              final params = PaymentMethodParams.cardFromToken(
                paymentMethodData: PaymentMethodDataCardFromToken(
                  token: token.id,
               ) );
              paymentIntentData = await createPaymentIntent("3", 'AED');
              await Stripe.instance.confirmPayment(paymentIntentData!['client_secret'], params);
        },
        onError: (error) {
          print(error);
        },
        loadingIndicator: const Center(
          child: CircularProgressIndicator(),
        ),
      ),

Any help please.

**Comment by remonh87** [comment]
can you give me context? Does Stripe give you some error messages?
