### ISSUE TITLE
iOS App Crash on After await Stripe.instance.handleNextAction("PaymentIntentValue")

### ISSUE THREAD

**Issue by DharmbirChoudhary** [flutter-stripe/flutter_stripe#1107]
After hitting 
`await Stripe.instance.handleNextAction(paymentIntentSecret) `getting crashed on iOS app on this file

`StripePayments/STPPaymentHandler.swift:325: `Assertion failed: Calling completion with invalid state

I'm using latest stripe sdk 
`flutter_stripe: ^8.0.0+1`

And I tried paymentsheet for the Sepa Debit payment so just want to confirm payment details using `handleNextAction`but suddenly crashed on this line. 

Your help will be appreciated.

Thanks

Code Sample

```
await Stripe.instance.initPaymentSheet(
        paymentSheetParameters: SetupPaymentSheetParameters(
          allowsDelayedPaymentMethods: true,
          customFlow: true,
          merchantDisplayName: 'Test',
          paymentIntentClientSecret: data['paymentIntent'],
          customerEphemeralKeySecret: data['ephemeralKey'],
          customerId: data['customer'],
          style: ThemeMode.light,
        ),
      );

await Stripe.instance.presentPaymentSheet();

await Stripe.instance.confirmPaymentSheetPayment();

var paymentData = await Stripe.instance.handleNextAction(paymentIntentSecret);// crashed here
```

**Comment by remonh87** [comment]
@DharmbirChoudhary  thanks for reporting can you give me an example of the test data you use for sepa debit? I was not able to reproduce it with version 9.0.0. Maybe can you also try to upgrade and run it again?
