### ISSUE TITLE
Cannot change aubecs form text color to black on android but works on iOS

### ISSUE THREAD

**Issue by kean-fetchpet** [flutter-stripe/flutter_stripe#1108]
**Describe the bug**
The AubecsFormField text color does not change to dark color on android but it does change on iOS given that the code used for both is the same. 

**To Reproduce**
Below is the code to build the form. 
```
AubecsFormField(
      height: 500,
      controller: AubecsEditFormController(),
      companyName: 'name',
      style: AubecsFormStyle(
        borderWidth: 1,
        borderRadius:10,
        fontSize: 15,
        backgroundColor: Colors.white,
        textColor: Colors.black,
        borderColor: Colors.black,
        placeholderColor: Colors.black,
      ),
    );
```

**Expected behavior**
I expect that when it is light mode, the text would be dark which is what happened on iOS but not on android. 

**Smartphone / tablet**
 - Device: Pixel 3XL
 - OS: Android 12
 - Package version: 8.0.0+1
 - Flutter version 3.0.5

**Additional context**
I have screenshots of android and ios of the form. 
Android
![image](https://user-images.githubusercontent.com/116161269/216948995-3fe65b89-55a2-4f11-ae23-e1c723d01fc9.png)

iOS
![image](https://user-images.githubusercontent.com/116161269/216949074-9d0e4289-b93b-4507-bc52-3e377f3e187d.png)

**Comment by remonh87** [comment]
this is intended behavior if you customise the appearance it will override the default behavior. It is curious that on iOS it changes. As work around I would check if darkmode is enabled and provide the proper config.

```dart
    final isDark = Theme.of(context).brightness == Brightness.dark;
    AubecsFormField(
          controller: _controller,
          style: AubecsFormStyle(
            textColor: isDark? Colors.white: Colors.black,
);
```
