### ISSUE TITLE
`8.0.0` breaks Apple Pay setup intent

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter-stripe/flutter_stripe#1110]
Previously, with version `7.0.0` of the `flutter_stripe` plugin, the following snippet worked without any issues to confirm a **setup intent** using Apple Pay:

```dart
Stripe.publishableKey = intent.publishableKey;
await stripe.presentApplePay(
  params: ApplePayPresentParams(
    cartItems: [
      ApplePayCartSummaryItem.immediate(
        label: 'Example',
        amount: '0.00',
      ),
    ],
    country: 'DE',
    currency: 'EUR',
  ),
);

await stripe.confirmApplePayPayment(intent.clientSecret);
```

After **updating** to version `8.0.0` and updating the snippet to support the breaking changes, the code looks like this:

```dart
Stripe.publishableKey = intent.publishableKey;
final params = PlatformPayConfirmParams.applePay(
  applePay: ApplePayParams(
    cartItems: [
      ApplePayCartSummaryItem.immediate(
        label: 'Example',
        amount: '0.00',
      ),
    ],
    merchantCountryCode: 'DE',
    currencyCode: 'EUR',
  ),
);
await stripe.confirmPlatformPaySetupIntent(
  clientSecret: intent.clientSecret,
  confirmParams: params,
);
```

This should work the same way as it previously did, however, it _always_ fails.

## Bug

The bug looks like this:

1. The Apple Pay sheet is still presented properly ("Pay Example €0.00").
2. After e.g. paying with passcode, the sheet is stuck at "Processing Payment" for ~30 seconds.
3. Then the function fails with:

```
StripeException(error: LocalizedErrorMessage(code: FailureCode.Canceled, localizedMessage: The payment has been canceled, message: The payment has been canceled, stripeErrorCode: null, declineCode: null, type: null))
```

Even though the user did not cancel the payment and the same setup intent worked properly on the same device with `flutter_stripe: 7.0.0`.

**Comment by creativecreatorormaybenot** [comment]
Note that with the same setup, **payment** intents (`confirmPlatformPayPaymentIntent`) do still work.

cc @remonh87 @jonasbark

**Comment by remonh87** [comment]
This is related to: https://github.com/stripe/stripe-react-native/pull/1266 which is fixed in a new release of react native. We will take this along in the next release. As work around you still can use the old one.

**Comment by creativecreatorormaybenot** [comment]
Thanks for the quick response @remonh87. As I see that the fix has been merged upstream, is there any way for me to already integrate this manually?

**Comment by remonh87** [comment]
Fixed in version 9.0.0

**Comment by creativecreatorormaybenot** [comment]
🫶

**Comment by congfandi** [comment]
> Fixed in version 9.0.0

Iam using v 9.2.0 still facing this issue

**Comment by remonh87** [comment]
are you also using stripe iOS v9.2.0 and make sure you update cocoa pods by running `pod update`.

**Comment by congfandi** [comment]
> are you also using stripe iOS v9.2.0 and make sure you update cocoa pods by running `pod update`.

Thank you for the quick response @remonh87 . its fix now. but i will create new issue. Hope will get answer from you.
