### ISSUE TITLE
WHEN I AM TRYING TO PAY IN DOLLAR FROM INDIA IT OIS ASKING CUSTOMER NAME AND ADDRESS

### ISSUE THREAD

**Issue by badshamasala** [flutter-stripe/flutter_stripe#1114]
**Describe the bug**

**To Reproduce**
1. Entering number 123-456-789 into the cardfield.
2. Tapping the confirm button.
3. Observe a failure with exception (including the part of the stack trace, belonging to this package) …

**Expected behavior**

**Smartphone / tablet**
 - Device: [e.g. iPhone X]
 - OS: [e.g. iOS 13, Android 10]
 - Package version: [e.g. 1.0.0]
 - Flutter version [e.g. 2.0.0.]

**Additional context**

**Comment by remonh87** [comment]
please comply to the issue template. Entering 123456789 is not a valid card number so it makes sense that it  fails. Use the cards from https://stripe.com/docs/testing
