### ISSUE TITLE
AppCompatActivity support

### ISSUE THREAD

**Issue by adricanedo** [flutter-stripe/flutter_stripe#1116]
We have a [native module, compatible with Flutter](https://github.com/situmtech/flutter-wayfinding), that requires an AppCompatActivity (androidx.appcompat.app.AppCompatActivity). We’ve seen that Stripe requires a FlutterFragmentActivity, which in turn requires native modules to be implemented as FragmentActivity. Therefore, our module can’t be use in apps that use Stripe. 

The Stripe plugin forces the use of FlutterFragmentActivity at [StripeAndroidPlugin.kt](https://github.com/flutter-stripe/flutter_stripe/blob/main/packages/stripe_android/android/src/main/kotlin/com/flutter/stripe/StripeAndroidPlugin.kt#L217). We propose to make that check more flexible so that it checks if it is a FragmentActivity (from Androidx): 
```
@SuppressLint("RestrictedApi")  
override fun onAttachedToActivity(binding: ActivityPluginBinding) {  
   when {  
       binding.activity !is FragmentActivity -> {  
           initializationError =  
               "Your Main Activity ${binding.activity.javaClass} is not a subclass of FragmentActivity."  
       } 

   …  

}
```

This will maintain the current behavior as FlutterFragmentActivity is a subclass of FragmentActivity. It will also enable using AppCompatActivity, [another subclass of FragmentActivity](https://developer.android.com/reference/androidx/appcompat/app/AppCompatActivity). It would also be compatible with [what’s said in this file](https://github.com/flutter-stripe/flutter_stripe/blob/main/packages/stripe_android/android/src/main/kotlin/com/flutter/stripe/StripeSdkModuleExtensions.kt).   

[In this hierarchy ](https://docs.flutter.dev/development/add-to-app/android/add-flutter-fragment) we can see that FlutterFragmentActivity inherits from FragmentActivity
![image](https://user-images.githubusercontent.com/16361322/219095053-e1464c8e-67e6-4385-b0d9-8b08b185ad98.png)

[Here](https://developer.android.com/reference/androidx/appcompat/app/AppCompatActivity), we see that AppCompatActivity inherits from FragmentActivity
![image](https://user-images.githubusercontent.com/16361322/219095434-1642ea3f-f716-47aa-a0ee-468f229785bf.png)

We were wondering if this would be a change that could be done on Stripe Flutter plugin to ensure Flutter compatibility with all kinds of native modules. Thanks a lot and congratulations for the great work!

**Comment by jonasbark** [comment]
I don't think this is possible because stripe_android relies on the propagation of e.g. the activity results. But feel free to fork it and try it out!

**Comment by remonh87** [comment]
closing this as out of scope
