### ISSUE TITLE
Google pay and Apple pay with Web

### ISSUE THREAD

**Issue by anovis** [flutter-stripe/flutter_stripe#1122]
I was having trouble finding information on what flutter_stripe_web currently supports. Specifically I was wondering if google pay and apple web is supported with `flutter_stripe_web`. 

I tried a basic example, but got into some error related to `userCanPay` with google pay in browser, but I wasn't sure if I was missing something or if it wasn't supported yet.

**Comment by jonasbark** [comment]
No, neither is supported currently. You may want to try Stripe Checkout or Payment Links instead.

**Comment by jamesblasco** [comment]
Hi @zzxoto, could you clarify if this integration made with the PaymentElement?

**Comment by CleverUnderDog** [comment]
Hi, as far as I understand, according to Stripe's [js-docs](https://stripe.com/docs/js/elements_object/create_payment_element#payment_element_create-options-wallets) the wallets options has to be set to `{"googlePay": "auto", "applePay": "auto"}`. Afterwards it should work out of the box.

After checking the source code of this repository I don't see any possibility to change this through the current api. I think the following class would need to be extended: [PaymentElementOptions](https://github.com/flutter-stripe/flutter_stripe/blob/main/packages/stripe_js/lib/src/api/elements/payment_element_options.dart#L42)

Implementing this feature would pretty much match the PaymentSheet functionality.

**Comment by remonh87** [comment]
fix is released
