### ISSUE TITLE
Add createGooglePayToken

### ISSUE THREAD

**Issue by davidoort** [flutter-stripe/flutter_stripe#1125]
**Is your feature request related to a problem? (please describe)**
I would like to see a way to get a stripe_token from a Google Pay payment method, similar to what is possible with [createApplePayToken](https://pub.dev/documentation/flutter_stripe/latest/flutter_stripe/Stripe/createApplePayToken.html)

**Describe the solution you'd like**
I would like to see a createGooglePayToken method similar to [createApplePayToken](https://pub.dev/documentation/flutter_stripe/latest/flutter_stripe/Stripe/createApplePayToken.html). 

**Describe alternatives you've considered**
Currently I think this is possible through:
```
final token =
    paymentResult['paymentMethodData']['tokenizationData']['token'];
final tokenJson = Map.castFrom(json.decode(token));
debugPrint(tokenJson.toString());
```
but I'm not sure. If this functionally does the same feel free to close this issue.

**Comment by davidoort** [comment]
I started a discussion about getting tokens from Payment Sheets https://github.com/flutter-stripe/flutter_stripe/discussions/1124 which would also resolve this issue as it would remove the need to manually put together methods for getting payment tokens from card, apple pay and google pay

**Comment by jamesblasco** [comment]
While the Stripe iOS SDK allows to create a token from an apple pay payment [(ref)](https://stripe.dev/stripe-ios/stripe/documentation/stripe/stpapiclient/createtoken(with:completion:)), the Android SDK does not support the same for Google Pay [(ref)](https://stripe.dev/stripe-ios/stripe/documentation/stripe/stpapiclient/createtoken(with:completion:)).

Same from supporting tokens on Payment Sheets, it is something that the native sdks do not support at the moment and we, as a third-party library, do not have control over it. You can propose this new features to the Stripe team directly 
https://discord.gg/stripe
