### ISSUE TITLE
Support Stripe Connect for charging and payouts to Flutter User Connected Accounts

### ISSUE THREAD

**Issue by sirwes** [flutter-stripe/flutter_stripe#1126]
I'd love to use the Stripe Connect as described here
https://dashboard.stripe.com/connect/accounts/overview

My use case being that I'll have some users that I will charge and later earn money. 

Please point me in the right direction with instructions on how to implement if this is already made for Flutter. Currently, I only see this being available for Web (and for native apps).

**Comment by jonasbark** [comment]
>  I only see this being available for Web (and for native apps).

What else is there that you need?

Please check the existing tickets regarding Stripe Connect:
https://github.com/flutter-stripe/flutter_stripe/issues?q=stripe+connect

**Comment by sirwes** [comment]
It'd be nice to just use the flutter stripe sdk so users can have an in-app experience rather than me pushing them to web to create a connect account and then hoping that it routes the user back to the flutter app correctly

**Comment by sirwes** [comment]
I suppose this is a duplicate of this https://github.com/flutter-stripe/flutter_stripe/issues/679
