### ISSUE TITLE
confirmPlatformPaySetupIntent with PlatformPayConfirmParams.googlePay always displays zero amount

### ISSUE THREAD

**Issue by DavidEcclesPH** [flutter-stripe/flutter_stripe#1127]
When confirming a setup intent with google pay confirm params, no matter what int I use in the amount parameter the amount is always shown as £0 on the presented google pay sheet.  The payment appears in Stripe as succeeded if i click pay and shows the correct amount, however I worry that users will NOT click pay to complete the payment when the amount to pay shows £0

I am using the method like this:

```
Stripe.instance.confirmPlatformPaySetupIntent(
      clientSecret: secret,
      confirmParams: PlatformPayConfirmParams.googlePay(
        googlePay: GooglePayParams(
          merchantCountryCode: checkout.country,
          currencyCode: checkout.currency,
          amount: checkout.amount,
          merchantName: checkout.description,
          testEnv: kGooglePayTestEnv,
        ),
      ),
    );
```

confirmPlatformPayPaymentIntent works as expected and shows the correct amount to be paid using the same parameters.

**Comment by jamesblasco** [comment]
The param  `amount` is only used by `createPlatformPayPaymentMethod` when creating a new payment method with google pay. We should definitely add this information to the documentation.

- For `PaymentIntent` the recommended way is to set the amount in the server when creating the payment intent and pass only the client secret. 

- For `SetupIntent` I might be wrong, the goal is to set up and save customer payment information for future payments. So not amount is charged when confirming a setup intent.

If you want to create a payment and save customer payment information at the same time you should use `PaymentIntent` with the setup future usage param
https://stripe.com/docs/api/payment_intents/object#payment_intent_object-setup_future_usage

**Comment by DavidEcclesPH** [comment]
hi @jamesblasco, sorry I am just coming back to this now. Yes setupIntent is to create a subscription eg. £10 every month. This works completely correctly via apple pay, however when using google pay the amount is not shown (as it is on apple pay) so this is still an issue on v9.2.0

**Comment by DavidEcclesPH** [comment]
@remonh87 @jamesblasco here is the UI for paying for the same item (a £1 a week subscription) on both platforms:
iOS correctly shows the amount, google pay still shows £0 which users will be unlikely to click!
![Image from iOS](https://github.com/flutter-stripe/flutter_stripe/assets/94359534/20586250-590f-499b-9873-3f76602cbe88)
![IMG_6387](https://github.com/flutter-stripe/flutter_stripe/assets/94359534/1d8190ac-3da1-4034-9f65-19e2564d183b)
