### ISSUE TITLE
presentPaymentSheet on iOS: Localization issues

### ISSUE THREAD

**Issue by LaurentHumbert** [flutter-stripe/flutter_stripe#1138]
Hi there,

On iOS, the "Scan card" icon and text get squashed if the translation to the "Card information" label is a bit too long and/or if the default text size for the iPhone is increased.

Translated "Card number" label is also problematic and gets hidden by the cards icons.

Configuration:
iPhone 11
Flutter 3.7.3
Stripe plugin: 8.0.0+1

Thanks,
![IMG_8360673A9DF7-1](https://user-images.githubusercontent.com/4736208/221538505-779728ba-a9ad-42d2-a48b-25fc2d1df0bb.jpeg)

**Comment by jonasbark** [comment]
Hi! Our plugin does not have control over this - please open a bug in https://github.com/stripe/stripe-ios instead :)
