### ISSUE TITLE
Payment sheet always renders in dark mode

### ISSUE THREAD

**Issue by amandoraya1995** [flutter-stripe/flutter_stripe#1141]
**Describe the bug**
No matter if you change the apps theme, or pass style property the payment sheet will always be dark. Payment sheet is only light if the mobile theme is light and vice versa.

**To Reproduce**
Steps to reproduce the behaviour:

` paymentSheetParameters: SetupPaymentSheetParameters(
              paymentIntentClientSecret:
                  jsonDecode(paymentIntentResponse.body)['client_secret'],
              merchantDisplayName: 'example app',
              primaryButtonLabel: 'Pay',
              style: ThemeMode.light,
          ),`

Result - 
Payment sheet is dark

**Smartphone / tablet**
Android devices

**Expected**
After passing style property the payment sheet them should override phones theme.

**Comment by remonh87** [comment]
yes good catch it is not supported (by Stripe) on Android devices I will add an extra comment in the docs to clarify this.
