### ISSUE TITLE
Confused by token example...

### ISSUE THREAD

**Issue by jamesdixon** [flutter-stripe/flutter_stripe#1142]
Hi, we are still on an old version of the Stripe API (Charges) internally and need tokenization. 

I see the `createToken` method, but [looking at the example](https://github.com/flutter-stripe/flutter_stripe/blob/6cdf95e6c0e6772f51fc0a92956174f658278a5c/example/lib/screens/others/legacy_token_card_screen.dart), I have no idea how tokenization is working. Card details are collected, then `createToken` is called, but the card details are never passed. 

How does this work?

**Comment by jamesdixon** [comment]
Okay, after toying with the example, it appears the card data is maintained internally. I'm assuming this might be related to PCI compliance even though as long as you're not storing/logging anything locally/to your server, then passing the card data into these methods doesn't seem harmful. 

@remonh87 @jonasbark can you comment?

**Comment by jonasbark** [comment]
Yes, it's due to PCI compliance issues. It's true what you say but in order to transmit the data to the stripe SDK and flutter back and forth it needs to pass through methodchannels, which is not safe to use for such information.

You can check stripe react native repository for more details
