### ISSUE TITLE
3DS2 authentication is not working in Thailand.

### ISSUE THREAD

**Issue by pokemonni01** [flutter-stripe/flutter_stripe#1151]
**Describe the bug**
I just publish my application to production and found the issue that when any setup intent require 3DS will be fail.

**To Reproduce**
1. confirm setup intent or payment intent and the intent should require 3DS.
2. SDK throw error with null.

**Expected behavior**
The SDK should navigate user to 3DS webview.

**Smartphone / tablet**
 - Device: iPhone, Android
 - OS: iOS, Android
 - Package version: 8.0.0+1
 - Flutter version: 3.3.0

**Additional Information**
Hint from Stripe team.
Stripe Flutter SDK might be not up-to-date with official SDK latest changes.

**Comment by pokemonni01** [comment]
This issue still occurs in version 9.0.0

**Comment by remonh87** [comment]
I would contact stripe support again  because version 9.0.0  is the latest greatest available.
