### ISSUE TITLE
latest version in flutter doesn't support IOS 12.0, when doing pod install

### ISSUE THREAD

**Issue by whinef** [flutter-stripe/flutter_stripe#1152]
**Describe the bug**
When I try to pod install, latest version of flutter stripe error message shows 
[!] CocoaPods could not find compatible versions for pod "stripe_ios":
  In Podfile:
    stripe_ios (from `.symlinks/plugins/stripe_ios/ios`)

Specs satisfying the `stripe_ios (from `.symlinks/plugins/stripe_ios/ios`)` dependency were found, but they required a higher minimum deployment target.

I've set my minimum IOS deployment target to 12.0 as per the documentation. 

But when I tried to change the minimum requirement to 13.0 the pod install is successful.

**To Reproduce**
1. dart pub add flutter_stripe
2. Tapping the confirm button.
3. Set your minimum ios deployment to 12.0 both in Xcode and Pubspec.yaml file
4. Do Pod install
5. Error occured

**Expected behavior**
To proceed sucessful pod install when minimum ios deployment is 12.0

**Smartphone / tablet**
 - Package version: 9.0.0
 - Flutter version : 3

**Comment by remonh87** [comment]
This is a decision made by the stripe iOS sdk. If you want stripe ios12 support you need to downgrade our library (which is not recommended). 

To be honest I think there will be little iOS users with iOS12 on their phones since apple is quite aggressive in upgrading and most devices still are on ios14.

**Comment by kevin-induro** [comment]
@remonh87 Perhaps the issue that the OP should have been pointing out is that pub.dev's page lists 12 as the minimum required: https://pub.dev/packages/flutter_stripe

I see that your [readme is listing 13](https://github.com/flutter-stripe/flutter_stripe/commit/c92fc5b94d9195ff7b19964e783e7b9fb4445a7b), but it hasn't gotten to pub.dev it seems, which is perhaps more visible.
