### ISSUE TITLE
timeout doesn't close the payment sheet

### ISSUE THREAD

**Issue by ChauCM** [flutter-stripe/flutter_stripe#1153]
**Describe the bug**
```
await Stripe.instance.presentPaymentSheet(
  options: const PaymentSheetPresentOptions(timeout: 2000),
);
```
suppose to close the payment sheet after two seconds. But it's not

**To Reproduce**
`customFlow: false`
using the code above to show the payment sheet

**Expected behavior**
payment sheet close on itself after two seconds

**Smartphone/tablet**
 - Device: [e.g. iPhone 14 Pro simulator]
 - OS: [e.g. iOS 13, Android 10]
 - Package version: [9.0.0]
 - Flutter version [e.g. 3.7.3]

**Comment by julian-printemps** [comment]
Has this been released already?
