### ISSUE TITLE
Add support for person tokens

### ISSUE THREAD

**Issue by devsideal** [flutter-stripe/flutter_stripe#1160]
I'm trying to create person token from app,
https://stripe.com/docs/api/tokens/create_person?lang=java

**Using below code:**

```
var relationship = {
   "owner": true,
};
var person = {
   "first_name": firstNameController.text.trim(),
   "last_name": lastNameController.text.trim(),
   "relationship": relationship
};
var param = {
    "person": person
};
final personToken = await Stripe.instance.createToken(CreateTokenParams.fromJson(param));
```

**Getting error:**

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: CheckedFromJsonException
 Could not create `CreateTokenParams`. There is a problem with "runtimeType". Invalid union type "null"!
#0      _$CreateTokenParamsFromJson (package:stripe_platform_interface/src/models/create_token_data.freezed.dart:29:7)
#1      new CreateTokenParams.fromJson (package:stripe_platform_interface/src/models/create_token_data.dart:47:7)
```

When I checked in the library code, looks like its not supported..?

<img width="781" alt="Screenshot 2023-03-11 at 12 54 47 PM" src="https://user-images.githubusercontent.com/91250232/224471214-33038034-f46e-439f-86c5-f82d80f533d2.png">

**My current flutter_stripe version is** `9.0.0+1`

I'm doing something wrong? or
This is not supported by flutter sdk?

**Comment by jamesblasco** [comment]
As you can see in the code we only support card, bankAccount and pii tokens. I will rename this issue to follow the implementation of person token in this issue
