### ISSUE TITLE
Apple Pay `cornerRadius` is not respected

### ISSUE THREAD

**Issue by joshuaruesweg** [flutter-stripe/flutter_stripe#1164]
**Describe the bug**
If I set a border radius for Apple Pay (in the `PlatformPayButton` button), the whole thing is not respected. The default radius (`4.0`)  is applied.

**To Reproduce**
1. Set a `borderRadius` for the `PlatformPayButton` to e.g. `32.0` [1]
2. Render the widget and see, that the default border radius of `4.0` is applied. 

**Expected behavior**
That the `borderRadius` is applied without any problem. 

**Smartphone / tablet**
 - Device: iPhone 14 Pro Max (Simulator on latest macOS)
 - OS: iOS 16.2
 - Package version: 9.0.0
 - Flutter version: 3.7.3

**Additional context**
[1] Demo code to reproduce the issue:
```DART
PlatformPayButton(
  borderRadius: 32,
  constraints: const BoxConstraints(minHeight: 48, maxHeight: 48),
  onShippingMethodSelected: (method) {
    debugPrint('Shipping contact updated $method');

    Stripe.instance.updatePlatformSheet(
      params: const PlatformPaySheetUpdateParams.applePay(
        summaryItems: [
          ApplePayCartSummaryItem.immediate(
            label: "TOTAL",
            amount: "13.37",
          )
        ],
        shippingMethods: [],
        errors: [],
      ),
    );
  },
  onDidSetShippingContact: (contact) {
    Stripe.instance.updatePlatformSheet(
      params: const PlatformPaySheetUpdateParams.applePay(
        summaryItems: [
          ApplePayCartSummaryItem.immediate(
            label: "TOTAL",
            amount: "13.37",
          )
        ],
        errors: [],
        shippingMethods: [],
      ),
    );
  },
  type: PlatformButtonType.checkout,
  appearance: PlatformButtonStyle.whiteOutline,
  onPressed: () => print("PRESSED"),
);
```

[2]: 
 ![Screenshot 2023-03-13 at 13 39 46](https://user-images.githubusercontent.com/1216563/224704566-1fcf8cb9-6e4a-43f2-961f-28f99a69f9c8.png)

**Comment by remonh87** [comment]
fix will be shipped in next release
