### ISSUE TITLE
Ambiguous import when using Card widget

### ISSUE THREAD

**Issue by TesLake** [flutter-stripe/flutter_stripe#117]
When using a Card widget and having the flutter_stripe imported it gives an Ambiguous_import error:

[class Card extends StatelessWidget, class Card with _$Card]
The name 'Card' is defined in the libraries 'package:flutter/src/material/card.dart (via package:flutter/material.dart)' and 'package:stripe_platform_interface/src/models/payment_methods.dart'.
Try using 'as prefix' for one of the import directives, or hiding the name from all but one of the imports.dart(ambiguous_import)
'Card' isn't a function.
Try correcting the name to match an existing function, or define a method or function named 'Card'.dart(invocation_of_non_function)

1. import 'package:flutter/material.dart';
2. import 'package:flutter_stripe/flutter_stripe.dart';
3. Add a Card widget 

Smartphone
 - Device: Samsung Galaxy A51 (Physical)
 - OS: Android 11.0
 - Package version: 1.0.1+3
 - Flutter version 2.2.0

Temporary solution is to use:
import 'package:flutter_stripe/flutter_stripe.dart'  hide Card;

**Comment by relief12** [comment]
@TesLake Import the dependency as follows:

For example:

`import 'package:flutter_stripe/flutter_stripe.dart' as FlutterStripe;
`

Then use it as:

 FlutterStripe.Stripe.(...)

or

FlutterStripe.(...)

**Comment by remonh87** [comment]
You indeed need to use named imports. We use `Card`  class since it is consistent naming with the stripe SDK we are using.
