### ISSUE TITLE
[Web] Possibility to enable/disable stripe libraries in runtime for privacy cookie consent. (GDPR regulations)

### ISSUE THREAD

**Issue by manandhar-aarya** [flutter-stripe/flutter_stripe#1178]
Stripe scripts should only run after user has given consent for it. There should be a way to disable the running of scripts until the consent the given. And a way to enable them afterwards.

**Comment by jamesblasco** [comment]
Hi @manandhar-aarya, the library is loaded when calling `Stripe.initialise` or `WebStripe.initialise`, none scripts will be run until the library is initialised. So you can do so when the user consent is given.

We try to adjust to the official Stripe apis and they do not provide a prebuilt solution for this case, while it is possible to implement it with what we provide
