### ISSUE TITLE
"sepa_debit" doesn't work with SetupIntents

### ISSUE THREAD

**Issue by janwol** [flutter-stripe/flutter_stripe#1184]
**Describe the bug**
If you use `"sepa_debit"` as one of the `payment_method_types ` of a _Setup Intent_ it doesn't appears in the _Payment Sheet_. If it is the only payment method type it causes an app crash. 

**To Reproduce**
create a setup intent server side:
```
await stripe.setupIntents.create({
  usage : 'off_session',
  payment_method_types : ['sepa_debit']
});
```

in client app:
```
await Stripe.instance.initPaymentSheet(
        paymentSheetParameters: SetupPaymentSheetParameters(
          customFlow: false,
          allowsDelayedPaymentMethods : true,
          merchantDisplayName: 'xyz',
          setupIntentClientSecret: 'seti_XXX',
));

await Stripe.instance.presentPaymentSheet();
```

causes:

> E/AndroidRuntime(  972): Process: app.abc.def, PID: 972
> E/AndroidRuntime(  972): java.util.NoSuchElementException: List is empty.
> E/AndroidRuntime(  972): 	at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:214)
> E/AndroidRuntime(  972): 	at com.stripe.android.paymentsheet.ui.AddPaymentMethodKt.getInitiallySelectedPaymentMethodType(AddPaymentMethod.kt:140)
> E/AndroidRuntime(  972): 	at com.stripe.android.paymentsheet.ui.AddPaymentMethodKt.access$getInitiallySelectedPaymentMethodType(AddPaymentMethod.kt:1)
> E/AndroidRuntime(  972): 	at com.stripe.android.paymentsheet.ui.AddPaymentMethodKt$AddPaymentMethod$selectedPaymentMethodCode$2.invoke(AddPaymentMethod.kt:50)
> E/AndroidRuntime(  972): 	at com.stripe.android.paymentsheet.ui.AddPaymentMethodKt$AddPaymentMethod$selectedPaymentMethodCode$2.invoke(AddPaymentMethod.kt:49)

**Smartphone / tablet**
 - Device: Pixel 6
 - OS: Android 10
 - Package version: 9.0.0+1
 - Flutter version 3.3.1

**Additional context**
Using it with _Payment Intents_ it works as aspected. A _Checkout Session_ created with the same parameters also works as aspected.

**Comment by remonh87** [comment]
I was able to complete a paymewnt for setupintent with sepa debit
