### ISSUE TITLE
Execution failed for task ':stripe_android:compileDebugKotlin'.

### ISSUE THREAD

**Issue by ketancts** [flutter-stripe/flutter_stripe#119]
The class is loaded from C:/Users/UserName/.gradle/caches/transforms-2/files-2.1/4e5aa79770c626f4db262bec4e99609f/jetified-stripe-android-16.8.2-api.jar!/com/stripe/android/model/ConfirmSetupIntentParams.class
e: E:\flutter\.pub-cache\hosted\pub.dartlang.org\stripe_android-1.0.1+3\android\src\main\kotlin\com\reactnativestripesdk\StripeSdkModule.kt: (455, 15): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from C:/Users/UserName/.gradle/caches/transforms-2/files-2.1/76549837d5deb210ea34fb837e9cb50b/jetified-kotlin-stdlib-1.5.0.jar!/kotlin/Unit.class

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':stripe_android:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 7s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by jonasbark** [comment]
Please refer to the requirements, in this case the Kotlin one:
https://github.com/flutter-stripe/flutter_stripe#android
