### ISSUE TITLE
Do we have any approach to implement flutter stripe in macOS? 

### ISSUE THREAD

**Issue by umar-stride-studio** [flutter-stripe/flutter_stripe#1192]
<img width="883" alt="Screenshot 2023-03-29 at 3 34 48 PM" src="https://user-images.githubusercontent.com/116542608/228507627-1819bb71-0da3-4caa-8b96-1a52ccb36d33.png">

This plugin is not providing any approach for macOS implementation. Do we have any alternate?

**Comment by jonasbark** [comment]
Your only possibility is to use e.g. Stripe Checkout. Stripe does not provide libraries for macOS.
