### ISSUE TITLE
Unable to show saved Card details

### ISSUE THREAD

**Issue by sumit-android-haridwar** [flutter-stripe/flutter_stripe#1193]
We are trying to add Stripe in flutter with Java as a server Side  using the payment Intent method

We are unable to show Saved card details while displaying the Bottom sheet of payment. We are adding the required the 'paymentIntentClientSecret' and 'customerId'
but not adding the 'customerEphemeralKeySecret' because it is not possible to generate at java side SDK of Stripe.

Any Possible way to achieve the saved cards details while payment ?

**Comment by jonasbark** [comment]
> but not adding the 'customerEphemeralKeySecret' because it is not possible to generate at java side SDK of Stripe.

please talk to your favorite Stripe support person. It's definitely possible to do this with the Java SDK as well.
