### ISSUE TITLE
Add PayPal support (update SDK to `0.26.0`)

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter-stripe/flutter_stripe#1194]
PayPal was recently added to the React Native SDK in this PR: https://github.com/stripe/stripe-react-native/pull/1331  
You can see that this PR also adds support for Cash App to both the _payment sheet_ and to the direct API bindings.

<img width="1125" alt="image" src="https://user-images.githubusercontent.com/19204050/228817505-663e557c-a258-4ad7-8ece-4e2fe3b61bcf.png">

[In the CHANGELOG](https://github.com/stripe/stripe-react-native/blob/master/CHANGELOG.md#0260---2023-03-16), you can see that this feature was made available in version `0.26.0` of Stripe for React Native.  
Could you please update the dependency in this plugin, thanks 🙏

**Comment by creativecreatorormaybenot** [comment]
This is resolved by #1171 🚀 cc @jamesblasco @jonasbark

**Comment by PatrikGolubar** [comment]
Hi, 
Is paypal also working on web? 
If not when it will be available for web?
