### ISSUE TITLE
StripeException "Invalid token ID: tok_xx" when integrating with Google Pay (Pay plugin)

### ISSUE THREAD

**Issue by manandhar-aarya** [flutter-stripe/flutter_stripe#1199]
Hi! I am trying to integrate Google Pay using the [Pay][1] plugin to [flutter_stripe][2] library. I am getting the token from the Pay plugin after the payment but when I try to send it to Stripe, I am getting exception as "Invalid token ID: tok_xx". 

I am following the sample provided by the flutter_stripe library like [here][3]: 

      final token = paymentResult['paymentMethodData']['tokenizationData']['token'];
      final tokenJson = Map.castFrom(json.decode(token));

      final params = PaymentMethodParams.cardFromToken(
        paymentMethodData: PaymentMethodDataCardFromToken(
          token: tokenJson['id'],
        ),
      );
      await Stripe.instance.confirmPayment(
        paymentIntentClientSecret: clientSecret,
        data: params,
      );

I am getting this error on the confirmPayment method. Do I need to do something more to the token? Is there another way I can verify the token?

I tried testing in release and test mode with same results. 

  [1]: https://pub.dev/packages/pay
  [2]: https://pub.dev/packages/flutter_stripe
  [3]: https://github.com/flutter-stripe/flutter_stripe/blob/db72f0ed6f5e47b932825e146f824608574ee75d/example/lib/screens/wallets/google_pay_screen.dart#L90

**Comment by remonh87** [comment]
Hi I just tested and it works on our example app. Did you configure the `google_pay_payment_profile.json` like:   [example](https://github.com/flutter-stripe/flutter_stripe/blob/main/example/assets/google_pay_payment_profile.json) ?
