### ISSUE TITLE
Andrdid Keyboard not showing correct

### ISSUE THREAD

**Issue by kekko7072** [flutter-stripe/flutter_stripe#120]
**Describe the bug**
I don't know if it's a bug,
Only on Android when I use this code for input the card field it shows a normal text keyboard and not number keyboard as it does on iOS.

```
CardField(
            onCardChanged: (card) {
              setState(() {
                _card = card;
              });
            },
          )
```
**Package version**
flutter_stripe: ^1.0.1+3

![WhatsApp Image 2021-06-05 at 20 16 22](https://user-images.githubusercontent.com/32552589/120901510-b6f7df00-c63b-11eb-9eba-6d2836e5b0c0.jpeg)

**Comment by kekko7072** [comment]
Only on CVC is number keyboard and after done it doesn't dessapear

**Comment by jonasbark** [comment]
Hi!

This issue is already tracked on https://github.com/flutter-stripe/flutter_stripe/issues/14
