### ISSUE TITLE
How to close PresentPaymentSheet

### ISSUE THREAD

**Issue by TransmachSystems** [flutter-stripe/flutter_stripe#1204]
Is there any way to close or dismiss payment sheet from code for flutter ?

tried things that didn't work
Navigator.pop();
SystemNavigator.pop();

**Comment by remonh87** [comment]
you can you can only set a timeout that automatically closes the payment sheet,

**Comment by apetroaeiandrei** [comment]
I have the following scenario:
I send the user order together with the request of creating the payment intent to the backend server. The order is confirmed by the backend server on payment_intent.succeeded event. The customer confirms the payment in the app then the internet drops which makes the payment sheet display "A data connection is not currently allowed" error but on the server side the payment is confirmed. Then the internet is restored, i know that the order is successful but I have no way of closing the payment sheet programatically. Any suggestion on how to handle this?
