### ISSUE TITLE
Execution failed for task ':stripe_android:generateDebugRFile'.

### ISSUE THREAD

**Issue by AndxEng** [flutter-stripe/flutter_stripe#1205]
**Describe the bug**

Execution failed for task ':stripe_android:generateDebugRFile'.
> Could not resolve all dependencies for configuration ':stripe_android:debugCompileClasspath'.
   > Problems reading data from Binary store in C:\Users\peter.zhu\.gradle\.tmp\gradle10164584867142497927.bin offset 61994 exists? true

**Smartphone / tablet**
Android Studio verion 2022.1.1
Flutter version 3.5.5

**Comment by remonh87** [comment]
Cannot reproduce it did you specify the correct kotlin version in your build.gradle file? IT should be: 1.8.0

**Comment by AndxEng** [comment]
My kotlin version is correct, and I cannot reference implementation 'com.stripe:stripe-android:[20.19.2, 20.20.0[' implementation "com.stripe:financial-connections:20.16.+" in my project

**Comment by AndxEng** [comment]
My kotlin version is correct, and I cannot reference 
implementation 'com.stripe:stripe-android:[20.19.2, 20.20.0[' 
implementation "com.stripe:financial-connections:20.16.+" 
in my project
