### ISSUE TITLE
PayPal payments do not work

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter-stripe/flutter_stripe#1211]
#1194 was closed as PayPal support should have been added in version `9.1.1` (see #1171).

However, I still see the same behavior. When trying to confirm a payment intent using `PaymentMethodParams.payPal`, nothing happens. There is no error message and the future completes as a noop (no web view is opened, nothing).

---

The implementation looks as follows:

```dart
final intent = await _createPaymentIntent(ref, mode);

Stripe.publishableKey = intent.publishableKey;
const params = PaymentMethodParams.payPal(
  paymentMethodData: PaymentMethodData(
    billingDetails: BillingDetails(
      email: ..,
      address: Address(
        ...,
      ),
      phone: ..,
      name: ..,
    ),
    shippingDetails: ShippingDetails(
      address: Address(
        ...,
      ),
      phone: ..,
      name: ..,
      carrier: ..,
      trackingNumber: ..,
    ),
  ),
);

await stripe.confirmPayment(
  paymentIntentClientSecret: intent.clientSecret,
  data: params,
);
```

In our default implementation, we do not even pass `billingDetails` or `shippingDetails` and this works for credit card, Apple Pay, and Google Pay. However, I figured that this may be an issue and therefore added all possible parameters with valid values.

Still, this does not change anything. On the backend payment intent side, I have chatted with the Stripe team and it all looked good. Do you think this is an issue with the `flutter_stripe` implementation or should I contact Stripe again?

**Comment by creativecreatorormaybenot** [comment]
cc @jamesblasco @jonasbark @remonh87

**Comment by jonasbark** [comment]
Works fine on my side with the PayPalScreen from the example app.

**Comment by jonasbark** [comment]
Closing issue due to lack of response

**Comment by nicklbaert** [comment]
@jonasbark Sorry for the delay. We needed to pause working on this due to an internal emergency. Contrary to what the example app is doing, we are creating a subscriptionIntent instead of a paymentIntent. 

This is the output from stripe.confirmPayment(..)

`StripeException(error: LocalizedErrorMessage(code: FailureCode.Failed, localizedMessage: There was an unexpected error -- try again in a few seconds, message: Missing required param: mandate_data[customer_acceptance][online]., stripeErrorCode: parameter_missing, declineCode: null, type: invalid_request_error))`

I passed this as the data parameter:
`const params = PaymentMethodParams.payPal(
    paymentMethodData: PaymentMethodData(
      mandateData: MandateData(
        customerAcceptance: MandateDataCustomerAcceptance(
          ipAddress: MandateDataOnlineData(
            ipAddress: '127.0.0.1',
            userAgent: 'device',
          ),
        ),
      ),
      billingDetails: BillingDetails(
        // email is mandatory
        email: 'niclasillg@gmail.com',
        address: Address(
          city: 'Stockholm',
          country: 'SV',
          line1: 'Kungsgatan 1',
          line2: '',
          state: 'Stockholm county',
          postalCode: '111 22',
        ),
      ),
    ),
  );`

Any ideas on what we need to change to make it work?

Thank you so much for the assistance :)

**Comment by jonasbark** [comment]
@remonh87 I think "ipAddress" should be "online" for `MandateDataCustomerAcceptance` - can you check?

**Comment by nicklbaert** [comment]
@jonasbark Thanks for the reply. Unfortunately, still the same error when passing an ipAddress of "online"

```
customerAcceptance: MandateDataCustomerAcceptance(
          ipAddress: MandateDataOnlineData(
            ipAddress: 'online',
            userAgent: 'device',
          ),
        ),
```

If you are referring to a parameter named 'online', there is no such parameter in MandateDataCustomerAcceptance.

**Comment by nicklbaert** [comment]
@jonasbark  Gotcha! Just to eliminate confusion: Are you referring to the flutter_stripe package or the Stripe iOS SDK when you say plugin?
And is it possible for you to give a rough estimation about how far in the future this will happen? 

Thank you a ton!

**Comment by nicklbaert** [comment]
> Yes, and it needs to be changed within the plugin.

Hi @jonasbark, is this going to be implemented any time soon?
