### ISSUE TITLE
Payment not completed

### ISSUE THREAD

**Issue by MasoudRashidi** [flutter-stripe/flutter_stripe#1214]
**Describe the bug**
iOS payment will be working just in simulator and on the real devices have "Payment not completed" error without the error code.

**To Reproduce**

I called this method for iOS payment (Apple Pay).
    await Stripe.instance.confirmPlatformPayPaymentIntent(
      clientSecret: event.clientSecret,
      confirmParams: PlatformPayConfirmParams.applePay(
        applePay: ApplePayParams(
          merchantCountryCode: "FR",
          currencyCode: "EUR",
          cartItems: [
            ApplePayCartSummaryItem.immediate(
              label: event.title,
              amount: "${event.amount}",
            ),
          ],
        ),
      ),
    );

**Error message is below**
error: StripeException(error: LocalizedErrorMessage(code: FailureCode.Failed, localizedMessage: Payment not completed, message: Payment not completed, stripeErrorCode: null, declineCode: null, type: null))

**Smartphone / tablet**
 - Device: [e.g. iPhone X]
 - Package version: flutter_stripe: ^9.1.1
 - Flutter version: (sdk: '>=2.19.0 <3.0.0')

**Additional context**

LOG ANALYTICS: ["pay_var": "legacy", "ocr_type": "none", "install": "C", "event": "mc_complete_init_applepay", "product_usage": ["PaymentSheet"], "app_name": "flutter_quiz", "analytics_ua": "analytics.stripeios-1.0", "bindings_version": "23.3.4", "locale": "en_US", "device_type": "iPhone10,3", "additional_info": [], "mpe_config": ["save_payment_method_opt_in_behavior": "automatic", "allows_delayed_payment_methods": false, "customer": false, "apple_pay_config": true, "style": 2, "return_url": false, "appearance": ["primary_button": false, "shadow": false, "colors": false, "usage": false, "border_width": false, "corner_radius": false, "font": false], "default_billing_details": false], "session_id": "018df625-0281-47f2-a6ed-a43f4ea831a8", "app_version": "1.0.0", "plugin_type": "flutter", "apple_pay_enabled": 0, "os_version": "16.3.1", "publishable_key": "pk_test_==============="] flutter: Stripe error is: StripeException(error: LocalizedErrorMessage(code: FailureCode.Failed, localizedMessage: Payment not completed, message: Payment not completed, stripeErrorCode: null, declineCode: null, type: null))

**Comment by remonh87** [comment]
Do you have apple pay configured on the phone? I can confirm Apple pay is working on our device. Also make sure you have configured apple pay like described in: https://stripe.com/docs/apple-pay?platform=ios#setup. For example you need to upload the apple pay certificate to Stripe.  Simulators do not have this check so that is why simulators are working.
