### ISSUE TITLE
3D secure page not localized

### ISSUE THREAD

**Issue by artemsorochan** [flutter-stripe/flutter_stripe#1217]
Device language set up to German, but 3D secure test page is shown in English(both android and iOS).
This is from our Info.plist
 <key>CFBundleLocalizations</key>
	<array>
		<string>en</string>
		<string>de</string>
        </array> 

1. Change device language to other than English.
2. Trigger 3D authentication webview.
3. Webview page is localized in English.

<img width="345" alt="Screenshot 2023-04-26 at 10 37 36" src="https://user-images.githubusercontent.com/116367489/234503762-27df3f4e-8b84-4ad1-a373-6c08aa08b709.png">

**Expected behavior**
Webview page localized in device language(in our case German).

**Smartphone / tablet**

 - Device: [e.g. iPhone 11]
 - OS: [e.g. iOS 16.4, Android 13]
 - Package version: [e.g. 7.0.0]
 - Flutter version [e.g. 3.7.7]

**Comment by jonasbark** [comment]
outside of the plugins control - also it's only a test page.
