### ISSUE TITLE
flutter_stripe and jitsi_meet_wrapper are not working together 

### ISSUE THREAD

**Issue by AbdallahR99** [flutter-stripe/flutter_stripe#1232]
When I add flutter_stripe to the project, jitsi_meet_wrapper package stop working, and I can't find any alternative that is working currently for the flutter_stripe or jitsi_meet_wrapper

Here is the log when I try to start a jitsi meeting:

> I/ViewRootImpl@e0cb556[MainActivity](29719): ViewPostIme pointer 0
> I/ViewRootImpl@e0cb556[MainActivity](29719): ViewPostIme pointer 1
> I/ViewRootImpl@e0cb556[MainActivity](29719): ViewPostIme pointer 0
> I/ViewRootImpl@e0cb556[MainActivity](29719): ViewPostIme pointer 1
> I/flutter (29719): JitsiMeetingOptions: JitsiMeetingOptions{roomNameOrUrl: jitsi-meet-wrapper-test-room, serverUrl: null, subject: My Plugin Test Meeting, token: , isAudioMuted: true, isAudioOnly: false, isVideoMuted: true, userDisplayName: Plugin Test User, userEmail: fake@email.com, userAvatarUrl: null, featureFlags: {}, configOverrides: null}
> D/OrientationModule(29719): onActivityPaused
> D/AppCompatDelegate(29719): Checking for metadata for AppLocalesMetadataHolderService : Service not found
> D/OrientationModule(29719): onActivityCreated
> I/DecorView(29719): [INFO] isPopOver=false config=true
> I/DecorView(29719): updateCaptionType: isFloating=false isApplication=true hasWindowDecorCaption=false this=DecorView@7a60f53[]
> D/DecorView(29719): setCaptionType = 0, this = DecorView@7a60f53[]
> I/DecorView(29719): getCurrentDensityDpi: from real metrics. densityDpi=600 msg=resources_loaded
> I/DecorView(29719): setWindowBackground: isPopOver=false color=fffafafa d=android.graphics.drawable.ColorDrawable@4b64d89
> W/com.zoolker(29719): Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (unsupported, reflection, allowed)
> W/com.zoolker(29719): Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (unsupported, reflection, allowed)
> D/org.jitsi.meet.sdk.ReactInstanceManagerHolder(29719): initializing RN with Activity
> W/com.zoolker(29719): Accessing hidden method Landroid/content/Context;->destroy()V (blocked, linking, denied)
> W/com.zoolker(29719): Accessing hidden method Landroid/content/Context;->destroy()V (blocked, linking, denied)
> D/AndroidRuntime(29719): Shutting down VM
> E/AndroidRuntime(29719): FATAL EXCEPTION: main
> E/AndroidRuntime(29719): Process: com.zoolker, PID: 29719
> E/AndroidRuntime(29719): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.zoolker/dev.saibotma.jitsi_meet_wrapper.JitsiMeetWrapperActivity}: android.view.InflateException: Binary XML file line #9 in com.zoolker:layout/activity_jitsi_meet: Binary XML file line #9 in com.zoolker:layout/activity_jitsi_meet: Error inflating class org.jitsi.meet.sdk.JitsiMeetView
> E/AndroidRuntime(29719): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4169)
> E/AndroidRuntime(29719): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4325)
> E/AndroidRuntime(29719): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
> E/AndroidRuntime(29719): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
> E/AndroidRuntime(29719): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
> E/AndroidRuntime(29719): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
> E/AndroidRuntime(29719): 	at android.os.Handler.dispatchMessage(Handler.java:106)
> E/AndroidRuntime(29719): 	at android.os.Looper.loopOnce(Looper.java:226)
> E/AndroidRuntime(29719): 	at android.os.Looper.loop(Looper.java:313)
> E/AndroidRuntime(29719): 	at android.app.ActivityThread.main(ActivityThread.java:8757)
> E/AndroidRuntime(29719): 	at java.lang.reflect.Method.invoke(Native Method)
> E/AndroidRuntime(29719): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
> E/AndroidRuntime(29719): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
> E/AndroidRuntime(29719): Caused by: android.view.InflateException: Binary XML file line #9 in com.zoolker:layout/activity_jitsi_meet: Binary XML file line #9 in com.zoolker:layout/activity_jitsi_meet: Error inflating class org.jitsi.meet.sdk.JitsiMeetView
> E/AndroidRuntime(29719): Caused by: android.view.InflateException: Binary XML file line #9 in com.zoolker:layout/activity_jitsi_meet: Error inflating class org.jitsi.meet.sdk.JitsiMeetView
> E/AndroidRuntime(29719): Caused by: java.lang.reflect.InvocationTargetException
> E/AndroidRuntime(29719): 	at java.lang.reflect.Constructor.newInstance0(Native Method)
> E/AndroidRuntime(29719): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
> E/AndroidRuntime(29719): 	at android.view.LayoutInflater.createView(LayoutInflater.java:876)
> E/AndroidRuntime(29719): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1028)
> E/AndroidRuntime(29719): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:983)
> E/AndroidRuntime(29719): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1145)
> E/AndroidRuntime(29719): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1106)
> E/AndroidRuntime(29719): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:692)
> E/AndroidRuntime(29719): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:544)
> E/AndroidRuntime(29719): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:491)
> E/AndroidRuntime(29719): 	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:775)
> E/AndroidRuntime(29719): 	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:197)
> E/AndroidRuntime(29719): 	at org.jitsi.meet.sdk.JitsiMeetActivity.onCreate(JitsiMeetActivity.java:102)
> E/AndroidRuntime(29719): 	at dev.saibotma.jitsi_meet_wrapper.JitsiMeetWrapperActivity.onCreate(JitsiMeetWrapperActivity.kt:37)
> E/AndroidRuntime(29719): 	at android.app.Activity.performCreate(Activity.java:8591)
> E/AndroidRuntime(29719): 	at android.app.Activity.performCreate(Activity.java:8570)
> E/AndroidRuntime(29719): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
> E/AndroidRuntime(29719): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4150)
> E/AndroidRuntime(29719): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4325)
> E/AndroidRuntime(29719): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
> E/AndroidRuntime(29719): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
> E/AndroidRuntime(29719): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
> E/AndroidRuntime(29719): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
> E/AndroidRuntime(29719): 	at android.os.Handler.dispatchMessage(Handler.java:106)
> E/AndroidRuntime(29719): 	at android.os.Looper.loopOnce(Looper.java:226)
> E/AndroidRuntime(29719): 	at android.os.Looper.loop(Looper.java:313)
> E/AndroidRuntime(29719): 	at android.app.ActivityThread.main(ActivityThread.java:8757)
> E/AndroidRuntime(29719): 	at java.lang.reflect.Method.invoke(Native Method)
> E/AndroidRuntime(29719): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
> E/AndroidRuntime(29719): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
> E/AndroidRuntime(29719): Caused by: java.lang.VerifyError: Verifier rejected class com.facebook.react.ReactInstanceManager: void com.facebook.react.ReactInstanceManager.setupReactContext(com.facebook.react.bridge.ReactApplicationContext) failed to verify: void com.facebook.react.ReactInstanceManager.setupReactContext(com.facebook.react.bridge.ReactApplicationContext): [0x38] register v10 has type Reference: com.facebook.react.bridge.ReactApplicationContext but expected Reference: com.facebook.react.bridge.ReactContext (declaration of 'com.facebook.react.ReactInstanceManager' appears in /data/app/~~eX5DLdzXOBzxGydgXmfg9A==/com.zoolker-o5DCduvf6nlKtmAx8Do3Hg==/base.apk!classes7.dex)
> E/AndroidRuntime(29719): 	at com.facebook.react.ReactInstanceManager.builder(ReactInstanceManager.java:215)
> E/AndroidRuntime(29719): 	at org.jitsi.meet.sdk.ReactInstanceManagerHolder.initReactInstanceManager(ReactInstanceManagerHolder.java:289)
> E/AndroidRuntime(29719): 	at org.jitsi.meet.sdk.JitsiMeetView.initialize(JitsiMeetView.java:192)
> E/AndroidRuntime(29719): 	at org.jitsi.meet.sdk.JitsiMeetView.<init>(JitsiMeetView.java:101)
> E/AndroidRuntime(29719): 	... 30 more
> E/JitsiMeetSDK(29719): JitsiMeetUncaughtExceptionHandler FATAL ERROR
> E/JitsiMeetSDK(29719): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.zoolker/dev.saibotma.jitsi_meet_wrapper.JitsiMeetWrapperActivity}: android.view.InflateException: Binary XML file line #9 in com.zoolker:layout/activity_jitsi_meet: Binary XML file line #9 in com.zoolker:layout/activity_jitsi_meet: Error inflating class org.jitsi.meet.sdk.JitsiMeetView
> E/JitsiMeetSDK(29719): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4169)
> E/JitsiMeetSDK(29719): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4325)
> E/JitsiMeetSDK(29719): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
> E/JitsiMeetSDK(29719): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
> E/JitsiMeetSDK(29719): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
> E/JitsiMeetSDK(29719): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
> E/JitsiMeetSDK(29719): 	at android.os.Handler.dispatchMessage(Handler.java:106)
> E/JitsiMeetSDK(29719): 	at android.os.Looper.loopOnce(Looper.java:226)
> E/JitsiMeetSDK(29719): 	at android.os.Looper.loop(Looper.java:313)
> E/JitsiMeetSDK(29719): 	at android.app.ActivityThread.main(ActivityThread.java:8757)
> E/JitsiMeetSDK(29719): 	at java.lang.reflect.Method.invoke(Native Method)
> E/JitsiMeetSDK(29719): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
> E/JitsiMeetSDK(29719): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
> E/JitsiMeetSDK(29719): Caused by: android.view.InflateException: Binary XML file line #9 in com.zoolker:layout/activity_jitsi_meet: Binary XML file line #9 in com.zoolker:layout/activity_jitsi_meet: Error inflating class org.jitsi.meet.sdk.JitsiMeetView
> E/JitsiMeetSDK(29719): Caused by: android.view.InflateException: Binary XML file line #9 in com.zoolker:layout/activity_jitsi_meet: Error inflating class org.jitsi.meet.sdk.JitsiMeetView
> E/JitsiMeetSDK(29719): Caused by: java.lang.reflect.InvocationTargetException
> E/JitsiMeetSDK(29719): 	at java.lang.reflect.Constructor.newInstance0(Native Method)
> E/JitsiMeetSDK(29719): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
> E/JitsiMeetSDK(29719): 	at android.view.LayoutInflater.createView(LayoutInflater.java:876)
> E/JitsiMeetSDK(29719): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1028)
> E/JitsiMeetSDK(29719): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:983)
> E/JitsiMeetSDK(29719): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1145)
> E/JitsiMeetSDK(29719): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1106)
> E/JitsiMeetSDK(29719): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:692)
> E/JitsiMeetSDK(29719): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:544)
> E/JitsiMeetSDK(29719): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:491)
> E/JitsiMeetSDK(29719): 	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:775)
> E/JitsiMeetSDK(29719): 	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:197)
> E/JitsiMeetSDK(29719): 	at org.jitsi.meet.sdk.JitsiMeetActivity.onCreate(JitsiMeetActivity.java:102)
> E/JitsiMeetSDK(29719): 	at dev.saibotma.jitsi_meet_wrapper.JitsiMeetWrapperActivity.onCreate(JitsiMeetWrapperActivity.kt:37)
> E/JitsiMeetSDK(29719): 	at android.app.Activity.performCreate(Activity.java:8591)
> E/JitsiMeetSDK(29719): 	at android.app.Activity.performCreate(Activity.java:8570)
> E/JitsiMeetSDK(29719): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
> E/JitsiMeetSDK(29719): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4150)
> E/JitsiMeetSDK(29719): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4325)
> E/JitsiMeetSDK(29719): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
> E/JitsiMeetSDK(29719): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
> E/JitsiMeetSDK(29719): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
> E/JitsiMeetSDK(29719): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
> E/JitsiMeetSDK(29719): 	at android.os.Handler.dispatchMessage(Handler.java:106)
> E/JitsiMeetSDK(29719): 	at android.os.Looper.loopOnce(Looper.java:226)
> E/JitsiMeetSDK(29719): 	at android.os.Looper.loop(Looper.java:313)
> E/JitsiMeetSDK(29719): 	at android.app.ActivityThread.main(ActivityThread.java:8757)
> E/JitsiMeetSDK(29719): 	at java.lang.reflect.Method.invoke(Native Method)
> E/JitsiMeetSDK(29719): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
> E/JitsiMeetSDK(29719): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
> E/JitsiMeetSDK(29719): Caused by: java.lang.VerifyError: Verifier rejected class com.facebook.react.ReactInstanceManager: void com.facebook.react.ReactInstanceManager.setupReactContext(com.facebook.react.bridge.ReactApplicationContext) failed to verify: void com.facebook.react.ReactInstanceManager.setupReactContext(com.facebook.react.bridge.ReactApplicationContext): [0x38] register v10 has type Reference: com.facebook.react.bridge.ReactApplicationContext but expected Reference: com.facebook.react.bridge.ReactContext (declaration of 'com.facebook.react.ReactInstanceManager' appears in /data/app/~~eX5DLdzXOBzxGydgXmfg9A==/com.zoolker-o5DCduvf6nlKtmAx8Do3Hg==/base.apk!classes7.dex)
> E/JitsiMeetSDK(29719): 	at com.facebook.react.ReactInstanceManager.builder(ReactInstanceManager.java:215)
> E/JitsiMeetSDK(29719): 	at org.jitsi.meet.sdk.ReactInstanceManagerHolder.initReactInstanceManager(ReactInstanceManagerHolder.java:289)
> E/JitsiMeetSDK(29719): 	at org.jitsi.meet.sdk.JitsiMeetView.initialize(JitsiMeetView.java:192)
> E/JitsiMeetSDK(29719): 	at org.jitsi.meet.sdk.JitsiMeetView.<init>(JitsiMeetView.java:101)
> E/JitsiMeetSDK(29719): 	... 30 more
> E/JitsiMeetSDK(29719):
> E/JitsiMeetSDK(29719): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.zoolker/dev.saibotma.jitsi_meet_wrapper.JitsiMeetWrapperActivity}: android.view.InflateException: Binary XML file line #9 in com.zoolker:layout/activity_jitsi_meet: Binary XML file line #9 in com.zoolker:layout/activity_jitsi_meet: Error inflating class org.jitsi.meet.sdk.JitsiMeetView
> E/JitsiMeetSDK(29719): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4169)
> E/JitsiMeetSDK(29719): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4325)
> E/JitsiMeetSDK(29719): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
> E/JitsiMeetSDK(29719): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
> E/JitsiMeetSDK(29719): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
> E/JitsiMeetSDK(29719): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
> E/JitsiMeetSDK(29719): 	at android.os.Handler.dispatchMessage(Handler.java:106)
> E/JitsiMeetSDK(29719): 	at android.os.Looper.loopOnce(Looper.java:226)
> E/JitsiMeetSDK(29719): 	at android.os.Looper.loop(Looper.java:313)
> E/JitsiMeetSDK(29719): 	at android.app.ActivityThread.main(ActivityThread.java:8757)
> E/JitsiMeetSDK(29719): 	at java.lang.reflect.Method.invoke(Native Method)
> E/JitsiMeetSDK(29719): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
> E/JitsiMeetSDK(29719): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
> E/JitsiMeetSDK(29719): Caused by: android.view.InflateException: Binary XML file line #9 in com.zoolker:layout/activity_jitsi_meet: Binary XML file line #9 in com.zoolker:layout/activity_jitsi_meet: Error inflating class org.jitsi.meet.sdk.JitsiMeetView
> E/JitsiMeetSDK(29719): Caused by: android.view.InflateException: Binary XML file line #9 in com.zoolker:layout/activity_jitsi_meet: Error inflating class org.jitsi.meet.sdk.JitsiMeetView
> E/JitsiMeetSDK(29719): Caused by: java.lang.reflect.InvocationTargetException
> E/JitsiMeetSDK(29719): 	at java.lang.reflect.Constructor.newInstance0(Native Method)
> E/JitsiMeetSDK(29719): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
> E/JitsiMeetSDK(29719): 	at android.view.LayoutInflater.createView(LayoutInflater.java:876)
> E/JitsiMeetSDK(29719): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1028)
> E/JitsiMeetSDK(29719): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:983)
> E/JitsiMeetSDK(29719): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1145)
> E/JitsiMeetSDK(29719): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1106)
> E/JitsiMeetSDK(29719): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:692)
> E/JitsiMeetSDK(29719): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:544)
> E/JitsiMeetSDK(29719): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:491)
> E/JitsiMeetSDK(29719): 	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:775)
> E/JitsiMeetSDK(29719): 	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:197)
> E/JitsiMeetSDK(29719): 	at org.jitsi.meet.sdk.JitsiMeetActivity.onCreate(JitsiMeetActivity.java:102)
> E/JitsiMeetSDK(29719): 	at dev.saibotma.jitsi_meet_wrapper.JitsiMeetWrapperActivity.onCreate(JitsiMeetWrapperActivity.kt:37)
> E/JitsiMeetSDK(29719): 	at android.app.Activity.performCreate(Activity.java:8591)
> E/JitsiMeetSDK(29719): 	at android.app.Activity.performCreate(Activity.java:8570)
> E/JitsiMeetSDK(29719): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
> E/JitsiMeetSDK(29719): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4150)
> E/JitsiMeetSDK(29719): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4325)
> E/JitsiMeetSDK(29719): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
> E/JitsiMeetSDK(29719): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
> E/JitsiMeetSDK(29719): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
> E/JitsiMeetSDK(29719): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
> E/JitsiMeetSDK(29719): 	at android.os.Handler.dispatchMessage(Handler.java:106)
> E/JitsiMeetSDK(29719): 	at android.os.Looper.loopOnce(Looper.java:226)
> E/JitsiMeetSDK(29719): 	at android.os.Looper.loop(Looper.java:313)
> E/JitsiMeetSDK(29719): 	at android.app.ActivityThread.main(ActivityThread.java:8757)
> E/JitsiMeetSDK(29719): 	at java.lang.reflect.Method.invoke(Native Method)
> E/JitsiMeetSDK(29719): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
> E/JitsiMeetSDK(29719): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
> E/JitsiMeetSDK(29719): Caused by: java.lang.VerifyError: Verifier rejected class com.facebook.react.ReactInstanceManager: void com.facebook.react.ReactInstanceManager.setupReactContext(com.facebook.react.bridge.ReactApplicationContext) failed to verify: void com.facebook.react.ReactInstanceManager.setupReactContext(com.facebook.react.bridge.ReactApplicationContext): [0x38] register v10 has type Reference: com.facebook.react.bridge.ReactApplicationContext but expected Reference: com.facebook.react.bridge.ReactContext (declaration of 'com.facebook.react.ReactInstanceManager' appears in /data/app/~~eX5DLdzXOBzxGydgXmfg9A==/com.zoolker-o5DCduvf6nlKtmAx8Do3Hg==/base.apk!classes7.dex)
> E/JitsiMeetSDK(29719): 	at com.facebook.react.ReactInstanceManager.builder(ReactInstanceManager.java:215)
> E/JitsiMeetSDK(29719): 	at org.jitsi.meet.sdk.ReactInstanceManagerHolder.initReactInstanceManager(ReactInstanceManagerHolder.java:289)
> E/JitsiMeetSDK(29719): 	at org.jitsi.meet.sdk.JitsiMeetView.initialize(JitsiMeetView.java:192)
> E/JitsiMeetSDK(29719): 	at org.jitsi.meet.sdk.JitsiMeetView.<init>(JitsiMeetView.java:101)
> E/JitsiMeetSDK(29719): 	... 30 more
> I/com.zoolker(29719): Thread[6,tid=29725,WaitingInMainSignalCatcherLoop,Thread*=0xb40000774fcafd10,peer=0x15d80260,"Signal Catcher"]: reacting to signal 3
> I/com.zoolker(29719):
> I/com.zoolker(29719): Wrote stack traces to tombstoned
> F/crash_dump64(30085): crash_dump.cpp:540] failed to attach to thread 1116: Permission denied
> Lost connection to device.
> Exited

I'm already added the notification icon
<img width="378" alt="image" src="https://user-images.githubusercontent.com/35397108/236777562-826ecde6-d470-46f3-ae7b-097c5c6c6718.png">

and the `implementation ('org.jitsi.react:jitsi-meet-sdk:6.0.0') { transitive = true }` and tried many solutions that I found on the internet and nothing working 

flutter doctor -v

> [✓] Flutter (Channel stable, 3.7.12, on macOS 12.5.1 21G83 darwin-x64, locale en-GB)
>     • Flutter version 3.7.12 on channel stable at /Users/rashedy/Documents/flutter
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision 4d9e56e694 (3 weeks ago), 2023-04-17 21:47:46 -0400
>     • Engine revision 1a65d409c7
>     • Dart version 2.19.6
>     • DevTools version 2.20.1
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
>     • Android SDK at /Users/rashedy/Library/Android/sdk
>     • Platform android-33, build-tools 33.0.2
>     • ANDROID_HOME = /Users/rashedy/Library/Android/sdk
>     • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 14.2)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Build 14C18
>     • CocoaPods version 1.11.3
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 2022.2)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
> 
> [✓] VS Code (version 1.78.0)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.62.0
> 
> [✓] Connected device (2 available)
>     • macOS (desktop) • macos  • darwin-x64     • macOS 12.5.1 21G83 darwin-x64
>     • Chrome (web)    • chrome • web-javascript • Google Chrome 112.0.5615.137
> 
> [✓] HTTP Host Availability
>     • All required HTTP hosts are available
> 
> • No issues found!

I know that this may be dub, but no one put the log before, and in the past there were alternative stripe packages that worked before, but today they are not

I hope the flutter_stripe team check the issue and fixing it soon

**Comment by jonasbark** [comment]
https://github.com/flutter-stripe/flutter_stripe/issues?q=jitsi
Not ours to fix.
