### ISSUE TITLE
CardFormField clips the validation message on Android

### ISSUE THREAD

**Issue by tbuczkowski** [flutter-stripe/flutter_stripe#1233]
**Describe the bug**
The validation message below the CardFormField is cut off in the same way as was reported in https://github.com/flutter-stripe/flutter_stripe/issues/1027, only this time it happens on Android instead of iOS.
<img width="408" alt="Screenshot 2023-05-09 at 15 16 41" src="https://github.com/flutter-stripe/flutter_stripe/assets/95422352/19d0398a-d037-4f8f-876f-bee3c745ea8b">

**To Reproduce**
1. Create a CardFormField widget.
2. Type an invalid card number.

**Expected behavior**
A validation error should be shown without being cut off.

**Smartphone / tablet**
 - Device: Android Emulator
 - OS: Android 12
 - Package version: 9.2.0
 - Flutter version 3.7.9

**Comment by jonasbark** [comment]
In which emulator can this be reproduced - as in its display size?

**Comment by tbuczkowski** [comment]
Here's the emulator I'm running:
<img width="330" alt="Screenshot 2023-05-11 at 08 45 32" src="https://github.com/flutter-stripe/flutter_stripe/assets/95422352/92071f65-8e39-43ef-9608-f482e1c53239">
