### ISSUE TITLE
Undefined name 'paymentMethodData'. Try correcting the name to one that is defined, or defining the name.

### ISSUE THREAD

**Issue by Emaren** [flutter-stripe/flutter_stripe#1235]
**Describe the bug**
Trying to implement a simple Stripe payment integration inn my flutter app.

**To Reproduce**
void _handlePayment() async {
  // Set up payment method
  final paymentMethod = await Stripe.instance.createPaymentMethod(
    params: PaymentMethodParams.card(paymentMethodData: paymentMethodData),
  );

  // Implement your server-side logic to create a PaymentIntent with the required parameters
  // and obtain its client secret. Replace 'your_client_secret_here' with the actual client secret.
  final clientSecret = 'your_client_secret_here';

  // Confirm the PaymentIntent
final paymentIntentResult = await Stripe.instance.confirmPayment(
    paymentIntentClientSecret: clientSecret,
    
  );

  // Handle payment result (e.g., show success message, handle errors, etc.)
}

**Expected behavior**
I want to be able to make credit card payments.

**Smartphone / tablet**
 flutter_stripe: ^9.2.0
  stripe: ^4.10.0
  stripe_platform_interface: ^9.2.0

Flutter 3.7.12 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4d9e56e694 (3 weeks ago) • 2023-04-17 21:47:46 -0400
Engine • revision 1a65d409c7
Tools • Dart 2.19.6 • DevTools 2.20.1

**Additional context**
import 'package:flutter/material.dart';
import 'package:flutter_stripe/flutter_stripe.dart';
import 'package:stripe_platform_interface/stripe_platform_interface.dart';

import 'time_tap_screen.dart';

class PaymentsScreen extends StatefulWidget {
  const PaymentsScreen({Key? key}) : super(key: key);

  @override
  _PaymentsScreenState createState() => _PaymentsScreenState();
}

class _PaymentsScreenState extends State<PaymentsScreen> {
  CardFieldInputDetails card = CardFieldInputDetails(complete: false);

  @override
  void initState() {
    super.initState();
    Stripe.publishableKey =
        "";
  }

  void _handlePayment() async {
  // Set up payment method
  final paymentMethod = await Stripe.instance.createPaymentMethod(
    params: PaymentMethodParams.card(paymentMethodData: paymentMethodData),
  );

  // Implement your server-side logic to create a PaymentIntent with the required parameters
  // and obtain its client secret. Replace 'your_client_secret_here' with the actual client secret.
  final clientSecret = 'your_client_secret_here';

  // Confirm the PaymentIntent
final paymentIntentResult = await Stripe.instance.confirmPayment(
    paymentIntentClientSecret: clientSecret,
    
  );

  // Handle payment result (e.g., show success message, handle errors, etc.)
}

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Payments'),
      ),
      body: Padding(
        padding: const EdgeInsets.symmetric(vertical: 16.0, horizontal: 16.0),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            Text(
              'Enter your card details',
              style: TextStyle(
                fontSize: 20,
                fontWeight: FontWeight.bold,
              ),
            ),
            SizedBox(height: 16),
            CardField(
              onCardChanged: (value) {
                setState(() {
                  card = value!;
                });
              },
            ),
            SizedBox(height: 16),
            ElevatedButton(
              onPressed: () {
                _handlePayment();
              },
              child: Text('Submit Payment'),
            ),
            ElevatedButton(
              onPressed: () {
                Navigator.push(
                  context,
                  MaterialPageRoute(builder: (context) => TimeTapScreen()),
                );
              },
              child: const Text('Time Tap'),
            )
          ],
        ),
      ),
    );
  }
}

**Comment by remonh87** [comment]
this is not a problem of our sdk but it seems like something is wrong in your environment. Did you run `flutter clean` & `flutter pub get`?  For a reference implementation see [link](https://github.com/flutter-stripe/flutter_stripe/blob/main/example/lib/screens/regional_payment_methods/ideal_screen.dart) .

Close the issue now but if the issue still persists feel free to reopen it and provide us with an example app where we can reproduce the issue.
