### ISSUE TITLE
Payment not completing in android

### ISSUE THREAD

**Issue by Uvais-Iocod** [flutter-stripe/flutter_stripe#1238]
**Describe the bug**
I have implemented flutter_stripe in an application. After completed all the procedures mentioned in the documentation, it works in ios finely. But in android, after entering the card details it stays incompleted

**To Reproduce**
1. Entering number 4242 4242 4242 4242 into the cardfield.
2. Tapping the pay button.
3. It remains incompleted

**Expected behavior**
Want to show completed and close the payment sheet automatically

**Smartphone / tablet**
 - Android Poco
 - OS: [Android 12]
 - Package version: 9.2.0
 - Flutter version :3.7.12

**Comment by Uvais-Iocod** [comment]
Add following dependencies in app level build.gradle

`implementation 'com.stripe:stripe-android:20.21.1'`

Now it looks like:

```
dependencies {
    implementation 'com.stripe:stripe-android:20.21.1'
}
```

**Comment by remonh87** [comment]
Great that it is solved. I would be very cautious by adding stripe sdk versions different than our plugin versions. There is no guarantee that the bindings will be compatible.
