### ISSUE TITLE
Allow using payment sheet for connect accounts.

### ISSUE THREAD

**Issue by loic-combis** [flutter-stripe/flutter_stripe#1245]
**Is your feature request related to a problem? (please describe)**
The package currently does not support opening payment sheets for connected accounts. (The payment sheet throws an error "no such payment intent").

**Describe the solution you'd like**

We would like to be able to pass the connect account id so the payment sheet can find the payment intent and proceed to the payment.

**Describe alternatives you've considered**
At the moment we can just use checkout URL payments, but the experience is not as good as the user has to leave the app top open a web page.

**Additional context**

**Comment by loic-combis** [comment]
Hello, we did try this but it did not work.

The API key provided did not have the credentials to fetch the payment intent.

**Comment by remonh87** [comment]
hey  I did some checks and there is nothing we can do in our plugin. I would recommend to contact stripe support for more help around it. Closing this for now but feel free to raise a new issue or reopen it if they say there is something wrong in our plugin.
