### ISSUE TITLE
Problem with 3dsecure

### ISSUE THREAD

**Issue by PositronicBrain** [flutter-stripe/flutter_stripe#125]
I am trying to finalize a payment with 3d secure (Android), I call ```await Stripe.instance.handleCardAction('pi_.......')``` and this opens the Stripe authentication webview. When the process is completed  the webview closes and  the app crashes with the following error:
```
E/flutter (18972): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: type 'Null' is not a subtype of type 'String' in type cast
E/flutter (18972): #0      _$_$_ShippingDetailsFromJson
package:stripe_platform_interface/…/models/payment_intents.g.dart:101
E/flutter (18972): #1      new _$_ShippingDetails.fromJson
package:stripe_platform_interface/…/models/payment_intents.freezed.dart:788
E/flutter (18972): #2      _$ShippingDetailsFromJson
package:stripe_platform_interface/…/models/payment_intents.freezed.dart:596
E/flutter (18972): #3      new ShippingDetails.fromJson
package:stripe_platform_interface/…/models/payment_intents.dart:107
E/flutter (18972): #4      _$_$_PaymentIntentFromJson
package:stripe_platform_interface/…/models/payment_intents.g.dart:27
E/flutter (18972): #5      new _$_PaymentIntent.fromJson
package:stripe_platform_interface/…/models/payment_intents.freezed.dart:374
E/flutter (18972): #6      _$PaymentIntentFromJson
package:stripe_platform_interface/…/models/payment_intents.freezed.dart:16
E/flutter (18972): #7      new PaymentIntent.fromJson
package:stripe_platform_interface/…/models/payment_intents.dart:62
E/flutter (18972): #8      MethodChannelStripe.handleCardAction
package:stripe_platform_interface/src/method_channel_stripe.dart:127
E/flutter (18972): <asynchronous suspension>
E/flutter (18972): #9      Stripe.handleCardAction
package:flutter_stripe/src/stripe.dart:207
E/flutter (18972): <asynchronous suspension>
E/flutter (18972): #10     _ReviewOrderState.build.<anonymous closure>.<anonymous closure>.processPayment
package:myapp/routes/review_order.dart:139
E/flutter (18972): <asynchronous suspension>
E/flutter (18972): #11     _ReviewOrderState.build.<anonymous closure>.<anonymous closure>.<anonymous closure>
package:myapp/routes/review_order.dart:275
E/flutter (18972): <asynchronous suspension>
E/flutter (18972):
W/cr_AwContents(18972): Application attempted to call on a destroyed WebView
W/cr_AwContents(18972): java.lang.Throwable
W/cr_AwContents(18972): 	at org.chromium.android_webview.AwContents.t(chromium-TrichromeWebViewGoogle.apk-stable-410410681:2)
W/cr_AwContents(18972): 	at Mt.loadingStateChanged(chromium-TrichromeWebViewGoogle.apk-stable-410410681:2)
```

I am not sure it this is a bug or if I am doing something wrong.

**Comment by jonasbark** [comment]
That does look like a bug. Can you describe the steps necessary to reproduce? E.g. which payment method you used etc.

**Comment by PositronicBrain** [comment]
It should be simple to reproduce. I get a payment method:
```
final paymentMethod = await Stripe.instance
       .createPaymentMethod(const PaymentMethodParams.card(
      billingDetails: billingDetails));
```
I pay using a stripe test card with 3d secure enabled: `4000000000003063`.

Then I pass `paymentMethod.id` to the backend and use the returned secret to `handleCardAction`. The authentication screens pops up, I press `validate` and then when control goes back to the app, the deserialization error happens.

**Comment by PositronicBrain** [comment]
We wrote a patch that fixes the de-serialization bug, 3d secure seems to work now and returns a payment intent, but when I call the Magento backend to confirm the payment, the process fails with message

```The provided PaymentMethod was previously used with a PaymentIntent without Customer attachment, shared with a connected account without Customer attachment, or was detached from a Customer. It may not be used again. To use a PaymentMethod multiple times, you must attach it to a Customer first.```

The same kind of flow works properly on native IOS, and on the web. Any idea why this may be?

**Comment by remonh87** [comment]
@PositronicBrain is the issue serliazation issue still there with version `1.1.0`?  I am able to do 3d secure authentication without issues.   I think the last error is related to something wrong in the backend.

**Comment by remonh87** [comment]
closed due to inactivity
