### ISSUE TITLE
google pay payment amount displaying 0 in confirmPlatformPaySetupIntent

### ISSUE THREAD

**Issue by DavidEcclesPH** [flutter-stripe/flutter_stripe#1250]
follow up to #1127 as that issue has been closed (probably due to the time I took to respond sorry!)

here is the UI for paying for the same item (a £1 a week subscription via confirmPlatformPaySetupIntent) on both platforms:
iOS correctly shows the amount, google pay still shows £0 which users will be unlikely to click as this looks like a bug!

I notice that amount within `PlatformPayConfirmParams` is a string for applePay but an int for googlePay, not sure if this an an issue. Although we use the same `PlatformPayConfirmParams` for `confirmPlatformPaySetupIntent` & `confirmPlatformPayPaymentIntent` and they display correctly for the paymentIntent but not the setupIntent.
 
![Image from iOS](https://github.com/flutter-stripe/flutter_stripe/assets/94359534/20586250-590f-499b-9873-3f76602cbe88)
![IMG_6387](https://github.com/flutter-stripe/flutter_stripe/assets/94359534/1d8190ac-3da1-4034-9f65-19e2564d183b)

**Comment by remonh87** [comment]
Thanks for reporting. Amount is displayed incorrectly as argument in our API. It should be part of createplatformpaypayment method. Google pay should get the amount displayed on the setupintent in stripe. This issue will be resolved in the next version.

**Comment by DavidEcclesPH** [comment]
great thanks @remonh87 👍

**Comment by DavidEcclesPH** [comment]
Hi @remonh87 just checking in, I have just tested with version 9.3.0 and still see google pay displaying £0 when confirming a setupIntent, should this be fixed in 9.3.0 or is this still expected? Thanks!
