### ISSUE TITLE
Pub.dev is one year and 6 commits behind

### ISSUE THREAD

**Issue by Andrflor** [flutter-stripe/flutter_stripe#1251]
![image](https://github.com/flutter-stripe/flutter_stripe/assets/32484588/413a0195-c8ba-41f1-ad03-0298b51e35df)

![image](https://github.com/flutter-stripe/flutter_stripe/assets/32484588/d828ad29-6972-4483-a405-4fdc76aa453b)

Please update the pub.dev version by bumping version because there are missing features in that one year old release.

**Comment by jonasbark** [comment]
@jamesblasco is there any need to do so?

**Comment by kishan-dhankecha** [comment]
@jonasbark Yes, we have some change now that fixes some bugs and also we have updated docs that can be helpful for new developer implementing stripe_checkout.
<img width="1236" alt="image" src="https://github.com/flutter-stripe/flutter_stripe/assets/68430205/957291db-462d-4507-b31d-4ceead760e22">

**Comment by jamesblasco** [comment]
Hey, I thought I already answered this, we are going to deprecate the `stripe_checkout` package, as Stripe now has developed new solutions that cover what Checkout was trying to achieve
   - Stripe Links for doing payments with zero integration needed
   - Stripe Payment Sheet for mobile that with very small integration you can support multiple payments in your apps
   - Stripe Payment Element for web that with very small integration you can support multiple payments in your webs

We have taken this decision to follow with the official Stripe sdks that have deprecated this feature several months ago:
https://stripe.com/docs/js/deprecated/redirect_to_checkout

**Comment by Andrflor** [comment]
Could you bump the version while deprecating it ?
Cause at the moment i cannot use the pub.dev version because it lacks some features compared to master and since this is a monorepo i have to fork stripe_checkout to be able to use it in my project.

With the bump all that trouble would be solved.

**Comment by jamesblasco** [comment]
I have published that latest version with the deprecated message, thanks for pointing that out @Andrflor.

@kishan-dhankecha you can still use Checkout without this package, in fact the new recommended approach from Stripe docs does not require any stripe library on the frontend to use this feature

https://stripe.com/docs/checkout/quickstart
