### ISSUE TITLE
Apple pay issue

### ISSUE THREAD

**Issue by MohammedShehata** [flutter-stripe/flutter_stripe#1252]
**Describe the bug**
I followed apple pay integration in this sample:
https://github.com/flutter-stripe/flutter_stripe/blob/main/example/lib/screens/wallets/apple_pay_screen_plugin.dart

and I always have this error:
"message": "You passed an empty string for 'payment_method_data[card][token]'. We assume empty values ​​are an attempt to unset a parameter; however 'payment_method_data[card][token]' cannot be unset. You should remove 'payment_method_data[card][token]' from your request or supply a non-empty value."
"type": "invalid_request_error"

as you can see:
final token = await Stripe.instance.createApplePayToken(paymentResult);

the token is always null or empty
so, what do you think about fixing this issue, the app is live now but on another console, and also the Apple app is approved by Apple.

**To Reproduce**
1. open the apple pay plugin screen
2. Confirm payment
3. always getting an error of an empty token

**Smartphone / tablet**
 - Device: [e.g. iPhone X]
 - OS: [e.g. iOS 13, Android 10]
 - Package version: 9.2.0
 - Flutter version 3.0.0

**Additional context**

**Comment by remonh87** [comment]
You need to make sure you configure the pay plugin correctly by adding the requested data in the `apple_pay_payment_profile.json`
