### ISSUE TITLE
Crash after payment sheet disappear

### ISSUE THREAD

**Issue by MohamedSayed9392** [flutter-stripe/flutter_stripe#1253]
**Describe the bug**
After entering the card data the bottom sheet disappear with this exception in the logs

[ +670 ms] D/StripeReactNative( 6646): com.stripe.android.paymentsheet.PaymentOptionResult$Succeeded cannot be cast to com.stripe.android.view.AddPaymentMethodActivityStarter$Result

**Comment by remonh87** [comment]
Can you please fill in the issue template so we can better triage the issue? We need:

- Output of `flutter doctor`
- Device details (Android version, brand, model)
- A minimum reproduction scenario (preferably with code).

**Comment by eravellaSC** [comment]
I have the same problem

I got the same error in my Flutter app, I have followed the flutter-stripe package documentation precisely but the payment sheet fails with that exception. 

## **Flutter doctor** (note that I use ```fvm``` to manage dart and flutter version)
[!] Flutter (Channel stable, 3.7.5, on Microsoft Windows [Version 10.0.22621.1702], locale en-US)
    • Flutter version 3.7.5 on channel stable 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c07f788888 (4 months ago), 2023-02-22 17:52:33 -0600
    • Engine revision 0f359063c4
    • Dart version 2.19.2
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at
    • Platform android-33-ext4, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.4.33213.308
    • Windows 10 SDK version 10.0.22000.0

[✓] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.79.1)
    • VS Code
    • Flutter extension version 3.66.0

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22621.1702]
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 114.0.1823.43

[✓] HTTP Host Availability
    • All required HTTP hosts are available

## **Device details** 

I am using the emulator listed in the Doctor, Android 12 API 31

## **Reproduce the error**

I have a "Checkout" button that opens a Dialog which prompts the user with their payment details. The dialog opening triggers the initPaymentSheet function, which retrieves the clientSecret from my server (and only the clientSecret, I am not interested in creating a Customer in Stripe). The "Confirm" button on the dialog triggers the presentPaymentSheet and then (after I have inserted a valid credit card) the sheet collapses with that exception.

I have initialized Stripe with the publishable key and double-checked all my ```await``` three times at least.

**Comment by eravellaSC** [comment]
@remonh87will you please investigate on this?
