### ISSUE TITLE
PaymentConfirmationRedirect Enum Incorrectly Using @JsonKey Instead of @JsonValue in Flutter Stripe Plugin (fixed but not added to build of last version)

### ISSUE THREAD

**Issue by rhonner** [flutter-stripe/flutter_stripe#1257]
I've identified an issue in the Flutter Stripe plugin, specifically within the stripe_js package. Currently, the PaymentConfirmationRedirect enum is using @JsonKey notation, which seems to be incorrect. It should be using @JsonValue instead. The enum is defined as follows:
`
enum PaymentConfirmationRedirect {
  always,
  @JsonKey(name: 'if_required')
  ifRequired,
}
`
The correct notation should be @JsonValue('if_required') for ifRequired. Although this issue has been addressed, the package stripe_js hasn't been updated to version 3.0.1 in the build of the parent package, which is causing a runtime error. The issue manifests when using the confirmPaymentElement function from WebStripe:
`
await WebStripe().confirmPaymentElement(
  ConfirmPaymentElementOptions(
    redirect: PaymentConfirmationRedirect.ifRequired,
    confirmParams: ConfirmPaymentParams(return_url: ''),
  ),
);
`
The ifRequired value does not return a valid value necessary for the continuation of the logic in the function.

It would be appreciated if this could be addressed in the next package update. Thank you.

To reproduce just use a PaymentElement and try to confirmPaymentElement with redirect 'ifRequired' 

**Expected behavior**
The expected is that when ifRequired, the correct value 'if_required' is passed to continue with the function.

 - Device: WEB (Chrome)
 - OS: WEB (Chrome)
 - Package version: 9.2.0
 - Flutter version 3.7.9

**Comment by remonh87** [comment]
should be fixed in 9.3.0
