### ISSUE TITLE
Apple Pay button issue

### ISSUE THREAD

**Issue by JayeshItaliya** [flutter-stripe/flutter_stripe#1258]
**Describe the bug**
My sheet is opening as per the screenshot only
But when i press on the apple pay button - the same sheet opens back again

**To Reproduce**
1. Opening up sheet
2. Pressing on the apple pay button
3. Payment sheet opens up again

**Expected behavior**
I was expecting it to take me forward to apple pay payment process

**Additional context**
The simulator is running properly and there is only one issue when i test in the real phone

**Comment by jamesblasco** [comment]
Hi @JayeshItaliya, What do you mean as per the screenshot only? Could you provide a bit more detail on the issue?

**Comment by malotolmoblers** [comment]
I think I have the same issue. please see the video:

https://github.com/flutter-stripe/flutter_stripe/assets/116058868/3b82e4b8-2921-4f54-a05a-9de95331e150

**Comment by SuryaChinnadurai1997** [comment]
Hi @JayeshItaliya, Did you fix this issue?

**Comment by remonh87** [comment]
Can someone check if this still happens with version 9.2.1?

**Comment by MohammedElotol** [comment]
@remonh87 It's not fixed even in 9.2.2

**Comment by SaadmLMC** [comment]
I am having the same issue on my iOS emulators and real devices

**Comment by remonh87** [comment]
I cannot reproduce it on my side. Can someone that has the issue run it in Xcode and provide some additional logging. Also it would be great to provide some dart code so we can try to triage it on our side.

**Comment by MohammedElotol** [comment]
**Solved for me.**
The **Apple Pay Payment Processing certificate** was wrong on the stripe account. I uploaded the correct one and it works fine now.
So, this issue probably due to configuration mistakes.
