### ISSUE TITLE
ApplePay doesn't work - 'created' field is String

### ISSUE THREAD

**Issue by kumien** [flutter-stripe/flutter_stripe#1259]
**Describe the bug**
I have used:
* Flutter 3.3.0
* Flutter Stripe 9.2.0
* Pay 1.1.0

After successful confirmation from ApplePay I run *Stripe.instance.createApplePayToken(paymentResult)* and at the end I got error from TokenData parser.

Error returned like this:

I have checked what was returned from *_methodChannel.invokeMapMethod<String, dynamic>('createApplePayToken', {'payment': payment});* and it look like "created" was returned as String. TokenData requires int and because of that the whole process failed.

**To Reproduce**
1. Enabled ApplePay Sandbox.
2. Add one of test's card.
3. Initialize payment and try to get confirmation.

**Expected behavior**
The whole process should be finished without issue.

**Smartphone / tablet**
 - Device: iPhone 8
 - OS: iOS 16.4
 - Package version: 9.2.0
 - Flutter version 3.3.0

**Additional context**
<img width="415" alt="Zrzut ekranu 2023-05-25 o 23 29 49" src="https://github.com/flutter-stripe/flutter_stripe/assets/491741/ea5561d0-e3c2-4fda-8172-ba8414894c8e">

**Comment by kumien** [comment]
Based on Stripe source inside library it is String, not int.

https://github.com/flutter-stripe/flutter_stripe/blob/9a31e1d8889bd531a1e96572aedf40a568fa7fc0/packages/stripe_ios/ios/Classes/Stripe%20Sdk/Mappers.swift#L949

**Comment by LutfiGarzon** [comment]
So we just change the value to string ?

**Comment by jamesblasco** [comment]
Hi @kumien, could you check with the new 9.2.1?

**Comment by kumien** [comment]
@jamesblasco It works fine. We can close this issue and marked it as resolved.

**Comment by jamesblasco** [comment]
Thanks!
