### ISSUE TITLE
GooglePay get OR_RIBED_07 error in 9.2.0

### ISSUE THREAD

**Issue by congfandi** [flutter-stripe/flutter_stripe#1261]
**Describe the bug**
i have been following the configuration in android. but i got this error. 

**To Reproduce**

```
 Future<void> googlePay() async {
    Stripe.publishableKey = AppEnv.stripePublish;
    Stripe.merchantIdentifier = AppEnv.stripeMerchant;
    await Stripe.instance
        .createPlatformPayPaymentMethod(
      params: const PlatformPayPaymentMethodParams.googlePay(
        googlePayParams: GooglePayParams(
          merchantCountryCode: 'us',
          currencyCode: 'usd',
          amount: 1,
        ),
        googlePayPaymentMethodParams: GooglePayPaymentMethodParams(
          billingAddressConfig: GooglePayBillingAddressConfig(
            isRequired: true,
            format: BillingAddressFormat.FULL,
            isPhoneNumberRequired: false,
          ),
          existingPaymentMethodRequired: false,
          shippingAddressConfig: GooglePayShippingAddressConfig(
            isRequired: false,
            isPhoneNumberRequired: false,
            allowedCountryCodes: ['US', 'ID', 'MY', 'SG'],
          ),
        ),
      ),
    )
        .then((value) async {
      AppNav.back();
      state.isLoading = true;
      notifyListeners();
      await _paymentController.addPayment(
        paymentRequest: PaymentRequest(
          type: 'google_pay',
          paymentMethodId: value.id,
        ),
      );
      await getPaymentMethod();
    }).catchError((err) {
      logg.d('errornya ${err.toString()}');
      ErrorResult(code: '500', message: err.toString()).showError();
    });
  }
}

```
**Expected behavior**

**Smartphone / tablet**
 - Device: android
 - OS: android 13
 - Package version: 9.2.0
 - Flutter version 3.10

**Additional context**
![Screenshot 2023-05-26 at 16 27 45](https://github.com/flutter-stripe/flutter_stripe/assets/10652810/6de32086-aa37-46ef-8000-d84f73e000ed)

**Comment by tairoroberto** [comment]
> **Describe the bug** i have been following the configuration in android. but i got this error.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> ```
>  Future<void> googlePay() async {
>     Stripe.publishableKey = AppEnv.stripePublish;
>     Stripe.merchantIdentifier = AppEnv.stripeMerchant;
>     await Stripe.instance
>         .createPlatformPayPaymentMethod(
>       params: const PlatformPayPaymentMethodParams.googlePay(
>         googlePayParams: GooglePayParams(
>           merchantCountryCode: 'us',
>           currencyCode: 'usd',
>           amount: 1,
>         ),
>         googlePayPaymentMethodParams: GooglePayPaymentMethodParams(
>           billingAddressConfig: GooglePayBillingAddressConfig(
>             isRequired: true,
>             format: BillingAddressFormat.FULL,
>             isPhoneNumberRequired: false,
>           ),
>           existingPaymentMethodRequired: false,
>           shippingAddressConfig: GooglePayShippingAddressConfig(
>             isRequired: false,
>             isPhoneNumberRequired: false,
>             allowedCountryCodes: ['US', 'ID', 'MY', 'SG'],
>           ),
>         ),
>       ),
>     )
>         .then((value) async {
>       AppNav.back();
>       state.isLoading = true;
>       notifyListeners();
>       await _paymentController.addPayment(
>         paymentRequest: PaymentRequest(
>           type: 'google_pay',
>           paymentMethodId: value.id,
>         ),
>       );
>       await getPaymentMethod();
>     }).catchError((err) {
>       logg.d('errornya ${err.toString()}');
>       ErrorResult(code: '500', message: err.toString()).showError();
>     });
>   }
> }
> ```
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Smartphone / tablet**
> 
> * Device: android
> * OS: android 13
> * Package version: 9.2.0
> * Flutter version 3.10
> 
> **Additional context** ![Screenshot 2023-05-26 at 16 27 45](https://user-images.githubusercontent.com/10652810/241179087-6de32086-aa37-46ef-8000-d84f73e000ed.png)

Look at https://pub.dev/packages/pay
in the [session]([defaultGooglePayConfigString](https://github.com/google-pay/flutter-plugin/tree/main/pay/example/lib/payment_configurations.dart#L63)) of setting up Google Pay, you must put your app in TEST or PRODUCTION mode. In the TEST mode, you can debug and try to understand your app payment flow. In PRODUCTION, you only can run payment when you build it to release.

This popup appears when you try to run an app builder to debug looking to a PRODUCTION env.

**Comment by congfandi** [comment]
Thank you @tairoroberto , i put testMode to true and its working well
