### ISSUE TITLE
Cannot compile the example, flutter 3.7.12

### ISSUE THREAD

**Issue by manzikki** [flutter-stripe/flutter_stripe#1264]
**Describe the bug**
Cannot compile. Error: ../packages/stripe/lib/src/widgets/keep_visible_on_focus.dart:35:30: Error: The getter 'View' isn't defined for the class '_KeepVisibleOnFocusState'.
 - '_KeepVisibleOnFocusState' is from 'package:flutter_stripe/src/widgets/keep_visible_on_focus.dart' ('../packages/stripe/lib/src/widgets/keep_visible_on_focus.dart').

**To Reproduce**
cd example
flutter pub get
flutter build apk --debug

**Expected behavior**
Should compile.

**Smartphone / tablet**
Any android,

**Additional context**

**Comment by remonh87** [comment]
master will only work with Flutter 3.10 and higher since Flutter introduced breaking changes. The latest version on pub.dev is still compliant with Flutter 3.10
