### ISSUE TITLE
No named parameter with the name 'includeFromJson' - payment_sheet.dart:112

### ISSUE THREAD

**Issue by danacealfonso** [flutter-stripe/flutter_stripe#1269]
**Describe the bug**
Versions from 9.0.0 to 9.2.0 produces this bug:
`Error (Xcode): ../../.pub-cache/hosted/pub.dev/stripe_platform_interface-9.2.1/lib/src/models/payment_sheet.dart:112:14: Error: No named parameter with the name 'includeFromJson'.  payment_sheet.dart:112`

The stripe_platform_interface 9.2.1 produces the bug but can't get back to 9.2.0. 

**To Reproduce**
1. Add flutter_stripe: ^9.2.0 in to dependencies
2. flutter clean && flutter pub get
3. flutter run

**Expected behavior**
It will generate the error below
<img width="1253" alt="Screenshot 2023-06-01 at 3 10 11 PM" src="https://github.com/flutter-stripe/flutter_stripe/assets/44434044/2c641c30-0a78-4398-b54a-6e1ac8835211">

**Smartphone / tablet**
 - Device: [iPhone 14 simulator, Pixel 6 pro API 33 Emulator]
 - OS: [iOS 13, Android 13]
 - Package version: [9.2.0]
 - Flutter version [3.7.12]

I tried

- flutter pub cache clean && flutter pub get
- delete .pub-cache

This bug only started when the stripe_platform_interface 9.2.1 updated while stripe_platform_interface 9.2.0 is working on my different PC.

**Comment by danacealfonso** [comment]
I solved this by renaming
.pub-cache/hosted/pub.dev/stripe_platform_interface-9.2.0 to stripe_platform_interface-9.2.1

**Comment by jonasbark** [comment]
Thanks - the missing update for the base flutter_stripe to 9.2.1 will be uploaded very soon

**Comment by remonh87** [comment]
published new version
