### ISSUE TITLE
Flutter-Strip-issue-on-Textfiled

### ISSUE THREAD

**Issue by fakhry-alnaffar** [flutter-stripe/flutter_stripe#1271]
The issue when I open the dialog strip text field has an issue 

Strip version =>  flutter_stripe: ^9.2.1

[√] Flutter (Channel stable, 3.10.2, on Microsoft Windows [Version 10.0.22621.1702], locale en-US)
    • Flutter version 3.10.2 on channel stable at C:\Users\fakhr\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9cd3d0d9ff (12 days ago), 2023-05-23 20:57:28 -0700
    • Engine revision 90fa3ae28f
    • Dart version 3.0.2
    • DevTools version 2.23.1

- this widget :
CardField(
          decoration: inputDecoration(),
          controller: controller.cardEditController,
          enablePostalCode: false,
          style: const TextStyle(color: Colors.black),
        ),

- I test to wrap widgets with IgnorePointer it's solved but the text field is not working because I wrap with IgnorePointer
- please check the issue as soon as possible

![042eb398-74fc-4b65-8fb2-d156c24b2e52](https://github.com/flutter-stripe/flutter_stripe/assets/88714248/ffc408a8-5ae5-48b1-89b9-e11020d05705)

![WhatsApp Image 2023-05-11 at 18 20 37](https://github.com/flutter-stripe/flutter_stripe/assets/88714248/44cd0fb9-3cb4-4b9b-9161-900629bf4ccd)

**Comment by jonasbark** [comment]
this looks like a bug in Flutter itself. 

I recommend the following:
- start an issue in the official flutter repository with a reproducible example
- do not overlay the card field with anything else for now
