### ISSUE TITLE
googlepay_button_content missing stripe flutter

### ISSUE THREAD

**Issue by anooravk** [flutter-stripe/flutter_stripe#1272]
I was trying to take my app to production so I changed the subscriptions from test to live and changed keys accordingly and now I encountered this error 

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     ERROR:/Users/mac/Downloads/test/build/stripe_android/intermediates/packaged_res/debug/layout/plain_googlepay_button.xml:10: AAPT: error: resource drawable/googlepay_button_content (aka com.mycompany.test:drawable/googlepay_button_content) not found.

**Comment by jonasbark** [comment]
can you provide a reproducible example?
