### ISSUE TITLE
Plugin not building. 

### ISSUE THREAD

**Issue by pneves001** [flutter-stripe/flutter_stripe#1273]
I can't get this plugin to build. 

**Describe the bug**
../../../.pub-cache/hosted/pub.dev/stripe_platform_interface-9.2.1/lib/src/models/payment_sheet.dart:112:14: Error: No named parameter with the name 'includeFromJson'.
    @JsonKey(includeFromJson: false, includeToJson: false)
             ^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/json_annotation-4.7.0/lib/src/json_key.dart:118:9: Context: Found this candidate, but the arguments don't match.
  const JsonKey({
        ^^^^^^^
Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

**Comment by jonasbark** [comment]
did you manually edit the payment_sheet.dart file and changed JsonKey to jsonkey?

**Comment by t09tanaka** [comment]
@pneves001 I got same error with `json_annotation: 4.7.0`.
`4.7.0` doesn't have `includeToJson` and `includeFromJson` in the decorator.
After I update it to 4.8.1, it solved.

```
json_annotation: ^4.8.1
```

I updated `flutter_stripe` from v6 to v9.2.1 today, so I don't know how long ago I had this dependency issue.

**Comment by jonasbark** [comment]
@remonh87 `json_annotation: ^4.7.0` should probably be updated in `stripe_platform_interface` or am I mistaken?
