### ISSUE TITLE
Flutter Android app name changed to "SECURE CHECKOUT"

### ISSUE THREAD

**Issue by demsey2** [flutter-stripe/flutter_stripe#1278]
I am not sure what is wrong, but the app name in Android shows "SECURE CHECKOUT" instead of my own app name.

I use flutter_stripe: ^7.0.0

Tried Google and Github issues, but I don't see anyone with a similar problem.

**Comment by demsey2** [comment]
I found that in many files inside my build directory

build/stripe_android/intermediates/merged_res/release/values-en/values-en.xml

 <string name="stripe_3ds2_hzv_header_label">Secure Checkout</string>

The only way to get that working was to add this to AndroidManifest.xml
```
<application
        android:label="My app name"
        tools:replace="android:label"
.....

**Comment by remonh87** [comment]
can you upgrade to a later version of our library?

**Comment by demsey2** [comment]
I upgraded but that didn't help. The only thing that worked was
```
<application
        android:label="My app name"
        tools:replace="android:label"
.....
```

**Comment by jamesblasco** [comment]
From what I can see in the android library "Secure Checkout" is only used for when using 3DS authorization 
<img width="252" alt="Screenshot 2023-06-17 at 11 40 37" src="https://github.com/flutter-stripe/flutter_stripe/assets/19904063/e6c9b25e-5c35-47ae-91ee-c1c2c1ea31e3">

https://github.com/stripe/stripe-android/blob/53e6a5de49715f62d2443807fe37b9fbf4a1e330/payments-core/res/layout/stripe_payment_auth_web_view_activity.xml#L35

- I've created a new Flutter project, added Flutter Stripe and it does not modify the name.
- The example app does not modify the name after navigating to the 3DS web view that contain that name

Could you delete the app from your test phone, install it again and check if the name is "Secure Checkout" from the start? 

Could it be any android native configuration that you could have setup and affecting the app name? Was ` tools:replace="android:label"` added by you, is there any other replacement affecting the AndroidManifest.xml?

**Comment by demsey2** [comment]
1. I tried to install the app again, but the issue still exists
2. I am not sure about any Android native configuration
3. Yes, `tools:replace="android:label"` was added by me and that fixed the problem
