### ISSUE TITLE
Improve Web Support Documentation

### ISSUE THREAD

**Issue by julianfalcionelli** [flutter-stripe/flutter_stripe#1279]
It's not clear what features are supported in Flutter Web. I think that being one of the world's most widely used payment services needs some decent documentation and prevents programmers from wasting unnecessary time. Thank you.

**Comment by remonh87** [comment]
@julianfalcionelli  thanks for giving feedback we try to do our best in providing good documentation and I agree we can improve on the web.  Keep in mind this is not an official stripe package (we have some collaboration with them) and we do maintenance on this package in our free time.

**Comment by julianfalcionelli** [comment]
@remonh87 my bad, though it was an official repository. Thanks for your support.
