### ISSUE TITLE
Dependency problem

### ISSUE THREAD

**Issue by Softmatech** [flutter-stripe/flutter_stripe#128]
I can't add the dependencies on my project,
when I added the dependency I got this
<img width="1280" alt="Screen Shot 2021-06-08 at 4 04 15 PM" src="https://user-images.githubusercontent.com/29921959/121250333-9dd97300-c873-11eb-9eb9-350b2c29c622.png">

**Comment by remonh87** [comment]
You are having an older version of firebase storage. If you update it to the latest version `8.1.1.` they use the same http version as us.

**Comment by jamesblasco** [comment]
I am not aware that we use `http` package anywhere except the example project. So this might be a problem that when adding `flutter_stripe`, you called ` flutter pub upgrade` instead of ` flutter pub get` and your previous dependencies have been updated causing a conflict between them
