### ISSUE TITLE
Crashes when going back from validating 3DS process

### ISSUE THREAD

**Issue by alextarrago** [flutter-stripe/flutter_stripe#1281]
**Describe the bug**
When going back from validating the 3DS process we get:

`java.lang.RuntimeException: Unable to start activity ComponentInfo{com.XXX.XXX/com.XXX.XXX.MainActivity}: androidx.fragment.app.Fragment$k: Unable to instantiate fragment g8.o0: could not find Fragment constructor`

**To Reproduce**
1. When handlingNextAction (Validating 3DS process)
2. Validating the process with Bank's app
3. Going back to the app, crashes.

**Expected behavior**
To proceed with the validation and not to crash.

**Smartphone / tablet**
 - Device: Real Android devices on release (last library version)

**Comment by jonasbark** [comment]
Is this reproducible in debug mode? It looks like your crash report is from a released app, thus the scrambled class names

**Comment by alextarrago** [comment]
No, since in debug we don't open the bank app for validating the 3DS process. Any clue?

**Comment by jonasbark** [comment]
Why not? There are special test credit cards that do require 3DS

**Comment by alextarrago** [comment]
Yes but they don't require to exit the current app and go back once the validation on the bank has been done.

**Comment by remonh87** [comment]
Cannot reproduce this anymore
