### ISSUE TITLE
The description of the product in apple pay and google pay is wrong.

### ISSUE THREAD

**Issue by alidev0** [flutter-stripe/flutter_stripe#1284]
The description of the product in apple pay and google pay is wrong. It says Pay Smth when we need to say HOLD payment.

![rrr](https://github.com/flutter-stripe/flutter_stripe/assets/55884589/0e9d5ae4-ba61-4d96-bad0-37fb1895ca6b)

**Comment by remonh87** [comment]
Can you follow the issue template and provide us with some reproduction steps so we can properly triage the issue?
