### ISSUE TITLE
Not able to use Stripe.buildWebCard properly in flutter web

### ISSUE THREAD

**Issue by rahulrmishra** [flutter-stripe/flutter_stripe#1285]
In my mobile app, I'm able to use `CardFormField` but in web Stripe.buildWebCard doesn't work properly

In the console, I'm getting the following message:

Height of Platform View type: [stripe_card] may not be set. Defaulting to height: 100%.
Set style.height to any appropriate value to stop this message.
Width of Platform View type: [stripe_card] may not be set. Defaulting to width: 100%.
Set style.width to any appropriate value to stop this message.

In the mobile app, the `CardFormField` is properly displayed:

```dart
CardFormField(
  enablePostalCode: false,
  controller: controller,
  style: CardFormStyle(
    borderColor: Colors.blueGrey,
    placeholderColor: AppColors.k949494,
    textColor: AppColors.k949494,
  ),
)
```
In the Flutter web app, the code used is Stripe.buildWebCard and it is displayed in a single line:

```dart
Stripe.buildWebCard(
  controller: c,
  height: MediaQuery.of(context).size.height,
  width: MediaQuery.of(context).size.width,
  onCardChanged: (details) {},
  enablePostalCode: false,
)
```
The constraints property doesn't have any effect.

I'm experiencing this issue and seeking assistance to properly display the Stripe.buildWebCard in the web app. Any guidance or suggestions would be appreciated.

**Comment by rahulrmishra** [comment]
@jamesblasco Thank you for the information. 
Is it possible to change the layout of **CardFormField** ? 
Like in this image 
![](https://b.stripecdn.com/docs-statics-srv/assets/appearance_example.4957e97d8fe29ee99b9a62eefd954b76.png)

**Comment by rahulrmishra** [comment]
@jamesblasco But in that case, I need to pass the client secret which I can get from payment intent. In my case I just want to show the UI and then tokenize it give it to my server for further handling.

**Comment by jamesblasco** [comment]
That is the only way it is allowed to use this element in web, it requires a client secret.
https://stripe.com/docs/payments/payment-element
https://stripe.com/docs/js/elements_object/create

If you need to tokenize the card you can use the `CardField`, but take into account that this flow is consider legacy and could be removed at some point in the future by Stripe
