### ISSUE TITLE
create card token?

### ISSUE THREAD

**Issue by wesleyxiao** [flutter-stripe/flutter_stripe#129]
i am using stripe connect, possible to create create payment intent id by credit card in flutter, and then charge on backend?

**Comment by Riscait** [comment]
Likewise, I tried to migrate from the `stripe_payment` plugin, but I couldn't find any method that could create a card token.
If there is a plan to implement this, or if there is an alternative method, I would like to know about it.

**Comment by wesleyxiao** [comment]
> Likewise, I tried to migrate from the `stripe_payment` plugin, but I couldn't find any method that could create a card token.
> If there is a plan to implement this, or if there is an alternative method, I would like to know about it.

first use  CardField(
                        autofocus: true,
                        enablePostalCode: true,
                        onCardChanged: (card) {}); to build credit card form,

and then you can do

  Stripe.instance.createPaymentMethod(PaymentMethodParams.card()).then((value) {print(value)}; you will get payment method information json with payment method id, which is token like old version.
