### ISSUE TITLE
I want to use BacsDebit but it is not showing here

### ISSUE THREAD

**Issue by dishankmicrasol** [flutter-stripe/flutter_stripe#1298]
**Describe the bug**
I want to use BacsDebit but it is not showing here.
 
![Screenshot 2023-07-05 at 3 22 03 PM](https://github.com/flutter-stripe/flutter_stripe/assets/126647606/aec49e2f-642f-4f1c-ba9e-3174cb498b2d)

 

**Expected behavior**
I didn't get BacsDebit in this package.

**Comment by remonh87** [comment]
BasDEbit is not available on the stripe sdk for mobile. You can only use it on the web by using the payment element: https://stripe.com/docs/payments/bacs-debit/accept-a-payment?platform=web
