### ISSUE TITLE
Get  Unhandled Exception: PlatformException when try to use Stripe.instance.presentPaymentSheet

### ISSUE THREAD

**Issue by Mikhail-Ivanou** [flutter-stripe/flutter_stripe#130]
**Describe the bug**
I get next error when try to use Stripe.instance.presentPaymentSheet both in Android and iOS.
The same issue was reproduced both in my project and in sample 

E/flutter ( 1124): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(Failed, , null, null)
E/flutter ( 1124): #0      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:155:7)
E/flutter ( 1124): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
E/flutter ( 1124): <asynchronous suspension>
E/flutter ( 1124): #2      MethodChannelStripe.presentPaymentSheet (package:stripe_platform_interface/src/method_channel_stripe.dart:181:5)
E/flutter ( 1124): <asynchronous suspension>
E/flutter ( 1124): #3      Stripe.presentPaymentSheet (package:flutter_stripe/src/stripe.dart:268:5)
E/flutter ( 1124): <asynchronous suspension>
E/flutter ( 1124): #4      _CampContent.build.<anonymous closure>.<anonymous closure> (package:___/ui/detail/checkout_screen.dart:58:11)
E/flutter ( 1124): <asynchronous suspension>

**To Reproduce**
1. Setup stripe, generate "paymentIntentClientSecret"
2. Init Stripe.instance.initPaymentSheet:
 await Stripe.instance.initPaymentSheet(
        paymentSheetParameters: SetupPaymentSheetParameters(
          applePay: true,
          googlePay: true,
          style: ThemeMode.dark,
          testEnv: true,
          merchantCountryCode: 'DE',
          merchantDisplayName: 'Flutter Stripe Store Demo',
          paymentIntentClientSecret: '%paymentIntentClientSecret%',
        ),
      );
3. Call  await Stripe.instance.presentPaymentSheet(
          parameters: PresentPaymentSheetParameters(
        clientSecret: '%paymentIntentClientSecret%',
        confirmPayment: true,
      ));

**Expected behavior**
User see correct payment modal sheet

**Smartphone / tablet**
 - Device:  iPhone 8+ emulator, pixel 3a emulator
 - OS: iOS 14, Android 11
 - Package version: 1.0.2
 - Flutter version: 2.2.1

**Additional context**

**Comment by jonasbark** [comment]
Can you reproduce this issue in the example app?

**Comment by Mikhail-Ivanou** [comment]
Yes, I have the same error in example app too. 
I see white bottom sheet with progress indicator for a while and than SnackBar with error appears. 
![image](https://user-images.githubusercontent.com/3472560/121333961-eea7a500-c921-11eb-9bc5-0b9b7fe6bf2e.png)

**Comment by jamesblasco** [comment]
Yeah probably it is related to the clientSecret. 

How do you retrieve the code from your server? Are you using the example one? The secret needs to be a valid one

**Comment by Mikhail-Ivanou** [comment]
It's our backend responsibility to create clientSecret, and it works correctly in our web client.  I've found issue in combination of publisherKey and clientSecret, so there is no more issue for us. 

Thanks for help.

BTW, it would be great to get correct error message for incorrect params, not platform channel crash.

**Comment by jamesblasco** [comment]
Yes in the next sync with the native sdk we will try to improve the errors to make theme more descriptive 👍🏻. Thank you for the feedback
