### ISSUE TITLE
paymentIntent.lastPaymentError || There was an error confirming the intent.

### ISSUE THREAD

**Issue by rohanots** [flutter-stripe/flutter_stripe#1301]
**Describe the bug**
Not able to do a simple payment using payment with Stripe flutter.

**To Reproduce**
Integration of the stripe sdk in flutter.

My Code:
  createPaymentIntent(String amount, String currency) async {
    try {
      //Request body
      Map<String, dynamic> paymentPayload = {
        'amount': calculateAmount(amount),
        'currency': currency,
      };

      //Make post request to Stripe
      var response = await apiClient.commonPostAPIMethod(
        'https://api.stripe.com/v1/payment_intents',
        {
          'Authorization': 'Bearer ${dotenv.env['STRIPE_SECRET']}',
          'Content-Type': 'application/x-www-form-urlencoded'
        },
        paymentPayload,
      );
      // print("payment payload $response");
      return response;
    } catch (err) {
      throw Exception(err.toString());
    }
  }
  
 //STEP 2: Initialize Payment Sheet
      await Stripe.instance
          .initPaymentSheet(
              paymentSheetParameters: SetupPaymentSheetParameters(
                  paymentIntentClientSecret: "pi_3NQsIjSAQhd1pas51oxZ5oZI_se********",
                  style: ThemeMode.dark,
                  merchantDisplayName: 'WCI'))
          .then((value) {});
          
  //STEP 3: Display Payment sheet
      await Stripe.instance.presentPaymentSheet();       

**Expected behavior**
A clear and concise description of what you expect
![MicrosoftTeams-image (14)](https://github.com/flutter-stripe/flutter_stripe/assets/86669706/3a688d2f-d153-44c5-b51c-a6fa65e2d9a4)
ed to happen.

Version Details:
flutter_stripe: ^8.0.0
Flutter version - Stable 3.7.10

**Additional context**

**Comment by remonh87** [comment]
This error is coming from Stripe itself and has nothing to do with our sdk. I would recommend contacting support and double check the payment intent the backend created  in the stripe dashboard.
