### ISSUE TITLE
How to migrate from using createTokenWithCard?

### ISSUE THREAD

**Issue by joknjokn** [flutter-stripe/flutter_stripe#131]
Hi,

With stripe_payment we used createTokenWithCard() to create a card and store it in the backend with the returned token-id tok_XXXXXX.

From the migration guide I see that we now have to use createPaymentMethod, but this returns a payment-method id like pm_XXXXXX. This means that our implementation now fails. 

So my question is: Is there any way we can get the tok_XXXXX instead of the pm_XXXXXX ?

We are storing the cards for later use - not direct payment in the app.

- Jonas

**Comment by jonasbark** [comment]
A similar function will be available when https://github.com/flutter-stripe/flutter_stripe/issues/104 is resolved

**Comment by joknjokn** [comment]
Perfect - Thanks for the quick response.

**Comment by thorsten-stripe** [comment]
@joknjokn you might want to consider updating your backend though. Tokens are considered legacy: https://stripe.com/docs/payments/payment-intents/migration

**Comment by wesleyxiao** [comment]
https://github.com/flutter-stripe/flutter_stripe/issues/129#issuecomment-857963764

solve card token issue.

**Comment by joknjokn** [comment]
@thorsten-stripe Yes, thanks, we will do that in near future.

**Comment by Riscait** [comment]
I'm migrating from stripe_payment as well, so I want to use `createTokenWithCard` to get the cardToken.
I found the Issue (104) to track. Thank you very much.

**Comment by thorsten-stripe** [comment]
@Riscait Tokens are considered legacy, please migrate to PaymentIntents: https://stripe.com/docs/payments/payment-intents/migration

**Comment by gocal** [comment]
Agree with @thorsten-stripe however PaymentIntents require significant changes on both backend and fronted side, so I believe we should still keep it as an intermediate solution. 
I've noticed @remonh87 is already working on that - https://github.com/flutter-stripe/flutter_stripe/tree/implement-create-token so hopefully we'll get the missing API soon...

**Comment by joknjokn** [comment]
If possible, please let me know if this is delayed further or similar. This is currently our only release blocker for our Flutter2-upgrade  (and our backend migration away from tokens can take months, I'm told.).

**Comment by jonasbark** [comment]
Merged and published
