### ISSUE TITLE
Cash App Pay doesn't work & Enable We Chat Pay

### ISSUE THREAD

**Issue by yasin1376** [flutter-stripe/flutter_stripe#1313]
I want to integrate cash app pay in my flutter app using this package but it shows the cash app payment type is not supported yet.

when this issue will solve it?

**Comment by remonh87** [comment]
It is supported in the native stripe so it should be quite easy for us to create bindings. Maybe we can take it along for the next release

**Comment by yasin1376** [comment]
When should be the next release?

**Comment by yasin1376** [comment]
Please enable We Chat Pay as well in the next release if possible.

**Comment by remonh87** [comment]
we chat pay will not be supported by our sdk because of: https://github.com/stripe/stripe-react-native/issues/1179

**Comment by yasin1376** [comment]
> we chat pay will not be supported by our sdk because of: [stripe/stripe-react-native#1179](https://github.com/stripe/stripe-react-native/issues/1179)

Ok, when will be the next release?
