### ISSUE TITLE
CreateToken with card gives the error

### ISSUE THREAD

**Issue by Usamakabir07** [flutter-stripe/flutter_stripe#1314]
**Issue**
Whenever i'm trying to generate token from credit card, it gives the following error

Error: Unexpected null value.
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 288:49        throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 606:63    nullCheck
packages/flutter_stripe_web/src/web_stripe.dart 85:20                               _createCardPaymentMethod
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                  runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                  _async
packages/flutter_stripe_web/src/web_stripe.dart 82:49                               [_createCardPaymentMethod]
packages/flutter_stripe_web/src/web_stripe.dart 74:16                               <fn>
packages/stripe_platform_interface/src/models/payment_methods.freezed.dart 3281:18  maybeWhen
packages/flutter_stripe_web/src/web_stripe.dart 72:16                               createPaymentMethod

**Comment by remonh87** [comment]
can you give us a reproducible scenario? Also make sure to comply to our issue template. It will be very hard for us to provide proper support with this.
