### ISSUE TITLE
IOS Build is Faild

### ISSUE THREAD

**Issue by mostafaalimorsy** [flutter-stripe/flutter_stripe#1317]
when I build the project on the IOS platform I got this issue:
 "CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/c/e/7/Stripe/11.3.0/Stripe.podspec.json Response: SSL connect error",
however on Android it is work 

flutter_stripe: ^9.2.2

I use simulator IOS 16.1 and platform: ios, '13.0'

**Comment by remonh87** [comment]
did you set the min sdk in the pod file like: https://github.com/flutter-stripe/flutter_stripe/blob/9361711a501c3b2238677c8b7712490d1a1b18ee/example/ios/Podfile#L2C3-L2C3.  ?
