### ISSUE TITLE
I can not find Coupon

### ISSUE THREAD

**Issue by mostafaalimorsy** [flutter-stripe/flutter_stripe#1320]
I can not find how to show Coupon Field on initPaymentSheet!!

**Comment by mostafaalimorsy** [comment]
no, I built it manually

**Comment by remonh87** [comment]
can you give more information why you expect a coupon field? The stripe sdk is more intended for collecting payment information. Coupons are normally applied before you start the payment process.

**Comment by EliaTolin** [comment]
> can you give more information why you expect a coupon field? The stripe sdk is more intended for collecting payment information. Coupons are normally applied before you start the payment process.

https://stripe.com/docs/payments/checkout/discounts

**Comment by mostafaalimorsy** [comment]
okay how to show the discount field!!! on 
Stripe.instance
          .initPaymentSheet(
        paymentSheetParameters: SetupPaymentSheetParameters()

**Comment by remonh87** [comment]
@EliaTolin thanks but Checkout on web is not the paymentsheet but sth entirely different.  Coupons are not supported by the mobile sdk of stripe see: https://github.com/stripe/stripe-android/issues/5630

We need to wait for them to fix it. In the mean time you need to implement promotional activities by yourself.  Will mark it as feature request

**Comment by mostafaalimorsy** [comment]
I appreciate that, thanks for helping me and for your time.
@remonh87 @EliaTolin
