### ISSUE TITLE
After confirm payment it throw a exception

### ISSUE THREAD

**Issue by EliaTolin** [flutter-stripe/flutter_stripe#1321]
**Describe the bug**
After complete payment stripe throw a Exception

**To Reproduce**
1. Entering number 4242 4242 4242 4242 into the cardfield.
2. Tapping the confirm button.
3. Observe a failure with exception (including the part of the stack trace, belonging to this package) …

**Smartphone / tablet**
 - Device: iPhone14 Simulator
 - OS: 16.4
 - Package version: 9.3.0
 
  Flutter 3.10.6 • channel stable • https://github.com/flutter/flutter.git
  Framework • revision f468f3366c (7 giorni fa) • 2023-07-12 15:19:05 -0700
  Engine • revision cdbeda788a
  Tools • Dart 3.0.6 • DevTools 2.23.1

**Additional context**
Code: 
```
 Future<void> initStripe() async {
    if (paymentDataKey != null) {
      await Stripe.instance.initPaymentSheet(
        paymentSheetParameters: SetupPaymentSheetParameters(
          // Main params
          merchantDisplayName: PaymentConstants.merchantDisplayName,
          paymentIntentClientSecret: paymentDataKey?.clientSecret,
        ),
      );
    } else {
      throw Exception();
    }
  }

  Future<bool> openPaymentSheet() async {
    try {
      await Stripe.instance.presentPaymentSheet();
      return true;
    } catch (error, stacktrace) {
      if (error is StripeException) {
        if (error.error.code == FailureCode.Canceled) {
          return false;
        }
      }
      log(error.toString());
      log(stacktrace.toString());
      throw Exception();
    }
  }
```

Exception: 
`type 'List<dynamic>' is not a subtype of type 'Map<String, dynamic>?'`

Stacktrace: 
```
MethodChannelStripe.presentPaymentSheet (package:stripe_platform_interface/src/method_channel_stripe.dart:263:37)
      <asynchronous suspension>
      #1      Stripe.presentPaymentSheet (package:flutter_stripe/src/stripe.dart:517:12)
      <asynchronous suspension>
      #2      SlotPaymentController.openPaymentSheet (package: foo/controller/payment/slot_payment_controller.dart:40:7)
      <asynchronous suspension>
      #3      _SlotPaymentPageState.openPayment (package:foo/pages/payment/slot_payment_page.dart:164:11)
      <asynchronous suspension>

```

**Comment by jorger5** [comment]
This happened to me to, on `v9.3.0`. Reverted back to `v9.2.2` as a workaround and

```
dependency_overrides: 
  stripe_platform_interface: 9.2.2
  ```

**Comment by EliaTolin** [comment]
> This happened to me to, on `v9.3.0`. Reverted back to `v9.2.2` as a workaround and
> 
> ```
> dependency_overrides: 
>   stripe_platform_interface: 9.2.2
> ```

Have you find where is the problem? We make a PR if we fix it.

**Comment by jorger5** [comment]
I guess the problem is in this file [method_channel_stripe.dart](https://github.com/flutter-stripe/flutter_stripe/blob/main/packages/stripe_platform_interface/lib/src/method_channel_stripe.dart#L310) specifically in the method `_parsePaymentSheetResult`.

From what the error says, there's a type error as `_parsePaymentSheetResult` expects a `Map<String,dynamic>?` and it's receiving a `List<dynamic>`. 

Not sure about this change but that result comes from iOS method channel (haven't testing in Android if it happens).

**Comment by EliaTolin** [comment]
> I guess the problem is in this file [method_channel_stripe.dart](https://github.com/flutter-stripe/flutter_stripe/blob/main/packages/stripe_platform_interface/lib/src/method_channel_stripe.dart#L310) specifically in the method `_parsePaymentSheetResult`.
> 
> From what the error says, there's a type error as `_parsePaymentSheetResult` expects a `Map<String,dynamic>?` and it's receiving a `List<dynamic>`.
> 
> Not sure about this change but that result comes from iOS method channel (haven't testing in Android if it happens).

In Android devices it works fine.
I'm not a native developer, but here the function `confirmPaymentSheetPayment` resolve the function with `[]`, maybe is it this the problem? 

[StripeSdk.swift](https://github.com/flutter-stripe/flutter_stripe/blob/63ab342639d9f3248bcdbd50cccac6fbd6142577/packages/stripe_ios/ios/Classes/Stripe%20Sdk/StripeSdk.swift#L143C28-L143C28)

**Comment by jorger5** [comment]
I'll check it out to see if I can make a quick fix / PR

**Comment by EliaTolin** [comment]
Yes, you can add me to co-author to your PR.

**Comment by jorger5** [comment]
Here's the quick fix https://github.com/flutter-stripe/flutter_stripe/pull/1325 !

**Comment by EliaTolin** [comment]
> Here's the quick fix #1325 !

Please add me co-authored

**Comment by RRosalia** [comment]
When will it be published and available for install through pubspec?

**Comment by tbuczkowski** [comment]
Any updates on releasing a fix to this issue? Frankly it's ridiculous, that a fix has been ready for over a month and hasn't been released yet, given this issue is pretty much a blocker.

**Comment by lucagiordano-visia** [comment]
> Any updates on releasing a fix to this issue? Frankly it's ridiculous, that a fix has been ready for over a month and hasn't been released yet, given this issue is pretty much a blocker.

I had to import both on my pubspec.yaml
`  flutter_stripe: ^9.3.0
  stripe_ios: ^9.3.1
`
