### ISSUE TITLE
How to change the cursor color in PaymentSheet?

### ISSUE THREAD

**Issue by ShrijeetHz** [flutter-stripe/flutter_stripe#1329]
There is no option for changing cursor color in appearance. i have a white background and due to this cursor color is getting mixed with it and looks invisible

**Comment by remonh87** [comment]
correct we need to wait for this to be implemented in the stripe sdk. https://github.com/stripe/stripe-react-native/issues/1075

**Comment by remonh87** [comment]
this should be fixed in the latest sdk
