### ISSUE TITLE
_retrievedPaymentIntent not null, but without paymentMethodId

### ISSUE THREAD

**Issue by ApofisXII** [flutter-stripe/flutter_stripe#133]
During a test with the Card that require authentication even during following payments:

While implementing the example, I found a bizarre issue here: 
https://github.com/flutter-stripe/flutter_stripe/blob/b8615d7f3d1e437eb6d4ed0516c0d2a3b0a6da84/example/lib/screens/setup_future_payment_screen.dart#L182

At line 182, the condition is false, because:
_retrievedPaymentIntent is not null
_card is not null
but **_retrievedPaymentIntent!.paymentMethodId is surprisingly null**!

I printed the _retrievedPaymentIntent.id and looked it up on the Stripe Dashboard, and it was valid with a paymentMethod id.

**The problem is that** `Stripe.instance.retrievePaymentIntent(clientSecret)` returns a **valid** paymentIntent but **without** the paymentMethodId (but online it has a payment method id).

**Smartphone**
 - Device: OnePlus 5
 - OS: Android 10
 - Package version: 1.0.2 and 1.0.1 both have the same issue
 - Flutter version: 2.3.0

(this code only runs when the card need authorisation for each payment)
(Stripe was here used in demo mode with a demo card that requires auth for each payment)

**Comment by remonh87** [comment]
I can reproduce the issue will look into it.
