### ISSUE TITLE
Api android Deprected

### ISSUE THREAD

**Issue by jailsondamasceno** [flutter-stripe/flutter_stripe#1330]
Note: /Users/*******/.pub-cache/hosted/pub.dev/stripe_android-9.3.0/android/src/main/kotlin/com/facebook/react/uimanager/DisplayMetricsHolder.java uses or overrides a deprecated API.
![image](https://github.com/flutter-stripe/flutter_stripe/assets/65731201/ed305594-1513-4047-87cf-f373aa31fb8a)

**Comment by remonh87** [comment]
this is out of our hands as we are dependent on what Stripe implements . I will label it as blocked for now

**Comment by Avoracity** [comment]
Encountering same issue regarding stripe_android. It is preventing application build 
and throws error in regards to the jvmTarget if the deprecated API warning is ignored. 

![image](https://github.com/flutter-stripe/flutter_stripe/assets/28462139/324400ab-88df-4f09-aab3-e8531d26a5d4)

**Comment by knatnaela** [comment]
> Encountering same issue regarding stripe_android. It is preventing application build and throws error in regards to the jvmTarget if the deprecated API warning is ignored.
> 
> ![image](https://private-user-images.githubusercontent.com/28462139/259187906-324400ab-88df-4f09-aab3-e8531d26a5d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5Njg1MzEsIm5iZiI6MTcwMjk2ODIzMSwicGF0aCI6Ii8yODQ2MjEzOS8yNTkxODc5MDYtMzI0NDAwYWItODhkZi00ZjA5LWFhYjMtZTg1MzFkMjZhNWQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDA2NDM1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2OTMyMjM3Y2I4YWUyOWI0ZWE5ZWEwY2UzZjNjMjFkMDRlZTJiMjk3ZjI2MDgzODlkMjczNTNlMGZkMmI5NjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.14wkfdJWhSocjX4GnLE7ICyyEvSMS_Q4hLfFIxbktZs)

Any Solution for this?

**Comment by remonh87** [comment]
this is fixed as we support latest greatest depedencies on android
