### ISSUE TITLE
google pay displays 0 amount when confirming setupIntent

### ISSUE THREAD

**Issue by DavidEcclesPH** [flutter-stripe/flutter_stripe#1339]
**Describe the bug**
relates to https://github.com/flutter-stripe/flutter_stripe/issues/1250 but i'm commenting here for visibility as that issue is closed. Google pay still displays 0 amount when confirming a subscription payment via confirmSetupIntent. We noticed the branch fix-amount-google-pay #1255 did not get merged to the last release is it expected in a release in the near future?

**To Reproduce**
use google pay to pay for a subscription (confirm setupupintent)

**Expected behavior**
google pay UI shows the amount relating to the subscription, not £0

**Smartphone / tablet**
 - Device: multiple android devices
 - OS: > android 8.1 
 - Package version: 9.3.0
 - Flutter version [e.g. 2.0.0.]

**Comment by DavidEcclesPH** [comment]
@remonh87 @jamesblasco would you be able to provide us an eta on this issue? We tried to fork the repo to merge the [fix-amount-google-pay] branch ourselves but couldn't build our project pointing to the forked repo.

**Comment by remonh87** [comment]
hey I did test it and I think we need to wait for https://github.com/stripe/stripe-react-native/issues/1436. I will poke stripe to look into it

**Comment by remonh87** [comment]
as alternative you can maybe use `createPlatformPayPaymentMethod`

**Comment by DavidEcclesPH** [comment]
morning @remonh87 just checking back in on this, wondering if there is any expected updates here? Not sure where the change came in but Google pay now shows no amount/description label at all when confirming setupIntent. I had a look at the https://github.com/stripe/stripe-react-native/issues/1436 issue you mentioned above and see it's resolved, does that pave the way for a fix here? Appreciate there may be higher priorities but let me know if there's any plans to look at this, cheers!

**Comment by remonh87** [comment]
@DavidEcclesPH yes this is indeed solved because we  are up to date on Stripe. Sorry for forgetting to close this issue
