### ISSUE TITLE
More explicit documentation on how to proceed with subscriptions

### ISSUE THREAD

**Issue by rlazom** [flutter-stripe/flutter_stripe#1343]
Almost all documentation available for the plugin is centered in checkouts. Could you please include END TO END example on how to use the plugin to create a subscription?

Additional use case:
- Also how to include Pay Wallets (Apple and Google) to create a subscription.

This would be extremely helpful for all developers how are struggling with this like me... At the end I just decided to use directly the API rest provided by Stripe, but I would prefer to use the plugin methods and UI.
For sure I will migrate my current implementation if this is added in the readme or the example in the documentation.

**Comment by remonh87** [comment]
I would recommend following the officially docs. https://stripe.com/docs/billing/subscriptions/overview

We are not an officially package but more like a thin wrapper around the react native stripe sdk. It would be unfortunately too much to maintain docs of the full Stripe sdk besides maintaining the flutter lib
