### ISSUE TITLE
Payment method data is not allowed when payment_method_options[us_bank_account][verification_method]=instant is used

### ISSUE THREAD

**Issue by rahulrepala** [flutter-stripe/flutter_stripe#1348]
**Issue -**
I am trying to do bank transfer. we are having a requirement to implement using instant bank transfer. on web in react it is working fine. when i am trying to do it in flutter using flutter_stripe i am getting the following error -

**Error -**
StripeException(error: LocalizedErrorMessage(code: FailureCode.Failed, localizedMessage: Payment method data is not allowed when payment_method_options[us_bank_account][verification_method]=instant is used., message: Payment method data is not allowed when payment_method_options[us_bank_account][verification_method]=instant is used., stripeErrorCode: payment_method_invalid_parameter, declineCode: null, type: invalid_request_error))

**When i am using the following code -**
 ```
final billingDetails = BillingDetails(
                                  name: name.text.toString(),
                                  email: email.text.toString(),
                                  phone: phone.text.toString(),
                                  address: Address(
                                    city: 'Houston',
                                    country: 'US',
                                    line1: '1459  Circle Drive',
                                    line2: '',
                                    state: 'Texas',
                                    postalCode: '77063',
                                  ),
                                );
final confirmIntent =
                     await Stripe.instance.confirmPayment(
                       paymentIntentClientSecret: clientSecret,
                       data: PaymentMethodParams.usBankAccount(
                              paymentMethodData:
                                  PaymentMethodDataUsBank(
                                   accountNumber: accNumber.text,
                               routingNumber: routingNumber.text,
                                  billingDetails: billingDetails,
                                  )),
                                );
```
I checked multiple places i am not able to find solution for it. if i remove the paymentmethod data as it was saying in error. how does it know the account details of user.

**Comment by remonh87** [comment]
Is your Business registered in the US and is us bank account registered in as a payment method?  Also I would recommend checking the example: https://github.com/flutter-stripe/flutter_stripe/blob/main/example/lib/screens/regional_payment_methods/us_bank_account.dart

**Comment by rahulrepala** [comment]
Hey Thanks for the reply, I have gone through the code. I am having business requirement to do with instant payment transfer. 

In the code that you mentioned. we need to do with microdeposits -
from line number 66 to 130

But I am having a requirement to do with instant transfer. when i am doing with instant transfer i am getting the above error.

can you help me with that

**Comment by rahulrepala** [comment]
I appreciate your efforts in explaining the issue. 
Thank you

**Comment by itsamit108** [comment]
> I appreciate your efforts in explaining the issue. 
> Thank you

Could you please share reference codes on how you fixed that issue? I'm trying to do the same but am encountering this error: https://github.com/flutter-stripe/flutter_stripe/issues/1980
