### ISSUE TITLE
this merchant is having trouble accepting your payment at the moment. try using a different payment method [or_bibed_11] in Google Pay

### ISSUE THREAD

**Issue by jrajora** [flutter-stripe/flutter_stripe#1351]
**Describe the bug**
hi i found error while i use to pay using live credential using Gpay rest is working fine only facing an error in GPay :
this merchant is having trouble accepting your payment at the moment. try using a different payment method [or_bibed_11] 

**To Reproduce**
1. Entering number 123-456-789 into the cardfield.
2. Tapping the confirm button.
3. Observe a failure with exception (including the part of the stack trace, belonging to this package) …

**Expected behavior**

**Smartphone**
 - Samsung F23 AND Samsung A14
 - OS: Android 13
 - flutter_stripe: ^9.3.0
 - Flutter version :  3.7.8
 - VS Code (version 1.80.2)
 - Android Studio (version 2022.2)
 - (Android SDK version 34.0.0)
 - 

**Additional context**
this merchant is having trouble accepting your payment at the moment. try using a different payment method [or_bibed_11] 
this one error is coming in android device only in rest card payment and apple pay and other payment is working fine only getting this error in while done payment using Google pay with country United Kingdom

**Comment by remonh87** [comment]
Are you running in production mode? Make sure that your app is approved in using for google pay. Check this checklist: https://developers.google.com/pay/api/android/guides/test-and-deploy/integration-checklist . 

I would recommend contacting stripe support if the problem persists as this comes from the google pay API  and this is out of our control
