### ISSUE TITLE
[Documentation]: Generic Query to run the codebase in local setup

### ISSUE THREAD

**Issue by Sahil-kachhap** [flutter-stripe/flutter_stripe#1354]
**Describe the bug**
- cp lib/.env.example.dart lib/.env.dart and set your Stripe publishable key.
- cp server/.env.example server/.env and set the variable values in your newly created .env file.

These are the two steps mentioned in the documentation to run the app in local setup. But after running `melos bootstrap`, I didn't find lib/env.dart file and servers/.env file in the codebase and therefore getting multiple compilation errors on import lines in the codebase (inside example/lib folder). Is this a bug or do I need to create these env files.

**To Reproduce**

**Expected behavior**
- .env files should be there in the codebase

**Smartphone / tablet**
 

**Additional context**
![stripe-sdk](https://github.com/flutter-stripe/flutter_stripe/assets/54017876/fb8f2bdf-53e8-4dec-b898-743600972d98)

**Comment by jonasbark** [comment]
Please follow the readme.
https://github.com/flutter-stripe/flutter_stripe#run-the-example-app
