### ISSUE TITLE
ACH Direct Debit in Flutter Web

### ISSUE THREAD

**Issue by yasin1376** [flutter-stripe/flutter_stripe#1357]
I have implemented the ACH Direct Debit payment method in my Flutter app so it is working perfect on mobile side both android and IOS but in web, it shows "Stripe Error: WebUnsupportedError".

The ACH payment is not supported on the Flutter Web?

How to solve it on the Flutter Web Stripe?

Thanks in advance,

**Comment by yasin1376** [comment]
@remonh87 The Bacs Direct Debit payment method type is not exist in this flutter package?

**Comment by remonh87** [comment]
yes we support it . https://github.com/flutter-stripe/flutter_stripe/blob/a5f866345f421a14fe3c992e6ff79cf86a497e32/packages/stripe_platform_interface/lib/src/models/payment_methods.dart#L36

**Comment by yasin1376** [comment]
It doesn't exist in PaymentMethodParams class to call on confirm payment?

**Comment by yasin1376** [comment]
@remonh87 Check the below link, there is no factory for Bacs Direct Debit.

https://github.com/flutter-stripe/flutter_stripe/blob/a5f866345f421a14fe3c992e6ff79cf86a497e32/packages/stripe_platform_interface/lib/src/models/payment_methods.dart#L323C16-L323C16

**Comment by yasin1376** [comment]
@remonh87 Any update on ACH Web and Bacs on Mobile?
