### ISSUE TITLE
StripeError<PaymentSheetError>(message: Unknown result this is likely a problem in the plugin {paymentOption: null}, code: PaymentSheetError.unknown)

### ISSUE THREAD

**Issue by LakshayDCoder** [flutter-stripe/flutter_stripe#1359]
**Describe the bug**
```StripeError<PaymentSheetError>(message: Unknown result this is likely a problem in the plugin {paymentOption: null}, code: PaymentSheetError.unknown)```
We are getting this error when we want to initialise the payment sheet.
Below is the full code that we are using

```
try {
      //STEP 1: Create Payment Intent
      paymentIntent = await createPaymentIntent(amount);

      //STEP 2: Initialize Payment Sheet
      if (paymentIntent != null) {
        // log(jsonEncode(paymentIntent));
        await Stripe.instance.initPaymentSheet(
          paymentSheetParameters: SetupPaymentSheetParameters(
            paymentIntentClientSecret: paymentIntent!['client_secret'],
            style: ThemeMode.light,
            merchantDisplayName: 'iSangha',
            customFlow: true,
            customerEphemeralKeySecret: paymentIntent!['ephemeralKey'],
            customerId: paymentIntent!['customer'],
          ),
        );

        isLoading.value = false;

        //STEP 3: Display Payment sheet
        bool val =
            await displayPaymentSheet(context, amount, userId, activateAccount);
        retVal = val;
      } else {
        throw Exception("Payment Intent is Null");
      }
    } catch (err) {
      print("Some error occureed: $err");
      errorPopUp();
    }
```

Code for creating payment intent
```
Future<Map<String, dynamic>> createPaymentIntent(double amount) async {
    try {
      //Request body
      // https://stripe.com/docs/currencies#zero-decimal
      Map<String, dynamic> body = {
        'amount': (amount * 100).toInt().toString(),
        'currency': 'USD',
      };

      //Make post request to Stripe
      var response = await http.post(
        Uri.parse('https://api.stripe.com/v1/payment_intents'),
        headers: {
          'Authorization': 'Bearer ${Config.stripeSecretKey}',
          'Content-Type': 'application/x-www-form-urlencoded'
        },
        body: body,
      );
      return json.decode(response.body);
    } catch (err) {
      throw Exception(err.toString());
    }
  }
```

<img width="1512" alt="Screenshot 2023-08-07 at 12 09 46 PM" src="https://github.com/flutter-stripe/flutter_stripe/assets/32734770/178607db-f106-468d-80b3-7d100fc72e60">

**To Reproduce**
Steps to reproduce the behaviour:
Simply try to initiate a payment

**Expected behaviour**
The payment sheet should open, showing us the card fields

**Smartphone/tablet**
 - Device: iPhone 14 Pro Max Simulator
 - OS: iOS 16.4
 - Package version: 9.3.0
 - Flutter version 3.10.6

**Comment by remonh87** [comment]
Can you double check your payment intent in the stripe dashboard? It looks like the payment intent is malicious because normally we would expect `paymentOption` to contain a payment. 

In your code to create a paymentinten you do not provide a payment_method.  This is recommended to do see: https://stripe.com/docs/api/payment_intents/create

Also I hope this is debug code because directly communicating to the Stripe API from the mobile phone is insecure because people can manipulate the request through a proxy.

**Comment by LakshayDCoder** [comment]
> Can you double check your payment intent in the stripe dashboard? It looks like the payment intent is malicious because normally we would expect `paymentOption` to contain a payment.
> 
> In your code to create a paymentinten you do not provide a payment_method. This is recommended to do see: https://stripe.com/docs/api/payment_intents/create
> 
> Also I hope this is debug code because directly communicating to the Stripe API from the mobile phone is insecure because people can manipulate the request through a proxy.

Below is the response that I have in my payment Intent. Let me know if there is some problem while generating the `payment intent`. 

```
{"id":"pi_3NcjdpSDoqbYFMpkQ5","object":"payment_intent","amount":1050,"amount_capturable":0,"amount_details":{"tip":{}},"amount_received":0,"application":null,"application_fee_amount":null,"automatic_payment_methods":null,"canceled_at":null,"cancellation_reason":null,"capture_method":"automatic","client_secret":"pi_3Nu0aaMpkQ5_secret_4kS5PoPzy7fa","confirmation_method":"automatic","created":1691477021,"currency":"usd","customer":null,"description":null,"invoice":null,"last_payment_error":null,"latest_charge":null,"livemode":false,"metadata":{},"next_action":null,"on_behalf_of":null,"payment_method":null,"payment_method_options":{"card":{"installments":null,"mandate_options":null,"network":null,"request_three_d_secure":"automatic"}},"payment_method_types":["card"],"processing":null,"receipt_email":null,"review":null,"setup_future_usage":null,"shipping":null,"source":null,"statement_descriptor":null,"statement_descriptor_suffix":null,"status":"requires_payment_method","transfer_data":null,"transfer_group":null}
```

**Comment by amazed11** [comment]
You can remove **{customFlow:true}** properties i think that causing the issue. If that again doesn't work make sure you have pass **(payment_method_types[]:"card")** into your payload while creating PaymentIntent.
Hope that works if not please paste your create payment intent code.

**Comment by LakshayDCoder** [comment]
> You can remove **{customFlow:true}** properties i think that causing the issue. If that again doesn't work make sure you have pass **(payment_method_types[]:"card")** into your payload while creating PaymentIntent. Hope that works if not please paste your create payment intent code.

So when I removed the `customFlow:true` property the payment sheet was displayed. But when I try to do a payment I am now getting a new error as mentioned in the screenshot. 
<img width="387" alt="Screenshot 2023-08-09 at 7 04 35 PM" src="https://github.com/flutter-stripe/flutter_stripe/assets/32734770/2b36b797-bace-4073-9f45-86f951625d90">

Once I add the `payment_method_types:"card"` in the payment intent body something like this
```
 Map<String, dynamic> body = {
        'amount': (amount * 100).toInt().toString(),
        'currency': 'USD',
        'payment_method_types': 'card',
      };
```
I am getting the below error. 
```
StripeException(error: LocalizedErrorMessage(code: FailureCode.Failed, localizedMessage: You must provide either paymentIntentClientSecret or setupIntentClientSecret, message: You must provide either paymentIntentClientSecret or setupIntentClientSecret, stripeErrorCode: null, declineCode: null, type: null))
```

Below is the code that I am using to create `Payment Intent`
```
Future<Map<String, dynamic>> createPaymentIntent(double amount) async {
    try {
      //Request body
      // https://stripe.com/docs/currencies#zero-decimal
      Map<String, dynamic> body = {
        'amount': (amount * 100).toInt().toString(),
        'currency': 'USD',
        'payment_method_types': 'card',
      };

      //Make post request to Stripe
      var response = await http.post(
        Uri.parse('https://api.stripe.com/v1/payment_intents'),
        headers: {
          'Authorization': 'Bearer $secretKey',
          'Content-Type': 'application/x-www-form-urlencoded'
        },
        body: body,
      );
      return json.decode(response.body);
    } catch (err) {
      throw Exception(err.toString());
    }
  }
```

**Comment by remonh87** [comment]
yes this error is correct you must provide  an payment intent secret or setup intent secret. See: https://docs.page/flutter-stripe/flutter_stripe/sheet
