### ISSUE TITLE
Issue with bacs_debit as a payment method

### ISSUE THREAD

**Issue by gabbygreat** [flutter-stripe/flutter_stripe#1361]
I noticed that when you create an intent with bacs_debit as the only payment method, the paymentSheet fails with an error.

**To Reproduce**
```
void proceedPay() async {
  await Stripe.instance.initPaymentSheet(
    paymentSheetParameters: const SetupPaymentSheetParameters(
      merchantDisplayName: 'Ajo',
      paymentIntentClientSecret:
          'pi_3Nc3dlLf0BOTBFpE2uB0JD9z_secret_O4QNzRlpCjVGwa5LoJVqWcqUi',
    ),
  );
  await Stripe.instance.presentPaymentSheet();
}
```

**Expected behavior**
I expected that the payment sheet opens up normally without error. If the payment method includes or is only a card, there won't be any issues. I have included a clientSecretKey whose payment intent has just *bacs_debit* as the payment method.

**Smartphone / tablet**
 - Device: iPhone 14 Pro Max Simulator
<img width="740" alt="Screenshot 2023-08-08 at 5 34 07 AM" src="https://github.com/flutter-stripe/flutter_stripe/assets/79731192/7a81a5e4-7582-4ca6-b3b6-43aeeab313b6">

 - OS:  iOS 16.4
 - Package version: 9.3.0
 - Flutter version 3.10.6

**Comment by remonh87** [comment]
Bacs is not supported on the paymentsheet. See: 

https://github.com/stripe/stripe-react-native/issues/1345 and https://stripe.com/docs/payments/payment-methods/bacs-debit

**Comment by gabbygreat** [comment]
Thank you, I finally figured it

**Comment by DavidEcclesPH** [comment]
> Bacs is not supported on the paymentsheet. See:
> 
> [stripe/stripe-react-native#1345](https://github.com/stripe/stripe-react-native/issues/1345) and https://stripe.com/docs/payments/payment-methods/bacs-debit

Hi @remonh87 is this still the case that bacs is not supported on the paymentsheet?
