### ISSUE TITLE
For bank transfer, In the code which is given as example. Why did you keep microdeposit always

### ISSUE THREAD

**Issue by rahulrepala** [flutter-stripe/flutter_stripe#1362]
For Bank Transfer in the following code example -
[https://github.com/flutter-stripe/flutter_stripe/blob/main/example/lib/screens/regional_payment_methods/us_bank_account.dart](url)

Why did you always keep microdeposit why not other states, successful, failure etc etc 

In this testing account from the stripe documentation -
[https://stripe.com/docs/testing](url)

For successful payment account credentials also it is navigating to verifyIntentWithMicroDeposit

Why ?

**Comment by remonh87** [comment]
For your information: Stripe is a big platform and there are so many outcomes that it will be impossible for us to cater for everything. Also it will confuse the users. 

We are open source so feel free to create a PR and improve the docs or example app.
