### ISSUE TITLE
After Stripe Payment success I am not able to get details Response, can you hepl me please

### ISSUE THREAD

**Issue by sunilkrsingh8922** [flutter-stripe/flutter_stripe#1365]
**Describe the bug**

**To Reproduce**
1. Entering number 123-456-789 into the cardfield.
2. Tapping the confirm button.
3. Observe a failure with exception (including the part of the stack trace, belonging to this package) …

**Expected behavior**

**Smartphone / tablet**
 - Device: [e.g. iPhone X]
 - OS: [e.g. iOS 13, Android 10]
 - Package version: [e.g. 1.0.0]
 - Flutter version [e.g. 2.0.0.]

**Additional context**

**Comment by sunilkrsingh8922** [comment]
Is there any flutter stripe sdk let me know so that I can manage by self.

**Comment by remonh87** [comment]
If there is an error we will normally throw an StripeException that you can catch. However the card is not a valid card input so the behaviour is correct. I would recommend looking at: https://stripe.com/docs/testing for test cards
