### ISSUE TITLE
Doc update request

### ISSUE THREAD

**Issue by pritamkarmakar** [flutter-stripe/flutter_stripe#1367]
https://docs.page/flutter-stripe/flutter_stripe/sheet this doc doesn't mention about `await Stripe.instance.confirmPaymentSheetPayment();` call after presenting the payment sheet. Without this, the payment will remain in an incomplete state. Can we please update this?

Thanks.

**Comment by remonh87** [comment]
yes you are right thanks for reporting. I created a fix for it.
