### ISSUE TITLE
[PAYMENT SHEET] Issue regarding closing of Payment Sheet

### ISSUE THREAD

**Issue by mike392** [flutter-stripe/flutter_stripe#137]
Greetings Team,

Can you, please, advise me what am i doing wrong?

I believe that if i press on [X] button after the Payment Sheet loading - it implies that Payment Intent needs to be somewhat Cancelled or...

Anyways - after i close the window with PaymentSheet i get this error below:

```
E/flutter ( 4748): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(Canceled, , null, null)
E/flutter ( 4748): #0      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:155:7)
E/flutter ( 4748): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
E/flutter ( 4748): <asynchronous suspension>
E/flutter ( 4748): #2      MethodChannelStripe.presentPaymentSheet (package:stripe_platform_interface/src/method_channel_stripe.dart:181:5)
E/flutter ( 4748): <asynchronous suspension>
E/flutter ( 4748): #3      Stripe.presentPaymentSheet (package:flutter_stripe/src/stripe.dart:268:5)
E/flutter ( 4748): <asynchronous suspension>
E/flutter ( 4748): 
```

**Comment by thorsten-stripe** [comment]
That's the expected result to let you know that the user has cancelled the payment flow.

**Comment by jamesblasco** [comment]
It is recommended that you handle the error thrown by this method 

```dart
try {
   await presentPaymentSheet(...);
} catch(e) {
}
```

We will try to improve the exception messages in the upcoming  weeks

**Comment by mike392** [comment]
Okay - thank you so much for the explanation! I will treat the exception correspondingly

**Comment by kalptech2021** [comment]
@mike392  is it working for you? I have tried using try-catch block but it isn't working. Even after pressing cross button, it executes the try block not the catch

**Comment by remonh87** [comment]
Stripe improved feedback mechanism in their bindings for paymentsheet. #199 will fix it
