### ISSUE TITLE
[Flutter][IOS][CardFormField] Tapping on card number, focus shifting to expiry date field

### ISSUE THREAD

**Issue by sabachimp** [flutter-stripe/flutter_stripe#1376]
Stripe Version: **flutter_stripe: ^9.3.0**
Widget used: **CardFormField**
IOS Version: 16.1, 16.4
Flutter Version: 3.10.6

**This issue occurs only in IOS, and it is working fine in ANDROID.**

Pre-requisites:

1. Added Text field for collecting name from the user above the Card Form Field

Steps to reproduce: 

1. Type something in custom name field 
2. Tapping on the card number field
3. Focus moving to expiry date field instead of card number field.

Here attached the video recording of the same.

https://github.com/flutter-stripe/flutter_stripe/assets/64010354/ec3c70a4-1ba4-4147-9502-1e9ae066b780

**Comment by remonh87** [comment]
thanks for reporting. I pushed a fix that will be released in the next sync with the stripe sdk. Hopefully we can ship it this week

**Comment by sabachimp** [comment]
Thanks for the fix @remonh87

**Comment by ChimpSumsIOS** [comment]
Thanks for the fix @remonh87 . If we could know the date by when the fix will be available for use, will help us the plan build activities accordingly. Thanks
