### ISSUE TITLE
[Flutter][Android] CardFormField height not adjusting when zip code field hidden for selected countries

### ISSUE THREAD

**Issue by sabachimp** [flutter-stripe/flutter_stripe#1382]
Stripe Version: flutter_stripe: ^9.3.0
Widget used: CardFormField
Android Version: All the versions (above Android 9)
Flutter Version: 3.10.6

**This issue occurs only in Android, and it is working fine in IOS.**

Pre-requisites:

Added Text field for collecting name from the user below the Card Form Field

Steps to reproduce:

1. Due to the following focus issue in iOS [https://github.com/flutter-stripe/flutter_stripe/issues/1376](url) , modified our UI like adding the card holder name after the card form filed
2. Now the issue is when the user choose countries other than zip code mandatory countries, zip code field is getting hidden but the height of the CardFormField is not shrinking/moving up. So there is space appears in between the card form field and name field.
3. Here is the video attachment of the same below
https://github.com/flutter-stripe/flutter_stripe/assets/64010354/038e74fd-2e77-463d-ae4d-2fdedf05d22e

Suggestions and solutions are much appreciated.

**Comment by remonh87** [comment]
The card field is not a Flutter widget but a native widget from the stripe sdk due to security reasons.  We do not have control over the UX of this widget.
