### ISSUE TITLE
CardField reset

### ISSUE THREAD

**Issue by LScodeblack** [flutter-stripe/flutter_stripe#1384]
i cant seem to find away to reset card field details and remove focus. any help ?

**Comment by remonh87** [comment]
you can do this by injecting an [CardEditController](https://github.com/flutter-stripe/flutter_stripe/blob/main/packages/stripe_platform_interface/lib/src/card_edit_controller.dart) to the card field

**Comment by LScodeblack** [comment]
This will clear the field but not remove focus
