### ISSUE TITLE
I m getting this error while adding flutter_stripe to my app.Tried latest as well as older versions.However not able to solve the issue.compiledkversion is 32,targetsdkversion is 31 etc

### ISSUE THREAD

**Issue by ashiqueachi696** [flutter-stripe/flutter_stripe#1385]
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '/Users/dataspot/.pub-cache/hosted/pub.dev/stripe_android-9.3.0/android/build.gradle' line: 29

* What went wrong:
A problem occurred evaluating project ':stripe_android'.
> No signature of method: build_30db1ybl4vn2ahalaxdm08pdc.android() is applicable for argument types: (build_30db1ybl4vn2ahalaxdm08pdc$_run_closure2) values: [build_30db1ybl4vn2ahalaxdm08pdc$_run_closure2@4f8f19c8]

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* Where:
Script '/Users/dataspot/Developer/flutter/packages/flutter_tools/gradle/src/main/groovy/flutter.groovy' line: 483

* What went wrong:
A problem occurred configuring project ':stripe_android'.
> Failed to notify project evaluation listener.
   > Cannot invoke method substring() on null object
   > compileSdkVersion is not specified. Please add it to build.gradle

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

**Comment by remonh87** [comment]
Like the error said make sure to add an compile sdkversion to your build.gradle

See https://github.com/flutter-stripe/flutter_stripe/blob/d6a90a8254acb863f88608e408ae239660bb9236/example/android/app/build.gradle#L30
