### ISSUE TITLE
R8: Type com.facebook.react.bridge.ReactContext is defined multiple times:

### ISSUE THREAD

**Issue by xrhstos334** [flutter-stripe/flutter_stripe#1386]
I faced this issue when i build apk for android any help?

\.gradle\caches\transforms-3\591fe65e72cd5150e616f82b85520e3e\transformed\jetified-react-native-0.68.5-runtime.jar: R8: Type com.facebook.react.bridge.ReactContext is defined multiple times : \.gradle\caches\transforms-3\591fe65e72cd5150e616f82b85520e3e\transformed\jetified-react-native-0.68.5-runtime.jar:com/facebook/react/bridge/ReactContext.class, \build\stripe_android\intermediates\runtime_library_classes_jar\release\classes.jar:com/facebook/react/bridge/ReactContext.class

* What went wrong:
Execution failed for task ':app:minifyReleaseWithR8'.
> com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin:.gradle\caches\transforms-3\591fe65e72cd5150e616f82b85520e3e\transformed\jetified-react-native-0.68.5-runtime.jar:com/facebook/react/bridge/ReactContext.class

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

**Comment by remonh87** [comment]
can you explain me what dependency add the jetified-react-native ?

**Comment by xrhstos334** [comment]
duplicate #197
