### ISSUE TITLE
Web CardField nullCheck Error

### ISSUE THREAD

**Issue by jpxcz** [flutter-stripe/flutter_stripe#1387]
Creating a simple CardField on Chrome Web will return an error at initializing the component. This will cause the widget to be rendered partially (only the outside box). Not allowing to render or modify any information inside of it.

```
══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following TypeErrorImpl was thrown during a scheduler callback:
Unexpected null value.

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 855:63  nullCheck
packages/flutter_stripe_web/src/web_stripe.dart 18:45                             get js
packages/flutter_stripe_web/src/widgets/card_field.dart 89:16                     <fn>
packages/flutter/src/scheduler/binding.dart 1297:15                               [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1236:9                                handleDrawFrame
packages/flutter/src/scheduler/binding.dart 1085:5                                [_handleDrawFrame]
lib/_engine/engine/platform_dispatcher.dart 1304:13                               invoke
lib/_engine/engine/platform_dispatcher.dart 278:5                                 invokeOnDrawFrame
lib/_engine/engine/initialization.dart 185:45                                     <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 574:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 579:39  dcall
════════════════════════════════════════════════════════════════════════════════════════════════════
```

Tracing down a little bit the error, seems that on web_stripe -> WebStripe class is trying to get a property that could be null at the time on initialization of Stripe State. https://github.com/flutter-stripe/flutter_stripe/blob/d6a90a8254acb863f88608e408ae239660bb9236/packages/stripe_web/lib/src/widgets/card_field.dart#L88 

** Dependencies ** 
```
  flutter_stripe: ^9.3.0
  flutter_stripe_web: ^4.3.0
```

** Flutter version **
```
Flutter 3.13.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision e1e47221e8 (4 days ago) • 2023-08-22 21:43:18 -0700
Engine • revision b20183e040
Tools • Dart 3.1.0 • DevTools 2.25.0
```

**Comment by remonh87** [comment]
@jpxcz  sorry for reaching out so late to this. For some reason it slipped through.

Did you initialise the sdk correctly?

```dart
  WidgetsFlutterBinding.ensureInitialized();
  Stripe.publishableKey = stripePublishableKey;
  await Stripe.instance.applySettings();
```

**Comment by jpxcz** [comment]
Hey @remonh87  thanks for the reply, no worries about it :)

I did configure it that way. This I didn on the `main.dart` file as I make sure all the configurations are ran before anything else.

Please let me know how I could help you debug this issue. Happy to be of any assistance

**Comment by remonh87** [comment]
can you run our example app and see if the error occurs? I really struggle to reproduce it. Else can you create a minimum reproducable example  so I can try to debug it?
