### ISSUE TITLE
PaymentSheet does not displays Google Pay as a payment option in flutter app 

### ISSUE THREAD

**Issue by shhbzkhn** [flutter-stripe/flutter_stripe#1388]
Stripe.instance
          .initPaymentSheet(
              paymentSheetParameters: SetupPaymentSheetParameters(
    
            paymentIntentClientSecret: data.tokenData?.clientSecret.toString(),
            merchantDisplayName: 'abc',
            Customer params
            customerId: data.tokenData?.id.toString(),
            customerEphemeralKeySecret: data.tokenData?.emphData?.id.toString(),
            style: ThemeMode.light,
            billingDetails: billingDetails,
      
            applePay: const PaymentSheetApplePay(merchantCountryCode: 'US'),
            googlePay: const PaymentSheetGooglePay(
                merchantCountryCode: 'US', currencyCode: "USD", testEnv: true),
          ))
          
          
          PaymentSheet does not displays Google Pay as a payment option

** flutter version**
-  3.13.1

**stripe version **
flutter_stripe: ^9.3.0

**Smartphone / tablet**
 - Device: [pixel 6 pro]

**Comment by remonh87** [comment]
Make sure you add this entry to your manifest and your device has a valid google pay configuration. For me it still is shown
```xml
<application>
  ...
  <meta-data
    android:name="com.google.android.gms.wallet.api.enabled"
    android:value="true" />
</application>

````

**Comment by shhbzkhn** [comment]
i have already added this in my  manifest file. still not able to see google pay as payment option

**Comment by remonh87** [comment]
Also make sure your device has google pay because the payment sheet internally checks for the availability of google pay

**Comment by shhbzkhn** [comment]
@remonh87  i have done every thing from manifest to availability of google pay in my device
