### ISSUE TITLE
Invalid argument(s): 'Unknown' is not one of the supported values: Manual, Automatic

### ISSUE THREAD

**Issue by sirawatGG** [flutter-stripe/flutter_stripe#1390]
**Describe the bug**
First of all I am still in test mode. after I call confirmPayment, it throw me an error. However in Stripe dashboard, it shows that the payment success

![Screenshot 2023-08-31 at 12 13 36 PM](https://github.com/flutter-stripe/flutter_stripe/assets/6262268/53582308-feb3-4a60-91b5-905655a251c1)

**To Reproduce**

1. after I receive clientSecret from backend
2. I call dangerouslyUpdateCardDetails as below
```
await Stripe.instance.dangerouslyUpdateCardDetails(CardDetails(
        expirationMonth: 12,
        expirationYear: 34,
        number: '4242424242424242',
        cvc: '567',
      ));
```
3. I create billingDetails as below
```
    final billingDetails = BillingDetails(
      email: _email,
      phone: '+48888000888',
      address: Address(
        city: 'Houston',
        country: 'US',
        line1: '1459  Circle Drive',
        line2: '',
        state: 'Texas',
        postalCode: '77063',
      ),
    ); 
```
4. now I call confirmPayment as below
```
      await Stripe.instance.confirmPayment(
        paymentIntentClientSecret: clientSecret,
        data: PaymentMethodParams.card(
          paymentMethodData: PaymentMethodData(
            billingDetails: billingDetails,
          ),
        ),
      );
```
5. I get error Unknown is not one of the supported values: Manual, Automatic, but in the stripe dashboard the payment is success

**Smartphone / tablet**
 - ios simulator

**Comment by remonh87** [comment]
Thanks for reporting created an PR that contains a fix.
