### ISSUE TITLE
Google pay GooglePayPaymentMethodParams(amount: 420) only integer is allowed?

### ISSUE THREAD

**Issue by ziagit** [flutter-stripe/flutter_stripe#1392]
In below code `GooglePayPaymentMethodParams(amount: orderPrice)` the variable `orderPrice` must be only an integer value. If it is considered a total amount then why total amount cannot be double. between `$100` and `$100.5` is a huge difference.
```
 final paymentMethod =
            await Stripe.instance.createPlatformPayPaymentMethod(
          params: PlatformPayPaymentMethodParams.googlePay(
            googlePayParams: GooglePayParams(
              merchantCountryCode: "US",
              currencyCode: "USD",
              merchantName: "Tingsapp",
              testEnv: true,
            ),
            googlePayPaymentMethodParams:
                GooglePayPaymentMethodParams(amount: orderPrice),
          ),
        );
```
please fix this bug if I'm not mistaking.

**Comment by remonh87** [comment]
I think the payment method amount is in cents .  If I go to the stripe SDK code it parses the argument to an int.

![Screenshot 2023-09-04 at 20 30 54](https://github.com/flutter-stripe/flutter_stripe/assets/20230599/abd4a662-0d3d-4209-a4d5-9f5d8a0671c5)

**Comment by ziagit** [comment]
@remonh87 The amount  in `GooglePayPaymentMethodParams(amount: **amount**),` is allowed only integer not `cent`.
