### ISSUE TITLE
In-App_Purshase for Apple

### ISSUE THREAD

**Issue by rickmocassa** [flutter-stripe/flutter_stripe#1398]
My iOS app being submitted for review by Apple was denied and to my surprise they informed me that it would be a bug on my side. 

However, when submitting for the second time, one of the analysts stated that it would not be a bug, but an implementation called **"in-app-purshase"** and StoreKit, and that the way I handle the attempt to sell my subscription is not correct and cannot be validated by Apple. 

They informed that it is not accepted that a payroll opens for the user to inform his data.

is **flutter_stripe** able to handle "in-app-purshase"?

P.s: On android everything works perfectly.

**Comment by remonh87** [comment]
Apple forces you to use there in app purchase  model for digital goods.  I would recommend to look into  https://pub.dev/packages/in_app_purchase .  This is unfortunately out of scope of our library

**Comment by ramiattaallah** [comment]
hi @rickmocassa 
Did you solve the problem? If yes, how
