### ISSUE TITLE
initPaymentSheet Problem on iOS

### ISSUE THREAD

**Issue by mirkomartino** [flutter-stripe/flutter_stripe#1403]
**Describe the bug**
As soon as you get to the function initPaymentSheet() precisely at the instance : Stripe.instance.initPaymentSheet() the application crashes.

Guide : https://docs.page/flutter-stripe/flutter_stripe/sheet

The following is reposted to the log:

```
Could not cast value of type 'NSNull' (0x1eedc5280) to 'NSDictionary' (0x1eedc51f0).
Could not cast value of type 'NSNull' (0x1eedc5280) to 'NSDictionary' (0x1eedc51f0).
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    Frame #0: 0x00000001d73bd578 libsystem_kernel.dylib'__pthread_kill + 8
libsystem_kernel.dylib':
-> 0x1d73bd578 <+8>: b.lo 0x1d73bd598 ; <+40>
    0x1d73bd57c <+12>: pacibsp 
    0x1d73bd580 <+16>: STP x29, x30, [sp, #-0x10]!
    0x1d73bd584 <+20>: MOV x29, SP
Target 0: (Runner) stopped.
Lost connection to device.
```

**To Reproduce**
1. Click on the payment button

**Smartphone / tablet**
 - Device: Iphone 12 Pro Max
 - OS: iOS 16.6
 - Package version: 9.4.0
 - Flutter version 3.7.11

**Comment by jonasbark** [comment]
https://github.com/flutter-stripe/flutter_stripe/issues/1397
