### ISSUE TITLE
Google Pay callback in payment sheet

### ISSUE THREAD

**Issue by pritamkarmakar** [flutter-stripe/flutter_stripe#1404]
I'm using custom flow for Stripe payment intent. I need to create a database `order` object when user finally submits payment info. For a credit card its not an issue, but if user selects Google pay they see an additional bottom sheet where they can select the credit card. So I'm looking for a callback which will be triggered when user will tap on the final `Continue` button (please see this screenshot). I can't save the order object before because user can change mind and can exit from the flow. So looking for a final method where user submitting the payment.

![PXL_20230908_234231800~2](https://github.com/flutter-stripe/flutter_stripe/assets/5255799/01f36257-5de1-4a48-b8f1-86d16f579d22)

**Comment by remonh87** [comment]
This is not how Stripe works on mobile. To get the latest status of the payment you always need to get it from the backend due to security reasons.
