### ISSUE TITLE
PlatformPayButton onPressed callback not working

### ISSUE THREAD

**Issue by pritamkarmakar** [flutter-stripe/flutter_stripe#1405]
**Describe the bug**
PlatformPayButton onPressed callback is not working, tested in real device as well as in an emulator.

**To Reproduce**
1. Run the sample app.
2. Open Wallet > Google Pay
3. Click on the GPay button
4. Nothing happens

**Expected behavior**
Should launch the Google Pay wallet flow.

**Smartphone / tablet**
 - Device: OnePlus 8T
 - OS: Android 13
 - Package version: [e.g. 1.0.0]
 - Flutter version 3.13.1

**Comment by remonh87** [comment]
duplicate of #1393
