### ISSUE TITLE
Build failed on iOS - "Variable binding in a condition requires an initializer"

### ISSUE THREAD

**Issue by ceribbo** [flutter-stripe/flutter_stripe#1408]
**Describe the bug**
The build of app fails in xcode with this error in 5 lines: "Variable binding in a condition requires an initializer"

**To Reproduce**

- ios/Pods/StripePayments/StripePayments/StripePayments/Source/Internal/API%20Bindings/APIRequest.swift:55:41
- ios/Pods/StripePayments/StripePayments/StripePayments/Source/Internal/API%20Bindings/APIRequest.swift:97:41
- ios/Pods/StripePayments/StripePayments/StripePayments/Source/PaymentHandler/STPPaymentHandler.swift:300:27
- ios/Pods/StripePayments/StripePayments/StripePayments/Source/PaymentHandler/STPPaymentHandler.swift:519:27
- ios/Pods/StripePayments/StripePayments/StripePayments/Source/PaymentHandler/STPPaymentHandler.swift:522:30

**Expected behavior**
successfull build

**Smartphone / tablet**
 - OS: iOS
 - Package version (flutter_version): 9.4.0
 - Flutter 3.10.4 • channel stable • https://github.com/flutter/flutter.git
 - Framework • revision 682aa387cf (3 months ago) • 2023-06-05 18:04:56 -0500
 - Engine • revision 2a3401c9bb
 - Tools • Dart 3.0.3 • DevTools 2.23.1

**Additional context**
just before adding the dependency the project successfully built

**Comment by remonh87** [comment]
Cannot reproduce the issue. Make sure that you have an updated version of Xcode and your project runs `SWIFT_VERSION=5`

my flutter doctor output
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.5.1 22G90 darwin-arm64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Community Edition (version 2023.1.1)
[✓] VS Code (version 1.81.1)
```

**Comment by illyaosik** [comment]
I have the same issue, could I ask for help?

**Comment by ceribbo** [comment]
> I have the same issue, could I ask for help?

If I remember coorrectly I updated the iOS version of flutter-stripe in the podfile configuration, then reinstalled

**Comment by illyaosik** [comment]
@ceribbo I've reinstalled ios folder (removed -> with help of flutter create it was made again), flutter_stripe ^9.5.0+1 was used.

But after all these manipulations still have:



Uncategorized (Xcode): Command CompileSwift failed with a nonzero exit code

Swift Compiler Error (Xcode): Variable binding in a condition requires an initializer
/Users/illiaosiyuk/Desktop/MyFlutterApp/flutter_app/ios/Pods/StripePayments/StripePayments/StripePayments/Source/API%20Bindings/Models/Shared/STPIntentAction.swift:255:41

Swift Compiler Error (Xcode): Variable binding in a condition requires an initializer
/Users/illiaosiyuk/Desktop/MyFlutterApp/flutter_app/ios/Pods/StripePayments/StripePayments/StripePayments/Source/PaymentHandler/STPPaymentHandler.swift:294:27

Swift Compiler Error (Xcode): Variable binding in a condition requires an initializer
/Users/illiaosiyuk/Desktop/MyFlutterApp/flutter_app/ios/Pods/StripePayments/StripePayments/StripePayments/Source/PaymentHandler/STPPaymentHandler.swift:507:27

Swift Compiler Error (Xcode): Variable binding in a condition requires an initializer
/Users/illiaosiyuk/Desktop/MyFlutterApp/flutter_app/ios/Pods/StripePayments/StripePayments/StripePayments/Source/PaymentHandler/STPPaymentHandler.swift:510:30

Swift Compiler Error (Xcode): Variable binding in a condition requires an initializer
/Users/illiaosiyuk/Desktop/MyFlutterApp/flutter_app/ios/Pods/StripePayments/StripePayments/StripePayments/Source/Internal/API%20Bindings/APIRequest.swift:55:41

Swift Compiler Error (Xcode): Variable binding in a condition requires an initializer
/Users/illiaosiyuk/Desktop/MyFlutterApp/flutter_app/ios/Pods/StripePayments/StripePayments/StripePayments/Source/Internal/API%20Bindings/APIRequest.swift:97:41

Uncategorized (Xcode): Command CompileSwiftSources failed with a nonzero exit code

Could not build the application for the simulator.
Error launching application on iPhone 8.

**Comment by illyaosik** [comment]
@remonh87 @ceribbo it looks that I can use 8.0.0+1 version but the problem appears with 9.0.0 and higher versions.
