### ISSUE TITLE
createPlatformPayPaymentMethod usesDeprecatedTokenFlow param has no effect

### ISSUE THREAD

**Issue by cornwe19** [flutter-stripe/flutter_stripe#1409]
**Describe the bug**
`usesDeprecatedTokenFlow` doesn't seem to have any effect in `createPlatformPayPaymentMethod`.

**To Reproduce**
1. Setup Flutter Stripe with proper publishable key and merchant identifier
2. Add an Apple Pay button
3. Run the app on an iOS device with Apple Pay configured (simulator is fine)
4. Configure a click action to call `createPlatformPayPaymentMethod` with `PlatformPayPaymentMethodParams.applePay` params and `usesDeprecatedTokenFlow` set to true
5. Confirm the Apple Pay sheet

**Expected behavior**
The platform payment method result should include some way to access a card token, but none exists.

**Smartphone / tablet**
 - Device: iPhone/iPhone simulator
 - OS: iOS 16
 - Package version: 9.4.0
 - Flutter version: 3.10.6

**Additional context**
There doesn't appear to be any documentation about how this parameter is supposed to work. It's possible I'm just misusing it?

**Comment by remonh87** [comment]
Thanks for reporting this issue we made a mistake in the implementation and forgot to send out the parameters. PR is created that will fix this issue

**Comment by remonh87** [comment]
I do not think platform pay supports this. You can create a payment method using the legacy but then I still think you need to create a payment intent on the backend and confirm it. 

I have little knowledge of the deprecated token flow. I would recommend contacting stripe support for this.

**Comment by cornwe19** [comment]
Platform pay does support this if you use the [pay plugin](https://pub.dev/packages/pay) (see the `createApplePayToken` method), but we're trying to transition away from that plugin and use `flutter_stripe` exclusively.

My assumption was that using the deprecated token method in `createPlatformPayPaymentMethod` would have returned a legacy card token in some capacity for legacy backends to use until they're upgraded to the intents APIs, but it sounds like that is not the purpose of this parameter.

**Comment by ethanp** [comment]
In the react native library they ended up implementing a separate `createPlatformPayToken` method which returns a token instead of a PaymentMethod https://github.com/stripe/stripe-react-native/commit/d60c9c026a7c7e627b7cfebec2446043d954eb68
