### ISSUE TITLE
Crash when calling initPaymentSheet on iOS

### ISSUE THREAD

**Issue by chiarfe** [flutter-stripe/flutter_stripe#1416]
**Describe the bug**
Crash when calling initPaymentSheet on iOS with paymentIntentClientSecret specified and no intentConfiguration.
App crashes with dynamic cast failure NSNull to NSDictionary at line 184 of StripePlugin.swift stripe_ios plugin, where it tries to cast param "intentConfiguration" to NSDictionary. 

Its value seems to be NSNull instead of nil, so it's not detected by if != nil at the previous line 183.  
Adding a check ```&& !(params.object(forKey: "intentConfiguration") is NSNull)``` to the "if" at line 183 seems to solve the problem.

**To Reproduce**
1. Launch initPaymentsheet with a paymentIntentClientSecret and no intentConfiguration object specified on iOS

**Expected behavior**
No crashes.

**Smartphone / tablet**
 - Any iOS device
 - Package version: 9.4.0
 - Flutter version 3.13.2

**Comment by jonasbark** [comment]
https://github.com/flutter-stripe/flutter_stripe/issues/1397#issuecomment-1708689710
