### ISSUE TITLE
RSD currency doesn't work correctly

### ISSUE THREAD

**Issue by antreznik** [flutter-stripe/flutter_stripe#1417]
**Describe the bug**
Hello! I am creating an app in FlutterFlow for Serbia with Stripe integration. Unfortunately there is a bug with the showing of the RSD currency during the card information input. Instead of for example 1234 RSD or 1,234.00 RSD it shows 123,400 RSD. 

I do understand, that it is because Stripe takes the smallest currency like cents, but it looks like my app is about to charge 123k RSD and users will not press the pay button. If you still press the pay button it charges the right amount in RSD - 1234 RSD. And it also shows the right amount during the 3ds confirmation. The only issue in 3ds confirmation is that by some reason it shows currency twice like this - РСД1,234.00 RSD. But it is not a big problem. 

The biggest problem is how RSD sum is shown at the payment sheet. If it would be possible to either (1) hide this amount, or (2) show it correctly with the coma in the right place (1,234.00 RSD), it would solve the problem.

I am passing value to Stripe as Double. I tried passing it as Integer, but the result is the same. Also if my currency is EUR, then everything shows correctly. For example it shows as 12,34 EUR, but not as 1,234 EUR for example

I have also tried other 2 decimal currencies to check if there is the same problem with other ones. But the problem is only with RSD. For example RUB works correctly. Screenshots are attached.

Also If I pass the amount as Integer and it is for example 12,345 RSD (or 16,740 RSD in my example), then it shows correctly as 16,740 RSD, but it charges only 167.40 RSD, since Stripe takes the smallest amount.

It seems as there is a problem of how Stripe or Flutter Stripe integration views RSD as currency. Maybe it is not 2 decimal currency for it, but it views it as somehow else.

I have contacted Stripe support team and they have already reported this issue to the Stripe native Mobile SDK team, and will update it. But since Flutter Stripe is a community-built library, they have also suggested to report this problem here. So when the fix is available in the native mobile SDK for Android and iOS, you can include the updated native SDK in the Flutter library.

I am attaching screenshots below. In my example I have 1164 RSD that should be charged, but it shows as 116,400 RSD.

**To Reproduce**
1. Select RSD as currency in Stripe payment integration.
2. Build it.
3. Press Pay button.
4. Get the Card input screen
5. Observe how the amount is shown and where the coma should be (should be 1,234.00 RSD or 1,234 RSD and instead it is 123,400 RSD)

**Expected behavior**
It should show amount in RSD as 1,234.00 RSD or 1,234 RSD and not as 123,400 RSD as it does right now.

**Smartphone / tablet**
 - Device: [e.g. iPhone X]
 - OS: [e.g. iOS 13, Android 10]
 - Package version: [e.g. 1.0.0]
 - Flutter version [e.g. 2.0.0.]

**Additional context**

<img width="375" alt="Screenshot 2023-09-07 at 13 35 56" src="https://github.com/flutter-stripe/flutter_stripe/assets/145126374/02cfd2b3-8ad0-4145-9760-6a618f1b4357">
<img width="393" alt="Screenshot 2023-09-07 at 13 44 37" src="https://github.com/flutter-stripe/flutter_stripe/assets/145126374/5c7e8bae-ccd9-461c-8484-682119352536">
<img width="375" alt="Screenshot 2023-09-07 at 13 35 56" src="https://github.com/flutter-stripe/flutter_stripe/assets/145126374/68d7c739-2cd2-47f4-a5b0-448136fac24e">
<img width="411" alt="Screenshot 2023-09-07 at 13 21 17" src="https://github.com/flutter-stripe/flutter_stripe/assets/145126374/926851ab-be62-42cf-99da-a00d35c06c58">
<img width="395" alt="Screenshot 2023-09-07 at 13 16 16" src="https://github.com/flutter-stripe/flutter_stripe/assets/145126374/ba81d087-2e2e-4bc2-9480-d2f2a9dc1184">

**Comment by seanzhang-stripe** [comment]
Hi @antreznik This issue is already fixed in Stripe [Android SDK 20.31.0](https://github.com/stripe/stripe-android/blob/master/CHANGELOG.md#20310---2023-09-18), as well as the upcoming Stripe [iOS SDK release](https://github.com/stripe/stripe-ios/blob/master/CHANGELOG.md#xxx)

**Comment by remonh87** [comment]
@seanzhang-stripe  thanks for answering!  I noticed the android sdk is in the react native sdk 0.33. Me and @jonasbark  are planning for a new sync soon

**Comment by remonh87** [comment]
This should be solved now in version 9.5.0
