### ISSUE TITLE
Invalid argument(s): `requires_capture` is not one of the supported values: requires_payment_method, requires_confirmation, requires_action, processing, succeeded, canceled

### ISSUE THREAD

**Issue by reginojohnrobert** [flutter-stripe/flutter_stripe#1421]
I am getting this error on web

`Invalid argument(s): `requires_capture` is not one of the supported values: requires_payment_method, requires_confirmation, requires_action, processing, succeeded, canceled`

after calling the WebStripe.instance.confirmPaymentElement() function

**To Reproduce**
1. Use PaymentElement widget on web
2. Call the WebStripe.instance.confirmPaymentElement()
3. Our BE uses the status requires_capture instead of succeed
4. Throws an error upon parsing the PaymentIntentStatus

**Expected behavior**
Should'n throw a parsing error.

**Additional context**
Our BE uses the status requires_capture instead of succeed

**Comment by victorkennedys** [comment]
Hey @reginojohnrobert . I think i may know the solution to this!

I was using flutter_stripe package on web to handle 3D Secure. We created the paymentintent on our server but handle the 3d Secure flow in app with the flutter_stripe package. 

I encountered this issue when we passed this property when creating the payment intent:
 
`capture_method: "manual"`

When I removed the above line of code, it started working!

**Comment by BakerSmithA** [comment]
The docs for PaymentIntent `status` mentions `PaymentIntentsStatus` it can be `requires_capture`:

https://github.com/flutter-stripe/flutter_stripe/blob/644cea0b4b4deaba6987539977a758e2be3313ee/packages/stripe_js/lib/src/api/payment_intents/payment_intent.dart#L258

However, in the definition of `PaymentIntentsStatus` `requiresCapture` is not one of the options:

https://github.com/flutter-stripe/flutter_stripe/blob/644cea0b4b4deaba6987539977a758e2be3313ee/packages/stripe_js/lib/src/api/payment_intents/payment_intent_status.dart#L7

**Comment by BakerSmithA** [comment]
Working on a fix https://github.com/BakerSmithA/flutter_stripe/tree/fixes/invalid_arg_requires_capture

**Comment by Samuele1no** [comment]
@jonasbark @BakerSmithA 
I have the same error in the newer version 4.6.0.
In the change log of this version there is this fix but in my payment_intent_status.dart there is no capture enum.
Could you check it? Thanks
