### ISSUE TITLE
CardField returns null values for card information

### ISSUE THREAD

**Issue by vesperadlaw** [flutter-stripe/flutter_stripe#1427]
CardField returns null values for "number", "expiryMonth", "expiryYear" and "cvc", while "brand" and "complete" are displayed correctly.

```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  Stripe.publishableKey = 'pk_test_••••'; // My publishable key
  runApp(
    const MaterialApp(
      title: "My project",
      debugShowCheckedModeBanner: false,
      home: StripePayment(),
    )
  );
}

class StripePayment extends StatefulWidget {
  const StripePayment({super.key});

  @override
  State<StripePayment> createState() => _StripePaymentState();
}

class _StripePaymentState extends State<StripePayment> {

  Size size(BuildContext context) => MediaQuery.of(context).size;

  double sizeWidth(BuildContext context) => size(context).width;
  double sizeHeight(BuildContext context) => size(context).height;

  String cardValue = '';
  
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        width: sizeWidth(context),
        height: sizeHeight(context),
        padding: const EdgeInsets.all(40),
        child: Column(
          children: [

            // ... Billing form

            // Card Field
            Container(
              margin: const EdgeInsets.only(
                top: 20,
              ),
              height: 45,
              width: sizeWidth(context),
              decoration: BoxDecoration(
                borderRadius: BorderRadius.circular(45),
                border: Border.all(
                  width: 1,
                  color: const Color(0xFFEDEDED),
                )
              ),
              child: CardField(
                cursorColor: const Color(0xFF000000),
                decoration: const InputDecoration(
                  border: InputBorder.none,
                ),
                onCardChanged: (card) {
                  if(card!.complete) {
                    setState(() {
                      cardValue = '${card.number}|${card.expiryMonth}|${card.expiryYear}|${card.cvc}';
                    });
                    print(cardValue);
                },
              ),
            ),

          ],
        ),
      ),
    );
  }
}

```

This code should print: 4242424242424242|12|24|123, for example. And in my console, it prints: null|null|null|null.
It's important to specify that I don't want to process raw data directly, I made this code as an example after all the payment tests I did didn't work because the card info was null. Then I saw that CardField wasn't returning any card data apart from "brand" and "complete".

environment:
  sdk: '>=3.0.6 <4.0.0'

flutter_stripe: ^9.4.0
 flutter_stripe_web: ^4.4.0

and all my packages are updated.

Even though I don't think it has anything to do with the problem I'm having, but it's weird, I can't figure out where to set these parameters and yet I'm also getting this in my console:
Height of Platform View type: [stripe_card] may not be set. Defaulting to `height: 100%`.
Set `style.height` to any appropriate value to stop this message.
Width of Platform View type: [stripe_card] may not be set. Defaulting to `width: 100%`.
Set `style.width` to any appropriate value to stop this message.

**Comment by remonh87** [comment]
This is intended because of PCI compliance requirements. You can get the card details by setting `dangerouslyGetFullCardDetails` . Be aware that then you need to comply to higher PCI standards and if you work in a small company it will be undoable.
