### ISSUE TITLE
initPaymentSheet returns null 

### ISSUE THREAD

**Issue by mohadel92** [flutter-stripe/flutter_stripe#1429]
**Describe the bug**
after creating my payment intent via api call i call the  `Stripe.instance.initPaymentSheet` but it always return null i can't know is i am moving in the right way so that i can display sheet call: `presentPaymentSheet` 

**To Reproduce**
1. create your payment intent
2. call Stripe.instance.initPaymentSheet
3. it will return null PaymentSheetPaymentOption

**Expected behavior**
at least getting any sign of success before moving to payment ,even payment sheet doesn't return any data

**Smartphone / tablet**
 - Device: Poco X3 Pro
 - OS: Android 12
 - Package version: 9.4.0
 - Flutter version latest

**Additional context**
the api call via create intent method also can't be parsed via `PaymentIntent.fromJson(response of the api)`

**Final list of issues**
1- initPaymentSheet returns null
2- presentPaymentSheet returns null
3- PaymentIntent.fromJson(response of the api) can't be parsed

**Comment by remonh87** [comment]
initpaymentsheet returns an empty future. If you await it and it completes without error it is successful
