### ISSUE TITLE
To Add Charges Api

### ISSUE THREAD

**Issue by jiten-acme** [flutter-stripe/flutter_stripe#143]
Are you planning to add Charges Api ? I am trying to look in to that today but couldn't figure it out.

**Comment by jamesblasco** [comment]
We are going to add support for it in the next version. But notice that this way to accept payments is disallowed and you should be sure to understand the implications of using it


![image](https://user-images.githubusercontent.com/19904063/121850178-a951f180-ccec-11eb-89aa-14b657177390.png)
https://stripe.com/docs/payments/accept-a-payment-charges

**Comment by remonh87** [comment]
This is already part of the sdk for a while. You can pay using card tokens.

**Comment by jamesdixon** [comment]
@remonh87 can you explain how to create a token from a card? I'm confused by the example as it shows collecting card details, then creating a token, but no card details are ever passed to tokenize the card.
