### ISSUE TITLE
Unable to dismiss keyboard in iOS - CardFormField

### ISSUE THREAD

**Issue by daviddavis83** [flutter-stripe/flutter_stripe#1430]
**Describe the bug**
On iOS I am unable to dismiss the keyboard after I tap into the credit card form. The form performs an animation downward but appears to pop back up. 

**To Reproduce**
1. Tap into Card Number field on iOS
2. Tap outside of the form field
3. Observe the keyboard does not dismiss

**Expected behavior**
I expect the keyboard to be dismissed

**Smartphone / tablet**
 - Device: iPhone 15 Pro Max
 - OS: ios 17.0
 - Package version: 9.4.0
 - Flutter version 3.13.1

**Additional context**
I tested on Android and the keyboard dismisses as expected. This only impacts iOS. 

https://github.com/flutter-stripe/flutter_stripe/assets/17017815/6faaae65-3312-439e-89b7-2aee46b29033

**Comment by remonh87** [comment]
This is unfortunately standard behavior of Flutter. You can try to dismiss it by `FocusManager.instance.primaryFocus?.unfocus()` .  On other hand I really would recommend using the paymentsheet as it has superior native user experience and customisation capabilities.

**Comment by lreardon** [comment]
This can't be considered resolved.

It's possible to work around this behavior be implementing onTapOutside in other form fields - something similar must be implemented here or CardFormField is completely unusable on iOS.
