### ISSUE TITLE
PaymentElement on web sometimes not showing

### ISSUE THREAD

**Issue by reginojohnrobert** [flutter-stripe/flutter_stripe#1432]
**Describe the bug**
Payment Element form is sometimes not showing or failed to load.

**To Reproduce**
1. Setup stripe with publishable key and account id and call applySettings() 
2. Load the screen with the Payment Element form for web in it.
3. Payment Element sometimes doesn't load/show with error on console
4. Error on console: Unhandled payment Element loaderror

**Expected behavior**
Payment Element should always show

**Smartphone / tablet**
 - Safari or Chrome
 - Safari 16.6
 - Package version: flutter_stripe 9.4.0 and flutter_stripe_web 4.4.0
 - Flutter version 3.10.6

**Additional context**
might be something to do with the **updateSettingsLazily** flag on the web_stripe.dart
currently there's no way to set this flag on the web package and it's hardcoded to false
we tried updating it to true and it seems to fix the issue.

**Comment by remonh87** [comment]
I cannot reproduce this issue. Can you give me some more info about the error (logs, chrome/safari debug info)?
