### ISSUE TITLE
Zip code is not verifying 

### ISSUE THREAD

**Issue by aalokhlink** [flutter-stripe/flutter_stripe#1434]
**Describe the bug**
I am using cardfield for add card. and I have set property for enable postalcode true in that when I am entering wrong card details its throw error in red color but when I add wrong zip code it doesn't showing any error and card is adding successfully based on generated token. so how can we overcome this issue ?
.

**Smartphone / tablet**
 - Device: [e.g. iPhone X]
 - OS: [e.g. iOS 13, Android 10]
 - Package version: [e.g. 1.0.0]
 - Flutter version [e.g. 9.4.0.]

**Comment by remonh87** [comment]
the zip code is only used for countries that need zip code for card verification (e.g. the USA). In production it will throw an error. If you want to collect the zip code for shipping I would recommend to collect it yourself and add it to billing details of the payment intent. 

The behaviour of the screen is outside our control but feel free to raise a ticket on https://github.com/stripe/stripe-react-native
