### ISSUE TITLE
Tapping blur/focus button in the sample app does not do anything

### ISSUE THREAD

**Issue by jooikwanw** [flutter-stripe/flutter_stripe#1435]
**Describe the bug**
1. Tapping blur button in the sample app in the card forms does not do anything. 
2. Tapping focus button in the sample app in the card forms only brings up keyboard but does not do anything else.

**To Reproduce**
1. Launch sample project provided
2. Go to Card Payments - Simple - Using webhooks or Card Payments - Card Form
3. Tap the blur/focus buttons

**Expected behavior**
1. For blur, the fields will be blurred when the button is pressed or anything that has to do with blurring.
2. A field will be focused when focus is pressed.

**Smartphone / tablet**
 - Samsung S9
 - OS: Android 10
 - Package version: 9.4.0
 - Flutter version 3.13.1

**Additional context**

**My main question is what do blur and focus actually do as I am not observing any behaviour at all?**

The CardFormEditController has a blur function but it doesn't seem to do anything when pressed? I have the fields filled up too. May I request a picture on how it is supposed to look like when its blurred/focused? 

When we use the form I assume we should provide a button for the customer to blur/unblur the fields? **Pressing focus also just brings up the keyboard but does not focus any field**

**Comment by remonh87** [comment]
Hi sorry for coming back to you a bit late but we were busy bringing out the new version of our sdk.

Focus issue:
For me it does what it says it focus on the card edit field and opens the keyboard(when you start typing it will enter the numbers). This is also a choice made by the stripe sdk. 

Blur issue:
This is a know issue on Android: https://github.com/stripe/stripe-react-native/issues/429 .
