### ISSUE TITLE
[Bug] Pressing system back button is closing the app even though there are multiple screens in navigation stack

### ISSUE THREAD

**Issue by pawanbhardwaj** [flutter-stripe/flutter_stripe#1436]
**Describe the bug**
After changing MainActivity to extend FlutterFragmentActivity, system back button behaviour has been disturbed. 

**To Reproduce**
1. Create empty flutter project
2. Integrate flutter_stripe to that project by following the package documentation
3. Create 2 separate pages
4. Navigate to 2nd page from 1st page
5. Then press, platform back button

**Expected behavior**
Pressing back button should pop only latest screen in the flutter navigation stack.

**Smartphone / tablet**
 - Device: Pixel 3a API 33
 - Package version: 9.4.0
 - Flutter version: 3.10.5

**Additional context**
If we use FlutterActivity, instead of FlutterFragmentActivity, this issue was not found. But the package can't be initialized.

**Comment by remonh87** [comment]
I doubt this has to do with the fragment activity as the navigation through the backbitten is correct in our example app.  Probably there is a bug in the navigator

**Comment by Kabariya** [comment]
@pawanbhardwaj Hi, I am having the same issue, Did you find the solution? Additional info: I using Getx

**Comment by logic-and-math** [comment]
Same issue here, if using FlutterActivity the systen back button works correctly, if using FlutterFragmentActivity it exits the app(pops the whole stack).
