### ISSUE TITLE
StripeAuthenticationError

### ISSUE THREAD

**Issue by waqasofswat** [flutter-stripe/flutter_stripe#1437]
**Describe the bug**
StripeAuthenticationError: You did not provide an API key. You need to provide your API key in the Authorization header, using Bearer auth (e.g. 'Authorization: Bearer YOUR_SECRET_KEY'). See https://stripe.com/docs/api#authenticatio
n for details, or we can help at https://support.stripe.com/.

**To Reproduce**
1. put api key and secret keys in env.example in both app and server
2. run the server and run the app on emulator
3. go to payment screen and press init payment sheet

**Comment by remonh87** [comment]
You need to put the key in the .env file as described here: https://github.com/flutter-stripe/flutter_stripe#run-the-example-app
