### ISSUE TITLE
Tap to Pay - Android & iOS

### ISSUE THREAD

**Issue by yatinj30** [flutter-stripe/flutter_stripe#1439]
I was trying to implement Tap to Pay in Android. However, I found that there is no methods or way to implement this.

The feature is already released by the stripe a long time ago. [Here](https://stripe.com/docs/terminal/payments/setup-reader/tap-to-pay) is the official doc. Further, they also provided the [example code](https://github.com/stripe-samples/tap-to-pay-android-demo) implemented in Android using their Native Android SDKs. 

Additionally, it should be implemented for both Android and iOS.

**Comment by parth-tagadiya** [comment]
Yes, I am also facing this, Can anyone help with it?

**Comment by krish-sohamtech** [comment]
Yes, i was also looking for solution. Is there any way to implement this?

**Comment by jaykukadiya99** [comment]
Let me know, if anyone has a solution.

Thanks in advance!!

**Comment by vivekjagani** [comment]
Finally, someone raised an issue. Let's see when we get the package update for this😅
.

**Comment by vivekjagani** [comment]
Finally, someone raised an issue. Let's see when we get the package update for this 😅.

**Comment by Nayan-03** [comment]
Waiting for update on this.....

**Comment by sanket-hv** [comment]
I would also like to get it fixed. Really in need of this. 
Thanks @yatinj30 for raising issues here.

**Comment by KevinShingala** [comment]
I would like to get it resolved asap.

**Comment by jonasbark** [comment]
Closing this in favor of https://github.com/flutter-stripe/flutter_stripe/issues/39
