### ISSUE TITLE
Another exception was thrown: Unsupported operation: Platform._operatingSystem [WEB]

### ISSUE THREAD

**Issue by Flucadetena** [flutter-stripe/flutter_stripe#1440]
**Describe the bug**
The flutter stripe web package throughs this error
```
Another exception was thrown: Unsupported operation: Platform._operatingSystem
```
- When running locally it throughs the error when showing the "CardFormField".
- When the app is deployed to "Firebase hosting" the error appears before starting the app and it won't pass the Splash acreen.

**To Reproduce**
Run the latest version of the package and show the "CardFormField" or deploy it to a hosting.

**Expected behavior**
For the error not to show and work as expected.

**Smartphone / tablet**
 - Device: Mac
 - OS: Web - Chrome
 - Package version:
  = flutter_stripe: ^9.4.0
  = flutter_stripe_web: ^4.4.0

 - Flutter version 3.13.2 - Stable
   = Inside the project: '>=3.0.6 <4.0.0' 

**Additional context**
I can confirm that when deployed, if I add
```
if(!kIsWeb){
    Init Stripe -------
}
```
I won't through the error and the app will run, but obviously the "CardFormFiel" wont show.

**Comment by remonh87** [comment]
Cardform is a mobile payment element. Use `PlatformPaymentElement` instead for the web
