### ISSUE TITLE
PaymentElement zip code on flutter web with android shows a white screen

### ISSUE THREAD

**Issue by URSFR** [flutter-stripe/flutter_stripe#1448]
Using flutter web with Android using the PaymentElement widget when selecting the zip code space a white screen overlays the field.

Images:

In this image the zip code is below everything on the screen (having even more space below if you scroll) but being where the cell phone keyboard should be the error occurs in image 2, covering the part of the zip code with a white screen and this does not allow the field to be filled out

1)
![werrornw](https://github.com/flutter-stripe/flutter_stripe/assets/97409596/4ee9159e-f43f-4f43-af76-b5d0582b02ef)

2)
![werrorw](https://github.com/flutter-stripe/flutter_stripe/assets/97409596/c805b21f-5ead-48e3-b36f-3d9c4d895de9)

On the other hand, if it does not occupy the space where the keyboard should be, it would work as expected. 

3)
![wherrornw](https://github.com/flutter-stripe/flutter_stripe/assets/97409596/4c8b47a9-8a8c-4241-8a89-b8372d4dee5d)

4)
![wherrorw](https://github.com/flutter-stripe/flutter_stripe/assets/97409596/6f2e2973-d8bd-4c31-8202-6cef6adefad0)

What should happen in short is that even though the zip code will occupy the space where the keyboard would appear, the zip code should still be displayed by pushing it above that white screen or removing it.
the app in production the zip code must be at the end of the screen, therefore my solution cannot be moving it to another place, I tried to reduce the size of everything but there was no solution.

Code:
home.dart

```
    final size = MediaQuery.sizeOf(context);
    return GetBuilder<UserController>(builder: (controller)=>
        SingleChildScrollView(
          keyboardDismissBehavior: ScrollViewKeyboardDismissBehavior.onDrag,
          child: Container(
            alignment: Alignment.center,
            margin: const EdgeInsets.only(left: 35,right: 35),
            child: Column(
              children: [
                SizedBox(height: size.height/3.5,),
                PaymentElement(
                  layout: PaymentElementLayout.tabs,
                  autofocus: true,
                  enablePostalCode: true,
                  onCardChanged: (value) {},
                  clientSecret: controller.clientSecret!,
                ),
                SizedBox(height: size.height/3.5,),
              ],
            ),
        ),
    ));
```

I have also tried adding Scaffold with resizeToAvoidBottomInset: false, but results in the same error
```
    return Scaffold(
      resizeToAvoidBottomInset: false,
      body: GetBuilder<UserController>(builder: (controller)=>
          SingleChildScrollView(
            keyboardDismissBehavior: ScrollViewKeyboardDismissBehavior.onDrag,
            child: Container(
              alignment: Alignment.center,
              margin: const EdgeInsets.only(left: 35,right: 35),
              child: Column(
                children: [
                  SizedBox(height: size.height/3.5,),
                  PaymentElement(
                    layout: PaymentElementLayout.tabs,
                    autofocus: true,
                    enablePostalCode: true,
                    onCardChanged: (value) {},
                    clientSecret: controller.clientSecret!,
                  ),
                  SizedBox(height: size.height/3.5,),
                ],
              ),
          ),
      )),
    );
```

flutter doctor -v

> [√] Flutter (Channel stable, 3.13.6, on Microsoft Windows [Versi¢n 10.0.19045.3570], locale es-AR)
>     • Flutter version 3.13.6 on channel stable at C:\flutter
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision ead455963c (2 weeks ago), 2023-09-26 18:28:17 -0700
>     • Engine revision a794cf2681
>     • Dart version 3.1.3
>     • DevTools version 2.25.0
> 
> [√] Windows Version (Installed version of Windows is version 10 or higher)
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
>     • Android SDK at C:\Users\vampi\AppData\Local\Android\sdk
>     • Platform android-34, build-tools 34.0.0
>     • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
>     • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
>     • All Android licenses accepted.
> 
> [√] Chrome - develop for the web
>     • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe
> 
> [√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.1)
>     • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
>     • Visual Studio Community 2022 version 17.7.34009.444
>     • Windows 10 SDK version 10.0.22621.0
> 
> [√] Android Studio (version 2022.3)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
> 
> [√] IntelliJ IDEA Community Edition (version 2023.2)
>     • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2023.2.2
>     • Flutter plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/6351-dart
> 
> [√] Connected device (3 available)
>     • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Versi¢n 10.0.19045.3570]
>     • Chrome (web)      • chrome  • web-javascript • Google Chrome 117.0.5938.152
>     • Edge (web)        • edge    • web-javascript • Microsoft Edge 117.0.2045.60
> 
> [√] Network resources
>     • All expected network resources are available.
> 
> • No issues found!

Reproducible example on github:
[Example](https://github.com/URSFR/error_stripe_example)

In the example change variables.dart with your own Stripe keys

This error on iOS does not occur.

UPDATE:
i detected the white screen is the index.html

**Comment by remonh87** [comment]
What if you wrap you wrap the payment element in a `SingleChildScrollview`?

**Comment by URSFR** [comment]
> What if you wrap you wrap the payment element in a `SingleChildScrollview`?

Yes, I have tried that, but I found where the error is and a small solution:

in payment_element of stripe_web the problem is when the html element is created. So to fix a little i added
```
          _divElement.style.height = '100%';
          _divElement.style.overflow = "hidden";
          _divElement.style.margin = "0";
```

to:
` late final resizeObserver = ResizeObserver`

so it looks like this:

```
  late final resizeObserver = ResizeObserver((entries, observer) {
    for (final entry in entries) {
      if (entry.contentRect is DomRectReadOnly) {
        final cr = entry.contentRect;
        final height = cr.height;
        setState(() {
          this.height = height;
          _divElement.style.height = '100%';
          _divElement.style.overflow = "hidden";
          _divElement.style.margin = "0";
        });
      }
    }
  });
```
sometimes it leaves a little space, but at least the field to fill in is always shown

It should be corrected because you have to enter the package to fix it
