### ISSUE TITLE
Integration Guide for Apple Pay & Google Pay with Payment Sheet

### ISSUE THREAD

**Issue by abumoallim** [flutter-stripe/flutter_stripe#145]
I can't find any documention related to integration of Apple Pay or Google Pay inside the Payment Sheet.

As I can see in the library itself it shows that if configuration is set it will show the Google Pay & Apple pay inside the Payment Sheet but what are the configuration steps for both?

**Comment by jamesblasco** [comment]
Here are the integration docs for Apple Pay on iOS
https://stripe.com/docs/payments/accept-a-payment?platform=ios&ui=payment-sheet#apple-pay

And for Google Pay on Android 
https://stripe.com/docs/payments/accept-a-payment?platform=android&ui=payment-sheet#google-pay

I am planning to improve the docs soon to improve this
