### ISSUE TITLE
Stripe integration for flutter web

### ISSUE THREAD

**Issue by ankitmiyantechspian** [flutter-stripe/flutter_stripe#1451]
A clear and concise description of what the problem is. Ex. I would like to see [...]
I have successfully integrated the stripe payment gateway using flutter_stripe packages.
1. First I am generating a payment intent in which I am getting a secret key and payment intent ID.
2. Based on the payment intent ID and secret key I am able to open a payment sheet in Android and iOS mobile apps.
3. After opening the payment sheet and successful payment I am able to capture the payment using the payment intent ID.

But when using a similar process I am unable to through the payment process in Flutter Web.
Using stripe checkout and passing line items, it works but in my case, I am using it for the hotel booking application where I can create and hit the product API every time to generate the line items to complete the payment.
I want it simple like a mobile app as when the user clicks on the book now button it should open a stripe card view on a popup or anyway with the billing address form, and then it should accept the details of the customer.

<img width="519" alt="Screenshot 2023-10-19 at 7 35 58 PM" src="https://github.com/flutter-stripe/flutter_stripe/assets/137860496/2d2abf89-30d2-48dd-94cb-95d28de49600">
<img width="475" alt="Screenshot 2023-10-19 at 7 36 12 PM" src="https://github.com/flutter-stripe/flutter_stripe/assets/137860496/88c37205-a191-4362-a1e2-bbf92bc5eb9d">
<img width="303" alt="Screenshot 2023-10-19 at 7 36 27 PM" src="https://github.com/flutter-stripe/flutter_stripe/assets/137860496/efa4d529-8f5d-4ad9-8fc7-364a13fbf600">

**Comment by remonh87** [comment]
Payment sheet is a mobile element and thus not available for the web.

Use[ payment element](https://github.com/flutter-stripe/flutter_stripe/blob/main/example/lib/screens/payment_sheet/payment_element/payment_element.dart) instead
