### ISSUE TITLE
`pod install` fails to parse `Specs/c/e/7/Stripe/23.18.0/Stripe.podspec.json`

### ISSUE THREAD

**Issue by asaarnak** [flutter-stripe/flutter_stripe#1456]
When i remove the `flutter_stripe` dependency then `pod install` works.

Error when running `pod install`:
```
JSON::ParserError - Failed to parse JSON at file: '/Users/home/.cocoapods/repos/trunk/Specs/c/e/7/Stripe/23.18.0/Stripe.podspec.json'.

859: unexpected token at ''
/Users/home/.gem/gems/cocoapods-core-1.13.0/lib/cocoapods-core/specification/json.rb:66:in `rescue in from_json'
/Users/home/.gem/gems/cocoapods-core-1.13.0/lib/cocoapods-core/specification/json.rb:61:in `from_json'
```

**Comment by jonasbark** [comment]
This in unrelated to our plugin itself.

Maybe try removing cocopods cache or removing /Users/home/.cocoapods/repos/trunk/Specs/c/e/7/Stripe/23.18.0 manually

**Comment by asaarnak** [comment]
@jonasbark
I tried
`rm -rf ~/.cocoapods/repos`
and also 
`pod cache clean --all`
and also
`flutter clean`
but still `pod install` fails.
Only when i remove `flutter_stripe` from `pubspec.json` then `pod install` works fine.

**Comment by asaarnak** [comment]
@jonasbark 
I can reproduce the issue when cloning https://github.com/flutter-stripe/flutter_stripe
And running the `example` project.
Also my coworker has the same issue on his Mac.

**Comment by asaarnak** [comment]
Same error after updating cocoapods and ruby to latest.
```
    JSON::ParserError - Failed to parse JSON at file: '/Users/home/.cocoapods/repos/trunk/Specs/c/e/7/Stripe/23.18.0/Stripe.podspec.json'.

    unexpected token at ''
    /Users/home/.rvm/gems/ruby-3.2.2/gems/cocoapods-core-1.14.0/lib/cocoapods-core/specification/json.rb:66:in `rescue in from_json'
    /Users/home/.rvm/gems/ruby-3.2.2/gems/cocoapods-core-1.14.0/lib/cocoapods-core/specification/json.rb:61:in `from_json'
```

**Comment by asaarnak** [comment]
@jonasbark 
Waited for about 2 weeks and tried again and it started working.
No clean or delete cache was needed.
Maybe some CDN issue that the 23.18.0 json parsing failed.
There are also 2 new versions, 23.18.1 and 23.18.2 here: https://github.com/CocoaPods/Specs/blob/master/Specs/c/e/7/Stripe/
