### ISSUE TITLE
 StripeException(error: LocalizedErrorMessage(code: FailureCode.Failed, localizedMessage: , message: null, stripeErrorCode: null, declineCode: null, type: null))

### ISSUE THREAD

**Issue by salahu01** [flutter-stripe/flutter_stripe#1458]
const billingDetails = BillingDetails(
        email: 'developer1@gmail.com',
        phone: '+48888000888',
        address: Address(
          city: 'Houston',
          country: 'US',
          line1: '1459  Circle Drive',
          line2: '',
          state: 'Texas',
          postalCode: '77063',
        ),
      );

      await Stripe.instance.dangerouslyUpdateCardDetails(CardDetails(
        cvc: card.ccv,
        expirationMonth: int.parse(card.expirationDate!.split('/').first),
        expirationYear: int.parse(card.expirationDate!.split('/').last),
        number: card.cardNumber,
      ));

      await Stripe.instance.confirmPayment(
        paymentIntentClientSecret: secret,
        data: const PaymentMethodParams.card(
          paymentMethodData: PaymentMethodData(
            billingDetails: billingDetails,
          ),
        ),

      );

flutter version : 3.13.6
package version :  ^9.5.0+1

**Comment by remonh87** [comment]
the localized error message is that something is going wrong in the Stripe sdk. I would check in your stripe dashboard what is going wrong

Also be aware that with the method you implelement your organisation needs to become PCI compliant which is a lot of paperwork. I recommend using the paymentsheet which has superior user experience, customization capabilities  and  better error handling

**Comment by salahu01** [comment]
But we are using using card selection .

I also tried paymentsheet option it also provides same issue . 

Is there any way to transfer the card details to the payment sheet? .

**Comment by remonh87** [comment]
I cannot do anything without a reproduction example it seems like you have a configuration issue on your side.  Can you check: https://docs.page/flutter-stripe/flutter_stripe/sheet ? 

Also try out our example app in this repo. IF this does not work I really need a full reproduction example so I can test it.

**Comment by salahu01** [comment]
await Stripe.instance.initPaymentSheet(
        paymentSheetParameters: SetupPaymentSheetParameters(
          paymentIntentClientSecret: secret,
          style: ThemeMode.dark,
          merchantDisplayName: 'fegno',
          billingDetails: billingDetails,
        ),
      );

      await Stripe.instance.presentPaymentSheet();

* I also tried this and it gives same issue.

**Comment by remonh87** [comment]
For me this works without issues. I would recommend looking into the stripe dashboard and see what is wrong with the particular payment intent. It can be that some things are not matching. One thing are you using the test publishable key in your app? If you use the production key this will not work with the payment sheet in test mode

**Comment by salahu01** [comment]
Finally i got it . 

Is there any currency restriction

![Screenshot_20231029_141408](https://github.com/flutter-stripe/flutter_stripe/assets/102010173/794f3b02-c552-442c-b9ad-dcabfa7f4039)
