### ISSUE TITLE
initCustomerSheet returns null & No confirm button shows up when Card already saved

### ISSUE THREAD

**Issue by dharmendrasinh-concetto** [flutter-stripe/flutter_stripe#1459]
**initCustomerSheet returns null**
1. When opening initCustomerSheet, it returns null.
2. On click of Close icon, it throws error : 'Null' is not a subtype of  'String' in type cast (stacktrace is provided below.)
3. When one card is saved, then next time presentCustomerSheet opens up with Add New & Saved Card option, here Saved Card is ticked by default for payment choice, but it's not showing Confirm button. Only way to get that button is remove card and add new again.

**Smartphone / tablet**
 - Device:  Android
 - OS: Android 10
 - Package version:  9.5.0+1 
 - Flutter version : 3.13.7

**Additional context**
$$_PaymentSheetPaymentOptionFromJson (package:stripe_platform_interface/src/models/payment_sheet.g.dart:406:28)
     new _$_PaymentSheetPaymentOption.fromJson (package:stripe_platform_interface/src/models/payment_sheet.freezed.dart:4570:7)
      _$PaymentSheetPaymentOptionFromJson (package:stripe_platform_interface/src/models/payment_sheet.freezed.dart:4465:37)
      new PaymentSheetPaymentOption.fromJson (package:stripe_platform_interface/src/models/payment_sheet.dart:464:7)
      _$$_CustomerSheetResultFromJson (package:stripe_platform_interface/src/models/customer_sheet.g.dart:103:39)
      new _$_CustomerSheetResult.fromJson (package:stripe_platform_interface/src/models/customer_sheet.freezed.dart:968:7)
      _$CustomerSheetResultFromJson (package:stripe_platform_interface/src/models/customer_sheet.freezed.dart:799:31)
      new CustomerSheetResult.fromJson (package:stripe_platform_interface/src/models/customer_sheet.dart:95:7)
      MethodChannelStripe._parseCustomerSheetResult (package:stripe_platform_interface/src/method_channel_stripe.dart:355:36)
      MethodChannelStripe.presentCustomerSheet (package:stripe_platform_interface/src/method_channel_stripe.dart:277:12)
<asynchronous suspension>

**Comment by remonh87** [comment]
thanks I created a fix for this. PR will follow this weekend (want to fix other issues as well).

**Comment by dharmendrasinh-concetto** [comment]
@remonh87 Thank you so much. Can I check that PR? So that I can confirm it's working for me !!

**Comment by remonh87** [comment]
the fixes are on branch `bugfixes`
