### ISSUE TITLE
Apple Pay Button is not shwoing

### ISSUE THREAD

**Issue by manishdubeit** [flutter-stripe/flutter_stripe#1462]
**Describe the bug**
I want to Implement the Apple Pay option in my Flutter app, but the Apple Pay button is not appearing in the Payment Sheet. I'm using flutter_stripe version 9.4.0.

I have configured the merchant ID and successfully uploaded the certificate in Stripe. Additionally, I've added the Apple Pay capability in Xcode, and I can see the created merchant ID there. I followed the instructions on this page (https://docs.page/flutter-stripe/flutter_stripe/sheet) to configure Apple Pay.

I also attempted to use flutter_stripe version 9.5.0, but it didn't work.

Currently sheet is showing like this: 
<img width="338" alt="image" src="https://github.com/flutter-stripe/flutter_stripe/assets/38417244/11b7c682-799e-4cc8-b656-d210c3837f1d">

**To Reproduce**

1. Opening up sheet
2. Payment sheet opens, but not shwoing Apple Pay Butoon

**Expected behavior**
The Apple Pay button should appear on the sheet like the image below.
 <img width="404" alt="image" src="https://github.com/flutter-stripe/flutter_stripe/assets/38417244/cb73f62b-3ff1-4e38-b371-8a2d5fb7a655">

**Smartphone / tablet**
 - Device: [e.g. iPhone 13]
 - OS: [e.g. iOS 16]
 - Package version: [e.g. 9.4.0]
 - Flutter version [e.g. 3.10.0]

**Additional context**

// This is the code I'm using to display the payment sheet:

```
await Stripe.instance.initPaymentSheet(
  paymentSheetParameters: SetupPaymentSheetParameters(
    // Main parameters
    paymentIntentClientSecret: paymentIntent.clientSecret,
    merchantDisplayName: 'MyTestApp',
    // Customer parameters
    customerId: paymentIntent.customerId,
    // customerEphemeralKeySecret: data['ephemeralKey'],
    // Extra parameters
    applePay: PaymentSheetApplePay(
      buttonType: PlatformButtonType.pay,
      merchantCountryCode: 'US',
    ),
    // ... other parameters ...
  )
);
```

// I also attempted to check if Apple Pay is supported with this code, and it returned false:

```
final isApplePaySupported = await Stripe.instance.isApplePaySupported();
print("isApplePaySupported $isApplePaySupported"); // it print false

```
// This is the initialization of Stripe in my code:

```
// Initialize Stripe
Stripe.publishableKey = Config.stripePublishableKey;
Stripe.merchantIdentifier = Config.stripeMerchantIdentifier;
Stripe.urlScheme = 'flutterstripe';
Stripe.instance.applySettings();

```

**Comment by remonh87** [comment]
does your phone have apple pay enabled? Also try to run it on a simulator first and see if the button appears. For me it works on version 9.5.0

**Comment by manishdubeit** [comment]
No my phone doesn't have apple pay enabled, i tried to run it on simulator it works on simulator.

**Comment by remonh87** [comment]
that is required for it to work :) closing it for now

**Comment by dicky28revo** [comment]
Hello @remonh87 , I have same issue like this. It worked at simulator, but not work at real device (iPhone XS). I have activated my Apple Pay

**Comment by manishdubeit** [comment]
> > does your phone have apple pay enabled? Also try to run it on a simulator first and see if the button appears. For me it works on version 9.5.0
> 
> How can we check this? @remonh87 @dicky28revo

Hi, you can test it on the iOS simulator. For testing on a real device, ensure that Apple Wallet is enabled on your iPhone. Since Apple Wallet is not widely used in India, I may not be able to check it. You should first explore how to set up Apple Wallet on your device.

In my case, my client has Apple Wallet on his iPhone, so he was able to confirm that Apple Pay was working perfectly, and he successfully made a payment.

**Comment by dicky28revo** [comment]
> > > does your phone have apple pay enabled? Also try to run it on a simulator first and see if the button appears. For me it works on version 9.5.0
> > 
> > 
> > How can we check this? @remonh87 @dicky28revo
> 
> Hi, you can test it on the iOS simulator. For testing on a real device, ensure that Apple Wallet is enabled on your iPhone. Since Apple Wallet is not widely used in India, I may not be able to check it. You should first explore how to set up Apple Wallet on your device.
> 
> In my case, my client has Apple Wallet on his iPhone, so he was able to confirm that Apple Pay was working perfectly, and he successfully made a payment.

Hi, thank you for sharing.

so if on iOS simulator is worked, is it work too on real device? Because on my client side at Singapore, it didn't work. He was already activate the Apple Pay with many CC
