### ISSUE TITLE
Using connected account as destination gives No such payment_intent: 'pi_XXX'

### ISSUE THREAD

**Issue by FancyPandaSoftworks** [flutter-stripe/flutter_stripe#1463]
**Describe the bug**
When you set the stripeAccountId and create a destination charge, it will fail.

**To Reproduce**
1. Create payment intent

```
Stripe.stripeAccountId
Map<String, dynamic> body = {
      'amount': amount,
      'currency': widget.restaurant.currency,
      // 'payment_method_types[]': 'ideal',
      'transfer_data[destination]': Stripe.stripeAccountId
    };
```
Example of output: 
```
{id: pi_3O6KK0GvLB0vMUvf0xHHnMeW, object: payment_intent, amount: 420, amount_capturable: 0, amount_details: {tip: {}}, amount_received: 0, application: null, application_fee_amount: null, automatic_payment_methods: null, canceled_at: null, cancellation_reason: null, capture_method: automatic, client_secret: pi_3O6KK0GvLB0vMUvf0xHHnMeW_secret_uXXXXA, confirmation_method: automatic, created: 1698529532, currency: eur, customer: null, description: null, invoice: null, last_payment_error: null, latest_charge: null, livemode: false, metadata: {}, next_action: null, on_behalf_of: null, payment_method: null, payment_method_configuration_details: null, payment_method_options: {ideal: {}}, payment_method_types: [ideal], processing: null, receipt_email: null, review: null, setup_future_usage: null, shipping: null, source: null, statement_descriptor: null, statement_descriptor_suffix: null, status: requires_payment_method, transfer_data: {destination: acct_zzz}, transfer_group: null}
```
2. initialize payment:
```
await Stripe.instance.initPaymentSheet(
          paymentSheetParameters: SetupPaymentSheetParameters(
              paymentIntentClientSecret: paymentIntent['client_secret'],
              style: ThemeMode.dark,
              googlePay: gpay,
              merchantDisplayName: franchiseName));
```

3. displayPaymentSheet
This is where it goes wrong with the following error:

```
StripeException(error: LocalizedErrorMessage(code: FailureCode.Failed, localizedMessage: No such payment_intent: 'pi_3O6KK0GvLB0vMUvf0xHHnMeW', message: No such payment_intent: 'pi_3O6KK0GvLB0vMUvf0xHHnMeW', stripeErrorCode: resource_missing, declineCode: null, type: invalid_request_error))
```
**Expected behavior**
You would expect to have the same as using main account, showing up ideal payment and Gpay. Instead, the payment sheet can't be displayed.

Any idea what may be causing this? I have asked Stripe support and they can't seem to find the cause either.

**Additional context**

This is on dashboard for connect account (404 response):
![error](https://github.com/flutter-stripe/flutter_stripe/assets/15878164/b2e67e6f-1deb-431e-b74b-7fad67b25c52)

However, on the main account it gives a 200 response:
![main_success](https://github.com/flutter-stripe/flutter_stripe/assets/15878164/9b52e186-eb0c-46a1-9526-f0ab49ae590e)

With "id": "pi_3O6KDEGvLB0vMUvf16z5J8Cf"

**Comment by remonh87** [comment]
I wish I could help you but this really should be sorted out with Stripe support as this is something thrown by the native sdks. Our library is just a flutter wrapper around it and we pass the native error to the flutter layer. 

Also is your company in Stripe registered in the EU (I can be mistaken but this is a requirement for Ideal) and is the ideal payment method enabled on the dashboard?

CLosing it as it is outside scope of this lib

**Comment by FancyPandaSoftworks** [comment]
@moesaid Hey there, I wrapped the parameters individually for each payment method. It is a pain but that's the only way I could think of. 

![Image](https://github.com/user-attachments/assets/9f8efe01-af8b-4643-a467-c69e1780e6ca)

**Comment by moesaid** [comment]
@FancyPandaSoftworks hey bud! Thanks for the update! 

I ended up using `setup intent` and handling the business logic on the server to create the payment intent
