### ISSUE TITLE
PaymentSheetError: Unknown result this is likely a problem in the plugin {paymentOption: null}

### ISSUE THREAD

**Issue by hibbert-de** [flutter-stripe/flutter_stripe#1465]
**Describe the bug**
When i want to create a custom flow on iOS, the PaymentSheet won't open. I have initialized the Sheet with `paymentIntentClientSecret` `customerEphemeralKeySecret` and `customerId`. This is working on Android as it should, I only have this problem with iOS.

**Full error message**
```
flutter: StripeError<PaymentSheetError>(message: Unknown result this is likely a problem in the plugin {paymentOption: null}, code: PaymentSheetError.unknown)
```

**To Reproduce**
Download the flutter_stripe Package, enter your keys in the example for Frontend and Backend, run the local server.
I have a screen recording with breakpoints in the flutter Package. The device i not a simulator, i have mirrored my iPhone to my mac.
https://www.youtube.com/watch?v=D5FXbxylJ1I
this is my init of the PaymentSheet
```[dart]
await Stripe.instance.initPaymentSheet(
        paymentSheetParameters: SetupPaymentSheetParameters(
          customFlow: true,
          merchantDisplayName: 'myTest',
          setupIntentClientSecret: paymentIntentClientSecret,
          paymentIntentClientSecret: paymentIntentClientSecret,
          customerEphemeralKeySecret: customerEphemeralKeySecret,
          customerId: customerId,
          allowsDelayedPaymentMethods: true,
          billingDetails: BillingDetails(
            address: Address(
                city: state.currentBasket?.shippingAddress?.city,
                country: state.currentBasket?.shippingAddress?.country,
                line1: state.currentBasket?.shippingAddress?.address1,
                line2: state.currentBasket?.shippingAddress?.address2,
                postalCode: state.currentBasket?.shippingAddress?.zip,
                state: state.currentBasket?.shippingAddress?.state),
            name:
                "${state.currentBasket?.shippingAddress?.firstName} ${state.currentBasket?.shippingAddress?.lastName}",
            email: state.currentBasket?.shippingAddress?.email,
            phone: state.currentBasket?.shippingAddress?.phone,
          ),
          applePay: const PaymentSheetApplePay(
            merchantCountryCode: 'IN',
          ),
          googlePay: const PaymentSheetGooglePay(merchantCountryCode: 'IN'),
          style: ThemeMode.dark,
        ),
      );
```
and when i call  `await Stripe.instance.presentPaymentSheet();` this exception is thrown:
`flutter: StripeError<PaymentSheetError>(message: Unknown result this is likely a problem in the plugin {paymentOption: null}, code: PaymentSheetError.unknown)`

**Expected behavior**
The Payment sheet should open and the Payment should be successfully shown in the dashboard, like on Android.

**Smartphone / tablet**
 - Device: iPhone 12
 - OS: 16.61
 - Package version: flutter_stripe: 9.5.0+1
 - Flutter version: stable, 3.13.0

**Additional context**
```
[✓] Flutter (Channel stable, 3.13.0, on macOS 13.4 22F66 darwin-arm64, locale
    de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```

**Comment by ahsi1999** [comment]
I am having the same issue in iOS in Android it is working fine.

**Comment by hibbert-de** [comment]
i have found a solution:
i have forked the `flutter_stripe` plugin, and modified this file:
https://github.com/flutter-stripe/flutter_stripe/blob/main/packages/stripe_platform_interface/lib/src/stripe_platform_interface.dart
```dart
 @override
  Future<PaymentSheetPaymentOption?> initPaymentSheet(
      SetupPaymentSheetParameters params) async {
    final result = await _methodChannel.invokeMethod(
      'initPaymentSheet',
      {'params': params.toJson()},
    );
    if (params.intentConfiguration?.confirmHandler != null) {
      _addListenerForDeffered();
      _confirmHandler = params.intentConfiguration?.confirmHandler;
    }
    // iOS workaround for no paymentOptions
    if (result['paymentOption'] == null) {
      return null; // just return null
    } else if (result is List) {
      return null;
    } else {
      return _parsePaymentSheetResult(result);
    }
  }
```
i do not know if this is the correct way, but it is working, for now.

**Comment by ChristineWasike** [comment]
Great, how did you go about linking this to your project?
