### ISSUE TITLE
When using GooglePay for confirming setup or payment intent, MissingPluginException gets thrown.

### ISSUE THREAD

**Issue by elvinasn** [flutter-stripe/flutter_stripe#1470]
**Describe the bug**
When using google pay with custom button(instead of using PlatformPayButton, since it does not work with Flutter 3.13 version) the methods confirmPlatformPaySetupIntent and confirmPlatformPayPaymentIntent throws ```MissingPluginException(No implementation found for method confirmPlatformPay on channel flutter.stripe/payments).```

Also, this gets printed: 
```
E/DartMessenger(24014): Uncaught exception in binary message listener
E/DartMessenger(24014): org.json.JSONException: No value for amount
E/DartMessenger(24014): 	at org.json.JSONObject.get(JSONObject.java:399)
E/DartMessenger(24014): 	at org.json.JSONObject.getInt(JSONObject.java:488)
E/DartMessenger(24014): 	at com.facebook.react.bridge.ReadableMap.getInt(ReadableMap.java:49)
E/DartMessenger(24014): 	at com.reactnativestripesdk.GooglePayLauncherFragment.presentGooglePaySheet(GooglePayLauncherFragment.kt:52)
E/DartMessenger(24014): 	at com.reactnativestripesdk.StripeSdkModule.confirmPlatformPay(StripeSdkModule.kt:584)
E/DartMessenger(24014): 	at com.flutter.stripe.StripeAndroidPlugin.onMethodCall(StripeAndroidPlugin.kt:197)
E/DartMessenger(24014): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/DartMessenger(24014): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/DartMessenger(24014): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/DartMessenger(24014): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/DartMessenger(24014): 	at android.os.Handler.handleCallback(Handler.java:900)
E/DartMessenger(24014): 	at android.os.Handler.dispatchMessage(Handler.java:103)
E/DartMessenger(24014): 	at android.os.Looper.loop(Looper.java:219)
E/DartMessenger(24014): 	at android.app.ActivityThread.main(ActivityThread.java:8668)
E/DartMessenger(24014): 	at java.lang.reflect.Method.invoke(Native Method)
E/DartMessenger(24014): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/DartMessenger(24014): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
```

**To Reproduce**
1. Create setup/payment intent in the backend
2. Use created intent client secret with confirmPlatformPaySetupIntent or confirmPlatformPayPaymentIntent.
3. Get error described.
**Expected behavior**
I expect that the methods work and i get bottom sheet so I can confirm.

**Smartphone / tablet**
 - Device: Huawei P30 Lite
 - OS: Android 11
 - Package version: 9.5.0+1
 - Flutter version 3.13.6
**Additional context**

This is the method I call for confirming setup intent:
```
Future<bool> confirmPlatfromSetupIntent(String clientSecret) async {
    try {
      if (Platform.isAndroid) {
        await _read(stripeProvider).confirmPlatformPaySetupIntent(
          clientSecret: clientSecret,
          confirmParams: const PlatformPayConfirmParams.googlePay(
            googlePay: GooglePayParams(
              merchantName: 'Meetelp',
              allowCreditCards: true,
              isEmailRequired: false,
              testEnv: kDebugMode,
              currencyCode: 'eur',
              merchantCountryCode: 'lt',
            ),
          ),
        );
        return true;
      }
      await _read(stripeProvider).confirmPlatformPaySetupIntent(
        clientSecret: clientSecret,
        confirmParams: const PlatformPayConfirmParams.applePay(
          applePay: ApplePayParams(
            cartItems: [
              ApplePayCartSummaryItem.immediate(
                label: 'Meetelp',
                amount: '0',
              ),
            ],
            merchantCountryCode: 'lt',
            currencyCode: 'eur',
          ),
        ),
      );
      return true;
    } catch (e) {
      log('error: $e');
      return false;
    }
  }
```

Code for confirming payment intent: 

```
 if (Platform.isIOS) {
        paymentIntent =
            await _read(stripeProvider).confirmPlatformPayPaymentIntent(
          clientSecret: paymentSecret,
          confirmParams: PlatformPayConfirmParams.applePay(
            applePay: ApplePayParams(
              cartItems: [
                ApplePayCartSummaryItem.immediate(
                  label: '$psychologistFullName(via Meetelp)',
                  amount: amount.toString(),
                ),
              ],
              merchantCountryCode: countryCode,
              currencyCode: currency,
            ),
          ),
        );
      } else {

        paymentIntent =
            await _read(stripeProvider).confirmPlatformPayPaymentIntent(
          clientSecret: paymentSecret,
          confirmParams: PlatformPayConfirmParams.googlePay(
            googlePay: GooglePayParams(
              merchantName: '$psychologistFullName(via Meetelp)',
              allowCreditCards: true,
              isEmailRequired: false,
              testEnv: kDebugMode,
              merchantCountryCode: countryCode,
              currencyCode: countryCode,
            ),
          ),
        );
      }
```

**Comment by Rimantovas** [comment]
Did you manage to solve this?

**Comment by perkuns** [comment]
Also having this issue with my side project

**Comment by Moyout** [comment]
I also encountered the same problem

**Comment by favazHF** [comment]
Same problem.

Devices: NE2213 | SM-A127F | SM-G988B | Pixel 6a | TECNO KG8, etc!
OSs: Android 9, 11, 12, 13.

Any update?

**Comment by HatsuneMikuV** [comment]
Same issue.

`MissingPluginException(No implementation found for method confirmPlatformPay on channel flutter.stripe/payments)`

**Comment by DavidEcclesPH** [comment]
same:

I/flutter ( 4807): ---------------- CAUGHT EXCEPTION! ----------------
I/flutter ( 4807): MissingPluginException(No implementation found for method confirmPlatformPay on channel flutter.stripe/payments)
I/flutter ( 4807): --------------------------------------------------------
I/flutter ( 4807): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308:7)
I/flutter ( 4807): <asynchronous suspension>
I/flutter ( 4807): #1      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:510:43)
I/flutter ( 4807): <asynchronous suspension>
I/flutter ( 4807): #2      MethodChannelStripe.platformPayConfirmPaymentIntent (package:stripe_platform_interface/src/method_channel_stripe.dart:456:20)
I/flutter ( 4807): <asynchronous suspension>
I/flutter ( 4807): #3      StripePaymentService.nativePay (package:pitchero_flutter/services/stripe_payment_service.dart:329:11)
I/flutter ( 4807): <asynchronous suspension>
I/flutter ( 4807): #4      StripePaymentCubit.beginPayment (package:pitchero_flutter/blocs/stripe/stripe_payment_cubit.dart:102:11)
I/flutter ( 4807): <asynchronous suspension>
I/flutter ( 4807): --------------------------------------------------------

**Comment by Rimantovas** [comment]
@Moyout Could you tell how you solved the issue? I see you left a thumbs up

**Comment by remonh87** [comment]
A custom button does not work because there is a lot of internal android code linked to it. I would use the https://github.com/flutter-stripe/flutter_stripe/blob/main/example/lib/screens/wallets/google_pay_screen.dart for now . I will ask the stripe android team for help to debug the issue on flutter.

Let's continue the discussion on https://github.com/flutter-stripe/flutter_stripe/issues/1393 which is the original problem

**Comment by elvinasn** [comment]
The custom button works with flutter_stripe version 9.3.0.

**Comment by Mik77o** [comment]
We encounter same issue (9.5.0)

**Comment by akrameev-rhino** [comment]
The issue is in GooglePayLauncherFragment.kt function presentGooglePaySheet. It tries to get integer value for amount (this.amount = googlePayParams.getInt("amount")) and fails as there is no amount in googlePayParams. Sync from React Native is not always correct (it has amount String value in googlePayParams as it is stated [here](https://stripe.dev/stripe-react-native/api-reference/modules/PaymentSheet.html))
