### ISSUE TITLE
White Screen being shown in payment page (ANDROID ONLY)

### ISSUE THREAD

**Issue by eugeneXJPIT** [flutter-stripe/flutter_stripe#1472]
**Describe the bug**
Mobile application developed using flutter, but payment process would only work for iOS devices but not Android devices.

**To Reproduce**
1.  Choosing the product
2. Clicking the 'Buy' button
3. Redirected to white screen.
**Note: Reproduce this steps using Android devices only.**

**Expected behavior**
![Expected_Behaviour](https://github.com/flutter-stripe/flutter_stripe/assets/141708298/19c11677-a74b-44ed-8bf6-a2f5fbf57388)

**Smartphone**
 - Device: Samsung Galaxy S20 FE 5G
 - OS: Android Version 13
 - Flutter version 2.19.4

**Additional context**
After enquiring with Stripe's developer live support(Through discord), i was redirected here to raise my enquiry about Stripe's incompatibility with Flutter's SDK.

Here is the error that I've encountered when testing the Stripe payment function using Android-based Devices:
![photo_2023-10-30 11 59 09](https://github.com/flutter-stripe/flutter_stripe/assets/141708298/6ab88c4e-0571-4d1d-af33-447b60090262)

**Comment by remonh87** [comment]
PAyment element is not a mobile component you need to use payment sheet for this.
