### ISSUE TITLE
How to add billing address to payment element flutter web

### ISSUE THREAD

**Issue by ankitmiyantechspian** [flutter-stripe/flutter_stripe#1477]
Hello, I am trying to make a USD payment from India and as paying USD from India we need to give the customer billing address in the mobile application flow i am able to do the same by passing BillingDetails, BillingDetailsCollectionConfiguration and IntentConfiguration but could you tell me how to achieve the same for web?

In the given code snipped I am adding this configuration and my payment sheet for the mobile app is coming up with card details form and billing address form eg address, state, city, country, and pin. Still, for the Web, I can't see a way to enable the billing address form with PaymentElement. The Payment Element is only showing me the card form and country dropdown i want to show the billing address form along with it in the Payment Element web like the payment sheet on mobile please help.

Please see the attachments for your reference.

![3](https://github.com/flutter-stripe/flutter_stripe/assets/137860496/731779fe-b52a-4815-9459-9d233768f6ec)
<img width="1063" alt="2" src="https://github.com/flutter-stripe/flutter_stripe/assets/137860496/aa2658f2-0e0b-48eb-b0fc-14760b1db151">
<img width="544" alt="1" src="https://github.com/flutter-stripe/flutter_stripe/assets/137860496/354cf5a5-02d5-409d-b021-920734208340">

**Comment by remonh87** [comment]
This is currently not possible in the stripe web element.  See: https://stripe.com/docs/payments/payment-element
