### ISSUE TITLE
Android Integration Issue

### ISSUE THREAD

**Issue by abumoallim** [flutter-stripe/flutter_stripe#148]
I upgraded my android minSdk to 21
Upgraded Kotlin: 1.5.0

Added FlutterFragmentActivity :
        import io.flutter.embedding.android.FlutterActivity;
        import io.flutter.embedding.android.FlutterFragmentActivity;
       
        public class MainActivity extends FlutterFragmentActivity {
        
        }

Did the Required Changes for Theme.AppCombat:
  <?xml version="1.0" encoding="utf-8"?>
  <resources>
      <style name="LaunchTheme" parent="@android:style/Theme.Black.NoTitleBar">
          
          <item name="android:windowBackground">@drawable/launch_background</item>
      </style>
  
      <style name="NormalTheme" parent="Theme.AppCompat.Light.NoActionBar">
          <item name="android:windowBackground">?android:colorBackground</item>
      </style>
  
  </resources>

But I am getting this error as soon as the app open:

  android.content.res.Resources$NotFoundException: Resource ID #0x0
  E/AndroidRuntime(21843): 	at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:404)
  E/AndroidRuntime(21843): 	at android.content.res.Resources.getDrawableForDensity(Resources.java:993)
  E/AndroidRuntime(21843): 	at android.content.res.Resources.getDrawable(Resources.java:933)
  E/AndroidRuntime(21843): 	at io.flutter.embedding.android.FlutterFragmentActivity.getSplashScreenFromManifest(FlutterFragmentActivity.java:327)
  E/AndroidRuntime(21843): 	at io.flutter.embedding.android.FlutterFragmentActivity.provideSplashScreen(FlutterFragmentActivity.java:303)
  E/AndroidRuntime(21843): 	at io.flutter.embedding.android.FlutterFragment.provideSplashScreen(FlutterFragment.java:934)
  E/AndroidRuntime(21843): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onCreateView(FlutterActivityAndFragmentDelegate.java:301)
  E/AndroidRuntime(21843): 	at io.flutter.embedding.android.FlutterFragment.onCreateView(FlutterFragment.java:621)
  E/AndroidRuntime(21843): 	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2963)
  E/AndroidRuntime(21843): 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518)
  E/AndroidRuntime(21843): 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
  E/AndroidRuntime(21843): 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
  E/AndroidRuntime(21843): 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
  E/AndroidRuntime(21843): 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
  E/AndroidRuntime(21843): 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3136)
  E/AndroidRuntime(21843): 	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3070)
  E/AndroidRuntime(21843): 	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
  E/AndroidRuntime(21843): 	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:501)
  E/AndroidRuntime(21843): 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1447)
  E/AndroidRuntime(21843): 	at android.app.Activity.performStart(Activity.java:8144)
  E/AndroidRuntime(21843): 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3922)
  E/AndroidRuntime(21843): 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:235)
  E/AndroidRuntime(21843): 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:215)
  E/AndroidRuntime(21843): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:187)
  E/AndroidRuntime(21843): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:105)
  E/AndroidRuntime(21843): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2462)
  E/AndroidRuntime(21843): 	at android.os.Handler.dispatchMessage(Handler.java:110)
  E/AndroidRuntime(21843): 	at android.os.Looper.loop(Looper.java:219)
  E/AndroidRuntime(21843): 	at android.app.ActivityThread.main(ActivityThread.java:8393)
  E/AndroidRuntime(21843): 	at java.lang.reflect.Method.invoke(Native Method)
  E/AndroidRuntime(21843): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
  E/AndroidRuntime(21843): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

I tried adding to my Manifest in my Activity Tag:
   
              <meta-data
                  android:name="io.flutter.embedding.android.NormalTheme"
                  android:resource="@style/NormalTheme"
                  />

**Comment by jaiswalshubham84** [comment]
@abumoallim 
Did u find any solution of it?

**Comment by bizready** [comment]
I have the same issue. Looks like the issue is closed. @abumoallim - is your problem resolved ? It would be great if you can share how it was resolved.

**Comment by abumoallim** [comment]
Try adding this in your app manifest

`<meta-data android:name="io.flutter.app.android.SplashScreenUntilFirstFrame
 android:value="true" />`

And in your MainActivity

`import
io.flutter.embedding.android.FlutterActivityLaunchConfigs;
import io.flutter.embedding.android.FlutterActivityLaunchConfigs.BackgroundMode;
import io.flutter.embedding.android.FlutterFragmentActivity;

public class MainActivity extends FlutterFragmentActivity {
   protected FlutterActivityLaunchConfigs.BackgroundMode getBackgroundMode() {
        return FlutterActivityLaunchConfigs.BackgroundMode.transparent;
}`
