### ISSUE TITLE
Disable edit/remove card option in the payment sheet

### ISSUE THREAD

**Issue by gauravwagh1** [flutter-stripe/flutter_stripe#1480]
Disable edit/remove card option in payment sheet.

How to keep always at least one saved card  ? 

**Additional context**
<img width="200" alt="Screenshot 2023-11-14 at 12 02 22" src="https://github.com/flutter-stripe/flutter_stripe/assets/82920987/e577ac10-c32c-4d42-9542-c957111826ed">

<img width="200" alt="Screenshot 2023-11-14 at 12 02 31" src="https://github.com/flutter-stripe/flutter_stripe/assets/82920987/13f38c67-2c91-442e-82ea-68b47940b636">

**Comment by jonasbark** [comment]
There is no way for us to add this functionality - you may want to ask in the original Stripe Android and Stripe iOS repository
