### ISSUE TITLE
App crashes (Android SDK 34) when selecting credit card payment method

### ISSUE THREAD

**Issue by Mik77o** [flutter-stripe/flutter_stripe#1486]
**Describe the bug**

When Android SDK is 34, flutter_stripe (9.5.0) and we want to display the credit card payment bottom modal, the application crashes. We see what someone already pointed out here: https://github.com/google/accompanist/issues/1713.

**To Reproduce**

```
...initPaymentSheet(
...
.presentPaymentSheet(); // CRASH HERE !!!
...

```
**Expected behavior**
The modal bottom sheet is visible and the app works stably.

**Smartphone / tablet**
 - Device: [e.g. Samsung Galaxy S22+]
 - OS: [Android 13 but it also occurred for other versions]
 - Package version: [9.5.0+1]
 - Flutter version [3.13.9]

**Comment by huan-at-agnt** [comment]
Add this to app/build.gradle for a temporary fix.

`    implementation "com.stripe:stripe-android:20.32.0"
    implementation "com.stripe:financial-connections:20.32.0"`

**Comment by remonh87** [comment]
I cannot reproduce this anymore in version 9.6.0 of our lib 

I really would advise against using an incompatible sdk with our library.
