### ISSUE TITLE
flutter_stripe package produces build error for iOS after upgrade to the newest Flutter 3.16

### ISSUE THREAD

**Issue by wenchenglai** [flutter-stripe/flutter_stripe#1496]
**Describe the bug**
My flutter project will get some generic error after upgrade to Flutter 3.16:

Error running pod install
Error launching application on iPhone 15 Pro Max.

I was able to reduce the noise and found out that flutter_stripe is causing the issue.  

**To Reproduce**
1. Create a new sample Flutter project from Flutter 3.16, build an iOS target, and the counter app should be working.
2. Add   "flutter_stripe: ^9.5.0+1" to pubspec.yaml
3. Try to compile again, you'll see the error.  The same thing happen if you build in xcode.

**Additional context**
I use Android Studio on MacBookPro to create the Flutter project.

**Comment by remonh87** [comment]
can you give the exact error that you receive because for me it works without any issues. Did you run pod update?

**Comment by wenchenglai** [comment]
The error is deployment version is too low.  So I modified my podfile, and the error goes away.  Thanks for the help!

**Comment by remonh87** [comment]
Fi

**Comment by GeovaneDaSilva** [comment]
change to stripe version 10.0.0
