### ISSUE TITLE
Support PayNow method

### ISSUE THREAD

**Issue by thphuc** [flutter-stripe/flutter_stripe#1498]
**Is your feature request related to a problem? (please describe)**
Currently, PayNow is not appearing on Android, while PayNow is not working on iOS (tap on PayNow -> crash the app)

**Describe the solution you'd like**
Can we add PayNow for Android? 
And fix the crash on iOS?

**Comment by remonh87** [comment]
Paynow is not officially supported by Stripe see: https://github.com/stripe/stripe-ios/issues/1996 . I will make it more explicit in the release notes.

**Comment by deepss1** [comment]
@remonh87 

PayNow is now officially supported by Stripe.

Currently, clicking on the PayNow option in the payment sheet crashes the app.
