### ISSUE TITLE
I'm Trying to implement Card saving for later use

### ISSUE THREAD

**Issue by Softmatech** [flutter-stripe/flutter_stripe#151]
I implement the card register like it is on the example enter (card number, expiry date, and CVC) and on saving, it shows this message on the log and looks at how the result appears at this video,
https://user-images.githubusercontent.com/29921959/122156864-d8c14500-ce37-11eb-841c-c338d288e511.mov

`static Future handlePayPress(BuildContext context,CardFieldInputDetails _card, String _email) async {
if (_card == null) {
return null;
}
setSettings();
try {
// 1. Create setup intent on backend
final clientSecret = await _createSetupIntentOnBackend(context,_email);
print("SECRET==================== $clientSecret");
// 3. Confirm setup intent
final setupIntentResult = await Stripe.instance.confirmSetupIntent(clientSecret, PaymentMethodParams.card(setupFutureUsage: PaymentIntentsFutureUsage.OffSession));
log('Setup Intent created $setupIntentResult');
ScaffoldMessenger.of(context).showSnackBar(
SnackBar(
content: Text(
'Success: Setup intent created. Intent status: $setupIntentResult',
),
),
);
return setupIntentResult;

} catch (error, s) {
  log('Error while saving payment', error: error, stackTrace: s);
  ScaffoldMessenger.of(context)
      .showSnackBar(SnackBar(content: Text('Error code: $error')));
}
}`

**Comment by jonasbark** [comment]
What's the full stack trace of the exception? Can you provide a minimal reproducible example?

**Comment by Softmatech** [comment]
![image](https://user-images.githubusercontent.com/29921959/122248174-e4435900-ce95-11eb-9b95-f18ab9c566a9.png)

Error while saving payment
      PlatformException(Failed, There was an unexpected error -- try again in a few seconds, null, null)
      #0      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:155:7)
      #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
      <asynchronous suspension>
      #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:358:43)
      <asynchronous suspension>
      #3      MethodChannelStripe.confirmSetupIntent (package:stripe_platform_interface/src/method_channel_stripe.dart:98:20)
      <asynchronous suspension>
      #4      Stripe.confirmSetupIntent (package:flutter_stripe/src/stripe.dart:228:27)
      <asynchronous suspension>
      #5      StripeHelper.handlePayPress (package:caritas/commons/stripe.dart:91:33)
      <asynchronous suspension>
      #6      getCardForm.<anonymous closure>.<anonymous closure> (package:caritas/commons/helper.dart:438:54)
      <asynchronous suspension>
