### ISSUE TITLE
Weird behavior of CardField

### ISSUE THREAD

**Issue by emmaxCreative** [flutter-stripe/flutter_stripe#152]
**Describe the bug**
I have a FAB on my Checkout page.
Whenever i scroll the CardField behind the Button some weird stuff happens and it starts flickering.
![image](https://user-images.githubusercontent.com/58904080/122228005-b707a280-ceb7-11eb-9184-059643bd41c2.png)

It happens when the keyboard is open and also when its hidden

The same flickering appears when I hit the pay-now button..But then the flickering is on the whole page. 
It dissapears once the payment is complete.

**To Reproduce**
1. Add a CardField somewhere 
2. Add a FloatingActionButton
3. Scroll the CardField behind the FAB
4. No exception is thown btw…

**Expected behavior**
Smooth UI without flickering.

**Smartphone / tablet**
 - Device: Pixel 3 Emulator
 - OS: Android API 30
 - Package version: 1.0.2
 - Flutter version: 2.2.2

**Comment by jonasbark** [comment]
Thanks for reporting - this is likely nothing we can fix ourselves and a bug in the Flutter native view integration.
Out of curiosity, can you try it with the latest master channel of Flutter?

**Comment by emmaxCreative** [comment]
its almost the same just without the rectangle in the background.
![image](https://user-images.githubusercontent.com/58904080/122267108-ce0bbc00-ceda-11eb-9b34-f43405fd5b1e.png)

**Comment by remonh87** [comment]
closed since there is not something we can do against that and should be fixed in flutter
