### ISSUE TITLE
No build on AGP above 8.0.2 (tested on 8.1.1 and 8.2.0) - because of minifying on reactnativestripesdk

### ISSUE THREAD

**Issue by Mortando** [flutter-stripe/flutter_stripe#1523]
Error with minifyReleaseWithR8 because R8 is deprecated and there is minifying on the reactnativestripesdk.

See info from newer Gradle:

```
 com.android.builder.errors.EvalIssueException: The option 'android.enableR8' is deprecated.
     It was removed in version 7.0 of the Android Gradle plugin.
     Please remove it from `gradle.properties`.
```

Additional this won't help because there is minifying:

```
minifyEnabled false
shrinkResources false
```

**Comment by remonh87** [comment]
which version of the sdk are you using because I am able to compile it.

**Comment by remonh87** [comment]
closed because not reproducable
