### ISSUE TITLE
`requires_capture` missing in `payment_intent.g.dart`

### ISSUE THREAD

**Issue by Samuele1no** [flutter-stripe/flutter_stripe#1529]
**Describe the bug**

Calling `confirmPayment` method of `flutter_stripe_web` throws the following error:
```
Invalid argument(s): 'requires_capture' is not one of the supported values: requires_payment_method, requires_confirmation, requires_action, processing, succeeded, canceled
```

**To Reproduce**

1. Entering number `4242-4242-4242-4242` into the cardfield with exipration date `04/24` and CVC `242`.
2. Tapping the confirm button``
3. Observe a failure with error message reported above

**Expected behavior**

Not throwing an error while parsing `require_capture` status.

**Smartphone / tablet**

 - Device: web
 - flutter_stripe version: 9.6.0
 - flutte_stripe_web version: 4.6.0
 - Flutter version 3.16.2
 
**Additional context**

I am using an express stripe account and the `paymentIntent` object is created with `require_capture=manual`.

Upon examination, the local file `stripe_js-3.2.0/lib/src/api/payment_intents/payment_intent.g.dart` dowloaded from pub.dev doesn't include the following line `PaymentIntentsStatus.requiresCapture: 'requires_capture'` found on GitHub source code.

To test the solution locally I've added the missing line `PaymentIntentsStatus.requiresCapture: 'requires_capture'` to the `stripe_js-3.2.0/lib/src/api/payment_intents/payment_intent.g.dart` local file. Once added, the `confirmPayment` method is able to handle the `requires_capture` status correctly.

@jonasbark @BakerSmithA 
I have the same error in the newer version 4.6.0.
In the change log of this version there is this fix but in my payment_intent_status.dart there is no capture enum.
Could you check it? Thanks

_Originally posted by @Samuele1no in https://github.com/flutter-stripe/flutter_stripe/issues/1421#issuecomment-1843119407_

**Comment by remonh87** [comment]
good catch we forgot to publish new version of stripe_js. It is fixed in version `3.3.0`.
