### ISSUE TITLE
Error building example android app bundle

### ISSUE THREAD

**Issue by VictorUvarov** [flutter-stripe/flutter_stripe#1546]
**Describe the bug**
Error building android app bundle. Missing classes

**To Reproduce**
1. Go to example app
2. Add stripe publishable key
3. run `flutter build appbundle`

**Expected behavior**
The appbundle should build with no missing class errors

**Smartphone / tablet**
 - Device: N/A
 - OS: Android 13
 - Package version: 9.6.0
 - Flutter version 3.16.3

**Additional context**
Before adding to `android/app/build.gradle` I get the following error
```
implementation 'com.stripe:stripe-android-issuing-push-provisioning:1.1.0'
```

```
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
ERROR: Missing classes detected while running R8. Please add the missing classes or apply additional keep rules that are generated in .../build/app/outputs/mapping/devRelease/missing_rules.txt.
ERROR: R8: Missing class com.stripe.android.pushProvisioning.PushProvisioningActivity$g (referenced from: void com.reactnativestripesdk.pushprovisioning.PushProvisioningProxy$createActivityEventListener$listener$1.onActivityResult(android.app.Activity, int, int, android.content.Intent))
Missing class com.stripe.android.pushProvisioning.PushProvisioningActivityStarter$Args (referenced from: void com.reactnativestripesdk.pushprovisioning.DefaultPushProvisioningProxy.beginPushProvisioning(android.app.Activity, java.lang.String, com.reactnativestripesdk.pushprovisioning.EphemeralKeyProvider))
Missing class com.stripe.android.pushProvisioning.PushProvisioningActivityStarter$Error (referenced from: void com.reactnativestripesdk.pushprovisioning.PushProvisioningProxy$createActivityEventListener$listener$1.onActivityResult(android.app.Activity, int, int, android.content.Intent))
Missing class com.stripe.android.pushProvisioning.PushProvisioningActivityStarter (referenced from: void com.reactnativestripesdk.pushprovisioning.DefaultPushProvisioningProxy.beginPushProvisioning(android.app.Activity, java.lang.String, com.reactnativestripesdk.pushprovisioning.EphemeralKeyProvider))
Missing class com.stripe.android.pushProvisioning.PushProvisioningEphemeralKeyProvider (referenced from: void com.reactnativestripesdk.pushprovisioning.DefaultPushProvisioningProxy.beginPushProvisioning(android.app.Activity, java.lang.String, com.reactnativestripesdk.pushprovisioning.EphemeralKeyProvider) and 1 other context)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:minifyDevReleaseWithR8'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.R8Task$R8Runnable
   > Compilation failed to complete

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 2m 29s
```

and then I get another error
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkReleaseDuplicateClasses'.
> Could not resolve all files for configuration ':app:releaseRuntimeClasspath'.
   > Could not find com.google.android.gms:play-services-tapandpay:17.1.2.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-tapandpay/17.1.2/play-services-tapandpay-17.1.2.pom
       - https://repo.maven.apache.org/maven2/com/google/android/gms/play-services-tapandpay/17.1.2/play-services-tapandpay-17.1.2.pom
       - https://storage.googleapis.com/download.flutter.io/com/google/android/gms/play-services-tapandpay/17.1.2/play-services-tapandpay-17.1.2.pom
     Required by:
         project :app > com.stripe:stripe-android-issuing-push-provisioning:1.1.0

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s

```

**Comment by AbdullahChauhan** [comment]
+1 
Just got the same error while creating the release build.

**Comment by VictorUvarov** [comment]
@remonh87 
Does this [comment](https://github.com/flutter-stripe/flutter_stripe/blob/ab3c0fd8bbabb52d4f6e9e8bf506de4663f32d8e/packages/stripe_android/android/build.gradle#L69) have anything to do with it

**Comment by AbdullahChauhan** [comment]
> @remonh87 Does this [comment](https://github.com/flutter-stripe/flutter_stripe/blob/ab3c0fd8bbabb52d4f6e9e8bf506de4663f32d8e/packages/stripe_android/android/build.gradle#L69) have anything to do with it

@VictorUvarov Can you confirm if the build successful after including this?

**Comment by VictorUvarov** [comment]
The build is not successful after adding the dependency as an implementation

**Comment by AbdullahChauhan** [comment]
Ok. Any other solution you found regarding this?

**Comment by computerfriendlog2** [comment]
I'm using
 flutter  3.17.0
ext.kotlin_version = '1.9.20'
  minSdkVersion 21
        targetSdkVersion 34
  #flutter_stripe: ^9.6.0


previously it was working fine. I don't know What happened to its not working since last week

getting below error.




FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':stripe_android:compileDebugJavaWithJavac'.
> error: invalid source release: 17

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 55s
Error: Gradle task assembleDebug failed with exit code 1

**Comment by AbdullahChauhan** [comment]
@computerfriendlog2 You need to migrate to JDK 17.

**Comment by MyBlueford16** [comment]
I'm running into the same issue as well
Any solution? @AbdullahChauhan @VictorUvarov

**Comment by nicholasalexanderchambers** [comment]
You can try adding
`
        minifyEnabled false
        shrinkResources false
`
to your release buildtype in gradle. Not smart for production builds since it'll disable obfuscation, but good enough for just the example app.

**Comment by MyBlueford16** [comment]
> You can try adding
> 
> ```
>         minifyEnabled false
>         shrinkResources false
> ```
> 
> to your release buildtype in gradle. Not smart for production builds since it'll disable obfuscation, but good enough for just the example app.

It does get the build to work, but like you said, not very ideal for a production build...

**Comment by mcmikashi** [comment]
Don't know if this good practice, but I add  this on android/app/build.gradle: 
```
`    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro' 
        }
    }`
```

and add android/app/proguard-rules.pro with this : 
```
`# Please add these rules to your existing keep rules in order to suppress warnings.
# This is generated automatically by the Android Gradle plugin.
-dontwarn com.google.android.gms.tapandpay.TapAndPayClient
`
```

**Comment by VictorUvarov** [comment]
@remonh87 Any ideas?

**Comment by remonh87** [comment]
add the following to your proguard files solves the issue. will document this in the troubleshoot settings of the app + readme

```txt
-dontwarn com.stripe.android.pushProvisioning.PushProvisioningActivity$g
-dontwarn com.stripe.android.pushProvisioning.PushProvisioningActivityStarter$Args
-dontwarn com.stripe.android.pushProvisioning.PushProvisioningActivityStarter$Error
-dontwarn com.stripe.android.pushProvisioning.PushProvisioningActivityStarter
-dontwarn com.stripe.android.pushProvisioning.PushProvisioningEphemeralKeyProvider
```

**Comment by remonh87** [comment]
See: https://github.com/flutter-stripe/flutter_stripe/commit/fb10f16462e77ffeb534f9b515a4872f415e829b for how to implement

**Comment by claudiooliveira** [comment]
I created the proguard-rules.pro file and it still has the same error

```proguard
# Please add these rules to your existing keep rules in order to suppress warnings.
# This is generated automatically by the Android Gradle plugin.
-dontwarn com.google.android.gms.tapandpay.TapAndPayClient
-dontwarn com.stripe.android.pushProvisioning.PushProvisioningActivity$g
-dontwarn com.stripe.android.pushProvisioning.PushProvisioningActivityStarter$Args
-dontwarn com.stripe.android.pushProvisioning.PushProvisioningActivityStarter$Error
-dontwarn com.stripe.android.pushProvisioning.PushProvisioningActivityStarter
-dontwarn com.stripe.android.pushProvisioning.PushProvisioningEphemeralKeyProvider
```

Error:

FAILURE: Build failed with an exception.

```
* What went wrong:
Execution failed for task ':app:checkQaReleaseAarMetadata'.
> Could not resolve all files for configuration ':app:qaReleaseRuntimeClasspath'.
   > Could not find com.google.android.gms:play-services-tapandpay:17.1.2.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-tapandpay/17.1.2/play-services-tapandpay-17.1.2.pom
       - https://repo.maven.apache.org/maven2/com/google/android/gms/play-services-tapandpay/17.1.2/play-services-tapandpay-17.1.2.pom
       - https://storage.googleapis.com/download.flutter.io/com/google/android/gms/play-services-tapandpay/17.1.2/play-services-tapandpay-17.1.2.pom
       - https://jitpack.io/com/google/android/gms/play-services-tapandpay/17.1.2/play-services-tapandpay-17.1.2.pom
     Required by:
         project :app > com.stripe:stripe-android-issuing-push-provisioning:1.1.0

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
```

**Comment by claudiooliveira** [comment]
@remonh87 should using the proguard-rules file solve this?

My build.gradle:

 ```
buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro' 
        }
    }
```

**Comment by thivankasarathchandra** [comment]
FYI if anyone stuck at this, change the  JDK version from, 

`   compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }`
    
to 
    
` compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }`
    
    
also add the proguard rules form the readme form the package.

**Comment by black10manda** [comment]
> I created the proguard-rules.pro file and it still has the same error
> 
> ```
> # Please add these rules to your existing keep rules in order to suppress warnings.
> # This is generated automatically by the Android Gradle plugin.
> -dontwarn com.google.android.gms.tapandpay.TapAndPayClient
> -dontwarn com.stripe.android.pushProvisioning.PushProvisioningActivity$g
> -dontwarn com.stripe.android.pushProvisioning.PushProvisioningActivityStarter$Args
> -dontwarn com.stripe.android.pushProvisioning.PushProvisioningActivityStarter$Error
> -dontwarn com.stripe.android.pushProvisioning.PushProvisioningActivityStarter
> -dontwarn com.stripe.android.pushProvisioning.PushProvisioningEphemeralKeyProvider
> ```
> 
> Error:
> 
> FAILURE: Build failed with an exception.
> 
> ```
> * What went wrong:
> Execution failed for task ':app:checkQaReleaseAarMetadata'.
> > Could not resolve all files for configuration ':app:qaReleaseRuntimeClasspath'.
>    > Could not find com.google.android.gms:play-services-tapandpay:17.1.2.
>      Searched in the following locations:
>        - https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-tapandpay/17.1.2/play-services-tapandpay-17.1.2.pom
>        - https://repo.maven.apache.org/maven2/com/google/android/gms/play-services-tapandpay/17.1.2/play-services-tapandpay-17.1.2.pom
>        - https://storage.googleapis.com/download.flutter.io/com/google/android/gms/play-services-tapandpay/17.1.2/play-services-tapandpay-17.1.2.pom
>        - https://jitpack.io/com/google/android/gms/play-services-tapandpay/17.1.2/play-services-tapandpay-17.1.2.pom
>      Required by:
>          project :app > com.stripe:stripe-android-issuing-push-provisioning:1.1.0
> 
> * Try:
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> ```

use 
buildTypes {
        release {
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro' 
        }
    }
