### ISSUE TITLE
Screen goes black on onResume PaymentSheet

### ISSUE THREAD

**Issue by abumoallim** [flutter-stripe/flutter_stripe#156]
I have successfully implemented PaymentSheet with android & IOS.
In android Just a little issue I am facing when the PaymentSheet is open and the user switches with apps or if the user visits the app from the background the screen goes black and if I press back the screen looks fine.
![WhatsApp Image 2021-06-19 at 4 02 33 PM](https://user-images.githubusercontent.com/14852095/122641671-d7359c80-d117-11eb-9ebe-c00ecb9cf65e.jpeg)

**Comment by jamesblasco** [comment]
Please could you share more about the devices you are testing? Is it the simulator?

**Comment by abumoallim** [comment]
I had to add this code to make it working

  public class MainActivity extends FlutterFragmentActivity {
  
      protected FlutterActivityLaunchConfigs.BackgroundMode getBackgroundMode() {
          return FlutterActivityLaunchConfigs.BackgroundMode.transparent;
      }
  
  }

**Comment by jonasbark** [comment]
Thanks for providing a fix!
