### ISSUE TITLE
Apple pay sheet closes when pressing it to pay.  

### ISSUE THREAD

**Issue by developermvuk** [flutter-stripe/flutter_stripe#1575]
The apple pay logo shows however when pressign to pay sheet closes and doesn't show cards on device.

since nobody helps here i'm willing to pay for assistance. We've configured this plug in however on ios we are facing an issue where when we click the apple pay button sheet just closes without cards showing in order to pay.

Please anyone help?

**Comment by remonh87** [comment]
please stop spamming our repo  I think the discussion forum is a good one. Keep in mind that it is holiday season and it takes a bit of time to answer everything
