### ISSUE TITLE
pkey remains unchanged although I change it, uses old pkey

### ISSUE THREAD

**Issue by ehcpdeveloper** [flutter-stripe/flutter_stripe#1578]
**Describe the bug**
pkey remains unchanged although I change it, uses old pkey

**To Reproduce**
1. Initialize flutter_stripe code and use a live key.
2. During App usage, change Stripe.publishableKey, like pk_test... (to enable testing etc.)
3. Try to complete payment in usual way: it raises exception: "Your card was declined. Your request was in live mode, but used a known test card.", although latest value of Stripe.publishableKey is a pk_test... 
I am checking submitted data using network tab of developer tools, it is sending pk_live_...

I need to change pkey upon some business logic needs. is there any special way to change pkey?
I cannot provide whole codes, as it is unnecessarily complex for a bugreport, but summary as above.

Sample codes:
```
    Stripe.publishableKey = "pk_live_....";

// After some screens/business logic:
    Stripe.publishableKey = "pk_test_....";
    Stripe.stripeAccountId = "...";
    Stripe.merchantIdentifier = 'merchant.net.xxx.yyy';
    Stripe.urlScheme = 'flutterstripe';
    await Stripe.instance.applySettings();

// ....

// Error thrown here; at this point, althaugh pkey (Stripe.publishableKey) is pk_test, it is sending pk_live...
final paymentMethod = await Stripe.instance.createPaymentMethod(params: pm_params);


```

**Expected behavior**
the transaction should be completed with pk_test_

**Versions**
 - Device: Web/Chrome (after uploading to a webserver)
 - Package version: latest, e.g: 10.0.0
 - Flutter version: 
 - $ flutter --version
Flutter 3.16.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 78666c8dc5 (9 days ago) • 2023-12-19 16:14:14 -0800
Engine • revision 3f3e560236
Tools • Dart 3.2.3 • DevTools 2.28.4

**Additional context**
Same codes work without changing pkey. Backend etc. working.

**Comment by remonh87** [comment]
I think the error is due to the fact that you are using a test card with a live key. 

It looks like that the paymentintent is created with a server key that is in testmode and you try to confirm it with a live key. Dynamically changing keys only work if the server also changes the keys correctly. If I were you I would check the stripe dashboard and see if everything is created correctly

**Comment by remonh87** [comment]
closed for now feel free to reopen if the issue still happens
