### ISSUE TITLE
iOS StripeException for confirmPayment() localizedMessage: Card details not complete

### ISSUE THREAD

**Issue by KunalChhatbarZignuts** [flutter-stripe/flutter_stripe#1581]
confirmPayment() method generate exception on that i am passing client secret that is created by backend and when i try to make payment **with old card** .

`StripeException(error: LocalizedErrorMessage(code: FailureCode.Failed, localizedMessage: Card details not complete, message: Card details not complete, stripeErrorCode: null, declineCode: null, type: null))`

when i add new card at that time i am not getting this Exception but if card is already added and after some time i am try to do payment on iOS then this exception is generated 

note : This Exception i am getting on iOS only in android it is working fine.

**To Reproduce**
1. create card with CardFormField 
2. generate token to save card data using Stripe.instance.createToken()
3. make payment with card id that is generated from backend 
4. generate clientSecret through card id and other data 
5. through that clientSecret make payment and conform with 
```
  final params = stripe.PaymentMethodParams.card(
                paymentMethodData: stripe.PaymentMethodData(
                  billingDetails: billingDetails,
                ),
                // mandateData:metadata
              );
confirmPayment(
  paymentIntentClientSecret: _clientSecret,
  data: params,
  )
 
```

i also changes version check then also i am getting same error 

**versions**
 - Package version: **flutter_stripe: ^9.3.0**
 - Flutter version: **Flutter 3.17.0-15.0.pre.20**
 - dart version: **Dart 3.3.0 (build 3.3.0-152.0.dev)**

**Comment by remonh87** [comment]
You always need the cardfield to generate a stripe token.  See: https://github.com/flutter-stripe/flutter_stripe/blob/main/example/lib/screens/others/legacy_token_card_screen.dart

**Comment by navin-zignuts** [comment]
Hello @remonh87 I faced the same issue and I tried what you suggest. still I am facing the same issue. Can you please help me into this asap.

As we did it the same in our previous app, before 1 year ago and it's still working but we did implementation in our new app but in iOS we have still the problem 

Thank you for you cooperation and support

**Comment by remonh87** [comment]
@navin-zignuts i would recommend checking our example app since this has working examples of paying with both. Else we need a reproducible scenario to look further into it

**Comment by KunalChhatbarZignuts** [comment]
blow is code snippet for token creation and make payment and conform payment 

this is card token creation 

```
onSaveCard: () async {
    if (cardFormEditController.details.complete == true) {
      _isCardAdded = false;
      final stripe.TokenData tokenData =
          await stripe.Stripe.instance.createToken(
        stripe.CreateTokenParams.card(
          params: stripe.CardTokenParams(
            type: stripe.TokenType.Card,
            // name: cardNameController.text,
          ),
        ),
      );
      if (_customerId.isNotEmpty && tokenData.id.isNotEmpty) {
        _addCardApiCall(_customerId, tokenData.id);
      }
    } else {
      showToast(msg: "Please enter the mandatory information");
    }
    //api call for card list data 
    getPaymentCardListData(_customerId);
},

```
hear, CardFormField use for card widget 

```
//card field 
Container(
padding: EdgeInsets.zero,
child:
    stripe.CardFormField(
  controller: widget.stripController,
  style: stripe.CardFormStyle(
    borderColor: Colors.black,
    cursorColor: Colors.black,
    placeholderColor: color.black,
    textColor: Colors.black,
    textErrorColor: Colors.red,
    borderRadius: 0,
    borderWidth: 0,
  ),
  enablePostalCode: true,
  onCardChanged: (cardFieldInputDetails) {
    setState(() {
      cardFieldInputDetails!.complete;
      if (cardFieldInputDetails.complete) {}
    });
  },
),
),
```
on this way we are creating token and _addCardApiCall(_customerId, tokenData.id); is a method for saving card data in our backend after that we are calling api for list data and get card detailes with card id 
we are saving multiple card on our backend and through card id we are calling an api for generating payment client Secret(client Secret creation is from out backend)
```
Future<void> _postPaymentPlansProduct() async {
try {
  //payment intent create with strip
  showLoadingDialog(context, true);
  stripe.BillingDetails billingDetails =
      const stripe.BillingDetails(
    email: 'test@gmail.com',
    name: "",
    phone: "",
    address: stripe.Address(
      city: '',
      country: 'DE',
      line1: '',
      line2: '',
      postalCode: '',
      state: '',
    ),
  );
  final params = stripe.PaymentMethodParams.card(
    paymentMethodData: stripe.PaymentMethodData(
      billingDetails: billingDetails,
    ),
  );
  stripe.PaymentIntent stripeData;
  if (Platform.isIOS) {
    stripeData = await stripe.Stripe.instance.confirmPayment(
      paymentIntentClientSecret: _clientSecret,
      data: params,
    );
  } else {
    stripeData = await stripe.Stripe.instance.confirmPayment(
      paymentIntentClientSecret: _clientSecret,
    );
  }
  print("stripeData $stripeData");
  showLoadingDialog(context, false);
  if (stripeData.status.name.toLowerCase() == 'succeeded') {
    _invoiceId = null;
    context.go(AppRoutesPath.paymentSuccessScreen);
  } else {
    context.push(AppRoutesPath.paymentFailedScreen);
  }
} catch (e) {
  showLoadingDialog(context, false);
  context.push(AppRoutesPath.paymentFailedScreen);
  print('error => ${e}');
}
}
```

we are using confirmPayment() to conform payment and on our backend we are using web-hook to update payment status on stripe   

on confirmPayment() method we are getting this error 
`StripeException(error: LocalizedErrorMessage(code: FailureCode.Failed, localizedMessage: Card details not complete, message: Card details not complete, stripeErrorCode: null, declineCode: null, type: null))`

**Comment by navin-zignuts** [comment]
Hello @remonh87 , i hope you are doing well. can i have any updates on above ?
