### ISSUE TITLE
Stripe.js HTTPS Error on flutter web

### ISSUE THREAD

**Issue by bookdoorsupport** [flutter-stripe/flutter_stripe#1587]
**Describe the bug**
I have implemented the flutter_stripe package with flutter and it works fine in mobile but when tested on web I always get this error :

`You may test your Stripe.js integration over HTTP. However, live Stripe.js integrations must use HTTPS.`

Also I have the flutter_stripe_web package added to pubspec.yaml, My website already has https and the payment node.js code is hosted on firebase functions, so am I doing something wrong or is this a bug?

**To Reproduce**
1. add the flutter_stripe_web package and flutter_stripe.
2. implement PaymentSheet
3. works in Android and IOS but doesnt work on web :/

**Expected behavior**
I expected the payment to go through normally as it does in android but it didn't

**Smartphone / tablet**
 - Device: tested on multiple devices still doesn't work
 - Chrome
 - Package version: 10.0.0
 - Flutter version: 3.16.1

**Comment by Gopinathp** [comment]
I am getting the same error when trying to make payments work on the web. It works on Android and iOS perfectly.

**Comment by jonasbark** [comment]
PaymentSheets are not supported on Web
