### ISSUE TITLE
App crash when removeing number from credit card number field

### ISSUE THREAD

**Issue by bertrandgelinas** [flutter-stripe/flutter_stripe#1593]
**Describe the bug**
I'm using the example payment sheet code in this repo. I send a request in order to create a payment sheet and get the response from server. It works fine at this point.

When i tap "pay" and enter my credit card (test card), it crashes once i remove number in credit card field (doing backspace). I was on a real device.

**To Reproduce**
1. Entering number 4242-4242-4242 into the cardfield.
2. remove last number (backspace in keypad)
3. Observe a failure with exception 

**Expected behavior**
Not to crashh

**Smartphone / tablet**
 - Device: Samsung S9
 - OS: Android 10
 - Package version: 9.6.0
 - Flutter version : 3.16.4

Stacktrace : 
`D/AndroidRuntime(15186): Shutting down VM
E/AndroidRuntime(15186): FATAL EXCEPTION: main
E/AndroidRuntime(15186): Process: com.greenplayapp, PID: 15186
E/AndroidRuntime(15186): java.lang.NoSuchMethodError: No virtual method getEmojiStart(Ljava/lang/CharSequence;I)I in class Landroidx/emoji2/text/EmojiCompat; or its super classes (declaration of 'androidx.emoji2.text.EmojiCompat' appears in /data/app/com.greenplayapp-7pi0Lp9R4glnUCe34yAg4Q==/base.apk!classes6.dex)
E/AndroidRuntime(15186):        at androidx.compose.foundation.text.StringHelpers_androidKt.findPrecedingBreak(StringHelpers.android.kt:24)
E/AndroidRuntime(15186):        at androidx.compose.foundation.text.selection.BaseTextPreparedSelection.getPrecedingCharacterIndex(TextPreparedSelection.kt:150)
E/AndroidRuntime(15186):        at androidx.compose.foundation.text.TextFieldKeyInput$process$2$3.invoke(TextFieldKeyInput.kt:131)
E/AndroidRuntime(15186):        at androidx.compose.foundation.text.TextFieldKeyInput$process$2$3.invoke(TextFieldKeyInput.kt:129)
E/AndroidRuntime(15186):        at androidx.compose.foundation.text.selection.TextFieldPreparedSelection.deleteIfSelectedOr(TextPreparedSelection.kt:397)
E/AndroidRuntime(15186):        at androidx.compose.foundation.text.TextFieldKeyInput$process$2.invoke(TextFieldKeyInput.kt:129)
E/AndroidRuntime(15186):        at androidx.compose.foundation.text.TextFieldKeyInput$process$2.invoke(TextFieldKeyInput.kt:106)
E/AndroidRuntime(15186):        at androidx.compose.foundation.text.TextFieldKeyInput.commandExecutionContext(TextFieldKeyInput.kt:226)
E/AndroidRuntime(15186):        at androidx.compose.foundation.text.TextFieldKeyInput.process-ZmokQxo(TextFieldKeyInput.kt:106)
E/AndroidRuntime(15186):        at androidx.compose.foundation.text.TextFieldKeyInputKt$textFieldKeyInput$2$1.invoke-ZmokQxo(TextFieldKeyInput.kt:261)
E/AndroidRuntime(15186):        at androidx.compose.foundation.text.TextFieldKeyInputKt$textFieldKeyInput$2$1.invoke(TextFieldKeyInput.kt:261)
E/AndroidRuntime(15186):        at androidx.compose.ui.input.key.KeyInputNode.onKeyEvent-ZmokQxo(KeyInputModifier.kt:80)
E/AndroidRuntime(15186):        at androidx.compose.ui.focus.FocusOwnerImpl.dispatchKeyEvent-ZmokQxo(FocusOwnerImpl.kt:193)
E/AndroidRuntime(15186):        at androidx.compose.ui.platform.AndroidComposeView.dispatchKeyEvent(AndroidComposeView.android.kt:647)
E/AndroidRuntime(15186):        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1949)
E/AndroidRuntime(15186):        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1949)
E/AndroidRuntime(15186):        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1949)
E/AndroidRuntime(15186):        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1949)
E/AndroidRuntime(15186):        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1949)
E/AndroidRuntime(15186):        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1949)
E/AndroidRuntime(15186):        at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:758)
E/AndroidRuntime(15186):        at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1942)
E/AndroidRuntime(15186):        at android.app.Activity.dispatchKeyEvent(Activity.java:3998)
E/AndroidRuntime(15186):        at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:126)
E/AndroidRuntime(15186):        at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:86)
E/AndroidRuntime(15186):        at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:144)
E/AndroidRuntime(15186):        at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:604)
E/AndroidRuntime(15186):        at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:60)
E/AndroidRuntime(15186):        at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3413)
E/AndroidRuntime(15186):        at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:624)
E/AndroidRuntime(15186):        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:6489)
E/AndroidRuntime(15186):        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6353)
E/AndroidRuntime(15186):        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5793)
E/AndroidRuntime(15186):        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5846)
E/AndroidRuntime(15186):        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5812)
E/AndroidRuntime(15186):        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5968)
E/AndroidRuntime(15186):        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5820)
E/AndroidRuntime(15186):        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6025)
E/AndroidRuntime(15186):        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5793)
E/AndroidRuntime(15186):        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5846)
E/AndroidRuntime(15186):        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5812)
E/AndroidRuntime(15186):        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5820)
E/AndroidRuntime(15186):        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5793)
E/AndroidRuntime(15186):        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9029)
E/AndroidRuntime(15186):        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8886)
E/AndroidRuntime(15186):        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8839)
E/AndroidRuntime(15186):        at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:5421)
E/AndroidRuntime(15186):        at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(15186):        at android.os.Looper.loop(Looper.java:237)
E/AndroidRuntime(15186):        at android.app.ActivityThread.main(ActivityThread.java:8167)
E/AndroidRuntime(15186):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(15186):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
E/AndroidRuntime(15186):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)`

**Comment by AlexGithubAlen** [comment]
Same issuse. Also, If I type numbers to credit card field very fast, then application crashes too.

**Comment by jonasbark** [comment]
This has been fixed with flutter_stripe: ^10.0.0.

**Comment by developermvuk** [comment]
Having same issue using latest flutter stripe package 

> This has been fixed with flutter_stripe: ^10.0.0.
