### ISSUE TITLE
Flutter Stripe Web StripeConfigException

### ISSUE THREAD

**Issue by Thibault4** [flutter-stripe/flutter_stripe#1595]
**Describe the bug**
Exception throw begin web app

Error: Instance of 'StripeConfigException'
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:3  throw_
packages/flutter_stripe/src/stripe.dart 31:7                                 get publishableKey
packages/flutter_stripe/src/stripe.dart 105:25                               applySettings
packages/flutter_stripe/src/stripe.dart 647:25                               [_awaitForSettings]
packages/flutter_stripe/src/stripe.dart 680:7                                markNeedsSettings
packages/flutter_stripe/src/stripe.dart 98:5                                 set merchantIdentifier
packages/decibell/main.dart 28:10                                            main
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50           <fn>
dart-sdk/lib/async/zone.dart 1661:54                                         runUnary
dart-sdk/lib/async/future_impl.dart 162:18                                   handleValue
dart-sdk/lib/async/future_impl.dart 846:44                                   handleValueCallback
dart-sdk/lib/async/future_impl.dart 875:13                                   _propagateToListeners
dart-sdk/lib/async/future_impl.dart 647:5                                    [_completeWithValue]
dart-sdk/lib/async/future.dart 529:22                                        <fn>
dart-sdk/lib/async/zone.dart 1661:54                                         runUnary
dart-sdk/lib/async/future_impl.dart 162:18                                   handleValue
dart-sdk/lib/async/future_impl.dart 846:44                                   handleValueCallback
dart-sdk/lib/async/future_impl.dart 875:13                                   _propagateToListeners
dart-sdk/lib/async/future_impl.dart 647:5                                    [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 721:7                                    callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                             _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                              _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:7           <fn>

**To Reproduce**
1. Setup Stripe.publishableKey.
2. Run flutter web app

**Expected behavior**
Setup  Stripe.merchantIdentifier = 'merchant.decibell.org'; and Exception appears

**Smartphone / tablet**
 - Device: X
 - OS: Chrome Web
 - Package version: Flutter Stripe Web 5.0.0
 - Flutter version Flutter 3.16.5 • channel stable

**Comment by remonh87** [comment]
you probably forgot to call `  await Stripe.instance.applySettings();`

This is our initcode and this works on Stripe web on the example app.
```dart
  WidgetsFlutterBinding.ensureInitialized();
  Stripe.publishableKey = stripePublishableKey;
  Stripe.merchantIdentifier = 'merchant.flutter.stripe.test';
  Stripe.urlScheme = 'flutterstripe';
  await Stripe.instance.applySettings();
```
 If the issue still persist can you reopen it and provide me a proper reproduction scenario?
