### ISSUE TITLE
CardField crash on Flutter(android)

### ISSUE THREAD

**Issue by punitsamcom84** [flutter-stripe/flutter_stripe#1597]
i used flutter_stripe: ^10.0.0

this is code:

class paymentCard extends StatefulWidget{
  @override
  State<paymentCard> createState() => _paymentCardState();
}

class _paymentCardState extends State<paymentCard> {

  @override
  Widget build(BuildContext context) {
    return CardField(
      onCardChanged: (card) {

      },
    );
  }
}

this is error:
E/flutter ( 7153): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:651:7)
E/flutter ( 7153): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:322:18)
E/flutter ( 7153): <asynchronous suspension>
E/flutter ( 7153): #2      ExpensiveAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1081:5)
E/flutter ( 7153): <asynchronous suspension>
E/flutter ( 7153): #3      AndroidViewController.create (package:flutter/src/services/platform_views.dart:804:5)
E/flutter ( 7153): <asynchronous suspension>

**Comment by remonh87** [comment]
did you add `  WidgetsFlutterBinding.ensureInitialized();` to the main of your application? also give me a bit more context so I can look further into it:
- output of `flutter doctor`
- Android version and device

I do not think there is much I can do about it as it looks like an issue in flutter itself

**Comment by punitsamcom84** [comment]
yes i already add this  ### WidgetsFlutterBinding.ensureInitialized();

main.dart :

import 'package:flutter/material.dart';
import 'package:flutter_stripe_demo/payment_card.dart';

void main() async{
  WidgetsFlutterBinding.ensureInitialized();
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home:  MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget{
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body:paymentCard()
    );
  }

}



payment_card.dart


import 'package:flutter/cupertino.dart';
import 'package:flutter_stripe/flutter_stripe.dart';

class paymentCard extends StatefulWidget{
  @override
  State<paymentCard> createState() => _paymentCardState();
}

class _paymentCardState extends State<paymentCard> {

  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return CardField(
      controller: CardEditController(),
      onCardChanged: (card) {

      },
    );
  }
}


![flutte doctor screen](https://github.com/flutter-stripe/flutter_stripe/assets/63594195/b619faf1-a07d-4697-84ef-ff066d6e4c95)

**Comment by Anonymousgaurav** [comment]
@punitsamcom84 try on real device..

**Comment by Anonymousgaurav** [comment]
@remonh87 my issue fixed!! it was due to wrong navigation

**Comment by remonh87** [comment]
@punitsamcom84  make sure to also add the stripe intialisation as I cannot see this in your code sample. See https://github.com/flutter-stripe/flutter_stripe/blob/f6f997bf5cde2010abfba37708d6fa498cd0c934/example/lib/main.dart#L9

**Comment by SushanDristi** [comment]
> @remonh87 my issue fixed!! it was due to wrong navigation

I am also having issue when i navigate to next screen from card screen. Can you explain me how you fix it?

**Comment by mian-asif** [comment]
The error indicates a crash in your Flutter application on Android, specifically related to handling text input.
This error suggests that there is a method call to getEmojiStart on EmojiCompat that does not exist.
dependencies {
 

    implementation "androidx.emoji2:emoji2:1.4.0"
    implementation "androidx.emoji2:emoji2-views:1.4.0"
    implementation "androidx.emoji2:emoji2-views-helper:1.4.0"
}
Add these lines in the App Level Build.Gradle

**Comment by ripal-crescentek** [comment]
Try to add 

<provider
    android:name="androidx.startup.InitializationProvider"
    android:authorities="${applicationId}.androidx-startup"
    android:exported="false"
    tools:node="merge">
    <meta-data android:name="androidx.emoji2.text.EmojiCompatInitializer"
        tools:node="remove" />
</provider>

inside android folder in manifest.xml file under <application> without adding below dependencies in app level Build.Gradle

implementation "androidx.emoji2:emoji2:1.4.0"
implementation "androidx.emoji2:emoji2-views:1.4.0"
implementation "androidx.emoji2:emoji2-views-helper:1.4.0"

**Comment by Manali-Flynaut** [comment]
> @remonh87 my issue fixed!! it was due to wrong navigation



> @remonh87 my issue fixed!! it was due to wrong navigation

@Anonymousgaurav how did you solved this error?
