### ISSUE TITLE
flutter_stripe fully supports the Pay plugin.integrate Stripe as a payment processor for Apple Pay:

### ISSUE THREAD

**Issue by umarm8627** [flutter-stripe/flutter_stripe#1604]
This function is working fine with GPay but i want to use the same function for onApplePayResult(paymentResult) with same functionality that are using in  this function. I want to payment with stripe 

Future<void> onGooglePayResult(paymentResult) async {
    final response = await fetchPaymentIntentClientSecret();
    final clientSecret = response['clientSecret'];
    final token = paymentResult['paymentMethodData']['tokenizationData']['token'];
    final tokenJson = Map.castFrom(json.decode(token));

    final params = PaymentMethodParams.cardFromToken(
      token: tokenJson['id'],
    );
    // Confirm Google pay payment method
    await Stripe.instance.confirmPayment(
      clientSecret,
      params,
    );
}

**Comment by remonh87** [comment]
yes see: https://github.com/flutter-stripe/flutter_stripe/blob/main/example/lib/screens/wallets/apple_pay_screen_plugin.dart
