### ISSUE TITLE
IOS App crashes in flutter_stripe:10.0.0, when install from test flight, works well in debug and release mode.

### ISSUE THREAD

**Issue by MuhammadMusa22** [flutter-stripe/flutter_stripe#1605]
**Describe the bug**
I was using flutter_stripe: ^9.4.0,  stripe payment sheet was working smoothly. Now as i have upgraded my flutter_stripe to 10.0.0, payment sheet crashes only when i install app from test flight. When i run app debug or release mode, it works well without crashing.

I have just removed this issue when i remove returnUrl from initPaymentSheet, then there is no crash, but same returnUrl worked before. I am using this for Klarna payment gateway inside flutter stripe payment sheet. I need to add this for this payment support. 

Even i have downgraded my flutter stripe to my old which was 9.4.0 but it is still giving me issue.

**To Reproduce**
1. Add returnUrl to initPaymentSheet
2. show payment sheet
3. Observe a crash.

**Smartphone / tablet**
 - Device: iPhone XR
 - OS: iOS 16
 - Package version: 10.0.0
 - Flutter version: 3.16.8 

**Additional context**
Info.plist
```
<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLSchemes</key>
			<array>
			    <string>flutterstripe</string>
			</array>
		</dict>

	</array>
```

Payment sheet code

```
await Stripe.instance.initPaymentSheet(
      paymentSheetParameters: SetupPaymentSheetParameters(
        customerId: rentingPropertyStripeCredentialsModel.data.customerId,
        customerEphemeralKeySecret: rentingPropertyStripeCredentialsModel.data.ephemeralKey.secret,
        paymentIntentClientSecret: rentingPropertyStripeCredentialsModel.data.clientSecret,
        merchantDisplayName: 'ABC',
        style: ThemeMode.light,
        appearance: const PaymentSheetAppearance(
          colors: PaymentSheetAppearanceColors(primary: AppColors.primaryColor),
        ),
        googlePay: googlePay,
        applePay: applePay,
        allowsDelayedPaymentMethods: true,
       ///this is where issue arises.
        returnURL: 'flutterstripe://com.shipohoi.shipOHoiApp',
      ),
    );
```

**Comment by remonh87** [comment]
can you provide me a crash log because for me it works fine.  I need the iOS crash logs from xcode.

**Comment by MuhammadMusa22** [comment]
@remonh87, In release mode and in debug mode, it is not causing any issue nor adding anything to the terminal regarding some errors. It only happen only when we install this from test flight app when we archive build.

If it is not happening with you, can you please provide how you initated payment sheet with returnUrl, and also how you managed all this in native iOS files of info.plist, let me have a look into this because i have added all this correctly, but still crashing issue.

I am adding returnURL for klarna payment gateway in payment sheet, which won't be showing if we remove returnURL from initPaymentsheet.

**Comment by remonh87** [comment]
I would recommend looking [here](https://github.com/flutter-stripe/flutter_stripe/blob/main/example/lib/screens/payment_sheet/payment_sheet_screen.dart) for the dart implementation. See [this](https://github.com/flutter-stripe/flutter_stripe/blob/f6f997bf5cde2010abfba37708d6fa498cd0c934/example/ios/Runner/Info.plist#L24) for ios.  I would recommend using some crashlogger (like crashlytics )to provide us the error. Unfortunately I will close it for now but feel free to reopen it when you have a decent stacktrace.
