### ISSUE TITLE
Tap to pay enabled

### ISSUE THREAD

**Issue by mrgithub** [flutter-stripe/flutter_stripe#1606]
Tap to pay seems to be on one the changelogs but I can't get it to work. Is this a stub feature? Forgive me for being stupid but does anyone know how to get it get tap to pay working with a basic example?

**Comment by remonh87** [comment]
released in v10.1.0

**Comment by parthjMandalia** [comment]
can you please give me any documentation for implementing Tap-to pay or example for the same.
Thanks

**Comment by karthikjn01** [comment]
Also looking for any documentation on how to implement it!

**Comment by myFLO-Developer1** [comment]
Same here. Looking for a documentation on how to implement the tap to pay feature.

**Comment by bluegene37** [comment]
+1

**Comment by yashpatel2202** [comment]
+1

**Comment by NijatTagizada** [comment]
+1
