### ISSUE TITLE
The binary version of its metadata is 1.9.0

### ISSUE THREAD

**Issue by miguelangelflores1993** [flutter-stripe/flutter_stripe#1628]
**Describe the bug**
BUG compiler android

**To Reproduce**
 flutter build apk --flavor=development -t lib/main_development.dart

![Screenshot 2024-02-02 143152](https://github.com/flutter-stripe/flutter_stripe/assets/116732288/1f3b14bc-25cd-4339-8be9-c678ad4edbbb)

`C:/Users/PC Gamer/.gradle/caches/transforms-3/166c7f10c316cb31420f884328236e16/transformed/jetified-kotlin-stdlib-common-1.9.0.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.`

**Expected behavior**

**Comment by remonh87** [comment]
Did you update your Google development sdk? I also need a reproducible scenario since the example app compiles without problems

**Comment by romithgiri** [comment]
To fix this issue, apply the declarative `plugins {}` block.

Projects created with Flutter versions before 3.16 require manual migration. For details, refer to the [documentation](https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply)

After migration, update the Kotlin version within the `settings.gradle` file inside the `plugins {}` block.

```
plugins {
  id 'dev.flutter.flutter-plugin-loader' version '1.0.0'
  id 'com.android.application' version '7.3.0' apply false
  id 'org.jetbrains.kotlin.android' version '1.9.22' apply false
}
```
Screenshot for reference:
<img width="628" alt="image" src="https://github.com/flutter-stripe/flutter_stripe/assets/104574660/f70acea6-8646-4133-a44f-673f75b53577">


Then, in the `app/build.gradle` file, add the `id 'org.jetbrains.kotlin.android' version '1.9.22'` line within the `plugins {}` block, removing `apply false`.

Screenshot for reference:
<img width="759" alt="image" src="https://github.com/flutter-stripe/flutter_stripe/assets/104574660/baa78f1c-16f1-48de-85ec-5ba5978861a3">

**Comment by edwito86** [comment]
> Para solucionar este problema, aplique el `plugins {}`bloque declarativo.
> 
> Los proyectos creados con versiones de Flutter anteriores a la 3.16 requieren migración manual. Para más detalles, consulte la [documentación.](https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply)
> 
> Después de la migración, actualice la versión de Kotlin dentro del `settings.gradle`archivo dentro del `plugins {}`bloque.
> 
> ```
> plugins {
>   id 'dev.flutter.flutter-plugin-loader' version '1.0.0'
>   id 'com.android.application' version '7.3.0' apply false
>   id 'org.jetbrains.kotlin.android' version '1.9.22' apply false
> }
> ```
> 
> Captura de pantalla como referencia: <img alt="imagen" width="628" src="https://private-user-images.githubusercontent.com/104574660/308886461-f70acea6-8646-4133-a44f-673f75b53577.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MjcxNDIsIm5iZiI6MTcwOTgyNjg0MiwicGF0aCI6Ii8xMDQ1NzQ2NjAvMzA4ODg2NDYxLWY3MGFjZWE2LTg2NDYtNDEzMy1hNDRmLTY3M2Y3NWI1MzU3Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwN1QxNTU0MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYzNiMzQ3MTBmODA0MGNlOTdlNjBmYzhlODQyY2Q0ODNjMzA2NmUwOTY3YTU2MDEzZTYyN2ExNTQwZTQ0OWFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.D3_cbeKhCovtduxCvqYKgDxrENdw7CBth4RcdGF7448">
> 
> Luego, en el `app/build.gradle`archivo, agregue la `id 'org.jetbrains.kotlin.android' version '1.9.22'`línea dentro del `plugins {}`bloque, eliminando `apply false`.
> 
> Captura de pantalla como referencia: <img alt="imagen" width="759" src="https://private-user-images.githubusercontent.com/104574660/308886088-baa78f1c-16f1-48de-85ec-5ba5978861a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MjcxNDIsIm5iZiI6MTcwOTgyNjg0MiwicGF0aCI6Ii8xMDQ1NzQ2NjAvMzA4ODg2MDg4LWJhYTc4ZjFjLTE2ZjEtNDhkZS04NWVjLTViYTU5Nzg4NjFhMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwN1QxNTU0MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MzI1ODQwYTliMjVhZTVhNGFiMzAxNTllZTA0YWZhYWU0Yjg0MmU1OTFhNDkxZWE2MzJkYmNjN2YwZTk0ZGRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BLlnypOrBmniyVb7OyZEqNMuaK5pI4GS7qe9CQG3q6s">

Excelente esto solucionó el problema... gracias por el aporte

**Comment by edwito86** [comment]
solo adicionar que en el app/build.gradle 
aparece así. y se agrega sin la versión... el resto todo super
![image](https://github.com/flutter-stripe/flutter_stripe/assets/53876001/f9f5772d-81c3-4bda-a8f6-a569ff3b810e)
