### ISSUE TITLE
Edit Option In PaymentSheet in Android

### ISSUE THREAD

**Issue by abumoallim** [flutter-stripe/flutter_stripe#163]
When you display the PaymentSheet,
The Edit option is not visible on Android but it is visible on IOS.
Any Solution for this?

In IOS:

![report_bug_stripe](https://user-images.githubusercontent.com/14852095/123258270-40e0ec80-d504-11eb-8713-9f3476f8d267.png)

in Android:

![report_bug_stripe_2](https://user-images.githubusercontent.com/14852095/123258278-42aab000-d504-11eb-87d2-b55711bca34c.png)

**Comment by jamesblasco** [comment]
I don't think it is implemented yet in the native android SDK. We will integrate it in this plugin as soon is released https://github.com/stripe/stripe-android/issues/3715

**Comment by jamesblasco** [comment]
This option is now available in the last version :)
