### ISSUE TITLE
Latest flutter_stripe 10.0.0 not working with compile SDK 33 

### ISSUE THREAD

**Issue by BrijalKothari** [flutter-stripe/flutter_stripe#1633]
![Screenshot 2024-02-07 at 2 27 54 PM-1](https://github.com/flutter-stripe/flutter_stripe/assets/92941109/b9c6efab-f17c-4141-873e-e3ba7c0418a5)

Also crash application with use of older flutter_stripe version in below given case

App crashes in android devices when click on back button while entering card details in stripe payment sheet

**Comment by freelancer-sk** [comment]
I am facing same error

**Comment by freelancer-sk** [comment]
![Screenshot 2024-02-07 at 8 18 38 PM](https://github.com/flutter-stripe/flutter_stripe/assets/158285364/9895e27a-0eb8-4afa-ba73-1d1f50afcd2e)

I am getting this error i tried all possible ways #needhelp

**Comment by freelancer-sk** [comment]
Hi @BrijalKothari 
the issue is solved on my side if you want help message here i will guide you

**Comment by BrijalKothari** [comment]
Can you give me solutions you are applied?@freelancer-sk

**Comment by remonh87** [comment]
this issue should be fixed

**Comment by misba031998** [comment]
![Image](https://github.com/user-attachments/assets/73edf01d-2b33-4025-9529-28462da70a0e)



same issue.
