### ISSUE TITLE
sendCancelIfRunning: isInProgress=falsecallback=androidx.activity.OnBackPressedDispatcher$Api33Impl$$ExternalSyntheticLambda0@b51d7d7

### ISSUE THREAD

**Issue by iwwencreative** [flutter-stripe/flutter_stripe#1634]
upon calling presentPaymentSheet this error occurs

**Comment by remonh87** [comment]
I need a reproduction scenario because I cannot reproduce it. Can you check your android configuration? https://docs.page/flutter-stripe/flutter_stripe/troubleshooting
