### ISSUE TITLE
Need "risk_correlation_id" when using saved PayPal

### ISSUE THREAD

**Issue by VtorovN** [flutter-stripe/flutter_stripe#1643]
I'm trying to pay with PayPal and save it for future usage using:

```dart
Stripe.confirmPayment(
  paymentIntentClientSecret: clientSecret,
  data: const PaymentMethodParams.payPal(
    paymentMethodData: PaymentMethodData(
      mandateData: MandateData(
        customerAcceptance: MandateDataCustomerAcceptance(
          ipAddress: MandateDataOnlineData(
            // See https://github.com/flutter-stripe/flutter_stripe/pull/1341#issue-1822333759 for details
            ipAddress: '127.0.0.1',
            userAgent: 'device',
          ),
        ),
      ),
    ),
  ),
  options: PaymentMethodOptions(
    setupFutureUsage: PaymentIntentsFutureUsage.OnSession,
  ),
);
```

For `setupFutureUsage` option I tried using both `PaymentIntentsFutureUsage.OnSession` and `PaymentIntentsFutureUsage.OffSession`.

---

However, whenever I try to use saved PayPal, I get this error:

```
StripeException(
  error: LocalizedErrorMessage(
    code: FailureCode.Failed,
    localizedMessage: There was an unexpected error -- try again in a few seconds,
    message: You must specify `payment_method_options[paypal][risk_correlation_id]` for on-session PayPal payments. Read our integration guide for more details at https://stripe.com/docs/payments/paypal/set-up-future-payments.,
    stripeErrorCode: parameter_missing, declineCode: null, type: invalid_request_error
  )
)
```

Note that the error is the same no matter what I pass to `setupFutureUsage` - `OnSession` or `OffSession` param.

I tried checking out the link in the error: https://stripe.com/docs/payments/paypal/set-up-future-payments. It seems it's not my case, it's all about `SetupIntent`.

Only thing I found about the `risk_correlation_id` is here: https://docs.stripe.com/api/checkout/sessions/create#create_checkout_session-payment_method_options-paypal-risk_correlation_id
It seems like my backend must pass it to Stripe when creating payment session. However, docs does not specify what is this parameter and where to get it.

Also, on Web (React SDK) saved PayPal is working perfectly fine, so it seems like it's a problem in mobile.

---

I can reproduce the error on both platforms, IOS and Android, with the latest SDK version 10.0.0

---

So, I have several questions:
1. Is it possible to setup PayPal for future usage using PaymentIntent?
2. What is risk_correlation_id and where to get it? Can I somehow avoid passing it, as it seems to work without it on Web SDK?
3. Is it possible that this issue appears because there is no way to pass `payment_method_id` to Stripe through Flutter SDK? This seems like a difference between Flutter and Web SDK. If so, is there a way to pass it that I can't see?

Thanks in advance!

**Comment by remonh87** [comment]
1. No this is not yet available we need to wait for stripe to implement it: https://github.com/stripe/stripe-react-native/issues/1562
2. I did look into this but the correlation ID can be provided in the server: https://docs.stripe.com/payments/paypal/set-up-future-payments?web-or-mobile=mobile&payments-ui-type=android#android-pass-risk-id-manually
3. You can specify a payment method but you need to use paymentintents for paying eventually. Payment methods are deprecated by Stripe

**Comment by remonh87** [comment]
For setup future usage I will track this in #1684
