### ISSUE TITLE
Payment Sheet Not Displaying on iOS 17 Devices with flutter_stripe 2.0.0

### ISSUE THREAD

**Issue by paradax005** [flutter-stripe/flutter_stripe#1650]
**Description of the bug**
The payment sheet fails to display on iOS 17 devices, despite working correctly on other iOS versions and iPads. This issue prevents users from completing payments on devices running iOS 17.

**To Reproduce**

Run the app on an iOS 17 device.
Attempt to make a payment using the payment sheet.
Observe that the payment sheet does not appear, and no error messages are displayed.
Expected behavior The payment sheet should display correctly on all iOS devices, including those running iOS 17, allowing users to complete payments as expected.

**Smartphone / tablet**

Device: iPhone 15, iPad Air (5th generation)
OS: iOS 17.2
Package version: 2.0.0
Flutter version: 2.10.2

**Additional context**

The issue occurs only on iOS 17 devices.
The payment sheet works correctly on other iOS versions, iPads and android.
No errors or exceptions are thrown in the console when attempting to display the payment sheet on iOS 17 devices.

**Comment by jonasbark** [comment]
We are regularly testing with iOS 17 and do not observe any issues. Please provide a reproducible example.

**Comment by paradax005** [comment]
Thank you for looking into this issue. I've been experiencing a problem where the payment sheet fails to display on iOS 17.2 devices, despite working correctly on other iOS versions and iPads. This issue prevents users from completing payments on devices running iOS 17.2.

I've attached a minimal reproducible example (MRE) and screenshots to help illustrate the problem. The MRE includes the initialization of flutter_stripe and the attempt to present the payment sheet, as shown in the code snippets below:

 await Stripe.instance.initPaymentSheet(
          paymentSheetParameters: SetupPaymentSheetParameters(
        applePay: false,
        googlePay: false,
        merchantDisplayName: "Toll Hopper",
        customerId: paymentIntentData['customer'],
        paymentIntentClientSecret: paymentIntentData['client_secret'],
        customerEphemeralKeySecret: paymentIntentData['ephemeralKey'],
      ));
      
      await Stripe.instance.presentPaymentSheet();
      
      this is the output of flutter doctor 
      flutter doctor 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.2, on macOS 14.2.1 23C71 darwin-arm, locale
    en-TN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✗] Chrome - develop for the web (Cannot find Chrome executable at
    /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.86.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.


![Simulator Screenshot - iPhone 15 Pro - 2024-02-27 at 10 43 04](https://github.com/flutter-stripe/flutter_stripe/assets/73790117/236f8ecc-802e-4920-a222-6872efa77b32)
![77-EA4488-1-C49-46-FC-B851-09-CB5-A3-E598-D](https://github.com/flutter-stripe/flutter_stripe/assets/73790117/54c73af2-d5aa-42ff-812e-95fb84660f00)

**Comment by jonasbark** [comment]
I just tried the `payment_sheet_screen.dart` in our example app and it works fine on iOS 17.2 simulator

**Comment by jonasbark** [comment]
By the way, your package version is super old. Upgrade to 10.0.0.

**Comment by paradax005** [comment]
thanks for your response
