### ISSUE TITLE
"Something went wrong" in payment sheet

### ISSUE THREAD

**Issue by iospidigi** [flutter-stripe/flutter_stripe#1654]
**Describe the bug**
While making payment in Stripe, the payment sheet shows "Something went wrong" message after entering the card details.

**To Reproduce**
1. Entering number 123-456-789 into the cardfield.
2. Enter expiry and cvv.
3. Tapping the confirm button.

**Expected behavior**
Payment should be successful 

**Smartphone / tablet**
 - Device: Vivo v27
 - OS: Funtouch OS Android 14
 - Package version: 9.3.0
 - Flutter version: 3.10.6

_Originally posted by @iospidigi in https://github.com/flutter-stripe/flutter_stripe/discussions/1653_

**Comment by Bittibw** [comment]
Facing the same problem

**Comment by jonasbark** [comment]
Please provide the exact steps on how to reproduce this. The number you provided is not a valid credit card number.

**Comment by Bittibw** [comment]
> Please provide the exact steps on how to reproduce this. The number you provided is not a valid credit card number.

I guess you are putting the wrong number of you are facing the same problem then try with this card number once 
4000003560000123
For the dates and cvv put any future number for date. And lastly select the  country as india and try it

**Comment by navaghandabhi** [comment]
![Screenshot_20240405_100439](https://github.com/flutter-stripe/flutter_stripe/assets/142008642/cf909a2d-25ff-421b-a1f4-c1405ba002e8)

I got this message `An unexpected error occurred`
some times I got  message `Something went wrong`

**Comment by remonh87** [comment]
This normally has to do with a misconfigured Stripe instance. Make sure that you use the proper keys and that you are allowed to accept payments from the united states. In this case I would check the stripe dashboard because I think the payment could not be processed.

**Comment by Bittibw** [comment]
> ![Card No : 4242 4242 4242 4242](https://private-user-images.githubusercontent.com/142008642/319859396-cf909a2d-25ff-421b-a1f4-c1405ba002e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxMjEzNzIsIm5iZiI6MTcxMzEyMTA3MiwicGF0aCI6Ii8xNDIwMDg2NDIvMzE5ODU5Mzk2LWNmOTA5YTJkLTI1ZmYtNDIxYi1hMWY0LWMxNDA1YmEwMDJlOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNFQxODU3NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOTE4ZGUyNDBiMDdlZGUzMGM5NTA3MjUyOWNjNWY0YmZmODJmMTczNDM1M2Y2YmZhYTliZmI3YTA5OWYwNzczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XChvlyoMWoOm2qQCO2puDnPO7Q_B305KI7qkbOfDfI8)I got this message `An unexpected error occurred` some times I got message `Something went wrong`

Bro I have given an Indian card test that us card is not working now as per rbi rules and regulations

**Comment by SreehariRajeevFSS** [comment]
Facing the same error.
But when I am changing the currency to inr in the payment intent and "currency" the payment is getting success, when I change the currecny back to usd the sheet prompts the error "Something went wrong".

**Comment by remonh87** [comment]
Check the logs if you received an exception from Stripe normally there is some issue there.  Also keep in mind that there are extra requirements to payments in India: https://support.stripe.com/questions/failed-international-payments-from-stripe-accounts-in-india  so your server needs to supply the proper details there.

The unexpected error is not something our library can solve since it is thrown by the offical stripe sdk

**Comment by SreehariRajeev** [comment]
> Check the logs if you received an exception from Stripe normally there is some issue there. Also keep in mind that there are extra requirements to payments in India: https://support.stripe.com/questions/failed-international-payments-from-stripe-accounts-in-india so your server needs to supply the proper details there.
> 
> The unexpected error is not something our library can solve since it is thrown by the offical stripe sdk

@remonh87 does this apply to test payments also?

**Comment by SreehariRajeev** [comment]
Any updates on this issue @albertus-stripe

**Comment by remonh87** [comment]
@SreehariRajeev  yes test payments still need to comply to some regulations

**Comment by aqeelshamz** [comment]
> > Please provide the exact steps on how to reproduce this. The number you provided is not a valid credit card number.
> 
> I guess you are putting the wrong number of you are facing the same problem then try with this card number once 4000003560000123 For the dates and cvv put any future number for date. And lastly select the country as india and try it

Worked. Thanks

**Comment by sujin93** [comment]
Map<String, dynamic>? paymentInfo = {
        "amount": amountToBeCharge,
        "currency": currency,
        "shipping": {
          "name":"Sujin"
          "address": {
            "line1": "Any where",
            "postal_code": "10001",
            "city": "Anytown",
            "state": "CA",
            "country": "US",
          }
        }
      };
      
      
      pass the params like this

**Comment by priyanshu-datacultr** [comment]
> > > Please provide the exact steps on how to reproduce this. The number you provided is not a valid credit card number.
> > 
> > 
> > I guess you are putting the wrong number of you are facing the same problem then try with this card number once 4000003560000123 For the dates and cvv put any future number for date. And lastly select the country as india and try it
> 
> Worked. Thanks

What's the reason behind it? why only this card works?
