### ISSUE TITLE
Issue Report: Assertion Failure in StripeUICore/ImageMaker.swift

### ISSUE THREAD

**Issue by abdullahjavaid409** [flutter-stripe/flutter_stripe#1657]
Dear Stripe Flutter Package Maintainers,

I hope this message finds you well. I'm writing to report an issue I encountered while integrating the Stripe Flutter package into my project.

Problem Description:
I'm encountering an assertion failure with the following error message:

StripeUICore/ImageMaker.swift:51: Assertion failed: Failed to find an image named icon_x_standalone

This error occurs when the payment sheet is opened in the Stripe Flutter UI. It seems that the Flutter UI is attempting to find an image named "icon_x_standalone" but failing to do so.

Steps to Reproduce:

Open the Flutter app.
Navigate to the payment sheet.
Observe the assertion failure with the error message mentioned above.
Additional Information:

Flutter SDK Version: >=3.3.0 <4.0.0
Stripe Flutter Package Version: 10.0.0
Platform: [Insert platform (iOS/Android) and version if applicable]
Expected Behavior:
The payment sheet should open without any assertion failures or errors related to missing images.

Potential Solutions Attempted:

Checked image assets in the project.
Reviewed package documentation and GitHub repository for similar issues.
Request:
I kindly request your assistance in resolving this issue. If there are any specific configurations or steps I should take to mitigate this problem, please let me know.

Thank you for your attention to this matter. I appreciate your efforts in maintaining the Stripe Flutter package and supporting the Flutter community.

Best regards,
Abdullah javaid

**Comment by jonasbark** [comment]
As seen in https://github.com/flutter-stripe/flutter_stripe/issues/1635
