### ISSUE TITLE
Hide country field which can be an optional field for card details

### ISSUE THREAD

**Issue by bikram-nestrait** [flutter-stripe/flutter_stripe#1668]
The basic required input fields for Credit Cards are 3 fields
1. Card Number
2. Expiration Date
3. CVC

![image](https://github.com/flutter-stripe/flutter_stripe/assets/112677011/19fd5b19-c5cb-4cd5-96ed-b097981e917f)

Address-related related like Country and Postal code are optional fields.

There is a feature to show/hide the postal code but not the country.

Can we have a feature to show/hide for the county as well?

**Comment by remonh87** [comment]
Is this in the web element or in the paymentsheet that you miss this functionality?

**Comment by hczmail** [comment]
I also need to hide the country

**Comment by AristideVB** [comment]
@remonh87 We are missing this feature in CardFormField
