### ISSUE TITLE
handleCardAction 3ds issue

### ISSUE THREAD

**Issue by CalmAndCoDe** [flutter-stripe/flutter_stripe#167]
**Describe the bug**
Hi, i used this package for one of my projects but i faced an issue with 3ds required cards, i created a customer, and then attached a payment method on it in my backend and then i created a payment intent with confirmation_method: automatic to confirm intents using my publishable key instread of server. then i tried using handleCardAtion to perform the 3ds authentication but i always get this error and sometimes even it asks for username and password for stripe.
i was thinking that there is something wrong with my publishable key but i set it at the start of app according to docs 
and also using 
```
await StripePlatform.instance.initialise(
    publishableKey: STRIPE_KEY,
 );
```
but didn't work.

[Error Screen Shot](https://ik.imagekit.io/ttmfcqqj1mv/Screenshot_1624717721_fMSebwAW7.png)

**To Reproduce**
1. Create payment intent using 3ds required card (4000 0025 0000 3155 TEST)
2. use: Stripe.instance.handleCardAction(INTENT_CLIENT_SECRET)
3. fetch the intent details and you will see the payment status: requires_confirmation
4. you will be redirected to webpage thats showing API key error at least for me

**Expected behavior**

**Smartphone / tablet**
 - Device: Google Pixel 4 API 29
 - OS: Android 10
 - Package version: 1.0.2 with local version of (stripe_platform_interface for the latest confirmPaymentMethod patch)
 - Flutter version 2.2.2

**Comment by CalmAndCoDe** [comment]
Update: i'm not sure if the error was on stripe end or plugin but it got solved without any change, maybe something is wrong in intialization but not sure.

**Comment by jamesblasco** [comment]
Glad to hear that you got it working! Please reopen this issue if you encounter again the same problem :)
