### ISSUE TITLE
Android Exception stripe v10.0.0 and 10.1.0 

### ISSUE THREAD

**Issue by KallepalliTirumalesh** [flutter-stripe/flutter_stripe#1670]
Card field not displaying with latest version getting below exception

 Exception: PlatformException(error, null cannot be cast to non-null type kotlin.collections.List<kotlin.Any>, null, java.lang.NullPointerException: null cannot be cast to non-null type kotlin.collections.List<kotlin.Any>
 
 Flutter Version 3.19.2

**Comment by Tom3652** [comment]
Hi @KallepalliTirumalesh may i ask you what version of Kotlin are you using in your project ? 

I am unable to build on Android using Kotlin `1.9.0` and would like to confirm that you have a version < `1.7.1` (which is the one working on `flutter_stripe`) please

**Comment by KallepalliTirumalesh** [comment]
Hi @Tom3652 I am using Kotlin 1.8.22 i dont have any build issue's with the latest stripe version only issue i have is with cardfield not showing up on Android ,On iOS its working fine.
9.6.0 looks stable to me with no issues apart from Apple Pay.
Hope this helps.

**Comment by jonasbark** [comment]
@KallepalliTirumalesh thanks for reporting! A fix will be released with 10.1.1 shortly

**Comment by aqtechnowis** [comment]
Hi I am facing the same issue as [KallepalliTirumalesh](https://github.com/KallepalliTirumalesh) that CardFormField does not appear and gives the exception.

Flutter Version 3.19.2

Here is the exception I am getting

E/MethodChannel#flutter/platform_views(26732): Failed to handle method call
E/MethodChannel#flutter/platform_views(26732): java.lang.NullPointerException: null cannot be cast to non-null type kotlin.collections.List<kotlin.Any>
E/MethodChannel#flutter/platform_views(26732): 	at com.flutter.stripe.StripeSdkCardFormPlatformView.<init>(StripeSdkCardFormPlatformView.kt:58)
E/MethodChannel#flutter/platform_views(26732): 	at com.flutter.stripe.StripeSdkCardFormPlatformViewFactory.create(StripeSdkCardFormPlatformViewFactory.kt:24)
E/MethodChannel#flutter/platform_views(26732): 	at io.flutter.plugin.platform.PlatformViewsController.createPlatformView(PlatformViewsController.java:527)
E/MethodChannel#flutter/platform_views(26732): 	at io.flutter.plugin.platform.PlatformViewsController$1.createForPlatformViewLayer(PlatformViewsController.java:169)
E/MethodChannel#flutter/platform_views(26732): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:105)
E/MethodChannel#flutter/platform_views(26732): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:55)
E/MethodChannel#flutter/platform_views(26732): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/MethodChannel#flutter/platform_views(26732): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/MethodChannel#flutter/platform_views(26732): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#flutter/platform_views(26732): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#flutter/platform_views(26732): 	at android.os.Handler.handleCallback(Handler.java:883)
E/MethodChannel#flutter/platform_views(26732): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/MethodChannel#flutter/platform_views(26732): 	at android.os.Looper.loop(Looper.java:219)
E/MethodChannel#flutter/platform_views(26732): 	at android.app.ActivityThread.main(ActivityThread.java:7709)
E/MethodChannel#flutter/platform_views(26732): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/platform_views(26732): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
E/MethodChannel#flutter/platform_views(26732): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
E/flutter (26732): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, null cannot be cast to non-null type kotlin.collections.List<kotlin.Any>, null, java.lang.NullPointerException: null cannot be cast to non-null type kotlin.collections.List<kotlin.Any>
E/flutter (26732): 	at com.flutter.stripe.StripeSdkCardFormPlatformView.<init>(StripeSdkCardFormPlatformView.kt:58)
E/flutter (26732): 	at com.flutter.stripe.StripeSdkCardFormPlatformViewFactory.create(StripeSdkCardFormPlatformViewFactory.kt:24)
E/flutter (26732): 	at io.flutter.plugin.platform.PlatformViewsController.createPlatformView(PlatformViewsController.java:527)
E/flutter (26732): 	at io.flutter.plugin.platform.PlatformViewsController$1.createForPlatformViewLayer(PlatformViewsController.java:169)
E/flutter (26732): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:105)
E/flutter (26732): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:55)



Leaving this here for the team if it helps in figuring out the issue.
