### ISSUE TITLE
[Reopen] Execution failed for task ':stripe_android:verifyReleaseResources'.

### ISSUE THREAD

**Issue by Okladnoj** [flutter-stripe/flutter_stripe#1679]
Describe the bug
I get an error when I try to generate apk "flutter build apk" as shown

Execution failed for task ':stripe_android:verifyReleaseResources'.

[Details](https://github.com/flutter-stripe/flutter_stripe/issues/1676#issuecomment-1984572294)

**Comment by Okladnoj** [comment]
### pubspec.yaml
```yaml
flutter_stripe: 10.1.1
``` 
### flutter pub upgrade
```sh
stripe_android 10.1.1 (was 10.1.0)
```

### Build apk
```log
flutter build apk --release --dart-define=prod=false
✓  Built build/app/outputs/flutter-apk/app-release.apk (48.7MB).
```
![image](https://github.com/flutter-stripe/flutter_stripe/assets/36802187/dc0ee68a-c078-4782-87ef-11bdcb79c412)

**Comment by Aptul9** [comment]
Same error for me after updating to the latest version, how did you resolve?

**Comment by Okladnoj** [comment]
```
flutter clean
flutter pub upgrade
flutter run
```

didn't help you?
