### ISSUE TITLE
Still getting error web payment `sepaDebit` is not one of the supported values

### ISSUE THREAD

**Issue by siherrmann** [flutter-stripe/flutter_stripe#1681]
https://github.com/flutter-stripe/flutter_stripe/issues/1637#issuecomment-1956319107

Thank you for your work but the fix (version stripe_js 3.4.0) didn't change anything for me. Please refer to my comment what exactly the breaking case was.

Error was still:
```
Invalid argument(s): `sepa_debit` is not one of the supported values: acssDebit, affirm, afterpayClearpay, alipay, auBecsDebit, bacsDebit, bancontact, blik, boleto, card, cashapp, cardPresent, customerBalance, eps, fpx, giropay, grabpay, ideal, interacPresent, klarna, konbini, link, oxxo, p24, paynow, pix, promptpay, sepaDebit, sofort, usBankAccount, wechatPay
```
Issue occurs on confirming a payment element created with two or more payment methods and there is still the error that sepaDebit is not the officially supported value by stripe and I get sepa_debit from the newly (and correctly) created payment intent.

I opened a new issue because the issue is slowing down development for us.

**Comment by siherrmann** [comment]
What does enhancement mean? Does it mean that you don't see it as necessary? For us it's currently breaking. Thank you for your help.

**Comment by alessandropettenuzzo96** [comment]
Adding an `unknownValue` in the decoding of the `payment_method_types` at line 59 of payment_intent.g.dart resolve the issue.
