### ISSUE TITLE
Is there any way to integrate Google Pay and Apple Pay on web app

### ISSUE THREAD

**Issue by rahulrmishra** [flutter-stripe/flutter_stripe#1685]
I wanted to know if we can integrate google pay or apple pay in web app?
If we can, then is there any documentation that I can refer?
If no, then is there any plan to make it happen with this plugin?

**Comment by remonh87** [comment]
You can use the platform pay integration as this is available in the latest version

**Comment by rahulrmishra** [comment]
@remonh87 Thanks for your reply but I couldn't understand the "platform pay integration".
Do you mean the "Pay" plugin? But that is only supported for Android and iOS.
