### ISSUE TITLE
Unsupported Swift architecture

### ISSUE THREAD

**Issue by Safiullah2000** [flutter-stripe/flutter_stripe#1686]
I am integrating sumup and stripe in my App but when i am running it in ios simulator it gives me Unsupported Swift architecture error first it comes on my sumup so i change my podfile as follows: 

<img width="598" alt="Screenshot 2024-03-15 at 2 14 37 PM" src="https://github.com/flutter-stripe/flutter_stripe/assets/45438596/68327d93-bcd9-4b89-9941-15bceea2a333">

So it resolves sumup but not resolves stripe error I want that you can help me to run stripe in my application as well as sumup.

<img width="1440" alt="Screenshot 2024-03-15 at 2 12 47 PM" src="https://github.com/flutter-stripe/flutter_stripe/assets/45438596/89442131-9154-4a28-a966-4c4382032f11">

**Smartphone / tablet**
 - Device: iPhone 15 Pro
 - OS: ios 17.2
 - Package version: 9.5.0+1
 - Flutter version 3.16.9

**Comment by remonh87** [comment]
can you upgrade the package? It looks like this package does not support latest xcode.

**Comment by Safiullah2000** [comment]
I have updated flutter stripe to 10.1.1 now gotting this error

Swift Compiler Error (Xcode): Could not find module 'StripePaymentSheet' for target 'arm64-apple-ios-simulator'; found: x86_64-apple-ios-simulator, at: /Users/safiullahparvez/Flutter Applications/Di-Donation-App/build/ios/Debug-iphonesimulator/StripePaymentSheet/StripePaymentSheet.framework/Modules/StripePaymentSheet.swiftmodule
/Users/safiullahparvez/.pub-cache/hosted/pub.dev/stripe_ios-10.1.0/ios/Classes/Stripe%20Sdk/AddressSheet/AddressSheetUtils.swift:8:7

Uncategorized (Xcode): Command SwiftCompile failed with a nonzero exit code

Could not build the application for the simulator.
Error launching application on iPhone 15 Pro.
