### ISSUE TITLE
Version incompatible

### ISSUE THREAD

**Issue by SantoshJaya** [flutter-stripe/flutter_stripe#1688]
I am following stripe official document,but still encountering the following issue,how to resolve

The class is loaded from /home/santosh/.gradle/caches/transforms-3/64a3ac285e7f1fb3bc51a2db1d8aedbf/transformed/jetified-payments-model-20.37.4-api.jar!/com/stripe/android/model/CardBrand.class
e: /home/santosh/.pub-cache/hosted/pub.dev/stripe_android-10.1.1/android/src/main/kotlin/com/reactnativestripesdk/utils/Mappers.kt: (947, 20): Class 'com.stripe.android.model.CardBrand' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.

**Comment by remonh87** [comment]
diplicate of #1669
