### ISSUE TITLE
Non active PayPal payment appearing in the payment sheet on Android 

### ISSUE THREAD

**Issue by matthewfx** [flutter-stripe/flutter_stripe#1698]
**Describe the bug**
We have just 3 payment methods active in Stripe dashboard: credit card, Apple Pay and Google Pay. All works and looks fine on iOS but surprisingly the payment sheet shows the PayPal button on Android. 

**To Reproduce**
1. Used ` Stripe.instance.initPaymentSheet` and `await Stripe.instance.presentPaymentSheet();` 

**Expected behavior**
A payment sheet appears that provides only credit card or Apple/Google Pay payments.

**Smartphone / tablet**
 - Device: tested on various Android emulators and real Pixel 3 device
 - OS: Android 12
 - Package version: tested  9.5.0+1 & 10.1.1

 - Flutter version 3.19.0

**Additional context**

**Comment by remonh87** [comment]
I would contact stripe support for this issue. They can based on the payment intent tell you why this happens. The paymentsheet is a native component that is out of our control. based on the payment intent it decides what to draw on there.

**Comment by nayanbabariya** [comment]
I see the `PayPal` option in the payment sheet in Android as I've enabled it from the Stripe dashboard. but can not see the PayPal option in iOS.

**Comment by SnapDrive** [comment]
@nayanbabariya any updates? Maybe Stripe only supports the PayPal payment sheet on android?

**Comment by SnapDrive** [comment]
@nayanbabariya Thanks for your fast response. Do you have a reference where I can see the redirect Urls to setup in Xcode? Happy Christmas!

**Comment by nayanbabariya** [comment]
@SnapDrive

Flutter code:
```dart
Stripe.urlScheme = 'flutterstripe';
await Stripe.instance.applySettings();
```
```xml
<key>CFBundleURLTypes</key>
<array>
	<dict>
		<key>CFBundleTypeRole</key>
		<string>Editor</string>
		<key>CFBundleURLSchemes</key>
		<array>
			<string>flutterstripe</string>
		</array>
	</dict>
</array>
```

Happy Christmas 🎅🎄🥳

**Comment by SnapDrive** [comment]
Hi @Adnan-addi as already mentioned above. You need to add a return url during payment intent creation in flutter. You can simply add it as an argument.

**Comment by Hemu21** [comment]
> [@SnapDrive](https://github.com/SnapDrive)
> 
> Flutter code:
> 
> Stripe.urlScheme = 'flutterstripe';
> await Stripe.instance.applySettings();
> info.plist in iOS
> 
> <key>CFBundleURLTypes</key>
> <array>
> 	<dict>
> 		<key>CFBundleTypeRole</key>
> 		<string>Editor</string>
> 		<key>CFBundleURLSchemes</key>
> 		<array>
> 			<string>flutterstripe</string>
> 		</array>
> 	</dict>
> </array>
> Happy Christmas 🎅🎄🥳

![Image](https://github.com/user-attachments/assets/36a9d300-5ab8-487c-b166-2e851c227db4)

**Should i need to add the url here or just need to update in code. @nayanbabariya can you please tell me i am also facing same issue**

**Comment by nayanbabariya** [comment]
@Hemu21 Please follow this article. Hope it will help you.
https://medium.com/@nayanbabariya/stripe-subscriptions-in-flutter-d34b568f98c4

**Comment by Hemu21** [comment]
> @Hemu21 Please follow this article. Hope it will help you.
> https://medium.com/@nayanbabariya/stripe-subscriptions-in-flutter-d34b568f98c4

Thank you 😊
