### ISSUE TITLE
iOS required reason API usage 

### ISSUE THREAD

**Issue by KallepalliTirumalesh** [flutter-stripe/flutter_stripe#1703]
Hi Team,

Please update and add api usage description

Found potentially required reason API usage 'UserDefaults' in './ios/Pods/Stripe/Stripe/StripeiOS/Source/STPCustomerContext.swift'
Line numbers: 372 376 402 411 413 
Found potentially required reason API usage 'NSUserDefaults' in './ios/Pods/Stripe/Stripe/StripeiOS/Source/STPCustomerContext.swift'
Line numbers: 411 
Found potentially required reason API usage 'UserDefaults' in './ios/Pods/Stripe/Stripe/StripeiOS/Source/STPPaymentContext.swift'
Line numbers: 180 
Found potentially required reason API usage 'NSUserDefaults' in './ios/Pods/Stripe/Stripe/StripeiOS/Source/STPPaymentContext.swift'
Line numbers: 180 
Found potentially required reason API usage 'UserDefaults' in './ios/Pods/Stripe/Stripe/StripeiOS/Source/STPPaymentOptionsViewController.swift'
Line numbers: 256 
Found potentially required reason API usage 'NSUserDefaults' in './ios/Pods/Stripe/Stripe/StripeiOS/Source/STPPaymentOptionsViewController.swift'
Line numbers: 256 
Found potentially required reason API usage 'UserDefaults' in './ios/Pods/Stripe/Stripe/StripeiOS/Source/UserDefaults+Stripe.swift'
Line numbers: 2 11 12 
Found potentially required reason API usage 'UserDefaults' in './ios/Pods/StripeCore/StripeCore/StripeCore/Source/Telemetry/FraudDetectionData.swift'
Line numbers: 19 20 55 
Found potentially required reason API usage 'UserDefaults' in './ios/Pods/StripeCore/StripeCore/StripeCore/Source/Telemetry/UserDefaults+PaymentsCore.swift'
Line numbers: 2 11 12 
Found potentially required reason API usage 'UserDefaults' in './ios/Pods/StripeFinancialConnections/StripeFinancialConnections/StripeFinancialConnections/Source/Common/FlowRouter.swift'
Line numbers: 45 
Found potentially required reason API usage 'UserDefaults' in './ios/Pods/StripePaymentSheet/StripePaymentSheet/StripePaymentSheet/Source/Internal/Link/Controllers/PayWithLinkWebController.swift'
Line numbers: 184 
Found potentially required reason API usage 'UserDefaults' in './ios/Pods/StripePaymentSheet/StripePaymentSheet/StripePaymentSheet/Source/Internal/Link/LinkUI.swift'
Line numbers: 66 
Found potentially required reason API usage 'UserDefaults' in './ios/Pods/StripePaymentSheet/StripePaymentSheet/StripePaymentSheet/Source/Internal/Link/ViewModels/LinkInlineSignupViewModel.swift'
Line numbers: 210 
Found potentially required reason API usage 'UserDefaults' in './ios/Pods/StripePaymentSheet/StripePaymentSheet/StripePaymentSheet/Source/PaymentSheet/CustomerAdapter/CustomerAdapter.swift'
Line numbers: 227 229 
Found potentially required reason API usage 'NSUserDefaults' in './ios/Pods/StripePaymentSheet/StripePaymentSheet/StripePaymentSheet/Source/PaymentSheet/CustomerAdapter/CustomerAdapter.swift'
Line numbers: 227 
Found potentially required reason API usage 'UserDefaults' in './ios/Pods/StripePaymentSheet/StripePaymentSheet/StripePaymentSheet/Source/PaymentSheet/CustomerAdapter/CustomerPaymentOption.swift'
Line numbers: 46 51 60 
Found potentially required reason API usage 'UserDefaults' in './ios/Pods/StripePaymentSheet/StripePaymentSheet/StripePaymentSheet/Source/PaymentSheet/CustomerAdapter/UserDefaults+StripePaymentSheet.swift'
Line numbers: 2 11 12 
Found potentially required reason API usage 'UserDefaults' in './ios/Pods/StripePaymentSheet/StripePaymentSheet/StripePaymentSheet/Source/PaymentSheet/PaymentSheet+API.swift'
Line numbers: 427 
Found potentially required reason API usage 'UserDefaults' in './ios/Pods/StripePaymentSheet/StripePaymentSheet/StripePaymentSheet/Source/PaymentSheet/PaymentSheet.swift'
Line numbers: 204 
Found potentially required reason API usage 'UserDefaults' in './ios/Pods/StripePaymentSheet/StripePaymentSheet/StripePaymentSheet/Source/PaymentSheet/ViewControllers/PaymentSheetFlowControllerViewController.swift'
Line numbers: 612 
Found potentially required reason API usage 'UserDefaults' in './ios/Pods/StripePaymentSheet/StripePaymentSheet/StripePaymentSheet/Source/PaymentSheet/ViewControllers/PaymentSheetViewController.swift'
Line numbers: 707 
Found potentially required reason API usage 'UserDefaults' in './ios/Pods/StripePayments/Stripe3DS2/Stripe3DS2/STDSDeviceInformationParameter.m'
Line numbers: 437 438 442 443 446 449 
Found potentially required reason API usage 'NSUserDefaults' in './ios/Pods/StripePayments/Stripe3DS2/Stripe3DS2/STDSDeviceInformationParameter.m'

**Comment by remonh87** [comment]
This needs to be done on the stripe sdk and is nothing we have control about.
