### ISSUE TITLE
paybutton description missing

### ISSUE THREAD

**Issue by TheFutureStartsNow** [flutter-stripe/flutter_stripe#171]
![Screenshot 2021-06-28 at 18 03 47](https://user-images.githubusercontent.com/26114698/123659349-e234af00-d832-11eb-916f-9f061a75055c.jpg)

This version from https://developer.apple.com/design/human-interface-guidelines/apple-pay/overview/buttons-and-marks/ is missing and it is picked by our design team, so it would be geat to add it.

So something like this would be great, but it is missing
child: ApplePayButton(
                constraints: BoxConstraints(maxWidth: 230),
                type: **ApplePayButtonType.pay**,
                onPressed: _handlePayPress,
              ),

**Comment by Faiizii** [comment]
is there any update on it ?

**Comment by jamesblasco** [comment]
This Apple Pay Button Type is called "inStore". You can use it as ApplePayButtonType.inStore

https://developer.apple.com/documentation/passkit/pkpaymentbuttontype/instore

**Comment by Faiizii** [comment]
We know that we can use it by pay button type, but how can it be done from this lib?
