### ISSUE TITLE
Flutter stripe web: add support for dangerouslyUpdateCardDetails

### ISSUE THREAD

**Issue by jasminCrest** [flutter-stripe/flutter_stripe#1710]
I have used following method for stripe payment.

Stripe.instance.dangerouslyUpdateCardDetails(
    CardDetails(
      number: '4242424242424242',
      cvc: '314',
      expirationMonth: 05,
      expirationYear: 29,
    ),
);

while calling this method in web getting following error.
WebUnsupportedError: dangerouslyUpdateCardDetails is not supported for Web.

can any one have idea or solution for working this in web.

I am using following package with version: 
flutter_stripe: ^10.1.1
flutter_stripe_web: ^5.1.0

Please help me i spend a week for it to working out.

Is there any other way to use custom cardDetail UI(card_number, card_name, expiry, cvv) for generating card payment method.?

Thank you

**Comment by jamesblasco** [comment]
Hi @jasminCrest, the official `stripe.js` does not allow to hard code customer card details into the web elements neither allows to create a card payment method that uses custom UI different from the Card Element. This is a security measurement and there is nothing we can do on the Flutter side to implement something like on mobile. 


The recommended way to accept payments for web is using the PaymentElement available in the flutter stripe web package. 
https://docs.stripe.com/payments/payment-element

**Comment by dhoffer** [comment]
Hi @jasminCrest I too am trying to implement Flutter web for Stripe CC payments.  Sounlds like you are way ahead of me in implementing this.  Could you send me your code that handles the Stripe CC payments for Flutter web?  My email is dhoffer6@gmail.com, much appreciated.
