### ISSUE TITLE
Android build issue

### ISSUE THREAD

**Issue by darshakpranpariya** [flutter-stripe/flutter_stripe#172]
[com.stripe:stripe-android:16.8.2] C:\Users\Admin\.gradle\caches\transforms-2\files-2.1\8dc4c04ceec06424a7af9ba3d43bee11\stripe-android-16.8.2\AndroidManifest.xml:13:9-54 Error:
	Missing 'package' key attribute on element package at [com.stripe:stripe-android:16.8.2] AndroidManifest.xml:13:9-54
[com.stripe:stripe-android:16.8.2] C:\Users\Admin\.gradle\caches\transforms-2\files-2.1\8dc4c04ceec06424a7af9ba3d43bee11\stripe-android-16.8.2\AndroidManifest.xml Error:
	Validation failed, exiting

When I start debugging it shows this error and build failed.

**Comment by linversion** [comment]
try to update your gradle version

**Comment by jonasbark** [comment]
Yes, that's the key. Update it to at least e.g. 4.1.9:
https://github.com/flutter-stripe/flutter_stripe/blob/main/example/android/build.gradle#L9
