### ISSUE TITLE
Invalid argument(s): `Unknown` is not one of the supported values: Failed, Canceled, Timeout.

### ISSUE THREAD

**Issue by AhmedAttia3** [flutter-stripe/flutter_stripe#1723]
**Exception: Invalid argument(s): Unknown is not one of the supported values**
**Description**
I encountered an exception when making a payment using Apple Pay. This exception does not occur in test mode. It appears to happen intermittently and we have been unable to reproduce the issue ourselves. However, it consistently appears in our Firebase Crashlytics reports.

**Stack Trace**
Here's the stack trace from Firebase Crashlytics:

Invalid argument(s): `Unknown` is not one of the supported values: Failed, Canceled, Timeout.
Fatal Exception: FlutterError
0  ???                            0x0 (null).$enumDecode + 83 (enum_helpers.dart:83)
1  ???                            0x0 (null)._$$LocalizedErrorMessageImplFromJson + 39 (errors.g.dart:39)
2  ???                            0x0 new _$LocalizedErrorMessageImpl.fromJson + 516 (errors.freezed.dart:516)
3  ???                            0x0 (null)._$LocalizedErrorMessageFromJson + 343 (errors.freezed.dart:343)
4  ???                            0x0 new LocalizedErrorMessage.fromJson + 73 (errors.dart:73)
5  ???                            0x0 (null)._$$StripeExceptionImplFromJson + 27 (errors.g.dart:27)
6  ???                            0x0 new _$StripeExceptionImpl.fromJson + 286 (errors.freezed.dart:286)
7  ???                            0x0 (null)._$StripeExceptionFromJson + 187 (errors.freezed.dart:187)
8  ???                            0x0 new StripeException.fromJson + 44 (errors.dart:44)
9  ???                            0x0 ResultParser.parseError + 21 (result_parser.dart:21)
10 ???                            0x0 ResultParser.parse + 16 (result_parser.dart:16)
11 ???                            0x0 MethodChannelStripe.retrievePaymentIntent + 186 (method_channel_stripe.dart:186)
12 ???                            0x0 Stripe.retrievePaymentIntent + 309 (stripe.dart:309)
13 ???                            0x0 PaymentCubit._pay + 118 (payment_cubit.dart:118)
14 ???                            0x0 PaymentCubit.payWithApple + 67 (payment_cubit.dart:67)

**Steps to Reproduce**
Unfortunately, we have not been able to consistently reproduce the issue ourselves. The issue occurs sporadically when a user attempts to make a payment using Apple Pay and we always get the error via Firebase carshlytics.

Expected Behavior
We expect that payments using Apple Pay should proceed smoothly without any exceptions.

Actual Behavior
The exception occurs intermittently, causing the payment process to fail.

**Environment**
Flutter version: 3.19.1
Stripe package version: 10.1.0
Apple device model: iPhone 12 Pro Max
iOS version: 17.4.1

**Additional Information**
The exception occurs during calling this functions:
 _stripe.retrievePaymentIntent(paymentIntent);

**Comment by AhmedAttia3** [comment]
Hey @jamesblasco,

Apologies for the oversight, but there's something I forgot to mention in the issue description.

Invalid argument(s): Unknown is not one of the supported values: Failed, Canceled, Timeout.

This issue arises after funds have already been deducted from the user, resulting in an incomplete order. Subsequently, users reach out to our customer service, reporting the deduction without completion of their order.

Upon investigation, we've found that payments were successfully processed via Apple Pay according to the Stripe dashboard. However, Firebase Crashlytics indicates the presence of this error.

![image](https://github.com/flutter-stripe/flutter_stripe/assets/36775916/d07f39d0-0a49-44d4-bad5-8e60c09bb60b)

![image](https://github.com/flutter-stripe/flutter_stripe/assets/36775916/69404be3-4f29-4c48-bf85-e0210431198d)

Although I've observed the solution proposed in PR #1729, I'm concerned it may not fully resolve the issue.

**Comment by jamesblasco** [comment]
Hi @AhmedAttia3, the `Invalid argument(s): Unknown is not one of the supported values: Failed, Canceled, Timeout.` bug is a failure on the flutter parsing.  The native layer is returning an error we do not parse correctly on the dart side because the iOS enum `ErrorType.Uknown` does not have its correspondent class in dart. The MR should solve this issue.

For your case of Apple Payment failing with an error but the payment being process,  I would recommend to try to reproduce the error with this fix so it gives you more information about what was the reason of the failure.  It could be a configuration issue or a possible bug in the native layer. Once there is more information feel free to create a new issue so we can investigate that other possible bug.
