### ISSUE TITLE
Web Stripe guide

### ISSUE THREAD

**Issue by TetrixGauss** [flutter-stripe/flutter_stripe#1724]
Hello there!

Does anyone know a good tutorial with all the steps that need to be done for the flutter web to be working perfectly with stripe? 

Thank you in advance

**Comment by jamesblasco** [comment]
Hi currently we do not have tutorials with guided steps. I recommend you to look at our example app where you can see easy examples of every feature that is supported by the web library:

<img width="1355" alt="Screenshot 2024-04-21 at 11 25 16" src="https://github.com/flutter-stripe/flutter_stripe/assets/19904063/05c718fe-3caa-4711-a1d2-10a28f75a6e8">
