### ISSUE TITLE
PaymentConfiguration was not initialized. Call PaymentConfiguration.init()

### ISSUE THREAD

**Issue by VictorUvarov** [flutter-stripe/flutter_stripe#1727]
**Describe the bug**
I found this while testing android in production with the card field. Do I need to initialize the `CardField`?
```java
Fatal Exception: java.lang.IllegalStateException: PaymentConfiguration was not initialized. Call PaymentConfiguration.init().
       at fj.s$a.c(SourceFile:1)
       at fj.s$a.a(SourceFile:1)
       at com.stripe.android.view.b1$b.d(SourceFile:1)
       at com.stripe.android.view.b1$b.c(SourceFile:1)
       at com.stripe.android.view.c1.get(SourceFile:1)
       at com.stripe.android.view.b1.j(SourceFile:1)
       at com.stripe.android.view.b1.h(SourceFile:1)
       at com.stripe.android.view.b1$a.invokeSuspend(:42)
       at kotlin.coroutines.jvm.internal.a.resumeWith(:11)
       at qt.y0.run(SourceFile:1)
       at vt.o$a.run(SourceFile:1)
       at xt.k.run(SourceFile:1)
       at xt.a.v(SourceFile:1)
       at xt.a$c.d(SourceFile:1)
       at xt.a$c.p(SourceFile:1)
       at xt.a$c.run(SourceFile:1)
```

**To Reproduce**
1. Enter credit card in card field
2. Create token
```dart
final token = await Stripe.instance.createToken(
      CreateTokenParams.card(
        params: CardTokenParams(name: name),
      ),
    );
```
3. Crash

**Expected behavior**

**Smartphone / tablet**
 - Device: [Pixel 4]
 - OS: [Android 13]
 - Package version: [10.1.1]
 - Flutter version [Channel stable, 3.19.5]

**Additional context**

**Comment by jamesblasco** [comment]
Hi @VictorUvarov, I can not manage to reproduce the issue. Could you provide a more detail example that I can run?

I suppose you set the `publishableKey` before right?

`PaymentConfiguration` is a native object that gets initialised when you set the `publishableKey`.

**Comment by VictorUvarov** [comment]
I was able to resolve the issue by calling apply settings.

**Comment by ibrahimtelman** [comment]
@VictorUvarov How did you resolve the issue? I encountered the same problem after upgrading the package version.

**Comment by VictorUvarov** [comment]
> @VictorUvarov How did you resolve the issue? I encountered the same problem after upgrading the package version.

There is a static apply settings method on the stripe class

**Comment by QuocTA-Amela** [comment]
@VictorUvarov can you elaborate or do you have any example code of where to fix this? Thank you

**Comment by VictorUvarov** [comment]
> @VictorUvarov can you elaborate or do you have any example code of where to fix this? Thank you

https://github.com/flutter-stripe/flutter_stripe/blob/main/example/lib/main.dart#L12C3-L12C41

**Comment by Erastoh** [comment]
I Made these changes to my code and it fixed the error.
  
  @override
  void initState(){
     Stripe.publishableKey = stripeTokensModel.stripePublishableKey;
    stripeCall();
    super.initState();
  }

  stripeCall() async {
    Stripe.merchantIdentifier = 'merchant.flutter.stripe.test';
    Stripe.urlScheme = 'flutterstripe';
    await Stripe.instance.applySettings();
  }
