### ISSUE TITLE
Blank White Screen on Android and iOS after Payment,

### ISSUE THREAD

**Issue by tailoristic** [flutter-stripe/flutter_stripe#1737]
**To Reproduce**
1. Entering number 4242 4242 4242 4242 into the cardfield.
2. Do the payment
3. And then it shows white screen and nothing happens after that

**Expected behavior**
Response  should come back to mobile but instead showing white screen.

**Smartphone / tablet**
 - Device: [e.g. iPhone 15 pro]
 - OS: [e.g. iOS 17, Android 13]
 - Package version: Latest
 - Flutter version 3.19.5

**Comment by jonasbark** [comment]
Please create a video and ideally a reproducible example
