### ISSUE TITLE
Payment sheet close as soon as it opens up.

### ISSUE THREAD

**Issue by jaiswalshubham84** [flutter-stripe/flutter_stripe#174]
I have a use case in which whatever user pays for the product, it will directly go out to merchant's account by deducting some application fee on top of it.
After reading the stripe documentation, I found that this can be done via using connected account, which I already set it up in stripe dashboard.

Now to complete the transaction first i am creating payment intent from my node server. and once payment intent is created, then by using paymentIntent client_secret, i am initializing and presenting the payment sheet in my flutter app.  

I am doing like this
In my **node server** in intent creation code I use the below lines of code and able to generate payment id successfully.

```
async function createIntent(res)
    await stripe.paymentIntents.create(
        {
            payment_method_types: ['card'],
            amount: 1000,
            currency: 'usd',
            application_fee_amount: 123,
        }, {
        stripeAccount: 'acct_1Jxxxxxxxxxx',
    },
        function (err, paymentIntent) {
            if (err != null) {
                console.log(err)
            } else {
                res.json({
                    paymentIntent: paymentIntent.client_secret
                })
            }
        })
        }

```
   **In my flutter app**
    
     GestureDetector(
            child:Container(
               height: 60,
             width: 300,              
              child: Center(child: 
              Text("make Payment"))),
            onTap: ()async{
              await Stripe.instance.initPaymentSheet(paymentSheetParameters: SetupPaymentSheetParameters(
                paymentIntentClientSecret:'pi_1J8R8MITRt0rxxxxxx_secret_6y3hP52m4AsWkxxxxxxx',
                 ));
                 setState(() {
                   
                 });
                 displatPaymentSheet();
            },
        ),
        
        
         displatPaymentSheet()async{
               await Stripe.instance.presentPaymentSheet(
               parameters: PresentPaymentSheetParameters(
               clientSecret: 'pi_1J8R8MITRt0rq72iYxxxxxx_secret_6y3hP52m4AsWkq2rYxxxxx',
               confirmPayment: true
    ));}

when I try to execute the payment sheet in my app, it opens up the sheet the then suddenly closed it out.

Although when I removed `stripeAccount`  parameter from the node server code and generated Id then it works and it successfully opens up the sheet and I am also able to complete the payment.

Any idea where I am doing wrong.
Thanks in advance

**Comment by manda95** [comment]
I have the same problem.
The connected account is a test account with status "Enabled" on the Stripe Dashboard. 

This is the stack trace thrown by the library:

`E/flutter ( 4541): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(Failed, , null, null)
E/flutter ( 4541): #0      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:155:7)
E/flutter ( 4541): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
E/flutter ( 4541): <asynchronous suspension>
E/flutter ( 4541): #2      MethodChannelStripe.presentPaymentSheet (package:stripe_platform_interface/src/method_channel_stripe.dart:181:5)
E/flutter ( 4541): <asynchronous suspension>
E/flutter ( 4541): #3      Stripe.presentPaymentSheet (package:flutter_stripe/src/stripe.dart:268:5)
E/flutter ( 4541): <asynchronous suspension>
E/flutter ( 4541): #4      PaymentCubit.paymentWithCardClicked (package:user_ui/bloc/payment/payment_cubit.dart:53:7)
E/flutter ( 4541): <asynchronous suspension>`

**Comment by manda95** [comment]
After debugging the file

stripe_android-1.0.2/android/src/main/kotlin/com/reactnativestripesdk/PaymentSheetFragment.kt

on line 61, paymentResult.error is:

`StripeError(
type=invalid_request_error,
message=Resource payment_intent not found: 'pi_1J96uU****n5uOwE',
code=resource_missing,
param=intent,
declineCode=null,
charge=null,
`docUrl=https://stripe.com/docs/error-codes/resource-missing)`

maybe because the payment intent belongs to the connected account, as the way was created on the server.

I found this issue, which describe the problem: [https://github.com/stripe/stripe-node/issues/636](url)

**[This comment](https://github.com/stripe/stripe-node/issues/636#issuecomment-526344989) suggest that on the client side should be added the ACCOUNT_ID information;**

Following [this comment](https://github.com/stripe/stripe-node/issues/636#issuecomment-539068717), and reading [this page](https://stripe.com/docs/payments/connected-accounts) (the link on the comment is outdated), now it seems to work without modify the client-side:

`const paymentIntent = await stripe.paymentIntents.create({
            amount: +ordination.price * 100,
            currency: 'eur', on_behalf_of: 'acct_1J933*****U0T', transfer_data: {
                destination: 'acct_1J933*****U0T',
            },
        },);`

hope it helps

**Comment by jaiswalshubham84** [comment]
@manda95 
Thanks for commenting. 
The solution you provided also worked for me.

**Comment by manda95** [comment]
> After debugging the file
> 
> stripe_android-1.0.2/android/src/main/kotlin/com/reactnativestripesdk/PaymentSheetFragment.kt
> 
> on line 61, paymentResult.error is:
> 
> `StripeError( type=invalid_request_error, message=Resource payment_intent not found: 'pi_1J96uU****n5uOwE', code=resource_missing, param=intent, declineCode=null, charge=null, `docUrl=[https://stripe.com/docs/error-codes/resource-missing)`](https://stripe.com/docs/error-codes/resource-missing)%60)
> 
> maybe because the payment intent belongs to the connected account, as the way was created on the server.
> 
> I found this issue, which describe the problem: [https://github.com/stripe/stripe-node/issues/636](url)
> 
> **[This comment](https://github.com/stripe/stripe-node/issues/636#issuecomment-526344989) suggest that on the client side should be added the ACCOUNT_ID information;**
> 
> Following [this comment](https://github.com/stripe/stripe-node/issues/636#issuecomment-539068717), and reading [this page](https://stripe.com/docs/payments/connected-accounts) (the link on the comment is outdated), now it seems to work without modify the client-side:
> 
> `const paymentIntent = await stripe.paymentIntents.create({ amount: +ordination.price * 100, currency: 'eur', on_behalf_of: 'acct_1J933*****U0T', transfer_data: { destination: 'acct_1J933*****U0T', }, },);`
> 
> hope it helps

The problem of this approach is that the stripe fee for the transfer is charged by the main account, and not to the connected account, which will receive the full payment; so the main account will pay the taxes.

e.g:

![image](https://user-images.githubusercontent.com/59965348/125161831-d2975d80-e184-11eb-8413-3120167658f8.png)

the user pay €5.00, the connected account will receive €5.00, and the main account pay in his balance €0.60 (stripe fee)

Any idea on how to solve this?

**Comment by remonh87** [comment]
I think with #199  we improve the error messaging of the paymentsheet, this is the only thing that we can do for you as a plugin.  For the rest of the problem I think it is good to ask stripe customer service on how to do this.  I will close it for now  but feel free to reopen it if you still do not get proper feedback.

**Comment by jaiswalshubham84** [comment]
@remonh87 @manda95 
I found one solution to it.
If you initialize stripeAccountId before initializing payment then it will work.
`Stripe.stripeAccountId = merchantAccount`
