### ISSUE TITLE
No method to know supported regional payment options in user's device

### ISSUE THREAD

**Issue by yashpalzala** [flutter-stripe/flutter_stripe#1751]
**Describe the bug**
I want to show users regional payment options, but only those options that users can use. 
Example: CashApp is only available in US, so I don't want to show that option to any other user around the world.
Similar to `isPlatformPaySupported` for Googlepay and Applepay

**Comment by remonh87** [comment]
This is not how stripe works. The client (app) is only used to collect payment data. I would solve this the following:

- from the app send a request to server to create the payment intent. Send the locale along with it.
- In the server based on the locale you create a paymentinten in stripe where you supply desired payment methods and the locale.
- if you use the payment sheet the stripe sdk handles automatically which payment methods to supply
