### ISSUE TITLE
CardFormField

### ISSUE THREAD

**Issue by HiZafeer** [flutter-stripe/flutter_stripe#1753]
Hello,

I am encountering an issue with the CardFormField in the flutter_stripe package (version 9.6.0). Despite setting the enablePostalCode to false, the postal code field is still visible and active in the form.

Environment:

flutter_stripe version: 9.6.0
Flutter SDK version: 3.16.8
Code Snippet:

CardFormField(
  enablePostalCode: false,
  controller: CardFormEditController(),
)

**Comment by remonh87** [comment]
did you try it on iOS ? because that is not working for the cardformfield.  I improved the docs
