### ISSUE TITLE
Payment Sheet on IOS: StripeUICore/ImageMaker.swift:51: Assertion failed: Failed to find an image named icon_x_standalone

### ISSUE THREAD

**Issue by SportApps** [flutter-stripe/flutter_stripe#1765]
**Describe the bug**
When opening the payment sheet on IOS iPhone 15 and iPhone 13 (tested on both), the app crashes and closes. The only error log I get is: StripeUICore/ImageMaker.swift:51: Assertion failed: Failed to find an image named icon_x_standalone

[✓] Flutter (Channel stable, 3.19.6, on macOS 14.4.1 23E224 darwin-arm64, locale en-ES)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] VS Code (version 1.87.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

and Flutter Stripe version  flutter_stripe: ^10.1.1. 

Tried Cleaning pods and pods cache, flutter clean, all the basics. Doesnt work neightor on emulator nor real device. 

**To Reproduce**
1. Opening a payment sheet on I phone

**Expected behavior**
The payment sheet to open

**Smartphone / tablet**
 - Device: Iphone 13 and 15

**Additional context**
On Android it works well. 

<img width="995" alt="image" src="https://github.com/flutter-stripe/flutter_stripe/assets/65491729/682c2b8b-63cf-40a9-8084-dc61f5ca1fca">

<img width="527" alt="image" src="https://github.com/flutter-stripe/flutter_stripe/assets/65491729/1bc0f2e8-a052-4783-82e1-a7797ca2163a">

**Comment by remonh87** [comment]
is the deployment target set to 13.0 and higher? else I need a reproducible scenario as a repo where I can try it.

**Comment by SportApps** [comment]
> is the deployment target set to 13.0 and higher? else I need a reproducible scenario as a repo where I can try it.

Correct, it's set to 13.0. Flutter clean , pod deintegrate  etc has been executed several times.

**Comment by SportApps** [comment]
I just updated flutter to 3.22.0, but the same error persists.


-v
[✓] Flutter (Channel stable, 3.22.0, on macOS 14.4.1 23E224 darwin-arm64, locale en-ES)
    • Flutter version 3.22.0 on channel stable at /Users/timknogel/FlutterDev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5dcb86f68f (9 days ago), 2024-05-09 07:39:20 -0500
    • Engine revision f6344b75dc
    • Dart version 3.4.0
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/timknogel/Library/Android/sdk
    • Platform android-34, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.89.1)
    • VS Code at /Users/timknogel/Desktop/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

**Comment by remonh87** [comment]
I fear I need a reproduction example. Can you try using our example app and see if the problem persists?
