### ISSUE TITLE
Android GMS service disabled  prevent payment sheet displaying correctly

### ISSUE THREAD

**Issue by LWFLBB** [flutter-stripe/flutter_stripe#1767]
Describe the bug
If the GMS service is disabled on my phone, the payment form displays an error and is always loading. The relevant information is as follows：

Flutter 3.16.16
Android 34
flutter_stripe: ^10.1.1
device: redmi note 12 turbo

![img_v3_02ap_e38c9913-1f7a-4cf2-99bb-6e5e5c9ada8g](https://github.com/flutter-stripe/flutter_stripe/assets/16347796/19da6cb9-8fa2-419d-b16d-d85392b0252d)

<img width="556" alt="image" src="https://github.com/flutter-stripe/flutter_stripe/assets/16347796/e7c95c7e-456a-47fd-ba5e-c1b51d850e1a">

![7Z5EyzItFX](https://github.com/flutter-stripe/flutter_stripe/assets/16347796/4dbcadcf-563c-47c6-9e83-0729e045e7f1)

<img width="588" alt="image" src="https://github.com/flutter-stripe/flutter_stripe/assets/16347796/cabe1241-9ee7-49e2-be0f-af3f28daee20">

**Comment by remonh87** [comment]
Thanks for reporting. This is an error outside the stripe sdk and it is a decision that google made. However it is a valid bug and you are right to report this there is not much I can do about it.
