### ISSUE TITLE
[Flutter Web] handleNextAction returns Unexpected null value

### ISSUE THREAD

**Issue by mirafiorielia** [flutter-stripe/flutter_stripe#1768]
**Describe the bug**
While creating a payment intent on Flutter Web and retrieving successfully its client_secret from my backend, when I rung Stripe.instance.handleNextAction(clientSecret) to check the status of the intent, Stripe throws the following error:

`Unexpected null value`

**To Reproduce**
1. Use Flutter Web
2. Add to pubspec: `flutter_stripe` and `flutter_stripe_web`
3. Create a payment method and get its ID
4. Create a payment intent on your backend and get the `client_secret`
5. Pass the `client_secret` to `Stripe.instance.handleNextAction`

**Expected behavior**
I expected to get the PaymentIntent associated to the `client_secret` retrieved above.
But instead I get the error `Unexpected null value`.

The `client_secret` passed is not null, it's a `String`.

**PC / Chrome**
 - Device: PC
 - OS: Win 11
 - Package version: `flutter_stripe: ^10.1.1`
 - Package version: `flutter_stripe_web: ^5.1.0`
 - Flutter version: 3.16.9

**Comment by guidotheelen** [comment]
Also facing this issue:
https://github.com/flutter-stripe/flutter_stripe/issues/1746
