### ISSUE TITLE
errors during "npm install" in the server folder for the example app

### ISSUE THREAD

**Issue by graemep-nz** [flutter-stripe/flutter_stripe#1769]
As described in the instructions for the example app I ran "npm install" in the server folder and got the following errors

code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: eslint-plugin-jest@24.7.0
npm ERR! Found: @typescript-eslint/eslint-plugin@2.34.0
npm ERR! node_modules/@typescript-eslint/eslint-plugin
npm ERR!   dev @typescript-eslint/eslint-plugin@"^2.21.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peerOptional @typescript-eslint/eslint-plugin@">= 4" from eslint-plugin-jest@24.7.0
npm ERR! node_modules/eslint-plugin-jest
npm ERR!   eslint-plugin-jest@"^24.1.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @typescript-eslint/eslint-plugin@7.8.0
npm ERR! node_modules/@typescript-eslint/eslint-plugin
npm ERR!   peerOptional @typescript-eslint/eslint-plugin@">= 4" from eslint-plugin-jest@24.7.0
npm ERR!   node_modules/eslint-plugin-jest
npm ERR!     eslint-plugin-jest@"^24.1.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by remonh87** [comment]
what is your node version?

**Comment by graemep-nz** [comment]
v20.11.1

**Comment by vietstone-ng** [comment]
Same problem. My node version is v21.5.0.

**Comment by remonh87** [comment]
can you use node 19 for our project ?

**Comment by vietstone-ng** [comment]
@remonh87 it happens with node 16 -> 21 as I tried. But it runs with the `--force` flag.

**Comment by remonh87** [comment]
and if you use the yarn command?

**Comment by grafst** [comment]
also doesn't work with node19 and --force on my machine
