### ISSUE TITLE
No docs for apple pay customer sheet flow

### ISSUE THREAD

**Issue by JSBmanD** [flutter-stripe/flutter_stripe#1770]
**Describe the bug**
I have integrated customer sheet (mobile elements) into my app. And I want to use Apple Pay. I choose apple pay in this sheet and future returns me that I've selected apple pay as payment method (for Google Pay should be the same). So after this how I need to proceed with payment that is made in future in my app?

**To Reproduce**
1. Present mobile element customer sheet
2. Select apple pay

**Expected behavior**
Should be documented how to proceed further with the payment

**Smartphone / tablet**
 - Device: any ios
 - OS: IOS 17.4
 - Package version: 10.1.1
 - Flutter version 3.19.0

**Comment by remonh87** [comment]
I gues you mean the paymentsheet? The customer sheet is not to be used for doing payments but only for managing saved payment methods. Related to the payment sheet we have documentation: https://docs.page/flutter-stripe/flutter_stripe/sheet

**Comment by JSBmanD** [comment]
@remonh87 I save payment method with https://docs.page/flutter-stripe/flutter_stripe/customer_sheet
And then as I see in official Stripe docs I need to call payment with apple pay. I don't see it covered anywhere

**Comment by JSBmanD** [comment]
@remonh87 I save payment method with https://docs.page/flutter-stripe/flutter_stripe/customer_sheet
And then as I see in official Stripe docs I need to call payment with apple pay. I don't see it covered anywhere

**Comment by remonh87** [comment]
yes exactly customer sheet is for customers to manage their payments and paymentsheet is for paying. To be honest I am not super happy with the choice that stripe made here as it can be quite confusing

**Comment by JSBmanD** [comment]
@remonh87 so I see now 2 methods - confirmPlatformPaySetupIntent and confirmPlatformPayPaymentIntent. When I need to use each one? They have the different usage description.

**Comment by JSBmanD** [comment]
Using setup intent (not payment) I'm getting the same error from Stripe - You must provide merchantIdentifier. No merchant id in method btw.

**Comment by JSBmanD** [comment]
Got it working.
1. Call customer sheet
2. Customer selects Apple Pay
3. We take result and check if it's Apple Pay
4. We call Stripe.instance.confirmPlatformPaySetupIntent with item in cart with 0 cost
5. In result we have payment method id

**Comment by remonh87** [comment]
so cartitems are required by apple as you are forced to display something in the apple pay sheet.  Docs are bit fragmented but this is a good way to start: https://developer.apple.com/design/human-interface-guidelines/apple-pay/

Maybe a simpler way for your usecase is using the paymentsheet. If you use a customer key and a ephermal key it will automatically preselect last used payment. I propose to close this ticket now
