### ISSUE TITLE
Apple Pay wallet displays wrong currency

### ISSUE THREAD

**Issue by shapeshiftersApp** [flutter-stripe/flutter_stripe#1772]
**Describe the bug**
I need to implement a subscription with free trial. I want to charge customer after free trial ends. For that I use SetupIntent. Whole workflow works as expected and user is charged after free trial. My problem is that Apple Pay sheet shows USD instead of Euro.

**To Reproduce**
1. Create SetupIntent.
2.  Init payment sheet with SetupIntentClientSecret
4. Open mobile payment sheet
5. Select ApplePay
6. See the price in USD

![unnamed (2)](https://github.com/flutter-stripe/flutter_stripe/assets/115003669/c724a9c4-001f-4d99-ac4f-99d4977e3f60)

**Expected behavior**
Apple payment sheet should display EUR as currency

**Smartphone / tablet**
 - Device: IPhone 14 Pro
 - OS: IOS 17.4.1
 - Package version:. 10.0.0
 - Flutter version 3.19.5

**Additional context**
I tried searching Git issues and I found out that it is not supported https://github.com/stripe/stripe-react-native/issues/1333
This link is for React Native extension, but I am using Flutter extension: https://pub.dev/packages/flutter_stripe

**Comment by rascafr** [comment]
Hi @shapeshiftersApp, sorry for asking this 2 years later... I'm facing the exact same issue, did you had any chance finding a workaround?
