### ISSUE TITLE
[example][server] Lack of session id in create-checkout-session endpoint

### ISSUE THREAD

**Issue by vietstone-ng** [flutter-stripe/flutter_stripe#1776]
Hello,

When I run the `example` app, there's an exception with checkout
`Unhandled Exception: type 'Null' is not a subtype of type 'String' in type cast`

The exception happens in file `checkout_screen.dart`,  function `_createCheckoutSession`, line 
```
final id = bodyResponse['id'] as String;
```

That is because the response from `create-checkout-session` endpoint, which is defined in `index.ts` lack of `id`.
Below is the response
```
  res.json({
    customer: customer.id,
    ephemeralKeySecret: ephemeralKey.secret,
    setupIntent: setupIntent.client_secret,
  });
```
Because I'm new to Stripe so I don't know how to overcome this. Please help. Thank you.

**Comment by remonh87** [comment]
checkout has been deprecated and we should remove this from the example app. reason why is explained here: https://pub.dev/packages/stripe_checkout . You can still use checkout but it fully works with the backend and outside of our package. Will keep it open for us to remove the code from example app

**Comment by vietstone-ng** [comment]
@remonh87 Thank you for letting me know. I can setup incomplete Subscription, then gather payment information by Elements.
Just curious what does this mean: "checkout now only relies on backend code to work" as reason in https://pub.dev/packages/stripe_checkout?. I think to use Elements, the subscription also needs to be created in backend.
And for normal web, I see many services use Checkout UI for they payment page. Is this mean they need to migrate Checkout to Elements?
Thank you!

**Comment by vietstone-ng** [comment]
For anyone has doubt as me on Checkout deprecation. It's not Checkout deprecation, but only the function `redirectToCheckout`. We can now use Checkout without `redirectToCheckout`. After the checkout session is created with `create-checkout-session`, there's a url property that you can use to open the checkout page directly.

**Comment by remonh87** [comment]
yes exactly it is just deprecation of the package 👍  thanks for clarifying this
