### ISSUE TITLE
Update js dependency version from 0.6.3 to 0.7.1

### ISSUE THREAD

**Issue by AristideVB** [flutter-stripe/flutter_stripe#1780]
**Is your feature request related to a problem? (please describe)**

js version is ^0.6.3, it needs to be updated to `^0.7.1` or this package pins the js version and blocks updates to other packages.

**Describe the solution you'd like**

I propose updating the js dependency in the flutter_stripe package from version 0.6.3 to 0.7.1.

**Describe alternatives you've considered**

We considered using the dependency_overrides in our pubspec.yaml to force the version to 0.7.1:

```yaml
dependency_overrides:
  js: ^0.7.1
 ```
However, this approach is not safe for production, especially in our Flutter Web environment, as it might lead to unexpected behavior

**Comment by jamesblasco** [comment]
Hi @AristideVB, the `^` syntax means that a you are allowed to use any version between that one and the next mayor version. The equivalent from  `^0.6.3` is  `>=0.6.3 <1.0.0`.

Either way we are moving away from `js` library to migrate to the new js interoperability.
You can give it a try by using `flutter_stripe_web: ^6.0.0-dev.0`

**Comment by AristideVB** [comment]
Hi @jamesblasco  thanks for your response!

Just to clarify, in Dart and Flutter, the caret (`^`) **for versions below `1.0.0`** like `^0.6.3` means `>=0.6.3 <0.7.0`. This is why there's a conflict with dependencies expecting versions `^0.7.1`. For this reason, I'd appreciate it if you could review and merge my PR which addresses this versioning issue.

Thanks for considering this!

**Comment by AristideVB** [comment]
You can read more about it here https://dart.dev/tools/pub/versioning

> Although semantic versioning doesn't promise any compatibility between versions prior to 1.0.0, the Dart community convention is to treat those versions semantically as well. The interpretation of each number is just shifted down one slot: going from 0.1.2 to 0.2.0 indicates a breaking change, going to 0.1.3 indicates a new feature, and going to 0.1.2+1 indicates a change that doesn't affect the public API. For simplicity's sake, avoid using + after the version reaches 1.0.0.
