### ISSUE TITLE
Unable to determine Payment Status

### ISSUE THREAD

**Issue by jeremiahseun** [flutter-stripe/flutter_stripe#1788]
**Describe the bug**
When I click on a payment method or when I try to discard the payment sheet, I get the same response. There is no difference whether I pay or cancel the transaction.
I have done research on how they handle canceled payments, but I couldn't find a workable solution.

**To Reproduce**
1. Initialize the payment sheet
2. Call the presentPaymentSheet function to show the payment sheet.
3. After the sheet shows up, click on the close button.
4. Observe the console, it is not throwing any exceptions.

**Expected behavior**
What I expect is in two ways:
- Let the presentPaymentSheet return the payment status (that exists in the ErrorCode Class)
- When it is canceled, let the exception be called.

**Smartphone / tablet**
 - Device: iPhone SE (2nd generation)
 - OS: iOS 17.2
 - Package version: 10.1.1
 - Flutter version 3.22.0 • channel stable

**Additional context**
Here is a video explaining what I am facing.

https://github.com/flutter-stripe/flutter_stripe/assets/53568423/591d0fa3-1cb6-40f1-875f-b79c7d865abd

**Comment by jeremiahseun** [comment]
## Here is my latest code:

```dart
 static Future<bool> _showPaymentSheet({
    required BuildContext context,
  }) async {
    try {
      // 3. display the payment sheet.
      final res = await Stripe.instance
          .presentPaymentSheet()
          .then((val) {})
          .onError((error, stackTrace) {
        log("There is an error: ${error.toString()}");
        throw Exception(error);
      });
      log("Response label of confirm payment sheet => ${res?.toJson()}");
      if (!context.mounted) return true;
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Payment successfully...'),
        ),
      );
      return true;
    } on StripeException catch (e) {
      // if (e is StripeException) {
      log("Making/Confirming payment code ${e.error.code.name}");
      log("Making/Confirming payment localized message ${e.error.localizedMessage}");
      log("Making/Confirming payment message ${e.error.message}");
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Error from Stripe: ${e.error.localizedMessage}'),
        ),
      );
      return false;
    } catch (e) {
      print('Catching $e');
      return false;
    }
  }
```

### The response is always the same:
```
{label: Apple Pay, image: iVBORw0KGgoAAAANSUh...}
```

**Comment by jeremiahseun** [comment]
I realized that the reason I was having the issue is because I set `customFlow: true`, that is why it wasn't throwing anything in the exception.

When I did `customFlow: false`, it worked fine. I was able to see the Exception work fine.

Thank you.

**Comment by esentis** [comment]
@jeremiahseun Ok, but what if you still want to know whether the user has closed the sheet  in `customFlow:true`?

**Comment by esentis** [comment]
@jeremiahseun Yes, I was afraid so.
