### ISSUE TITLE
Creating a bank account and receiving a token

### ISSUE THREAD

**Issue by Raphicci** [flutter-stripe/flutter_stripe#179]
I'm currently using flutter_stripe_payment package in order to register a bank account and receive a token, for receiving later payments on an account (using their method "createTokenWithBankAccount") and wanted to migrate to this package,  forced by outdated stripe plugin versions.

As stated in their migration guide ([here](https://github.com/jonasbark/flutter_stripe_payment/blob/master/migration.md)) i should be using "createPaymentMethod", but this method doesn't seem to handle my particular case.

So i was wondering if there is any plan to implement the stripe API to create a bank account and receive a token for it in the near future of this package ?

What i am referring to is this particular stripe [API call](https://stripe.com/docs/api/tokens/create_bank_account) handling IBAN and other forms of bank accounts information.

**Comment by jonasbark** [comment]
Thanks for the hint - unfortunately we have forgotten about adding other token types apart from Card.

cc @remonh87  https://github.com/stripe/stripe-react-native/blob/master/src/types/Card.ts#L61

**Comment by Raphicci** [comment]
My company will need this feature ASAP so i thought i could help you by creating a PR for it, do you have any guidelines / interfaces in mind to implement this and contribute ?

**Comment by remonh87** [comment]
@jonasbark  I added the dart bindings for bankaccount already but it was not yet supported in the react-native bindings at the version we integrated. I noticed bankaccount is not yet supported in react native https://github.com/stripe/stripe-react-native/blob/2b8fdd8d6634662bcd03ec01be32a7ce4c72e914/src/functions.ts#L52 . @thorsten-stripe  can you confirm?

**Comment by leochiu-work** [comment]
Hi @remonh87 , may I ask if there is any update on this feature?   Thanks

**Comment by jamesblasco** [comment]
We are blocked by this: https://github.com/stripe/stripe-react-native/issues/464

**Comment by remonh87** [comment]
This functionality is available in v1.3.0.
