### ISSUE TITLE
ApplePay token makes the app literally freeze my app 

### ISSUE THREAD

**Issue by louisbdc** [flutter-stripe/flutter_stripe#1791]
Hello,

I am trying to add applePay. I use my Iphone 14 pro (128gb) because on simulator it doesn't work.
And the app freeze because of this line below (line 221):
```dart
 TokenData tokenResult = await Stripe.instance.createApplePayToken(paymentMethod.toJson());
```

I did put a print before and after the line, of course the first line is displayed and not the second.

just after is my api call to the server, but the code doen't reach it !
And I need the token because i don't handle the backend

[Link to the quick video where you can see my problem](https://youtube.com/shorts/rzB0_PJLs_Y?feature=share)

<img width="661" alt="Capture d’écran 2024-06-06 à 23 21 36" src="https://github.com/flutter-stripe/flutter_stripe/assets/72014929/4cccbc06-fc47-4f83-a4ab-380325b9fbe0">

**Comment by remonh87** [comment]
you stil need to confirm the payment intent. 

```dart

    final params = PaymentMethodParams.cardFromToken(
        paymentMethodData: PaymentMethodDataCardFromToken(
          token: token.id,
        ),
      );

      // 3. Confirm Apple pay payment method
      await Stripe.instance.confirmPayment(
        paymentIntentClientSecret: clientSecret,
        data: params,
      );

```
