### ISSUE TITLE
[Web] CardField displaying as blank input

### ISSUE THREAD

**Issue by guidotheelen** [flutter-stripe/flutter_stripe#1792]
I'm getting an `UnimplementedError()` error when building the `CardField` or `CardFormField` on Web.

Browser: 
Chrome - Version 125.0.6422.142 (Official Build) (arm64)

Package version: 
flutter_stripe: 10.0.0
flutter_stripe_web: 5.1.0

Flutter version: 
3.19.6

What are the plans for implementing these widgets?

**Comment by guidotheelen** [comment]
`CardField` is not throwing an `UnimplementedError()`
But instead displaying as a unresponsive blank input:
<img width="441" alt="image" src="https://github.com/flutter-stripe/flutter_stripe/assets/9211107/c0f17511-e5bf-48d5-91ea-f773fa3da78c">

**Comment by jamesblasco** [comment]
Hi @guidotheelen, CardField is implemented for Flutter Web. There is no Stripe CardFormField component in their js sdk so we can not implement it either. 

Make sure you have added both dependencies to your project and build it again. Is there any other error besides UnimplementedError?

You can see the example project:
<img width="500" alt="Screenshot 2024-06-09 at 13 53 42" src="https://github.com/flutter-stripe/flutter_stripe/assets/19904063/340b8989-aaa0-43df-9dfe-d05334d2b193">

**Comment by guidotheelen** [comment]
Thanks for reaching out @jamesblasco!
I added both dependencies but it's still blank.

Could this warning in the console have anything to do with it?

```
js_util_patch.dart:110 
Height of Platform View type: [stripe_card] may not be set. Defaulting to `height: 100%`.
Set `style.height` to any appropriate value to stop this message.
```

**Comment by guidotheelen** [comment]
Just tried the `CardField` in a new Flutter project. This gives the same result...

```
Flutter 3.19.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 54e66469a9 (8 weeks ago) • 2024-04-17 13:08:03 -0700
Engine • revision c4cd48e186
Tools • Dart 3.3.4 • DevTools 2.31.1
```

**Comment by guidotheelen** [comment]
@jamesblasco @remonh87 Do you have any clue on what's causing this issue?

**Comment by marwfair** [comment]
I am experiencing the same issue. `CardField` is working fine for me locally, but is blank when deployed. I see the warnings in both environments.

**Comment by Virenvkj** [comment]
hi @guidotheelen ,

 I am experiencing the same issue and its quite a blocker now. This error severely obstructs the functionality of our application, rendering crucial payment features unusable on this platform.

When are we fixing it ?

**Comment by egonm12** [comment]
The card field will be blank on the web when the publishable key is not set and settings are not applied yet. If we call this before showing the `CardField` is interactable.

```
Stripe.publishableKey = stripePublishableKey;
await Stripe.instance.applySettings();
```

However, we stumbled into our next problem: the `CardFieldInputDetails` fields are `null` where we expect a value. Reproducible on the Stripe example app:

![2024-06-19 at 14 33 12](https://github.com/flutter-stripe/flutter_stripe/assets/20042349/c8916a9c-8a02-4077-8f5c-333155e53d83)

**Comment by guidotheelen** [comment]
I just tried the `PaymentElement` but the `CardFieldInputDetails` fields in the `onCardChanged` are null as well:

```
CardFieldInputDetails(
complete: false, 
last4: null, 
expiryMonth: null, 
expiryYear: null, 
postalCode: null, 
brand: null, 
number: null, 
cvc: null, 
validExpiryDate: CardValidationState.Unknown, 
validCVC: CardValidationState.Unknown, 
validNumber: CardValidationState.Unknown
)
```

@jamesblasco @remonh87 Is this a known issue?

**Comment by remonh87** [comment]
Can you try this with the new flutter_stripe plugin? we totally changed the jsinterop there.
