### ISSUE TITLE
confirmPlatformPayPaymentIntent for ApplePayCartSummaryItem.recurring always failed

### ISSUE THREAD

**Issue by ryohetoy** [flutter-stripe/flutter_stripe#1796]
**Describe the bug**
When I use `confirmPlatformPayPaymentIntent` for `ApplePayCartSummaryItem.recurring`, method always failed.
Error message is below.

`Failed to create Apple Pay summary item with label: xxx. The intervalCount item parameter is required, but none was provided.`

Of course I provided intervalCount, but it failed.

However, in the case for using `initPaymentSheet` instead of `confirmPlatformPayPaymentIntent`, it succeeded even same parameters are provided.

**To Reproduce**
Excutes the code below.

```dart
const confirmParams = PlatformPayConfirmParams.applePay(
  applePay: ApplePayParams(
    request: PaymentRequestType.recurring(
      description: 'description',
      managementUrl: 'https://example.com',
      billing: ImmediateCartSummaryItem(
        label: 'label',
        amount: '1000',
        isPending: false,
      ),
    ),
    merchantCountryCode: 'JP',
    currencyCode: 'jpy',
    cartItems: [
      ApplePayCartSummaryItem.recurring(
        label: 'label',
        amount: '1000',
        intervalUnit: ApplePayIntervalUnit.month,
        intervalCount: 1,
      ),
    ],
  ),
);

await Stripe.instance.confirmPlatformPayPaymentIntent(
  clientSecret: 'correct_secret',
  confirmParams: confirmParams,
);
```

**Expected behavior**
`confirmPlatformPayPaymentIntent` method should be succeeded.

**Smartphone / tablet**
 - Device: iPhone13 (real device)
 - OS: iOS 16.3
 - Package version: 10.1.1
 - Flutter version: 3.22.0

**Comment by jonasbark** [comment]
@remonh87 from what I can see the intervalCount parameter needs to move to the billing attribute for PaymentRequestType.recurring

**Comment by ryohetoy** [comment]
Thank you for the comment. Any update?
I cannot implement the package because of this issue.

Or, is there any workaround for this? 
I don't want to use the prebuild payment sheet because we would not like to accept credit card.

**Comment by jonasbark** [comment]
If you don't want to allow credit cards then you can specify that during payment intent creation when using PaymentSheet

**Comment by ryohetoy** [comment]
@jonasbark 
I couldn't find the way to exclude the credit card.
Could you please provide the example code for me? 
I'm using node.js for server code.
