### ISSUE TITLE
Can you please integrate Affirm?

### ISSUE THREAD

**Issue by mahimrocky** [flutter-stripe/flutter_stripe#1813]
We are using the updated version of Flutter and the stripe library. 
And we are using the backend to create payment intent "We call the payment intent method on the server side (python). Here is the implementation"
Here is the code
`def createPaymentIntent(amount, cur):
    stripe.api_key = os.getenv('STRIPE_API_KEY')    

    stripeResponse = stripe.PaymentIntent.create(
                            amount= math.floor(amount * 100),
                            currency=cur,
			    payment_method_types=['affirm']
                        )

    logger.info(f'stripeResponse: {stripeResponse}')
    return stripeResponse['client_secret']`

After getting the `client_secret` we call stripe methods

```
await Stripe.instance
        .initPaymentSheet(
      paymentSheetParameters: SetupPaymentSheetParameters(
    
       paymentIntentClientSecret: paymentIntent["client_secret"],
          style: ThemeMode.light,
          merchantDisplayName: "merchantName"),
    )
```

But the problem is when we are calling `tripe.instance.presentPaymentSheet()` then we get an error 

> None of the requested payment methods (affirm) match the supported payment types (card, klarna).

Could you please check this matter? For your information **afterPay/clearPay** also not working. Or provide any suggestion to implement affirm payment method. 

Thanks you

**Comment by remonh87** [comment]
the response is coming from stripe itself. You must enable the payment method in the stripe dashboard.  I tested affirm in the example app with my stripe account and it works.  See: https://docs.stripe.com/payments/affirm/accept-a-payment?payment-ui=direct-api

**Comment by chungxon** [comment]
Hi @mahimrocky, may I know if you have fixed this issue? I have the same issue with AfterPay/ClearPay (on both Android and iOS) and Affirm (Android only). I tested with the example code on this repo (my test keys). AfterPay and Affirm are enabled on my Stripe Dashboard, Affirm works fine on iOS. Creating a payment intent using the server API works fine, only the `initPaymentSheet` step with the Flutter Stripe package fails

|AfterPay|Affirm|
|:-:|:-:|
|![Image](https://github.com/user-attachments/assets/fb0cd910-47fc-4f94-a620-842be3837fd8)|![Image](https://github.com/user-attachments/assets/c43b5a69-3e8d-47a2-a9a1-12bd47ace0b0)|
