### ISSUE TITLE
Apple deferred payment does not give back shippingAddress, billingAddress or shippingMethods

### ISSUE THREAD

**Issue by debasmitasarkar** [flutter-stripe/flutter_stripe#1814]
**Describe the bug**
I am trying to use flutter_stripe plugin for apple deferred payment. I have asked user to add the shipping address and billing address and added shippingMethods as well in the plugin parameters. What I expect is to get the shippingAddress and the billingAddress details from the method confirmPlatformPaySetupIntent. But I can't get back the shipping , billing address or any other details and after calling the method, it just adds the card to stripe nothing else happens.

If I use pay plugin and get apple pay token, I don't know what to do with that token as flutter_stripe plugin does not tell which method to call. If I call confirmPayment method it throws error once I provide the token.

**To Reproduce**
1. Call flutter_stripe  confirmPlatformPaySetupIntent with apple pay deferred payment details. 
2. Expect the shipping and billing address back from the method.

```
 await Stripe.instance.confirmPlatformPaySetupIntent(
            clientSecret: response.clientSecret,
            confirmParams: PlatformPayConfirmParams.applePay(
              applePay: ApplePayParams(
                requiredBillingContactFields: [
                  ApplePayContactFieldsType.postalAddress,
                  ApplePayContactFieldsType.name,
                  ApplePayContactFieldsType.phoneNumber,
                  ApplePayContactFieldsType.emailAddress,
                ],
                requiredShippingAddressFields: [
                  ApplePayContactFieldsType.postalAddress,
                  ApplePayContactFieldsType.name,
                  ApplePayContactFieldsType.phoneNumber,
                  ApplePayContactFieldsType.emailAddress,
                ],
                shippingType: ApplePayShippingType.shipping,
                shippingMethods: [
                  ApplePayShippingMethod(
                    amount: '0.00',
                    detail: 'Available within an hour',
                    identifier: 'in_store_pickup',
                    label: 'In-Store Pickup',
                  ),
                  ApplePayShippingMethod(
                    amount: '4.99',
                    detail: '5-8 Business Days',
                    identifier: 'flat_rate_shipping_id_2',
                    label: 'UPS Ground',
                  ),
                  ApplePayShippingMethod(
                    amount: '29.99',
                    detail: '1-3 Business Days',
                    identifier: 'flat_rate_shipping_id_1',
                    label: 'FedEx Priority Mail',
                  ),
                ],
                merchantCountryCode: 'US',
                currencyCode: 'USD',
                cartItems: [
                  ApplePayCartSummaryItem.deferred(
                    label: 'Artwork',
                    amount: '99.99',
                    deferredDate:
                        (DateTime.now().millisecondsSinceEpoch / 100).floor(),
                  ),
                ],
              ),
            ),
```

With pay plugin,
1. Call pay plugin with necessary details
2. Get the apple pay token back
3. No idea what to do with that token to connect to stripe.
4. Calling confirmSetupIntent does not help and throws error.

**Expected behavior**
I need the deferred apple pay to work with flutter_stripe and I should be able to get back the shippingAddress, billingAddress and shipping methods. 
With pay plugin, once I provide the apple pay token to stripe I see parsing error.

**Smartphone / tablet**
 - Device: iPhone 12 pro max
 - OS: iOS 14
 - Package version: 10.1.1
 - Flutter version : 3.22.0

**Additional context**

**Comment by remonh87** [comment]
We cannot return the address from stripe but apple pay provides us with a callback with the shipping details. Use the `onShippingContactSelected`  on our library to get the address.


https://github.com/flutter-stripe/flutter_stripe/blob/main/example/lib/screens/wallets/apple_pay_screen.dart
