### ISSUE TITLE
[Web] please update the stripe_js plugin

### ISSUE THREAD

**Issue by Usamakabir07** [flutter-stripe/flutter_stripe#1817]
Please update the **stripe_js: ^3.4.0** plugin as its having analysis issue and "allowInterop" method is giving error while build for web

**Comment by remonh87** [comment]
you can use [6.0.0-dev.0](https://pub.dev/packages/stripe_js/versions/6.0.0-dev.0) that has the new interop. Since it is a big change we first want people to try it.
