### ISSUE TITLE
Your project requires a newer version of the Kotlin Gradle plugin.

### ISSUE THREAD

**Issue by faisalsaleemdev** [flutter-stripe/flutter_stripe#1820]
**Describe the bug**
I have used the kotlin verions which is defined on the flutter stripe [Example from flutter stripe](https://github.com/flutter-stripe/flutter_stripe/blob/main/example/android/build.gradle#L9)

**Expected behavior**
I should build or run the app

<img width="870" alt="Screenshot 2024-06-25 at 12 03 32 AM" src="https://github.com/flutter-stripe/flutter_stripe/assets/66200018/6ff59157-75f7-47bf-89ff-c842bf1caaae">

**Comment by remonh87** [comment]
in your case you need to upgrade the kotlin version of your project like the command tool says. This does not look like a problem on our side since the example app compiles

**Comment by AdeelWajid** [comment]
We are waiting for update. can't able to make build

**Comment by faisalsaleemdev** [comment]
> in your case you need to upgrade the kotlin version of your project like the command tool says. This does not look like a problem on our side since the example app compiles

I have tried all the version version from the example app to the latest version.

**Comment by jonasbark** [comment]
Closed due to lack of response
