### ISSUE TITLE
web: NoSuchMethodError: method not found: 'canMakePayment$0'

### ISSUE THREAD

**Issue by dioseltorre** [flutter-stripe/flutter_stripe#1821]
**Describe the bug**
`stripe.isPlatformPaySupported` is throwing error in release and profile modes using Flutter 3.22.2.

```console
NoSuchMethodError: method not found: 'canMakePayment$0' (_this._js.canMakePayment$0 is not a function. (In '_this._js.canMakePayment$0(0)', '_this._js.canMakePayment$0' is undefined))
```

**Smartphone / tablet**
 - Device: 
 - OS:
 - Package version: `flutter_stripe: ^10.2.0` `flutter_stripe_web: ^5.2.0`
 - Flutter version: `3.22.2`

**Comment by smihica** [comment]
Ok. so let's downgrade it!

**Comment by remonh87** [comment]
if you compile to wasm you need to use our dev version: [6.0.0-dev.0](https://pub.dev/packages/flutter_stripe_web/versions/6.0.0-dev.0)

**Comment by SaddarTuri** [comment]
Stripe do not accept amount less than 50 cents. And i see you are giving $0. Increase amount to 50 or more it will work.

**Comment by remonh87** [comment]
@SaddarTuri  the $0 issue has nothing to do with  the amount but with the new js interop of flutter.

@dioseltorre  you also need to confirm the platform payment. See: https://github.com/flutter-stripe/flutter_stripe/blob/main/example/lib/screens/wallets/apple_pay_screen.dart

**Comment by dioseltorre** [comment]
> @dioseltorre you also need to confirm the platform payment. See: https://github.com/flutter-stripe/flutter_stripe/blob/main/example/lib/screens/wallets/apple_pay_screen.dart

@remonh87 I don't think this can be done on web platform because [platformPayConfirmPaymentIntent](https://github.com/flutter-stripe/flutter_stripe/blob/main/packages/stripe_web/lib/src/web_stripe.dart#L520C25-L520C56) on `stripe_web` is currently not implemented.
