### ISSUE TITLE
Could not build the precompiled application for the device.

### ISSUE THREAD

**Issue by AkshayStackSum** [flutter-stripe/flutter_stripe#1823]
**Describe the bug**
i am having issue while i am running the app in iOS 
```
Could not build the precompiled application for the device.
Swift Compiler Error (Xcode): Missing return in closure expected to return 'String'
/Users/keyurrathod/Documents/GitHub/prs_flutter_app/ios/Pods/StripeCore/StripeCore/StripeCore/Source/Analytics/AnalyticLoggableError.swift:62:8

Swift Compiler Error (Xcode): Missing return in closure expected to return 'String'
/Users/keyurrathod/Documents/GitHub/prs_flutter_app/ios/Pods/StripeCore/StripeCore/StripeCore/Source/Analytics/AnalyticLoggableError.swift:69:8


Error launching application on shubham’s iPhone.
```
**To Reproduce**
flutter_stripe: ^10.2.0
just add the dependencies and run in iOS

**Expected behavior**
As it run smoothly in Android but not working on iOS 15.8.2

**Smartphone / tablet**
 - Device: [iPhone 6s]
 - OS: [iOS 15.8.2]
 - Package version: [10.2.0]
 - Flutter version [3.22.2.]

**Comment by ziadhassan7** [comment]
I'm also facing this issue, and the only fix was downgrading stripe to a version less than 10.0.0 .

My Xcode version is: 14.3.1

**Comment by AkshayStackSum** [comment]
**It's work great thank you buddy.**
