### ISSUE TITLE
Widget crash - ClassNotFoundException StripeCardMultilineWidgetBinding

### ISSUE THREAD

**Issue by matmicro** [flutter-stripe/flutter_stripe#1826]
**Describe the bug**
My Flutter App crash as soon as it tries to display the Stripe widget.
Crash with output:
java.lang.ClassNotFoundException: Didn't find class "com.stripe.android.databinding.StripeCardMultilineWidgetBinding

It works fine with flutter_stripe: ^7.0.0
but it crash with newer versions.

**Smartphone / tablet**
 - Device: Samsun and emulator
 - OS: Android
 - Flutter version 3.16.0 and 3.22.2

**Comment by remonh87** [comment]
which widget and which version of the sdk are you using?

**Comment by jonasbark** [comment]
You should not override the dependency constraints and remove your replacement line in your build.gradle as well
