### ISSUE TITLE
Afterpay is not working if add in payment_method_types[]

### ISSUE THREAD

**Issue by PurjaRipal** [flutter-stripe/flutter_stripe#1827]
When i try to pass afterpay with ’payment_method_types': [‘card’, ‘afterpay_clearpay’] I’m getting this response :

```
{
  "id": "pi_****",
  "object": "payment_intent",
  "amount": 500,
  "amount_capturable": 0,
  "amount_details": {
    "tip": {
      
    }
  },
  "amount_received": 0,
  "application": null,
  "application_fee_amount": null,
  "automatic_payment_methods": null,
  "canceled_at": null,
  "cancellation_reason": null,
  "capture_method": "automatic",
  "charges": {
    "object": "list",
    "data": [
      
    ],
    "has_more": false,
    "total_count": 0,
    "url": "/v1/charges?payment_intent=pi_****"
  },
  "client_secret": "pi_****",
  "confirmation_method": "automatic",
  "created": 1234567890,
  "currency": "aud",
  "customer": null,
  "description": "The payment transaction description.",
  "invoice": null,
  "last_payment_error": null,
  "latest_charge": null,
  "livemode": false,
  "metadata": {
    
  },
  "next_action": null,
  "on_behalf_of": null,
  "payment_method": null,
  "payment_method_configuration_details": null,
  "payment_method_options": {
    "afterpay_clearpay": {
      "reference": null
    }
  },
  "payment_method_types": [
    "afterpay_clearpay"
  ],
  "processing": null,
  "receipt_email": null,
  "review": null,
  "setup_future_usage": null,
  "shipping": null,
  "source": null,
  "statement_descriptor": null,
  "statement_descriptor_suffix": null,
  "status": "requires_payment_method",
  "transfer_data": null,
  "transfer_group": null
}
```

But in this I’m getting error in onError() :

> await flutter_stripe.Stripe.instance.presentPaymentSheet().then((newValue)
> {
> 	
> }).onError((error, stackTrace)
> {
> 	print("onError: $error");
> }); 

Log : 

- LocalizedErrorMessage(code: FailureCode.Failed, localizedMessage: None of the requested payment methods (afterpay_clearpay) are supported., message: None of the requested payment methods (afterpay_clearpay) are supported., stripeErrorCode: null, declineCode: null, type: null)

- so I contact with stripe support they said pass type “afterpay / clearpay” so after passing this type in payment intent : 

{amount: 500, currency: AUD, payment_method_types[]: [card, zip, afterpay / clearpay], description: The payment transaction description.}

I got this error in **flutter_stripe.Stripe.instance.presentPaymentSheet()** :

- LocalizedErrorMessage(code: FailureCode.Failed, localizedMessage: Invalid Setup Intent client secret: sk_test_****, message: Invalid Setup Intent client secret: sk_test_****, stripeErrorCode: null, declineCode: null, type: null)

**package version : flutter_stripe: ^10.2.0**

**Comment by remonh87** [comment]
it looks like you added the server key to the setupintent which is wrong. You should never incorporate the server key secret.  I would recommend you to read up a bit on the official docs: https://docs.stripe.com/payments/accept-a-payment?platform=android and also check our example app

**Comment by chungxon** [comment]
Hi @PurjaRipal, may I know if you have fixed this issue? I have the same issue with AfterPay/ClearPay (on both Android and iOS) and Affirm (Android only). I tested with the example code on this repo (my test keys). AfterPay and Affirm are enabled on my Stripe Dashboard, Affirm works fine on iOS. Creating a payment intent using the server API works fine, only the `initPaymentSheet` step with the Flutter Stripe package fails

Another same question from [StackOverflow](https://stackoverflow.com/q/78841280/19622959)

|AfterPay|Affirm|
|:-:|:-:|
|![Image](https://github.com/user-attachments/assets/fb0cd910-47fc-4f94-a620-842be3837fd8)|![Image](https://github.com/user-attachments/assets/c43b5a69-3e8d-47a2-a9a1-12bd47ace0b0)|
