### ISSUE TITLE
Strange error in deferred PaymentSheet in iOS

### ISSUE THREAD

**Issue by pgiacomo69** [flutter-stripe/flutter_stripe#1834]
In iOS the Credit Card Payment (deferred PaymentSheet) is unsuccesful, with a message:
"An error occurred in PaymentSheet. Your PaymentIntent setupFutureUsage (none) does not match the PaymentSheet.IntentConfiguration setupFutureUsage (Optional (StripePaymentSheet.PaymentSheet.IntentConfi guration.SetupFutureUsage.onSession))."

Apple Pay works well. Same App in Android Emulator works perfectly.
  
1. Launch the "Stripe Example" App
2. Select "Single step (differed payment)" from "payment Sheet" demos 
3. Enter the fake card data.
4. Tap the confirm button.
5. Observe the failure.

Smartphone / tablet**
 - Device: IPhone 15 Pro Emulator
 - OS: iOS 17
 - Package version: >=10.1
 - Flutter version 3.22

**Additional context**

`await Stripe.instance.initPaymentSheet(
        paymentSheetParameters: SetupPaymentSheetParameters(
          merchantDisplayName: 'Flutter Stripe Store Demo',
          allowsDelayedPaymentMethods: true,
          intentConfiguration: IntentConfiguration(

              mode: IntentMode(
                setupFutureUsage: null,
                currencyCode: 'eur',
                amount: amount,
              ),

              confirmHandler: (method, saveFuture) {
                _createIntentAndConfirmToUser(method);
              }),

          // Extra params
          primaryButtonLabel: 'Pay now',
          applePay: const PaymentSheetApplePay(
            merchantCountryCode: 'DE',
          ),
          googlePay: const PaymentSheetGooglePay(
            merchantCountryCode: 'DE',
            testEnv: true,
          ),

          style: ThemeMode.light,
          appearance: const PaymentSheetAppearance(
            colors: PaymentSheetAppearanceColors(
                /*  background: Colors.white,
              componentBackground: Colors.white,
              componentText: Colors.black,
              primary: Colors.blue,
              componentBorder: Colors.black,
              placeholderText: Colors.black,
              primaryText: Colors.black,
              secondaryText: Colors.green, */

                ),
            shapes: PaymentSheetShape(
              borderWidth: 0.5,
              borderRadius: 8,
              shadow: PaymentSheetShadowParams(color: Colors.yellow),
            ),
            primaryButton: PaymentSheetPrimaryButtonAppearance(
              shapes: PaymentSheetPrimaryButtonShape(blurRadius: 8),
              colors: PaymentSheetPrimaryButtonTheme(
                light: PaymentSheetPrimaryButtonThemeColors(
                  background: Color.fromARGB(255, 231, 235, 30),
                  text: Color.fromARGB(255, 235, 92, 30),
                  border: Color.fromARGB(255, 235, 92, 30),
                ),
              ),
            ),
          ),
          billingDetails: billingDetails,
        ),
      );`

**Comment by daijintaozz** [comment]
I encountered the same problem
