### ISSUE TITLE
Google Console Warnings 

### ISSUE THREAD

**Issue by TiruKallepalli** [flutter-stripe/flutter_stripe#1836]
Hi Team,

I am using V10.2.0 while updating the build in play store i see below warning.

The developer of Stripe Android PaymentSheet SDK (com.stripe:paymentsheet) added the following note to SDK version 20.44.2:
This version has an issue where customers are shown a blank screen in `FlowController` when Google Pay is supported within `FlowController` and the customer checks out as a guest as well as supports Google Pay on their device. Please use version 20.47.0 or later if this affects your application.

**Comment by osamaeshmilh** [comment]
We are having the same issue, and it is delaying the release of a new version of our app in Google Play Console. Is there any solution?

**Comment by remonh87** [comment]
We upgraded to the latest stripe sdk so this should be fixed in stripe 11.0.0
