### ISSUE TITLE
how to handle payment failed on close icon click of card payment ?  

### ISSUE THREAD

**Issue by pateldhiraj782** [flutter-stripe/flutter_stripe#184]
**Describe the bug**

**To Reproduce**
1. Entering number 123-456-789 into the cardfield.
2. Tapping the confirm button.
3. Observe a failure with exception (including the part of the stack trace, belonging to this package) …

**Expected behavior**

**Smartphone / tablet**
 - Device: [e.g. iPhone X]
 - OS: [e.g. iOS 13, Android 10]
 - Package version: [e.g. 1.0.0]
 - Flutter version [e.g. 2.0.0.]

**Additional context**

**Comment by kalptech2021** [comment]
When I am pressing the close icon, its not confirming the payment but still it shows the snackbar, "payment successfully completed", How to handle if the payment is completed or not

**Comment by wilpar** [comment]
I use the charge.succeeded webhook to 'believe' that the payment worked.  Always better to trust a Stripe webhook than something that happens on the client.

**Comment by kalptech2021** [comment]
@wilpar now I am using stripe's API directly with node, I need to add a lot of functions, but it solves all the issues.
