### ISSUE TITLE
Exception: MissingPluginException(No implementation found for method onPlaceholderChanged on channel flutter.stripe/card_field/1)

### ISSUE THREAD

**Issue by TatsuUkraine** [flutter-stripe/flutter_stripe#1842]
**Describe the bug**
Exception in console, it seems it doesn't crash the app, but continuously reported during the embedded form render

**To Reproduce**
1. Just render inline Card Form field in Android

**Expected behavior**
No exceptions are thrown in console

**Smartphone / tablet**
 - Device: Pixel 7
 - OS: Android 13
 - Package version: 10.2.0
 - Flutter version 3.22.2

**Additional context**
It seems it happens just once of very first inline Card Form render in android, each next form render doesn't throw this exception

**Comment by remonh87** [comment]
@TatsuUkraine  I cannot reproduce it in the example app can you give me a reporduction example?

**Comment by TatsuUkraine** [comment]
@remonh87 I will try to reproduce it and send a code sample, maybe it got fixed already 🤔

**Comment by remonh87** [comment]
Closed for now feel free to reopen it if the issue still persist
