### ISSUE TITLE
Your Main Activity class io.flutter.embedding.android.FlutterActivity is not a subclass FlutterFragmentActivity

### ISSUE THREAD

**Issue by patialvikas** [flutter-stripe/flutter_stripe#1843]
Your Main Activity class io.flutter.embedding.android.FlutterActivity is not a subclass FlutterFragmentActivity.
I/flutter (27852): Please make sure you follow all the steps detailed inside the README: https://github.com/flutter-stripe/flutter_stripe#android
I/flutter (27852): If you continue to have trouble, follow this discussion to get some support https://github.com/flutter-stripe/flutter_stripe/discussions/538, null, null)
I/flutter (27852): #0      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:170:7)
I/flutter (27852): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:322:18)
I/flutter (27852): <asynchronous suspension>
I/flutter (27852): #2      MethodChannelStripe.initialise (package:stripe_platform_interface/src/method_channel_stripe.dart:54:5)
I/flutter (27852): <asynchronous suspension>
I/flutter (27852): #3      Stripe._initialise (package:flutter_stripe/src/stripe.dart:714:5)
I/flutter (27852): <asynchronous suspension>
I/flutter (27852): #4      main (package:spaces_user/main.dart:39:3)

**Comment by patialvikas** [comment]
My gradle  version 

  classpath 'com.android.tools.build:gradle:7.1.2'

And MainActivity
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.android.FlutterFragmentActivity

class MainActivity: FlutterFragmentActivity() {
}

**Comment by remonh87** [comment]
does it still happen if you remove import `import io.flutter.embedding.android.FlutterActivity` ?
