### ISSUE TITLE
Card Scanning Option Not Showing in Payment Sheet on Android Like iOS?

### ISSUE THREAD

**Issue by SaddarTuri** [flutter-stripe/flutter_stripe#1845]
On iOS, we have the camera option available above the card field for card scanning, but this feature is missing on Android. Does the Flutter-Stripe package support card scanning on Android? If so, could you please provide guidance on how to enable this feature for Android, as it is already functioning correctly on iOS?
<img width="399" alt="Screenshot 2024-07-11 at 12 33 29 PM" src="https://github.com/flutter-stripe/flutter_stripe/assets/30259257/ffcf523e-1793-4070-b5bd-b27bc50caacb">

**Comment by remonh87** [comment]
Card scan is only supported by the stripe iOS sdk
