### ISSUE TITLE
Get null value for description on Andorid

### ISSUE THREAD

**Issue by jinzekid** [flutter-stripe/flutter_stripe#1846]
Get null value for description for Android.

1. flutter stripe verison: [10.2.0](https://pub.dev/packages/flutter_stripe/versions/10.2.0)
2. Android

when we try to get description from api. we get null value.

Here is some debug log:

[log] intent json: {id: pi_3PbIGADTSuZ6kkTf1D9VCKzp, amount: 100, created: 1720686110000, currency: usd, status: Succeeded, clientSecret: pi_3PbIGADTSuZ6kkTf1D9VCKzp_secret_6VzLZu6WED5htUCfWaedO46FO, livemode: false, captureMethod: Automatic, confirmationMethod: Automatic, paymentMethodId: pm_1PbIHTDTSuZ6kkTf90nMyOcc, description: null, receiptEmail: null, canceledAt: 0, nextAction: null, shipping: null, mandateData: null, latestCharge: null}
[log] intent description: null

Anyone can help? Thanks.

**Comment by remonh87** [comment]
I would check the API docs. If you create a payment intent you can supply a description here https://docs.stripe.com/api/payment_intents/object . This has nothing to do with our sdk I would recommend contacting stripe support if you are still stuck
