### ISSUE TITLE
Creating Payment method missing address

### ISSUE THREAD

**Issue by hjudoo** [flutter-stripe/flutter_stripe#185]
Creating payment method not sending address but  name, email and phone information sent.
 I am using the example no webhooks with cardfield

 On stripe:
Request POST body
{
  "muid": "xxxxxxxx",
  "billing_details": {
    "name": "test30 test",
    "phone": "5555555555",
    "email": "h@gmail.com"
  },

"billing_details": {
          "address": {
            "city": null,
            "country": null,
            "line1": null,
            "line2": null,
            "postal_code": null,
            "state": null
          },

**Comment by jonasbark** [comment]
Which method are you using with this Flutter Stripe plugin where you cannot set an address?

**Comment by hjudoo** [comment]
try {

    final billingDetails = BillingDetails(
      email: 'email@stripe.com',
      phone: '+48888000888',
      address: Address(
        city: 'Quebec',
        country: 'CA',
        line1: '1459  Circle Drive',
        line2: '',
        state: 'quebec',
        postalCode: 'j1x1x1',
      ),
    ); // mocked data for tests

    // 2. Create payment method
    final paymentMethod =
        await Stripe.instance.createPaymentMethod(PaymentMethodParams.card(
      billingDetails: billingDetails,
    ));

**Comment by jonasbark** [comment]
> Creating payment method not sending address but name, email and phone information sent.
what exactly do you mean by that? the address in BillingDetails isn't sent? Isn't sent where? To Stripe? 
Please share more details

**Comment by hjudoo** [comment]
sorry I thought I was clear..my bad. 
I am using the example Payment No Webhooks. The first step in the code is create payment method and sending parameters BillingDetails. The name, email and phone appears in the stripe payment method that was created but not the address and if I look as the post body(in stripe logs) the address was not sent to stripe. The whole process works even if the address is not sent but it was supposed to send the address aswell

**Comment by jgrody** [comment]
This is happening to me as well. 

```
const billingDetails = stripe.BillingDetails(
  email: 'email@stripe.com',
  phone: '+48888000888',
  name: 'Foo Bar',
  address: stripe.Address(
    line1: '123 main st',
    line2: '',
    city: 'San Diego',
    state: 'CA',
    postalCode: '92103',
    country: 'US',
  ),
);
final paymentMethod = await stripe.Stripe.instance.createPaymentMethod(
  stripe.PaymentMethodParams.card(
    billingDetails: billingDetails,
  ),
);
```

This is the output `BillingDetails` object:

```
BillingDetails(email: email@stripe.com, address: Address(city: null, country: null, line1: null, line2: null, postalCode: null, state: null), phone: +48888000888, name: Foo Bar)
```

All the `Address` values are null

**Comment by didnteven** [comment]
![Image 8-08-21 at 11 52 AM](https://user-images.githubusercontent.com/73682268/128616581-deb8464a-f211-455c-93a6-5f42cf29ae38.jpg)
![Image 8-08-21 at 11 51 AM](https://user-images.githubusercontent.com/73682268/128616582-61c70f3d-9493-4d7c-9b8d-6893bd9babac.jpg)


I am getting the same issue. Name, phone number, email saving fine. But the Address object isn't saving when calling confirmSetupIntent?

The code where I use the billing details:
(method where the error is happening)

     //3. confirm set up intent
      final setupIntentResult = await Stripe.instance.confirmSetupIntent(
        clientSecret,
        PaymentMethodParams.card(
          billingDetails: billingDetails,
        ),
      );

**Comment by musthafa1996** [comment]
This issue has been fixed by the pull request: #284

**Comment by kotchuprik** [comment]
@jonasbark any updates here? 🙈🙈🙈

**Comment by eliezerp3** [comment]
Any update on this? Also having this problem. Using this setup:

```
Future<void> checkout() async {
    final billingDetails = BillingDetails(
      email: 'email@stripe.com',
      phone: '+48888000888',
      address: Address(
        city: 'Houston',
        country: 'US',
        line1: '1459  Circle Drive',
        line2: '',
        state: 'Texas',
        postalCode: '77063',
      ),
    );
    try {
      /// retrieve data from the backend
      final _paymentSheetData = await API.createPaymentIntent();
      print(_paymentSheetData.data);
      await Stripe.instance.initPaymentSheet(
          paymentSheetParameters: SetupPaymentSheetParameters(
        // applePay: true,
        // googlePay: true,
        style: ThemeMode.dark,
        testEnv: true,
        merchantCountryCode: 'US',
        merchantDisplayName: 'Flutter Stripe Store Demo',
        customerId: _paymentSheetData.data['customer_id'],
        paymentIntentClientSecret: _paymentSheetData.data['client_secret'],
        customerEphemeralKeySecret: _paymentSheetData.data['ephemeral_key'],
        billingDetails: billingDetails,
      ));
      
      await Stripe.instance.presentPaymentSheet();
    } catch (e) {
      if (e is StripeException)
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(
            content: Text(
          e.error.localizedMessage ??
              'There was an error proccesing your payment',
          textAlign: TextAlign.center,
        )));
      else
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(
            content: Text(
          e.toString(),
          textAlign: TextAlign.center,
        )));
    }
  }
```

**Comment by remonh87** [comment]
we are waiting for a new version to be launched by Stripe that includes the fix. Till now not much has happened

**Comment by pradeep14598** [comment]
Still there no changes in getting address null

` setBillingDetails = BillingDetails(
      name: getOrderResponse.user.name,
      email: getOrderResponse.user.email,
      phone: getOrderResponse.user.phone,
      address: Address(
          city:' Kuala Lumpur',
          line1: 'Pej Icu & Mkn Blok C & D Jpm Jln Dato Onn Mal,
          line2: ' ',
          postalCode: ' 50502',
          state: ' Wilayah Persekutuan',
          country: 'MY'),
    );

 try {
      await Stripe.instance.confirmPayment(
        clientSecret,
        PaymentMethodParams.grabPay(
          billingDetails: getBillingDetails,
        ),
      );
      endLoading();
      _handlePaymentSuccess();
    } catch (e) {
      endLoading();
      _handlePaymentFailure(e);
    }

`

**Comment by syedabdulbasit1** [comment]
>

After updating Flutter Stripe 4.0.0 but still billing address is not sent in the stripe dashboard.

**Comment by khizar1556** [comment]
did anyone resolve this issue?

**Comment by syedabdulbasit1** [comment]
@khizar1556 we have to create a customer for stripe and pass parameter in its API

**Comment by memishood** [comment]
I have same issue

**Comment by Aung-Zaw-Phyo** [comment]
This problems is still happening.

Any update?

**Comment by DroidMagician** [comment]
Facing same issue not getting address details all fields are null 
Any solution to this?
