### ISSUE TITLE
Payment Sheet not being translated on Android into 

### ISSUE THREAD

**Issue by emilysmithson** [flutter-stripe/flutter_stripe#1850]
**Describe the bug**
Our app has been translated into 12 languages. On android the payment sheet is not picking up on the device language for 
- Polish
- Romanian
- Czech

**To Reproduce**
On android device set the locale in the settings to Polish/Poland.
Initialise the payment sheet:     
 await _stripe.initPaymentSheet(
        paymentSheetParameters: SetupPaymentSheetParameters(
          setupIntentClientSecret: clientSecret,
          merchantDisplayName: merchantName, 
          allowsDelayedPaymentMethods: true, 
        ),
      );
      await _stripe.presentPaymentSheet();

**Expected behavior**
PaymentSheet should be displayed in Polish
Instead, PaymentSheet is displayed in English

**Smartphone / tablet**
 - Device: Seen on multiple android devices
 - OS: Android 14 + Android 13
 - Package version: 10.0.0
 - Flutter version 3.19.5

**Additional context**
For all other locales the payment sheet appears in the correct language

**Comment by jonasbark** [comment]
https://github.com/stripe/stripe-react-native/issues/243
There's not much that can be done here
