### ISSUE TITLE
UI Payment sheet glitch, when payment sheet pop before completely loads.

### ISSUE THREAD

**Issue by MuhammadMusa22** [flutter-stripe/flutter_stripe#1860]
**Describe the bug**
When paymen sheet is ready to show, as soon as it appears or just click outside again and again during loading phase, payment sheet pops but showing a little glitch, as you can see it video attached as well.

**To Reproduce**
1. Open payment sheet.
2. During loading phase of payment sheet, continuously click outside payment sheet area.
3. Observe a UI payment sheet glitch.

**Smartphone / tablet**
 - Device: iPhone X
 - Package version: flutter_stripe: ^10.1.1
 - Flutter version: Flutter 3.19.5

https://github.com/user-attachments/assets/99972b16-8c93-4e2c-b627-24981556b239

**Comment by remonh87** [comment]
This was fixed in one of the latest sdks and should not happen anymore
