### ISSUE TITLE
[Google Pay] button PlatformPayButton is not trigger only in android

### ISSUE THREAD

**Issue by mtiendat** [flutter-stripe/flutter_stripe#1861]
**Describe the bug**
click PlatformPayButton is not trigger when I try to click in test mode even use Real Device. 
PlatformPayButton
**To Reproduce**
` return ValueListenableBuilder(
      valueListenable: Stripe.instance.isPlatformPaySupportedListenable,
      builder: (context, value, widget) {
        return value
            ? Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  const SizedBox(
                    height: 16,
                  ),
                  SizedBox(
                    height: 48,
                    child: PlatformPayButton(
                      type: PlatformButtonType.pay,
                      onPressed: (){}, //not trigger when I tap it
                    ),
                  ),
                  Padding(
                    padding: const EdgeInsets.symmetric(vertical: 8),
                    child: Row(
                      children: [
                        const Expanded(
                          child: Divider(
                            color: AppColors.textTertiary,
                          ),
                        ),
                        Padding(
                          padding: const EdgeInsets.symmetric(horizontal: 16),
                          child: Text(
                            'OR',
                            style: TextStyles.footnote.copyWith(
                              color: AppColors.textTertiary,
                            ),
                          ),
                        ),
                        const Expanded(
                          child: Divider(
                            color: AppColors.textTertiary,
                          ),
                        ),
                      ],
                    ),
                  ),
                ],
              )
            : const SizedBox();
      },
 )`

**Expected behavior**

**Smartphone**
 - Device: Samsung S10e
 - OS: Android 13
 - Package version: 10.2.0
 - Flutter version 3.22.2
**Emulator**
 - Device:Pixel 
 - OS: Android 14
 - Package version: 10.2.0
 - Flutter version 3.22.2
 -
**Additional context**
these are some version:
`plugins {
    id "dev.flutter.flutter-plugin-loader" version "1.0.0"
    id "com.android.application" version '8.4.2' apply false
    id "com.google.gms.google-services" version "4.4.0" apply false
    id "org.jetbrains.kotlin.android" version "1.8.10" apply false
}
`
**This is log when flutter render the button**
`java.lang.UnsupportedOperationException: Failed to resolve attribute at index 0: TypedValue{t=0x2/d=0x7c040084 a=-1}, theme={InheritanceMap=[id=0x7c1100a8com.google.android.gms:style/PayButtonDarkTheme], Themes=[com.google.android.gms:style/PayButtonDarkTheme, forced, android:style/Theme.DeviceDefault.Light.DarkActionBar, forced]}
View class android.support.v7.widget.AppCompatTextView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
I/DynamiteModule(10378): Considering local module com.google.android.gms.wallet_dynamite:0 and remote module com.google.android.gms.wallet_dynamite:242632000
I/DynamiteModule(10378): Selected remote version of com.google.android.gms.wallet_dynamite, version >= 242632000
V/DynamiteModule(10378): Dynamite loader version >= 2, using loadModule2NoCrashUtils
E/ThemeUtils(10378): View class android.support.v7.widget.AppCompatTextView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
E/ThemeUtils(10378): View class com.google.android.material.imageview.ShapeableImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).`

already set theme to Theme.AppCompat and use FlutterFragmentActivity

**Comment by mtiendat** [comment]
here is video

https://github.com/user-attachments/assets/0b1d1ce5-7598-4230-b380-35c87662b85b

**Comment by remonh87** [comment]
@jonasbark  seems like latest upgrade broke something in the theming on Android can you take a look at this? I can reproduce it on my phone

**Comment by jonasbark** [comment]
Currently on vacation - will be able to have a look sometime next week
