### ISSUE TITLE
Error installing pod

### ISSUE THREAD

**Issue by krumpking** [flutter-stripe/flutter_stripe#1867]
**Describe the bug**
When flutter_stripe is added to the  pubspec.yaml the app is not installing with error : Error installing pod, but when commented out it works

**To Reproduce**
1. Add flutter_stripe to pubscpec.yaml
2. Install
3. Try run on an iOS virtual device

**Expected behavior**
Expected to run 

**Smartphone / tablet**
 - Device: iphone SE 3rd generation
 - OS:  iOS 17
 - Package version: 10.2.0
 - Flutter 3.19.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 300451adae (4 months ago) • 2024-03-27 21:54:07 -0500
Engine • revision e76c956498
Tools • Dart 3.3.3 • DevTools 2.31.1

**Additional context**

**Comment by remonh87** [comment]
can you provide the full logs of the pod error?

**Comment by krumpking** [comment]
Thank you it seems to be working

**Comment by krumpking** [comment]
It was my ios build problem, so when I deleted the podfile and reinstalled it, it started working
