### ISSUE TITLE
merchantDisplayName can not be set via Stripe.instance.presentApplePay

### ISSUE THREAD

**Issue by werdlv** [flutter-stripe/flutter_stripe#187]
**Describe the bug**
`merchantDisplayName` can not be set via `Stripe.instance.presentApplePay`

**To Reproduce**
```dart
await Stripe.instance.presentApplePay(
  ApplePayPresentParams(
    cartItems: [
      ApplePayCartSummaryItem(
        label: 'Item name',
        amount: '15',
      ),
    ],
    country: 'DE',
    currency: 'EUR',
  ),
);

```

**Expected behavior**
Possibility to pass `merchantDisplayName` into `ApplePayPresentParams` class. It seems that further on the platform code logic already handles that [here](https://github.com/flutter-stripe/flutter_stripe/blob/b73481528a14ad7bc33673b0a380ac93a2b30773/packages/stripe_ios/ios/Classes/StripeSdk.swift#L73-L75).

**Additional context**
We got our APP rejected because of `Specifically, payee name is missing on Apple Pay payment sheet.`

**Comment by remonh87** [comment]
@jamesblasco  this is very curious I see the merchantDisplayName in the initPaymentSheet but it is not added in the stripe bindings for apple pay. Can you check what is going on there?

**Comment by jamesblasco** [comment]
Mmm I am not sure if there is an option to add the merchant name to the Apple Pay sheet. See docs:

https://developer.apple.com/documentation/passkit/pkpaymentrequest

https://developer.apple.com/documentation/passkit/apple_pay/offering_apple_pay_in_your_app

I have done some research and this is what I found out. Apple requires you to add the merchant name inside your summary items.
The payment sheet automatically does that:
![image](https://user-images.githubusercontent.com/19904063/125636898-5df9c56d-e707-4930-b966-b75adfef9d50.png)

You can see here the native iOS Stripe SDK where it is added a new summary item with the Merchant name and the total:

https://github.com/stripe/stripe-ios/blob/591f54d11f6f60be609e294f7dd7570c0ad32b49/Stripe/STPApplePayContext%2BPaymentSheet.swift#L63-L67

The `presentApplePay` is a raw implementation where you add the summary items yourself. So it is expected that you also add the one with the merchant name. It is a bit confusing as Apple does not explain it very well in their docs. I will add it to ours.

Let me know if after adding the summary item with your merchant name your app is accepted.

**Comment by werdlv** [comment]
Thanks @jamesblasco - I can confirm that the issue raised by the Apple Review team (`payee name is missing on Apple Pay payment sheet.`) was resolved by putting the name of the payee as the item summary.
