### ISSUE TITLE
Error installing StripeFinancialConnections

### ISSUE THREAD

**Issue by spn107** [flutter-stripe/flutter_stripe#1870]
Getting issue when installing pods

[!] Error installing StripeFinancialConnections
[!] /usr/bin/git clone https://github.com/stripe/stripe-ios.git /var/folders/3g/vfpjsjw55r51jhg0n0zklz9m0000gn/T/d20240726-26569-rv498c --template= --single-branch --depth 1 --branch 23.28.1

Cloning into '/var/folders/3g/vfpjsjw55r51jhg0n0zklz9m0000gn/T/d20240726-26569-rv498c'...
error: 1766 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

Flutter version: 3.22.2
Xcode: 15.4

**Comment by remonh87** [comment]
what is the version of the library you are installing?

**Comment by spn107** [comment]
> what is the version of the library you are installing?

flutter_stripe: ^11.0.0

**Comment by remonh87** [comment]
I cannot reproduce it added stripe to a clean project and it works like a charm. If you want me to dive into it further I need a complete reproduction project.

**Comment by hungdq-nws** [comment]
same issues!

I resolve issue by steps:
1. cd ios && pod repo update
2. pod install

Hope this help!
@spn107

**Comment by LeDrOxx** [comment]
@spn107 I faced this issue on WIFI when when running `pod update` so i switched to cellular data from my phone hotspot and it worked with no further changes

**Comment by JUDEJEEVAN** [comment]
@LeDrOxx Thanks, it really works, at first I was suspicious, but when I tried, it eventually worked.

**Comment by loicgeek** [comment]
Thanks @LeDrOxx it worked lol
