### ISSUE TITLE
IN iOS: Error installing StripePaymentsUI -- IN Android: Build failed with an exception.

### ISSUE THREAD

**Issue by RajSoni8866** [flutter-stripe/flutter_stripe#1871]
IN iOS:

[!] Error installing StripePaymentsUI
[!] /usr/bin/git clone https://github.com/stripe/stripe-ios.git /var/folders/fc/j638kg4n1ds4ytj7bxkgpzfh0000gn/T/d20240726-70943-mjlgo5 --template= --single-branch --depth 1 --branch 23.28.0

Cloning into '/var/folders/fc/j638kg4n1ds4ytj7bxkgpzfh0000gn/T/d20240726-70943-mjlgo5'...
error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
error: 2071 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

===========================================

IN Android: 

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':stripe_android:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 19s

┌─ Flutter Fix ──────────────────────────────────────────────────────────────────────────────┐
│ [!] Your project requires a newer version of the Kotlin Gradle plugin.                     │
│ Find the latest version on https://kotlinlang.org/docs/releases.html#release-details, then │
│ update /Volumes/E Drive/Working/homezena/android/build.gradle:                │
│ ext.kotlin_version = '<latest-version>'                                                    │
└────────────────────────────────────────────────────────────────────────────────────────────┘
Error: Gradle task assembleDebug failed with exit code 1

**Comment by remonh87** [comment]
can you run flutter clean and flutter pub get and try again?

**Comment by RajSoni8866** [comment]
I found solution for android in flutter_stripe document formate changed for build.gradle file now kotlin version is in setting.gradle file

pluginManagement {
    def flutterSdkPath = {
        def properties = new Properties()
        file("local.properties").withInputStream { properties.load(it) }
        def flutterSdkPath = properties.getProperty("flutter.sdk")
        assert flutterSdkPath != null, "flutter.sdk not set in local.properties"
        return flutterSdkPath
    }
    settings.ext.flutterSdkPath = flutterSdkPath()

    includeBuild("${settings.ext.flutterSdkPath}/packages/flutter_tools/gradle")

    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id "dev.flutter.flutter-plugin-loader" version "1.0.0"
    id "com.android.application" version "7.3.0" apply false
    id "org.jetbrains.kotlin.android" version "1.9.10" apply false
}

include ":app"





BUT iOS has same issue version flutter_stripe ^11.0.0

**Comment by RajSoni8866** [comment]
Please update document for both file in in new version of flutter you didn't get kotlin version in build.gradle file it is in setting.gradle file

id "org.jetbrains.kotlin.android" version "1.9.10" apply false

**Comment by RajSoni8866** [comment]
> can you run flutter clean and flutter pub get and try again?

iOS and Android both issue solved

**Comment by RajSoni8866** [comment]
> can you run flutter clean and flutter pub get and try again?

iOS and Android both issue solved
