### ISSUE TITLE
Unable to build apk when adding stripe

### ISSUE THREAD

**Issue by iSaqibShafique** [flutter-stripe/flutter_stripe#1872]
**Describe the bug**
 [!] Your project requires a newer version of the Kotlin Gradle plugin.                                                                 │
│ Find the latest version on https://kotlinlang.org/docs/releases.html#release-details, then update /Users/saqibshafique/Desktop/Flutter │
│ Projects/pink_elephants_coaching/android/build.gradle:                                                                                 │
│ ext.kotlin_version = '<latest-version>'                                                                                                

**To Reproduce**
* What went wrong:
Execution failed for task ':stripe_android:compileReleaseKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10m 9s
Running Gradle task 'assembleRelease'...                          609.8s

┌─ Flutter Fix ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ [!] Your project requires a newer version of the Kotlin Gradle plugin.                                                                 │
│ Find the latest version on https://kotlinlang.org/docs/releases.html#release-details, then update /Users/saqibshafique/Desktop/Flutter │
│ Projects/pink_elephants_coaching/android/build.gradle:                                                                                 │
│ ext.kotlin_version = '<latest-version>'                                                                                                │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Gradle task assembleRelease failed with exit code 

**Expected behavior**
I want to build app

**Smartphone / tablet**
 - Device: [e.g. iPhone X]
 - OS: [e.g. iOS 13, Android 10]
 - Package version: 10.2.0
 - Flutter version 3.19.6

**Additional context**

**Gradle-wrapper.properties**

distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-8.0-bin.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists

**Android/build.gradle**

buildscript {
    ext.kotlin_version = '1.8.10'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.1.3'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}

**Android/app/build.gradle**

plugins {
    id "com.android.application"
    // START: FlutterFire Configuration
    id 'com.google.gms.google-services'
    // END: FlutterFire Configuration
    id "kotlin-android"
    // The Flutter Gradle Plugin must be applied after the Android and Kotlin Gradle plugins.
    id "dev.flutter.flutter-gradle-plugin"
}

def localProperties = new Properties()
def localPropertiesFile = rootProject.file("local.properties")
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader("UTF-8") { reader ->
        localProperties.load(reader)
    }
}

def flutterVersionCode = localProperties.getProperty("flutter.versionCode")
if (flutterVersionCode == null) {
    flutterVersionCode = "1"
}

def flutterVersionName = localProperties.getProperty("flutter.versionName")
if (flutterVersionName == null) {
    flutterVersionName = "1.0"
}

android {
    defaultConfig {
    multiDexEnabled true
   }
    namespace = "com.example.pink_elephants_coaching"
    compileSdk = 34
    ndkVersion = flutter.ndkVersion

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.pinkelephants.amberx"
        // You can update the following values to match your application needs.
        // For more information, see: https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.
        minSdk = 23
        targetSdk = flutter.targetSdkVersion
        versionCode = flutterVersionCode.toInteger()
        versionName = flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig = signingConfigs.debug
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
}

flutter {
    source = "../.."
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.google.android.gms:play-services-wallet:19.1.0'
    androidTestImplementation 'androidx.test:runner:1.2.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
}

**Comment by yazanturk** [comment]
the same error

**Comment by iSaqibShafique** [comment]
Fixed it but now got a new error, actually that was my biggest mistake to use stripe services now

**Comment by yazanturk** [comment]
any update ?

**Comment by remonh87** [comment]
please follow the android instructions provided here: https://github.com/flutter-stripe/flutter_stripe?tab=readme-ov-file#android .  For me everything compiles without issues using a new flutter project and following the instructions
