### ISSUE TITLE
Request to add additional parameter to pass setupIntentClientSecret in confirmSetupIntent()

### ISSUE THREAD

**Issue by mobileexpert1** [flutter-stripe/flutter_stripe#1875]
Hello Team,

Currently we have a requirement to link the ACH flow without any amount in flutter. And I'm using the method confirmSetupIntent() for ACH for US bank account. 

Please provide any solution so I can be able to use Ach flow without payment. 

Your prompt response highly appreciated. 

Thanks

**Comment by remonh87** [comment]
You can provide the setupintentclientsecret in confirmsetupintent. Stripe calls it `paymentIntentClientSecret` in their sdk which is a bit confusing but it should be the setup intent.
