### ISSUE TITLE
[Web]The `platformPayCreatePaymentMethod` method results in an error.

### ISSUE THREAD

**Issue by kanghuicong** [flutter-stripe/flutter_stripe#1879]
When I call the `platformPayCreatePaymentMethod` method, upon successful payment, `response.complete('success')` is supposed to close the payment process. However, it results in an error: `IntegrationError: Missing value for status for PaymentRequest completion: value should be one of the following strings: success, fail, invalid_payer_name, invalid_payer_email, invalid_payer_phone, invalid_shipping_address.`

This is confusing because the code does pass 'success', unless it is being changed when passed into the JS.

flutter_stripe: 11.0.0
flutter_stripe_web: 6.0.0

**Comment by EduardDumitrescu** [comment]
It seems that declaring it as a normal function fixes the error and removes the gray filter screen. I opened a mr here with the changes -> https://github.com/flutter-stripe/flutter_stripe/pull/1882.

**Comment by dioseltorre** [comment]
This maybe a similar issue. The payment seems successful but the Apple Pay wallsheet didn't close and resulted in `Payment Not Completed` error though no error log on console. [This](https://github.com/flutter-stripe/flutter_stripe/pull/1882) fixes the issue.

<img src="https://github.com/user-attachments/assets/9359e3d1-98a9-4c6e-a11d-8dcae4fecd3c" width="300" />
<img src="https://github.com/user-attachments/assets/3ff0a82d-b7f1-4a20-a137-fe22d3a02f94" width="300" />

**Comment by dioseltorre** [comment]
@kanghuicong Can you please reopen this issue until [#1882](https://github.com/flutter-stripe/flutter_stripe/pull/1882) will be merged?
