### ISSUE TITLE
using 'stripe_account' parameter for marketplace functionality

### ISSUE THREAD

**Issue by mklepaczko** [flutter-stripe/flutter_stripe#188]
Hi,

I need to implement Stripe using the marketplace functionality. For this according to Stripe docs the 'stripe_account' parameter is needed.

Since there is no documentation about that for this plugin and the official docs does not include any Dart or Flutter code samples could you provide an example? I tried several combination but I still get the 'parameter_unknown - stripe_account'.

https://stripe.com/docs/connect/enable-payment-acceptance-guide?platform=ios

Here is a sample of my fetchPaymentIntentClientSecret:

```
final response = await http.post(
      url,
      headers: {
        'Authorization':
            'Bearer sk_test_xxxj',
      },
      body: {
        'amount': 1000,
        'currency': 'EUR',
        'application_fee_amount': 5,
        'stripe_account': '{{${service.servicePaymentToken}}}'
      },
    );
    return json.decode(response.body);

```

**Comment by jonasbark** [comment]
I'm not sure what this is targeting? 
Which function of this Flutter library are you trying to use with an included "stripe_account"? Are you talking about Stripe Connect?

**Comment by mklepaczko** [comment]
Yes, it is Connect / Payments / Multiparty payments.

"In our store builder example, we want to build an experience where customers pay businesses directly. To set this experience up:

Indicate a purchase from the business is a direct charge with the Stripe-Account header."

**Comment by wilpar** [comment]
I just completed this yesterday using the payment_sheet demo.  I'll be making a video about it today, will link it here.

**Comment by mklepaczko** [comment]
> I just completed this yesterday using the payment_sheet demo. I'll be making a video about it today, will link it here.

Great thanks!

**Comment by jonasbark** [comment]
Isn't https://github.com/flutter-stripe/flutter_stripe/blob/main/packages/stripe_platform_interface/lib/src/stripe_platform_interface.dart#L33 'stripeAccountId' what you're searching for?

**Comment by mklepaczko** [comment]
@wilpar Yes thanks, I will have the answer there. I will wait till you publish the link to the video and close this one.

thx.
