### ISSUE TITLE
When Payment Sheet of Stripe is open then if i press back button of keyboard then app gets crashed

### ISSUE THREAD

**Issue by jimeshait** [flutter-stripe/flutter_stripe#1880]
**Describe the bug**

E/AndroidRuntime(31368): java.lang.NoSuchMethodError: No virtual method getEmojiStart(Ljava/lang/CharSequence;I)I in class Landroidx/emoji2/text/EmojiCompat; or its super classes (declaration of 'androidx.emoji2.text.EmojiCompat' appears in /data/app/~~UYBcvkLW_VtesJEsFyzyBA==/com.example.example-0ycqiBuhlp2yq7IoqzmdLw==/base.apk!classes5.dex)
E/AndroidRuntime(31368): 	at androidx.compose.foundation.text.StringHelpers_androidKt.findPrecedingBreak(StringHelpers.android.kt:24)
E/AndroidRuntime(31368): 	at androidx.compose.foundation.text.selection.BaseTextPreparedSelection.getPrecedingCharacterIndex(TextPreparedSelection.kt:150)
E/AndroidRuntime(31368): 	at androidx.compose.foundation.text.TextFieldKeyInput$process$2$3.invoke(TextFieldKeyInput.kt:131)
E/AndroidRuntime(31368): 	at androidx.compose.foundation.text.TextFieldKeyInput$process$2$3.invoke(TextFieldKeyInput.kt:129)
E/AndroidRuntime(31368): 	at androidx.compose.foundation.text.selection.TextFieldPreparedSelection.deleteIfSelectedOr(TextPreparedSelection.kt:397)
E/AndroidRuntime(31368): 	at androidx.compose.foundation.text.TextFieldKeyInput$process$2.invoke(TextFieldKeyInput.kt:129)
E/AndroidRuntime(31368): 	at androidx.compose.foundation.text.TextFieldKeyInput$process$2.invoke(TextFieldKeyInput.kt:106)
E/AndroidRuntime(31368): 	at androidx.compose.foundation.text.TextFieldKeyInput.commandExecutionContext(TextFieldKeyInput.kt:226)
E/AndroidRuntime(31368): 	at androidx.compose.foundation.text.TextFieldKeyInput.process-ZmokQxo(TextFieldKeyInput.kt:106)
E/AndroidRuntime(31368): 	at androidx.compose.foundation.text.TextFieldKeyInputKt$textFieldKeyInput$2$1.invoke-ZmokQxo(TextFieldKeyInput.kt:261)
E/AndroidRuntime(31368): 	at androidx.compose.foundation.text.TextFieldKeyInputKt$textFieldKeyInput$2$1.invoke(TextFieldKeyInput.kt:261)
E/AndroidRuntime(31368): 	at androidx.compose.ui.input.key.KeyInputNode.onKeyEvent-ZmokQxo(KeyInputModifier.kt:80)
E/AndroidRuntime(31368): 	at androidx.compose.ui.focus.FocusOwnerImpl.dispatchKeyEvent-ZmokQxo(FocusOwnerImpl.kt:193)
E/AndroidRuntime(31368): 	at androidx.compose.ui.platform.AndroidComposeView.dispatchKeyEvent(AndroidComposeView.android.kt:647)
E/AndroidRuntime(31368): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1985)
E/AndroidRuntime(31368): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1985)
E/AndroidRuntime(31368): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1985)
E/AndroidRuntime(31368): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1985)
E/AndroidRuntime(31368): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1985)
E/AndroidRuntime(31368): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1985)
E/AndroidRuntime(31368): 	at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:496)
E/AndroidRuntime(31368): 	at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1865)
E/AndroidRuntime(31368): 	at android.app.Activity.dispatchKeyEvent(Activity.java:4201)
E/AndroidRuntime(31368): 	at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:126)
E/AndroidRuntime(31368): 	at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:86)
E/AndroidRuntime(31368): 	at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:144)
E/AndroidRuntime(31368): 	at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:604)
E/AndroidRuntime(31368): 	at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:60)
E/AndroidRuntime(31368): 	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3413)
E/AndroidRuntime(31368): 	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:410)
E/AndroidRuntime(31368): 	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:6300)
E/AndroidRuntime(31368): 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6163)
E/AndroidRuntime(31368): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5652)
E/AndroidRuntime(31368): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5709)
E/AndroidRuntime(31368): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5675)
E/AndroidRuntime(31368): 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5827)
E/AndroidRuntime(31368): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5683)
E/AndroidRuntime(31368): 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5884)
E/AndroidRuntime(31368): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5656)
E/AndroidRuntime(31368): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5709)
E/AndroidRuntime(31368): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5675)
E/AndroidRuntime(31368): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5683)
E/AndroidRuntime(31368): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5656)
E/AndroidRuntime(31368): 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8548)
E/AndroidRuntime(31368): 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8499)
E/AndroidRuntime(31368): 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8450)
E/AndroidRuntime(31368): 	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:5406)
E/AndroidRuntime(31368): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(31368): 	at android.os.Looper.loop(Looper.java:236)
E/AndroidRuntime(31368): 	at android.app.ActivityThread.main(ActivityThread.java:8097)
E/AndroidRuntime(31368): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(31368): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
E/AndroidRuntime(31368): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
I/Process (31368): Sending signal. PID: 31368 SIG: 9

**To Reproduce**
1. Entering number 4242
2. If I click back button of keyboard to erase number
3. App gets Crashed

**Expected behavior**
Number should gets erase and app should react normally

**Smartphone / table

![WhatsApp Image 2024-08-04 at 19 33 51_8573ac79](https://github.com/user-attachments/assets/ebf202fa-a1e1-4327-9122-974943d18b1f)

 - Redmi 10 A

**Additional context**
I am using flutter_stripe: ^11.0.0 having flutter version  3.19.6

**Comment by remonh87** [comment]
Did you follow the instruction for [android](https://github.com/flutter-stripe/flutter_stripe?tab=readme-ov-file#requirements)?

**Comment by jimeshait** [comment]
Yes I have followed all the instructions but then also it gives this error if I click on back button else if I am not clicking then it works fine

**Comment by remonh87** [comment]
I tried to debug it tonight but I really cannot reproduce it. Can you give me a reproduction app so that I debug it further? Also try to run our example app and see if the issue persist there.

**Comment by jimeshait** [comment]
thanks @remonh87 issue is not seen now.

**Comment by jimeshait** [comment]
@remonh87 can you please help me on this issue https://github.com/flutter-stripe/flutter_stripe/issues/1916
