### ISSUE TITLE
Payment Element WEB save and retrieve customer payment methods

### ISSUE THREAD

**Issue by Andrea951112** [flutter-stripe/flutter_stripe#1886]
In payment element for web i would like to have to possibility of save and use saved payment methods from customer.

as described here:
[https://docs.stripe.com/payments/save-during-payment?platform=web&ui=elements#enable-saving-the-payment-method-in-the-payment-element]

**Comment by remonh87** [comment]
I will have a look coming week at it. I think we should be possible to add the customerSessionClientSecret to the options

**Comment by Andrea951112** [comment]
thanks @remonh87

**Comment by T-P-F** [comment]
Isn't this already supported in main?

https://github.com/flutter-stripe/flutter_stripe/blob/main/packages/stripe_web/lib/src/widgets/payment_element.dart
Line 18 etc...
