### ISSUE TITLE
Billing Details:  Unable to reflect in flutter Android Application.

### ISSUE THREAD

**Issue by DeepeshKalura** [flutter-stripe/flutter_stripe#1890]
**Describe the bug**
As, for indian export guidliance  we need to add customer address and name for successful payment.

Otherwise I will get the error.

``` json
  "last_payment_error": {
    "message": "As per Indian regulations, export transactions require a customer name and address. More info here: https://stripe.com/docs/india-exports",
```

To resolve, I added billing parameter in the stripe paymentsheet. But I am unable to see any changes in APP.

**ScrrenShot:**

![Screenshot_1723650962](https://github.com/user-attachments/assets/e72c8f51-f422-4914-8343-f70376fcc597)

**To Reproduce**
1. Copy paste the code
```dart 
import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:flutter_stripe/flutter_stripe.dart';
import 'package:dio/dio.dart';

const String privateKey = "Add your private key here";

const String publicKey = "Add your public key here";

void main() {
  Stripe.publishableKey = publicKey;
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Stripe Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: ElevatedButton(
          child: const Text("Press for payment"),
          onPressed: () async {
            await StripeSerevice().initPaymentSheet();
          },
        ),
      ),
    );
  }
}

class StripeSerevice {
  // StripeService() {
  // }
  Dio dio = Dio();

  final String baseUrl = "https://api.stripe.com/v1/";

// goes to the client side of the code
  Future<dynamic> createPayement() async {
    Map<String, dynamic> payload = {
      "amount": 1000 * 100,
      "currency": 'USD',
      "automatic_payment_methods[enabled]": true,
      "description": "Payment for jik jamp dump dump",
      "metadata": {
        "payment_for": "PaymentForTesting",
        "plan_id": "planId",
      }
    };
    try {
      final response = await dio.post(
        "${baseUrl}payment_intents",
        data: payload,
        options: Options(
          headers: {
            "Authorization": "Bearer $privateKey",
            "Content-Type": "application/x-www-form-urlencoded"
          },
        ),
      );
      final body = response.data;
      return (body);
    } catch (e) {
      print(e);
    }
  }

  Future<void> initPaymentSheet() async {
    try {
      var response = await createPayement();
      await Stripe.instance.initPaymentSheet(
        paymentSheetParameters: SetupPaymentSheetParameters(
          paymentIntentClientSecret: response['client_secret'],
          merchantDisplayName: "jan gui man kuli",
          customFlow: false,
          billingDetails: const BillingDetails(
            address: Address(
              city: "What is your city",
              country: "What is your country",
              line1: "What is your line1",
              line2: "What is your line2",
              postalCode: "What is your postal code",
              state: "What is your state",
            ),
            name: "What is your name",
          ),
        ),
      );
      await Stripe.instance.presentPaymentSheet();
    } catch (e) {
      print(e);
    }
  }

  Future<void> createCustomer() async {
    try {
      // final response = await dio.post(

      // );
    } catch (e) {
      print(e);
    }
  }
}


```

1. Run this code in flutter
3. Tapping the "Press for payment" Button.
4. Observe a failure that billing is not get support

**Expected behavior**
My expectation is to resolve this  "As per Indian regulations, export transactions require a customer name and address. More info here: https://stripe.com/docs/india-exports." error. 

And need the reason why billing is not showing in the UI. Does I am doing anything wrong? 

  

**Smartphone / tablet**
 Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.9, on Linux Mint 21.3 5.15.0-118-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2024.1)
[✓] IntelliJ IDEA Community Edition (version 2024.2)
[✓] VS Code (version 1.92.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

Found 3 connected devices:
  sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 14 (API 34) (emulator)
  Linux (desktop)              • linux         • linux-x64      • Linux Mint 21.3 5.15.0-118-generic
  Chrome (web)                 • chrome        • web-javascript • Google Chrome 127.0.6533.99

**Comment by remonh87** [comment]
You need to collect the address and name before creating the payment intent and it during the creation: https://docs.stripe.com/api/payment_intents/create.  I think this will fix your problem if not let me know
