### ISSUE TITLE
Bump web dependency to 1.0.0?

### ISSUE THREAD

**Issue by gourgouris** [flutter-stripe/flutter_stripe#1891]
Hi, would it be possible to bump the web dependency of stripe_web to ^1.0.0?

Given that the official recommendation is to move from dart:html to package:web, it would make sense for people to depend on the latest (1.0.0) when they migrate their packages. But the ^0.5.1 dependency that stripe_web has means anything lower than 1.0.0, making it impossible to upgrade projects that depend on both stripe and another package that uses package:web due to conflicts.

One such example is [printing](https://pub.dev/packages/printing) and more specifically [here](https://github.com/DavBfr/dart_pdf/blob/4146df6053d7192e7d15610d802209bde0b3dd7c/printing/pubspec.yaml#L36)

**Comment by remonh87** [comment]
yes I will take a look at the coming week

**Comment by mauriziopinotti** [comment]
Any news on this? All Firebase packages recently switched to web 1.0.0 so from now on Stripe will be preventing Firebase upgrades until this issue is resolved.

**Comment by remonh87** [comment]
fixed and shipped in latest version of flutter stripe web 6.1.0
