### ISSUE TITLE
Some Android device crash when call `Stripe.instance.applySettings()`

### ISSUE THREAD

**Issue by luunc** [flutter-stripe/flutter_stripe#1892]
In `main()` before `runApp()` function:

```
WidgetsFlutterBinding.ensureInitialized();

... <Some codes here>

Stripe.publishableKey = <Key>
**await Stripe.instance.applySettings();**

... <Some codes here>

runApp(const MyApp());
```

For some Android phones, it stops at `await Stripe.instance.applySettings()` with no response. This is Xiaomi 13T crash:

![Screenshot_2024-08-10-11-07-10-774_com silverlight store silverlight](https://github.com/user-attachments/assets/01a49ca4-41ba-4764-98ff-851cd8624922)

Kotlin versiom, Android Gradle, Theme, proguard-rules, using FlutterFragmentActivity are set up exactly like the example 
Android version: 14 UP1A.230905.011
OS Version: 1.0.5.0.UMFMIXM

Does anyone have solution for this?
Thank you in advance.

**Comment by remonh87** [comment]
Can you provide me the stacktrace of the crash?

**Comment by luunc** [comment]
I don't actually have the device that has bug, but Firebase Crashlytics captures this stacktrace:
![Screenshot 2024-08-19 at 11 41 55](https://github.com/user-attachments/assets/c717fbd5-9818-4039-899a-88e79808fc22)

You can see full stacktrace in the txt file below:
[issue_15c1049c4d0bc536c073e5cbbeef1b7c_ANR_session_66B78FEA00FD0001110186781D9417D1_DNE_0_v2_stacktrace.txt](https://github.com/user-attachments/files/16655834/issue_15c1049c4d0bc536c073e5cbbeef1b7c_ANR_session_66B78FEA00FD0001110186781D9417D1_DNE_0_v2_stacktrace.txt)

**Comment by remonh87** [comment]
hmm I do not see that the stacktrace has anything to do with the Stripe sdk. Are you sure it is not some http call that you make in the same code (I see that okhttp is crashing)

**Comment by luunc** [comment]
That's the only crash happened on the Android phone (Xiaomi 13T) when I use `await Stripe.instance.applySettings()` in `main()` function.
When I remove that line of code, the app run smoothly without crash.
So, I'm pretty sure about the stacktrace.

**Comment by remonh87** [comment]
To be honest without a clear reproduction scenario there is not much I can do.  It looks like something in the flutter C++ lib is crashing but there is no clear point to the stripe sdk.

**Comment by davemg3** [comment]
@remonh87 , hi, i confirm the same behaviour on some android phone.

While you dont manage to reproduce, i think this issue should not be closed as the culprit is indeed this line of code.
I did track this bug for months coming from some users, and finally "await Stripe.instance.applySettings();" is the line which causes crashes on some Oneplus 7T pro and Samsung A34 5g. 

I cannot provide stack cause i finally found it using dichotomia thanks to the support of some remote test user having a OnePlus 7T pro and willing to test each of my test case.
The strange thing is that i have procured the same OnePlus 7T pro following his specifications but i havent managed to reproduce.

```
`
final navigatorKey = GlobalKey<NavigatorState>();

void main() async {
  runZonedGuarded<Future<void>>(() async {
    //for error caught by Zones, use runZonedGuarded
    WidgetsFlutterBinding.ensureInitialized();
    await Firebase
        .initializeApp(); 
    FirebaseFirestore.instance.settings =
        Settings(persistenceEnabled: true, cacheSizeBytes: 10000000); 
    Stripe.publishableKey = prodStripePubKey;
    Stripe.merchantIdentifier = 'bubblesmapper.stripe.prod';
    Stripe.urlScheme = 'flutterstripe';
    //await Stripe.instance.applySettings(); //to be commented on OnePlus 7T pro phone

    AppLanguage appLanguage = AppLanguage();
    await appLanguage.fetchLocale();

    FlavourConfig(
      flavour: Flavour.Prod,
      values: const FlavourValues(currentFlavour: 'Prod'),
    );

    runApp(
      MultiProvider(
        providers: [
          ChangeNotifierProvider.value(value: appLanguage),
        ],
        child: MyApp() ,
      ),
    );
  }, (error, stack) => FirebaseCrashlytics.instance.recordError(error, stack));
}


class MyApp extends StatefulWidget {

  MyApp();

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {


  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {

    return GestureDetector(
      onTap: () {
        FocusScopeNode currentFocus = FocusScope.of(context);
        if (!currentFocus.hasPrimaryFocus && currentFocus.focusedChild != null) {
          FocusManager.instance.primaryFocus!.unfocus();
        }
      },
      child: MaterialApp(
          debugShowCheckedModeBanner: Constants.debugShowCheckedModeBanner,
          localizationsDelegates: AppLocalizations.localizationsDelegates, // Add this line

          locale: context.watch<AppLanguage>().appLocal,
          title: Constants.appName, //AppLocalizations.of(context).helloWorld
          routes: Routes.routes, //all routes to screens
          onGenerateRoute: RouteGenerator.generateRoute,
          home:
              TestScreen() // a stateful widget with appBar and container with green background color
        ),
    );
  }
}
`
```
