### ISSUE TITLE
Cannot scroll when pressing PaymentElement

### ISSUE THREAD

**Issue by WilliamCunhaCardoso** [flutter-stripe/flutter_stripe#1894]
**Describe the bug**
Considering a page with PaymentElement. When I try to scroll it, due to not being fully visible, it does not respect the scroll behavior of the parent component.

**To Reproduce**
Just create enough component to make screen scrollable

        return Scaffold(
          body: SingleChildScrollView(
            child: Column(
              children: [
                Container(
                  height: context.heightFromMediaQuery * 0.4,
                  color: Colors.red,
                ),
                ValetCreditCardPayment(),
                Container(
                  height: context.heightFromMediaQuery * 0.4,
                  color: Colors.blue,
                ),
              ],
            ),
          ),
        );

Media:

https://github.com/user-attachments/assets/14d75f26-03b9-4758-95dd-17bfdd249eb2

**Expected behavior**
Scroll normally

**Smartphone / tablet**
- Any browser, desktop or mobile
 - Package version: 6.0.0 flutter_stripe_web. 11.0.0 flutter_stripe
 - Flutter 3.24

**Additional context**

**Comment by remonh87** [comment]
This is a flutter issue and not related to this sdk. See for example: https://github.com/flutter/flutter/issues/69529

**Comment by WilliamCunhaCardoso** [comment]
Thanks very much for your clarification!
