### ISSUE TITLE
Google Pay Button Not Visible in Stripe Payment Sheet on Android Devices

### ISSUE THREAD

**Issue by mihiravdevs** [flutter-stripe/flutter_stripe#1897]
**Describe the bug**
I am integrating Stripe in a Flutter project using the flutter_stripe package (version 11.0.0). The Google Pay button is not appearing in the payment sheet on physical devices (Xiaomi Redmi Note 10 Pro Max and Realme 10) even though the Google Pay app is installed and functional on these devices.

**To Reproduce**
1. I have implemented flutter stripe payment sheet for subscription functionality, so when user click on subscribe payment sheet should open with google pay button

**Expected behavior**
The Google Pay button should be visible in the Stripe payment sheet when Google Pay is available on the device.

**Smartphone / tablet**
 - Device: Xiaomi Redmi Note 10 Pro Max and Realme 10
 
 **Environment**
Flutter Stripe Dependency: flutter_stripe: ^11.0.0
Physical Devices: Xiaomi Redmi Note 10 Pro Max, Realme 10
Google Pay App: Installed and functional on both devices
Test Environments: Tested with testEnv: true and testEnv: false in both test and production environments

**Additional context**
Despite the correct setup and Google Pay being installed, the Google Pay button is not visible in the payment sheet on Android devices. I have verified that the Apple Pay button appears correctly on an iOS simulator. This issue persists even after uploading the app to the Play Store for internal testing.

**Code Snippets:**
1. Flutter Stripe Initialization:
```
void main() async {
  WidgetsFlutterBinding.ensureInitialized(); // Initialize Flutter Binding
  _initStripe();

  runApp(
    MultiProvider(
      providers: providers(),
      child: const MyApp(),
    ),
  );
}


void _initStripe() async {
  Stripe.publishableKey = AppConstant.stripePublishKey;
  Stripe.merchantIdentifier = StringResources.appName;
  await Stripe.instance.applySettings();
}
```

2. Payment Sheet Setup:

```
Future<void> makePayment({
  required SubscriptionProvider provider,
  required String clientSecret,
  required String ephemeralKey,
  required String stripeUserID,
}) async {
  provider.setLoading(true);

  try {
    await Stripe.instance.initPaymentSheet(
      paymentSheetParameters: SetupPaymentSheetParameters(
        primaryButtonLabel: "Pay",
        customFlow: false,
        merchantDisplayName: StringResources.appName,
        setupIntentClientSecret: clientSecret,
        customerEphemeralKeySecret: ephemeralKey,
        applePay: const PaymentSheetApplePay(
          merchantCountryCode: 'CA',
        ),
        googlePay: PaymentSheetGooglePay(
          merchantCountryCode: 'CA',
          testEnv: true, // Set to false for production
        ),
        style: ThemeMode.system,
      ),
    );
    
    await displayPaymentSheet(provider);
  } on StripeException catch (e) {
    provider.setLoading(false);
    context.showSnackBar(
      'Payment sheet initialization failed: ${e.error.localizedMessage}',
      type: SnackBarType.warning,
    );
  } catch (e) {
    provider.setLoading(false);
    context.showSnackBar(
      'An unexpected error occurred. Please try again.',
      type: SnackBarType.warning,
    );
  }
}

```

3. Android Manifest.xml
```
<meta-data
    android:name="com.google.android.gms.wallet.api.enabled"
    android:value="true" />

```

**Comment by mihiravdevs** [comment]
I raised the same issue with the stipe support team, I am attaching the screenshot of reply

<img width="1124" alt="Screenshot 2024-08-20 at 6 31 26 PM" src="https://github.com/user-attachments/assets/bab858cc-33c9-40ce-832d-0f539fa97b19">

**Comment by DavidEcclesPH** [comment]
also experiencing this. further to your config above I have set the following in build.gradle as specified here https://developers.google.com/pay/api/android/guides/setup and https://docs.stripe.com/payments/accept-a-payment?platform=android&locale=en-GB : 
dependencies {
    implementation 'com.google.android.gms:play-services-wallet:19.4.0'
    implementation 'com.stripe:stripe-android:20.48.4'
}

**Comment by remonh87** [comment]
looks liek potential dupliate of #1887

**Comment by mihiravdevs** [comment]
@remonh87 I think https://github.com/flutter-stripe/flutter_stripe/issues/1887 is diffrent issue

**Comment by dapoadeleke** [comment]
Has anyone been able to resolve this issue?

**Comment by nurllhk** [comment]
I had the same problem, but a few days after I went into live mode and filled in all the information in the stripe account, it opened itself
