### ISSUE TITLE
 Could not resolve com.stripe:stripe-android:20.48.6 and Failed to list versions for com.stripe:financial-connections.

### ISSUE THREAD

**Issue by waleedasad23** [flutter-stripe/flutter_stripe#1904]
**Describe the bug**
I am getting an error when building my flutter project which uses the flutter_stripe package. 

Here is the **Error Message** that I am getting.

`
Execution failed for task ':app:checkDevDebugAarMetadata'.
> Could not resolve all files for configuration ':app:devDebugRuntimeClasspath'.
   > Could not resolve com.stripe:stripe-android:20.48.6.
     Required by:
         project :app
      > Could not resolve com.stripe:stripe-android:20.48.6.
         > Could not get resource 'https://jcenter.bintray.com/com/stripe/stripe-android/20.48.6/stripe-android-20.48.6.pom'.
            > Could not GET 'https://repo1.maven.org/maven2/com/stripe/stripe-android/20.48.6/stripe-android-20.48.6.pom'.
               > PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Failed to list versions for com.stripe:financial-connections.
         > Unable to load Maven meta-data from https://repo.maven.apache.org/maven2/com/stripe/financial-connections/maven-metadata.xml.
            > Could not HEAD 'https://repo.maven.apache.org/maven2/com/stripe/financial-connections/maven-metadata.xml'.
               > The server may not support the client's requested TLS protocol versions: (TLSv1.2, TLSv1.3). You may need to configure the client to allow other protocols to be used. See: https://docs.gradle.org/7.3.3/userguide/build_environment.html#gradle_system_properties
                  > PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
`
**Build Gradle**
`
dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.stripe:stripe-android:20.48.6'
}
dependencies {
       classpath  "com.android.tools.build:gradle:7.2.2"
`

**Expected behavior**
The error should not appear when building the project.

**Smartphone / tablet**
 - Device: Pixel 5 Android API 31
 - Package version: ^9.5.0+1
 - Flutter version 3.7.9

**Additional context**

**Comment by remonh87** [comment]
this looks like an issue with fetching the depedencies and not with our SDK. Cannot reproduce it
