### ISSUE TITLE
How to add shipping address form in flutter stripe sheet

### ISSUE THREAD

**Issue by Aung-Zaw-Phyo** [flutter-stripe/flutter_stripe#1905]
Like this 

![Screenshot 2024-08-31 000159](https://github.com/user-attachments/assets/e35da178-0cb4-41db-890c-9f95542be06d)

**Comment by remonh87** [comment]
The paymentsheet is only for collecting payment info. If you want to add shippingdetails make sure you collect them in the app and you can attach them either to the payment intent (using the stripe api from the backend) or add the shipping details to the `PaymentMethodParams`  when confirming a paymentintent
