### ISSUE TITLE
Setup intent cannot be use twice to register cards

### ISSUE THREAD

**Issue by angelorodem** [flutter-stripe/flutter_stripe#1913]
**Describe the bug**
When using the customer sheet, if you try to register more that one card without closing the widget, it gives an error, and there is no way to prevent it or automatically close on successful register of the card

**To Reproduce**

https://github.com/user-attachments/assets/a0d5dc01-8e57-4db6-b167-d58d38eb95ea

1. Insert a test card in the example app
2. try inserting another
3. it will give an error "you canot confirm this setupintent because it was already"
**Expected behavior**
allow adding another card without issues

**Smartphone / tablet**
 - Device: All android devices
 - OS: [e.g. iOS 13, Android 10]
 - Package version: ^11.0.0
 - Flutter version latest

**Comment by angelorodem** [comment]
what i'm trying to achieve is use the customerSheet to allow the user to control their payment methods in-app,
the charge is done off-session after a process has finished.

**Comment by remonh87** [comment]
You need to remove the setupintent in this case. The use of the customer sheet is to allow a customer to save payment methods upfront and it will be saved to the customer object

**Comment by angelorodem** [comment]
Worked, thank you.
