### ISSUE TITLE
This merchant is having trouble accepting your payment right now by using different payment method OR_BIBED_07. Getting this issue while clicking on Gpay button

### ISSUE THREAD

**Issue by jimeshait** [flutter-stripe/flutter_stripe#1916]
**Describe the bug**
In Test mode google pay works fine but as i switched to live mode it shows me above error in poppup

**To Reproduce**
1. Clicking on Pay with Gpay button in stripe sheet

![screenshot](https://github.com/user-attachments/assets/88f2f8e4-145f-401d-919c-19ed7534597c)

**Expected behavior**
Should see list of cards and on clicking card payment should be initiated

**Smartphone / tablet**
 - Device: Redmi 10A

**Additional context**
My other question is that is it necessary to fill https://docs.stripe.com/google-pay?platform=android#going-live and https://developers.google.com/pay/api/android/guides/test-and-deploy/publish-your-integration for google pay stripe flutter

**Comment by jimeshait** [comment]
please help me to get out of this issue

**Comment by remonh87** [comment]
you cannot use production environment unless google approved you for google pay. See https://docs.stripe.com/google-pay for more info

**Comment by jimeshait** [comment]
@remonh87 can you please share video link so that I can follow it and make Google pay enable.
