### ISSUE TITLE
Reduce Flutter Stripe Package Size(currently 24MB) to Optimise App Build Size

### ISSUE THREAD

**Issue by sharathguvvala** [flutter-stripe/flutter_stripe#1919]
**Is your feature request related to a problem? (please describe)**
The current size of the Flutter Stripe package (24 MB) significantly increases the overall app size.

**Describe the solution you'd like**
I would like to see the package size optimised, potentially by modularising the package, so that we can selectively include only the necessary components in their app.

For reference, in the native Stripe iOS SDK 23:
StripePaymentSheet: 2.7 MB
Stripe: 2.2 MB
StripePayments: 1.1 MB
StripePaymentsUI: 1.7 MB
StripeApplePay: 0.4 MB

**Comment by remonh87** [comment]
this is out of our power. I would recommend logging an issue to the stripe react native repo or stripe ios repo. We only create dart bindings around their sdk.
