### ISSUE TITLE
The future of intentCreationCallback method never completes

### ISSUE THREAD

**Issue by limonadev** [flutter-stripe/flutter_stripe#1949]
**Describe the bug**
After showing the users the PaymentSheet to enter their card details, I call `await Stripe.instance.intentCreationCallback` inside the `confirmHandler`, but that await never finishes so the app is stuck there.Also, there is no exceptions nor logs sent by the method.

**To Reproduce**
1. Call `Stripe.instance.initPaymentSheet` with the mode as `IntentMode.setupMode`, currencyCode as `'USD'` and `setupFutureUsage` as `IntentFutureUsage.OnSession`.
2. Inside the `confirmHandler` get the `clientSecret` and try to call `await Stripe.instance.intentCreationCallback()` with that secret.
3. Add a break point after that call.

**Expected behavior**
The break point should be reached after Stripe finishes the processing of `intentCreationCallback` method.

**Smartphone / tablet**
 - Device: iPhone 15 (Simulator)
 - OS: iOS 17
 - Package version: 11.1.0
 - Flutter version 3.19.6

**Additional context**
This was tested only on dev environment, as part of a migration from the old `stripe_payment` package to `flutter_stripe`, but all the configurations related to the new package were already done.

**Comment by remonh87** [comment]
hmm it looks like we do not set the confirmhandler correct. @jonasbark  it looks like the completer on android never yield a resutt back to the method channel even though the method is invoked from dart.

**Comment by jonasbark** [comment]
I tested the payment_sheet_deffered_screen.dart example where this is being used and have not experienced any issues - maybe I'm missing something here?

**Comment by limonadev** [comment]
@jonasbark [this future](https://github.com/flutter-stripe/flutter_stripe/blob/main/example/lib/screens/payment_sheet/payment_sheet_deffered_screen.dart#L120) never completes. If you add a print after the await, the print is never executed
