### ISSUE TITLE
Call to createPaymentMethod still uses previous publishable key after new publishable key is set on Stripe instance with applySettings(). 

### ISSUE THREAD

**Issue by moony-baby** [flutter-stripe/flutter_stripe#1954]
This is similar to [this issue](https://github.com/flutter-stripe/flutter_stripe/issues/1785), but for the publishable key.

The following will create a payment method in the account with publishable key pk_test_xxx:

```
Stripe.publishableKey = "pk_test_xxx";
await Stripe.instance.applySettings();

Stripe.publishableKey = "";
await Stripe.instance.applySettings();

final paymentMethod = await Stripe.instance.createPaymentMethod(
          params: PaymentMethodParams.card(
        paymentMethodData: PaymentMethodData(
          billingDetails: billingDetails,
        ),
      ));
```

To me this behaviour is unexpected, as I would expect the API call that creates the payment method to use the new publishable key (i.e. the empty string).

When you inspect Stripe and Stripe.instance after the second applySettings(), the publishableKey property is blank as expected, but clearly this does not apply to the API call, as the payment method is successfully created.

I would expect no payment method to be created, as the Stripe instance has an empty publishable key.

**Comment by remonh87** [comment]
I do not think this is how Stripe works. It looks like they see it as an invalid key so they do not apply it. This is unfortunately something outside our sphere of control (and something stripe decides for us) so I have to close it

**Comment by moony-baby** [comment]
Sorry, this may have been misleading. If you run the following code, the payment method is created in the account associated with pk1 rather than pk2.

```
Stripe.publishableKey = pk1;
await Stripe.instance.applySettings();

Stripe.publishableKey = pk2;
await Stripe.instance.applySettings();

final paymentMethod = await Stripe.instance.createPaymentMethod(
          params: PaymentMethodParams.card(
        paymentMethodData: PaymentMethodData(
          billingDetails: billingDetails,
        ),
      ));
```
