### ISSUE TITLE
Apple Pay / Google Pay are not showings when presenting the Stripe Payment Sheet

### ISSUE THREAD

**Issue by Tom3652** [flutter-stripe/flutter_stripe#1963]
**Describe the bug**
I am using this code : 

```
Stripe.merchantIdentifier = "mymerchant.bundle.id";
Stripe.urlScheme = "myscheme";
Stripe.publishableKey = "api_key"
String customerID = "customerIDFromBackend";
String secret = "secretFromBackend";
try {
  await Stripe.instance.applySettings();
  await Stripe.instance.initPaymentSheet(
    paymentSheetParameters: SetupPaymentSheetParameters(
        merchantDisplayName: "MyCompanyName",
        customerId: customerID,
        allowsDelayedPaymentMethods: true,
        applePay: const PaymentSheetApplePay(
          merchantCountryCode: "FR",
        ),
        googlePay: const PaymentSheetGooglePay(
            merchantCountryCode: "FR",
            testEnv: !kReleaseMode),
        style: ThemeMode.system,
        paymentIntentClientSecret: secret),
  );
  await Stripe.instance.presentPaymentSheet();
```

And it doesn't show either Google Pay or Apple Pay buttons. 

Note iOS : 
- I have done the configuration required on Apple Pay : i have uploaded the certificate to my Stripe account and registered in Xcode capibility the merchant ID
- I have a Banking card in my Apple Wallet 

Note Android : 
- My banking card could not be added to the Google Wallet (because my bank doesn't support it) but was added a payment method on my google account (for play store)

I am testing on real devices.

**To Reproduce**
1. Entering number 123-456-789 into the cardfield.
2. Tapping the confirm button.
3. Observe a failure with exception (including the part of the stack trace, belonging to this package) …

**Expected behavior**

**Smartphone / tablet**
 - Devices: iPhone XS Max, Motorola 8 
 - OS: iOS 18.0.1, Android 11
 - Package version: 11.2.0
 - Flutter version : 3.24.3

**Additional context**
I have searched multiple issues and read everything you said in your [discussion](https://github.com/flutter-stripe/flutter_stripe/discussions/1445) but this doesn't help.

I have also tried to run the example app but i have got so many build errors from the stripe_js (`/packages` directory) classes with attributes not found, and so on.. That i could not try with your code to see if it was working unfortunately but there may be a real issue here.

**Comment by Tom3652** [comment]
hi @remonh87 thanks for your quick reply, yes indeed : 

<img width="1367" alt="Capture d’écran 2024-10-15 à 18 46 42" src="https://github.com/user-attachments/assets/80f8f9a9-b88f-4c1f-9ac1-d00ead1f5bc0">

**Comment by Tom3652** [comment]
Okay @remonh87 i have the apple pay appearing on another phone (iPhone 12 Pro Max), i guess my own wallet has an issue 😅 

For Google Play do you confirm i simply need to have a valid card in my Google Wallet for it to appear as well ?  

Thanks for your help !

**Comment by Tom3652** [comment]
Alright thank you for your help, my app is already live on the store for few months so i will check how to update all this.

**Comment by Tom3652** [comment]
I confirm that Google Pay has appeared in debug mode after adding a Revolut card in my wallet and my app is under review for production. 
Thanks again for your time

**Comment by taqi92** [comment]
@remonh87 hi, is it also the same case for stripe payment sheet? i can't see gpay or apple pay option in my stripe paymentsheet but in your code people can see that with old app.

**Comment by remonh87** [comment]
@taqi92 yes. you need to have a valid wallet. also keep in mind if you are testing from india google pay is disabled.

**Comment by taqi92** [comment]
@remonh87 but when some of the user who have already wallet in their phone,can't see gpay & apple pay. is there any configuration changes i have to do in paymentsheet? i have passed true as it will go in prod.
