### ISSUE TITLE
Missing classes detected while running R8 Missing class com.stripe.android.pushProvisioning 

### ISSUE THREAD

**Issue by mitesh77** [flutter-stripe/flutter_stripe#1964]
**Describe the bug**
latest flutter_stripe: ^11.2.0 has some strange ERROR: Missing classes detected while running R8.
ERROR: R8: Missing class com.stripe.android.pushProvisioning.PushProvisioningActivity$g .

**To Reproduce**
just add the latest flutter_stripe: ^11.2.0 and do this simple command "flutter build apk". it will not working 
check this photo, but the debug working fine no problem. we are not able to make a release apk.
![Screenshot 2024-10-16 at 2 38 23 AM](https://github.com/user-attachments/assets/826edf6c-8a01-4f2d-86c3-a641700ad885)

**Smartphone / tablet**
 - OS: [Android lastest]
 - Package version: [11.2.0]
 - Flutter version [3.24.3]

**Comment by remonh87** [comment]
You have to follow the instructions set here: https://github.com/flutter-stripe/flutter_stripe?tab=readme-ov-file#android . When you have the proguard file the app compiles
