### ISSUE TITLE
Android WebView Permits JavaScript Execution The mobile application was found to permit JavaScript execution in its WebView implementation.

### ISSUE THREAD

**Issue by spdeol20** [flutter-stripe/flutter_stripe#1965]
Android WebView Permits JavaScript Execution The mobile application was found to permit JavaScript execution in its WebView implementation.
Whilst this setting can be essential for certain interactive web content, it can also introduce various security weaknesses
if the WebView is used to load untrusted or dynamically generated content. Vulnerabilities like Cross-Site Scripting
(XSS) have become a significant concern in such scenarios and could expose the application and its users to various
security threats. These threats include stealing user data, accessing local resources, or manipulating application
behaviour.
we crrently using flutter_stripe: ^11.0.0

**Comment by remonh87** [comment]
This is not related to Flutter Stripe
