### ISSUE TITLE
MinimumSystemVersion 11.0 or 12.0 of App store required .

### ISSUE THREAD

**Issue by jubayerhossain625** [flutter-stripe/flutter_stripe#1973]
**Describe the bug**
flutter_stripe of latest version using few day ago published app . But Today (22-OCT-2024) can't publish it . MinimumSystemVersion 11.0 or 12.0 of App store required . 

Please confirm and better way to approach provide now.
**To Reproduce**
1. Target Version Issue for IOS  13.0 on podfile 

**Additional context**

ITMS-90899: Macs with Apple silicon support issue - The app isn‘t compatible with the provided minimum macOS version of 11.0.0. It can run on macOS 12.0 or later. Please specify an LSMinimumSystemVersion value of 12.0 or later in a new build, or select a compatible version in App Store Connect. For details, visit: https://developer.apple.com/help/app-store-connect/manage-your-apps-availability/manage-availability-of-iphone-and-ipad-apps-on-macs-with-apple-silicon.

visited: 
https://developer.apple.com/documentation/bundleresources/information_property_list/lsminimumsystemversion

**Comment by remonh87** [comment]
this is something outside of our sdk and introduced by the newest xcode. 

if you add to info.plist
```yaml
<dict>
        <key>LSMinimumSystemVersion</key>
        <string><yourversion (e.g.13.0.0)</string>
    </dict>
```

the issue should be gone
