### ISSUE TITLE
Google pay button in payment sheet does not respect light / dark theme modes

### ISSUE THREAD

**Issue by cedvdb** [flutter-stripe/flutter_stripe#1975]
Currently the pay with google pay does not respect dark modes on android

![image](https://github.com/user-attachments/assets/2edfc5c9-7758-4215-9c65-7e6b25624e59)

_The above screenshot is from running the example_

As per the [guidelines](https://developers.google.com/pay/api/web/guides/brand-guidelines) it should look like the following.

![image](https://github.com/user-attachments/assets/853b636a-cc4c-4165-a7c7-fc4eb50abe7b)

According to Stripe assistant this is supported by stripe:

![image](https://github.com/user-attachments/assets/004eaa8d-fbd7-4dbf-91c7-a1dd3b9255a4)

**Comment by remonh87** [comment]
the express checkout is not the payment sheet. The sdk currently doesn't support providing a google pay button appearance. Feel free to add an issue at https://github.com/stripe/stripe-react-native/issues . When they implement it there we can take it over. For now I close it as not planned

**Comment by cedvdb** [comment]
> the express checkout is not the payment sheet 

I did not mention express checkout anywhere.

**Comment by remonh87** [comment]
the AI did :) but in order for us to fix it we need to wait for Stripe to implement this option in their sdk
