### ISSUE TITLE
Creating Payment method: Unhandled Exception: type 'Null' is not a subtype of type 'Map<String, dynamic>' in type cast

### ISSUE THREAD

**Issue by ericel** [flutter-stripe/flutter_stripe#198]
**Describe the bug**
I am getting the following error trying to use creae payment method for card:

> [VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: type 'Null' is not a subtype of type 'Map<String, dynamic>' in type cast
> #0      MethodChannelStripe.createPaymentMethod
> package:stripe_platform_interface/src/method_channel_stripe.dart:61
> <asynchronous suspension>
> #1      Stripe.createPaymentMethod
> package:flutter_stripe/src/stripe.dart:133
> <asynchronous suspension>

**To Reproduce**
```
final billingDetails = BillingDetails(
      email: 'email@stripe.com',
      phone: '+48888000888',
      address: Address(
        city: 'Houston',
        country: 'US',
        line1: '1459  Circle Drive',
        line2: '',
        state: 'Texas',
        postalCode: '77063',
      ),
    ); // mocked data for tests

    // 2. Create payment method
    final paymentMethod =
        await Stripe.instance.createPaymentMethod(PaymentMethodParams.card(
      billingDetails: billingDetails,
    ));
    print(paymentMethod);
```

**Smartphone / tablet**
 - Device: [e.g. iPhone X]
 - OS: [e.g. iOS 11]

**Comment by jonasbark** [comment]
Can you tell us how you resolved this?

**Comment by ericel** [comment]
I didn't solve it. I closed because there is an open case about this..
