### ISSUE TITLE
Payment sheet doesn't client secret for the connected account

### ISSUE THREAD

**Issue by WaliHassanKhan** [flutter-stripe/flutter_stripe#1990]
**Describe the bug**
when creating a payment sheet for a connected account you need to create a payment intent.
In nodejs the payment intent is created like this

` const subscription = await stripe.subscriptions.create({
            customer: customerId,
            items: [{ price: priceId }],
            payment_behavior: 'default_incomplete',
            expand: ['latest_invoice.payment_intent'],
            collection_method: 'charge_automatically',
        },
            {
                stripeAccount: accountNumber
            });
            res.json(subscription);
            `
            
in flutter we get the client id like this 

 `
     final paymentIntent =
          await createPaymentIntent(membershipDetails, stripeAccountId);
     final clientSecret =
          paymentIntent['latest_invoice']['payment_intent']['client_secret'];
      await Stripe.instance.initPaymentSheet(
        paymentSheetParameters: SetupPaymentSheetParameters(
          style: ThemeMode.dark,
          merchantDisplayName: 'Abc xyz',
          paymentIntentClientSecret: clientSecret,
          customerId: myConnectedCustomerID,
          billingDetails: BillingDetails(
            name: inputUserName,
            email: inputEmail,
          ),
        ),
      );
      await Stripe.instance.presentPaymentSheet();
 `

**To Reproduce**
1 create a connected account 
2 create a product for that connected account
3 create a customer for that connected account
4 create a subscription for that product
5 that subscription has a client secret. use that to create the paymentsheet

**Expected behavior**
The backend sends the client secret like this
pi_3QJhlUP0d1iRLOUJ1PdHiOXM_secret_LTx8jPhnqrnxoXdX20fmLIzlS

but the flutter error states

I/flutter (13604): Error: StripeException(error: LocalizedErrorMessage(code: FailureCode.Failed, localizedMessage: No such payment_intent: 'pi_3QJhlUP0d1iRLOUJ1PdHiOXM', message: No such payment_intent: 'pi_3QJhlUP0d1iRLOUJ1PdHiOXM', stripeErrorCode: resource_missing, declineCode: null, type: invalid_request_error))

**Smartphone / tablet**
 - Device: iphone 15 pro
 - Pixel 8

environment:
  sdk: ^3.5.0

**Additional context**

**Comment by moesaid** [comment]
Hey @WaliHassanKhan , I am having the same issue, any pointers could help me ?
