### ISSUE TITLE
PayPal WebView does not close on test's payment

### ISSUE THREAD

**Issue by FabrizioBilleciUNICT** [flutter-stripe/flutter_stripe#1992]
**Describe the bug**
When I use "PayPal" as the payment method in the PaymentIntent with presentPaymentSheet(), the web test screen opens with buttons to respond as authorized or declined. In both cases, the web page seems to load but doesn't close automatically, and nothing is triggered.

**To Reproduce**
This is how I open the PaymentSheet:
```
    await Stripe.instance.initPaymentSheet(paymentSheetParameters: SetupPaymentSheetParameters(
         setupIntentClientSecret: response.publishableKey,
         paymentIntentClientSecret: response.paymentIntent,
         customerEphemeralKeySecret: response.ephemeralKey,
         customerId: response.customer,
         merchantDisplayName: Configuration.appName,
    ));
    await Stripe.instance.presentPaymentSheet();
```

This is the back-end configuration:
```

    const paymentIntent = await stripe.paymentIntents.create({
        amount: price * 100,
        currency: 'eur',
        customer: customer.id,
        payment_method_types: [
               'card',
               'paypal' // <-- HERE I enable 'PayPal'
        ],
        metadata: paymentIntentMetadata
    });
```

This is what I see on the WebView's PaymentIntent object:
```
{
  "id": "pi_XXX",
  "object": "payment_intent",
  "amount": 150000,
  "amount_details": {
    "tip": {
    }
  },
  "automatic_payment_methods": null,
  "canceled_at": null,
  "cancellation_reason": null,
  "capture_method": "automatic_async",
  "client_secret": "pi_XXX_secret_SSS",
  "confirmation_method": "automatic",
  "created": 1731314574,
  "currency": "eur",
  "description": null,
  "last_payment_error": null,
  "livemode": false,
  "next_action": {
    "redirect_to_url": {
      "return_url": "stripesdk://payment_return_url/MY_APP_ID",
      "url": "https://pm-redirects.stripe.com/authorize/acct_XX...useWebAuthSession=true\u0026followRedirectsInSDK=true"
    },
    "type": "redirect_to_url"
  },
  "payment_method": "pm_XXXX",
  "payment_method_configuration_details": null,
  "payment_method_types": [
    "card",
    "paypal"
  ],
  "processing": null,
  "receipt_email": null,
  "setup_future_usage": null,
  "shipping": null,
  "source": null,
  "status": "requires_action"
}
```

**Expected behavior**
I would expect the WebView to close automatically. Additionally, if I manually close the WebView, the authorized payment result is received, and I can complete the flow. So, it doesn’t seem to be an API issue, but rather this missing WebView closure upon action. I wonder if I'm missing something on the configuration side, but I haven't found any information related to this. I am using AppLinks for other purposes, but I could use it to intercept any redirect events if needed.

**Smartphone / tablet**
 - Device: Motorola Edge 40
 - OS: Android 13
 - Package version: 11.2.0
 - Flutter version: Flutter (Channel stable, 3.24.4, on Linux Mint 21.3 5.15.0-124-generic, locale it_IT.UTF-8)

Thank you.

**Comment by remonh87** [comment]
You need to provide a correct return_url that is accepted by your app to return back. See: https://docs.flutter.dev/ui/navigation/deep-linking

**Comment by hbrhbr** [comment]
> You need to provide a correct return_url that is accepted by your app to return back. See: https://docs.flutter.dev/ui/navigation/deep-linking

I have done this but still the web view is not being closed automatically.
