### ISSUE TITLE
Stripe subscriptions through sdk doesn't process recurring payments

### ISSUE THREAD

**Issue by syedehsans1** [flutter-stripe/flutter_stripe#1993]
Creating subscriptions from sdk works fine but when stripe tries to charge customer for subsequent payments, payments fail. We talked to stripe customer support and their recommendation was to ask you guys here if you know what the problem might be. I can share code from my repo if required.
Attached is a screenshot of stripe support case. Please help.
<img width="791" alt="Screenshot 2024-11-12 at 13 21 25" src="https://github.com/user-attachments/assets/dfcf170e-a564-4d10-9c65-c906c7f4724e">

**Comment by remonh87** [comment]
I do not  understand Stripe's answer to be honest because we only collect the card info but providing the charges should be done on the backend. Can you check their integration docs to see if you miss something on the backend? https://docs.stripe.com/billing/subscriptions/build-subscriptions .
