### ISSUE TITLE
Wrong type of keyboard on some Android devices

### ISSUE THREAD

**Issue by ApofisXII** [flutter-stripe/flutter_stripe#201]
**The bug**
On Android, when adding a Credit Card, the component uses the standard keyboard, forcing user to switch to numeric keyboard for **every keypress**.

**Expected behavior**
Card element need to show up the _numeric keyboard_

**Smartphone / tablet**
Device: OnePlus 5
OS: Android 10
Package version: 1.0.2 and 1.0.1 both have the same issue
Flutter version: 2.3.0

![photo_2021-07-12 10 35 30](https://user-images.githubusercontent.com/5765363/125257521-c97dcc00-e2fd-11eb-8c5e-718cea0c0998.jpeg)

**Comment by jonasbark** [comment]
Please use Plugin version 1.1.0 
This issue is mentioned in the readme and tracked in https://github.com/flutter-stripe/flutter_stripe/issues/14

**Comment by ApofisXII** [comment]
@jonasbark not working even with 1.1.0.
I'll continue writing about this in #14
