### ISSUE TITLE
type 'Null' is not a subtype of type 'Map<String, dynamic>' in type cast 

### ISSUE THREAD

**Issue by MadhanAD** [flutter-stripe/flutter_stripe#207]
**Describe the bug**
From [this example](https://github.com/flutter-stripe/flutter_stripe/blob/main/example/lib/screens/webhook_payment_screen.dart) I was trying to integrate Stripe payment.

Getting null exception while calling `Stripe.instance.confirmPaymentMethod('clientSecret'
      PaymentMethodParams.card(
        billingDetails: billingDetails
      ))`

**Error log while calling confirmPaymentMethod()**
```
[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: type 'Null' is not a subtype of type 'Map<String, dynamic>' in type cast
#0      MethodChannelStripe.confirmPaymentMethod (package:stripe_platform_interface/src/method_channel_stripe.dart:89:44)
<asynchronous suspension>
#1      Stripe.confirmPaymentMethod (package:flutter_stripe/src/stripe.dart:219:29)
<asynchronous suspension>
#2      _HomeScreenState._handlePayPress (package:flutter_base_app/screens/android/HomeScreen.dart:99:27)
<asynchronous suspension>
```

**Smartphone**
 - Device: [e.g. iPhone 12 simulator]
 - OS: [e.g. iOS 14.5]
 - Package version: [e.g. 1.1.0]
 - Flutter version [e.g. 2.2.1]

**Comment by jonasbark** [comment]
This looks very similar to https://github.com/flutter-stripe/flutter_stripe/issues/206
can you try the solution from that ticket?

Gonna assign this to @remonh87 - we should handle it in Dart

**Comment by MadhanAD** [comment]
@jonasbark I have added a publishable key in my main.dart as shown in the example.
Still having the same issue.

**Comment by jonasbark** [comment]
Please provide an example project / code so we can reproduce it

**Comment by MadhanAD** [comment]
@jonasbark  Here is the [Sample Project](https://github.com/MadhanAD/flutter_base) to reproduce the issue

**Comment by MadhanAD** [comment]
@jonasbark  do you have any updates for me?
Did you find any issue on this code?

**Comment by remonh87** [comment]
I am working on it at the moment expect to have it fixed this week.
