### ISSUE TITLE
The cursorColor parameter of the CardField widget does not change the color

### ISSUE THREAD

**Issue by diegopq** [flutter-stripe/flutter_stripe#211]
**Describe the bug**
I have the CardField widget implemented in a payment form, I want to change the color of the cursor but when putting the required color it does not change, it happens to me both in an app without null safety and in one that has null safety active

**To Reproduce**
1. Indicate a color in the cursorColor parameter of the CardField widget

**Expected behavior**
Change the cursor color

**Smartphone / tablet**
 - Device: [iPhone 11]
 - OS: [e.g. iOS 14.6]
 - Package version: [1.1.0]
 - Flutter version [2.2.3.]

**Additional context**
[![ezgif.com-gif-makerc9e9392b0a769fe4.gif](https://s6.gifyu.com/images/ezgif.com-gif-makerc9e9392b0a769fe4.gif)](https://gifyu.com/image/BVjg)
### Code

`stripe.CardField(
            onCardChanged: (cardData) {},
            cursorColor: theme.colorScheme.primary,
            expirationHintText: AppLocalizations.current.monthYear,
            style: TextStyle(
              color: theme.colorScheme.onSurface,
              fontSize: 14.sp,
            ),
            decoration: InputDecoration(
              alignLabelWithHint: true,
              border: UnderlineInputBorder(
                borderSide: BorderSide(
                  color: theme.colorScheme.onSurface.withOpacity(0.3),
                ),
              ),
              focusedBorder: UnderlineInputBorder(
                borderSide: BorderSide(
                  color: theme.colorScheme.onSurface.withOpacity(0.3),
                ),
              ),
              enabledBorder: UnderlineInputBorder(
                borderSide: BorderSide(
                  color: theme.colorScheme.onSurface.withOpacity(0.3),
                ),
              ),
            ),
          ),`

**Comment by remonh87** [comment]
does the issue also happen on Android?

**Comment by diegopq** [comment]
> does the issue also happen on Android?

it also happens

**Comment by remonh87** [comment]
see answer at #321

**Comment by jonasbark** [comment]
@remonh87 this is about the CardField, so I'll reopen this Ticket

**Comment by nerder** [comment]
Any update on this?

**Comment by remonh87** [comment]
The cursor color can be changed on iOS but on Android it is not exposed in the Stripe sdk. Created ticket: https://github.com/stripe/stripe-react-native/issues/766

**Comment by remonh87** [comment]
fixed in version 2.2.0
