### ISSUE TITLE
Confirm payment method is only possible when there is a CardField widget present

### ISSUE THREAD

**Issue by tudor07** [flutter-stripe/flutter_stripe#213]
I have a flow where user navigates to a new screen where `CardField` widget exists. User inputs card on this screen then goes back. Now `CardField` widget is no longer present but I have the card details in a `CardFieldInputDetails` variable.
I call `confirmPaymentMethod` with `PaymentMethodParams.card()` params. 
I get the error:
```
Card details not complete
```

I guess this is because the library searches for a `CardField` widget and gets card details from it. In my case I no longer have a `CardField` widget and I also cannot pass `CardFieldInputDetails` parameter to `PaymentMethodParams.card()`.

I think we should be able to send `CardFieldInputDetails` parameter to `PaymentMethodParams.card()` so we are not obligated to have a `CardField` widget in the screen.

**Comment by remonh87** [comment]
@tudor07   implementing the suggested functionality would break PCI compliance for users of this library. Now we are using stripe Native components that are PCI compliant. For more info about what PCI compliance means see [link](https://stripe.com/en-gb-se/guides/pci-compliance).  

I think we should fix the issues. As alternative you can use the paymentsheet which does not have these issues.. 

Can you provide some logs and context of the issue:
- version of the library
- flutter version
- logs 
- simple reproduction scenario (prefarably in code)

**Comment by panchalAlpit** [comment]
@tudor07 and @remonh87 How can you solve this issue? I'm also getting the same thing.

   `. //initialization;

        CardDetails  _card;`


`. //onTap

    _card = CardDetails(number: "4242424242424242",expirationYear: 25,expirationMonth: 02,cvc: "254");

    _handleCreateTokenPress();`

    `//Call Method
      Future<void> _handleCreateTokenPress() async {
        if (dad == null) {
           return;
         }

       try {
         // 1. Gather customer billing information (ex. email)
          final address = Address(
          city: 'Houston',
         country: 'US',
         line1: '1459  Circle Drive',
         line2: '',
          state: 'Texas',
         postalCode: '77063',
        ); // mocked data for tests

       // 2. Create payment method
        final tokenData = await Stripe.instance.createToken(
        CreateTokenParams(type: TokenType.Card, address: address),
        );
     
        LLPrint(name: "ChgeckToken",value: tokenData.id);
        LLPrint(name: "ChgeckToken",value: tokenData.toString());
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(
          content: Text('Success: The token was created successfully!'+tokenData.toString())));
       return;
        } catch (e) {
          ScaffoldMessenger.of(context)
           .showSnackBar(SnackBar(content: Text('Error: $e')));
        rethrow;
       }
}`

Please help me out with this issue.
