### ISSUE TITLE
PresentPaymentSheet followed by confirmPaymentSheetPayment not working

### ISSUE THREAD

**Issue by neilhosey** [flutter-stripe/flutter_stripe#214]
Hi,
I'm trying to do the following:

      await Stripe.instance.presentPaymentSheet(
          parameters: PresentPaymentSheetParameters(
        clientSecret: _paymentIntent,
        confirmPayment: true,
      ));

      var result = await Stripe.instance.confirmPaymentSheetPayment();

but the confirmPaymentSheetPayment doesnt seem to return anything.  For example, if i hit X on the payment sheet, ie dont enter any info.  The confirm doesn't throw an exception or tell me no payment was made.  

I'm just to figure out how to confirm if they payment sheet actually took a payment or not.

**Comment by jonasbark** [comment]
Please tell us which plugin version you're using, Flutter version, device etc :)

**Comment by neilhosey** [comment]
Apologies!! i created in a rush.

Device: 
Android Emulator (Pixel 4 XL)

Version:
Flutter 2.0.6

Plugin Version:
latest 1.1.0

**Comment by remonh87** [comment]
This issue is fixed in the upcoming version which we will launch very soon.  Fixed with #209

**Comment by neilhosey** [comment]
oh amazing, thanks!

**Comment by KennyChan94P** [comment]
hi guys, can i have the code snippet which allows us to retrieve the successful Stripe payment response body as shown as the attachment? 
<img width="455" alt="image" src="https://user-images.githubusercontent.com/62973895/186068313-4172c799-5f68-4c4e-805c-b4a3ad4809da.png">

i really cannot manage to get the Stripe response through the plugin as both confirmPaymentSheetPayment() and presentPaymentSheet() are Future<void> functions.
unless i do a substring() on the paymentIntentClientSecret which i dont think it is a good idea.
