### ISSUE TITLE
PlatformException (PlatformException(Failed, Card details not complete, null, null))

### ISSUE THREAD

**Issue by robyhuzwandar** [flutter-stripe/flutter_stripe#215]
**Describe the bug**

ANDROID BUG

I got this error only when I run the app for the first time
PlatformException (PlatformException(Failed, Card details not complete, null, null))

but on the second try, it worked, even though I had filled out all the forms

**To Reproduce**

1. run the project for the first time
2. Entering all of the values into the card field.
2. Tapping the create new payment method button.
3. get error
4. enter again all of the values into the card field
5. click the add button
6. success

**Expected behavior**
1. run the project for the first time
2. Entering all of the value into the card field.
2. Tapping the create new payment method button.
3. success

![Screen Shot 2021-07-19 at 15 04 10](https://user-images.githubusercontent.com/20414047/126119079-aee0ae6a-0a53-4d85-8eca-530ca8cae58a.png)
![Screen Shot 2021-07-19 at 15 04 55](https://user-images.githubusercontent.com/20414047/126119087-8bbefd07-fbdc-4dcb-a94b-ae5a20bfb62f.png)

**Comment by jonasbark** [comment]
Can you reproduce this with the example app? If so please show us how - otherwise please create a minimal reproducible example. 
Thanks!

**Comment by EUGinsane** [comment]
I'm facing the same issues, this happens randomly, even tho the `complete` prop in `CardFieldInputDetails` is true, when using `Stripe.instance.createPaymentMethod()` or `Stripe.instance.confirmPayment()`, it throws that exception, retry it again and it works again.
