### ISSUE TITLE
Error occurred while while parsing card arguments on Android

### ISSUE THREAD

**Issue by imajercsik** [flutter-stripe/flutter_stripe#216]
On Android when I am entering the digits in the CardField widget, I am getting the following:

`[log] An error ocurred while while parsing card arguments, this should not happen, please consider creating an issue at https://github.com/flutter-stripe/flutter_stripe/issues/new`

Device: [e.g. OnePlus 6]
OS: [e.g. Oxygen OS 10.3.11]
Package version: [e.g. 1.1.0]
Flutter version [e.g. Channel stable, 2.2.3]

note: on iOS everything seems to work as expected

**Comment by jonasbark** [comment]
Which digits did you enter? Please provide more information so we can reproduce this issue.

**Comment by imajercsik** [comment]
In fact, I just only show the screen with the CardField and this appears in the log:

```
W/View    (28580): requestLayout() improperly called by android.widget.ImageView{90d0dba V.ED..... ......ID 0,0-84,55 #7f080139 app:id/icon} during layout: running second layout pass
W/View    (28580): requestLayout() improperly called by android.widget.FrameLayout{c99b46b VFE...... ......ID 156,33-1013,90 #7f0800b1 app:id/container} during layout: running second layout pass
W/View    (28580): requestLayout() improperly called by com.google.android.material.textfield.TextInputLayout{82c9bc8 V.ED..... ......ID 0,0-384,57 #7f080093 app:id/card_number_text_input_layout} during layout: running second layout pass
W/View    (28580): requestLayout() improperly called by com.google.android.material.textfield.TextInputLayout{7257461 V.ED..... ......ID 525,0-666,57 #7f08010e app:id/expiry_date_text_input_layout} during layout: running second layout pass
W/View    (28580): requestLayout() improperly called by com.google.android.material.textfield.TextInputLayout{86e4b86 V.ED..... ......ID 2625,0-2625,57 #7f0800c1 app:id/cvc_text_input_layout} during layout: running second layout pass
[log] An error ocurred while while parsing card arguments, this should not happen, please consider creating an issue at https://github.com/flutter-stripe/flutter_stripe/issues/new

```

**Comment by remonh87** [comment]
I think this is a bit pollution in the log but you can still enter a card number and it should parse again. Can you provide an example  like Jonas asked so we can test it on our side?

**Comment by GyuriMajercsik** [comment]
hi everyone, I created a sample example with the above issue. 
I adjusted the `WebhookPaymentScreen` implementation to have the problematic scenario in place. 

You can find it here: https://github.com/GyuriMajercsik/flutter_stripe/tree/216

There are two issues, from my point of view: 

1. Somehow the `rethrow` is not working. Basically, potential errors are swallowed and not visible to the developer. 
![image](https://user-images.githubusercontent.com/1482221/127470946-bcf4584d-8c2d-4fca-b5c4-b7430ba5f494.png)

2. The second problem is that `CardField` widget doesn't handle when the widget is changed. This happens in the above example. Basically the `onCardChanged` method is called on an `unmounted` widget, hence the `setState` call fails.

**Comment by illiashvedov** [comment]
Hi, is there any progress?

**Comment by remonh87** [comment]
Cannot reproduce this issue anymore on latest SDK. Thanks @GyuriMajercsik  for providing an example. I created a pr that will call set state only when the widget is mounted. I think this is a good practice nonetheless

**Comment by gyuri-fluttech** [comment]
Yes, I totally agree. Thanks for the plugin !
