### ISSUE TITLE
CardField screen error

### ISSUE THREAD

**Issue by dalton5** [flutter-stripe/flutter_stripe#219]
Hi,

I setup everything. The app is launching 

But I have the error below:

I can't find any clues on what is wrong.

Can you help? I struggle since 2 hours on this.

D/EGL_emulation(26511): eglMakeCurrent: 0xe566a8a0: ver 2 0 (tinfo 0xda105ad0)
W/View    (26511): requestLayout() improperly called by android.widget.ImageView{a7e2c6a V.ED..... ......ID 0,0-84,55 #7f080146 app:id/icon} during layout: running second layout pass
W/View    (26511): requestLayout() improperly called by android.widget.FrameLayout{d3d655b VFE...... ......ID 156,33-1097,90 #7f0800c2 app:id/container} during layout: running second layout pass
W/View    (26511): requestLayout() improperly called by com.google.android.material.textfield.TextInputLayout{76811f8 V.ED..... ......ID 0,0-384,57 #7f08009a app:id/card_number_text_input_layout} during layout: running second layout pass
W/View    (26511): requestLayout() improperly called by com.google.android.material.textfield.TextInputLayout{a9966d1 V.ED..... ......ID 525,0-666,57 #7f08011c app:id/expiry_date_text_input_layout} during layout: running second layout pass

My screen is looking like this:

![image](https://user-images.githubusercontent.com/8339768/126410439-815c67c7-bfdc-4f10-b1eb-0ce9c61a7e39.png)

**Comment by dalton5** [comment]
Ok I fixed my issue by using present paymentsheet.

**Comment by Kang-Kim1** [comment]
@dalton5 I am facing the same issue.. what do you mean by the "present paymentsheet"?

**Comment by casumatt** [comment]
Hi, any help here would be appreciated. On most devices the CardField works fine, however we do have some customers (currently they are only Android) who just see the CardField widget as blank with an underline, i.e. no Credit Card icon, hint text, etc. I have not been able to replicate the issue, but when I do load the screen with the widget I see the errors the same as dalton5 above, as below. I guess it's possible that these errors are causing the widget to crash on some device types or android versions?

W/View    ( 6556): requestLayout() improperly called by android.widget.ImageView{541d990 V.ED..... ......ID 0,0-112,74 #7f08013c app:id/icon} during layout: running second layout pass
W/View    ( 6556): requestLayout() improperly called by com.google.android.material.textfield.TextInputLayout{2b3b289 V.ED..... ......ID 0,0-496,76 #7f08008f app:id/card_number_text_input_layout} during layout: running second layout pass
W/View    ( 6556): requestLayout() improperly called by com.google.android.material.textfield.TextInputLayout{5def28e V.ED..... ......ID 700,0-896,76 #7f08010d app:id/expiry_date_text_input_layout} during layout: running second layout pass
W/View    ( 6556): requestLayout() improperly called by com.google.android.material.textfield.TextInputLayout{5a8baaf V.ED..... ......ID 3500,0-3500,76 #7f0800bf app:id/cvc_text_input_layout} during layout: running second layout pass
