### ISSUE TITLE
Retrieve saved cards

### ISSUE THREAD

**Issue by dalton5** [flutter-stripe/flutter_stripe#220]
Hi,

I use the plugin with paymentsheet.

How can I show the screen to retrieve saved cards in stripe account?

And in the payment sheet is there a way to add a checkbox to save the card?

I did not find it.

Thanks,

**Comment by jonasbark** [comment]
There's no way to achieve this with the plugin itself - you'll need a backend for that.
If you're using the payment sheet then this functionality is indeed built-in.

**Comment by dalton5** [comment]
payment sheet then this functionality is indeed built-in

That's a really good news.

So I use this code:

`                String intent = await StripeAppService.instance
                  .createTipPayment(stripePaymentInput);  // Call to my api

              final paymentMethod = await Stripe.instance.initPaymentSheet(
                  paymentSheetParameters: SetupPaymentSheetParameters(customerId: custId,
                      paymentIntentClientSecret: intent,
                      merchantCountryCode:
                          ApplicationContext.instance.currentLanguage!.name,
                      merchantDisplayName: 'Wetip'));

              Stripe.instance.presentPaymentSheet(
                  parameters: PresentPaymentSheetParameters(
                      clientSecret: intent, confirmPayment: true));`

My customer has one card saved in his stripe profile but it doesn't show the cards.

How can I enable this part?

**Comment by Ajai-Joseph** [comment]
how to enable that 'save card for future purchases' checkbox?
