### ISSUE TITLE
How to show saved cards in Payment sheet?

### ISSUE THREAD

**Issue by dalton5** [flutter-stripe/flutter_stripe#224]
Based on my old issue paymentsheet seems to include this functionality to show saved cards

That's a really good news.

So I use this code:

`                  String intent = await StripeAppService.instance
                  .createTipPayment(stripePaymentInput);  // Call to my API

                final paymentMethod = await Stripe.instance.initPaymentSheet(
                  paymentSheetParameters: SetupPaymentSheetParameters(customerId: custId,
                      paymentIntentClientSecret: intent,
                      merchantCountryCode:
                          ApplicationContext.instance.currentLanguage!.name,
                      merchantDisplayName: 'Wetip'));

              Stripe.instance.presentPaymentSheet(
                  parameters: PresentPaymentSheetParameters(
                      clientSecret: intent, confirmPayment: true));`

My customer has one card saved in his stripe profile but it doesn't show the cards.

How can I enable this part?

I see this:

![image](https://user-images.githubusercontent.com/8339768/126507908-e3e51870-482d-461c-8812-12eee0b413ac.png)

_Originally posted by @dalton5 in https://github.com/flutter-stripe/flutter_stripe/issues/220#issuecomment-883959995_

**Comment by jeff-odopass** [comment]
Hello, for me it displays the saved cards before showing the screen in your post.
I did nothing particular to enable this, you should double-check that your backend correctly handle the card datas with Stripe.

Good luck !

**Comment by dalton5** [comment]
In the flutter code did you add other parameters than my code?

I am going to double check my api call.

Thanks,

**Comment by jeff-odopass** [comment]
Yes, I just noticed you didn't included the `customerEphemeralKeySecret`, which may be the missing part in your `initPaymentSheet`

**Comment by dalton5** [comment]
Ok it's better because now I can see the option to save the card for next cards at the bottom with ephemeralkey setup. I create ephemeralkey at every payment intent. is it the good way?

But even when I save the card, I do not have the UI to choose the card.

Can you please share how you create the payment intent?

My code is in .net for the API call:

           `            var service = new PaymentIntentService();
            var createOptions = new PaymentIntentCreateOptions
            {
                PaymentMethodTypes = new List<string>
                {
                    "card",
                }, ReceiptEmail = user.EmailAddress,
                Metadata = new Dictionary<string, string> { { "from", user.Id.ToString()}, { "to", AIdUser.Heros.Id.ToString() } },
                Customer = user.CustomerStripeId,
                Amount = CalculateOrderAmount(createRequest.Price),
                Currency = createRequest.Currency,
                ApplicationFeeAmount = applicationFeeAmount,
                TransferData = new PaymentIntentTransferDataOptions
                {
                    Destination = AIdUser.Heros.StripeAccountId
                },
               
               };

            var ephemeralService = new EphemeralKeyService();
            var options = new EphemeralKeyCreateOptions
            {
                Customer = user.CustomerStripeId,
                StripeVersion = "2020-08-27"
            };
            var ephemeralservice = new EphemeralKeyService();
            var key = ephemeralService.Create(options);

            PaymentIntent paymentIntent = service.Create(createOptions);
`


What I have now:

![image](https://user-images.githubusercontent.com/8339768/126659356-e9cb9ca7-6489-48e6-8396-bcd7cb0309a0.png)

**Comment by jamesblasco** [comment]
You can check the example server version that integrates this here:

https://github.com/flutter-stripe/flutter_stripe/blob/ae51739acb9704c5e51da853458942a895924f22/example/server/src/index.ts#L491

**Comment by dalton5** [comment]
Thanks I did everything.

And I still get the same issue. I went to ask support to stripe. They explained to me that it must be a payment method and not a card which is the old API.

I setup everything but we can't get it to work.

Can you please confirm to me that for you it works? This feature is enabled in the flutter version please?

**Comment by remonh87** [comment]
I think your code looks good from Flutter side and I use something similar in my app. It looks like something is incorrect in the backend. Can you try to run your app code and talk to our example server (see readme on how to run it)?

**Comment by dalton5** [comment]
Ok I am gonna try. I use the stripe api in .net. Maybe there is an issue. Thanks,

**Comment by jeff-odopass** [comment]
Hi there, you may have forgotten to save the paymentMethod using the correct Stripe webhook. It is done after a successfull payment is made.
It is not in the flutter plugin docs so you should check the official Stripe docs related to tour backend stack.

Hope it helps

**Comment by dalton5** [comment]
Ok it works with the example.

![image](https://user-images.githubusercontent.com/8339768/126775273-bb907a3e-b8a3-4d0c-97ff-73a8b184c3c8.png)

So it should come from my API call. I investigate more

**Comment by dalton5** [comment]
Ok I found the issue. I sent id of the ephemeral key instead of the ephemeral secret. 

It works great now! Thanks a lot! I close the case.

**Comment by pedrumiranda** [comment]
Does this solution still works in the most recent version of flutter_stripe ?

**Comment by RajatKhoware** [comment]
> Ok I found the issue. I sent id of the ephemeral key instead of the ephemeral secret.
> 
> It works great now! Thanks a lot! I close the case.

Thank you for you have raised this issue on GitHub i am also facing the same issue for past two weeks read all docs, stack over flow ans, but nothing work just found this GitHub raised issue and finally my payment sheet is also showing saved cards  thanku 🙏🏻

**Comment by cedraz** [comment]
Valeu gostosos, tava procurando aqui
