### ISSUE TITLE
iDeal Payments: Confirm Setup Intent returns "You must provide a `return_url` when confirming a SetupIntent with the payment method type ideal."

### ISSUE THREAD

**Issue by JFMSAlmeida** [flutter-stripe/flutter_stripe#225]
I'm trying to configure iDeal Payments in my flutter application using your lib. The functionality that I want is the described in this [link](https://stripe.com/docs/payments/ideal/set-up-payment?platform=web). The code below is how I'm implementing it (I've previously made a request to my backend to create a Setup Intent and it returns successfully with the client secret).

```
PaymentMethodParams params = PaymentMethodParams.ideal(
    billingDetails: BillingDetails(name: name, email: email),
    bankName: bankName
);

Map<String, String> data = new Map();
data['return_url'] = 'example/url';

SetupIntent setupIntent = await Stripe.instance.confirmSetupIntent(stripeClientSecret, params, data);

```
The problem is that it returns an exception when I invoke the confirmSetupIntent. The exception itself is very confusing and non-explicative, it returns: _"Tried calling: \[\]("id")"_.

After some digging with the debugger inside your code I've figure out the real problem. Inside your code, in the  _method_channel_stripe.dart_ file, when invoking the _confirmSetupIntent_ method it returns an exception as result from the following function:

```
final result = await _methodChannel
    .invokeMapMethod<String, dynamic>('confirmSetupIntent', {
  'setupIntentClientSecret': setupIntentClientSecret,
  'params': data.toJson(),
  'options': options
});
```

The exception type is _invalid_request_error_ and its message is _You must provide a `return_url` when confirming a SetupIntent with the payment method type ideal._.
So I think the real problem is that the request is thinking that I'm not sending the return url, however I'm sending it inside the data parameter of the confirmSetupIntent method, since it is not possible to send it inside any other parameter, or as a parameter. 

So, I would like to know if the problem is in my implementation or is in the lib that doesn't support the extra parameter `return_url`. Thanks for your help.

My version is 1.1.0 and the full log of the original exception is:

> Tried calling: \[\]("id")
flutter: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      _$_$_SetupIntentFromJson (package:stripe_platform_interface/src/models/setup_intent.g.dart:11:13)
#2      new _$_SetupIntent.fromJson (package:stripe_platform_interface/src/models/setup_intent.freezed.dart:302:7)
#3      _$SetupIntentFromJson (package:stripe_platform_interface/src/models/setup_intent.freezed.dart:16:23)
#4      new SetupIntent.fromJson (package:stripe_platform_interface/src/models/setup_intent.dart:57:7)
#5      MethodChannelStripe.confirmSetupIntent (package:stripe_platform_interface/src/method_channel_stripe.dart:114:24)
<asynchronous suspension>
#6      Stripe.confirmSetupIntent (package:flutter_stripe/src/stripe.dart:259:27)
<asynchronous suspension>

**Comment by jonasbark** [comment]
The url_scheme parameter can be set as part of the `initialize` method (urlScheme).  Please check that and report back.

**Comment by JFMSAlmeida** [comment]
Yep, it worked, thanks. Issue solved.
