### ISSUE TITLE
Apple pay asks billing address, is it possible to disable it?

### ISSUE THREAD

**Issue by awaik** [flutter-stripe/flutter_stripe#226]
**Describe the bug**
Usually Apple pay doesn't ask billing address. But if I implement it with this plugin, is displays error that user must add billing address.

![photo_2021-07-22 21 00 45](https://user-images.githubusercontent.com/5330807/126687703-ead5ca7d-c5d5-4209-805a-91be7bd9ca53.jpeg)

**Comment by jonasbark** [comment]
@jamesblasco can you please have a look?

**Comment by awaik** [comment]
Also in old plugin was separate property for this.

https://github.com/jonasbark/flutter_stripe_payment/blob/7948a80a07cf9d01e795b1f3bb33fd21ed7093f0/lib/src/apple_pay_payment_request.dart#L10

``` List<RequiredBillingAddressFields>? requiredBillingAddressFields;```

**Comment by jamesblasco** [comment]
The current implementations is very similar and billing address is not required 
https://github.com/flutter-stripe/flutter_stripe/blob/df2f9c13aa7c93e32a633838489970a6d44364aa/packages/stripe_platform_interface/lib/src/models/apple_pay.dart#L83-L89

I have just tried the Apple Pay example in the simulator and I can confirm there is no need for billing address and it does not ask for that. 

It looks like you have one selected by default that is not valid. Try to remove it or fix the billing address.
