### ISSUE TITLE
Apple Pay with requiredShippingAddressFields [postalAddress] is broken

### ISSUE THREAD

**Issue by hyphense** [flutter-stripe/flutter_stripe#228]
When requiredShippingAddressFields contains "postalAddress", the Apple Pay sheet is shown but times out.

```
   List<ApplePayContactFieldsType> requiredShippingAddressFields = [];
    requiredShippingAddressFields.add(ApplePayContactFieldsType.name);
    requiredShippingAddressFields.add(ApplePayContactFieldsType.emailAddress);
    //requiredShippingAddressFields.add(ApplePayContactFieldsType.postalAddress);

    // 1. Present Apple Pay sheet
    await Stripe.instance.presentApplePay(
      ApplePayPresentParams(
        requiredShippingAddressFields: requiredShippingAddressFields,
        cartItems: [
          ApplePayCartSummaryItem(
            label: 'Mxxxxx',
            amount: '10.00',
          ),
        ],
        country: 'DE',
        currency: 'EUR',
      ),
    );
```

This code works until i un-comment postalAddress.

**Comment by jamesblasco** [comment]
This looks like a problem with the native Stripe sdk, I will try to find the root of the problem. 

Looks like requiredShippingAddressFields has been deprecated
https://developer.apple.com/documentation/passkit/pkpaymentrequest/1619228-requiredshippingaddressfields

**Comment by hyphense** [comment]
Thanks for looking into it.

I have tried this on device (14.6. on 11 pro max).

Also tried using pay.ApplePayButton from the pay package. I can select an address (payment and shipping) in the apple pay sheet with this one, but no address-data in the paymentResult.

Using this payment profile:

```
{
  "provider": "apple_pay",
  "data": {
    "merchantIdentifier": "merchant.mxxxxx",
    "displayName": "xxxxx",
    "merchantCapabilities": ["3DS", "debit", "credit"],
    "supportedNetworks": ["amex", "visa", "discover", "masterCard"],
    "countryCode": "DE",
    "currencyCode": "EUR",
    "requiredBillingContactFields": ["postalAddress"],
    "requiredShippingContactFields": ["emailAddress", "name", "postalAddress"],
  }
}
```

**Comment by mklepaczko** [comment]
Same problem here when using the field 'ApplePayContactFieldsType.postalAddress,'

**Comment by remonh87** [comment]
@mklepaczko  can yo add some additional context please? Which device, version of the library, version of Flutter? It would help us determining the issue

**Comment by remonh87** [comment]
cannot reproduce this anymore. Feel free to reopen it in case you run into some issues.

**Comment by omar-selo** [comment]
I have this issue #988
