### ISSUE TITLE
Payment sheet: Get result if payment failed or successed

### ISSUE THREAD

**Issue by dalton5** [flutter-stripe/flutter_stripe#229]
Hi,

Is there a way to get a result if the payment from the paymentsheet has been a success or has failed?

I just see presentpaymentsheet return future<void>, but if I have the option confirmpayment I would like to know if the payment successed or not to go to the next steps. 

How can I achieve this?

Thanks,

**Comment by remonh87** [comment]
We integrated the new result object from the stripe sdk and this will be part of the new version that we will launch this weekend.

**Comment by dalton5** [comment]
Wow amazing! Thanks a lot!

**Comment by emme1009** [comment]
@remonh87 when will the release be live ?

**Comment by omaralmgerbie** [comment]
> We integrated the new result object from the stripe sdk and this will be part of the new version that we will launch this weekend.

its not implemented in `v1.2.0`?, and is it implemented in master or not?

**Comment by remonh87** [comment]
It is part of version 1.2.0  In case the user cancels the paymentsheet or an error will come from Stripe we will throw an `StripeException` containing localised context regarding the unforseen event. You can deviate between `error` and `cancelled` by using the `code` field. This is in line with the Stripe SDK

**Comment by kevindree** [comment]
> It is part of version 1.2.0 In case the user cancels the paymentsheet or an error will come from Stripe we will throw an `StripeException` containing localised context regarding the unforseen event. You can deviate between `error` and `cancelled` by using the `code` field. This is in line with the Stripe SDK

I am facing the same issue, I didn't get what you mean, Can you please explain it in detail.

**Comment by Aung-Zaw-Phyo** [comment]
> We integrated the new result object from the stripe sdk and this will be part of the new version that we will launch this weekend.

How to implete this, Sir.
I still get null value in flutter_stripe: ^11.0.0 version.
