### ISSUE TITLE
Any Ali pay or Wechat pay example?

### ISSUE THREAD

**Issue by coodysk8er** [flutter-stripe/flutter_stripe#234]
Can someone help add an example of how to have wechat pay or ali pay?  Or give some general hints so I can help add this example or implement it.  Thanks

**Comment by coodysk8er** [comment]
can someone kindly provide some general advice?  Thanks

**Comment by remonh87** [comment]
Stripe has many different payment methods for which we do not have a full example. I would advice reading the official Stripe docs: https://stripe.com/docs/payments/alipay .

**Comment by coodysk8er** [comment]
@remonh87  Thank you for your advice. 

I did read the official documentation before trying, but the confusing part is flutter_stripe doesn't expose the method `confirmPayment` on the client-side as official doc.

So I tried the following codes but still got an error of "Result should not be null"
Can you help point out where I was wrong ? Thank you again.

flutter code:
`

      //request server to create payment intent wraped in transaction
      final transaction = await _createTransaction(
          PaymentMethodType.PAYMENT_METHOD_TYPE_ALIPAY);
  
      final clientSecret = transaction.paymentIntentClientSecret;

      final method = await sp.Stripe.instance
          .createPaymentMethod(sp.PaymentMethodParams.alipay());

     //not sure confirmPaymentMethod is the correct method to call for alipay or any third party payment methods.
      await sp.Stripe.instance
          .confirmPaymentMethod(clientSecret, sp.PaymentMethodParams.alipay());
`


server-side for creating payment intent in go, following the official doc where actually indicates be done on the client-side.
https://stripe.com/docs/payments/alipay/accept-a-payment

Intent created successfully and passed to the client
`

      params := &stripe.PaymentIntentParams{
		Amount: stripe.Int64(50), //test
		Currency: ToStripeCurrency(transaction.Currency),
		PaymentMethodTypes: []*string{
			PaymentMethodTypeToStripe(paymentMehtodType),
		},
		Customer: &transaction.ProviderCustomerId,
                PaymentMethodData: &stripe.PaymentIntentPaymentMethodDataParams{
			Alipay: &stripe.PaymentMethodAlipayParams{},
		},
                PaymentMethodOptions:  &stripe.PaymentIntentPaymentMethodOptionsParams{
			Alipay: &stripe.PaymentIntentPaymentMethodOptionsAlipayParams{},
		}
	}
	pi, err := paymentintent.New(params)

`

**Comment by zmGitHub** [comment]
＋１

**Comment by remonh87** [comment]
I will look into it in the weekend when I have a bit more time.  btw we have a method called `confirmPayment` (before version 1.2.0 known as `confirmPaymentMethod` => Stripe renamed it in their sdk recently)

**Comment by coodysk8er** [comment]
Thank you, @remonh87 

my bad, didn't upgrade to 1.2.0 and it worked with `confirmPayment` instead. I can help add example code or just refer to the following snippet.

btw, can we add wechatPay in PaymentMethodParams, should be minimal work as we already had the general  confirmPayment? (Stripe doc : https://stripe.com/docs/payments/wechat-pay/accept-a-payment)

**Make sure 1.2.0 or above**

flutter code:
`

      //request server to create payment intent wraped in transaction
      final transaction = await _createTransaction(
          PaymentMethodType.PAYMENT_METHOD_TYPE_ALIPAY);
  
      final clientSecret = transaction.paymentIntentClientSecret;

      final method = await Stripe.instance
          .createPayment(PaymentMethodParams.alipay());

     //not sure confirmPaymentMethod is the correct method to call for alipay or any third party payment methods.
      await sp.Stripe.instance
          .confirmPaymentMethod(clientSecret, PaymentMethodParams.alipay());
     
     //should popup a web view to load Stripe test payment page to mock a Alipay payment in test env

`


server-side `_createTransaction` for creating payment intent, following the official doc 
https://stripe.com/docs/payments/alipay/accept-a-payment

`

      params := &stripe.PaymentIntentParams{
		Amount: stripe.Int64(50), //test
		Currency: ToStripeCurrency(transaction.Currency),
		PaymentMethodTypes: []*string{
			PaymentMethodTypeToStripe(paymentMehtodType),
		},
		Customer: &transaction.ProviderCustomerId,
                PaymentMethodData: &stripe.PaymentIntentPaymentMethodDataParams{
			Alipay: &stripe.PaymentMethodAlipayParams{},
		},
                PaymentMethodOptions:  &stripe.PaymentIntentPaymentMethodOptionsParams{
			Alipay: &stripe.PaymentIntentPaymentMethodOptionsAlipayParams{},
		}
	}
	paymentIntent, err := paymentintent.New(params)
        ...

`

**Send  paymentIntent to client**

**Comment by remonh87** [comment]
@coodysk8er  thanks for the example. WeChat is not yet supported in the React Native Stripe sdk. When it is integrated there we will pick it up. https://github.com/stripe/stripe-react-native/issues/52

**Comment by coodysk8er** [comment]
@remonh87 I think wechat pay is merged in 0.2.0 of stripe-react-native , thanks!

https://github.com/stripe/stripe-react-native/pull/486
