### ISSUE TITLE
presentApplePay sometimes throws with "Canceled by user" without even presenting ApplePay

### ISSUE THREAD

**Issue by santiagomboc** [flutter-stripe/flutter_stripe#236]
**Describe the bug**
Sometimes, when attempting to presentApplePay, method will return with a "Canceled by user" message before even presenting ApplePay.

**To Reproduce**
1. Attempt to presentApplePay with the following code: 
```dart
await Stripe.instance.presentApplePay(ApplePayPresentParams(
      cartItems: [ApplePayCartSummaryItem(amount: amount, label: "ExampleLabel")],
      country: 'CA',
      currency: 'CAD',
));
```
2. After several attempts, Canceled by user will be thrown before presenting ApplePay.

**Expected behavior**
ApplePay to be shown to the user.

**Smartphone / tablet**
 - Device: iPhones and iPhone simulators
 - OS: iOS
 - Package version: 1.0.2
 - Flutter version: 2.2.0

**Comment by niklaesAtMonta** [comment]
Have you tried updating to 1.2.0? :)
