### ISSUE TITLE
The code in the example does not build

### ISSUE THREAD

**Issue by kwstasarva** [flutter-stripe/flutter_stripe#237]
**Describe the bug**
The code in the example/lib/screens folder does not build 

**To Reproduce**
1. Clone the repo
2. Follow the instructions to run the example 

**Expected behavior**
The example app should run properly 

**Smartphone / tablet**
 - Package version: [commit: 9804530]
 - Flutter version [2.0.3]

**Additional context**
The code in the example/lib/screens seems to use outdated code of the SDK.

**Comment by remonh87** [comment]
Make sure you follow the steps described in: 

https://github.com/flutter-stripe/flutter_stripe#contributing . You need to run `melos bootstrap`

**Comment by kwstasarva** [comment]
> Make sure you follow the steps described in:
> 
> https://github.com/flutter-stripe/flutter_stripe#contributing . You need to run `melos bootstrap`

I need to run that in case I want to contribute. I just need to run the example app. And the instructions to do so are described under the "Run the example app" as referenced in the docs. I will try  to run `melos bootstrap` as well now.

**Comment by remonh87** [comment]
yeah sorry our bad we still need to merge one pr that fixes the right dependencies

**Comment by kwstasarva** [comment]
No problem. I followed your instructions and everything seems to work smoothly now. Thank you @remonh87 :)
