### ISSUE TITLE
Google Pay with PaymentSheet in Production

### ISSUE THREAD

**Issue by emme1009** [flutter-stripe/flutter_stripe#241]
**Describe the bug**
I use the paymentSheet with integrated Google Pay feature.
But when used with live stripe key, I get the error `Unexpected Developer Error, please try again later`.  and after that the paymentSheet says `Internal Error occured`.

BTW Im using the stripe connect platform to pay directly to a connected account. (Its working perfectly fine in testmode)
AND I already got approved from google to use google pay in my production app.

Can someone guide me? What is the correct approach for using Google Pay + paymentSheet + Stripe Connect platform? Is there another setup needed than setting `googlePay: true,` inside the `SetupPaymentSheetParameters`??
          

**To Reproduce**
1. Using stripe in livemode
2. getting approved from google to use google pay
3. try to pay with google pay button from the paymentSheet

**Smartphone / tablet**
 - Device: Pixel 3 Emulator & Xiaomi Mi 9T Pro
 - OS: Android 11
 - Package version: 1.2.0
 - Flutter version: 2.2.2.

**Comment by remonh87** [comment]
If I understand the [Stripe docs](https://stripe.com/docs/google-pay) correctly you also need to add:
```xml
<application>
  ...
  <meta-data
    android:name="com.google.android.gms.wallet.api.enabled"
    android:value="true" />
</application>
```

to the manifest.

**Comment by emmaxCreative** [comment]
Thank you that helped. Now it works perfectly fine.
