### ISSUE TITLE
Plugin version 1.1.0, with stripe_platform_interface 1.2.0 causing errors

### ISSUE THREAD

**Issue by niklaesAtMonta** [flutter-stripe/flutter_stripe#243]
**Describe the bug**
It seems like the StripePlatform used in flutter_stripe is updating automatically to a newer version.
Which seems to trigger an error.
I am runnning flutter_stripe 1.1.0, but the package is gathering stripe_platform_interface 1.2.0 which is suddenly causing problems.

It seems related to the newest flutter_stripe update (1.2.0), with breaking changes:
"Rename confirmPaymentMethod to confirmPayment accordingly with the change in the native SDK"

I am not using these methods in the app, so it is not related to that.

**To Reproduce**
Install flutter_stripe version 1.1.0, and try to build ipa or apk.

**Expected behavior**
The app builds successfully

**Smartphone / tablet**
 - OS: [iOS 13, Android 10]
 - Package version: [e.g. 1.1.0]
 - Flutter version [2.2.3]

**Additional context**
Stacktrace dump:
``` dart
../programs/flutter_2_2_3/.pub-cache/hosted/pub.dartlang.org/flutter_stripe-1.1.0/lib/src/stripe.dart:219:45: Error: The method 'confirmPaymentMethod' isn't defined for the class 'StripePlatform'.

 - 'StripePlatform' is from 'package:stripe_platform_interface/src/stripe_platform_interface.dart' ('../programs/flutter_2_2_3/.pub-cache/hosted/pub.dartlang.org/stripe_platform_interface-1.2.0/lib/src/stripe_platform_interface.dart').

Try correcting the name to the name of an existing method, or defining a method named 'confirmPaymentMethod'.

      final paymentMethod = await _platform.confirmPaymentMethod(

                                            ^^^^^^^^^^^^^^^^^^^^
```

**Temporary solution **
I updated the plugin to 1.2.0, and it solved the issue, but i think it is wrong that I cannot set a fixed version, without it breaking because of dependency updates.

**Comment by remonh87** [comment]
that should not happen IMO since we lock the versions in the flutter_stripe package. I will investigate it.

**Comment by remonh87** [comment]
you are right we made a mistake with versioning.  You adding the following to your pubspec.yaml :

```yaml
dependency_overrides:
  stripe_platform_interface: '1.1.0'
  stripe_ios: '1.1.0'  
  stripe_android: '1.1.0' 
```
