### ISSUE TITLE
PaymentSheet not opening on Tablet in Landscape mode

### ISSUE THREAD

**Issue by emmaxCreative** [flutter-stripe/flutter_stripe#245]
**Describe the bug**
When I use a tablet in landscape and want to open the payment screen then the screen automatically rotates to open the paymentSheet. Which fails and shows an infinite loading spinner.

Checkout Page (setting up the paymentSheet)
![image](https://user-images.githubusercontent.com/58904080/127354983-1248dbc9-99a2-42ac-88bb-4f5b0ad11525.png)

Next Step automatically rotates the screen but never opens the Sheet
![image](https://user-images.githubusercontent.com/58904080/127355212-e2fafc28-b247-4509-9db0-b292099387f7.png)

No errors are thrown and the paymentSheet data is all set. But it does not open. Probably because of the forced rotation it loses a state somewhere. 

BTW: When using the tablet in Portrait then the paymentSheet opens without problems

**To Reproduce**
1. trigger paymentSheet in landscape mode on a tablet

**Expected behavior**
Open PaymentSheet in Landscape mode as well

**Smartphone / tablet**
 - Device: Pixel C Emulator
 - OS: Android 11
 - Package version: 1.2.0
 - Flutter version 2.2.2

**Comment by remonh87** [comment]
Thanks for reporting I can reproduce it (it happens also on phone on landscape).  Funny thing is that I do not see any logs that result in a crash of some sort.

I think https://github.com/stripe/stripe-android/issues/3878 may be related to it.  @jonasbark  You have a bit more knowledge about Android bindings, can you shine your light on this one?

**Comment by jonasbark** [comment]
Stripe Android SDK itself must force it to portrait only. When we find the time we will open a ticket at their repository for investigation.

**Comment by brnunes-stripe** [comment]
Hi @emmaxCreative, this was actually a bug on the Android SDK and has been fixed on v17.1.0, please try again once the dependency has been upgraded on the flutter project. We also plan on supporting landscape at some point in the future.

**Comment by arcangeltech** [comment]
hello , i face the same problem with the paymentsheet (it opens only in portrait mode ) . Any solution please?

**Comment by remonh87** [comment]
@arcangeltech  this should be actually fixed in the latest version of the library. Let me know if this is the case.

**Comment by brnunes-stripe** [comment]
Hi @arcangeltech,
To clarify, we fixed the bug that was raised in this ticket (stuck in loading). We did not implement support for landscape, so it will still switch to portrait. This is in our backlog, we just haven't been able to get to it yet.

**Comment by jamesblasco** [comment]
I will close this issue as we are using a newer version that solves it.
