### ISSUE TITLE
Cardfield forcefully taking focus from other text fields

### ISSUE THREAD

**Issue by huzaif23** [flutter-stripe/flutter_stripe#246]
**Describe the bug**
Cardfield forcefully taking focus from other text fields therefore I cannot insert text to other textfields.

**To Reproduce**
1. Add Cardfield widget to the screen.
2. Cardfield won't allow other text fields to gain focus

**Expected behavior**
Cardfield should not be forcefully taking focus over other textfields

**Smartphone / tablet**
 - Device: [Emulator, POCO X3]
 - OS: [Android 10,11]
 - Package version: [1.2.0]
 - Flutter version [ 2.0.0.]

**Additional context**
It was working fine before the update (1.2.0)

**Comment by jonasbark** [comment]
There is an existing issue:
https://github.com/flutter-stripe/flutter_stripe/issues/14

The underlying cause is tracked in https://github.com/flutter/flutter/issues/86480 
For now, we recommend using a custom Flutter native Card Field for Android users.

**Comment by niklaesAtMonta** [comment]
@jonasbark i do not believe it is the same issue as #14, because the issue has appeared on version 1.2.0, and was not an issue on version 1.1.0?

**Comment by Spyingaround** [comment]
@jonasbark I'm working on a project with a TextFormField and a CardField from flutter_stripe 1.2.0.
I'm experiencing this issue on Android only as well. 

It was working fine on flutter_stripe 1.1.0.

**Comment by huzaif23** [comment]
@niklaesAtMonta  yes it was working fine before the update, but I think it's related to the issue: flutter/flutter#86480 created by @jonasbark.

@Spyingaround currently the only workaround is to use a custom form using flutter text field widget but I think it may break PCI compliance.
