### ISSUE TITLE
App crashes after going back from 3DS challenge

### ISSUE THREAD

**Issue by juleshyacinthe** [flutter-stripe/flutter_stripe#247]
**Describe the bug**
I'm using `confirmSetupIntent` to save my customers' credit card details. I guess it's worth noticing that I'm using the `dangerouslyUpdateCardDetails` method as the card input is broken in my Android builds.
It opens the 3DS challenge, and after I complete it, if I go back using the app drawer, my app crashes. Going back using the back button of my phone has the expected behavior.
So far this only happened in pre-production tests using real-world credit cards. I didn't run into this issue during testing.

**To Reproduce**
1. Enter card details
2. Call `Stripe.instance.dangerouslyUpdateCardDetails(card);`
3. Call `Stripe.instance.createPaymentMethod(PaymentMethodParams.card(billingDetails: billingDetails));`
4. Create a `SetupIntent` from my server
5. Call `Stripe.instance.confirmSetupIntent(secret, paymentMethodParams);` using the secret from my server
6. 3DS challenge occurs
7. Complete bank's challenge
8. Go back to the app using the app drawer
9. Get this in logs: 
`E/libEGL  (27773): call to OpenGL ES API with no current context (logged once per thread)`
`W/System  (27773): A resource failed to call end. `
`W/System  (27773): A resource failed to call end. `

**Expected behavior**
App should stay opened and the rest of the code should execute (in my case, sending the payment method's ID to my server to save it in my database).

**Smartphone / tablet**
 - Device: Google Pixel 4a
 - OS: Android 11
 - Package version: 1.1.2
 - Flutter version 2.2.3

**Comment by jonasbark** [comment]
Do you have test credit card details where this is reproducible?

**Comment by juleshyacinthe** [comment]
Here is a video capture of the issue (made on Pixel 3a API 30 simulator):
![3DS2 crash](https://user-images.githubusercontent.com/10943906/127628517-05e71379-247c-4edd-9759-148d2da00923.gif)

As soon as I tap the phone's button to show currently opened apps, I get the logs I posted in my first message and although the 3DS challenge doesn't fail or freeze or anything, when it tries to go back to the app it goes back to the phone's home.

**Comment by jonasbark** [comment]
Thanks for the information. I was able to reproduce this - the example implementation was not complete and didn't support 3DS checks.

A PR will be added in a few minutes.
