### ISSUE TITLE
Text Input focus error

### ISSUE THREAD

**Issue by mzincube161** [flutter-stripe/flutter_stripe#255]
**Describe the bug**
If the Card Element is on the same screen as another Text Input. The other text input cannot be edited as the card element automatically grabs the focus hence not allowing other text inputs to be used.

**To Reproduce**
Steps to reproduce the behaviour:
Add the card element and then a text input on the same screen and try to edit the second text input after adding a card number.

**Expected behavior**
The text input cannot be edited as the card element automatically grabs focus.

**Smartphone / tablet**
 - Device: [e.g. iPhone X]
 - OS: [e.g. iOS 13, Android 10]
 - Package version: 1.2.0
 - Flutter version [e.g. 2.0.0.]

**Additional context**

**Comment by jamesblasco** [comment]
Could you share the code part where you use the CardField? 

Do you have autofocus:true?

**Comment by mzincube161** [comment]
Auto focus is turned to false. Below is the CardField Code: 

`CardField(
          onCardChanged: (CardFieldInputDetails details) {
            cardDetails = details;
          },
          autofocus: false,
          enablePostalCode: false,
          numberHintText: 'Card number',
          expirationHintText: 'Exp',
          cvcHintText: 'Cvc/cvv',
          postalCodeHintText: 'Postcode',
          decoration: InputDecoration(
            border: InputBorder.none,
          ),
        ),`

Below is the TextField code: 

`TextFormField(
                    controller: street,
                    keyboardType: TextInputType.text,
                    decoration: InputDecoration(
                      contentPadding: EdgeInsets.symmetric(
                        vertical: 5,
                        horizontal: 5,
                      ),
                      border: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(20),
                      ),
                      enabledBorder: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(20),
                      ),
                      errorBorder: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(20),
                        borderSide: BorderSide(color: Colors.red),
                      ),
                      hintText: 'Enter street',
                      helperStyle: TextStyle(
                        color: Colors.grey[300],
                      ),
                      suffixIcon: Icon(
                        Icons.security,
                        color: Colors.grey[300],
                      ),
                    ),
                    validator: (val) {
                      return val.isEmpty ? 'Please enter street name' : null;
                    },
                  ),`

Another slight thing I noticed is that whether autofocus is true or false the Card always auto focuses anyway. The reason for this is because I believe in the class called _MethodChannelCardField. Autofocus is passed but it's not being used. Instead autoFocus is automatically set to true in the Focus widget. Link to the code is here at line 343 [https://github.com/flutter-stripe/flutter_stripe/blob/main/packages/stripe/lib/src/widgets/card_field.dart](url)

**Comment by taqi92** [comment]
requestLayout() improperly called by com.google.android.material.textfield.TextInputLayout{5b94797 V.ED..... ......ID 0,0-384,58 #7f080097 app:id/card_number_text_input_layout} during layout: running second layout pass

this message throws in log for this particular issue too, i can take character values but not numeric value

**Comment by jonasbark** [comment]
This issue is tracked on https://github.com/flutter-stripe/flutter_stripe/issues/14
