### ISSUE TITLE
Confirm not capture payment

### ISSUE THREAD

**Issue by jacklondon90** [flutter-stripe/flutter_stripe#256]
Hi everyone, with the PaymentSheetScreen I want to confirm the payment and later capture it how can I achieve this? Using this method 
`  await Stripe.instance.initPaymentSheet(
          paymentSheetParameters: SetupPaymentSheetParameters(
              paymentIntentClientSecret: stripe[0]['client_secret'],
              applePay: false,
              googlePay: false,
              style: ThemeMode.light,
              merchantCountryCode: 'US',
              merchantDisplayName: 'Upaynet',
              testEnv: true));`
`    await Stripe.instance.presentPaymentSheet(
          parameters: PresentPaymentSheetParameters(
              clientSecret: stripe[0]['client_secret'], confirmPayment: true));`

**Comment by remonh87** [comment]
can you explain what you want to capture? The paymentsheet provides a result (success or failed) what do you miss?

**Comment by jacklondon90** [comment]
I want to authorize the card and later charge it, and by the way is there are an option to save card?

**Comment by iamshaunwu** [comment]
@remonh87 hi, when you mention that paymentsheet provides a result, what is the code to obtain this result?
i used catch (e) to obtain any possible errors. for success how can we go about coding it? appreciate if you can enlighten with some good examples.
