### ISSUE TITLE
Any way to use google pay without Pay plugin?

### ISSUE THREAD

**Issue by tijnar** [flutter-stripe/flutter_stripe#264]
**Is your feature request related to a problem? (please describe)**
I am having a problem integrative google pay with stripe. for the Google pay sheet, I have used the Pay plugin. But I don't know what the issue is.  I am unable to show the google pay button in my application.

**Describe the solution you'd like**
It would be great if there is a similar to `presentApplePay` function for android also.

**Describe alternatives you've considered**
No other alternatives

**Additional context**

**Comment by jonasbark** [comment]
This will be available with the upcoming version within the next one or two weeks

**Comment by jamesblasco** [comment]
This has been implemented in version 1.3.0. You can see an example here:
https://github.com/flutter-stripe/flutter_stripe/blob/main/example/lib/screens/wallets/google_pay_stripe_screen.dart
