### ISSUE TITLE
When trying  with Invalid card details in  Live  throwing   'Null' is not a subtype of type 'Map<String, dynamic>' in type cast

### ISSUE THREAD

**Issue by SoorajSoman** [flutter-stripe/flutter_stripe#265]
First of all thanks for this great library. I'm  trying  stripe payment with Invalid card details (valid card  number and invalid expiry or ccv combination ) in  Live mode throwing exception   'Null' is not a subtype of type 'Map<String, dynamic>' in type cast while Stripe.instance.confirmPaymentMethod is called.I checked the other issues reported with same exception but it is of different context hence raising as a new one. 

I'm following  [https://github.com/flutter-stripe/flutter_stripe/blob/main/example/lib/screens/webhook_payment_screen.dart](https://github.com/flutter-stripe/flutter_stripe/blob/main/example/lib/screens/webhook_payment_screen.dart) implementation

**To Reproduce**
1. Entering number test card 4242  into the cardfield in live 
2. Tapping the confirm button.
3. Observe a failure with exception (including the part of the stack trace, belonging to this package)
'Null' is not a subtype of type 'Map<String, dynamic>' in type cast while Stripe.instance.confirmPaymentMethod is called.

**Expected behavior**
 Any response from library  to handle invalid card details 

**Additional context**
 Could any one please confirm whether this is achievable with current version of library and implementation I'm following?

**Comment by remonh87** [comment]
@SoorajSoman  I need a bit more information about it which version of the library do you use? Also can you provide me the full stack trace?

**Comment by SoorajSoman** [comment]
@remonh87  I'm using   flutter_stripe: ^1.0.2  since 1.1.0 and 1.1.2 is having  some issues with input focus of android number keyboard in different OS version,I reverted back to 1.0.2.Please find the stacktrace below ,it happens when stripe.instance.confirmPaymentMethod  is called 

>  ViewRootImpl@44c3b5d[MainActivity](22527): updateBoundsLayer: shouldReparent = false t = android.view.SurfaceControl$Transaction@d7ac30c sc = Surface(name=Bounds for - com.***/com.example.***.MainActivity@0)/@0xbfae455 frame = 1017
I/flutter (22527): #0      MethodChannelStripe.confirmPaymentMethod (package:stripe_platform_interface/src/method_channel_stripe.dart:89:44)
I/flutter (22527): <asynchronous suspension>
I/flutter (22527): #1      Stripe.confirmPaymentMethod (package:flutter_stripe/src/stripe.dart:219:29)
I/flutter (22527): <asynchronous suspension>
I/flutter (22527): #2      PaymentScreenState._handlePayPress (package:****/Service/StripePayment.dart:171:25)
I/flutter (22527): <asynchronous suspension>
I/flutter (22527): #3      _LoadingButtonState._loadFuture (package:***/UIComponents/LoadingButton.dart:37:7)
I/flutter (22527): <asynchronous suspension>

**Comment by remonh87** [comment]
@SoorajSoman  in version `1.2.0 ` we made significant improvements related to the response objects . I would ask you to try it out on this version and let me know if the issue exist.

**Comment by SoorajSoman** [comment]
@remonh87 It was not 1.1.2 rather 1.2.0 I tried and had the  issue with the keyboard  in some Android devices (marshmallow and  pie OS ), the main blocker CardFields were taking input from keyboard or even not focussing  ,So thats the reason switching back to 1.0.2 in which happy path was working as expected  but  got the above issue. if needed I can try with 1.2.0 again and update over here.

**Comment by remonh87** [comment]
@SoorajSoman  there were some issues in the previous libraries with result objects which we fixed form version 1.2.0 would be great if you can verify if the issue still occurs
