### ISSUE TITLE
Payment Sheet doesn't allow requires_confirmation status for PaymentIntent

### ISSUE THREAD

**Issue by akerr501** [flutter-stripe/flutter_stripe#269]
**Is your feature request related to a problem? (please describe)**
I would like the ability to use the payment sheet while using the requires_confirmation status as described [here](https://stripe.com/docs/payments/intents#intent-statuses). When generating the PaymentIntent on the server for a destination charge, I specify the customer's payment method as so

` const paymentIntent = await stripe.paymentIntents.create({`
      `payment_method_types: ['card'],`
      `amount: Math.round(amount* 100),`
      `currency: 'usd',`
      `application_fee_amount: Math.round(fee * 100),`
      `customer: customerID,`
      `payment_method: payMethodID,`
      `transfer_data: { `
       `destination: connectID,`
      `},`
    `});`

However, when I try to present the payment sheet, I receive this error.

> I/flutter (12375): StripeException(error: LocalizedErrorMessage(code: FailureCode.Failed, localizedMessage: A PaymentIntent with status='requires_payment_method' is required.
> I/flutter (12375): The current PaymentIntent has status requires_confirmation.

**Describe the solution you'd like**
I would like a payment sheet to be presented to have the customer confirm the payment with a payment method saved on file when the status of the PaymentIntent is requires_confirmation, similarly to as shown on the Stripe documentation mentioned above.

**Describe alternatives you've considered**
The reason I want to use the requires_confirmation status is I need to have the customer's payment information saved on the Stripe Dashboard, and when the status of the PayementIntent is requires_payment_method, it allows customers to pay by using a card without saving the information for later. I attempted to use a custom_flow for the payment sheet to see if this would work around the issue, however, I ran into a different issue with the FlowController. I am willing to try again to see if a custom_flow would work after #268 is merged, but I would prefer to see support for the different PaymentIntent status

**Comment by remonh87** [comment]
If you add a `setupIntentClientSecret` instead of a `paymentintentSecret` to initPaymentSheet you will get what you want.

**Comment by akerr501** [comment]
This fixed the error that I was receiving, but the payment sheet seems to be stuck loading on something. I don't receive any error logs and I cannot tap out of the payment sheet. Here is how I am initializing and presenting the payment sheet, please let me know if there are any other changes I need to make or if you need any more information such as flutter doctor.

    // 3. initialize the payment sheet
      await Stripe.instance.initPaymentSheet(
        paymentSheetParameters: SetupPaymentSheetParameters(
          customFlow: false,
          applePay: false,
          googlePay: false,
          merchantCountryCode: "US",
          merchantDisplayName: "Merchant Name",
          testEnv: true,
          customerId: paymentSheetData['customer'],
          setupIntentClientSecret: paymentSheetData['paymentIntent'],
          customerEphemeralKeySecret: paymentSheetData['ephemeralKey'],
        ),
      );

     // 4. display the payment sheet.
      await Stripe.instance.presentPaymentSheet(
        parameters: PresentPaymentSheetParameters(
          clientSecret: paymentSheetData['paymentIntent'],
          confirmPayment: true,
        ),
      );

And here is the content of `paymentSheetData`

> I/flutter (13234): {ephemeralKey: ek_test_YWNjdF8xSUVweU9FZTdIb2Nhc3VXLHdCbWdrYzNpZTl4TnpWc0hIamJUZzVOOVAwQXJWRXY_00wZEMpxIu, paymentIntent: pi_3JN0iYEe7HocasuW0rzKeZkm_secret_va6dh5b4HitNX66pFc73Ypvt1, customer: cus_JzEmMXvvJBEshM}


![image](https://user-images.githubusercontent.com/58118891/128924145-6ba56094-d76e-422a-b448-4ecb1ac5770f.png)

**Comment by AdnanAppify** [comment]
@akerr501 Have you found any solution?

**Comment by remonh87** [comment]
@akerr501  if you use your credentials on the example app do you experience the same?  It looks like there is sth missing in initialising Stripe.  Check for example: https://github.com/flutter-stripe/flutter_stripe/blob/0ee2bf30613fb5cacde7efc25e80851f93044df1/example/lib/main.dart#L10

**Comment by akerr501** [comment]
@remonh87 I don't think that's the issue as I can properly display the payment sheet using the code from the example, it only gets stuck loading when I try the code above for the requires_confirmation intent. But here is how I am initializing Stripe, the only difference is I don't include merchant identifier or URL scheme, although I don't know exactly what those are for anyways.

    void main() async {
       WidgetsFlutterBinding.ensureInitialized();
       Stripe.publishableKey = publishableKey;
       // issue persists whether or not this line is included
       // Stripe.stripeAccountId = myAccountID;
       await Stripe.instance.applySettings();
       runApp(FirestoreSetup());
    }

**Comment by AdnanKazi** [comment]
@akerr501 is right that should not be the problem there is something else that needs to be done can you please fix it

**Comment by remonh87** [comment]
I spend some time on it and it is hard to reproduce it on our example app. Can you provide us some sample code?

**Comment by remonh87** [comment]
ah I see the problem now you are not using a setupintent on the backend  but based on the key you provided I noticed you are using a normal payment intent. In that case you need to provide a value for `paymentIntentClientSecret` and leave `setupIntentClientSecret ` empty.  

I think there is something missing on the backend in that case. I created several payment intents and setup intents using the example app and the payment sheet is shown correctly.  I used exact the same code as provided above.

The only think I can tell you is double check the Android settings: https://github.com/flutter-stripe/flutter_stripe#android and the backend response but I do not see there is an issue with the library.
