### ISSUE TITLE
Sending signal. PID: 30835 SIG: 9 App Crash on Confirm Payment Call

### ISSUE THREAD

**Issue by tijnar** [flutter-stripe/flutter_stripe#270]
Everything is running  perfectly but when I try to call `Stripe.instance.confirmPayment()`, my app crashes and the output is _Sending signal. PID: 30835 SIG: 9_ . Is there any solution for this?

**My Code:**
```
Pay _payClient = Pay.withAssets([ 'google_pay_payment_profile.json' ]);

final _paymentItems = [
  PaymentItem(
  label: 'Total',
  amount: '300',
  status: PaymentItemStatus.final_price,
 )];
                            
 try {
        final result = await _payClient.showPaymentSelector(
                                        provider: PayProvider.google_pay,
                                              paymentItems: _paymentItems  );

         final token = result['paymentMethodData']
                      [ 'tokenizationData']['token']; 

          final tokenJson = Map.castFrom(json.decode(token));
         var tokenId = tokenJson['id'];
         final params = PaymentMethodParams.cardFromToken(token: tokenId );
         final response = await fetchPaymentIntentClientSecret();
         final clientSecret = response['client_secret'];
 
         await Stripe.instance.confirmPayment(clientSecret, params);

} catch (e) {
 ScaffoldMessenger.of(context).showSnackBar(
       SnackBar(content: Text('An error occourred $e')));
 }

```

**Error**

Sending signal. PID: 30835 SIG: 9

**Comment by jonasbark** [comment]
Please provide all the information from the bug template:

> 
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 1. Entering number 123-456-789 into the cardfield.
> 2. Tapping the confirm button.
> 3. Observe a failure with exception (including the part of the stack trace, belonging to this package) …
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Smartphone / tablet**
>  - Device: [e.g. iPhone X]
>  - OS: [e.g. iOS 13, Android 10]
>  - Package version: [e.g. 1.0.0]
>  - Flutter version [e.g. 2.0.0.]
> 
> **Additional context**
> Add any other context about the problem here.
>

**Comment by jonasbark** [comment]
@tijnar ?

**Comment by tijnar** [comment]
Sorry for my inactiveness. 

**Bug Description**
I got just _Sending signal. PID: 30835 SIG: 9_ message and gets my app crash when `Stripe.instance.confirmPayment()` this statement tries to execute. 

**Steps to Reproduce**
1. show payment sheet working fine
2. get token from the payment sheet is fine
3. get client secret from is also fine
4. crash when confirming payment

**Expected Behavior**
confirm payment needs to execute successfully. 

Smartphone - Redmi Note 5
Flutter Version - 2.2.3
ext.kotlin_version = '1.5.0'
distributionUrl=https\://services.gradle.org/distributions/gradle-6.7-all.zip
dependency - classpath 'com.android.tools.build:gradle:4.1.2'

**Comment by jamesblasco** [comment]
Hello @tijnar, we can not help if you don't provide more details about the crash.

So you have debug the app and you are sure that the problem is happening in `confirmPayment` and not in `showPaymentSelector` no?

Is there not a call stack or any more text related to the crash? Could you debug the android side with Android studio?
