### ISSUE TITLE
IDEAL Payment

### ISSUE THREAD

**Issue by madhanshan04** [flutter-stripe/flutter_stripe#271]
Hi , 

I want to implement ideal payment method for my application , unfortunately i could not able to test the ideal payment gateway in our example package . Here below i have submitted the error message which i got while executed the package .

Please advise

Unhandled Exception: SocketException: OS Error: Connection refused, errno = 111, address = 10.0.2.2, port = 57470
E/flutter ( 6443): 

Thanks and regards
madhan Shan

**Comment by remonh87** [comment]
Hi you,

You need to check that your stripe backend is running on the correct port + that the ipaddress is 10.0.2.2. Else you need to change the configuration in the example app to the correct ipaddress. 

Make sure that you also forward the web hooks properly to the backend as described in https://stripe.com/docs/payments/ideal/accept-a-payment?platform=react-native#test-your-integration .  For example I use the stripe client .
