### ISSUE TITLE
Android - CardField displays alpha-numeric keyboard instead of numeric keyboard.

### ISSUE THREAD

**Issue by gospuzic** [flutter-stripe/flutter_stripe#272]
**Describe the bug**
On Android SM - G965F - CardField displays alpha-numeric keyboard instead of numeric keyboard. 

**To Reproduce**
1. Add CardField to screen.
2. Navigate to screen from another screen.

**Expected behavior**
A numeric keyboard should be displayed.

**Smartphone / tablet**
 - Device: Samsung S9+
 - OS: Android 8.0.0
 - Package version: 1.2.0
 - Flutter version 2.2.3

**Additional context**

**Comment by jonasbark** [comment]
This issue is tracked on https://github.com/flutter-stripe/flutter_stripe/issues/14
