### ISSUE TITLE
Android - CardField ignores autoFocus

### ISSUE THREAD

**Issue by gospuzic** [flutter-stripe/flutter_stripe#273]
**Describe the bug**
CardField is not respecting autoFocus:false sretting.

**To Reproduce**
1. Add CardField with autoFocus false
2. Navigate to screen
3. CardField has autofocus

**Expected behavior**
CardField should not have autofocus

**Smartphone / tablet**
 - Device: Samsung
 - OS: Android 8.0.0
 - Package version: 1.2.0
 - Flutter version:2.13.4

**Additional context**

**Comment by jonasbark** [comment]
This issue is tracked on https://github.com/flutter-stripe/flutter_stripe/issues/14
