### ISSUE TITLE
How to pay with saved cards

### ISSUE THREAD

**Issue by awaik** [flutter-stripe/flutter_stripe#274]
I've implemented  payment with new cards, apple pay. Also made possibility to save cards.

But, I can't find the way how to pay with saved cards from UI with `PaymentIntentsFutureUsage.OnSession` parameter.

Can you please point to the method or how to do this feature?

![photo_2021-08-11 13 41 06](https://user-images.githubusercontent.com/5330807/129028528-1af50424-c511-4a08-ac50-50fe91d0d47a.jpeg)

**Comment by jonasbark** [comment]
You will have to query your backend services which in turn can call the Stripe APIs to return the saved cards.
Another and possibly easier alternative is to use the payment sheet which supports this use case out of the box.

**Comment by awaik** [comment]
Thank you, made it with `cardFromMethodId`. Just didn't know that is possible to use this method without `cvc` property.

```
Stripe.instance.confirmPayment(
      intentId,
      PaymentMethodParams.cardFromMethodId(paymentMethodId: card.cardId),
    );
```
