### ISSUE TITLE
Possibility of Adding/Deleting cards in PaymentSheet

### ISSUE THREAD

**Issue by UsamaKarim** [flutter-stripe/flutter_stripe#275]
I would like to see if there is a possibility of adding & removing cards from the Payment sheet?

By **Adding** I mean that customers can only add cards & do not pay.

**Comment by Lyba97** [comment]
I am also looking forward to it.

**Comment by Lyba97** [comment]
I am also looking forward to it.

**Comment by jonasbark** [comment]
This is unrelated to this plugin and a feature request for the Stripe Android plugin and already tracked here:
https://github.com/stripe/stripe-android/issues/3715

**Comment by jonasbark** [comment]
https://github.com/stripe/stripe-android/issues/3715#issuecomment-896937428
> I'm currently working on the deletion feature, it should be part of our next release.

**Comment by thorsten-stripe** [comment]
@UsamaKarim setup (non-payment) mode is already supported by providing a SetupIntent clientSecret instead of a PaymentIntent one: https://github.com/flutter-stripe/flutter_stripe/blob/main/packages/stripe_platform_interface/lib/src/models/payment_sheet.dart#L32-L36

**Comment by UsamaKarim** [comment]
> @UsamaKarim setup (non-payment) mode is already supported by providing a SetupIntent clientSecret instead of a PaymentIntent one: [https://github.com/flutter-stripe/flutter_stripe/blob/main/packages/stripe_platform_interface/lib/src/models/payment_sheet.dart#L32-L36](https://github.com/flutter-stripe/flutter_stripe/blob/main/packages/stripe_platform_interface/lib/src/models/payment_sheet.dart?rgh-link-date=2021-08-16T14%3A37%3A11Z#L32-L36)

Thanks for the help @thorsten-stripe :appreciated:
