### ISSUE TITLE
Card field input not working on iOS 

### ISSUE THREAD

**Issue by Lyba97** [flutter-stripe/flutter_stripe#277]
I am trying to integrate Flutter-stripe into an app but I have observed that CardField input works on android but when I run it in iOS simulator, it does not work. **I cannot enter anything in the card field**. 

**Smartphone / tablet**
 - Device: iPhone 12 Pro max - simulator
 - OS: iOS 14.4

**Additional Issue**
I also observed that when I tried to work with Payment sheet it also didn't appear on iOS while it was working fine on android.

**Comment by jonasbark** [comment]
Please check existing issues: https://github.com/flutter-stripe/flutter_stripe/issues/242
