### ISSUE TITLE
[PaymentSheet] Allow us to set a default country

### ISSUE THREAD

**Issue by ollydixon** [flutter-stripe/flutter_stripe#285]
When opening the card details panel allow us to add a default country so that payments can be processed faster for local apps.

**Comment by logic-emotion** [comment]
@ollydixon This would be a great improvement to the UX. Hopefully this is a relatively easy feature to implement.

**Comment by ollydixon** [comment]
@logic-emotion yes it would because I see some customers dropping off costing us money during the country selection phase as it's not good for counties that have multiple names (UK for example)

**Comment by jamesblasco** [comment]
That sounds like a great idea! Consider creating this issue in the native sdks as a feature request. We can't do much from here: 
https://github.com/stripe/stripe-ios/
https://github.com/stripe/stripe-android

**Comment by logic-emotion** [comment]
@ollydixon from browsing the iOS Stripe repo, I was able to discover that the region a device is set to will determine which country is automatically selected in the payment sheet. The default iOS Simulator region is set to United States.

Simulator -> Settings -> General -> Language & Region -> Region

Not sure if this applies to your use case/implementation?

**Comment by ollydixon** [comment]
@logic-emotion indeed that is true.

**Comment by UsamaKarim** [comment]
How about disabling the country. Why it is required?

**Comment by jamesblasco** [comment]
@UsamaKarim it is something we can't control ourselves. Please consider submitting an issue to the Stripe native sdk repos about it

**Comment by nicks258** [comment]
How can I set default country to UAE in both android and iOS. Testing on real device. @jamesblasco @logic-emotion please help.

**Comment by emme1009** [comment]
It seems that we now can pass default values for country and postal code. (https://github.com/stripe/stripe-android/issues/3719)
I hope that this library will also implement these changes.

**Comment by bhanuka96** [comment]
@nicks258 How do you set UAE by default?

**Comment by nicks258** [comment]
Still struggling.. @bhanuka96

**Comment by remonh87** [comment]
the default country is set based on the localization of the phone. Like said before this is the behaviour of the native stripe sdk.

**Comment by remonh87** [comment]
Also let's keep track of the discussion: https://github.com/stripe/stripe-react-native/issues/717

**Comment by ktiniatros** [comment]
At the moment with flutter_stripe 9.1.1:
Localisation is based on the device set language. If you want to force one language only on iOS (usual case in MVPs) then you can set one localisation only in the Info.plist in the Runner project.

To prelect a country, you can set it in the billing details:

```
await Stripe.instance.initPaymentSheet(
      paymentSheetParameters: SetupPaymentSheetParameters(
        billingDetails: const BillingDetails(
          address: Address(
            country: 'GR',
            city: '',
            line1: '',
            line2: '',
            state: '',
            postalCode: '',
          ),
        ),
        style: ThemeMode.light,
      ),
    );
```

**Comment by rashedoz** [comment]
This worked for me

```  
await Stripe.instance.initPaymentSheet(
              paymentSheetParameters: SetupPaymentSheetParameters(
                  billingDetailsCollectionConfiguration: const BillingDetailsCollectionConfiguration(address: AddressCollectionMode.never)
....
...```
