### ISSUE TITLE
Google Pay and confirmSetupIntent failure.

### ISSUE THREAD

**Issue by quentinleguennec** [flutter-stripe/flutter_stripe#292]
**Describe the bug**
When i call `Stripe.instance.confirmSetupIntent` with a PaymentMethodParams created from a card token obtained from Google Pay (using the Pay plugin) like this:
```
    final PaymentMethodParams paymentMethodParams = PaymentMethodParams.cardFromToken(
      token: token,
      setupFutureUsage: PaymentIntentsFutureUsage.OffSession,
    );
```
I get the below exception:
```
PlatformException(error, null, null, java.lang.NullPointerException
	at com.reactnativestripesdk.PaymentMethodCreateParamsFactory.createCardPaymentSetupParams(PaymentMethodCreateParamsFactory.kt:161)
	at com.reactnativestripesdk.PaymentMethodCreateParamsFactory.createSetupParams(PaymentMethodCreateParamsFactory.kt:41)
	at com.reactnativestripesdk.StripeSdkModule.confirmSetupIntent(StripeSdkModule.kt:485)
	at com.flutter.stripe.StripeAndroidPlugin.onMethodCall(StripeAndroidPlugin.kt:68)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:336)
	at android.os.Looper.loop(Looper.java:181)
	at android.app.ActivityThread.main(ActivityThread.java:7560)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
)
#0      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:164:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
<asynchronous suspension>
#2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:358:43)
<asynchronous suspension>
#3      MethodChannelStripe.confirmSetupIntent (package:stripe_platform_interface/src/method_channel_stripe.dart:99:20)
<asynchronous suspension>
#4      Stripe.confirmSetupIntent (package:flutter_stripe/src/stripe.dart:261:27)
```

**To Reproduce**
1. Get a Google Pay card token from the Pay plugin.
2. Create a setup intent from backend and get a clientSecret.
3. Create a PaymentMethodParams like so:
```
    final PaymentMethodParams paymentMethodParams = PaymentMethodParams.cardFromToken(
      token: token,
      setupFutureUsage: PaymentIntentsFutureUsage.OffSession,
    );
```
4. Call `Stripe.instance.confirmSetupIntent` like so:
```
      setupIntent = await Stripe.instance.confirmSetupIntent(
        clientSecret,
        paymentMethodParams,
      );
```
5. See the exception.

**Expected behavior**
The setup intent would be confirmed, no exception would be thrown.

**Smartphone / tablet**
    - Device: Android MI 9 with android-arm64
    - OS: Android 10 (API 29)
    - Package version: flutter_stripe: 1.2.0
    - Flutter version: Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale en-GB)

**Additional context**
What I'm trying to achieve here is to save the card details for later use, wihtout charging the card yet.

**Comment by jonasbark** [comment]
Can you confirm this issue on the example app as well? If you can, can you tell us how to reproduce it there?

**Comment by quentinleguennec** [comment]
@jonasbark i'm having trouble runnning the example, I've setup the `lib/.env.dart` and `server/.env` as per the instructions, then installed and ran the server with `yarn --cwd "server"` followed by `yarn --cwd "server" start`. 
I didn't do the last part about web hooks since they are not yet configured on our backend (not sure if that would be an issue for the example).
I get the token from google pay without issue but the call to 'fetchPaymentIntentClientSecret' is timing out.
I'm runnning the server on my computer and building the app on my actual phone (not emulator). Since the server is targeting `localhost` I guess I need to run it in an emulator?

**Comment by quentinleguennec** [comment]
I just tried to test on an Android emulator, but it is not possible to have Google Pay on an emulator, so I don't think I can reproduce in the example.

**Comment by jonasbark** [comment]
it is possible with the Google Play emulator images afaik

**Comment by jonasbark** [comment]
also you can test it on your Mi 9 device

**Comment by jamesblasco** [comment]
Thanks! I will add it to the example project docs
