### ISSUE TITLE
createPayment throws StripeException with generic message

### ISSUE THREAD

**Issue by marcossevilla** [flutter-stripe/flutter_stripe#293]
**Describe the bug**
When we use `Stripe.instance.createPaymentMethod`, it throws a `StripeException` with a non-descriptive message.

**To Reproduce**

We have a service that contains this `addPaymentMethod` to add a new payment method for the user on our backend.

```dart
Future<PaymentMethod> addPaymentMethod({
    required CardDetails cardDetails,
    required BillingDetails billingDetails,
}) async {
      await Stripe.instance.dangerouslyUpdateCardDetails(cardDetails);

      final intermediaryPaymentMethod = await Stripe.instance.createPaymentMethod(
        PaymentMethodParams.card(
          billingDetails: billingDetails,
        ),
      );

     // we send the paymentMethod to our backend and then return the result
}
```

But this `createPaymentMethod` throws a `StripeException` with not much information of what happened. Here's a screenshot:

![stripe-issue](https://user-images.githubusercontent.com/31174242/130075683-c305bb1e-a1d5-4646-a928-65e8ce74b254.png)

**Expected behavior**
`Stripe.instance.createPaymentMethod` should return the new `PaymentMethod` so we can send it to our backend.

**Smartphone / tablet**
 - Device: iPhone 12 Pro Max simulator
 - OS: iOS 14.5
 - Package version: ^1.2.0
 - Flutter version: 2.2.3

**Additional context**
We configured Google and Apple payment profile for native payments if that configuration affects this. Also `Stripe.publishableKey` and `Stripe.merchantIdentifier` are configured with `Stripe.instance.applySettings`.

**Comment by remonh87** [comment]
The exception is coming from the Stripe native sdk and we visualise this so unfortunately there is little we can do about it. What I suggest to do is double check if the card details are send properly and contain the correct values.

**Comment by marcossevilla** [comment]
We figured out there were some missing params on the billing details, I'm closing the issue and hope it helps for future reference if someone gets this generic error some time, thanks! 👍
