### ISSUE TITLE
Reduce duplication in example server api calls

### ISSUE THREAD

**Issue by jamesblasco** [flutter-stripe/flutter_stripe#294]
Maybe we should  extract this into sth generic we have a lot of duplication everywhere.  => not for this pr btw

_Originally posted by @remonh87 in https://github.com/flutter-stripe/flutter_stripe/pull/268#discussion_r686231521_

**Comment by remonh87** [comment]
Actually I think for the sake of the example our approach is good. I think if we would create a generic object which potentially contain code not related to the specific example we would confuse the user.
