### ISSUE TITLE
Wechat Payment method

### ISSUE THREAD

**Issue by dariuspo** [flutter-stripe/flutter_stripe#297]
the issues is closed in https://github.com/flutter-stripe/flutter_stripe/issues/234
regarding the wechat, so i just create a new one, please close it if prefer use that.

I see the we chat feature PR is merged in stripe react native
https://github.com/stripe/stripe-react-native/pull/422

is there any plan to integrate it?

thanks for the awesome work guys.

**Comment by remonh87** [comment]
@dariuspo  it is already part of the `sync` brand and will be released with the next version.

**Comment by remonh87** [comment]
WeChat is available in version 1.3.0 which is published today
