### ISSUE TITLE
Google Pay Support

### ISSUE THREAD

**Issue by ened** [flutter-stripe/flutter_stripe#30]
Should the plugin contain components to activate & use Google Pay?

The actual interfaces between Google Pay & Stripe are:

``` java
// get things ready for payment
GooglePayConfig(publishableKey).tokenizationSpecification

// submit the json result from google pay to Stripe
// at this moment, the payment request should be valid, errors are handled earlier
PaymentMethodCreateParams.createFromGooglePay(json)
```

There is a bit more to it than Apple Pay I think, for example these additional dependencies - which can (& will) outdate:

``` gradle
  implementation 'com.google.android.gms:play-services-wallet:18.1.1'
  implementation 'androidx.appcompat:appcompat:1.2.0'
```

Developers are also required to modify AndroidManifest.xml files.

--- 

If this were not to be included in this package, then the Dart side would act as a JSON messenger between a google pay plugin (to generate tokenization spec) and the stripe side (to receive json results). 

IMHO it is acceptable to include Google Pay fully in this package as Stripe ships with a few APIs already (com.stripe.android.googlepay.*).

**Comment by jonasbark** [comment]
the cat is out of the bag:

If you need Google / Apple Pay integration asap you can have a look at the new pay plugin:
https://pub.dev/packages/pay

And here's how it can be used with the flutter_stripe plugin:
https://github.com/google-pay/flutter-plugin/pull/20
