### ISSUE TITLE
How to get paid status when using presentPaymentSheet

### ISSUE THREAD

**Issue by Obinna-e** [flutter-stripe/flutter_stripe#302]
Tried getting status from the enum PaymentIntentStatus but all I see printed in debug console is "Flutter: PaymentIntentStatus"

**Comment by Obinna-e** [comment]
Or at least a method to know when the payment sheet is dismissed

**Comment by jamesblasco** [comment]
Hello! You can catch an exception when the payment sheet was canceled by the user.

If the Future presentPaymentSheet finishes with no error means that the payment was completed successfully. Notice that doesn't meant that the payment was processed. 

See Stripe official docs for more details
https://stripe.com/docs/payments/accept-a-payment?platform=ios#integrate-payment-sheet

<img width="536" alt="Screenshot 2021-08-30 at 09 18 58" src="https://user-images.githubusercontent.com/19904063/131301123-fec13fcf-dec4-4cf0-b825-5f071e40dd92.png">

**Comment by Obinna-e** [comment]
Thanks for the response. So if I have a function like this, how do I prevent ShowDialog from running if payment sheet is dismissed?

`Future<void> _handleStripe() async {
    try {
      await Stripe.instance.presentPaymentSheet(
        parameters: PresentPaymentSheetParameters(
          clientSecret: paymentIntentClientSecret,
          confirmPayment: true,
        ),
      );
      showDialog(
        context: context,
        builder: (context) {
          return MintingDialog(amountText, true);
        },
        barrierDismissible: false,
      );`

**Comment by Obinna-e** [comment]
Hi thanks for the response, so if I have a function like this and didn't want showDialog to run when the sheet is dismissed, how would I go about that?

  ```
Future<void> _handleStripe() async {
     try {
        await Stripe.instance.presentPaymentSheet(
        parameters: PresentPaymentSheetParameters(
          clientSecret: paymentIntentClientSecret,
          confirmPayment: true,
        ),
      );

      showDialog(
        context: context,
        builder: (context) {
          return MintingDialog(amountText, true);
        },
        barrierDismissible: false,
      );
```

**Comment by remonh87** [comment]
In that case we will throw a `StripeException` with a failure code canceled.
