### ISSUE TITLE
[stripe_checkout] No such payment_page

### ISSUE THREAD

**Issue by xni06** [flutter-stripe/flutter_stripe#311]
**Node**: `"stripe": "^8.170.0"`
**Flutter**: `stripe_checkout: ^0.0.1-dev2`

I am trying to use https://pub.dev/packages/stripe_checkout which is referred to _by @jamesblasco in https://github.com/flutter-stripe/flutter_stripe/issues/36#issuecomment-899350951_

First I fetch the `session` from my Firebase Cloud Function

```node
const session = await stripe.checkout.sessions.create({
        payment_method_types: ['card'],
        mode: 'payment',
        line_items: {}, // some stuff
        success_url: 'https://blah.com/success', 
        cancel_url: 'https://blah.com/error', 
      });
```

This is the response as per the **POST /v1/checkout/sessions** log:

```
{
  "id": "cs_test_a11H34xrGrzgJPQ5SygNCiycjJ3hWpcr3s9xyaJif26QzObJ05t8ODuc3m",
  "object": "checkout.session",
  "allow_promotion_codes": null,
  "amount_subtotal": 100,
  "amount_total": 100,
  "automatic_tax": {
    "enabled": false,
    "status": null
  },
  "billing_address_collection": null,
  "cancel_url": "https://blah.com/success", 
  "client_reference_id": null,
  "currency": "gbp",
  "customer": null,
  "customer_details": null,
  "customer_email": null,
  "livemode": false,
  "locale": null,
  "metadata": {
  },
  "mode": "payment",
  "payment_intent": "pi_3JUULJBWtCS8nqeR1kH5Dnsv",
  "payment_method_options": {
  },
  "payment_method_types": [
    "card"
  ],
  "payment_status": "unpaid",
  "setup_intent": null,
  "shipping": null,
  "shipping_address_collection": null,
  "submit_type": null,
  "subscription": null,
  "success_url": "https://blah.com/success", 
  "total_details": {
    "amount_discount": 0,
    "amount_shipping": 0,
    "amount_tax": 0
  },
  "url": "https://checkout.stripe.com/pay/cs_test_a11H34xrGrzgJPQ5SygNCiycjJ3hWpcr3s9xyaJif26QzObJ05t8ODuc3m#fidkdWxOYHwnPyd1blpxYHZxWjA0TWhvREpORlJNNjNAU0hfZE5qMnRPbTxOUHxURzBkdF19cUYzV1U0UX1jbUQzUUhCa0BPcm5jQEM1aG1mcTJ8dFJGZlJ8XEpkNEIxaEZkUk9wPG9dUkRQNTViMzN2V0RLNycpJ2N3amhWYHdzYHcnP3F3cGApJ2lkfGpwcVF8dWAnPyd2bGtiaWBabHFgaCcpJ2BrZGdpYFVpZGZgbWppYWB3dic%2FcXdwYCkndnF3bHVgRGZmanBrcSc%2FJ2RmZnFaNE9WYjRnR1JxRlY9a3RgVyd4JSUl"
}
```

In the returned session, I note that it contains a `url` - more on that in a bit

Then I invoke Stripe from the client

```dart
await stripe.redirectToCheckout(
            context: context,
            publishableKey: publishableKey,
            sessionId: sessionId, // from the above session
            successUrl: 'https://blah.com/success',
            canceledUrl: 'https://blah.com/error',
          );
```

This results in the following screen.

<img width="404" alt="Screenshot 2021-08-31 at 11 37 39" src="https://user-images.githubusercontent.com/4117210/131530331-d77348d3-b5e0-47b0-8b4b-5f99e832bac4.png">

When I look at the Stripe POST /v1/payment_pages log, I see...
```
{
  "error": {
    "code": "resource_missing",
    "doc_url": "https://stripe.com/docs/error-codes/resource-missing",
    "message": "No such payment_page: 'cs_test_a11H34xrGrzgJPQ5SygNCiycjJ3hWpcr3s9xyaJif26QzObJ05t8ODuc3m'",
    "param": "payment_page",
    "type": "invalid_request_error"
  }
}
```

The URL in the browser window is...

```
https://checkout.stripe.com/pay/cs_test_a11H34xrGrzgJPQ5SygNCiycjJ3hWpcr3s9xyaJif26QzObJ05t8ODuc3m#fidkdWxOYHwnPyd1blpxYHZxWjA0TWhvREpORlJNNjNAU0hfZE5qMnRPbTxOUHxURzBkdF19cUYzV1U0UX1jbUQzUUhCa0BPcm5jQEM1aG1mcTJ8dFJGZlJ8XEpkNEIxaEZkUk9wPG9dUkRQNTViMzN2V0RLNycpJ2hsYXYnP34nYnBsYSc%2FJ2M1YTZmNjxmKDU2MjMoMT1kMyhkYTNnKDQ3PDMzZ2FgZjFjNDBjZzwzNCcpJ2hwbGEnPydgYTUyPWFgNihgMmBjKDE2ZDwoPTU3YyhkMzNjYzYxZjxgNTc3PDRgMTMnKSd2bGEnPycxYGBhMmAxNyhkNz1gKDE3ZjYoPTVmPSg1NTFkZmZjMTRmZjI3MzIyYWEneCknZ2BxZHYnP15YKSdpZHxqcHFRfHVgJz8ndmxrYmlgWmxxYGgnKSd3YGNgd3dgd0p3bGJsayc%2FJ21xcXU%2FKippamZkaW1qdnE%2FMDU2NjQneCUl
```

However, the URL in the session (mentioned earlier) is _similar_ to the above URL but when I view it in the browser  it takes me to the checkout page where I can add the card details, etc., submit and receive a successful confirmation.

**Questions**
1. Why does the call to `redirectToCheckout` fail with a _No such payment_page_?
2. Why is the session URL not being used?

It's as if I could do away with the call to `redirectToCheckout` altogether and simply open a WebView using the session URL but no doubt I'm misunderstanding the whole process if I were to try that.

Any advice would be welcomed - thanks

**Comment by jamesblasco** [comment]
Please could you confirm that both publishable keys in the server and the dart layer are the same and they are the test ones?

**Comment by xni06** [comment]
> Please could you confirm that both publishable keys in the server and the dart layer are the same and they are the test ones?

Yes, they are test keys - Dart (app) uses the `pk_test_****` key while the server uses the corresponding `sk_test_****` key.

If they were not, then cut'n pasting the session URL into browser wouldn't work... or is that assumption incorrect?

**Comment by xni06** [comment]
If I replace the keys used in the latest `flutter_stripe` (e12d7eb1a39d5e0317892e2350ddfe7b53222ef3) example app with mine and run it against Android, it works. This suggests that they keys are correct.

**Comment by remonh87** [comment]
@jamesblasco  I think we now implement checkout right? Can we close this ticket

**Comment by xni06** [comment]
> @jamesblasco I think we now implement checkout right? Can we close this ticket

We now use `flutter_stripe: ^1.3.0` so it's no longer a concern to us.
