### ISSUE TITLE
confirmSetupIntent by google pay or apple pay

### ISSUE THREAD

**Issue by arashamini71** [flutter-stripe/flutter_stripe#312]
i want to set a card for future usage and i want to choose a card from google pay or apple pay and set it up as a future payment by using confirmsetupintent ... what should i do?

**Comment by jamesblasco** [comment]
You should be able to call with the confirmSetupIntent with the tokenized card id from Google Pay and Apple Pay.
Check the Google Pay example using Payment Intent and use the same process with the SetupIntent.

1. Create a Setup Intent in your server
2. Confirm the setup intent with the following code
```dart

      final params = PaymentMethodParams.cardFromToken(
        token: tokenJson['id'],
      );

      // 3. Confirm Google pay payment method
      await Stripe.instance.confirmSetupIntent(
        clientSecret,
        params,
      );

```

For Apple Pay, next release version will allow getting the token id using the `pay` plugin
