### ISSUE TITLE
customized payment methods in paymentsheet?

### ISSUE THREAD

**Issue by SiRumCz** [flutter-stripe/flutter_stripe#313]
**Describe the solution you'd like**
Showing method for alipay when displaying payment sheet along with applePay, googlePay, credit cards, etc.

**Describe alternatives you've considered**
Currently, it can only be another button to use the service.

**Comment by jamesblasco** [comment]
This feature is not available for the Stripe SDK, consider creating a feature request issue in the correspondent channels:
https://github.com/stripe/stripe-ios
https://github.com/stripe/stripe-android

**Comment by SiRumCz** [comment]
Thanks for reply, may I ask what service that flutter_stripe `payment sheet` depends on in stripe-ios/android?

**Comment by SiRumCz** [comment]
Thank you
