### ISSUE TITLE
Example app has compile errors?

### ISSUE THREAD

**Issue by chunyongg** [flutter-stripe/flutter_stripe#317]
The example app has over 1000 compile errors, such as:

![image](https://user-images.githubusercontent.com/68111375/132226258-aec137b4-ce94-4a2c-9c05-136a8bdbff88.png)

I am trying to implement a paymentsheet for custom payments, and my code goes something like this:

```
Column(
          mainAxisAlignment: MainAxisAlignment.start,
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            CardField(),
            ElevatedButton(
              style: ElevatedButton.styleFrom(primary: Styles.purple),
              onPressed: () async {
                // create payment method
                final PaymentMethodParams paymentMethod =
                    PaymentMethodParams.card();
                await process(paymentMethod);
              },
              child: Text('Pay')
            )
          ],
        )));
```

where my `process` method takes in a `PaymentMethodParams`, fetches the payment intent from my server and simply confirms the payment:

```
      PaymentIntent charge = await Stripe.instance.confirmPayment(
        paymentIntent,
        method,
      );
```

![image](https://user-images.githubusercontent.com/68111375/132226813-652ce5b1-df11-4ac0-9ed0-6eb67fa0f2a5.png)

The UI isnt fantastic, and ideally, I'd like to use a Payment Sheet but I cannot find a simple example on how to.

**Comment by jamesblasco** [comment]
Please download the latest version of the repo, those problems should be addressed now. 
You can customize the UI of the CardField with the decoration param.

For the payment sheet you can check this example https://github.com/flutter-stripe/flutter_stripe/blob/main/example/lib/screens/payment_sheet/payment_sheet_screen.dart

Please consider next time creating a specific issue for each problem you might have. Thanks
