### ISSUE TITLE
nhandled Exception: MissingPluginException(No implementation found for method initialise on channel flutter.stripe/payments)

### ISSUE THREAD

**Issue by IntepayHK** [flutter-stripe/flutter_stripe#318]
**Describe the bug**
Hi i have a Exception about MissingPlugin below:

 [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: MissingPluginException(No implementation found for method initialise on channel flutter.stripe/payments)

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  Stripe.publishableKey = myStripe.publishableKey;
  Stripe.merchantIdentifier = 'merchant.flutter.stripe.test';
  Stripe.urlScheme = 'flutterstripe';
 await Stripe.instance.applySettings();
....

i follow the document set my android build.grade but still not work
here is my code
main/AndroidManifest.xml
buildscript {
    ext.kotlin_version = '1.5.0'
    repositories {
        google()
        jcenter()
    }
src/res/value-night/values.xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    
    
    <style name="LaunchTheme" parent="Theme.AppCompat.Light.NoActionBar">
        
        <item name="android:windowBackground">@drawable/launch_background</item>
    </style>
    
    <style name="NormalTheme" parent="Theme.MaterialComponents">
        <item name="android:windowBackground">?android:colorBackground</item>
    </style>
</resources>
grade/wrapper/grade-wrapper.properties
 distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-6.7-all.zip
kotlin/com../MainActivity.kt
 package com.intepay.lookcardapp
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.android.FlutterFragmentActivity

class MainActivity: FlutterFragmentActivity() {
}

**Comment by remonh87** [comment]
Hi can you confirm if this also happens on iOS (e.g. run it on a simulator)?

**Comment by IntepayHK** [comment]
its just happen in android

**Comment by remonh87** [comment]
did you add the following to the manifest?

```xml
    <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
```

**Comment by IntepayHK** [comment]
yep i already added

**Comment by IntepayHK** [comment]
i fix the problem with upgrade flutter thx

**Comment by remonh87** [comment]
ah ok that is good to hear will close it for now.

**Comment by bhanuka96** [comment]
@remonh87 How to find actual data on these:

```
 Stripe.merchantIdentifier = 'merchant.flutter.stripe.test';
  Stripe.urlScheme = 'flutterstripe';
```

**Comment by eZoomOK** [comment]
I am getting the same error on android, it works fine on iOS
I am on latest version of flutter and latest version of Stripe.

**Comment by Krishnabhattacharya** [comment]
hi.. i am also getting the error on android please tell me how to fix
