### ISSUE TITLE
Example code missing?

### ISSUE THREAD

**Issue by abel-123** [flutter-stripe/flutter_stripe#32]
The link to the example (on pub.dev) is broken. The link:
https://github.com/flutter-stripe/flutter_stripe/blob/main/example/lib/main.dart

Example code seems to be missing from github?

**Comment by jamesblasco** [comment]
Thank you for submitting this issue. I will update the readme with the new url later today 🙂

https://github.com/flutter-stripe/flutter_stripe/tree/main/stripe/example

**Comment by abel-123** [comment]
Thanks! Running the example code now and I'm able to successfully execute test payments with webhooks. If I try to use the 'no_webhook' example the server gives an error:

> Unknown error occurred TypeError: Cannot read property 'id' of undefined
>     at C:\Users\Abel\AndroidStudioProjects\flutter_stripe-main\stripe\example\server\build\index.js:354:64
>     at step (C:\Users\Abel\AndroidStudioProjects\flutter_stripe-main\stripe\example\server\build\index.js:33:23)
>     at Object.next (C:\Users\Abel\AndroidStudioProjects\flutter_stripe-main\stripe\example\server\build\index.js:14:53)
>     at fulfilled (C:\Users\Abel\AndroidStudioProjects\flutter_stripe-main\stripe\example\server\build\index.js:5:58)
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)

I'm using the example unchanged. Did a bit of testing and the payment method is created successfully, but the paymentIntentResult is never generated. The http.post in callNoWebhookPayEndpointMethodId seems to trigger the error...

**Comment by jamesblasco** [comment]
This example url should be fixed in the next version. Related to your last comment, I think it might be the same as https://github.com/flutter-stripe/flutter_stripe/issues/21. Feel free to comment about it there. I will take a look soon
