### ISSUE TITLE
How to change the colors/styling of CardFormField content?

### ISSUE THREAD

**Issue by joknjokn** [flutter-stripe/flutter_stripe#321]
**Describe the bug**
We are trying to switch to the new CardFormField. All input field labels are white, on our white background. On focus the cursor and label becomes neon blue/turquoise. I've tried the style param, inputDecoration, wrapping the field in a theme, setting textColor in android styles.xml, adding values-navy with same content as in values. Nothing changes anything in the CardFormField widget.

How should this be done? I don't see any documentation or examples of how to do it. If there are "styling" and "decoration" params to a widget, I expect them to have an effect when set.

**Comment by Lab360-inc** [comment]
same. white hint text color and turquoise focus. I tried hintstyle and helperstyle no effects..fillcolor also not working..seems the decoration not taking into effect

on another note another option is to add disable country field

**Comment by joknjokn** [comment]
@Lab360-inc How do I disable the country field? Can't find a param for that. Maybe I misunderstood you.

**Comment by Lab360-inc** [comment]
> @Lab360-inc How do I disable the country field? Can't find a param for that. Maybe I misunderstood you.

I meant it would be great if we could also disable or auto populate country but it seems its not ready from stripe pr yet

back to the issue of decoration none of the decoration are working for the CardFormField.

**Comment by joknjokn** [comment]
@jonasbark, can we get a reaction of some sort?

**Comment by jonasbark** [comment]
> I meant it would be great if we could also disable or auto populate country but it seems its not ready from stripe pr yet

For me, my country is auto-populated. Try it on a real device and try different device locale settings. Disabling is not supported and would need to be requested at https://github.com/stripe/stripe-react-native

**Comment by joknjokn** [comment]
@Lab360-inc @jonasbark I believe that's not related to my issue. Maybe create another one.

**Comment by jonasbark** [comment]
Regarding styling: Right now only the backgroundColor may be adjusted:
https://github.com/stripe/stripe-react-native/blob/8e438ea917671d26e41f8bfac52f2206182e8efe/src/types/components/CardFormView.ts#L27

This was an oversight - the unsupported attributes such as cursorColor should be removed in the next version.
Regarding the styling options, look for the already open issues regarding this on https://github.com/stripe/stripe-react-native/issues.

**Comment by jonasbark** [comment]
I'll leave this open so the removal of the unsupported attributes is tracked.

**Comment by Satishpethani92** [comment]
![Screenshot 2021-09-27 at 3 44 58 PM](https://user-images.githubusercontent.com/5456770/134890956-76276f31-1327-482d-89e6-270e7b8b01ff.png) ![Screenshot 2021-09-27 at 3 45 28 PM](https://user-images.githubusercontent.com/5456770/134890962-7ffb6b3d-c5c1-4621-a22a-05f12dc83aff.png) ![Screenshot 2021-09-27 at 3 45 41 PM](https://user-images.githubusercontent.com/5456770/134890963-f8d2574e-b345-4008-bb01-35b2dcc7de68.png)

I do have the same issue in android. I can't see placeholder on android as it is white. I can see label on top if i focus on card and when i blur, label doesn't appear.

**Comment by deep8292** [comment]
Hi, did anyone find any luck, customization?

**Comment by remonh87** [comment]
The cursor problem is not reproducible anymore on the latest version. 

Also I looked into some discussions on the Stripe sdk and the cardformfield is limited in customisation options by intention: https://github.com/stripe/stripe-react-native/issues/77. Closing this ticket for now.
