### ISSUE TITLE
An error ocurred while parsing card arguments in CardField

### ISSUE THREAD

**Issue by diegopq** [flutter-stripe/flutter_stripe#326]
I am using the CardField widget but when writing it does not receive the data, and when it receives it, the onCardChanged function returns the data in null when the card number is written, when the month and year is written if it returns that data, it is until the CardField fields are complete when the function returns the last 4 numbers of the card number. 
While the card number is being written this error returns:
### **"An error ocurred while while parsing card arguments, this should not happen, please consider creating an issue at https://github.com/flutter-stripe/flutter_stripe/issues/new"**
Autofocus is also done automatically even if the autofocus property is set to false.
The version of the package is 1.3.0
**All of the above only happens on Android**

**Code of widget**
```dart

CardField(
          onCardChanged: (cardField) {
            print(cardField);
            final data = NewPaymentCard(
              last4: cardField?.last4,
              month: cardField?.expiryMonth.toString(),
              year: cardField?.expiryYear.toString(),
              brand: cardField?.brand,
            );
            context.read<WriteDataCardCubit>().writeData(data);
            if (cardField!.complete) {
              context.read<PaymentMethodsBloc>().add(WriteNewCardData(data));
            } else if (cardField.last4!.isEmpty) {
              context.read<PaymentMethodsBloc>().add(ClearNewCardData());
            }
          },
          decoration: InputDecoration(
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(10),
              borderSide: const BorderSide(
                color: Colors.transparent,
              ),
            ),
            filled: true,
            fillColor: theme.colorScheme.onSurface.withOpacity(0.05),
            // hintText: hintText,
            hintStyle: theme.textTheme.headline4!.copyWith(
              color: theme.colorScheme.onSurface.withOpacity(0.2),
              fontWeight: FontWeight.normal,
              fontSize: 14.sp,
            ),
            errorText: null,
            errorStyle: const TextStyle(
              height: 0,
            ),
            enabledBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(10),
              gapPadding: 1.0,
              borderSide: const BorderSide(
                color: Colors.transparent,
              ),
            ),
            focusedBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(10),
              gapPadding: 1.0,
              borderSide: const BorderSide(
                color: Colors.transparent,
              ),
            ),
            alignLabelWithHint: true,
          ),
          style: theme.textTheme.headline4!.copyWith(
            fontWeight: FontWeight.w400,
            fontSize: 14.sp,
          ),
          expirationHintText: 'MM/AA',
          cursorColor: theme.textSelectionTheme.cursorColor!,
        ),

```

### Error
```
W/View    (27400): requestLayout() improperly called by android.widget.ImageView{6adf0ba V.ED..... ......ID 0,0-88,58 #7f080138 app:id/icon} during layout: running second layout pass
W/View    (27400): requestLayout() improperly called by android.widget.FrameLayout{1445b6b VFE...... ......ID 161,32-898,85 #7f0800b3 app:id/container} during layout: running second layout pass
W/View    (27400): requestLayout() improperly called by com.google.android.material.textfield.TextInputLayout{db7b6c8 V.ED..... ......ID 0,0-304,53 #7f080095 app:id/card_number_text_input_layout} during layout: running second layout pass
W/View    (27400): requestLayout() improperly called by com.google.android.material.textfield.TextInputLayout{799f361 V.ED..... ......ID 550,0-704,53 #7f08010d app:id/expiry_date_text_input_layout} during layout: running second layout pass
W/View    (27400): requestLayout() improperly called by com.google.android.material.textfield.TextInputLayout{2ba5e86 V.ED..... ......ID 2750,0-2750,53 #7f0800c3 app:id/cvc_text_input_layout} during layout: running second layout pass
I/flutter (27400): CardFieldInputDetails(complete: false, last4: null, expiryMonth: null, expiryYear: null, postalCode: null, brand: null, number: null, cvc: null)
W/IInputConnectionWrapper(27400): sendKeyEvent on inactive InputConnection
[log] "An error ocurred while while parsing card arguments, this should not happen, please consider creating an issue at https://github.com/flutter-stripe/flutter_stripe/issues/new"
```

### Flutter doctor
[✓] Flutter (Channel stable, 2.5.0, on macOS 11.5.2 20G95 darwin-x64, locale es-419)
    • Flutter version 2.5.0 at /Users/---/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (hace 23 horas), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/---/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.60.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (2 available)
    • Redmi Note 6 Pro (mobile) • 3f3bacff • android-arm64  • Android 9 (API 28)
    • Chrome (web)              • chrome   • web-javascript • Google Chrome 93.0.4577.63

• No issues found!

**Android Example**

[![ezgif.com-gif-makerb447697fc7707075.gif](https://s9.gifyu.com/images/ezgif.com-gif-makerb447697fc7707075.gif)](https://gifyu.com/image/J7Vt)

[![ezgif.com-gif-maker-179d2f3c1e9de4ac3.gif](https://s9.gifyu.com/images/ezgif.com-gif-maker-179d2f3c1e9de4ac3.gif)](https://gifyu.com/image/J7Uu)

**iOS Example**
[![ezgif.com-gif-makere18606618706a29b.gif](https://s9.gifyu.com/images/ezgif.com-gif-makere18606618706a29b.gif)](https://gifyu.com/image/J7VQ)

**Comment by jonasbark** [comment]
The focus issues are already tracked on https://github.com/flutter-stripe/flutter_stripe/issues/14
