### ISSUE TITLE
Split payment

### ISSUE THREAD

**Issue by khurram40** [flutter-stripe/flutter_stripe#329]
**I wants to split payment, If customer is paying 10$, I want to transfer 8$ to driver and 2$ to company's account.**

![image](https://user-images.githubusercontent.com/43464947/132937042-2dddf568-36a7-44ff-ade3-7a2ac17c43d1.png)

**Comment by remonh87** [comment]
I think this is something you need to do on the backend: https://stripe.com/docs/connect/charges-transfers#on-behalf-of .  What you need to do is create a payment intent for the full amount and then use the transfer API to send the money to the different accounts

**Comment by DevFreeze** [comment]
If you use the PaymentSheet example, do the following:

Before you call `Stripe.instance.initPaymentSheet` you need to assign the AccountId of the driver to `Stripe.stripeAccountId`:

```
Stripe.stripeAccountId = "acct_12345678910ABCD";
await Stripe.instance.applySettings();
```

In the Post methode of _createTestPaymentSheet() you need to add your fee for the company, the stripeAccountId, and of course price and currency:

```
final url = Uri.parse('$kApiUrl/payment-sheet');
final response = await http.post(
  url,
  headers: {
    'Content-Type': 'application/json',
  },
  body: json.encode({
    'amount': 1000, // this represents 10$
    'currency': 'USD',
    'fee': 200, // your 2$ 
    'vendorId': "acct_12345678910ABCD",
  }),
);
final body = json.decode(response.body);
if (body['error'] != null) {
  throw Exception(body['error']);
}
return body;
```

And finally you need to add this data in the paymentIntents.create method of you server:

```
exports.stripePayment = functions.https.onRequest(async (req, res) => {

    const amount = req.body.amount;
    const currency = req.body.currency;
    const fee = req.body.fee;
    const stripeAccountId = req.body.stripeAccountId;

    const paymentIntent = await stripe.paymentIntents.create({
        amount: amount,
        application_fee_amount: fee,
        currency: currency,
    }, {
        stripeAccount: stripeAccountId,
    });

    res.json({
        paymentIntent: paymentIntent.client_secret,
    });
});
```

If you have an already existing customer, don't forget to add the customerId and the ephemeralKey.

**Comment by DevFreeze** [comment]
> I think this is something you need to do on the backend: https://stripe.com/docs/connect/charges-transfers#on-behalf-of . What you need to do is create a payment intent for the full amount and then use the transfer API to send the money to the different accounts

I tried this approach at first, but Stripe suggested, to use a direct charge with applied fees:

"We generally advise against using standard Connect accounts such as acct_[...] from “separate charge and transfer”, as the risk of chargebacks and disputes lies with the platform, i.e. with you"
