### ISSUE TITLE
Stripe.instance.confirmSetupIntent crashes iOS

### ISSUE THREAD

**Issue by mortenolsson** [flutter-stripe/flutter_stripe#33]
Android works as intended but on iOS calling Stripe.instance.confirmSetupIntent causes this crash:

** Assertion failure in -[FlutterStandardReader readValueOfType:], FlutterStandardCodec.mm:469
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Corrupted standard message'
*** First throw call stack:
(0x1a17425b4 0x1b61c17a8 0x1a1644258 0x1a2a0b6e4 0x1035e61d0 0x1035e77e8 0x1035e464c 0x102d84038 0x10308341c 0x10302281c 0x103024ed4 0x1a16bd08c 0x1a16bcc88 0x1a16bc0d8 0x1a16b5e8c 0x1a16b51c0 0x1b8c9d734 0x1a41237e4 0x1a4129054 0x1009a7c24 0x1a1371cf8)
libc++abi: terminating with uncaught exception of type NSException
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00000001cf73b334 libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`__pthread_kill:
->  0x1cf73b334 <+8>:  b.lo   0x1cf73b354               ; <+40>
    0x1cf73b338 <+12>: pacibsp
    0x1cf73b33c <+16>: stp    x29, x30, [sp, #-0x10]!
    0x1cf73b340 <+20>: mov    x29, sp

**Comment by jamesblasco** [comment]
Thank you for submitting the issue @mortenolsson! I will try to check this issue as soon as possible today.

**Comment by mortenolsson** [comment]
Great thanks !
And it is awesome what you're doing - I really, really appreciate that I will soon be able to build a pretty card signup page instead of the ugly default UI I'm currently getting from the old version. You guys rock !
