### ISSUE TITLE
Is there a way to stop the zip code field showing from the CardSection sheet?

### ISSUE THREAD

**Issue by bhanuka96** [flutter-stripe/flutter_stripe#330]
I'm using this library within the UAE, so the zip code field's not required

**Comment by jonasbark** [comment]
What is the 'CardSection' sheet? Do you mean PaymentSheet?

**Comment by bhanuka96** [comment]
@jonasbark yes payment sheet. Is it possible to disable country and postal code field?

**Comment by jonasbark** [comment]
At the moment, no. But you can ask at https://github.com/stripe/stripe-android, https://github.com/stripe/stripe-ios and/or in https://github.com/stripe/stripe-react-native repositories so this functionality can be added.

**Comment by bhanuka96** [comment]
`merchantCountryCode: 'DE',`

@jonasbark what for this parameter?
