### ISSUE TITLE
CustomFlow is broken

### ISSUE THREAD

**Issue by steeling** [flutter-stripe/flutter_stripe#334]
**Describe the bug**
CustomFlow opens the payment Intent sheet, but doesn't update payment details for a future confirm with Stripe API.

**To Reproduce**
Try setting customFlow = true in initPaymentSheet

**Expected behavior**
PaymentIntent object is updated with payment details.

**Smartphone / tablet**
 - Device:iPhone 12 Pro (simulator)
 - OS:iOS 14.5
 - Package version:1.3.0
 - Flutter version: 2.5.0

**Additional context**
I'm not able to set the customer ID due to #332. There are no errors. Getting the following in the logs:

```
POST /v1/payment_method_preferences

2020-08-27
request body:

{
  "client_secret": "************************************************************",
  "expand": {
    "0": "payment_intent"
  },
  "locale": "en-US",
  "type": "payment_intent"
}
```

**Comment by remonh87** [comment]
did you forward calls using for example the stripe client? see: https://github.com/flutter-stripe/flutter_stripe#additional-steps-for-webhook-forwarding .

Feel free to reopen the issue if this is not working. For me it works.
