### ISSUE TITLE
Cannot click pay when using United Arab Emirates (UAE) as country

### ISSUE THREAD

**Issue by JonasKuschel** [flutter-stripe/flutter_stripe#335]
**Describe the bug**

After inputting the country United Arab Emirates I cannot click the pay button on the payment sheet. I guess it's because there is no ZIP code to input.
For testing there is a workaround: You can edit the card number, cvc or date field to activate the payment button after inputting the country

![image](https://user-images.githubusercontent.com/82314210/133212186-efe6f45a-9a0d-4ed2-b12d-545c49d97287.png)

**To Reproduce**
1. Use PaymentSheet
2. Input card information
3. Input "United Arab Emirates" as the country
4. The Pay button cannot be clicked

**Smartphone / tablet**
 - Device: iphone 12 pro max
 - OS: iOS
 - Package version: 1.3.0
 - Flutter version 2.5.0

**Comment by jonasbark** [comment]
This seems like an issue meant for the Stripe iOS SDK: https://github.com/stripe/stripe-ios
If in question you can also contact their support, e.g. on Discord.
