### ISSUE TITLE
Cancel operation

### ISSUE THREAD

**Issue by ambr89** [flutter-stripe/flutter_stripe#336]
**Describe the bug**
When I press cancel and come back to app, 

**To Reproduce**
1. Press pay button from android app
2. Press Google pay button 
3. Tapping back
4. Tapping X from the payment sheet pop up

**Expected behavior**
I expect that payment will come in canceled state

**Smartphone / tablet**
 - Device: Huawey 
 - OS: Android 10
 - Package version: 1.3.0
 - Flutter version 2.5.0

**Additional context**

This is stack error on console

```bash
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: StripeException(error: LocalizedErrorMessage(code: FailureCode.Canceled, localizedMessage: The payment has been canceled, message: The payment has been canceled, stripeErrorCode: null, declineCode: null, type: null))
 #0      MethodChannelStripe._parsePaymentSheetResult (package:stripe_platform_interface/src/method_channel_stripe.dart:226:11)
 #1      MethodChannelStripe.presentPaymentSheet (package:stripe_platform_interface/src/method_channel_stripe.dart:184:14)
 <asynchronous suspension>
 #2      Stripe.presentPaymentSheet (package:flutter_stripe/src/stripe.dart:327:12)
 <asynchronous suspension>
#3      _CartScreenState._buildCart.<anonymous closure>.<anonymous closure> (package:gttapp/ui/screens/cart/cart_screen.dart:564:31)
 <asynchronous suspension>
```

**Comment by jonasbark** [comment]
>I expect that payment will come in canceled state

Please explain what you mean by that.

**Comment by ambr89** [comment]
My Code is like this.

```js
                            var p = getData()

                              await Stripe.instance.initPaymentSheet(
                                  paymentSheetParameters: SetupPaymentSheetParameters(
                                    applePay: Stripe.instance.isApplePaySupported.value,
                                    googlePay: true,
                                    style: ThemeMode.light,
                                    testEnv: true,
                                    merchantCountryCode: 'XX',
                                    merchantDisplayName: 'XXX',
                                    paymentIntentClientSecret: p.paymentData!.client_secret,
                                  ));

                              await Stripe.instance.presentPaymentSheet();
                              
                              ... TODO OTHER ...
                            ```

When I cancel the operation, I've 2 problem:
- 1. I can make TODO OTHER operation
- 2. in the stripe dashboard the payment is unclompleted state, not canceled (by user).

**Comment by remonh87** [comment]
@ambr89  this is correct behaviour. It would be quite bad user experience in case a user closes the payment sheet that the payment intent will be cancelled.  What if it was by accident? 
If you want this behaviour you need to interact with your backend and make sure the payment intent is cancelled accordingly.

**Comment by ambr89** [comment]
Ok, but, I need to do something after closing the page.
At the moment, I can't do other.

Can I intercept for example the closes operation?

**Comment by ambr89** [comment]
It's strange but I've need put it into try-cath for manage del user closed session

```js
 try {
    await Stripe.instance.presentPaymentSheet();
  }catch(ex, stack){
    print("Exception");
  }
```

**Comment by rddewan** [comment]
is this exception correct ? why do we need to have a exception when user click on cancel button ?
![Screen Shot 2565-11-01 at 4 16 12 PM](https://user-images.githubusercontent.com/13164167/199200790-dc3560c4-d8d8-4be7-9488-bbaf5d98ba6f.png)
