### ISSUE TITLE
Ability to build on Apple M1

### ISSUE THREAD

**Issue by mintotsai** [flutter-stripe/flutter_stripe#339]
**Is your feature request related to a problem? (please describe)**
When trying to build the example app on Apple M1, I am getting the error:

Could not find module 'Stripe' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator

**Describe the solution you'd like**
Ability to run the example app on Apple M1.

**Additional context**
![AuBECSDebitFormView_swift_and_New_Issue_·_flutter-stripe_flutter_stripe](https://user-images.githubusercontent.com/1557318/133528999-28299704-5b8e-43f9-8379-b36eb7607b3f.png)

**Comment by remonh87** [comment]
I am able to run the SDK on my M1 laptop. I think if you use `flutter run` from the terminal it works like expected.

**Comment by mintotsai** [comment]
You're correct. I just pulled a clean clone and flutter run is successful. It must have been user error somewhere. Thanks for checking.
