### ISSUE TITLE
PaymentSheet stopped showing after upgrading the package to version 1.2.0

### ISSUE THREAD

**Issue by joeloudjinz** [flutter-stripe/flutter_stripe#343]
**Describe the bug**
After upgrading the package to version `1.2.0`, and removing `Stripe.instance.presentPaymentSheet()` parameter, the payment sheet is shown and immediately closed with this error logged into the console:
```
flutter:
#0      MethodChannelStripe._parsePaymentSheetResult
package:stripe_platform_interface/src/method_channel_stripe.dart:226
#1      MethodChannelStripe.presentPaymentSheet
package:stripe_platform_interface/src/method_channel_stripe.dart:184
<asynchronous suspension>
#2      Stripe.presentPaymentSheet
package:flutter_stripe/src/stripe.dart:327
<asynchronous suspension>
#3      ServiceRequestChargesStateProvider.processPayment
package:assistt_app/…/service_request_charges/service_request_charges_state_provider.dart:109
<asynchronous suspension>
```

**Smartphone / tablet**
 - Device: iPhone 6s plus
 - OS: iOS 14.8
 - Package version: 1.2.0
 - Flutter version 2.5

**Additional context**
Note: payment sheet was working before the upgrade and it is displayed in android devices.

**Code**
```dart
Stripe.instance.initPaymentSheet(
      paymentSheetParameters: SetupPaymentSheetParameters(
        googlePay: true,
        applePay: true,
        style: ThemeMode.dark,
        testEnv: isTestMode,
        merchantCountryCode: 'US',
        merchantDisplayName: 'Dunder Mifflin Inc.',
        customerId: credentials.clientId,
        paymentIntentClientSecret: credentials.paymentIntent,
        customerEphemeralKeySecret: credentials.eKey,
        customFlow: false,
      ),
    );
```

**Comment by joeloudjinz** [comment]
Update:
![134006664-09b9367c-bb8c-4642-aea8-30f6f7d0130e](https://user-images.githubusercontent.com/33733877/134008353-09035c2f-6b8b-4c7d-bca7-8e779c8186fb.png)

**Comment by jonasbark** [comment]
Can you reproduce this in the example application?

**Comment by remonh87** [comment]
small addition also try it on version `1.3.0` since we made some improvements to payment sheet.

**Comment by joeloudjinz** [comment]
> small addition also try it on version `1.3.0` since we made some improvements to payment sheet.

Updating the package from `1.2.0` to `1.3.0` fixed the problem.
