### ISSUE TITLE
Change stripe country from mobile 

### ISSUE THREAD

**Issue by bhanuka96** [flutter-stripe/flutter_stripe#347]
How to pass the country code in the `defaultBillingDetails` of the `Configuration.Configuration`? 
[original answer](https://github.com/stripe/stripe-android/issues/4206#issuecomment-923901384)

[screen shot](https://user-images.githubusercontent.com/34953062/134163514-14f4d098-8ca4-4e18-b418-17ed0b0e5fc0.jpg)

**Comment by bhanuka96** [comment]
@jonasbark I just want to hide country selection and postal text field or set by default country to UAE. is it possible to do it? [see country selection drop down and postal code textField](https://stripe.com/docs/payments/accept-a-payment?platform=android).

**Comment by remonh87** [comment]
fixed in version `2.0.2`

**Comment by bhanuka96** [comment]
@remonh87 I upgrade the plugin to `2.0.2`. But it's not set by default to **UAE**.

```dart
     await stripe.Stripe.instance.initPaymentSheet(
        paymentSheetParameters: stripe.SetupPaymentSheetParameters(
            paymentIntentClientSecret: model?.stripeResModel?.paymentIntent,
            merchantDisplayName: 'name',
            customerId: model?.stripeResModel?.customer,
            customerEphemeralKeySecret: model?.stripeResModel?.ephemeralKey,
            applePay: true,
            googlePay: true,
            style: ThemeMode.system,
            testEnv: env.flavor == BuildFlavor.development,
            billingDetails: stripe.BillingDetails(
                address: stripe.Address(
                  city: 'Dubai',
                  country: 'AE',
                  line1: 'line 1',
                  line2: 'line 2',
                  postalCode: 'postal code',
                  state: 'state'
                ),
                email: email, name: name, phone: phone),
            merchantCountryCode: 'AE'
            ),
      );
      await stripe.Stripe.instance.presentPaymentSheet();
```

I tried with `merchantCountryCode: 'DE'`. But it's not set by default to Germany.

**Comment by nicks258** [comment]
Not working. Using exact above code snippet. @remonh87 Can you please explain how to set default country in payment sheet?

**Comment by remonh87** [comment]
According to:   https://github.com/stripe/stripe-react-native/issues/552 the default country is selected based on the locale of the phone I am located in Sweden and for me this is selected. There is no way changing the default country as far as I know.

**Comment by bhanuka96** [comment]
@remonh87 I change my keyboard language INto Arabic and German. Now, it's set to UAE and Germany by default.
