### ISSUE TITLE
Future Use (confirmSetupIntent) fails

### ISSUE THREAD

**Issue by spideythewebhead** [flutter-stripe/flutter_stripe#352]
Hi!

I've been trying to save a card for future use, but i always get the same error (Card details not completed).
I've seen your examples too but it seems they dont differ from my use.

steps i have followed:

1. get the card details
```dart
stripe.CardField(
  decoration: InputDecoration(
    filled: true,
    border: InputBorder.none,
  ),
  onCardChanged: (card) {
    this.card = card;
  },
)
```

2. get the client secret from backend
```ts
const intent = await stripe.setupIntents.create({
  customer: stripeId,
  usage: 'off_session',
});
```

3. after succesfull creation of the intent
```dart
final confirmResult = await stripe.Stripe.instance.confirmSetupIntent(
  result.clientSecret!,
  stripe.PaymentMethodParams.card(),
);
```
also filling the card details parameter made no difference.

Throws StripeException with message "Card details not completed"

I have also tried, to get a payment method and pass the payment method id to the setup intent with no difference

```dart
final paymentMethod = await stripe.Stripe.instance.createPaymentMethod(
  stripe.PaymentMethodParams.card(
    setupFutureUsage: stripe.PaymentIntentsFutureUsage.OffSession,
  ),
);
```

I saw that other similar issues exist but they are closed / abandoned without disclosure.

Any help?

**Comment by remonh87** [comment]
card details not completed means that you have entered incomplete card details and thus this fails.  Did you use one of the stripe test cards? https://stripe.com/docs/testing#cards

**Comment by spideythewebhead** [comment]
Hi, yes i am using the test cards. In the past i have used this plugin https://pub.dev/packages/stripe_payment and i had not problems. Also i have entered the details manually from the api and still the object sent has null values for addess

from stripe dashboard
```
  "billing_details": {
    "address": {
      "city": null,
      "country": null,
      "line1": null,
      "line2": null,
      "postal_code": null,
      "state": null
    },
    "email": "has value",
    "name": "has value",
    "phone": "has value"
  },
```

also adding a default payment method works fine, but adding a payment method for later use doesnt work, always getting the same response no matter what i pass

**Comment by spideythewebhead** [comment]
For anyone coming across the same issue, you have to keep the CardView visible while doing your actions.

I had a bottom sheet and when the user clicked on done, i was closing the bottom sheet and then did my actions.
