### ISSUE TITLE
Not able to use a custom design for adding the card to get the token (Non seamless).

### ISSUE THREAD

**Issue by NarendraAmz** [flutter-stripe/flutter_stripe#354]
**Describe the bug**
Not able to use a custom design for adding the card to get the token. could someone help me is there any other method to get the token instead of creating tokens clear and concise description of what the bug is.

**To Reproduce**
CardFieldInputDetails testCard = CardFieldInputDetails(
    number: widget.cardnumberController.text,
    expiryMonth: month,
    expiryYear: year,
    cvc: widget.cvvCardController.text,
    postalCode: widget.zipcodeController.text,
    complete: true,
    last4: '4242',
    brand: cardtYpeStr,
  );
final address = Address(
        city: 'Houston',
        country: 'US',
        line1: '1459  Circle Drive',
        line2: '',
        state: 'Texas',
        postalCode: '77063',
      );
      // 2. Create payment method
      
      // final paymentMethod =
      //             await Stripe.instance.createPaymentMethod(PaymentMethodParams.card());
       final tokenData = await Stripe.instance.createToken(
         CreateTokenParams(type: TokenType.Card, address: address),
      );
      setState(() {
        paymentToken = tokenData;
       // mainpaymentMethod = paymentMethod;
        ;
      });
     
      //return;
    } catch (e) {

      print(e.toString());
      Dialogs.dismissLoadingDialog(context);
         AlertHandler.alertDisplay(context, e.toString());
     // rethrow;
    }

**Expected behavior**

**Smartphone / tablet**
 - Device: [e.g. iPhone X]
 - OS: [e.g. iOS 13, Android 10]
 - Package version: [e.g. 1.0.0]
 - Flutter version [e.g. 2.0.0.]

**Additional context**

**Comment by remonh87** [comment]
you can use the following api for it: https://github.com/flutter-stripe/flutter_stripe/blob/f6c64f659ec79e63dbedaaa3bef24fc4fc46b670/packages/stripe/lib/src/stripe.dart#L343

However you and your organisation need to understand the implications of going fully customised: it means you need to become PCI compliant. My advise would be to use either the payment sheet or the carnfield and accept a bit less customisation.

**Comment by NarendraAmz** [comment]
### Using that card we can create a new token for a specific card 

We are using the below method I got an exception 

#StripeException(error: LocalizedErrorMessage(code: FailureCode.Failed, localizedMessage: There was an unexpected error -- try again in a few seconds, message: There was an unexpected error -- try again in a few seconds, stripeErrorCode: null, declineCode: null, type: null))


```
final tokenData = await Stripe.instance.createToken(
     CreateTokenParams(type: TokenType.Card, address: address),
  );
```
