### ISSUE TITLE
Non-seam less card creation token generation problem

### ISSUE THREAD

**Issue by NarendraAmz** [flutter-stripe/flutter_stripe#359]
Non-seam less card created, Using that card we can create a new token for a specific card

Card creation - using this method
`Future<void> dangerouslyUpdateCardDetails(CardDetails card) async { 
}`

Card token generation 
`final tokenData = await Stripe.instance.createToken(
     CreateTokenParams(type: TokenType.Card, address: address),
  );`

We are using the above method for creating tokens -  I got an exception
#StripeException(error: LocalizedErrorMessage(code: FailureCode.Failed, localized message: There was an unexpected error -- try again in a few seconds, message: There was an unexpected error -- try again in a few seconds, stripeErrorCode: null, decline code: null, type: null))**
  
  Can you please help me with that

**Comment by jonasbark** [comment]
Can you reproduce this in the example app as well using the screen that is provided there?
