### ISSUE TITLE
Web Support

### ISSUE THREAD

**Issue by subinsv** [flutter-stripe/flutter_stripe#36]
**Is your feature request related to a problem? (please describe)**
* Since Flutter web is already in stable branch. It will be good to have web support for this plugin.

**Describe alternatives you've considered**
* Currently we use https://pub.dev/packages/stripe_sdk for web.

**Comment by jamesblasco** [comment]
Hello! I am working on that here https://github.com/flutter-stripe/flutter_stripe/tree/web.

The stripe.js library is very extensive and I have used a code-generator that does not support null-safety yet. So it will take a while until is fully stable. 

Right now the CardField with simple payment should work, but don't recommend using it

**Comment by subinsv** [comment]
Thanks @jamesblasco for the update. 👍

**Comment by identi-non-devs** [comment]
Hey @jamesblasco, are there any updates on the status of Flutter Web support?

**Comment by DenisMisiuraItomy** [comment]
@jamesblasco what about that?

**Comment by remonh87** [comment]
At the moment we are integrating the latest greatest of Stripe which includes some needed bugfixes for us on Android + iOS. Once we have that out of the way we can plan a move towards the web.

**Comment by identi-team** [comment]
Thanks a lot for the update, @remonh87 !

**Comment by chetu-ko** [comment]
Hi. there is any update for flutter web support?

**Comment by vahurh** [comment]
Looking forward to this as well!

**Comment by jefrisingh** [comment]
Hi what will be the expected date for web support?

**Comment by surveshoeb** [comment]
Hi, @jamesblasco have you created any timeline to complete this task? If only code generator creating an issue for null safety have you considered any other package? There are a lot of developers waiting for this SDK to support flutter web since it's stable.

**Comment by Ahmadre** [comment]
@jamesblasco are you porting the code? Would it be better if it's written in dart?

**Comment by jamesblasco** [comment]
I will post a timeline next week with approximated dates! 

@Ahmadre I am porting the code. If we write it directly in the dart, the code would need to be audited to comply with the PCI compliance. It is something discouraged by the Stripe team so far.

**Comment by tylerdurden-87** [comment]
Yes, would love to get a timeline on this as well. We're contemplating not using flutter for our web portal for this one issue. We need a reliable payment method with stripe and that isn't an option right now without a hack. Would love to see flutter web officially supported in this package. And thank you very much for all your hard work and contributions.

**Comment by jamesblasco** [comment]
I will expect to have a beta release for the web package middle of September. 

If anyone is really in a rush to support Stripe payments on Flutter web I would encourage you to use Stripe Checkout in the meantime. While is not very customizable it has a very easy integration
https://pub.dev/packages/stripe_checkout

**Comment by tylerdurden-87** [comment]
@jamesblasco thanks for the timeline. Mid September is great! Thanks you!

**Comment by codedaddy-llp** [comment]
> I will expect to have a beta release for the web package middle of September.
> 
> If anyone is really in a rush to support Stripe payments on Flutter web I would encourage you to use Stripe Checkout in the meantime. While is not very customizable it has a very easy integration
> [pub.dev/packages/stripe_checkout](https://pub.dev/packages/stripe_checkout)

Getting error while using [stripe_checkout](https://pub.dev/packages/stripe_checkout) on web:

```
TypeError: dart.global.Stripe is not a constructor
    at redirectToCheckout (http://localhost:59767/packages/stripe_checkout/src/platforms/stripe_checkout_web.dart.lib.js:21:29)
    at redirectToCheckout.next (<anonymous>)
    at runBody (http://localhost:59767/dart_sdk.js:37422:34)
    at Object._async [as async] (http://localhost:59767/dart_sdk.js:37453:7)
    at Object.redirectToCheckout (http://localhost:59767/packages/stripe_checkout/src/platforms/stripe_checkout_web.dart.lib.js:19:18)
    at Object.redirectToCheckout (http://localhost:59767/packages/stripe_checkout/stripe_checkout.dart.lib.js:18:32)
```

**Comment by surveshoeb** [comment]
> > I will expect to have a beta release for the web package middle of September.
> > If anyone is really in a rush to support Stripe payments on Flutter web I would encourage you to use Stripe Checkout in the meantime. While is not very customizable it has a very easy integration
> > [pub.dev/packages/stripe_checkout](https://pub.dev/packages/stripe_checkout)
> 
> Getting error while using [stripe_checkout](https://pub.dev/packages/stripe_checkout) on web:
> 
> ```
> TypeError: dart.global.Stripe is not a constructor
>     at redirectToCheckout (http://localhost:59767/packages/stripe_checkout/src/platforms/stripe_checkout_web.dart.lib.js:21:29)
>     at redirectToCheckout.next (<anonymous>)
>     at runBody (http://localhost:59767/dart_sdk.js:37422:34)
>     at Object._async [as async] (http://localhost:59767/dart_sdk.js:37453:7)
>     at Object.redirectToCheckout (http://localhost:59767/packages/stripe_checkout/src/platforms/stripe_checkout_web.dart.lib.js:19:18)
>     at Object.redirectToCheckout (http://localhost:59767/packages/stripe_checkout/stripe_checkout.dart.lib.js:18:32)
> ```
> 
> Current package version: `0.0.1-dev2`

@jamesblasco is it possible for you to share the example project of stripe_checkout?

**Comment by kekko7072** [comment]
@jamesblasco Any idea on when will be stable or ready to use, I need to make a plan. Thank you so much !

**Comment by jamesblasco** [comment]
You can check an example for checkout here
https://github.com/flutter-stripe/flutter_stripe/blob/web_2/example/lib/screens/checkout/checkout_screen.dart

@codedaddy-llp @surveshoeb I think you are missing to add the stripe js library to your index.html. There is no other way to add web libraries in flutter for the moment

https://github.com/flutter-stripe/flutter_stripe/blob/5b859a7e9842a83dfba19175803770cfc20f5894/example/web/index.html#L43

**Comment by jamesblasco** [comment]
@kekko7072 there is no timeline for when the plugin will be stable for the web. Hope we can give an estimate time when we get feedback of its use

**Comment by kekko7072** [comment]
> @kekko7072 there is no timeline for when the plugin will be stable for the web. Hope we can give an estimate time when we get feedback of its use

Thank you so much.

**Comment by surveshoeb** [comment]
> You can check an example for checkout here
> [https://github.com/flutter-stripe/flutter_stripe/blob/web_2/example/lib/screens/checkout/checkout_screen.dart](https://github.com/flutter-stripe/flutter_stripe/blob/web_2/example/lib/screens/checkout/checkout_screen.dart?rgh-link-date=2021-08-30T08%3A01%3A10Z)
> 
> @codedaddy-llp @surveshoeb I think you are missing to add the stripe js library to your index.html. There is no other way to add web libraries in flutter for the moment
> 
> https://github.com/flutter-stripe/flutter_stripe/blob/5b859a7e9842a83dfba19175803770cfc20f5894/example/web/index.html#L43

After updating, `index.html` Got a new error whenever I tried to run on local using test Publishable key

```
You may test your Stripe.js integration over HTTP. However, live Stripe.js integrations must use HTTPS.
```

**Comment by jamesblasco** [comment]
@surveshoeb That is not an error, is an alert. Stripe.js allows you to use http localhost for testing. For production you will need to use HTTPS to keep it secure

**Comment by tylerdurden-87** [comment]
> I will expect to have a beta release for the web package middle of September. 
> 
> 
> 
> If anyone is really in a rush to support Stripe payments on Flutter web I would encourage you to use Stripe Checkout in the meantime. While is not very customizable it has a very easy integration
> 
> https://pub.dev/packages/stripe_checkout

@jamesblasco hi, any new updates on this? 

Thank you very much for all your hard work!

**Comment by nicks258** [comment]
Thanks @enwi  for your quick response. As far as my understanding Sessions are only for checkout only. But according to my need I  need to pay or capture [Payment Intent](https://stripe.com/docs/api/payment_intents). Also in Stripe documentation I was unable to create Payment Link for Payment Intent. FYI I am creating Payment Intent from my flutter application and share to customers. If Customers doesn't have app they can also pay using web which is again Flutter. In App I am handling deep linking but and opening `Stripe.instance.initPaymentSheet()`. But unable to do in Web.

**Comment by ahetawal-p** [comment]
I also came here looking for flutter web support. Really looking forward to it @jamesblasco

**Comment by NaokiDohi** [comment]
Hi, @jamesblasco.
I'm so happy with your support.
if you are ok, please tell me how to create the subscription.

**Comment by cweinberger** [comment]
Hi @jamesblasco any update on this? An ETA for our planing would be nice 🤞 
Thanks for all your efforts!

**Comment by NaokiDohi** [comment]
Hi, @jamesblasco.
Are you here?

**Comment by AlirezaDaryani** [comment]
Any update?!
I need pwa `Stripe.instance.presentPaymentSheet()` method

**Comment by aytunch** [comment]
> Hello @NaokiDohi,
> 
> Sorry for the delay. I am the only one working right now on the web side and my time for this is very limited by some personal reasons. Seeing the interest in this I will try to push next week a very early and limited version so people that is interested can start implementing it and give feedback. How does it sound for u?

This sounds great. At least we can try the new web API and give feedback

**Comment by NaokiDohi** [comment]
@jamesblasco 
Are you making a stripe package for the web?

**Comment by mcmikecreations** [comment]
@jamesblasco any news regarding flutter web support?

**Comment by jamesblasco** [comment]
The beta version will be released together with the next release of the plugin

**Comment by NaokiDohi** [comment]
great news @jamesblasco 
I'm so happy to hear.
Is it something that is customizable like ”Stripe SUBSCRIPTIONS” rather than something that is non-customizable like ”Stripe Checkout”?

**Comment by karimkod** [comment]
Hello, any news on this. 

Thanks.

**Comment by NaokiDohi** [comment]
@jamesblasco 
when will you release it?

**Comment by remonh87** [comment]
Thanks to the hard work of @jamesblasco we launched the first beta version for web. Have fun!

**Comment by jamesblasco** [comment]
Please if you encounter any error, have any doubt, or have a feature request specific for the web, create a new issue for it with the title starting like:
-  [web] Implement .....

**Comment by lucasmenezesdev** [comment]
hi, could someone give me an example or help to implement signature with stripe in flutter web?

**Comment by ollydixon** [comment]
Getting the following response from the call on ```stripe_checkout: ^1.0.0```

```
_$36_Error (CheckoutResponse.error(error: TypeError: dart.global.Stripe is not a constructor))
<error>:
<getObject: Unexpected error from chrome devtools:>
```

The call
```
final response = await redirectToCheckout(
  context: context,
  sessionId: sessionId,
  publishableKey: environementProviderProviderRead(context).environment.stripePubKey,
);
```

**Comment by oliveyew** [comment]
Stripe One Time Payment & Subscription in Flutter Web & mobile [link](https://www.udemy.com/course/flutter-in-app-consumable-non-consumable-purchase-2022/?couponCode=NEW_USER_DISCOUNT)

**Comment by toqirnasir** [comment]
@jamesblasco @remonh87 
i'm facing a strange thing.
running the webapp locally it is working, but when i create a flutter web release. 
The app is not working.
giving me 
`VM363 main.dart.js:4133 Uncaught Unsupported operation: Platform._operatingSystem`

if i remove stripe and stripe_web from pub_spec and index.html.
it started running correctly.
someone can help me?

**Comment by manandhar-aarya** [comment]
Hi @jamesblasco @remonh87, 
flutter_strip 7.0.0 and flutter_stripe_web 2.1.0 are not compatible with each other because of dependency stripe_platform_interface. 

I am getting this error:
`Because flutter_stripe_web >=2.0.0 depends on stripe_platform_interface ^6.0.0 and flutter_stripe >=7.0.0 depends on stripe_platform_interface ^7.0.0, flutter_stripe_web >=2.0.0 is incompatible with flutter_stripe >=7.0.0.` 

If I downgrade flutter_stripe library to 6.0.0, the version issue is fixed but I get error at build time. It seems flutter_stripe_web  2.1.0 is dependent on flutter_strip 7.0.0.

Please look into this, thank you!

**Comment by remonh87** [comment]
#1062 will fix this issue. You can use a dependency override for the platform interface for now

**Comment by manandhar-aarya** [comment]
Thank you for the quick reply! I put the dependency override like so:
`dependency_overrides:
  stripe_platform_interface: 6.0.0`

The version issue is fixed but I still get error regarding onDidSetShippingContact, OnDidSetShippingMethod, and so on at build time.

`
../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_stripe-7.0.0/lib/src/stripe.dart:213:5: Error: Type 'OnDidSetShippingContact' not found.
    OnDidSetShippingContact? onDidSetShippingContact,
    ^^^^^^^^^^^^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_stripe-7.0.0/lib/src/stripe.dart:214:5: Error: Type 'OnDidSetShippingMethod' not found.
    OnDidSetShippingMethod? onDidSetShippingMethod,
    ^^^^^^^^^^^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_stripe_web-2.1.0/lib/src/web_stripe.dart:232:5: Error: Type 'OnDidSetShippingContact' not found.
    OnDidSetShippingContact? onDidSetShippingContact,
    ^^^^^^^^^^^^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_stripe_web-2.1.0/lib/src/web_stripe.dart:233:5: Error: Type 'OnDidSetShippingMethod' not found.
    OnDidSetShippingMethod? onDidSetShippingMethod,
    ^^^^^^^^^^^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_stripe_web-2.1.0/lib/src/web_stripe.dart:230:16: Error: The method 'WebStripe.presentApplePay' has more required arguments than those of overridden method 'StripePlatform.presentApplePay'.
  Future<void> presentApplePay(
               ^
../../flutter/.pub-cache/hosted/pub.dartlang.org/stripe_platform_interface-6.0.0/lib/src/stripe_platform_interface.dart:63:16: Context: This is the overridden method ('presentApplePay').
  Future<void> presentApplePay(ApplePayPresentParams params);
               ^
../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_stripe-7.0.0/lib/src/stripe.dart:213:5: Error: 'OnDidSetShippingContact' isn't a type.
    OnDidSetShippingContact? onDidSetShippingContact,
    ^^^^^^^^^^^^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_stripe-7.0.0/lib/src/stripe.dart:214:5: Error: 'OnDidSetShippingMethod' isn't a type.
    OnDidSetShippingMethod? onDidSetShippingMethod,
    ^^^^^^^^^^^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_stripe-7.0.0/lib/src/stripe.dart:222:38: Error: Too many positional arguments: 1 allowed, but 3 found.
Try removing the extra positional arguments.
      await _platform.presentApplePay(
                                     ^
../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_stripe-7.0.0/lib/src/stripe.dart:376:28: Error: The method 'resetPaymentSheetCustomer' isn't defined for the class 'StripePlatform'.
 - 'StripePlatform' is from 'package:stripe_platform_interface/src/stripe_platform_interface.dart' ('../../flutter/.pub-cache/hosted/pub.dartlang.org/stripe_platform_interface-6.0.0/lib/src/stripe_platform_interface.dart').
Try correcting the name to the name of an existing method, or defining a method named 'resetPaymentSheetCustomer'.
    return await _platform.resetPaymentSheetCustomer();
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_stripe_web-2.1.0/lib/src/web_stripe.dart:232:5: Error: 'OnDidSetShippingContact' isn't a type.
    OnDidSetShippingContact? onDidSetShippingContact,
    ^^^^^^^^^^^^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_stripe_web-2.1.0/lib/src/web_stripe.dart:233:5: Error: 'OnDidSetShippingMethod' isn't a type.
    OnDidSetShippingMethod? onDidSetShippingMethod,
    ^^^^^^^^^^^^^^^^^^^^^^`
    
I am waiting until the pull request is merged.

**Comment by JustinJFox** [comment]
@jamesblasco [web] Implement there is currently no documentation for the flutter stripe web. How can we implement it?

**Comment by iKK001** [comment]
Any documentation how to implement flutter stripe web ??

**Comment by Zeeshan0201** [comment]
any update on documentations?

**Comment by flutterdev28** [comment]
exception:WebUnsupportedError: initPaymentSheet is not supported for Webdart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:3  

Any Solutions @jamesblasco ??
