### ISSUE TITLE
CardField not working with Flutter v2.5.1

### ISSUE THREAD

**Issue by TesLake** [flutter-stripe/flutter_stripe#360]
When typing text into the CardField nothing happens. It worked when I was running Flutter 2.2.3 but after I updated it it stopped working.
I do not have any other TextField on the screen.
I have tried by adding a controller to the CardField with the same result.
Also tried using the onCardChange updating the state manually of CardFieldInputDetails, not working either.

I have followed the steps in the docs for android compatibility. 

I do not get any exception only a lot of this output while typing:
I/ViewRootImpl@80e9f17[MainActivity]( 9065): ViewPostIme key 0
I/ViewRootImpl@80e9f17[MainActivity]( 9065): ViewPostIme key 1
I/ViewRootImpl@80e9f17[MainActivity]( 9065): ViewPostIme key 0
I/ViewRootImpl@80e9f17[MainActivity]( 9065): ViewPostIme key 1
I/ViewRootImpl@80e9f17[MainActivity]( 9065): ViewPostIme key 0
I/ViewRootImpl@80e9f17[MainActivity]( 9065): ViewPostIme key 1

Smartphone
 - Device: Samsung Galaxy A51
 - OS: Android 11.0
 - Package version: 1.3.0
 - Flutter version 2.5.1

**Comment by jonasbark** [comment]
This issue is tracked on https://github.com/flutter-stripe/flutter_stripe/issues/14
