### ISSUE TITLE
No documentation about recurring payment subscription 

### ISSUE THREAD

**Issue by akhlaqshah** [flutter-stripe/flutter_stripe#362]
I couldn't find anything regarding recurring payment option, I want to add monthly payment subscription , I know it's supported by stripe SDK, I'm not sure if that feature is included in this plugin.

Thank you for this plugin, it is really a great help for newbies like me.

**Comment by remonh87** [comment]
This is outside the scope of our library, I would advise you to go to the Stripe docs: https://stripe.com/docs/billing/subscriptions/overview#integration-example . 

When I read the docs I think you need to do the following:

- create a payment method and attach it to customer
- create a subscription server side
- create payment method and confirm it client side

**Comment by oliveyew** [comment]
@akhlaqshah  you can do it this way
https://www.youtube.com/watch?v=9fwQRHKuUmU
