### ISSUE TITLE
Focus lost on Android TV

### ISSUE THREAD

**Issue by LastxTemplar** [flutter-stripe/flutter_stripe#364]
**Describe the bug**
I imagine this package is not inherently designed for use on an Android TV but it does seem to work until you get to the payment sheet which does not get focused when shown.

**To Reproduce**
1. run the example project on an Nvidia Shield
2. Choose Single Step -> Init payment sheet -> Pay now
3. The screen turns to portrait mode and shows the payment sheet but no interaction can be done except for the Back Button.

**Expected behavior**
I should be able to choose the payment option and finish the payment

**Smartphone / tablet**
 - Device: Nvidia Shield

**Comment by jonasbark** [comment]
Thanks for reporting!
This issue is better placed in the stripe-android repository which we rely on:
https://github.com/stripe/stripe-android/issues
