### ISSUE TITLE
Issues migrating from stripe_payment to flutter_stripe. "Unexpected Error, try again" without giving more details

### ISSUE THREAD

**Issue by danielo17** [flutter-stripe/flutter_stripe#373]
Hello,

As indicated in the former discontinued "stripe_payment" plugin, I migrated my app to "flutter_stripe" + "pay". At the moment of writing on their last versions. 

I use Pay plugin to get from the Apple Pay sheet a payment result, and when I pass this for creating a token, I get this. Doesn't give much detail:

```
flutter: StripeException(error: LocalizedErrorMessage(code: FailureCode.Failed, localizedMessage: There was an unexpected error -- try again in a few seconds, message: There was an unexpected error -- try again in a few seconds, stripeErrorCode: null, declineCode: null, type: null))
      flutter: #0      ResultParser.parse (package:stripe_platform_interface/src/result_parser.dart:15:7)
      #1      MethodChannelStripe.createApplePayToken (package:stripe_platform_interface/src/method_channel_stripe.dart:279:10)
      <asynchronous suspension>
      #2      Stripe.createApplePayToken (package:flutter_stripe/src/stripe.dart:130:25)
      <asynchronous suspension>
      #3      ServicioPago.pagaNativo (package:save/serviciosProveedores/servicioPago.dart:336:21)
      <asynchronous suspension>
      #4      _SelectorPagoState.pagar (package:save/pages/selectorPago.dart:119:11)
      <asynchronous suspension>

```

Here my Pubspec.yaml:

```
  flutter_stripe: ^1.3.0
  pay: ^1.0.5
```
Here is what I do.
First I initialize both plugging when running main():

```
    _payClient = Pay.withAssets([
      'apple_pay_payment_profile.json',
      'google_pay_payment_profile.json'
    ]);
    Stripe.publishableKey = _stripeClavePublica;
    Stripe.merchantIdentifier = ConfigSave.merchantAppleStore;
    Stripe.urlScheme = 'xxxx';
    await Stripe.instance.applySettings();
```
apple_pay_payment_profile.json looks something like:

```
{
  "provider": "apple_pay",
  "data": {
    "merchantIdentifier": "myMerchant",
    "displayName": "MyCompanyName",
    "merchantCapabilities": ["3DS", "debit", "credit"],
    "supportedNetworks": ["amex", "visa", "discover", "masterCard"],
    "countryCode": "ES",
    "currencyCode": "EUR",
    "requiredBillingContactFields": ["emailAddress", "name", "phoneNumber", "postalAddress"],
    "requiredShippingContactFields": [],
    "shippingMethods": [
      {
        "amount": "0.00",
        "detail": "Available within an hour",
        "identifier": "in_store_pickup",
        "label": "In-Store Pickup"
      },
      {
        "amount": "4.99",
        "detail": "5-8 Business Days",
        "identifier": "flat_rate_shipping_id_2",
        "label": "UPS Ground"
      },
      {
        "amount": "29.99",
        "detail": "1-3 Business Days",
        "identifier": "flat_rate_shipping_id_1",
        "label": "FedEx Priority Mail"
      }
    ]
  }
}
```
And I invoke:
```
     var _paymentItems = [
        PaymentItem(
          label: 'Pagar a MyCompany Servicio X',
          amount: '200',
          status: PaymentItemStatus.final_price,
        )
      ];

      final paymentResult = await _payClient.showPaymentSelector(
        provider: Platform.isIOS?PayProvider.apple_pay:PayProvider.google_pay,
        paymentItems: _paymentItems,
      );
```
This seems to work, both in a simulator and a device, returning the following paymentResult:

```
PAYMENTRESULT: {shippingMethod: null, token: {"version":"EC_v1","data":"loooong key","header":{"ephemeralPublicKey":"someKey","publicKeyHash":"someKey","transactionId":"someID"}}, paymentMethod: {displayName: Visa 8180, type: 2, network: Visa}, billingContact: {name: The Customer, phoneNumber: null, emailAddress: null}, shippingContact: null}
    LOG ANALYTICS: ["event": "stripeios.token_creation", "apple_pay_enabled": 1, "product_usage": [], "publishable_key": "pk_test_51...", "additional_info": [], "apple_merchant_identifier": "unknown", "os_version": "14.5", "shipping_type": "shipping", "bindings_version": "21.7.0", "app_version": "1.0.4", "additional_payment_methods": "none", "token_type": "apple_pay", "device_type": "iPhone10,4", "ocr_type": "none", "analytics_ua": "analytics.stripeios-1.0", "required_billing_address_fields": "zip", "app_name": "save", "company_name": "save", "required_shipping_address_fields": "none", "ui_usage_level": "none"]
```

Then, when I try to get the token to pass it to my backend like this:

```
      String tokenId;
      if (Platform.isIOS) {
        var token = await Stripe.instance.createApplePayToken(paymentResult);
        print(token.id);
        tokenId = token.id;
      }else{
        final token = paymentResult['paymentMethodData']['tokenizationData']['token'];
        final tokenJson = Map.castFrom(json.decode(token));
        tokenId = tokenJson['id'];
      }
```

I get the error instead of having the token.

There is something important, when I test in the emulator, I see some fake card in the simulator and IT WORKS. But when I test in a real device I get the real card and IT FAILS

Finally:
 - Device: iPhone 8
 - OS: iOS 14.5
 - Package version: 1.3.0, latest stable
 - Flutter version: 2.5.1

Many thanks for any help or guidance!

**Comment by hockleongloh** [comment]
Facing same issue, is there any update on this?

**Comment by danielo17** [comment]
Hello, @jamesblasco,

Is there any news or ideas on this? Still facing the same issue and not a clue on how to move on

Thanks!

**Comment by AbdulbasitSaid** [comment]
Hello, @remonh87 and @jamesblasco any solution yet?

**Comment by remonh87** [comment]
@AbdulbasitSaid  the problem is that this message is thrown by the Stripe sdk. It looks like sth is wrong on the Stripe side there since we just parse the error. I think it is good to reach out to support why this is happening.

**Comment by mknox10** [comment]
@danielo17 @AbdulbasitSaid have either of you had any success?

**Comment by danielo17** [comment]
> @danielo17 @AbdulbasitSaid have either of you had any success?

No, unfortunately not

**Comment by Boldbayar** [comment]
Im having same error on production, have you solved it?

**Comment by mknox10** [comment]
I messaged the stripe support team related to this issue. They asked for the 'request ID for the error', does anyone know where I could find that?

**Comment by ohhfreddypleaseno** [comment]
Any updates here?

**Comment by remonh87** [comment]
@mknox10  you can get the request id in the Stripe dashboard developer section.

Normally it means the token is not valid, you either need to set the merchant id , upload the apple key in the stripe dashboard or you made a mistake in the pay plugin. Personally I have a strong preference to the apple pay methods from the Stripe sdk because I find solution Google chooses the json config quite complex and not transparent (prefer strong typed data models).

**Comment by tiagocdr** [comment]
Is there any resolution to this?

**Comment by techweblasb** [comment]
Still getting same error. Any one got solution ??

**Comment by loicgeek** [comment]
Same here, I am having the same issue

**Comment by AsjadSiddiqui** [comment]
For someone still facing this issue in the future,
I managed to fix this
You have to go to Stripes dashboard settings then payment methods and select and configure the iOS certificate for Apple Pay there
Then rebuild the app and it should work
