### ISSUE TITLE
Cardfield widdget not working properly on Android

### ISSUE THREAD

**Issue by RomuloDomiciano** [flutter-stripe/flutter_stripe#374]
**Describe the bug**

I am using the **Cardfield Widget** but whenever I try to tap on it to add credit card information, nothing happens. Keyboard won't appear, placeholders are not rendering as well.It keeps there as a static page. This issue happens only on Android devices, on IOS works perfectly. It is worthy mentioning that we have tested on Android 9 and Android 10 and in few devices it worked a little "buggy", but it worked, it flicks one time and then renders. 

**To Reproduce**

1. Run an Android Emulator with Android 9 or 10.
2. Use the Cardfield Widget in a page.
3. Try to tap on it to insert credit card information.

**Expected behavior**

Placeholders are rendered, when I tap on it, the cursor starts blinking, keyboard shows-up so I can insert my information into the Cardfield. 

**Smartphone**

 - Device: Motorola G 9, Xaiomi Redmi 6, Pixel 2 and Pixel 4.
 - OS: For Motorola, Xaiomi and Pixel 4 Android 9.0 and for Pixel 2 Android 10.0.
 - Package version: we have tested with both 1.2.0 and 1.3.0.
 - Flutter version: we have tested with both 2.2.3 and 2.5.1 on stable channel.

**Additional context**

We are using Getx for state management.

Here is the log with the errors: 

`E/flutter ( 8267): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(error, Binary XML file line #5: Binary XML file line #5: Error inflating class com.google.android.material.card.MaterialCardView, null, android.view.InflateException: Binary XML file line #5: Binary XML file line #5: Error inflating class com.google.android.material.card.MaterialCardView
E/flutter ( 8267): Caused by: android.view.InflateException: Binary XML file line #5: Error inflating class com.google.android.material.card.MaterialCardView
E/flutter ( 8267): Caused by: java.lang.reflect.InvocationTargetException
E/flutter ( 8267):      at java.lang.reflect.Constructor.newInstance0(Native Method)
E/flutter ( 8267):      at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
E/flutter ( 8267):      at android.view.LayoutInflater.createView(LayoutInflater.java:647)
E/flutter ( 8267):      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
E/flutter ( 8267):      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
E/flutter ( 8267):      at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
E/flutter ( 8267):      at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
E/flutter ( 8267):      at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
E/flutter ( 8267):      at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
E/flutter ( 8267):      at com.stripe.android.databinding.StripeCardFormViewBinding.inflate(StripeCardFormViewBinding.java:73)
E/flutter ( 8267):      at com.stripe.android.view.CardFormView.<init>(CardFormView.kt:46)
E/flutter ( 8267):      at com.reactnativestripesdk.CardFormView.<init>(CardFormView.kt:22)
E/flutter ( 8267):      at com.reactnativestripesdk.CardFormViewManager.createViewInstance(CardFormViewManager.kt:56)
E/flutter ( 8267):      at com.flutter.stripe.StripeSdkCardFormPlatformView.<init>(StripeSdkCardFormPlatformView.kt:33)
E/flutter ( 8267):      at com.flutter.stripe.StripeSdkCardFormPlatformViewFactory.create(StripeSdkCardFormPlatformViewFactory.kt:22)
E/flutter ( 8267):      at io.flutter.plugin.platform.PlatformViewsController$1.createAndroidViewForPlatformView(PlatformViewsController.java:146)
E/flutter ( 8267):      at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:101)
E/flutter ( 8267):      at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
E/flutter ( 8267):      at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter ( 8267):      at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter ( 8267):      at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/flutter ( 8267):      at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter ( 8267):      at android.os.MessageQueue.next(MessageQueue.java:326)
E/flutter ( 8267):      at android.os.Looper.loop(Looper.java:160)
E/flutter ( 8267):      at android.app.ActivityThread.main(ActivityThread.java:6669)
E/flutter ( 8267):      at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 8267):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/flutter ( 8267):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/flutter ( 8267): Caused by: java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.MaterialComponents (or a descendant).
E/flutter ( 8267):      at com.google.android.material.internal.ThemeEnforcement.checkTheme(ThemeEnforcement.java:243)
E/flutter ( 8267):      at com.google.android.material.internal.ThemeEnforcement.checkMaterialTheme(ThemeEnforcement.java:217)
E/flutter ( 8267):      at com.google.android.material.internal.ThemeEnforcement.checkCompatibleTheme(ThemeEnforcement.java:145)
E/flutter ( 8267):      at com.google.android.material.internal.ThemeEnforcement.obtainStyledAttributes(ThemeEnforcement.java:76)
E/flutter ( 8267):      at com.google.android.material.card.MaterialCardView.<init>(MaterialCardView.java:124)
E/flutter ( 8267):      at com.google.android.material.card.MaterialCardView.<init>(MaterialCardView.java:114)
E/flutter ( 8267):      ... 28 more
E/flutter ( 8267): )
E/flutter ( 8267): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597:7)
E/flutter ( 8267): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
E/flutter ( 8267): <asynchronous suspension>
E/flutter ( 8267): #2      AndroidViewController.create (package:flutter/src/services/platform_views.dart:748:5)
E/flutter ( 8267): <asynchronous suspension>
E/flutter ( 8267): 
E/flutter ( 8267): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: MissingPluginException(No implementation found for method focus on channel flutter.stripe/card_form_field/0)
E/flutter ( 8267): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
E/flutter ( 8267): <asynchronous suspension>
E/flutter ( 8267): 
E/flutter ( 8267): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: MissingPluginException(No implementation found for method onPlaceholderChanged on channel flutter.stripe/card_form_field/0)
E/flutter ( 8267): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
E/flutter ( 8267): <asynchronous suspension>
E/flutter ( 8267): `

**Comment by jonasbark** [comment]
Here's the real issue:

> Caused by: java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.MaterialComponents 

You'll have to use Theme.MaterialComponents, as also similarly described in https://github.com/flutter-stripe/flutter_stripe#android
