### ISSUE TITLE
Create token problem in Android 

### ISSUE THREAD

**Issue by NarendraAmz** [flutter-stripe/flutter_stripe#377]
Stripe initialization

Stripe.publishableKey = stripe_global_key;
 Stripe.merchantIdentifier =
            'merchant.flutter.stripe.test'; //"Test";//'merchant.flutter.stripe.test';
 Stripe.urlScheme = 'flutterstripe';
 
 Card adding 
 
  CardField(
          autofocus: true,
          onCardChanged: (card) {
            setState(() {
              _card = card;
            });
          },
        ),

Using token creation for the specific card
 
 final tokenData = await Stripe.instance.createToken(
        CreateTokenParams(type: TokenType.Card, address: address),
      );

I got an exception in Android, But iOS is working fine.

PlatformException(flutter_stripe initialization failed, The plugin failed to initialize. Are you using FlutterFragmentActivity? Please check the README: https://github.com/flutter-stripe/flutter_stripe#android, null, null)

**Comment by jonasbark** [comment]
Please post the full exception details from the log output.
Also, follow https://github.com/flutter-stripe/flutter_stripe#android closely.

**Comment by jonasbark** [comment]
This error has been reported often and it was always a configuration issue. Double-check the readme and follow its instructions on Android 👍
