### ISSUE TITLE
Example breaks when trying to select test cards using pay plugin

### ISSUE THREAD

**Issue by klivin** [flutter-stripe/flutter_stripe#378]
**Describe the bug**
The example for native Apple Pay with pay plugin does not allow selection of test cards 

**To Reproduce**
1. Run example after filling in stripe client account info
2. Open Apple Pay (Pay Plugin)
3. Observe failure to select cards. When tapping the first card (Amex), the cards are shown under Not available for this payment...  

**Expected behavior**
Should be able to select test card under "Select How You Want to pay"

**Smartphone / tablet**
 - Device: [e.g. iPhone 12 sim]
 - OS: [e.g. iOS 15]
 - Package version: 
 flutter_stripe 1.3.0 
 - Flutter version 
 Flutter 2.5.1 • channel stable
 
![Simulator Screen Shot - iPhone 12 - 2021-10-06 at 09 58 45](https://user-images.githubusercontent.com/200045/136249701-6a0d2796-a0b1-4ec6-826a-ab270b9dc5eb.png)

Note, when not using the pay plugin, cards are selectable.  I need to use the pay plugin for added control with subscription items and order of operations during checkout.

**Comment by remonh87** [comment]
It looks like you run into the same issue as: https://github.com/google-pay/flutter-plugin/issues/46 .
