### ISSUE TITLE
StripeException when Presenting Payment Sheet: No payment sheet has been initialized yet

### ISSUE THREAD

**Issue by VinceGee** [flutter-stripe/flutter_stripe#385]
**Describe the bug**
I am getting the following error when trying to implement flutter_stripe in my app
flutter: StripeException(error: LocalizedErrorMessage(code: FailureCode.Failed, localizedMessage: No payment sheet has been initialized yet, message: No payment sheet has been initialized yet, stripeErrorCode: null, declineCode: null, type: null))

**To Reproduce**
1. I am getting my paymentIntent from the server, using the following:
```
MyResponse myResponse = await CheckoutController.processThePayment(orderId);
    if (myResponse.success) {
      paymentIntentData = myResponse.data;

    } else {
      ApiUtil.checkRedirectNavigation(context, myResponse.responseCode);
      showMessage(message: myResponse.errorText);
    }
```
2. Initializing the paymentSheet as follows:
```
await Stripe.instance.initPaymentSheet(
        paymentSheetParameters: SetupPaymentSheetParameters(
          paymentIntentClientSecret: paymentIntentData['paymentIntent'],
          applePay: true,
          googlePay: true,
          style: ThemeMode.dark,
          merchantCountryCode: 'UK',
          merchantDisplayName: 'VinceShop'
        ));

    setState(() {});
    print('initialised');
    displaySheet();
```
3. The displaySheet() is defined as follows:
```
Future<void> displaySheet() async {
    try {
      print('trying to present');<-----------This is printing
      await Stripe.instance.presentPaymentSheet();
      print('not reaching here?');<-----------This is NOT printing

      setState(() {
        showMessage(message: "Order paid successfully.");
        paymentIntentData = null;
      });
    } catch (e){
      print(e);
      showMessage(message: "Failed to make the payment.");
    }
  }
```
4. The StripeKey is initialized in the main():
```
    Stripe.publishableKey = pubKey;
    Stripe.merchantIdentifier = 'VinceShop';
    await Stripe.instance.applySettings();
```

**Expected behavior**
Show PaymentSheet, where client can enter their payment details to confirm and complete a transaction

**Smartphone / tablet**
 - Device: [iPhone 12 Pro Max Emulator and Huawei G8]
 - OS: [e.g. iOS 14.2, Android 6.0.1]
 - Package version: [e.g. 1.3.0]
 - Flutter version [e.g. Flutter 2.5.1 • channel stable.]

**Additional context**
On the Stripe Dashboard its showing that the payment status is incomplete. When I hover over it its saying "The customer has not entered their payment method"

**Comment by jonasbark** [comment]
Please double check that the initPaymentSheet method fully succeeds before opening presentPaymentSheet.
Refer to the example application for reference.

**Comment by VinceGee** [comment]
I was using the `await` on as on the example app, (_and the entire snippets I have shared in the question are wrapped within the same async method_) as follows:

```
// 2. initialize the payment sheet
      await Stripe.instance.initPaymentSheet(
        paymentSheetParameters: SetupPaymentSheetParameters(
          // Main params
          paymentIntentClientSecret: data['paymentIntent'],
          merchantDisplayName: 'Flutter Stripe Store Demo',
          // Customer params
          customerId: data['customer'],
          customerEphemeralKeySecret: data['ephemeralKey'],
          // Extra params
          applePay: true,
          googlePay: true,
          style: ThemeMode.dark,
          testEnv: true,
          merchantCountryCode: 'DE',
        ),
      );
```

Unless I am using the wrong example, I am using [this](https://github.com/flutter-stripe/flutter_stripe/blob/main/example/lib/screens/payment_sheet/payment_sheet_screen.dart) example, but the above snippet is from there

**Comment by VinceGee** [comment]
Yes. Please check the attached image, on the snackbar: [https://pasteboard.co/Luw95qJ3PGrT.png](https://pasteboard.co/Luw95qJ3PGrT.png)

**Comment by sindhuperumalla** [comment]
The payment sheet get initialised well on android but fails to do so on iOS. Probably, the documentation needs to be updated. Adding merchant identifier when initialising Stripe worked for me.

```
    Stripe.publishableKey = paymentpublishableKey!;
    Stripe.merchantIdentifier = "App Identifier";
    await Stripe.instance.applySettings();
```
