### ISSUE TITLE
Flutter Web

### ISSUE THREAD

**Issue by NaokiDohi** [flutter-stripe/flutter_stripe#404]
This is my first time presenting an issue, so please let me know if there are any mistakes.
I want to implement subscription payment and user registration only on the web like Netflix in Flutter.
However, the current Flutter_stripe does not support the web. Can you help me to support it?

**Comment by oliveyew** [comment]
@NaokiDohi now you can, checkout this new way
https://www.youtube.com/watch?v=9fwQRHKuUmU
