### ISSUE TITLE
Keyboard won't dismiss on IOS.

### ISSUE THREAD

**Issue by RomuloDomiciano** [flutter-stripe/flutter_stripe#408]
**Describe the bug**
I am using cardfield and when I finish adding credit card information, I press a button to send to my back-end the data needed. When I receive the answer from my back-end, a bottom snackbar shows-up. In the version 1.3.0, the keyboard would dismiss with no problem, but in the newest versions, 2.0.0 and 2.0.1, keyboard keeps there without the possibility to dismiss it.

**To Reproduce**
1. Entering credi card number into the cardfield.
2. Tapping the confirm button.
3. Keyboard won't dismiss.

**Expected behavior**
Keyboard is dismissed.

**Smartphone / tablet**
 - Any device.
 - OS: IOS 11 > and Android 9>
 - Package version: 2.0.0 and 2.0.1
 - Flutter version 2.5.2 stable version

**Comment by jamesblasco** [comment]
Should be fixed with version 2.0.2
