### ISSUE TITLE
 The plugin failed to initialize. Are you using FlutterFragmentActivity? 

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [flutter-stripe/flutter_stripe#411]
@jonasbark I know you have closed previous bug like this but i have double checked all android settings 3 times on here: https://github.com/flutter-stripe/flutter_stripe#android. Cleaned gradlew, cleaned flutter but still have same error:

```
Caught error: PlatformException(flutter_stripe initialization failed, The plugin failed to initialize. Are you using FlutterFragmentActivity? Please check the README: https://github.com/flutter-stripe/flutter_stripe#android, null, null)
I/flutter (16493): #0      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:155:7)
I/flutter (16493): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
I/flutter (16493): <asynchronous suspension>
I/flutter (16493): #2      MethodChannelStripe.initialise (package:stripe_platform_interface/src/method_channel_stripe.dart:43:5)
```

can you help?

**Comment by jonasbark** [comment]
Please don't open a new ticket every time. I am unwilling to help any further if this behavior continues.

I can only point you to the readme again and more speciifically to the example. If it does not help then create a project where this issue is reproducible and I'll reopen the ticket.
