### ISSUE TITLE
General] Payment request is invalid: Error Domain=PKPassKitErrorDomain

### ISSUE THREAD

**Issue by dalton5** [flutter-stripe/flutter_stripe#412]
Hi,

I have also posted the issue in the pay plugin. I don't know which plugin has the bug.

I use apple pay with the plugin flutter_stripe.

When I pay with Apple pay in the currency of my card (€). Apple pay is loading and works.

When I pay with Apple pay in another currency ($) Apple pay is raising an error in my debug log.

General] Payment request is invalid: Error Domain=PKPassKitErrorDomain Code=1 "Invalid in-app payment request" UserInfo={NSLocalizedDescription=Invalid in-app payment request, NSUnderlyingError=0x281bd8c00 {Error Domain=PKPassKitErrorDomain Code=1 "PKPaymentRequest must contain a property 'countryCode' of type 'NSString'

I think it's a bug in the plugin.

Can you please check?

Is it a known bug?

Is there a workaround?

Thanks,

**Comment by dalton5** [comment]
Have you found a fix on this issue?

**Comment by Flucadetena** [comment]
I'm having the same problem!! Any luck??
