### ISSUE TITLE
CRASH: java.lang.NullPointerException: null cannot be cast to non-null type com.reactnativestripesdk.PaymentSheetFragment

### ISSUE THREAD

**Issue by nicks258** [flutter-stripe/flutter_stripe#416]
**FATAL CRASH**
I am facing some weird problem in some days. When I am trying to complete the payment Application is crashing with this logcat.
```
D/AndroidRuntime(17442): Shutting down VM
E/AndroidRuntime(17442): FATAL EXCEPTION: main
E/AndroidRuntime(17442): Process: com.shubbak.pay.dev, PID: 17442
E/AndroidRuntime(17442): java.lang.NullPointerException: null cannot be cast to non-null type com.reactnativestripesdk.PaymentSheetFragment
E/AndroidRuntime(17442): 	at com.reactnativestripesdk.StripeSdkModule$mPaymentSheetReceiver$1.onReceive(StripeSdkModule.kt:228)
E/AndroidRuntime(17442): 	at androidx.localbroadcastmanager.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:313)
E/AndroidRuntime(17442): 	at androidx.localbroadcastmanager.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:121)
E/AndroidRuntime(17442): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(17442): 	at android.os.Looper.loop(Looper.java:233)
E/AndroidRuntime(17442): 	at android.app.ActivityThread.main(ActivityThread.java:8030)
E/AndroidRuntime(17442): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(17442): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
E/AndroidRuntime(17442): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
``` 
Please find my initiation steps: 
```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  FirebaseMessaging.instance.getInitialMessage();
  // FirebaseMessaging.instance.sendMessage();
  await FirestoreServices.init();
  await PreferenceServices.init();
  await AuthService.init();
  // set the publishable key for Stripe - this is mandatory
  Stripe.publishableKey = pubTestKey;
  await Stripe.instance.applySettings();
  runApp(MyApp());
}
```
My Payment Screen:
```dart
Future<void> _initPaymentSheet(clientSecret) async {
    log(clientSecret);
    try {
      await Stripe.instance.initPaymentSheet(
        paymentSheetParameters: SetupPaymentSheetParameters(
          applePay: true,
          googlePay: true,
          style: ThemeMode.dark,
          testEnv: true,
          customerId: _paymentInfoMap["customer"],
          merchantCountryCode: 'AE',
          merchantDisplayName: merchantDetails["business_profile"]["name"],
          customFlow: false,
          // customerId: "cus_KRSsQJvcKiS1pH",
          paymentIntentClientSecret: _paymentIntentModel!.clientSecret,
          // customerEphemeralKeySecret: _paymentSheetData!['ephemeralKey'],
        ),
      );
      setState(() {});
      _displayPaymentSheet(clientSecret: _paymentIntentModel!.clientSecret);
    } catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Error: $e')),
      );
      rethrow;
    }
  }
```
```dart
Future<void> _displayPaymentSheet({required clientSecret}) async {
    try {
      await Stripe.instance.presentPaymentSheet(
          parameters: PresentPaymentSheetParameters(
        clientSecret: clientSecret,
        confirmPayment: true,
      ));
      setState(() {
        async = true;
      });
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Payment successfully completed'),
        ),
      );
      await logTransactionEvent();
    } on Exception catch (e) {
      if (e is StripeException) {
        log(e.error.localizedMessage.toString());
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Error from Stripe: ${e.error.localizedMessage}'),
          ),
        );
      } else {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Unforeseen error: ${e}'),
          ),
        );
      }
    }
  }

```

  I tried every possible answer and example code still facing the same problem.

**Smartphone / tablet**
 - Device: [One Plus 8]
 - OS: [ Android 11]
 - Package version: [e.g. 2.0.1 and 2.0.0]
 - Flutter version [latest]

I followed android step up steps correctly. Also It would be helpful for developers if they got some meaningful errors so that they can understand what went wrong. 
Please Help.

**Comment by remonh87** [comment]
sorry for the late reaction we totally missed this!  Your issue looks like a bug in the underlying Stripe library. See linked issue. We have to wait for Stripe to fix it.

**Comment by marcos930807** [comment]
> **FATAL CRASH** I am facing some weird problem in some days. When I am trying to complete the payment Application is crashing with this logcat.
> 
> ```
> D/AndroidRuntime(17442): Shutting down VM
> E/AndroidRuntime(17442): FATAL EXCEPTION: main
> E/AndroidRuntime(17442): Process: com.shubbak.pay.dev, PID: 17442
> E/AndroidRuntime(17442): java.lang.NullPointerException: null cannot be cast to non-null type com.reactnativestripesdk.PaymentSheetFragment
> E/AndroidRuntime(17442): 	at com.reactnativestripesdk.StripeSdkModule$mPaymentSheetReceiver$1.onReceive(StripeSdkModule.kt:228)
> E/AndroidRuntime(17442): 	at androidx.localbroadcastmanager.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:313)
> E/AndroidRuntime(17442): 	at androidx.localbroadcastmanager.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:121)
> E/AndroidRuntime(17442): 	at android.os.Handler.dispatchMessage(Handler.java:106)
> E/AndroidRuntime(17442): 	at android.os.Looper.loop(Looper.java:233)
> E/AndroidRuntime(17442): 	at android.app.ActivityThread.main(ActivityThread.java:8030)
> E/AndroidRuntime(17442): 	at java.lang.reflect.Method.invoke(Native Method)
> E/AndroidRuntime(17442): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
> E/AndroidRuntime(17442): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
> ```
> 
> Please find my initiation steps:
> 
> ```dart
> void main() async {
>   WidgetsFlutterBinding.ensureInitialized();
>   await Firebase.initializeApp();
>   FirebaseMessaging.instance.getInitialMessage();
>   // FirebaseMessaging.instance.sendMessage();
>   await FirestoreServices.init();
>   await PreferenceServices.init();
>   await AuthService.init();
>   // set the publishable key for Stripe - this is mandatory
>   Stripe.publishableKey = pubTestKey;
>   await Stripe.instance.applySettings();
>   runApp(MyApp());
> }
> ```
> 
> My Payment Screen:
> 
> ```dart
> Future<void> _initPaymentSheet(clientSecret) async {
>     log(clientSecret);
>     try {
>       await Stripe.instance.initPaymentSheet(
>         paymentSheetParameters: SetupPaymentSheetParameters(
>           applePay: true,
>           googlePay: true,
>           style: ThemeMode.dark,
>           testEnv: true,
>           customerId: _paymentInfoMap["customer"],
>           merchantCountryCode: 'AE',
>           merchantDisplayName: merchantDetails["business_profile"]["name"],
>           customFlow: false,
>           // customerId: "cus_KRSsQJvcKiS1pH",
>           paymentIntentClientSecret: _paymentIntentModel!.clientSecret,
>           // customerEphemeralKeySecret: _paymentSheetData!['ephemeralKey'],
>         ),
>       );
>       setState(() {});
>       _displayPaymentSheet(clientSecret: _paymentIntentModel!.clientSecret);
>     } catch (e) {
>       ScaffoldMessenger.of(context).showSnackBar(
>         SnackBar(content: Text('Error: $e')),
>       );
>       rethrow;
>     }
>   }
> ```
> 
> ```dart
> Future<void> _displayPaymentSheet({required clientSecret}) async {
>     try {
>       await Stripe.instance.presentPaymentSheet(
>           parameters: PresentPaymentSheetParameters(
>         clientSecret: clientSecret,
>         confirmPayment: true,
>       ));
>       setState(() {
>         async = true;
>       });
>       ScaffoldMessenger.of(context).showSnackBar(
>         SnackBar(
>           content: Text('Payment successfully completed'),
>         ),
>       );
>       await logTransactionEvent();
>     } on Exception catch (e) {
>       if (e is StripeException) {
>         log(e.error.localizedMessage.toString());
>         ScaffoldMessenger.of(context).showSnackBar(
>           SnackBar(
>             content: Text('Error from Stripe: ${e.error.localizedMessage}'),
>           ),
>         );
>       } else {
>         ScaffoldMessenger.of(context).showSnackBar(
>           SnackBar(
>             content: Text('Unforeseen error: ${e}'),
>           ),
>         );
>       }
>     }
>   }
> ```
> 
> I tried every possible answer and example code still facing the same problem.
> 
> **Smartphone / tablet**
> 
> * Device: [One Plus 8]
> * OS: [ Android 11]
> * Package version: [e.g. 2.0.1 and 2.0.0]
> * Flutter version [latest]
> 
> I followed android step up steps correctly. Also It would be helpful for developers if they got some meaningful errors so that they can understand what went wrong. Please Help.

Same happens to me on OnePlus 8pro, and it is random not always happens.

**Comment by remonh87** [comment]
@marcos930807  did you try it on another phone with the same code or a simulator? Would be awesome if we have a reproducible scenario .

**Comment by marcos930807** [comment]
@remonh87  It has only happened to me 2 or 3 times in the development process of at least 50 60 payment attempts. I have only tested it on my development device which is this (One Plus 8 pro) and on an Ios Emulator, in the emulator I have never had problems.

**Comment by jamesblasco** [comment]
Apparently, this looks related to the GooglePay process inside the paymentSheet. Could you check if that workflow is working correctly for you on your device? Do you have GooglePay setup for that device?

**Comment by remonh87** [comment]
I see the crash happening in one of my projects as well will further investigate it

**Comment by remonh87** [comment]
ok what it looks like is that `initPaymentSheet` and `presentPaymentSheet`  are called too quickly after each other and then the presentPaymentSheet  causes the fragment manager to inflate a fragment which is null (initPaymentSheet is still creating the fragment). 

I propose adding a small delay between them:

```dart
await stripe.initPaymentSheet();
await Future<void>.delayed(Duration(milliSeconds:400));
await stripe.presentPaymentSheet(); 
```

**Comment by remonh87** [comment]
Integrated a potential fix in master. It is super complex to reproduce but it is indeed a crash that happens quite frequently on specific devices.

**Comment by matthewfx** [comment]
@remonh87 Hi has your fixed been released?

**Comment by charliecruzan-stripe** [comment]
FYI @remonh87 a potential fix for this has landed in `stripe-react-native` and will be published in our next release

**Comment by remonh87** [comment]
will be done with the next stripe sync
