### ISSUE TITLE
PaymentMethod has customerId = null

### ISSUE THREAD

**Issue by fedecarroz** [flutter-stripe/flutter_stripe#419]
When I try to create a new PaymentMethod object the property customerId is automatically setted to null.

```
final paymentMethod = await Stripe.instance.createPaymentMethod(
        PaymentMethodParams.card(
          billingDetails: billingDetails,
        ),
);

print(paymentMethod.customerId); // this will print null
```

 - Device: Pixel 4 Emulator / OnePlus Nord
 - OS: Android 11
 - Package version: 2.0.1
 - Flutter version 2.5.3

I followed the example on GitHub
https://github.com/flutter-stripe/flutter_stripe/blob/main/example/lib/screens/card_payments/custom_card_payment_screen.dart

**Comment by remonh87** [comment]
As far as I know the customerID will only be returned when you attached the id to the payment method. https://stripe.com/docs/api/payment_methods/attach . Normally you would link a payment intent to a customer. This is also the recommended way of Stripe.

**Comment by fedecarroz** [comment]
Thanks for the answer. By the way I create the payment method with the code I posted before. How can I attach the customerId to it? I tried using SetupFutureUsage: onSession/offSession but I still got customerId = null

> As far as I know the customerID will only be returned when you attached the id to the payment method. https://stripe.com/docs/api/payment_methods/attach . Normally you would link a payment intent to a customer. This is also the recommended way of Stripe.

**Comment by remonh87** [comment]
Normally this is done on the backend. I prefer payments from the client side to be very simple. Backend gives me a payment intent + customerId and ephermal key (temp key to access stored cards etc.) then , the client collects the data and the backend handles the rest

**Comment by fedecarroz** [comment]
> Normally this is done on the backend. I prefer payments from the client side to be very simple. Backend gives me a payment intent + customerId and ephermal key (temp key to access stored cards etc.) then , the client collects the data and the backend handles the rest

Thank you
