### ISSUE TITLE
Issue when using this package with FlutterFragemntActivity

### ISSUE THREAD

**Issue by HeshamErfanMDLabs** [flutter-stripe/flutter_stripe#424]
**Describe the bug**
Using (Extending) FlutterFragmentActivity (which is needed by this package) causes an issue when used with [firebase_dynamic_links](https://pub.dev/packages/firebase_dynamic_links)

This error is shown when trying to initialize the app using a dynamic link
`The internal FlutterEngine created by FlutterFragment has been attached to by another activity. To persist a FlutterEngine beyond the ownership of this activity, explicitly create a FlutterEngine`

**To Reproduce**
1. Extend FlutterFragmentActivity in MainActivity.java.
2. Implement firebase_dynamic_links.
3. Open the app using a dynamic link

**Expected behavior**
App opens normally

**Actual behavior**
App crashes with the error
`The internal FlutterEngine created by FlutterFragment has been attached to by another activity. To persist a FlutterEngine beyond the ownership of this activity, explicitly create a FlutterEngine`

**Smartphone / tablet**
 - Device: [Redmi note 6 pro]
 - OS: [Android 9]
 - Package version: [2.0.1]
 - Flutter version [2.5.3]
 
 **Additional Context**
 As described in package requirements for android, extending the **FlutterFragmentActivity** is used for **Payment Sheets**, but I don't need it, I use my own UI and just send the payment request using `dangerouslyUpdateCardDetails` and `Stripe.instance.createToken`  which is not related to the **payment Sheets** so **FlutterFragmentActivity** should not be required here, but the actual behavior is that it breaks if I didn't use **FlutterFragmentActivity**

**Comment by remonh87** [comment]
Do you get a crash when you are not using the `FlutterFragmentActivity`? If yes can you provide the stack trace? It should work if you are not using the paymentsheet.

**Comment by HeshamErfanMDLabs** [comment]
Not using **FlutterFragmentActivity** results no crash and the app works fine, but the payment process is the thing that crashes.
It shows me that error
```
`E/flutter (13952): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(flutter_stripe initialization failed, The plugin failed to initialize. Are you using FlutterFragmentActivity? Please check the README: https://github.com/flutter-stripe/flutter_stripe#android, null, null)
E/flutter (13952): #0      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:155:7)
E/flutter (13952): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
E/flutter (13952): <asynchronous suspension>
E/flutter (13952): #2      MethodChannelStripe.dangerouslyUpdateCardDetails (package:stripe_platform_interface/src/method_channel_stripe.dart:221:5)
E/flutter (13952): <asynchronous suspension>
E/flutter (13952): #3      Stripe.dangerouslyUpdateCardDetails (package:flutter_stripe/src/stripe.dart:349:12)
E/flutter (13952): <asynchronous suspension>
E/flutter (13952): 
I/flutter (13952): flutter_stripe initialization failed
I/flutter (13952): Exception PlatformException(flutter_stripe initialization failed, The plugin failed to initialize. Are you using FlutterFragmentActivity? Please check the README: https://github.com/flutter-stripe/flutter_stripe#android, null, null)
```

As I said in the issue I'm using 
```dart
Stripe.publishableKey = 'publishable_key';

TokenData? token = await _generateToken();


Future<TokenData?> _generateToken() async {
    try {
      Stripe.instance.dangerouslyUpdateCardDetails(CardDetails(
        number: creditNumberController.text,
        expirationMonth:
            num.parse(creditExpDateController.text.split("/").first).toInt(),
        expirationYear:
            num.parse(creditExpDateController.text.split("/").last).toInt(),
        cvc: creditCVVController.text.toString(),
      ));
      TokenData token = await Stripe.instance.createToken(
        CreateTokenParams(type: TokenType.Card),
      );
      return token;
    } catch (e) {
      String? message = e.toString();
      if (e is PlatformException) {
        print(e.code);
      }
    return null;
  }
```

And as you can see, all data are handled throw my UI not the PaymentSheet

**Comment by remonh87** [comment]
@jonasbark  can you give some more insights on why we chose to require `FlutterFragmentActivity` for all options? I agree with the above if you have a custom UI there should be no need for it.

**Comment by jonasbark** [comment]
It must be used for getting access to the activity result listeners and support fragment manager in different places, so it's a hard requirement and I don't see a feasible way to change that, as the react-native sources require those exact classes.

**Comment by guymclean** [comment]
Think this may be related https://github.com/flutter/flutter/issues/75656

**Comment by jamesblasco** [comment]
As this is an issue of the library firebase_dynamic_links when using FlutterFragmentActivity we suggest you to create an issue there.
There is an example on a detailed issue that got fixed for another firebase library:
https://github.com/FirebaseExtended/flutterfire/issues/4078
