### ISSUE TITLE
Metadata

### ISSUE THREAD

**Issue by enviro-apps** [flutter-stripe/flutter_stripe#425]
Dear sir or Madam,
I would like o pass some Metadata when using this Plugin as described here: https://stripe.com/docs/api/metadata

How can I do it with the Plugin?

Best Regards

**Comment by remonh87** [comment]
You cannot use the plugin for this. Metadata needs to be passed serverside. See also the official answer of Stripe in: https://github.com/stripe/stripe-react-native/issues/402
