### ISSUE TITLE
Clicking "Return to Merchant" prompts error message in iOS devices

### ISSUE THREAD

**Issue by KuroXII** [flutter-stripe/flutter_stripe#427]
When integrating with FPX payment using confirmPayment method, it will prompt the following error "Safari cannot open the page because the address is invalid" and also not working back to previous screen when click return to merchant button.

![image](https://user-images.githubusercontent.com/23252483/140695910-53f40bf0-e46d-428e-86a4-7c3a11e42832.png)

**Comment by jamesblasco** [comment]
Closing it in favor of https://github.com/flutter-stripe/flutter_stripe/issues/462
