### ISSUE TITLE
Hide postal code on paymentSheet

### ISSUE THREAD

**Issue by mortenolsson** [flutter-stripe/flutter_stripe#430]
**Is your feature request related to a problem? (please describe)**
My customer would like the postal code removed from the PaymentSheet used for adding new payment cards.

**Describe the solution you'd like**
I would like a be able to pass a "hidePostalCode" parameter to SetupPaymentSheetParameters

**Comment by remonh87** [comment]
We use the Stripe native components for (PCI compliance) in case you want this feature I would recommend creating a ticket on: https://github.com/stripe/stripe-react-native
