### ISSUE TITLE
In Production only, Native 3D secure fails to authenticate, webview works. iOS and Android

### ISSUE THREAD

**Issue by bradsb** [flutter-stripe/flutter_stripe#431]
**Describe the bug**
Our customers cannot pass 3D secure authentication when it triggers the native flow despite receiving verification from their bank. This is not reproducible in development. One customer sent us a video, and we confirmed with others that it is multiple banks. The problem occurs with the flows triggered with these [test cards](https://stripe.com/docs/payments/3d-secure#three-ds-cards), except the Webview one, which successfully authenticates.

**To Reproduce**
Not reproducible in development.

**Expected behavior**
Users to successfully authenticate with 3D secure.

**Smartphone / tablet**
 - Device: Any Android/iOS
 - OS: Android 11, iOS 15
 - Package version: 2.0.1
 - Flutter version 2.5.3
 
**Additional context**
Censored video from customer to our support, the notification that appears is the bank for verification. Multiple users have told us that they complete the verification and return to the app and it has failed. This video shows that it fails immediately after selecting the verification method:

https://user-images.githubusercontent.com/18087818/140756552-cb68e145-e883-48ea-87da-fcf95f64d686.mp4

I've opened [a companion issue](https://github.com/stripe/stripe-react-native/issues/703) on the stripe react native repo.

**Comment by remonh87** [comment]
Thanks for filing the issue on this library we will ask Stripe to action it.

**Comment by nerder** [comment]
This is happening to us as well, any update on the issue?

**Comment by remonh87** [comment]
All issues marked blocked are issues that are needed to be fixed in the Stripe library we are dependent on them to fix it.

**Comment by bradsb** [comment]
@nerder I found [an issue](https://github.com/stripe/stripe-react-native/issues/733) opened a few weeks after mine that could possibly be related. You may want to try registering for their 3DS fallback test: https://github.com/stripe/stripe-react-native/issues/733#issuecomment-1012612488

**Comment by nerder** [comment]
Thank you so much @bradsb 🙏🏼 It's quite an annoying issue, what you end up doing after that?

**Comment by remonh87** [comment]
this should be fixed now in version 3.1.0

**Comment by nerder** [comment]
@remonh87 can you please share more details on this?
