### ISSUE TITLE
Ideal does not show in paymentsheet

### ISSUE THREAD

**Issue by remonh87** [flutter-stripe/flutter_stripe#433]
### Discussed in https://github.com/flutter-stripe/flutter_stripe/discussions/429

<div type='discussions-op-text'>

<sup>Originally posted by **NeatFastro** November  8, 2021</sup>
I have created a payment intent with
**"payment_method_types": ["card", "ideal"]**
But the sheet only allows adding credit/debit card info, is this something that's not supported yet or I am doing something wrong?</div>

**Comment by remonh87** [comment]
I can reproduce this behavior in the example app on the main branch.

**Comment by remonh87** [comment]
Did test it and there was sth wrong in the specific payment intent. Issue can be closed.

**Comment by ayushin** [comment]
i have the same problem, do you have ideal now in the paymentsheet?
