### ISSUE TITLE
While publing app on playstore got : Error We've detected this app uses an unsupported version of Play billing. Please upgrade to Billing Library version 3 or newer to publish this app

### ISSUE THREAD

**Issue by developmentkws** [flutter-stripe/flutter_stripe#434]
Please help me to solve this problem,

![Screenshot](https://user-images.githubusercontent.com/72291258/140869077-588125be-5d68-47da-8a7e-862f2a2543f2.png)

**Comment by jamesblasco** [comment]
Could you point out what version of flutter_stripe are u using?

**Comment by jonasbark** [comment]
Wrong repository.
https://github.com/jonasbark/flutter_stripe_payment/issues/340

**Comment by developmentkws** [comment]
> 
> 
> Wrong repository. [jonasbark/flutter_stripe_payment#340](https://github.com/jonasbark/flutter_stripe_payment/issues/340)

Will this error be fixed , if I use "Flutter_stripe"  latest one ?
