### ISSUE TITLE
Return to merchant after setting up a Bancontact card for future payments doesn't work on iOS

### ISSUE THREAD

**Issue by juleshyacinthe** [flutter-stripe/flutter_stripe#436]
**Describe the bug**
When attaching a Bancontact payment method to a customer, the redirection from the authentication flow doesn't happen. The "Return to Merchant" button gives me this log every time I tap it: 
```
Deep Link does not contain valid required params. URL params: {
    "redirect_status" = succeeded;
    "setup_intent" = "seti_1JtuVuHGSEETwhyBgiGKpHfh";
    "setup_intent_client_secret" = "seti_1JtuVuHGSEETwhyBgiGKpHfh_secret_KZ2b2Nxpeh8okj5m6hbUNECvqPvhJKy";
}
```
Using the "Close" button from the browser opened by the intent confirmation works as expected and the rest of the flow goes smoothly.
This only happens on iOS devices and behaves as expected on Android devices.

**To Reproduce**
1. Setup a Bancontact form (Name + email fields).
2. Fill the form and create a Bancontact setup intent server-side.
3. Confirm the setup intent in app 
4. Complete the authentication process
5. Auto-redirection doesn't happen and "Return to merchant" button gives me an error log.

**Expected behavior**
The redirection from the authentication flow should be automatic / the "Return to merchant" button should make the user go back in app.

**Smartphone / tablet**
 - Device: iPhone 6s / iPhone X
 - OS: iOS 15.0
 - Package version: 2.0.2
 - Flutter version 2.5.3

**Additional context**
The flutter_stripe package is setup this way:
```
Stripe.publishableKey = await FlutterConfig.get('STRIPE_PK');
if (Platform.isAndroid) {
  Stripe.urlScheme = await FlutterConfig.get('ANDROID_PACKAGE_NAME');
} else if (Platform.isIOS) {
  Stripe.urlScheme = await FlutterConfig.get('IOS_BUNDLE_ID');
}
await Stripe.instance.applySettings();
```  
Here is a video of the issue:

https://user-images.githubusercontent.com/10943906/140935880-0677c70c-5437-482a-b621-260a13a8db89.mp4

**Comment by jamesblasco** [comment]
Closing it in favor of https://github.com/flutter-stripe/flutter_stripe/issues/462.

We will update there when we have more information about how the bug
