### ISSUE TITLE
Coacoa Pods for stripe_ios can't find compatible version

### ISSUE THREAD

**Issue by Solutionstbd** [flutter-stripe/flutter_stripe#437]
I have upgraded my application to use latest flutter_stripe package 2.0.2. While compiling for iOS, I get the following in my debug console before it terminates.

`
[!] CocoaPods could not find compatible versions for pod "stripe_ios":
      In Podfile:
        stripe_ios (from `.symlinks/plugins/stripe_ios/ios`)
    Specs satisfying the `stripe_ios (from `.symlinks/plugins/stripe_ios/ios`)` dependency were found, but they required a higher minimum deployment target.
`
I originally had my iOS deployment target set to 9.0. After reading that stripe needs to have a min of 11, I switched but have had no luck. I have also raised the target to 14.3 for the heck of it and CocoaPods still fails with the same error.

In between each change, I have also completed a flutter clean and flutter pub get to ensure a clean compile.

Flutter version has been upgraded from 2.2 to 2.5 this week. I doubt that has anything to do with this. 

Is this possibly a CocoaPods issue?
Or are others running into this issue?
Would other packages cause this?

**Comment by remonh87** [comment]
this looks like a cocoa pods issue I would recommend the following:

1. Go to your app folder and run `flutter clean`
2. Run  `flutter pub get`
3. go to iOS folder and run `pod install`

This normally should do the trick

**Comment by Solutionstbd** [comment]
Completed steps mentions just now. It did not correct the issue. 
I have also updated the version of cocoa pods, just incase, and ran those steps again. Still same error.
I will start searching for CocoaPods specific issues online, but will still appreciate any guidance here until I find another thread to rely on.

**Comment by Solutionstbd** [comment]
Problem found in my PodFile.
I had forgot to update the global platform version number. I had been previously trying to update the target level within the runner file directly.

**Comment by jonasbark** [comment]
thanks for posting the solution
