### ISSUE TITLE
Missing PaymentMethodParams.auBecsDebit and AuBECSDebitForm equivalent

### ISSUE THREAD

**Issue by eneesolutions** [flutter-stripe/flutter_stripe#439]
I have been trying to follow this guide: https://stripe.com/docs/payments/au-becs-debit/set-up-payment?platform=react-native

I have run into two main issues. The first is that I can't work out how to collect the bank details on the client and the second is that I can't work out how to confirmSetupIntent with this payment method.'

I have created my setup intent on the server the same as shown in the guide, with `payment_method_types: ['au_becs_debit'],`

When I fetch the setup intent on the client, I can see that information is there. The guide suggests using the AuBECSDebitForm to collect the bank details, but there is no such form available through the flutter_stripe package.

I tried passing the setupIntentClientSecret to the initPaymentSheet method, but when I present the sheet I get an error on this line in the Swift package: 
<img width="962" alt="Screen Shot 2021-11-10 at 15 05 05" src="https://user-images.githubusercontent.com/63626327/141050476-dca582a1-965b-415c-88a3-a067caaa8259.png">

The error says that paymentMethodTypes is empty.

Is what I am trying to do currently supported by this package? I feel very confused so any direction provided would be appreciated

Thanks

**Comment by eneesolutions** [comment]
Hi @jonasbark, @jamesblasco , @remonh87,

So sorry if I seem impatient here, not expecting a solution but I'm at an impasse with an important client project, would one of you be able to clarify if AU direct debit is supported?

Even if there is nothing you can do right now at least I can start looking for alternative solutions.

Thanks

**Comment by remonh87** [comment]
Thanks for reporting this. We weren't  aware AUbecs needs a specific Stripe native UI. I will look into how to implement this because I noticed the Stripe react native has support for this.

**Comment by eneesolutions** [comment]
Thanks so much for taking a look at this, would I be able to get a very rough timeline of how long you think it could take to implement? I only ask so I can pass along to our client

**Comment by remonh87** [comment]
To be honest that is very difficult to say because it can be something simple like payment sheet or something more complex like cardfield. To give a pessimistic number let's say 3-4 weeks .

**Comment by eneesolutions** [comment]
Hey, just wanted to check in and see how it's going, any progress? If you do find it's going to take longer than expected, please let me know so I can pass that info along :)

**Comment by remonh87** [comment]
@eneesolutions  we are implementing this weekend. I was able to get a raw version running on Android.  So  maybe we can release a first beta end of next week depending how much time we have on implementing it on iOS.

**Comment by eneesolutions** [comment]
Great to hear :) I'll keep an eye out on the implement-aubecs-platformview branch

**Comment by remonh87** [comment]
We expect to ship a new version end of this week hopefully. You can already use the form using the master branch as dependency. I did a round trip and the payment got accepted on both iOS and Android

Also keep in mind there are 2 issues with BECS so far. 

stripe/stripe-react-native#743
stripe/stripe-react-native#652

**Comment by eneesolutions** [comment]
Tested on iOS and Android, seems to be working, thank you so much :)

Also did notice the issues you linked, so will keep an eye on those
