### ISSUE TITLE
MacOS and Windows compatibility issues

### ISSUE THREAD

**Issue by piano375** [flutter-stripe/flutter_stripe#440]
**Describe the bug**
MacOS and Windows throw a MissingPluginException when calling Stripe.instance.initPaymentSheet()

** Function **
  Future<void> pay() async {
    read(userProvider).maybeWhen(data: (user) async {

      // Backend Data
      final Map<String, dynamic> _paymentSheetData = await _api.fetchPaymentSheetData(user.token!);

      // Init Stripe Payment Sheet
      await Stripe.instance.initPaymentSheet(
        paymentSheetParameters: SetupPaymentSheetParameters(
          style: ThemeMode.dark,
          testEnv: true,
          applePay: false,
          googlePay: false,
          merchantCountryCode: 'US',
          merchantDisplayName: 'Auguron',
          customerId: _paymentSheetData['customer'],
          paymentIntentClientSecret: _paymentSheetData['paymentIntent'],
          customerEphemeralKeySecret: _paymentSheetData['ephemeralKey'],
        ),
      );

      // Present Payment Sheet
      await Stripe.instance.presentPaymentSheet();
    }, orElse: () {
      print("Error no User");
    });
  }

**To Reproduce**
1) Add flutter_stripe 2.0.2 to Pubspec and run Pub Get
2) Setup the backend to return payment sheet data
3) Call await Stripe.instance.initPaymentSheet() in MacOS or Windows

**Expected behavior**
Expect a payment sheet to appear for a user to present their payment details. 

**Smartphone / tablet**
 - Device: Apple MacBook Pro 2021 - M1 Pro
 - OS: macOS Monterey 12.0.1
 - Package version: 2.0.2
 - Flutter version: 2.5.3

**Additional context**
- Using Riverpod for state management.

- Error Message:
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method initialise on channel flutter.stripe/payments)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
<asynchronous suspension>
#1      MethodChannelStripe.initialise (package:stripe_platform_interface/src/method_channel_stripe.dart:43:5)
<asynchronous suspension>
#2      Stripe._initialise (package:flutter_stripe/src/stripe.dart:415:5)
<asynchronous suspension>
#3      Stripe.initPaymentSheet (package:flutter_stripe/src/stripe.dart:318:5)
<asynchronous suspension>
#4      StripeServiceProvider.pay.<anonymous closure> (package:auguron/services/stripe_service.dart:32:7)
<asynchronous suspension>

**Comment by piano375** [comment]
Same MissingPluginException for the following Device:

Device: Apple MacBook Pro 2016 - Intel i5
OS: macOS Monterey 12.0.1
Package version: 2.0.2
Flutter version: 2.5.2

**Comment by jonasbark** [comment]
Only iOS and Android are the supporter platforms. You should not call the functions on any other platforms.

**Comment by piano375** [comment]
Thanks @jonasbark! Can you please remove Windows, MacOS on the supported platforms on the Pub.dev page? Thanks!

**Comment by ibmgeniuz** [comment]
@jonasbark I agree with @piano375 . If there is no support for other platforms other than android and iOS, then it would be best to indicate it at pub.dev . I have spent so many days trying to debug and search for why my macOS version was throwing errors, thinking I was doing something wrong not knowing that it was just not supported. I can confirm that web version works though when the extra steps are followed per the documentation. 

@jonasbark, is there any intention to support macOS in future? Thank you.

**Comment by jonasbark** [comment]
As there is no official SDK for macOS or Windows there are no plans to support either platforms
