### ISSUE TITLE
This extension needs better documentations.

### ISSUE THREAD

**Issue by muddi900** [flutter-stripe/flutter_stripe#444]
**Is your feature request related to a problem? (please describe)**
You need better documentation and better example code.

**Describe the solution you'd like**
Just better documentation.

**Describe alternatives you've considered**
I am running the example on my current setup and I am getting error for things there aren't documented.

**Comment by remonh87** [comment]
please create some specific issues or contribution and describe what you are missing this way to generic.

**Comment by muddi900** [comment]
I have created specific issue here #446
