### ISSUE TITLE
3D Secure Mastercard layout issues after update from 1.3.0 to 2.0.2

### ISSUE THREAD

**Issue by mrRedSun** [flutter-stripe/flutter_stripe#447]
**Describe the bug**
After the update when doing 3d secure with android + SEB bank (test credit cards from stripe work ok) there is a layout issue that doesn't show confirm button and requires to scroll area about 30 px in height as shown on the video. First few steps of the process looks fine, except for that webview in the end. Video is a bit edited to hide personal info

**To Reproduce**
1. Not sure how it can be reproduced, seems to be related to bank used (Estonian SEB) and Platform (Android). Seems like layout doesn't stretch fully

https://user-images.githubusercontent.com/22750848/141961740-e4c59770-0cdb-4074-b06c-d9b371126c59.mp4

**Expected behavior**

**Smartphone / tablet**
 - Device: Samsung A72
 - OS: Android 11
 - Package version: 2.0.2
 - Flutter version: 2.5.3

**Comment by remonh87** [comment]
Thanks for reporting this looks indeed quite bad. To be honest the 3d secure options that I use are looking good which makes it more difficult to pinpoint. So if you downgrade the library back to `1.0.3` the issue doesn't happen?  If that is the case I will file a bug on the Stripe repo because it looks like a breaking change is introduced there

**Comment by jamesblasco** [comment]
@mrRedSun could that 30px height space be where the CardField was previously located? Maybe we could be pushing the InAppBrowser android fragment inside that view

**Comment by mrRedSun** [comment]
@remonh87 1.0.3 works fine, yes. iOS works fine
@jamesblasco Cardfield was at the bottom, so not the same place, also it does this mastercard loading screen in fullscreen, so for some reason it has issues when there are multiple steps maybe?

**Comment by remonh87** [comment]
@mrRedSun  Stripe fixed quite some 3ds issues that we integrated in version 3.1.0. Can you check it again?
