### ISSUE TITLE
Stripe CardField input error : keyboard not opening on ios when using many ListTiles or RadioListTiles

### ISSUE THREAD

**Issue by davemg3** [flutter-stripe/flutter_stripe#449]
**Describe the bug**
Cannot enter input in Keyboard with Stripe CardField as keyboard cannot be opened (when clicked,it blinks with open/immediate close) 

**To Reproduce**
1. Set a flutter screen as per code example (with at least 7 listTiles...) and build on ios, Xcode 13
2. Try to enter input into the cardfield.
3. Observe a failure of keyboard opening  (it is blinking)…

IDE android studio error : 

> Can't find keyplane that supports type 11 for keyboard iPhone-PortraitChoco-NumberPad; using 25889_PortraitChoco_iPhone-Simple-Pad_Default

**Expected behavior**
Keyboard opening for input

```
class WalletScreen extends StatefulWidget {
  @override
  _WalletScreenState createState() => _WalletScreenState();
}

class _WalletScreenState extends State<WalletScreen> {
  final cardEditController = CardEditController();

  @override
  void initState() {
    cardEditController.removeListener(() {});
    super.initState();
    StripeService.init();
  }

  @override
  void dispose() {
    cardEditController.removeListener(() {});
    cardEditController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('My wallet'),
      ),
      body: Padding(
        padding: const EdgeInsets.all(8.0),
        child: ListView(
          children: [
            SizedBox(
              width: 90,
              child: RadioListTile<int?>(
                title: Text(
                  'test',
                ),
                value: 1,
                groupValue: 3,
                onChanged: (v) {},
              ),
            ),
            SizedBox(
              width: 90,
              child: RadioListTile<int?>(
                title: Text(
                  'test2',
                ),
                value: 2,
                groupValue: 3,
                onChanged: (v) {},
              ),
            ),
            SizedBox(
              width: 90,
              child: RadioListTile<int?>(
                title: Text(
                  'test3',
                ),
                value: 3,
                groupValue: 3,
                onChanged: (v) {},
              ),
            ),
            SizedBox(
              width: 90,
              child: RadioListTile<int?>(
                title: Text(
                  'test4',
                ),
                value: 4,
                groupValue: 3,
                onChanged: (v) {},
              ),
            ),
            SizedBox(
              width: 90,
              child: RadioListTile<int?>(
                title: Text(
                  'test5',
                ),
                value: 5,
                groupValue: 3,
                onChanged: (v) {},
              ),
            ),
            SizedBox(
              width: 90,
              child: RadioListTile<int?>(
                title: Text(
                  'test6',
                ),
                value: 6,
                groupValue: 3,
                onChanged: (v) {},
              ),
            ),
            SizedBox(
              width: 90,
              child: RadioListTile<int?>(
                title: Text(
                  'test6',
                ),
                value: 7,
                groupValue: 3,
                onChanged: (v) {},
              ),
            ),
            SizedBox(
              height: 24,
            ),
            CardField(
              decoration: InputDecoration(border: InputBorder.none),
              controller: cardEditController,
            ),
          ],
        ),
      ),
    );
  }
}
```

**flutter doctor -v**

> 
[✓] Flutter (Channel stable, 2.5.2, on macOS 11.5.1 20G80 darwin-x64, locale en-FR)
    • Flutter version 2.5.2 at /Users/....flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (7 weeks ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/.../Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[!] Android Studio
    • Android Studio at /Users/.../Android Studio Preview 3.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.61.2)
    • VS Code at /Users/...Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

**Comment by jonasbark** [comment]
Apparently, there is a setting in the iOS Simulator to enable soft keyboard. Otherwise, you need to test it on a real device.

**Comment by davemg3** [comment]
@jonasbark , this is not an error on simulator but on real iphone 12….
I think the issue is still open and not solved…

**Comment by jonasbark** [comment]
Which version of flutter_stripe are you using?

**Comment by davemg3** [comment]
I am not in front of my laptop but i took the last one …2.0.8 i think…

**Comment by davemg3** [comment]
I have opened an issue on SO : https://stackoverflow.com/questions/70050220/stripe-cardfield-input-error-keyboard-not-opening-on-ios-iphone-when-using-sev

**Comment by davemg3** [comment]
@jonasbark @remonh87 @jamesblasco , if it cannot be solved, at least can we let this issue open so to get any chance to have someone help on this issue? as the target should not be to improve github statistics figures on open and closed issues but to solve them or get other contribution
