### ISSUE TITLE
presentGooglePlay() overrides/deletes Stripe.stripeAccountId

### ISSUE THREAD

**Issue by t-kietzmann** [flutter-stripe/flutter_stripe#456]
I'm trying to implement Google Pay without the Pay Plugin with Stripe Connect.

I'm able to make payments with Credit Card and Apple Pay, for that i'm creating the payment Intent for the right account server-side and setting the Stripe.stripeAccountId on the client-side before Stripe.instance.presentApplePay / Stripe.instance.initPaymentSheet.

When doing this with Google Pay (first create payment Intent for the right stripe account via server, then setting Stripe.stripeAccountId before calling Stripe.instance.presentGooglePay()) i get this error:

StripeException(error: LocalizedErrorMessage(code: FailureCode.Failed, localizedMessage: Keine solche payment_intent: 'pi_3JxXo6ICQYHd3D1Y1xxxxxxx', message: Keine solche payment_intent: 'pi_3JxXo6ICQYHd3D1Y1xxxxxxx', stripeErrorCode: null, declineCode: null, type: null)).
-- in english: PaymentIntent does not exist.

When doing exactly the same without connect (don't change the stripeAccountId via server/client) everything works as expected.
Therefore i suspect that something in the presentGooglePay() function overrides/deletes the Stripe.stripeAccountId

**Comment by remonh87** [comment]
Did you check on the Stripe dashboard if the payment intent is there? Because it looks like you provide an payment intent that is not linked to your Stripe account (this message is coming directly from Stripe native sdk and we only forward it). I would also contact Stripe support in that case.


Also maybe our [example](https://github.com/flutter-stripe/flutter_stripe/blob/main/example/lib/screens/wallets/google_pay_stripe_screen.dart) is useful.

**Comment by t-kietzmann** [comment]
Yes, the payment Intent is there. 
As I figured out when implementing this functionality (stripe connect accounts) with credit card and apple pay, it's important to create the customer and the payment Intent for the connected Account, eg:

```
 exports.StripePI = functions
  .region('europe-west3')
  .https.onRequest(async (req, res) => {
    const customers = await stripe.customers.list();
    const connectAccount = req.body['stripe_acct'];

    const newConnectCustomer = await stripe.customers.create(
      {
        name: req.body['name'],
        description: req.body['auth_id'],
      },
      {
        stripeAccount: connectAccount,
      }
    );

    const ephemeralKey = await stripe.ephemeralKeys.create(
      { customer: newConnectCustomer.id },
      {
        apiVersion: '2020-08-27',
        stripeAccount: connectAccount,
      }
    );

    const paymentIntent = await stripe.paymentIntents.create(
      {
        amount: req.body['amount'],
        currency: req.body['currency'],
        customer: newConnectCustomer.id,
      },
      {
        stripeAccount: connectAccount,
      }
    );
    console.log(paymentIntent);
    res.json({
      clientSecret: paymentIntent.client_secret,
      paymentIntent: paymentIntent,
      ephemeralKey: ephemeralKey.secret,
      customer: newConnectCustomer.id,
      amount: paymentIntent.amount,
      currency: paymentIntent.currency,
      time: paymentIntent.time,
    });
  });

```

and also set the Stripe.stripeAccountId in Flutter before calling initPaymentSheet (CC):

```
 Stripe.stripeAccountId = _stripeAcct;


        await Stripe.instance.initPaymentSheet(
          paymentSheetParameters: SetupPaymentSheetParameters(

            paymentIntentClientSecret: data['clientSecret'] as String,
            merchantDisplayName: '$_partnerName',

            customerId: data['customer'] as String,
            customerEphemeralKeySecret: data['ephemeralKey'] as String,

            applePay: false,
            googlePay: false,

            style: ref.read(themeProvider).isDarkMode
                ? ThemeMode.dark
                : ThemeMode.light,
            primaryButtonColor: mainThemeColor,
            billingDetails: billingDetails,
            testEnv: false,
            merchantCountryCode: 'IT',
          ),
        );
```

So the PaymentIntent is created on the correct Account in the "Front- and Backend".
This works well for CC and ApplePay.

When not setting the Stripe.stripeAccountId in Flutter the paymentIntent on the client is "created for the stripe main account" and not for the connected Account and you get also the error that the paymentIntent from the Server does not exist (because its configured for the connected Account).

Exactly this happens when using GooglePay, so i think that the Stripe.stripeAccountId is deleted/overwritten when calling the GooglePaySheet. 

I hope you could follow me :)

Thanks & all the best

**Comment by jamesblasco** [comment]
Could you try to enable  googlePay: true, in the initPaymentSheet and check if Google Pay works well there? 

I can´t think a way how we could be overriding the stripeAccountId just for that method. The stripeAccountId is injected globally through 
https://github.com/flutter-stripe/flutter_stripe/blob/8e48dbbe48daf0c07d81c3cda81f2dbe3e48308f/packages/stripe_android/android/src/main/kotlin/com/reactnativestripesdk/StripeSdkModule.kt#L301

And Google Pay is implemented as the recommended guide and the `stripeAccountId` is retrieved from `PaymentConfiguration`here:

https://github.com/stripe/stripe-android/blob/5a1fd4ad9e1726ace8e31a6d4ebb2789bbf53358/payments-core/src/main/java/com/stripe/android/GooglePayConfig.kt#L33-L34

**Comment by remonh87** [comment]
closed due to inactivity feel free to reopen it if the issue still persist
