### ISSUE TITLE
Payment Sheet fails to open when using Destination Charges (fine with Direct Charges)

### ISSUE THREAD

**Issue by xni06** [flutter-stripe/flutter_stripe#457]
When using [Direct Charges](https://stripe.com/docs/connect/direct-charges), everything works beautifully:

**Flutter code**
```
      await Stripe.instance.initPaymentSheet(
        paymentSheetParameters: SetupPaymentSheetParameters(
          applePay: true,
          googlePay: true,
          testEnv: sandbox,
          merchantCountryCode: 'GB',
          merchantDisplayName: merchantName,
          paymentIntentClientSecret: clientSecret,
        ),
      );

      await Stripe.instance.presentPaymentSheet();
```

**Cloud Function used with Flutter app (Direct Charges)**
```
    await stripe.paymentIntents.create({
      amount: amount,
      confirmation_method: 'automatic',
      currency: currency
      application_fee_amount: applicationFee,
    }, 
    { stripeAccount: connectedStripeAccountId });
```

The business has now decided to use [Destination Charges](https://stripe.com/docs/connect/destination-charges) instead. I have replaced `stripeAccount` with `on_behalf_of` and `transfer_data` in the cloud function:

**Cloud Function used with Flutter app (Destination Charges)**
```
    await stripe.paymentIntents.create({
      amount: amount,
      confirmation_method: 'automatic',
      currency: currency,
      application_fee_amount: applicationFee,
      on_behalf_of: connectedStripeAccountId,
      transfer_data: { destination: connectedStripeAccountId }
    });
```

However, now the payment sheet pops up then disappears and the error that gets logged by `Stripe.instance.presentPaymentSheet()` is:

```
StripeException(error: LocalizedErrorMessage(code: FailureCode.Failed, localizedMessage: 
The client_secret provided does not match the client_secret associated with the PaymentIntent., message: 
The client_secret provided does not match the client_secret associated with the PaymentIntent., 
stripeErrorCode: null, declineCode: null, type: null))
```

I have compared the `client_secret` being passed in to the `SetupPaymentSheetParameters` and it is the same as what's being returned from the cloud function so the error message above is confusing.

What gives me some sort of confidence is that it the app works it redirects to Stripe web which does not make use of the `flutter_stripe` - here's the cloud function that creates the payment intent for the web:

**Cloud Function used with Flutter web app (Direct Charges)**
```
      await stripe.checkout.sessions.create({
        payment_method_types: ['card'],
        payment_intent_data: {
          application_fee_amount: applicationFee,
          on_behalf_of: connectedStripeAccountId,
          transfer_data: { destination: connectedStripeAccountId }
        },
        line_items: lineItems,
        mode: 'payment',
        success_url: successUrl,
        cancel_url: cancelUrl
      });
```

I have tested on iOS and Android using both `flutter_stripe` 1.3.0 and 2.0.2

**Comment by xni06** [comment]
One thing that I forgot to mention was that I was setting the following properties beforehand: 

```
    Stripe.publishableKey
    Stripe.stripeAccountId
    Stripe.merchantIdentifier
```

These work fine for _Direct Charges_ but it appears that if I were to comment out `Stripe.stripeAccountId` then _Destination Charges_ will work - sort of makes sense. 

The jury is still out and I'll report back here with a conclusion after the weekend.

**Comment by remonh87** [comment]
Thanks for the long explanation. I will await your verdict on it. If there is still a problem  I will create an issue for Stripe since the exception is coming from the Native sdk (we just translate and forward it).

**Comment by xni06** [comment]
Problem has been solved with the above _fix_
