### ISSUE TITLE
Google Play rejects the app.

### ISSUE THREAD

**Issue by viktor-ohanyan** [flutter-stripe/flutter_stripe#459]
**Is your feature request related to a problem? (please describe)**

Google Play rejects the app.
From Google Play

>Your app has been removed from Google Play

>Your app includes non-compliant SDK version
>Your app ***** version code ***** includes SDK com.stripe:stripe-android, 10.4.6 which facilitates the transmission or collection of personal and sensitive information. Such behaviour must comply with Google Play's prominent disclosure and consent requirements, and applicable privacy policy requirements as described in the user data policy.

>Starting from 12 July 2021 midnight (UTC), new app releases containing this SDK version that do not meet the prominent disclosure and consent requirements per the user data policy will be rejected. You may consider upgrading to 16.9.0, which the SDK provider has recommended for use instead. Please consult the SDK provider for further information.

**Describe the solution you'd like**

I think you should add something like this to the android configuration section.

> dependencies {
>     implementation 'com.stripe:stripe-android:18.2.0'
> }

**Comment by jonasbark** [comment]
You're talking about flutter_stripe_payment: https://github.com/jonasbark/flutter_stripe_payment/issues?q=10.4.6

**Comment by viktor-ohanyan** [comment]
@jonasbark No, I have faced this issue in flutter_stripe (v2.0.2)

**Comment by jonasbark** [comment]
This plugin has never used com.stripe:stripe-android in version 10.4.6. It's currently using 18.1.0.

**Comment by viktor-ohanyan** [comment]
@jonasbark Then why Google Play reject the app with the above reasoning if I am not using anything else related to stripe?

**Comment by jonasbark** [comment]
I can't tell you that because I don't know how their checks are working. I recommend analyzing the uploaded APK and checking their dependencies - or even opening the project in Android Studio and check dependencies from there.

**Comment by viktor-ohanyan** [comment]
@jonasbark The same issue and no solution ...
https://github.com/jonasbark/flutter_stripe_payment/issues/335

**Comment by remonh87** [comment]
@viktor-ohanyan  you are referring to the wrong repo in your last comment. That repo is deprecated.

I did run `./gradlew app:dependencies | grep stripe ` on our example app. I recommend you run the same and make sure that you do run `flutter clean` before building the app.
 
And this is the output: 


```
--- project stripe_android (n)
\--- project :stripe_android FAILED
+--- project :stripe_android
\--- com.stripe:stripe-wechatpay:17.1.0
+--- project :stripe_android FAILED
+--- project :stripe_android
+--- com.stripe:stripe-wechatpay:17.1.0
+--- com.stripe:stripe-wechatpay:{strictly 17.1.0} -> 17.1.0 (c)
+--- project :stripe_android FAILED
\--- com.stripe:stripe-wechatpay:17.1.0
+--- project :stripe_android
|    +--- com.stripe:stripe-android:18.1.0
|    |    +--- com.stripe:payments-core:18.1.0
|    |    |    +--- com.stripe:stripe-3ds2-android:6.1.2
|    |    +--- com.stripe:paymentsheet:18.1.0
|    |    |    +--- com.stripe:payments-core:18.1.0 (*)
\--- com.stripe:stripe-wechatpay:17.1.0
     +--- com.stripe:payments-core:17.1.0 -> 18.1.0 (*)
+--- project :stripe_android
+--- com.stripe:stripe-wechatpay:17.1.0
+--- com.stripe:stripe-wechatpay:{strictly 17.1.0} -> 17.1.0 (c)
+--- project :stripe_android
|    +--- com.stripe:stripe-android:18.1.0
|    |    +--- com.stripe:payments-core:18.1.0
|    |    |    +--- com.stripe:stripe-3ds2-android:6.1.2
|    |    +--- com.stripe:paymentsheet:18.1.0
|    |    |    +--- com.stripe:payments-core:18.1.0 (*)
\--- com.stripe:stripe-wechatpay:17.1.0
     +--- com.stripe:payments-core:17.1.0 -> 18.1.0 (*)
\--- com.stripe:stripe-wechatpay:17.1.0 (n)
+--- project :stripe_android FAILED
\--- com.stripe:stripe-wechatpay:17.1.0
+--- project :stripe_android FAILED
+--- project :stripe_android
+--- com.stripe:stripe-wechatpay:17.1.0
+--- com.stripe:stripe-wechatpay:{strictly 17.1.0} -> 17.1.0 (c)
+--- project :stripe_android FAILED
+--- com.stripe:stripe-wechatpay:17.1.0
+--- project :stripe_android
|    +--- com.stripe:stripe-android:18.1.0
|    |    +--- com.stripe:payments-core:18.1.0
|    |    |    +--- com.stripe:stripe-3ds2-android:6.1.2
|    |    +--- com.stripe:paymentsheet:18.1.0
|    |    |    +--- com.stripe:payments-core:18.1.0 (*)
+--- com.stripe:stripe-wechatpay:17.1.0
|    +--- com.stripe:payments-core:17.1.0 -> 18.1.0 (*)
+--- project :stripe_android
+--- com.stripe:stripe-wechatpay:17.1.0
+--- com.stripe:stripe-wechatpay:{strictly 17.1.0} -> 17.1.0 (c)
+--- project :stripe_android
|    +--- com.stripe:stripe-android:18.1.0
|    |    +--- com.stripe:payments-core:18.1.0
|    |    |    +--- com.stripe:stripe-3ds2-android:6.1.2
|    |    +--- com.stripe:paymentsheet:18.1.0
|    |    |    +--- com.stripe:payments-core:18.1.0 (*)
+--- com.stripe:stripe-wechatpay:17.1.0
|    +--- com.stripe:payments-core:17.1.0 -> 18.1.0 (*)
+--- project :stripe_android FAILED
+--- project :stripe_android
+--- com.stripe:stripe-wechatpay:17.1.0
+--- com.stripe:stripe-wechatpay:{strictly 17.1.0} -> 17.1.0 (c)
+--- project :stripe_android FAILED
+--- com.stripe:stripe-wechatpay:17.1.0
+--- project :stripe_android
|    +--- com.stripe:stripe-android:18.1.0
|    |    +--- com.stripe:payments-core:18.1.0
|    |    |    +--- com.stripe:stripe-3ds2-android:6.1.2
|    |    +--- com.stripe:paymentsheet:18.1.0
|    |    |    +--- com.stripe:payments-core:18.1.0 (*)
+--- com.stripe:stripe-wechatpay:17.1.0
|    +--- com.stripe:payments-core:17.1.0 -> 18.1.0 (*)
+--- project :stripe_android
+--- com.stripe:stripe-wechatpay:17.1.0
+--- com.stripe:stripe-wechatpay:{strictly 17.1.0} -> 17.1.0 (c)
+--- project :stripe_android
|    +--- com.stripe:stripe-android:18.1.0
|    |    +--- com.stripe:payments-core:18.1.0
|    |    |    +--- com.stripe:stripe-3ds2-android:6.1.2
|    |    +--- com.stripe:paymentsheet:18.1.0
|    |    |    +--- com.stripe:payments-core:18.1.0 (*)
+--- com.stripe:stripe-wechatpay:17.1.0
|    +--- com.stripe:payments-core:17.1.0 -> 18.1.0 (*)
```

**Comment by Solutionstbd** [comment]
Ran into the same issue. Was very annoying, especially after discovering the issue had nothing to do my latest apks.
Fixed my situation by upgrading all the apk versions on my testing tracks(internal, open and closed) to my most current  apk.
If the version that is not in compliance is still available to any users, via testing tracks or production track, they will deny your app.

**Comment by fabios9702** [comment]
I  have the same problem, I've update the privacy policy and The data security, but the app was rejected again. And It's not possibile to update a new version until this problem is fixed. Anyone knows a solution?

**Comment by leidig54** [comment]
You guys find a solution?
