### ISSUE TITLE
The plugin failed to initialize. Are you using FlutterFragmentActivity

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [flutter-stripe/flutter_stripe#463]
@jonasbark you promised to reopen closed ticket if i provide sample project so i did but ticket remains closed. SO I am opening new one - would you mind to look at it? 

https://github.com/flutter-stripe/flutter_stripe/issues/411

Thanks.

**Comment by jonasbark** [comment]
I'm only going to repeat myself:
> Please don't open a new ticket every time. I am unwilling to help any further if this behavior continues.

So I'm also closing this one. 
Closely compare your app with the example app by doing a side-by-side diff.

**Comment by jonasbark** [comment]
Actually you are right - this shouldn't be closed but be moved to Q&A discussion as it's a configuration issue 👍
