### ISSUE TITLE
The translation in French is missing a word in payment-sheet

### ISSUE THREAD

**Issue by vercorro** [flutter-stripe/flutter_stripe#468]
**Describe the bug**
The sentence in the title of the payment-sheet is not complete in French.
**To Reproduce**
1. Change the system language to French.
2. Tapping the init-payment-sheet button and then confirm button.
3. The title of the payment-sheet is "Sélectionner votre moyen de "
**Expected behavior**
The title should be "Sélectionner votre moyen de paiement"
**Smartphone / tablet**
 - Device: Realme X2 pro, Samsung Note 9.
 - OS: Android 11
 - Package version: [e.g. 1.0.0]
 - Flutter version [e.g. 2.0.0.]

**Comment by jonasbark** [comment]
Hi there! Thanks for reporting - unfortunately, we do not have control over the Payment Sheet UI so your best bet is to open a ticket on the https://github.com/stripe/stripe-android repository that we're using.
