### ISSUE TITLE
Google rejected the app with Stripe SDK 

### ISSUE THREAD

**Issue by nambv** [flutter-stripe/flutter_stripe#474]
**Describe the bug**
- After publishing & review, Google rejected my app that integrated Stripe

**To Reproduce**

![Screen Shot 2021-12-07 at 17 18 08](https://user-images.githubusercontent.com/13296355/145011264-80d41dec-7160-4fed-a52c-30636a4542f7.png)

Can you tell me how to solve this problem please? Thanks a lot

**Comment by jonasbark** [comment]
Hi!

This is likely unrelated to this plugin and we recommend that you contact the Support from Stripe e.g. using their Discord server.

**Comment by remonh87** [comment]
@nambv  also check: https://stackoverflow.com/questions/69072021/stripe-android-sdk-doesn-t-comply-with-the-user-data-and-mobile-unwanted-softwar or you need to update the privacy policy in the play store.

**Comment by nambv** [comment]
> @nambv also check: https://stackoverflow.com/questions/69072021/stripe-android-sdk-doesn-t-comply-with-the-user-data-and-mobile-unwanted-softwar or you need to update the privacy policy in the play store.

thanks a lot @remonh87, have you face this issue yet? Will updating policy be okay to make app available again. And do we need to put this policy in seperate url for Stripe only?

**Comment by ymerdrengene** [comment]
@nambv did you manage to fix the issue?

**Comment by ambr89** [comment]
@nambv, @ymerdrengene  Any news?
I used the last SDK (version 2.5.0) and there is still the problem.

**Comment by remonh87** [comment]
you need to update the privacy policy in the google play console. see [instrunctions](https://support.google.com/googleplay/android-developer/answer/9859455?hl=en#:~:text=Add%20a%20privacy%20policy,select%20Manage%20instead%20of%20start.)

**Comment by ambr89** [comment]
Hi @remonh87 ,
thanks for the answer but my privacy policy document is right updated.
![image](https://user-images.githubusercontent.com/34572512/167139892-349dfa24-40d6-41c0-9c1c-4044ae8b9b59.png)

But after the last review app was still rejected

![image](https://user-images.githubusercontent.com/34572512/167141347-9e267af4-d592-4a69-bfc5-e34187bd3c37.png)


I've tried to change **App content --> Data safety** and I've put the app in review again.
I'll write the end of the stories.

Ambra

**Comment by ambr89** [comment]
@ymerdrengene thanks but my situation is a bit o different.
I've an old version of the app in production, without stripe SDK.
I have a version on internal and closed test, with stripe SDK 2.1.1, I've update both to 2.5.0.
They reject update again.

**Comment by ambr89** [comment]
Hi.
Google accept the version, I've only created a new version with a new number.
Really I'm shocked

**Comment by remonh87** [comment]
that is life of the mobile app dev. Sometimes it really depends on the reviewer. What sometimes also helps is appealing, I found that both Apple and google are quite reasonable if you provide a plausible explanation why you did certain things.

**Comment by ambr89** [comment]
@remonh87 Exactly,
by the way, my new release, updated yesterday, was rejected again!

**Comment by fabios9702** [comment]
I have the same problem, I've update the privacy policy and The data security, but the app was rejected again. And It's not possibile to update a new  version until this problem is fixed. Anyone knows a solution?
