### ISSUE TITLE
How to obtain an ephemeralKey

### ISSUE THREAD

**Issue by eliezerp3** [flutter-stripe/flutter_stripe#478]
I do not see anything in the official stripe sdk about how to obtain an ephemeral key. I am using python. How do I get this key?

**Comment by remonh87** [comment]
I think this is what you are looking for. https://stripe.com/docs/mobile/android/basic#set-up-ephemeral-key-server-side

**Comment by jacob-hutchings** [comment]
But how do we get the stripe version from flutter_stripe to send to our backend server?

**Comment by remonh87** [comment]
@jacob-hutchings  you do not need the client to tell you the version you need the backend server to talk to stripe and provide you with the key + customer
