### ISSUE TITLE
Calling confirmSetupIntent creates a new PaymentMethod

### ISSUE THREAD

**Issue by ericalderman-emilio** [flutter-stripe/flutter_stripe#479]
We are in the process of migrating from the `stripe_payment` plugin.  We use a “future card setup” implementation so that we store the payment information for future purchases.  

Our sequence to take card info with `stripe_payment`: 
1) App calls createPaymentMethod with BillingDetails to create a PaymentMethod ID
2) Server creates a SetupIntent using customer ID and PaymentMethod ID
3) App calls confirmSetupIntent with SetupIntent client secret and existing PaymentMethod ID

With `flutter_stripe`, confirmSetupIntent requires PaymentMethodParams.  If we pass a card object with Billing Details, it returns the SetupIntent with a new PaymentMethod attached.  We don't want to create a second PaymentMethod, since we already have a valid one.

We are setting up PaymentMethodParams like this:

```
    PaymentMethodParams paymentMethodParams = PaymentMethodParams.card(
        billingDetails: _billingDetails
    );
```

We tried using `PaymentMethodParams.cardFromMethodId` which seems like it should be what we need, but this still created a new PaymentMethod.

**Comment by jamesblasco** [comment]
I think you don't need to use a confirmSetupIntent when you have already created a SetupIntent with a PaymentMethodID,
see this thread for more information: 
https://github.com/stripe/stripe-react-native/issues/371#issuecomment-878024817

**Comment by ericalderman-emilio** [comment]
We followed [this flow](https://stripe.com/docs/payments/save-and-reuse?platform=web) in building our integration, which has been working successfully.  This specifies that `confirmSetupIntent` is called after the SetupIntent is created with PaymentMethod attached, so that if there are further authentication steps the user can complete them immediately.

The [Stripe documentation](https://stripe.com/docs/js/deprecated/confirm_setup_intent) for `confirmSetupIntent` says it can take either a PaymentMethod, or a Payment Method data include Billing Details:

![Screen Shot 2021-12-11 at 8 59 28 AM](https://user-images.githubusercontent.com/51841358/145681242-bb2acedb-3618-4d5f-95ec-21d29892135f.png)

It would seem that using `PaymentMethodParams.cardFromMethodId` is what we need, but this is also creating a new PaymentMethod in the returned SetupIntent.  Can you confirm that the intended behavior is that when you provide an existing PaymentMethodId, it should not create a new PaymentMethod?

**Comment by jamesblasco** [comment]
@ericalderman-emilio  I have been researching the native layer and it looks like the `PaymentMethodParams.cardFromMethodId` is being ignore and acts as PaymentMethodParams.card().

I submitted an issue there, and I hope it can be fixed soon by the Stripe team:
https://github.com/stripe/stripe-react-native/issues/744

**Comment by ericalderman-emilio** [comment]
@jamesblasco OK thank you.

**Comment by vinnytwice** [comment]
@jamesblasco  @ericalderman-emilio 

I'm implementing `flutter_stripe` but this is quite blocking! 
I've realised it from the docs, as the only parameters you can pass to the method are a `client secret ` and `PaymentMethodParams` ( which will be seen as `payment_method_options` hence creating a new `PaymentMethod`) but this issue confirms my findings. 

So at the moment any `PaymentIntent` confirmation from the client will create a new `PaymentMethod` on the `Customer`?
 

From https://github.com/stripe/stripe-react-native/issues/371#issuecomment-878359137 
>As far as I can tell stripe intends for the payment intent to be confirmed from the server and only from the client if unavoidable. 

Is this true? I actually understood the opposite, you create the `PaymentIntent` from the server but then confirm it from the client.
If confirming a PaymentIntent from the client using `flutter_stripe` is messing up customers' `PaymentMethod`s well maybe it's just the case to confirm them from server right?
How are you managing the problem at the moment?
Many thanks.

**Comment by kcruzat** [comment]
Hello. Just wanted to add that it is working for me on one time payments eg.
stripe.Stripe.instance.confirmPayment(decodedOutput["ClientSecret"],
                        stripe.PaymentMethodParams.cardFromMethodId(
                            paymentMethodId: decodedOutput["PaymentMethod"]));
                            
not working for future/scheduled payments using confirmSetupIntent e.g

stripe.Stripe.instance.confirmSetupIntent(decodedOutput["ClientSecret"],
                        stripe.PaymentMethodParams.cardFromMethodId(
                            paymentMethodId: decodedOutput["PaymentMethod"]));
                            
the equivalent ngx-stripe is working though:

this.stripeService.confirmCardSetup(this.clientSecret, { payment_method: this.currentPaymentMethod });
