### ISSUE TITLE
Add new widget for IBAN collection

### ISSUE THREAD

**Issue by nerder** [flutter-stripe/flutter_stripe#480]
**Is your feature request related to a problem? (please describe)**
I would like to be able to collect `IBAN` for `SEPA Debit` using a smarter widget that can handle all the edge cases

**Describe the solution you'd like**
I would love a solution similar of the one from `CardDetail` and `paymentMethod.card()` so a pre-made component that is able to collect the payment method and can share the information with the `paymentMethod.sepaDebit()`

**Describe alternatives you've considered**
Implement and ad-hoc widget in our codebase

**Comment by jamesblasco** [comment]
Currently, there is not a native component in the Stripe SDK that accomplishes that, therefore we don't have it in our roadmap. The official recommended way is to use a custom flow.

You can use a normal TextField with a validator like  https://pub.dev/packages/iban
