### ISSUE TITLE
payment sheet showing TEST MODE when testEnv is set to false

### ISSUE THREAD

**Issue by SiRumCz** [flutter-stripe/flutter_stripe#483]
I have a problem with the payment sheet when trying to move from test mode to live mode. Here is how my `initPaymentSheet` looks like:
```
await Stripe.instance.initPaymentSheet(
        paymentSheetParameters: SetupPaymentSheetParameters(
          // applePay: true,
          // googlePay: true,
          style: ThemeMode.dark,
          testEnv: false,
          merchantCountryCode: 'CA',
          merchantDisplayName: 'myApp',
          customerId: _paymentSheetData['customer'],
          paymentIntentClientSecret: _paymentSheetData['paymentIntent'],
          customerEphemeralKeySecret: _paymentSheetData['ephemeralKey'],
          billingDetails: billingDetails,
        ),
      );
```

In the app, the payment sheet only shows for a very short period, and when it shows, it still says "TEST MODE" (testEnv has been set to false). I wonder if there is anything wrong with what I am doing.

**Comment by remonh87** [comment]
Did you configure the production publishable key or are you still using the test key? This typically happens when you are still using test keys  either on the app or the server.

**Comment by SiRumCz** [comment]
thank you, that explains the TEST MODE label. I tested it on my phone and can confirm the label is gone, but I still have the problem that the payment sheet won't stay, it only shows for a very short period of time.

**Comment by SiRumCz** [comment]
sorry, you are correct, I forgot to change the publishable key in app to live key.
