### ISSUE TITLE
Does not show/present payment sheet

### ISSUE THREAD

**Issue by Dr-Usman** [flutter-stripe/flutter_stripe#486]
I'm using flutter_stripe package version 2.0.2. I've intialize and configured correctly. But when trying to present paymentSheet nothing showing or happen. There's also no error cause. As it stuck at the line and not run code after that. I've also tried plugin simple example code as well but not work as i want. 

main.dart
```
  void main() async {
  Stripe.publishableKey = StripeService.publishableKey;
  Stripe.merchantIdentifier = 'merchant.flutter.stripe.test';
  Stripe.urlScheme = 'flutterstripe';
  await Stripe.instance.applySettings();
  runApp(const MyApp());
}
```
service.dart
```
Future<void> initPaymentSheet() async {
try {
  // 1. create payment intent on the server
  final paymentSheetData = await createPaymentIntent("1200", 'usd');
  print("payment intent created");

  // create some billingdetails
  final billingDetails = BillingDetails(
    email: 'email@stripe.com',
    phone: '+48888000888',
    address: Address(
      city: 'Houston',
      country: 'US',
      line1: '1459  Circle Drive',
      line2: '',
      state: 'Texas',
      postalCode: '77063',
    ),
  ); // mocked data for tests

 // 2. initialize the payment sheet
  await Stripe.instance.initPaymentSheet(
      paymentSheetParameters: SetupPaymentSheetParameters(
    applePay: true,
    googlePay: true,
    style: ThemeMode.dark,
    testEnv: true,
    merchantCountryCode: 'US',
    merchantDisplayName: 'Prospects',
    customerId: paymentSheetData!['customer'],
    paymentIntentClientSecret: paymentSheetData['paymentIntent'],
    customerEphemeralKeySecret: paymentSheetData['ephemeralKey'],
  ));
  print("payment sheet created");

  await Stripe.instance.presentPaymentSheet();

  print("after payment sheet presented");
} on Exception catch (e) {
  if (e is StripeException) {
    print("Error from Stripe: ${e.error.localizedMessage}");
  } else {
    print("Unforeseen error: ${e}");
  }
  rethrow;
}
}
```
output

> I/flutter (14987): payment intent created
I/flutter (14987): payment sheet created

Backend Response
[https://textdoc.co/akteSsynvKdZREmP](url)

**Comment by remonh87** [comment]
Normally this happens when you didn't add the correct keys. Make sure you add the correct stripe keys . Also I checked your response and it looks like there is no `payment_method`  selected because it is set to `null`. Make sure you follow either the example app or the stripe docs when creating the `payment_intent`.

**Comment by Dr-Usman** [comment]
I got the solution, there's something incorrect parameter value by my mistake while initialize the payment sheet

**Wrong**

> paymentIntentClientSecret: paymentSheetData['paymentIntent'],

**Correct**

> paymentIntentClientSecret: paymentIntentData!['client_secret'],

**Comment by sindhuperumalla** [comment]
Probably, Stripe documentation needs to be updated. On Android, it was working fine, but on iOS, the Payment sheet doesn't show up.

When initialising stripe, try adding merchant identifier.
```
    Stripe.publishableKey = paymentpublishableKey!;
    Stripe.merchantIdentifier = "Random String";
    await Stripe.instance.applySettings();
```

This worked for me.
