### ISSUE TITLE
Bug with Android Version

### ISSUE THREAD

**Issue by Softmatech** [flutter-stripe/flutter_stripe#489]
I'm facing some issues with the flutter_stripe dependencies with the android version

when i trigger the cardform i got this message error : E/MethodChannel#flutter/platform_views: Failed to handle method call
    kotlin.UninitializedPropertyAccessException: lateinit property stripeSdk has not been initialized

**Comment by remonh87** [comment]
This has probably to do with race condition between initialisation of the method channel and your code. Did you add 

`  WidgetsFlutterBinding.ensureInitialized();` to your main.dart file?

**Comment by BluMichele** [comment]
Could you explain why this is necessary?
