### ISSUE TITLE
Dependency libraries are not fixed

### ISSUE THREAD

**Issue by niklaesAtMonta** [flutter-stripe/flutter_stripe#492]
### Describe the bug
The dependencies used in this plugin are not fixed.
I reported this in an earlier release, where it was fixed.
But now the issue has resurfaced.

I am using `flutter_stripe` version 2.0.1, but it is retrieving the latest dependencies:
- `stripe_platform_interface` 2.1.0
- `stripe_ios` 2.1.0
- `stripe_android` 2.1.0

### To Reproduce
1. Delete `pubspec.lock`
2. Set `flutter_stripe` to version 2.0.1
3. `flutter pub get` command
4. Observe that the retrieved dependency packages is the newest.

### Expected behavior
I would expect that the dependencies are following the release version of the plugin

It works on my local machine, 
because the `pubspec.lock` file is specified,
with version 2.0.2 for the different dependencies.

## Temp fix for devs with the issue
Add this inside your `pubspec.yaml` (with the versions that you need):

```
dependency_overrides:
  stripe_platform_interface: 2.0.2
  stripe_ios: 2.0.2
  stripe_android: 2.0.2
```

**Comment by remonh87** [comment]
Thanks for reporting. We use a common practice that is used also in for example: Flutter Firebase. In case of a breaking changes we bump the version to a new major version (2.1.0 becomes 3.0.0) in that case the dependencies are not taken along. When we do not have breaking changes we bump it a minor version and the advantage is that minor fixes will be taken along automatically when running pub get.
