### ISSUE TITLE
Coupon Code in SheetParameters

### ISSUE THREAD

**Issue by kekko7072** [flutter-stripe/flutter_stripe#496]
Hey for my project I need to create and use **coupon code** during the check out. How can I implement the generation and usage of them in **PaymentSheet**?

For creating it I can use the HTTP API REST, but for use it it's just implemented in the `PaymentSheet` the usage of coupon code? 
Thankyou

**Comment by remonh87** [comment]
The payment sheet is used for paying and not per se for checkout. I implement it in my app the following:

1. I have a checkout page where the user enters a coupon code. When submitting I check on the backend if it is a valid coupon and give back the discount to the app
2. After that the user presses checkout and I request the backend to create a payment intent (discount included). 
3. Server gives back a payment intent and I initialise the payment sheet with that.
4. Complete the payment  etc..

Let me know if this helps.

**Comment by kekko7072** [comment]
Thank you so much so I should make a screen where user insert the coupon, then I check using Stripe API in backed and then I adjust the price ( based on coupon discount ) and mark as used the discount ( if it's personal ). At the end I open the payment sheet (with adjusted price) in the app, right ?

Which stripe api I can use to check if it's a valid coupon code?

Thank you
