### ISSUE TITLE
call createPaymentMethod function from CardFieldInputDetails 

### ISSUE THREAD

**Issue by g-apparence** [flutter-stripe/flutter_stripe#497]
Hi,
loving the work here. 👏 
I'm currently trying to create a subscription (for physical goods so I can use stripe). 
The thing is I need to save a user card so I can't use the awesome payment sheet.

**Describe the bug**
- create a page with CardField
- try to save this card on Stripe
as we don't have a tokenize method we can't save this new paymentMethod.

If there is another way this could be interesting to add a documentation.

Edit : 
It seems there is a workaround without using createPaymentMethod manually. 
[see doc ](https://stripe.com/docs/payments/save-during-payment?platform=android&ui=payment-sheet)
Will give it a try.

**Comment by remonh87** [comment]
@g-apparence  I try to understand the remark "I need to save the user card so I can't use the awesome payment sheet". You can save customer card credentials by creating a customer in the backend. When you provide the client with the customer key and the ephemeral key you get the previously entered cards on the payment sheet. Maybe I misunderstood your requirement.

**Comment by g-apparence** [comment]
Yes I just discovered it. Thank you for your answer.
I didn't know paymentsheet was usable for more than instant payment. 

I was trying to : 
- create a card using CardField
- save it using (createPaymentMethod on mobile)
- save it on customer as default (on back)
- create a subscription on the user using the default payment method

As I didn't want to send number and cvc to my back I wanted to use createPayment method to call stripe API directly from mobile.

So as you said I was maybe in the wrong now that Paymentsheet exists. 
Here's what I'll do
// 1 - Creates a new subscription, with the customer and price IDs.
// 2 - Generates an invoice for the initial subscription cycle.
// 3 - Collects payment details and pays the invoice.
// 4 - Sets the payment method as the default payment method for the subscription, which is a requirement for subsequent payments.

**So I have two questions remaining :** 
- my first method used to work. Should this be recommended to not save a card yourself?
- in that case maybe that  createPayment and Cardfield shouldn't be exposed anymore?

**Comment by remonh87** [comment]
Paymentmethods are an old way of handling payments. Stripe recommends using payment intents and setupintents.  I think as long as you create a customerId and supply it when using the card field or the payment sheet you will always see the saved payment methods (on the payment sheet you will see it only when the user ticks the box save card). 

You probably already found it but I found this [doc](https://stripe.com/docs/billing/subscriptions/overview#subscription-lifecycle) very useful in understanding subscription in stripe.
 
There is indeed no need to send the Cvc and card number to the backend since the Stripe sdk will handle everything for you.

**Comment by g-apparence** [comment]
Thank you for your answer. 
Maybe this can help others (I've seen some questions similar to this one in discussions tab). 
What about adding this to the readme like "How to handle subscription using PaymentSheet"?

**Comment by remonh87** [comment]
yes we are going to improve the docs the coming time since now we are getting feature complete

**Comment by FilledStacks** [comment]
I ended up here searching for a way to:

1. Take card details on a form in my app (not built in stripe for)
2. Save that to an accountId on stripe which I have already created

It's so strange, stripe is going from an easy to understand system and making it more and more confusing as they grow haha. Even if they wanted to swap out their mechanism and flow of capturing user details they could have left the association for developers to use real world domain language. I just want to add a card and save it. I can't figure it out with this package 😓 

Any help would be appreciated

**Comment by remonh87** [comment]
We launched more elaborate docs: https://docs.page/flutter-stripe/flutter_stripe/sheet#2-add-an-enpoint-server-side regarding references to Stripe docs.

@FilledStacks  I think above references will help you. You need basically a customerId and a ephermal key on the backend. Basically Stripe is very easy when you use the payment sheet. Customised widgets involve more manual work and also you need to be wary of PCI compliance.

**Comment by FilledStacks** [comment]
Yeah, we have a customer id and the key. I don't want to use the payment sheet, it doesn't fit with what we want in our app. But maybe we will, I'll run it past my team. Thanks for replying. I appreciate it.
