### ISSUE TITLE
Following migration guide from stripe_payment but suggested "confirmPaymentMethod" doesn't exist

### ISSUE THREAD

**Issue by carman247** [flutter-stripe/flutter_stripe#498]
I'm trying to follow the migration guide https://github.com/jonasbark/flutter_stripe_payment/blob/master/migration.md but the suggested replacement for `confirmPaymentIntent` doesn't exist... 

![Screenshot 2021-12-23 at 15 18 23 (2)](https://user-images.githubusercontent.com/31341463/147254846-7f00793f-f7c0-45bb-bc49-fe6281d4cd4e.png)

Nor can I find another method that accept `clientSecret` and `paymentMethodId`

**Comment by remonh87** [comment]
I think you need to use this method https://github.com/flutter-stripe/flutter_stripe/blob/9a7b5f19d81376fa3045464447172df275ccae47/packages/stripe/lib/src/stripe.dart#L235

**Comment by carman247** [comment]
It's all good. I've managed to figure out saved payment method now.
