### ISSUE TITLE
stripe_checkout redirectToCheckout() method name typo

### ISSUE THREAD

**Issue by kylegraycar** [flutter-stripe/flutter_stripe#511]
**Describe the bug**
In https://pub.dev/packages/stripe_checkout, the example code shows the method redirectCheckout(), when it is actually redirectToCheckout() in the docs https://pub.dev/documentation/stripe_checkout/latest/stripe_checkout/stripe_checkout-library.html

Package version 0.1.0

**Comment by kylegraycar** [comment]
Also, a link to an example app would be really helpful. Thank you!

**Comment by jamesblasco** [comment]
This is updated in the version 1.0.0. Thanks for submitting the issue
