### ISSUE TITLE
[stripe_checkout] Live Stripe.js integrations must use HTTPS error

### ISSUE THREAD

**Issue by kylegraycar** [flutter-stripe/flutter_stripe#516]
**Describe the bug**
I'm testing stripe_checkout with live checkout session creation and a live publishable key. This throws a javascript exception:
```
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: PlatformException(runJavascript_failed, Failed running JavaScript, JavaScript string was: 'var stripe = Stripe("pk_live_xxxxx");
           stripe.redirectToCheckout({sessionId: "cs_live_xxxxx"}).then(function (result) {
             result.error.message = 'Error'
           });
           123;
           '
           Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred" UserInfo={WKJavaScriptExceptionLineNumber=1, WKJavaScriptExceptionMessage=IntegrationError: Live Stripe.js integrations must use HTTPS. For more information: https://stripe.com/docs/security/guide#tls, WKJavaScriptExceptionColumnNumber=275312, WKJavaScriptExceptionSourceURL=https://js.stripe.com/v3/, NSLocalizedDescription=A JavaScript exception occurred}, null)
           #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
           #1      MethodChannel._inv<…>
```

**To Reproduce**
1. Use redirectToCheckout() method with live keys
3. Observe above failure with exception 

**Expected behavior**
The checkout session should display

**Smartphone / tablet**
 - Device: iPhone 13 Simulator
 - Package version: 0.1.0
 - Flutter version: 2.8.1

**Comment by jonasbark** [comment]
The error message says it - you're not allowed to use plain HTTP here. If you must test it against a local server, then you may want to look into e.g. ngrok and use the HTTPS URL that they provide.

As it's not related to the plugin I'm gonna close this issue
