### ISSUE TITLE
The client_secret provided does not match the client_secret associated with the PaymentIntent. 

### ISSUE THREAD

**Issue by vercorro** [flutter-stripe/flutter_stripe#517]
**Describe the bug**
Initialisation of the payment-sheet works well but the confirmation step gives this error :

" code: FailureCode.Failed, localizedMessage: The client_secret provided does not match the client_secret associated with the PaymentIntent., message: The client_secret provided does not match the client_secret associated with the PaymentIntent., stripeErrorCode: null, declineCode: null, type: null). "

I replaced the publishable and secret keys with the production live mode keys. 
To remove any doubt I hardcoded the customer_Id in my cloud function so it's the same in my flutter app and backend.

Interesting thing, in the Stripe dashboard the payment is listed but tagged as "incomplete"

**To Reproduce**
1. tap on init payment .
2. Tapping the confirm button.
3. failure with exception :
"The client_secret provided does not match the client_secret associated with the PaymentIntent."

**Expected behavior**
Payment-sheet should appear to allow the choice of payment methods.
 
**Smartphone / tablet**
 - Device: Realme x2 pro , Huawei mate 20 pro, Iphone 13 pro max
 - OS: Android 11, iOS 15 
 - Package version: 2.1.0
 - Flutter version 2.8

**Additional context**
Here's my cloud function code:

```
exports.payment = functions.https.onCall(async(data, context) => {
  const { secret_key } = getKeys();
  
  const stripe = new Stripe(secret_key as string, {
    apiVersion: '2020-08-27',
    typescript: true,
  });


  const ephemeralKey = await stripe.ephemeralKeys.create(
    { customer: "cus_KdD2Rxcp4JjGT8" },
    { apiVersion: '2020-08-27' }
  );
  const paymentIntent = await stripe.paymentIntents.create({
    amount: data.message,
    currency: 'eur',
    customer: "cus_KdD2Rxcp4JjGT8",
  });

  return {
    paymentIntent: paymentIntent.client_secret,
    ephemeralKey: ephemeralKey.secret,
    customer: "cus_KdD2Rxcp4JjGT8",
  }
}); 

```
Here's my flutter code : 

```
 Future<void> initPaymentSheet(StateSetter setState) async {
    try {
      final data = await _createTestPaymentSheet();
      print('the data in initPaymentSheet is '+data.toString());
      final billingDetails = BillingDetails(
        email: 'vercorrobers2@gmail.com',
        phone: '+48888000999',
        address: Address(
          city: 'Houston',
          country: 'US',
          line1: '1459  Circle Drive',
          line2: '',
          state: 'Texas',
          postalCode: '77063',
        ),
      ); 

      await Stripe.instance.initPaymentSheet(
        paymentSheetParameters: SetupPaymentSheetParameters(
          paymentIntentClientSecret: data['paymentIntent'],
          merchantDisplayName: 'Flutter Stripe Store Demo',
          customerId: data['customer'],
          customerEphemeralKeySecret: data['ephemeralKey'],
          applePay: true,
          googlePay: true,
          style: ThemeMode.light,
          primaryButtonColor: Colors.blueAccent,
          billingDetails: billingDetails,
          testEnv: false,
          merchantCountryCode: 'DE',
        ),
      );
      setState(() {
        paymentSheetReady=true;
      });
    } catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Error: $e')),
      );
      rethrow;
    }
  }
  HttpsCallable callable = FirebaseFunctions.instance.httpsCallable('payment',
      options: HttpsCallableOptions(timeout: Duration(seconds: 5)));

  Future<Map<String, dynamic>> _createTestPaymentSheet() async {
    print('the amount entered '+widget._mission.montantEstime!.toInt().toString());
    try {
      final HttpsCallableResult result = await callable.call(
        <String, int>{
          'message': widget._mission.montantEstime!.toInt(),
        },
      );
      print("the result is  "+ result.data.toString());

      Map<String, dynamic> map={
        "ephemeralKey": result.data['ephemeralKey'],
        "paymentIntent": result.data['paymentIntent'],
        "customer": result.data['customer'],
      };
      final jsonResponse=json.encode(map).toString();
      print('map is '+jsonResponse.toString());
      final body = json.decode(jsonResponse.toString());
      if (body['error'] != null) {
        throw Exception(body['error']);
      }
      return body;
    } on Exception catch (e) {
      print('caught firebase functions exception '+e.toString());
      return <String, dynamic>{
        'error': "caught firebase functions exception",
      };
    } catch (e) {
      print('caught generic exception '+e.toString());
      print(e);
      return <String, dynamic>{
        'error': "caught generic exception",
      };
    };
  }

  Future<void> confirmPayment(StateSetter setState) async {
    try {
      await Stripe.instance.presentPaymentSheet();

      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Payment succesfully completed'),
        ),
      );

    } on Exception catch (e) {
      if (e is StripeException) {
        print('stripe error '+e.toString());
        print('stripe error '+e.error.toString());

        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Error from Stripe: ${e.error.localizedMessage}'),
          ),
        );
      } else {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Unforeseen error: ${e}'),
          ),
        );
      }
    }
  }

```

**Comment by Manasmd** [comment]
I am having the same issue

**Comment by remonh87** [comment]
looks like you didn't set the correct account_id in your application. Can you check you call: https://github.com/flutter-stripe/flutter_stripe/blob/9a7b5f19d81376fa3045464447172df275ccae47/packages/stripe/lib/src/stripe.dart#L39 and provide the correct account id?

**Comment by vinnytwice** [comment]
@remonh87 Could you please clarify this a bit?
>/// Reconfigures the Stripe platform by applying the current values for
  /// [publishableKey], [merchantIdentifier], [stripeAccountId],
  /// [threeDSecureParams], [urlScheme]
  Future<void> applySettings() => _initialise(
        publishableKey: publishableKey,
        merchantIdentifier: merchantIdentifier,
        stripeAccountId: stripeAccountId,
        threeDSecureParams: threeDSecureParams,
        urlScheme: urlScheme,
      );

In my case I am a marketplace with connected accounts an I'm initialising flutter_stripe in my buyer app (Stripe Customer API ) so `publishableKey` is of course my platform Account one , but `merchantIdentifier` and  `stripeAccountId` and `urlScheme`? Should I've the blank or should I put my platform AccountId??

**Comment by remonh87** [comment]
@vinnytwice  to be honest that is a very specific config Maybe good to check with Stripe support. I think the accountID needs to match the accountId of the payment intent.

**Comment by vinnytwice** [comment]
@remonh87 ok, looking at it this way that should be fo using flutter_stripe in my seller app..while for the buyer app I could just use the platform publishable key. I'll dig deeper. Thank you

**Comment by vercorro** [comment]
I just added this before initiating the payment-sheet and it worked!
``
      Stripe.publishableKey = "your_publishable_key";;
      await Stripe.instance.applySettings();
``

**Comment by remonh87** [comment]
closed because original issue is solved. For more support let's use the discussions
