### ISSUE TITLE
Google pay must be installed

### ISSUE THREAD

**Issue by ramesh998** [flutter-stripe/flutter_stripe#520]
I am getting this error when using google pay on my code as well as on your repo

StripeException(error: LocalizedErrorMessage(code: FailureCode.Failed, localizedMessage: presentForPaymentIntent() may only be called when Google Pay is available on this device., message: presentForPaymentIntent() may only be called when Google Pay is available on this device., stripeErrorCode: null, declineCode: null, type: null))

**Comment by remonh87** [comment]
This error comes from the Stripe native SDK and mainly has to do with the fact that the configuration is incorrect. Make sure you follow the steps described in: https://stripe.com/docs/google-pay. For example:`    implementation 'com.google.android.gms:play-services-wallet:18.1.3'` needs to be added to your application.

See also our example: https://github.com/flutter-stripe/flutter_stripe/blob/71b65a62c4b735912f286000a05731fe97ff9b60/example/lib/screens/wallets/google_pay_stripe_screen.dart#L10

I just tested our example app and Google pay works there.
