### ISSUE TITLE
Does this package directly connect with Stripe API or I have to use my Node server ?

### ISSUE THREAD

**Issue by vinnytwice** [flutter-stripe/flutter_stripe#522]
Following the link https://mypace-co-ltd.medium.com/use-flutter-stripe-for-payment-and-subscription-registration-without-a-backend-9c503ed86fdd I see that using `flutter_stripe` all data are passed to Stripe via https requests to their Direct API endpoints , which they strongly discourage because it make you NOT PCI Compliant ( or at least makes it harder for you to be Compliant ).
>We strongly discourage passing card information directly to Stripe’s API as it means your integration is directly handling card information. Even if you do not store any payment information, we can only help simplify PCI compliance if you’ve integrated with Checkout, Elements, or our mobile SDKs.
...
you’ll be required to upload your SAQ D annually to prove your business is PCI compliant. SAQ D is the most onerous of all the SAQs, with over 40 pages of requirements you must implement to remain PCI compliant.

If I would have to set in my Node server all the endpoints to simply pass the data inserted  in my app ( card details) to Stripe via the Stripe.js sdk I already use there to create users, accounts, payment intents etc etc, what's the point of using this flutter_stripe package then?
Many thanks.

**Comment by remonh87** [comment]
I would recommend using our example app approach. What we do is have a backend (we use the stripe node.js example backend) that talks to the Stripe SDK. The app should be responsible for collecting the card details and we use Stripe native components for this. The backend get's notified by Stripe when a payment succeeds (e.g. through a Webhook). For more info check: https://stripe.com/docs/payments/accept-a-payment

**Comment by vinnytwice** [comment]
>we use Stripe native components for this

@remonh87 like Stripe Elements you mean?

 > The backend get's notified by Stripe when a payment succeeds (e.g. through a Webhook). 
 
 if I'm going through my server I'd know by Stripe SDK response if a Payment was successful or not without listening to any Webhook right?

**Comment by oliveyew** [comment]
Hi @vinnytwice checkout this video it's more easy
https://www.youtube.com/watch?v=9fwQRHKuUmU
