### ISSUE TITLE
[Android] - CardField card details has merged the date and card number 

### ISSUE THREAD

**Issue by SebghatYusuf** [flutter-stripe/flutter_stripe#524]
**Describe the bug**
in Android for some devices CardField is showing card number and date placeholders merged together. 
![1641556621326](https://user-images.githubusercontent.com/48417629/148610000-80e5788e-5512-4c4d-99d8-ff50b1069e6b.JPEG)

**To Reproduce**
1. Install the app on lower-resolution phones or make text bigger from the phone settings. 
2. open card field page.

**Expected behavior**
the placeholders should not overlap and if there's not enough space, only show one placeholder at a time. 

**Smartphone / tablet**
 - Device: [RUIO S6501  A-ONE ]
 - OS: [Android 11]
 - Package version: [2.0.1]
 - Flutter version [2.8.1]

**Comment by jonasbark** [comment]
Thanks for reporting - unfortunately, we have very limited support for the layout of this view. It is using the native view from the official Stripe Android SDK: https://github.com/stripe/stripe-android
We recommend opening up a ticket there.

**Comment by skyler-stripe** [comment]
@jonasbark could you give some insight on to what classes from the android sdk you're using and how you're using them. I'm working on reproducing this issue and am unable to without flutter.

**Comment by jonasbark** [comment]
@skyler-stripe we're using the exact same ones from the Stripe React Native team:
https://github.com/stripe/stripe-react-native/blob/master/android/src/main/java/com/reactnativestripesdk/CardFormView.kt
