### ISSUE TITLE
Cannot create a SepaDirect payment method using createPaymentMethod

### ISSUE THREAD

**Issue by martgeier** [flutter-stripe/flutter_stripe#525]
This code always produces the error "Card details not complete" when calling createPaymentMethod

`final paymentParams = PaymentMethodParams.sepaDebit(
          iban: 'AT611904300234573201',
          billingDetails: BillingDetails(email: 'max@muster.com', name: 'Max Muster'),
          setupFutureUsage: PaymentIntentsFutureUsage.OffSession);
      final paymentMethod = await Stripe.instance.createPaymentMethod(paymentParams);`

**Comment by remonh87** [comment]
I really would advice against using the PaymentMethods since they are an old way of handling payments. If you use `PaymentIntents` it should work. I think https://github.com/flutter-stripe/flutter_stripe/blob/main/example/lib/screens/regional_payment_methods/ideal_screen.dart is a good starting point.

**Comment by martgeier** [comment]
Problem is, I need to setup a payment method without actually doing a payment right away. The payment method is then used on a weekly basis to purchase. But it is not a subscription, no need for off-session payment. How can I achieve this with SEPA direct?

**Comment by remonh87** [comment]
Maybe [setupintents](https://stripe.com/docs/api/setup_intents) can work? Else I would recommend to contact Stripe support to advice which use case suits you best.

**Comment by martgeier** [comment]
SetupIntents ultimately needs a PaymentMethodId and the only way to get it is trough the PaymentMethod API. I managed to work around it by using the PaymentIntents API, but of course I lost the ability to add a Sepa payment method without purchasing. 

I still think this should be fixed or removed from flutter_stripe. I checked the network communication and I'm getting the error without any network requests going out. So the error is actually in the createPaymentMethod code of flutter_stripe.

**Comment by remonh87** [comment]
We are tied to what Stripe SDK offers us and this error comes from their SDK. I found some additional docs about sepa payments here: 

https://stripe.com/docs/payments/sepa-debit/set-up-payment?platform=react-native

I agree we have to better in documenting payments.
