### ISSUE TITLE
error with strip when i want to build or run the flutter app 

### ISSUE THREAD

**Issue by Krahost** [flutter-stripe/flutter_stripe#526]
*** Please anybody to help me solve this strip issue , i get this error whenever i want to run or build my app***

../../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_stripe-2.0.1/lib/flutter_stripe.dart:1:1: Error: 'CardChangedCallback' is exported from both 'package:flutter_stripe/src/widgets/card_field.dart' and 'package:stripe_platform_interface/src/card_edit_controller.dart'.
export 'package:stripe_platform_interface/stripe_platform_interface.dart';
^
../../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_stripe-2.0.1/lib/flutter_stripe.dart:1:1: Error: 'CardFocusCallback' is exported from both 'package:flutter_stripe/src/widgets/card_field.dart' and 'package:stripe_platform_interface/src/card_edit_controller.dart'.
export 'package:stripe_platform_interface/stripe_platform_interface.dart';
^
../../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_stripe-2.0.1/lib/flutter_stripe.dart:1:1: Error: 'CardFieldContext' is exported from both 'package:flutter_stripe/src/widgets/card_field.dart' and 'package:stripe_platform_interface/src/card_edit_controller.dart'.
export 'package:stripe_platform_interface/stripe_platform_interface.dart';
^
../../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_stripe-2.0.1/lib/flutter_stripe.dart:1:1: Error: 'CardEditController' is exported from both 'package:flutter_stripe/src/widgets/card_field.dart' and 'package:stripe_platform_interface/src/card_edit_controller.dart'.
export 'package:stripe_platform_interface/stripe_platform_interface.dart';

**Comment by remonh87** [comment]
You need to remove the import to: `'package:stripe_platform_interface/src/card_edit_controller.dart'.` and only keep the import to `'package:stripe_platform_interface/stripe_platform_interface.dart'`
