### ISSUE TITLE
Not possible to complete `CardField` in ios

### ISSUE THREAD

**Issue by nerder** [flutter-stripe/flutter_stripe#529]
**Describe the bug**
As in the title, is not possible due to a known bug of the numeric keyboard in `flutter` to actually complete the `CardField` insertion and therefore activate any button that was attached to that `completed` status as shown in the examples.

Usually, the workaround for when this happens in a `TextField` is to do something like this: https://stackoverflow.com/a/57074822/4420152

What can be done here?

**To Reproduce**
1. Complete the insertion of all the fields in a `CardField`
2. See the missing done button

**Expected behavior**

I expect to see a done button 

**Smartphone / tablet**
 - Device: iPhone X
 - OS: iOS 15,
 - Package version: `latest`
 - Flutter version: `latest` (beta)

**Comment by jamesblasco** [comment]
I am checking and it looks possible to complete all the card parameters.

Notice that we are using native CardField that uses native text fields. I don't think it is possible to edit the keyboard configuration to display a done button as the implementation of the CardField is private. 


<img width="326" alt="Screenshot 2022-01-15 at 11 49 37" src="https://user-images.githubusercontent.com/19904063/149619047-cce336c4-1c82-4714-8665-1b4bd0c5392e.png">

**Comment by nerder** [comment]
Hey @jamesblasco

Thank you for your reply, the problem for us happen when we do something similar to this code: https://github.com/flutter-stripe/flutter_stripe/blob/56a443bb0b13204eb0c4f163e02b6a35547b5f61/example/lib/screens/card_payments/no_webhook_payment_screen.dart#L48

Because `complete` does not become true until it's submitted so the button pay doesn't get activated.

**Comment by jamesblasco** [comment]
Could you show me so code? Are you listening to the controller changes?

**Comment by nerder** [comment]
@jamesblasco here you can find our implementation: https://github.com/striveapp/checkin/blob/master/lib/src/ui/components/card_sheet.dart

Actually we are listening on `CardFieldInputDetails`

**Comment by jamesblasco** [comment]
https://github.com/striveapp/checkin/blob/1aa66fa82cd8402d976841e302bcfe3dd18d36cc/lib/src/ui/components/card_sheet.dart#L53

You have to update the state to rebuild the widget
setState(() => _card = card);

**Comment by nerder** [comment]
Oh, yes!

The fact that on Android the keyboard has a done button for some reasons tricked us and we didn't spot this mistake on our code!

Very nice catch thank you so much for your help 🙏🏼
