### ISSUE TITLE
Have some problem after changing stripe SDK

### ISSUE THREAD

**Issue by myunggeonchung** [flutter-stripe/flutter_stripe#533]
After upgrading the flutter version(2.8.1), I found that the existing stripe SDK can’t be used anymore. Stripe_payment sdk should be changed to flutter_stripe (Totally different SDK).
After looking through documents and sample code about flutter_stripe. I realized that the codes should be changed a lot.
So I need the technical support. First of all, I created default_payment_profile_apple_pay.json and defaut_payment_profile_google_pay.json that are needed for native payment. But I’m not sure which part should be customized to apply it to our app.
I just changed merchantIdentifier, displayName in apple_pay file and allowedCardNetworks in google_pay file.
Is it enough to use it for a native payment or are there any other parts to be changed.

**Comment by jamesblasco** [comment]
Could you explain what features of the Stripe SDK you want to implement on your app?

**Comment by myunggeonchung** [comment]
![스크린샷 2022-01-27 오전 11 25 14](https://user-images.githubusercontent.com/54304539/151280731-113cf069-7f9c-4587-afd6-1ba3164869ed.png)
I don't know how to customize this file.

**Comment by remonh87** [comment]
Sorry for some reason this slipped passed our nets, hopefully you managed to solve it. To be honest I would advice to use the Stripe implemented version of Google Pay. It has a nicer and easier integration. Check out for example: https://github.com/flutter-stripe/flutter_stripe/blob/main/example/lib/screens/wallets/google_pay_stripe_screen.dart
