### ISSUE TITLE
platform exception in stripe_flutter 

### ISSUE THREAD

**Issue by devtaju** [flutter-stripe/flutter_stripe#536]
**Describe the bug**
im facing the issue after the server to getting the clientsecret successfully  after that i'm setup the stripe code then i click to hit the request of stripe payment getting I'm showing the platform exception i'm already update mainactivity.kt file fluttteractvity to fragment
below im paste  the my issue which one showing into log please check and help me how to fix 

PlatformException(flutter_stripe initialization failed, The plugin failed to initialize: Your theme isn't set to use Theme.AppCompat or Theme.MaterialComponents. Please check the README: https://github.com/flutter-stripe/flutter_stripe#android, null, null)

**Smartphone / tablet**
 - Device: [e.g. iPhone X]
 - OS: [e.g. iOS 13, Android 12]
 - Package version: [e.g. 2.1.1]
 - Flutter version [e.g. 2.8.1]
=

**Comment by jamesblasco** [comment]
Make sure you follow the step in the readme where you need to change the style.xml file and use Theme.AppCompat or Theme.MaterialComponents.

If you continue to have problems, please feel free to write with more detail what steps have you followed and the Android and gradle version in this discussion: https://github.com/flutter-stripe/flutter_stripe/discussions/538

**Comment by devtaju** [comment]
hi  thanks for you reply 
i am already change into style.xml night and normal both mode added into the Theme.AppCompat and Theme.MaterialComponent but after that comes  
PlatformException(flutter_stripe initialization failed, The plugin failed to initialize: Your theme isn't set to use Theme.AppCompat or Theme.MaterialComponents. Please check the README: https://github.com/flutter-stripe/flutter_stripe#android, null, null) this issue in log and not bottom sheet enable for stripe ui ..

**Comment by jamesblasco** [comment]
Could you share with me the style.xml file and the AndroidManifest of the app?

**Comment by devtaju** [comment]
sure below i m pasting my style.xml dark and normal both case same

<?xml version="1.0" encoding="utf-8"?>
<resources>
    
    <style name="LaunchTheme" parent="@android:style/Theme.Black.NoTitleBar">
        
        <item name="android:windowBackground">@drawable/launch_background</item>
    </style>
    
    <style name="NormalTheme" parent="@android:style/Theme.MaterialComponents">
        <item name="android:windowBackground">?android:colorBackground</item>
    </style>

</resources>


below manifest activity 


     <activity
            android:name=".MainActivity"
            android:debuggable="false"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">

**Comment by jamesblasco** [comment]
As you can see that is not a Theme.AppCompact or Theme.MaterialComponents theme:

Please use the ones in the example:
https://github.com/flutter-stripe/flutter_stripe/blob/main/example/android/app/src/main/res/values/styles.xml

If that does not fix it, please share the AndroidManifest file here so I can help

**Comment by devtaju** [comment]
hi after the same copy and paste into my style.xml this 
https://github.com/flutter-stripe/flutter_stripe/blob/main/example/android/app/src/main/res/values/styles.xml after that my log showing error is this 

Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     AAPT: error: resource android:style/Theme.MaterialComponents not found.
     error: failed linking references.





here below my manifest code paste check this also
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.lenscartapp"
    xmlns:tools="http://schemas.android.com/tools">


    <uses-permission android:name="android.permission.INTERNET"/>

   <application
        android:label="lenscart"
       tools:node="merge"
       android:allowBackup="true"
       android:hardwareAccelerated="true"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:debuggable="false"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>

**Comment by devtaju** [comment]
below this is my manifest file codepls check and revert me fast

 <manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.lenscartapp"
    xmlns:tools="http://schemas.android.com/tools">


    <uses-permission android:name="android.permission.INTERNET"/>

   <application
        android:label="lenscart"
       tools:node="merge"
       android:allowBackup="true"
       android:hardwareAccelerated="true"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:debuggable="false"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>

**Comment by jamesblasco** [comment]
Then try using "Theme.AppCompat.Light.NoActionBar" for both styles in that file

**Comment by devtaju** [comment]
im used into style.xml both "Theme.AppCompat.Light.NoActionBar" after that i am run the app then in log shwoing the error is 

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     AAPT: error: resource android:style/Theme.AppCompat.Light.NoTitleBar not found.
     error: resource android:style/Theme.AppCompat.Light.NoTitleBar not found.
     error: resource android:style/Theme.AppCompat.Light.NoActionBa not found.
     error: resource android:style/Theme.AppCompat.Light.NoActionBa not found.
     error: failed linking references.

**Comment by jonasbark** [comment]
please post your full style.xml - you mentioned the LaunchTheme earlier, which is not the one where the correct style must be applied to

**Comment by devtaju** [comment]
below im paste my both style sheet code 

<?xml version="1.0" encoding="utf-8"?>
<resources>
    
    <style name="LaunchTheme" parent="@android:style/Theme.Light.NoTitleBar">
        
        <item name="android:windowBackground">@drawable/launch_background</item>
    </style>
    
    <style name="NormalTheme" parent="@android:style/Theme.AppCompat">
        <item name="android:windowBackground">?android:colorBackground</item>
    </style>
</resources>



below my night mode style.xml code

<?xml version="1.0" encoding="utf-8"?>
<resources>
    
    <style name="LaunchTheme" parent="@android:style/Theme.AppCompat.Light.NoTitleBar">
        
        <item name="android:windowBackground">@drawable/launch_background</item>
    </style>
    
    <style name="NormalTheme" parent="@android:style/Theme.AppCompat">
        <item name="android:windowBackground">?android:colorBackground</item>
    </style>
</resources>

**Comment by jonasbark** [comment]
we need the full file to help you - you only posted a small part of it

**Comment by jamesblasco** [comment]
@devtaju please, copy and paste all the file as 
https://github.com/flutter-stripe/flutter_stripe/blob/main/example/android/app/src/main/res/values/styles.xml

You are using 
```<style name="LaunchTheme" parent="@android:style/Theme.AppCompat.Light.NoTitleBar">```
And it should be:
```<style name="LaunchTheme" parent="Theme.AppCompat.Light.NoActionBar">````

Please, copy and paste all the file XD

**Comment by devtaju** [comment]
hi thanks for this now its working thanks a lot for solving my problem thank you soo much
