### ISSUE TITLE
Android device doesn't record the card

### ISSUE THREAD

**Issue by NuHunter** [flutter-stripe/flutter_stripe#543]
![image](https://user-images.githubusercontent.com/95836909/149724849-7233a36f-81d8-4805-a1f0-04e7edb8929c.png)
When I run it on an Android device, it doesn't record the card, but when I run it on an iOS device, it does

**Comment by jonasbark** [comment]
What do you mean by 'record the card'?

**Comment by NuHunter** [comment]
> 

When we add the credit card information on the ios device for the first time and pay successfully, it will automatically save the credit card information. When we use it again, the bound credit card popup window will pop up, so we do not need to fill in the credit card information, which is normal on ios. But on Android, even if you check save credit card, the next time you use it, you still don't pop up the attached credit card information

**Comment by NuHunter** [comment]
> What do you mean by 'record the card'?

When using a credit card on an Android device, the saved credit card list does not pop up, and you need to re-enter your credit card information each time to use it

**Comment by jonasbark** [comment]
This is not reproducible in the example, so you'd better check your server's implementation. Compare it to the server provided in the example.
