### ISSUE TITLE
CardFormField field styling unusable when phone is in dark mode

### ISSUE THREAD

**Issue by kcruzat** [flutter-stripe/flutter_stripe#544]
**Describe the bug**
The field styling for the CardFormField widget changes when the phone's system is in dark mode making it unusable.

**To Reproduce**
1. Turn the phone (iOS or Android) to dark mode
2. View CardFormFieldWidget
3. Widget styling is unusable

**Expected behavior**
Expected to not change when phone's system  changes or a property in the widget to force this from not happing. Other styling properties would be helpful to control the label colour and text colour etc.

**Smartphone / tablet**
 - Device: LG V50, iPhone X
 - OS: Android 11, iOS 14.5.1
 - Package version: 2.0.2
 - Flutter version 2.5.3

**Additional context**
![image](https://user-images.githubusercontent.com/35256345/149741906-97a9d2e6-46ac-47ab-974b-5d8ad0e279aa.png)
![IMG_0149](https://user-images.githubusercontent.com/35256345/149741938-38923b95-2e5a-47d6-ae95-621a5a8ee561.jpeg)

**Comment by remonh87** [comment]
thanks for reporting and you are absolutely right! Unfortunately we have no control over the layout of the card form field since it is a Stripe native component. See: https://github.com/stripe/stripe-react-native/issues/771

**Comment by Shuvo1260** [comment]
Is there any solution for this issue?

**Comment by jaredweinfurtner** [comment]
How is this stale?  This is a major blocking issue.

**Comment by remonh87** [comment]
> How is this stale? This is a major blocking issue.

We are depending on stripe to fix the issue since we integrate their sdk. See issue mentioned above. They are currently working on fixing it in their native sdks once it is in there we can integrate it.

**Comment by korzonkiee** [comment]
Any updates on this? Seems like the customization has been achieved in stripe-react-native repository few days ago ([#849](https://github.com/stripe/stripe-react-native/pull/849/)). I'm happy to help adding this feature to the flutter_stripe repository.

**Comment by otopba** [comment]
Any updates?(

**Comment by remonh87** [comment]
This is fixed in version 3.0.0 which is shipped today

**Comment by ShwetaChauhan18** [comment]
Getting error after updating version: WidgetsBinding.instance.focusManager.primaryFocus

**Comment by otopba** [comment]
@ShwetaChauhan18 I created an issue
https://github.com/flutter-stripe/flutter_stripe/issues/730
