### ISSUE TITLE
[Flutter - Android] : presentPaymentSheet() is not opening stripe payment sheet in android

### ISSUE THREAD

**Issue by NuHunter** [flutter-stripe/flutter_stripe#545]
[Flutter - Android] : presentPaymentSheet() is not opening stripe payment sheet in android
![image](https://user-images.githubusercontent.com/95836909/149860907-bda72fa6-fe9b-48ac-a17c-0d67f577b322.png)

**Comment by remonh87** [comment]
Can you please follow the issue template because it is super hard for us to triage this issue. Normally this has to do with either you didn't follow the Android config on the readme or you added a wrong config (Stripe key etc). Please add some more additional info

**Comment by NuHunter** [comment]
> Can you please follow the issue template because it is super hard for us to triage this issue. Normally this has to do with either you didn't follow the Android config on the readme or you added a wrong config (Stripe key etc). Please add some more additional info

thank you ~ When using a credit card on an Android device, the saved credit card list does not pop up, and you need to re-enter your credit card information each time to use it

**Comment by NuHunter** [comment]
> Can you please follow the issue template because it is super hard for us to triage this issue. Normally this has to do with either you didn't follow the Android config on the readme or you added a wrong config (Stripe key etc). Please add some more additional info
![149724849-7233a36f-81d8-4805-a1f0-04e7edb8929c](https://user-images.githubusercontent.com/95836909/149877719-f0544173-d4be-4683-882e-dec230181a55.png)
look at the picture,
When using a credit card on an Android device, the saved credit card list does not pop up, and you need to re-enter your credit card information each time to use it

**Comment by remonh87** [comment]
> > Can you please follow the issue template because it is super hard for us to triage this issue. Normally this has to do with either you didn't follow the Android config on the readme or you added a wrong config (Stripe key etc). Please add some more additional info
> 
> thank you ~ When using a credit card on an Android device, the saved credit card list does not pop up, and you need to re-enter your credit card information each time to use it

This is something different than previously reported. 

The saved credit card will be opened when you use the customerID and ephermal key in the payment intent and specify this on the payment sheet.

**Comment by NuHunter** [comment]
> > > 您能否按照问题模板进行操作，因为我们很难对这个问题进行分类。通常这与您没有遵循自述文件中的 Android 配置有关，或者您添加了错误的配置（条带键等）。请添加更多附加信息
> > 
> > 
> > 谢谢~在安卓设备上使用信用卡时，不弹出保存的信用卡列表，每次使用都需要重新输入信用卡信息
> 
> 这与之前报道的有所不同。
> 
> 当您在付款意图中使用 customerID 和临时密钥并在付款表上指定时，将打开保存的信用卡。

Here's the front-end code：↓

try {
        dynamic authToken = await PayReposity.createPayAuthToken(
            orderNo: orderNo, payChannel: PayChannel.visapay.name);
        dynamic data = json.decode(authToken);

        String? customerId = data['customerId'] as String?;
        String? paymentIntent = data['paymentIntent'] as String?;
        String? ephemeralKey = data['ephemeralKey'] as String?;

        if (isNotEmpty(customerId) && isNotEmpty(paymentIntent)) {
          try {
            await Stripe.instance.initPaymentSheet(
                paymentSheetParameters: SetupPaymentSheetParameters(
                    // customFlow: false,
                    applePay: false,
                    googlePay: false,
                    style: ThemeMode.system,
                    testEnv: true,
                    merchantCountryCode: 'DE',
                    merchantDisplayName: Strings().logoTitle,
                    customerId: customerId,
                    paymentIntentClientSecret: paymentIntent,
                    customerEphemeralKeySecret: ephemeralKey 
                    ));
          } catch (e) {
            log('^^^^^^^initPaymentSheet is error:$e ^^^^^^^');
          }

          try {
            await Stripe.instance.presentPaymentSheet(
                // parameters: PresentPaymentSheetParameters(
                //     clientSecret: paymentIntent!, confirmPayment: true),
                );
          } catch (e) {
            log('^^^^^^^presentPaymentSheet is error: $e ^^^^^^^');
          }

**Comment by remonh87** [comment]
I would advice you to check the Stripe dashboard and see if there is a customer key and ephemeral key in the payment intent. Also add some logging in the app to check that the key is provided into the payment sheet. 

I did check our library yesterday and for me saving cards are working.

**Comment by NuHunter** [comment]
> I would advice you to check the Stripe dashboard and see if there is a customer key and ephemeral key in the payment intent. Also add some logging in the app to check that the key is provided into the payment sheet.
> 
> I did check our library yesterday and for me saving cards are working.

Thanks ,That sounds great! There's one more question I'd like to ask you：
https://stripe.com/docs/mobile/android/basic#set-up-ephemeral-key
![image](https://user-images.githubusercontent.com/95836909/150282790-7d93ffb5-266e-41a3-a049-91b5a042b8ac.png)
![image](https://user-images.githubusercontent.com/95836909/150282842-5212de49-14e3-4ebe-9f10-21549c865c58.png)
How can the server get the app_version value?

**Comment by remonh87** [comment]
The api version needs to be set on the backend. The app doesn't have anything to do with this. 

See https://stripe.com/docs/upgrades. 

I am closing this for now since your question has more to do with backend implementation and is not an issue with our library.

**Comment by NuHunter** [comment]
> 



> The api version needs to be set on the backend. The app doesn't have anything to do with this.
> 
> See https://stripe.com/docs/upgrades.
> 
> I am closing this for now since your question has more to do with backend implementation and is not an issue with our library.

My problem has been solved ~
 Because our ephemeralKey was not built according to the rules, when we built according to the rules it worked fine. Thank you ~
