### ISSUE TITLE
Not able to run app after adding this plugin

### ISSUE THREAD

**Issue by pg598595** [flutter-stripe/flutter_stripe#548]
I have added the latest version of the plugin

  flutter_stripe: ^2.1.1

After adding this plugin, when I am trying to run the application It is giving the following error:

e: /Users/priyankagupta/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/stripe_android-2.1.0/android/src/main/kotlin/com/flutter/stripe/StripeAndroidPlugin.kt: (22, 7): Redeclaration: StripeAndroidPlugin

**Comment by remonh87** [comment]
this looks like some mis configuration in grade and Android. Did you already try to clean the project ? 

Also check your grade settings: https://github.com/flutter-stripe/flutter_stripe/blob/main/example/android/gradle/wrapper/gradle-wrapper.properties

And the Android tools version which you can find here
 https://github.com/flutter-stripe/flutter_stripe/blob/56a443bb0b13204eb0c4f163e02b6a35547b5f61/example/android/build.gradle#L9

If this doesn't work can you provide some more info?

**Comment by pg598595** [comment]
This Solved the issue,
