### ISSUE TITLE
Need clear migration guide from stripe_payment

### ISSUE THREAD

**Issue by GMerakis** [flutter-stripe/flutter_stripe#549]
Currently there's https://github.com/jonasbark/flutter_stripe_payment/blob/master/migration.md

Previously we could have easily get payment method with

var paymentMethod = await StripePayment.paymentRequestWithCardForm(
          CardFormPaymentRequest());

This does not seem possible in flutter stripe and in the examples you just mock the details:

https://github.com/flutter-stripe/flutter_stripe/blob/main/example/lib/screens/card_payments/custom_card_payment_screen.dart#L142

**Comment by remonh87** [comment]
@jonasbark  can you answer this ticket as previous maintainer

**Comment by jonasbark** [comment]
Hi @GMerakis - feel free to continue discussion in the GitHub discussion in this repo or in the repository of the stripe_payment plugin :)
