### ISSUE TITLE
App crashes in release mode both on android and iOS

### ISSUE THREAD

**Issue by Rimantovas** [flutter-stripe/flutter_stripe#552]
Calling the method confirmPayment() makes the app crash when in release mode. In debug mode everything works perfectly on iOS while android seems to only sometimes work on debug. Though I think android has an other issues of cardfield not being present when calling payment method. The situation is the same on both android and iOS.

**Comment by jonasbark** [comment]
Please use the bug report template and provide proper information:
https://github.com/flutter-stripe/flutter_stripe/issues/new?assignees=&labels=needs+triage&template=bug-report.md&title=

**Comment by remonh87** [comment]
duplicate of #672
