### ISSUE TITLE
Recieving PlatformException flutter_stripe initialization failed Exception

### ISSUE THREAD

**Issue by code-gene** [flutter-stripe/flutter_stripe#553]
I am receiving the below Exception after upgrading flutter stripe version to 2.1.1. I was already using2.1.0 version which was working fine but now it is showing this.

Meanwhile I have also made all the changes written in the documentation under requirement section but still it's not working.

![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/72328725/150301693-4290b10e-79da-49cb-b2e3-454b3bc62d8f.png)

**Comment by BriceChk** [comment]
I am facing the same issue.  It was working fine, the only change I can think of in my project is upgrades of other packages. Now it won't initialize correctly on Android.

**Comment by jonasbark** [comment]
Please double-check your styles.xml files for Android. Post them here if you don't see an issue and keep in mind that by default there is one file for dark theme and light theme in separate directories.

**Comment by BriceChk** [comment]
> 

Thanks for the reminder. For me it was the issue.

**Comment by Manasmd** [comment]
Yes setting the styles .xml in both "values" and "values-night" fixed the issue for me as well
make sure to add both as per the Adnroid setup guide mentioned on the home page of the repo

values/styles.xml: https://github.com/flutter-stripe/flutter_stripe/blob/main/example/android/app/src/main/res/values/styles.xml#L15

values-night/styles.xml:
https://github.com/flutter-stripe/flutter_stripe/blob/main/example/android/app/src/main/res/values-night/styles.xml#L16
