### ISSUE TITLE
Creating Payment Method through Payment sheet

### ISSUE THREAD

**Issue by Kang-Kim1** [flutter-stripe/flutter_stripe#563]
We used `stripe_payment` for a while, but switched to `flutter_stripe` sdk due to some compatibility issue. Currently, we are using `CardFormField` for users to add the card information on our app. 
However, due to some UI issues on specific devices, we are now considering `PaymentSheet` form as a replacement. We looked through the codes in example application, and realized that `Stripe.instance.createPaymentMethod` is not being called by PaymentSheet, and wonder if PaymentSheet is the correct form to create `PaymentMethod`.  Please correct me if I am wrong, and if not, could anyone please share the proper way that I can create payment method using `PaymentSheet`?

**Comment by remonh87** [comment]
The  paymentsheet is used to collect relevant data for a`paymentIntent`.  Stripe considers the `PaymentMethod` legacy and they advice everyone to use `PaymentIntents`.  

How it basically works is:
- Create a payment intent on the backend 
- Use the payment intent in the paymentsheet
-  The customer enters the necessary details to confirm the payment intent on the client side.
-  Stripe provides a callback to the backend (e.g. through a webhook) that the payment is processed.

**Comment by Kang-Kim1** [comment]
Thanks for the response, I've got few more things to clarify :  
1. Despite `PaymentMethod` is considered as legacy, I see they are still being called before creating PaymentIntents in example app like below :
```
      // 2. Create payment method
      final paymentMethod =
          await Stripe.instance.createPaymentMethod(PaymentMethodParams.card(
        billingDetails: billingDetails,
      ));

      // 3. call API to create PaymentIntent
      final paymentIntentResult = await callNoWebhookPayEndpointMethodId(
        useStripeSdk: true,
        paymentMethodId: paymentMethod.id,
        currency: 'usd', // mocked data
        items: [
          {'id': 'id'}
        ],
      );
``` 


Above 2 steps in the code are being used to create payment method for CardFormFIeld & CardField form, and it seems id of PaymentMethod is required to create PaymentIntent. If this example code can be considered as legacy as well, what would be the proper code without using PaymentIntents over PaymentMethod?


2. When we were using CardFormField, the following code was being called by adding credit card information   
```
final paymentMethod = await Stripe.instance.createPaymentMethod(PaymentMethodParams.card());
```  
Simply, what we are trying to do is that we want the same PaymentMethod information using `PaymentSheet`. If it is feasible, could you please share a brief code example or explanation?

**Comment by remonh87** [comment]
1 and 2 I think this doc  is very elaborate and gives a lot of explanation. https://stripe.com/docs/payments/payment-methods .  The paymentsheet requires a payment intent or setup intent. In our examples we follow that document. We create first a payment method and then on the backend we call the Stripe API that returns a payment intent which we use.

3: that one is related to the fact that you probably miss some configuration on Android (unfortunately configuring Android is a bit cumbersome). Checkout https://github.com/flutter-stripe/flutter_stripe#android . We will launch some improved docs soon on this area.

**Comment by remonh87** [comment]
improved docs are online: https://docs.page/flutter-stripe/flutter_stripe/troubleshooting
