### ISSUE TITLE
Version Solving Failed

### ISSUE THREAD

**Issue by JatinAgrawal94** [flutter-stripe/flutter_stripe#565]
**Describe the bug**
I am having issue of 'Version Solving failed"
Phone Used: Redmi Note 5 Pro
Android Version: 11
 
Error on Terminal:
"
Because file_picker 2.1.7 depends on plugin_platform_interface ^1.0.1 and every version of stripe_platform_interface depends on plugin_platform_interface ^2.0.0, file_picker 2.1.7 is incompatible with stripe_platform_interface.
Because flutter_stripe >=2.1.0 <2.1.1 depends on stripe_platform_interface ^2.1.0 and flutter_stripe >=2.1.1 depends on stripe_platform_interface ^2.1.1, flutter_stripe >=2.1.0 requires stripe_platform_interface ^2.1.0.
Thus, file_picker 2.1.7 is incompatible with flutter_stripe >=2.1.0.
So, because careconnect(App name) depends on both file_picker 2.1.7 and flutter_stripe ^2.1.0, version solving failed."

**Comment by jonasbark** [comment]
I recommend updating your file_picker plugin. 2.1.7 is very old - the newest version is file_picker 4.3.3

**Comment by JatinAgrawal94** [comment]
I tried that but then i creates issues with other firebase packages.
At last adding this in pubscpec.yaml solved my issue.
dependency_overrides:
   plugin_platform_interface: '>=2.0.0'
