### ISSUE TITLE
Apple Pay not working on real device even when card is added.

### ISSUE THREAD

**Issue by charlesarchibong** [flutter-stripe/flutter_stripe#566]
**Describe the bug**
Apple Pay it not working on physical iPhone

 final support = await Stripe.instance.checkApplePaySupport()

support is always = false

**To Reproduce**
1. Initial stripe and called the Stripe.instance.checkApplePaySupport().

**Expected behavior**
Stripe.instance.checkApplePaySupport() should returns true is card is added to my Apple Pay

**Smartphone**
 - Device: [ iPhone 12 Pro Max]
 - OS: [iOS 13.5]
 - Package version: [2.1.1]
 - Flutter version [2.8.1.]

**Additional context**
Every part of the integration works and even Apple Pay works on simulator.

**Comment by remonh87** [comment]
Did you follow the instructions stated here: https://developer.apple.com/documentation/passkit/apple_pay/setting_up_apple_pay ?

**Comment by charlesarchibong** [comment]
> Did you follow the instructions stated here: https://developer.apple.com/documentation/passkit/apple_pay/setting_up_apple_pay ?
> 
> Simulators work a bit different because they use some sandbox environment

Yes

**Comment by SebghatYusuf** [comment]
Same issue, 
I've done the apple instructions step by step, but still, I get the `PlatformException(Failed, Payment not completed, null, null)` error. 
Any suggestions?

**Comment by remonh87** [comment]
For me Apple Pay works in production environment . Normally the fact that something works in dev and not production can be related to the following:
- not created a merchant id on developer.apple.com
- You are using the dev keys on either client or server ( you can check in the stripe dashboard if that is the case).
- Another question: are you using the `pay` library from Flutter or our native apple payment?

**Comment by remonh87** [comment]
ok and you run the app on a real phone ? Also the Apple Pay capability is added in the app ?

**Comment by SebghatYusuf** [comment]
Yes I ran the app on a real device, and I've added the apply pay capability in xcode.

**Comment by SebghatYusuf** [comment]
Any suggestions here??

**Comment by SebghatYusuf** [comment]
Any updates here??

**Comment by ahmedatTakalam** [comment]
I ran into the same issue that apple pay on a real device is not working however its works on a simulator

**Comment by liamsammut97** [comment]
Make sure your bundle id matches the merchant name, i had the same issue. When i changed my merchant id to match my bundle id all is good. Example: merchant.(your bundle id)
