### ISSUE TITLE
Card details not complete, stripeErrorCode: null, declineCode: null, type: null

### ISSUE THREAD

**Issue by priyankgujarati1991** [flutter-stripe/flutter_stripe#568]
**StripeException "Card details not complete" on Android while it not doing so on iOS.**
CardDetails _card = CardDetails();

 Future<void> makePayment() async {
    await Stripe.instance.applySettings();
    _card = _card.copyWith(number: '4242424242424242');
    _card = _card.copyWith(expirationYear: int.tryParse('42'));
    _card = _card.copyWith(expirationMonth: int.tryParse('04'));
    _card = _card.copyWith(cvc: '424');
    try {
      const billingDetails = BillingDetails(
        email: 'email@stripe.com',
        phone: '+48888000888',
        address: Address(
          city: 'Houston',
          country: 'US',
          line1: '1459  Circle Drive',
          line2: '',
          state: 'Texas',
          postalCode: '77063',
        ),
      );

      final paymentMethod = await Stripe.instance.createPaymentMethod(
        const PaymentMethodParams.card(
          setupFutureUsage: PaymentIntentsFutureUsage.OnSession,
          billingDetails: billingDetails,
        ),
      );
      debugPrint(paymentMethod.id);
      showSnackBar('Payment ID', paymentMethod.id.toString(), Colors.black);
      final paymentIntentResult = await callNoWebhookPayEndpointMethodId(
        useStripeSdk: true,
        paymentMethodId: paymentMethod.id,
        currency: 'usd', // mocked data
        items: [
          {'id': 'id'}
        ],
      );
   
      // displayPaymentSheet();
    } catch (e, s) {
      debugPrint('exception:$e$s');
    }
  }

Here I want only paymentMethod ID in iOS it is working fine.

**Comment by remonh87** [comment]
@priyankgujarati1991  we upgraded our library can you check if the issue still occurs on version 2.2.0?

**Comment by lrorpilla** [comment]
Also having this issue on my Google Pixel 6 Pro on the latest Flutter stable and on `flutter_stripe` 2.2.0. iOS works, but Android doesn't.

`onCardChanged` doesn't trigger at all and I can't extract or update card fields from the `CardField`.

**Comment by lrorpilla** [comment]
Strangely, putting the screen on landscape allows me to access a different fullscreen text editor where the numbers are censored. But it allows full entry of the CVC and acknowledges the card as complete. In portrait, even completing the CVC text field doesn't work and CVC remains incomplete.

**Comment by remonh87** [comment]
@lrorpilla that is interesting. From version 2.2.0 we have added a new `ValidationState` to the `CardFieldInput` see: https://github.com/flutter-stripe/flutter_stripe/blob/f77f7c14f843c1803a2b77a8effe294156a86e65/packages/stripe_platform_interface/lib/src/models/card_field_input.dart#L172

Can you listen to the card controller and check if the CVC is considered to be valid?

**Comment by lrorpilla** [comment]
Hi, @remonh87. Thanks for responding. 

The setup I had was actually using `onCardChanged` to update a `card` variable, then check if that variable is complete or not.

I've changed it to what you suggested, assigning a `CardEditController` to a `CardField`.

Even if I've filled up the card number, expiry and CVC fields and they are complete visually, the controller returns `false` for both `complete` and `CardValidationState.Unknown` for `validCVC`.

I had this issue in 2.1.1 and I updated to 2.2.0 to fix it actually, and I can't seem to get the field to return `true` for `complete` on Android, and I can't use `createPaymentMethod` whereas I could on iOS.

**Comment by remonh87** [comment]
I did check the card field and for me it is working with latest version on a pixel4. Did you update the state when an event is received? See for example: https://github.com/flutter-stripe/flutter_stripe/blob/b6bb2ec72b3b45092eddd6053893e56d139de2b7/example/lib/screens/card_payments/no_webhook_payment_cardform_screen.dart#L29

**Comment by lrorpilla** [comment]
I now have the state set to update `onCardChanged` and the `Pay` button is now lighting up properly. Though I'm still having the root issue, `createPaymentMethod` works on iOS perfectly well, but I'm having problems on both my Android devices, on a Pixel 6 and a OnePlus 6.

On an iPhone simulator and a real device, payment is processed but I'm getting this on Android devices:
```
StripeException(error: LocalizedErrorMessage(code: FailureCode.Failed, localizedMessage: Card details not complete, message: Card details not complete, stripeErrorCode: null, declineCode: null, type: null))
```

**Comment by lrorpilla** [comment]
Hey @remonh87, this is the value that I'm getting from `controller.details.toJson()`, I've filled up the form and `complete` is updating correctly, but I can't correctly use `createPaymentMethod` on Android where I could on iOS, this is the JSON:

```
{complete: true, last4: 5454, expiryMonth: 2, expiryYear: 25, postalCode: null, brand: MasterCard, number: null, cvc: null, validExpiryDate: Valid, validCVC: Valid, validNumber: Valid}
```

**Comment by remonh87** [comment]
I will need to dive into this weekend. Looks like a bug if it works on iOS but not on Android.

**Comment by remonh87** [comment]
Can try running our example app and try it there? It really looks like sth in your implementation because I spend some time trying to reproduce it but for me Android is working fine

**Comment by lrorpilla** [comment]
I can't really give more information other than that putting the app on landscape will pass this card details complete check and allow it to work as it should.

iOS functionality is fine, but Android seems to fail to get parameters and is dependent on how the UI is laid out somehow, since it sometimes works and doesn't depending on the orientation.

**Comment by remonh87** [comment]
can you check with latest master of our librart?
