### ISSUE TITLE
PlatformException(flutter_stripe initialization failed, The plugin failed to initialize:

### ISSUE THREAD

**Issue by pradeep14598** [flutter-stripe/flutter_stripe#572]
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(flutter_stripe initialization failed, The plugin failed to initialize:
E/flutter (22171): Your theme isn't set to use Theme.AppCompat or Theme.MaterialComponents.
E/flutter (22171): Please check the README: https://github.com/flutter-stripe/flutter_stripe#android, null, null)
E/flutter (22171): #0      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:155:7)
E/flutter (22171): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
E/flutter (22171): <asynchronous suspension>
E/flutter (22171): #2      MethodChannelStripe.initialise (package:stripe_platform_interface/src/method_channel_stripe.dart:43:5)
E/flutter (22171): <asynchronous suspension>
E/flutter (22171): #3      Stripe._initialise (package:flutter_stripe/src/stripe.dart:417:5)
E/flutter (22171): <asynchronous suspension>
E/flutter (22171): #4      main (package:customer/main.dart:28:3)
E/flutter (22171): <asynchronous suspension>
E/flutter (22171):

**Comment by remonh87** [comment]
Please follow the instructions: https://github.com/flutter-stripe/flutter_stripe#android .  Android is quite annoying to configure  we will improve the documentation of it soon
