### ISSUE TITLE
Payment Error Handling on the Web

### ISSUE THREAD

**Issue by mcmikecreations** [flutter-stripe/flutter_stripe#573]
**Describe the bug**
Observed during debugging on Chrome. My current code to make a payment is:
```
    try {
      final paymentMethod = PaymentMethodParams.card(
        billingDetails: details,
      );
      final intent = await Stripe.instance.confirmPayment(secretKey, paymentMethod);

      logger.d(intent);
      if (intent.status == PaymentIntentsStatus.Succeeded) {
        NavigatorUtils.returnRoute<WebPaymentPayload>(context, WebPaymentSuccessPayload(verified: true));
      } else {
        NavigatorUtils.returnRoute(context, WebPaymentErrorPayload(message: intent.description));
      }
    }
    on StripeException catch (e) {
      handleError(context, e.error.localizedMessage ?? '');
    }
    on StripeError catch (e) {
      handleError(context, e.message);
    }
    on PlatformException catch (e) {
      handleError(context, e.message ?? '');
    }
    on Exception catch (e) {
      handleError(context, e.toString());
    }
    on Error catch (e) {
      handleError(context, e.toString());
    }
```
Despite all these efforts, when something goes wrong in the intent (card number is wrong, problems with internet, wrong secret key from backend, etc.), flutter_stripe_web on [this line](https://github.com/flutter-stripe/flutter_stripe/blob/d09d3da0f355544cde2e4a1e23b8253cebe2c207/packages/stripe_web/lib/src/web_stripe.dart#L163) throws an error that I can't catch. Because of this, an `[object Object]` is printed in the console, the card field disappears and nothing else happens. I can't enter new information, can't re-send it, nothing. I have to navigate to a different view and then back to get the card field to show up again.

**To Reproduce**
1. Generate wrong secret key on the backend.
2. Enter card info.
3. Tapping the confirm button.
4. Observe uncaught error.

**Expected behavior**
I expect to be able to catch the error and properly handle it depending on the type, message, etc.

**Smartphone / tablet**
 - Device: Chrome
 - OS: Win 11 Pro
 - Package version: flutter_stripe: ^2.1.1  flutter_stripe_web: ^0.1.1
 - Flutter version: 2.8.1

**Additional context**
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.22000.434])
    • Flutter version 2.8.1 at C:\Soft\Android\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (7 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1
[√] Connected device (3 available)
    • Chrome (web)        • chrome       • web-javascript • Google Chrome 97.0.4692.99

**Comment by remonh87** [comment]
Thanks for the clear description very helpful. You are right we should provide an error that can be caught.

**Comment by RawatAshish11** [comment]
bro fix this package it is far away from bull shit fix it

**Comment by RawatAshish11** [comment]
why  are you making server

**Comment by RawatAshish11** [comment]
you are calling same api 3 times 
in local server and all 3 api are doing the same work

**Comment by jonasbark** [comment]
Hi @RawatAshish11 - I have just reported your comment. Please provide constructive feedback and refrain yourself from harassing anyone on this platform.

**Comment by VictorSDK** [comment]
I'm having same issue, mobile version returns a `StripeException`, but web returns a `LegacyJavaScriptObject` that has no public properties.

**Comment by devyev** [comment]
We are having the same issue. Any timeline on the fix?

**Comment by wintrue** [comment]
We are having the same issue. Any timeline on the fix?

**Comment by wintrue** [comment]
We are having the same issue. Any timeline on the fix?

**Comment by wintrue** [comment]
@jonasbark [remonh87](https://github.com/remonh87) 我们有同样的问题。有修复的时间表吗？

**Comment by sramac2** [comment]
I would love to have a fix for this. This would help me to show the exact error of what happened

**Comment by debjeetdebnath** [comment]
+1

**Comment by jamesblasco** [comment]
Hello! I I am currently working on a fix for this. Will update when it is fixed

**Comment by fahadappguy** [comment]
> Hello! I I am currently working on a fix for this. Will update when it is fixed

Hi @jamesblasco.
      It would be great if you test this method "confirmPayment" for Flutter Web, after this fix. It's working fine on Android but for Web throwing exception pasted below. 
I can test it on my end when you are done with this fix. I will be more than happy to test it if you notify me, You can drop an email here "adnan.nazir.dev@gmail.com" or contact me on Insta "adnannazir398".
`{
  "error": {
    "code": "resource_missing",
    "doc_url": "https://stripe.com/docs/error-codes/resource-missing",
    "message": "No such payment_intent: 'pi_3Lst68RiaRAgBC6I1170rELR'",
    "param": "intent",
    "request_log_url": "https://dashboard.stripe.com/test/logs/req_gwncznon0QZqHt?t=1665773974",
    "type": "invalid_request_error"
  }
}`

**Comment by chatoromo** [comment]
James. Thanks for working on this. Can you please provide us with an estimate? I was also talking to my team last week about fixing it on our end since it is a critical part of our project.

**Comment by mminhlequang** [comment]
@jamesblasco hi i have question
I saw you already throw `StripeError` but why i can't catch it

always catch ` _$36_PaymentElementChangeEvent` (js object)
or i missing something?

![image](https://github.com/flutter-stripe/flutter_stripe/assets/46816270/f15cc446-0c94-483e-bc23-1abb0c9776ba)

**Comment by dioseltorre** [comment]
> I saw you already throw `StripeError` but why i can't catch it
> 
> always catch ` _$36_PaymentElementChangeEvent` (js object) or i missing something?

Same here with `Stripe.instance.confirmSetupIntent()` on web. Error's runtime type is `_$36_PaymentElementChangeEvent`.
