### ISSUE TITLE
Build Ios null safety errors

### ISSUE THREAD

**Issue by spiderion** [flutter-stripe/flutter_stripe#574]
The error only appears when trying to build for IOS.

Uncategorized (Xcode): Command CompileSwift failed with a nonzero exit code

Swift Compiler Error (Xcode): Value of optional type '[AnyHashable : Any]?' must be unwrapped to a value of type '[AnyHashable : Any]'
/Users/ionolaru/WorkProjects/discuvur/ios/Pods/Stripe/Stripe/STPBSBNumberValidator.swift:85:26

Swift Compiler Error (Xcode): Value of optional type '[AnyHashable : Any]??' not unwrapped; did you mean to use 'try!' or chain with '?'?
/Users/ionolaru/WorkProjects/discuvur/ios/Pods/Stripe/Stripe/STPAPIClient+Payments.swift:234:28

Swift Compiler Error (Xcode): Value of optional type '[String : Any]?' must be unwrapped to refer to member 'subscript' of wrapped base type '[String : Any]'
/Users/ionolaru/WorkProjects/discuvur/ios/Pods/Stripe/Stripe/STPTelemetryClient.swift:187:26

Swift Compiler Error (Xcode): Value of optional type '[String : Any]?' must be unwrapped to refer to member 'subscript' of wrapped base type '[String : Any]'
/Users/ionolaru/WorkProjects/discuvur/ios/Pods/Stripe/Stripe/STPTelemetryClient.swift:190:26

Swift Compiler Error (Xcode): Value of optional type '[String : Any]?' must be unwrapped to refer to member 'subscript' of wrapped base type '[String : Any]'
/Users/ionolaru/WorkProjects/discuvur/ios/Pods/Stripe/Stripe/STPTelemetryClient.swift:194:25

Swift Compiler Error (Xcode): Value of optional type '[String : Any]?' must be unwrapped to a value of type '[String : Any]'
/Users/ionolaru/WorkProjects/discuvur/ios/Pods/Stripe/Stripe/STPTelemetryClient.swift:198:33

Could not build the application for the simulator.
Error launching application on iPhone 13.

**Comment by remonh87** [comment]
Can you follow our issue template? I need some more info about the Flutter version (output of the command `flutter doctor`) and the version of our library you are using.

**Comment by spiderion** [comment]
**Describe the bug**
Build Ios null safety errors in the swift code.

**To Reproduce**
1. Try to build the IOS App using the flutter_stripe package.
exception below

**Expected behavior**
should build on ios with no "swift" compile  errors

**Smartphone / tablet**

 - OS: [ iOS 13, Android 10]
 - Package version: [2.1.1]
 - Flutter version:   2.8.1 • channel stable • 

**Additional context**
The error only appears when trying to build for IOS.

Uncategorized (Xcode): Command CompileSwift failed with a nonzero exit code

Swift Compiler Error (Xcode): Value of optional type '[AnyHashable : Any]?' must be unwrapped to a value of type '[AnyHashable : Any]'
/Users/ionolaru/WorkProjects/discuvur/ios/Pods/Stripe/Stripe/STPBSBNumberValidator.swift:85:26

Swift Compiler Error (Xcode): Value of optional type '[AnyHashable : Any]??' not unwrapped; did you mean to use 'try!' or chain with '?'?
/Users/ionolaru/WorkProjects/discuvur/ios/Pods/Stripe/Stripe/STPAPIClient+Payments.swift:234:28

Swift Compiler Error (Xcode): Value of optional type '[String : Any]?' must be unwrapped to refer to member 'subscript' of wrapped base type '[String : Any]'
/Users/ionolaru/WorkProjects/discuvur/ios/Pods/Stripe/Stripe/STPTelemetryClient.swift:187:26

Swift Compiler Error (Xcode): Value of optional type '[String : Any]?' must be unwrapped to refer to member 'subscript' of wrapped base type '[String : Any]'
/Users/ionolaru/WorkProjects/discuvur/ios/Pods/Stripe/Stripe/STPTelemetryClient.swift:190:26

Swift Compiler Error (Xcode): Value of optional type '[String : Any]?' must be unwrapped to refer to member 'subscript' of wrapped base type '[String : Any]'
/Users/ionolaru/WorkProjects/discuvur/ios/Pods/Stripe/Stripe/STPTelemetryClient.swift:194:25

Swift Compiler Error (Xcode): Value of optional type '[String : Any]?' must be unwrapped to a value of type '[String : Any]'
/Users/ionolaru/WorkProjects/discuvur/ios/Pods/Stripe/Stripe/STPTelemetryClient.swift:198:33

Could not build the application for the simulator.
Error launching application on iPhone 13.

Flutter doctor: 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.6 20G165 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.1)
[✓] VS Code (version 1.64.0)
[✓] Connected device (3 available)

• No issues found!

**Comment by remonh87** [comment]
I think there is sth wrongly cached. Did you already try to run `flutter clean`  and build it again. What also can help is remove your `podfile.lock` and run pod install again?  I did just create a base flutter project, added the library and could run it without any issues.

**Comment by remonh87** [comment]
@spiderion  I think you missed the following requirement: `Compatible with apps targeting iOS 11 or above`. Make sure you specify the minimum iOS requirement in your pod file like: https://github.com/flutter-stripe/flutter_stripe/blob/d09d3da0f355544cde2e4a1e23b8253cebe2c207/example/ios/Podfile#L2

This will solve your issue.

**Comment by remonh87** [comment]
Do you think you can share your pod file with us?

**Comment by spiderion** [comment]
# Uncomment this line to define a global platform for your project
platform :ios, '12.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
         config.build_settings['ENABLE_BITCODE'] = 'NO'
         config.build_settings['SWIFT_VERSION'] = '4.2'
           config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
                 '$(inherited)',

                 ## dart: PermissionGroup.calendar
                  'PERMISSION_EVENTS=0',

                 ## dart: PermissionGroup.reminders
                  'PERMISSION_REMINDERS=0',

                 ## dart: PermissionGroup.contacts
                  'PERMISSION_CONTACTS=0',

                 ## dart: PermissionGroup.camera
                  'PERMISSION_CAMERA=0',

                 ## dart: PermissionGroup.microphone
                  'PERMISSION_MICROPHONE=0',

                 ## dart: PermissionGroup.speech
                  'PERMISSION_SPEECH_RECOGNIZER=0',

                 ## dart: PermissionGroup.photos
                   'PERMISSION_PHOTOS=0',

                 ## dart: [PermissionGroup.location, PermissionGroup.locationAlways, PermissionGroup.locationWhenInUse]
                 # 'PERMISSION_LOCATION=0',

                 ## dart: PermissionGroup.notification
                  'PERMISSION_NOTIFICATIONS=0',

                 ## dart: PermissionGroup.mediaLibrary
                  'PERMISSION_MEDIA_LIBRARY=0',

                 ## dart: PermissionGroup.sensors
                  'PERMISSION_SENSORS=0'
               ]
       end
  end
end

**Comment by spiderion** [comment]
`# Uncomment this line to define a global platform for your project
platform :ios, '12.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
         config.build_settings['ENABLE_BITCODE'] = 'NO'
         config.build_settings['SWIFT_VERSION'] = '4.2'
           config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
                 '$(inherited)',

                 ## dart: PermissionGroup.calendar
                  'PERMISSION_EVENTS=0',

                 ## dart: PermissionGroup.reminders
                  'PERMISSION_REMINDERS=0',

                 ## dart: PermissionGroup.contacts
                  'PERMISSION_CONTACTS=0',

                 ## dart: PermissionGroup.camera
                  'PERMISSION_CAMERA=0',

                 ## dart: PermissionGroup.microphone
                  'PERMISSION_MICROPHONE=0',

                 ## dart: PermissionGroup.speech
                  'PERMISSION_SPEECH_RECOGNIZER=0',

                 ## dart: PermissionGroup.photos
                   'PERMISSION_PHOTOS=0',

                 ## dart: [PermissionGroup.location, PermissionGroup.locationAlways, PermissionGroup.locationWhenInUse]
                 # 'PERMISSION_LOCATION=0',

                 ## dart: PermissionGroup.notification
                  'PERMISSION_NOTIFICATIONS=0',

                 ## dart: PermissionGroup.mediaLibrary
                  'PERMISSION_MEDIA_LIBRARY=0',

                 ## dart: PermissionGroup.sensors
                  'PERMISSION_SENSORS=0'
               ]
       end
  end
end
`

**Comment by spiderion** [comment]
I will try that and let you know. Thank you.

**Comment by spiderion** [comment]
Yes, that actually worked 
config.build_settings['SWIFT_VERSION'] = '5.0' was the solution
Thank you for the support.
@remonh87
