### ISSUE TITLE
[stripe_checkout] not working on Real device

### ISSUE THREAD

**Issue by surveshoeb** [flutter-stripe/flutter_stripe#576]
**Bug**
stripe_checkout package not working in Live mode on Android/iOS device. I'm able to use it with the Test key but not with the Live key. It only shows the white page without any error. I can use generated checkout URL on the web but by using sessionId in stripe_checkout it won't work.

**To Reproduce**
Steps to reproduce the behaviour:
1. Use stripe_checkout example app
2. Replace key with Live key
3. Navigate to the payment page.

**Smartphone / tablet**
 - Device: Any Physical Android/iOS Mobile
 - OS: Any version of Android/iOS
 - Package version: 0.0.1-dev2
 - Flutter version: 2.8.1

**Comment by jamesblasco** [comment]
Are you using https callbacks for successUrl and canceledUrl? It is required for webviews.

I will release a new update where I remove http://localhost:8080/#/success and http://localhost:8080/#/cancel and explain that in the docs and the asserts

**Comment by surveshoeb** [comment]
Yeap the callback URL's are the actual URL which is hosted on Firebase Hosting.

 ```
success_url: `${baseURL}:${effectivePort}/order-success-view?transactionId=${transactionID}`,
cancel_url: `${baseURL}:${effectivePort}/order-failed-view`,
```

**Comment by jamesblasco** [comment]
I think I located the problem and fixed it here:

https://github.com/flutter-stripe/flutter_stripe/pull/582

Will let you know when is merged and published

**Comment by jamesblasco** [comment]
Could you try using `0.1.2` fixes your issue?

**Comment by surveshoeb** [comment]
@jamesblasco Still same. Still getting the white screen
`I[/chromium]()(29280): [INFO:CONSOLE(1)] "Unrecognized feature: 'payment'.", source: [https://js.stripe.com/v3/]() (1)`

Suggestion: Add `required` for successUrl, canceledUrl. in `redirectToCheckout` as it's mandatory to pass the value. If I don't pass the value it gives the error.

**Comment by jamesblasco** [comment]
Is the error different than before? 

Regarding `required` for successUrl, canceledUrl. It is not needed for the main target that is web. It contains an assert that force to include successUrl, canceledUrl on platforms using webviews

**Comment by kduvignau** [comment]
@remonh87 same issue here on an Android emulator.
`I/chromium(19985): [INFO:CONSOLE(1)] "Unrecognized feature: 'payment'.", source: https://js.stripe.com/v3/ (1)`

The sessionId is generated from a firebase cloud function : 

```
@override
  Widget build(BuildContext context, WidgetRef ref) {
    return Scaffold(
      body: SafeArea(
        child: TextButton(
          onPressed: () async {
            final callable =
                FirebaseFunctions.instance.httpsCallable('checkout');

            final session = await callable();

            if (session.data['success']) {
              await redirectToCheckout(
                context: context,
                sessionId: session.data['sessionId'],
                publishableKey: publicKey,
                successUrl: 'https://checkout.stripe.dev/success',
                canceledUrl: 'https://checkout.stripe.dev/cancel',
              );
            }
          },
          child: Text('Pay'),
        ),
      ),
    );
  }
```
