### ISSUE TITLE
The pre-build payment UI is not popped up on some Android devices

### ISSUE THREAD

**Issue by Springload-MaxC** [flutter-stripe/flutter_stripe#577]
**Describe the bug**
The pre-build payment UI is not popped up on some Android devices, for example Galaxy S21+ running Android 12, 
Oneplus 8T running Android 11.

**To Reproduce**
1. Retrieve the parameters (customerId, customerEphemeralKeySecret, setupIntentClientSecret) from the server.
2. Call initPaymentSheet() method.
3. Call presentPaymentSheet() method.
3. The UI doesn't pop up and the presentPaymentSheet() method doesn't return any values.

**Expected behavior**
Pop up the pre-build payment UI.

**Smartphone / tablet**
 - Device: Galaxy S21+ running Android 12, Oneplus 8T running Android 11
 - Package version: [2.1.1]
 - Flutter version [2.10.0]

**Additional context**
It works on some other Android devices such as Pixel 6 Android 12, Samsung Galaxy S21 Android 11.

**Comment by remonh87** [comment]
@Springload-MaxC  thanks for reporting.  do you receive any output in the logcat that can be of help?

**Comment by Springload-MaxC** [comment]
@remonh87 Thanks for the quick reply. Here are the output in the logcat when calling presentPaymentSheet() method:

2022-02-10 11:25:59.147 3827-3827/co.againagain.app.staging I/ViewRootImpl@2d90674[MainActivity]: ViewPostIme pointer 0
2022-02-10 11:25:59.197 3827-3827/co.againagain.app.staging I/ViewRootImpl@2d90674[MainActivity]: ViewPostIme pointer 1
2022-02-10 11:26:07.677 3827-3827/co.againagain.app.staging I/ViewRootImpl@2d90674[MainActivity]: ViewPostIme pointer 0
2022-02-10 11:26:07.728 3827-3827/co.againagain.app.staging I/ViewRootImpl@2d90674[MainActivity]: ViewPostIme pointer 1

And there are no error messages in the logcat, it seems the app is stuck in the middle of that function.

**Comment by remonh87** [comment]
@Springload-MaxC  we updated the library yesterday (version 2.2.0) which also consists of upgrades to both iOS and android native sdks. Can you check if this issue still happens?  I struggle to reproduce it, spend some time this weekend to make it fail.  btw can you test our example app on the specific phones? i

**Comment by remonh87** [comment]
assuming the issue to be solved else feel free to reopen it
