### ISSUE TITLE
Cannot show the input text completly in PaymentSheet

### ISSUE THREAD

**Issue by yiukamsum** [flutter-stripe/flutter_stripe#578]
**Describe the bug**
Cannot show the input text completly in cardfield when font size is not default in android system settings.
![image](https://user-images.githubusercontent.com/13889428/153370118-fc1f4767-0641-46e2-a4b2-7d4cdd6df6c6.png)

**To Reproduce**
1. Set the font size to Largest in android settings.
![image](https://user-images.githubusercontent.com/13889428/153368943-27e24a43-9eeb-4e28-8030-481a7fb2dcaa.png)
1. Entering number 4242 4242 4242 4242 into the cardfield.

**Expected behavior**
Expected to show the whole number in the cardfield.

**Smartphone / tablet**
 - Device: Pexel 3a (Emulator)
 - OS: Android 10
 - Package version: 2.1.1
 - Flutter version: 2.8.1

**Comment by remonh87** [comment]
The card field is a native component over which we have little control. I would recommend using the `paymentsheet` for better accessibility features

**Comment by yiukamsum** [comment]
I think we have been using the `paymentsheet` in our code already. Please review our code below. Also, thanks for your quick response.
```dart
await Stripe.instance.applySettings();
await Stripe.instance.initPaymentSheet(
  paymentSheetParameters: SetupPaymentSheetParameters(
  applePay: true,
  googlePay: true,
  style: ThemeMode.light,
  testEnv: true,
  merchantCountryCode: countryName,
  merchantDisplayName: storeName,
  customerId: customerId,
  paymentIntentClientSecret: paymentIntentClientSecret,
  customerEphemeralKeySecret: customerEphemeralKeySecret,
));
try {
  // await Stripe.instance.presentPaymentSheet();
  await Stripe.instance.presentPaymentSheet();

} catch (e) {
  print(e);
}
```

**Comment by remonh87** [comment]
thanks I will check if this happens also on iOS and will create a ticket for the Stripe sdks to solve it.

**Comment by varunbhalerao56** [comment]
@remonh87 I am facing the same issue as well, some of our customers would prefer it to have smaller text. In flutter it is possible to set textScaleFactor:1 but not sure how to apply it here since its native.

**Comment by remonh87** [comment]
this is fixed now also you have more ways of customising the payment sheet yourself.
