### ISSUE TITLE
Klarna

### ISSUE THREAD

**Issue by RobWitteman** [flutter-stripe/flutter_stripe#581]
Hi! How do you add klarna to your flutter app? I do not see klarna in the available PaymentMethodParams

**Comment by remonh87** [comment]
At the moment the underlying Stripe sdk does not support Klarna. I have asked Stripe if it is on their roadmap

**Comment by remonh87** [comment]
got confirmation that it will be implemented in one of the coming releases. It is brand new added to the native sdks. Once the Stripe team has added it to the react native sdk we can use their native bindings and implement it on our side.

**Comment by RobWitteman** [comment]
Thank you for your quick response and the good work you deliver!

**Comment by remonh87** [comment]
update: 2 days ago Stripe launched a new version with Klarna support. We will integrate it in the next version (ETA let's say 2 weeks at most)

**Comment by remonh87** [comment]
fixed in release 2.4.0
