### ISSUE TITLE
CardFieldInputDetails.brand is not consistent with Stripe Card API

### ISSUE THREAD

**Issue by AlexanderFarkas** [flutter-stripe/flutter_stripe#586]
[https://stripe.com/docs/api/cards/object#card_object-brand](API) has 'American Express',
while CardFieldInputDetails.brand is 'AmericanExpress'

**Comment by remonh87** [comment]
you are right but we use the exact mapping as the react native mappers: https://github.com/stripe/stripe-react-native/blob/9b6a184e6bee1ad0ed1ac74422a86be7ffe4f1b6/android/src/main/java/com/reactnativestripesdk/Mappers.kt#L73 . 

you can always create an extension function to name it the way you like :) .
