### ISSUE TITLE
Return PaymentSheetResult instead of void on presentPaymentSheet

### ISSUE THREAD

**Issue by tuxskar** [flutter-stripe/flutter_stripe#588]
The return of the function https://github.com/flutter-stripe/flutter_stripe/blob/main/packages/stripe/lib/src/stripe.dart#L331 should be `PaymentSheetResult` instead of void.

I have an old package that is using this return object and I'm not sure how I should update it but also I think that is an issue on the code, that's why I'm opening the issue.

If you have an alternative to use the PaymentSheet I'll adapt the code accordingly to stop using the package version I have, or how to create a version where it is returning the PaymentSheetResult object instead of void.

Thank you in advance.

**Comment by remonh87** [comment]
`PaymentSheetResult` is a  deprecated object and we now use the result in line with the Stripe SDK: 
In case of success the future completes
In case of failure it will throw an `StripeException`.

Check: https://github.com/flutter-stripe/flutter_stripe/blob/main/example/lib/screens/payment_sheet/payment_sheet_screen.dart for a more concrete implementation
