### ISSUE TITLE
java.lang.IllegalStateException: Reply already submitted

### ISSUE THREAD

**Issue by jigs2707** [flutter-stripe/flutter_stripe#591]
I am using Stripe payment sheet, Sometimes it is working fine  but sometimes getting **java.lang.IllegalStateException: Reply already submitted error,** 

W/System.err(22499): java.lang.IllegalStateException: Reply already submitted
W/System.err(22499): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:431)
W/System.err(22499): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:267)
W/System.err(22499): 	at com.facebook.react.bridge.Promise$1.run(Promise.java:26)
W/System.err(22499): 	at android.os.Handler.handleCallback(Handler.java:883)
W/System.err(22499): 	at android.os.Handler.dispatchMessage(Handler.java:100)
W/System.err(22499): 	at android.os.Looper.loop(Looper.java:230)
W/System.err(22499): 	at android.app.ActivityThread.main(ActivityThread.java:7873)
W/System.err(22499): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(22499): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:526)
W/System.err(22499): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

And also i am using new version flutter_stripe: ^2.2.0

Everything setup properly as requirements .

Here is the flutter doctor output

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.1, on Ubuntu 20.04.3 LTS 5.13.0-28-generic, locale en_IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] Android Studio
[✓] VS Code (version 1.60.2)
[✓] VS Code
[✓] Connected device (3 available)
[✓] HTTP Host Availability

**Comment by jonasbark** [comment]
Can you find out when exactly it happens, as in during which operation or method call?

**Comment by remonh87** [comment]
I got this warning incidentally as well when using the paymentsheet (when executing presentPaymentSheet), however I still am able to show the paymentsheet and handle the payment.

**Comment by remonh87** [comment]
Assuming this issue to be resolved but feel free to reopen it if this is not the case.
