### ISSUE TITLE
Stripe Connect: Client Secret invalid

### ISSUE THREAD

**Issue by alleonhardt** [flutter-stripe/flutter_stripe#595]
When using Stripe Connect and creating the Payment Intent for a connected account on the server the present payment sheet function throws an error complaining that the 'The client_secret provided does not match the client_secret associated with the PaymentIntent'. Is it possible to process payment intents of connected accounts with this software?

**Comment by remonh87** [comment]
I think there is nothing that prevents you from doing it. We build just a dart wrapper around the native sdks,  however I think you should check if you supply the correct client secret to the payment intent. You can check this by comparing the secret in the Stripe dashboard and the one you provide to the app.

**Comment by alleonhardt** [comment]
Thanks a lot for the fast response. The client secrets are the same so I guess that this is not the problem. Based on the documentation of the API it seems that the 'stripeAccount' field is a optional HTTP header which can be included when dealing with connected payment intents. This is based on the explanation here: https://stripe.com/docs/connect/enable-payment-acceptance-guide?platform=web#set-up-stripe-elements . I was just wondering if there is a method to specify this additional setup parameter.

**Comment by remonh87** [comment]
I would suggest to ask Stripe on this matter. We do not have a specific setting for it as well as the native sdks lack it.  I am closing this issue for now but please share how you did (when possible ) solve  it.

**Comment by alleonhardt** [comment]
Thanks again for the answer. It seems to me that it is available in the native sdks. This site shows examples how to use connected accounts client side: https://stripe.com/docs/connect/authentication for Android, iOS, React Native and JS+HTML. If you can point me the location in the code where I can change this I will submit a pull request.
