### ISSUE TITLE
add_payment_method: unable to complete the process of adding payment method due to postalCode

### ISSUE THREAD

**Issue by fernan542** [flutter-stripe/flutter_stripe#599]
**Describe the bug**
Unable to add any payment method if the `CardFormField` widget's property `enablePostalCode` is set to false.
The `controller.details.complete` still validates if the `postalCode` field is not null.

**To Reproduce**
```
import 'dart:developer' as dev;

import 'package:flutter/material.dart';
import 'package:flutter_stripe/flutter_stripe.dart';

class AddPaymentMethodScreen extends StatefulWidget {
  const AddPaymentMethodScreen({Key? key}) : super(key: key);

  @override
  State<AddPaymentMethodScreen> createState() => _AddPaymentMethodScreenState();
}

class _AddPaymentMethodScreenState extends State<AddPaymentMethodScreen> {
  final controller = CardFormEditController();

  @override
  void initState() {
    controller.addListener(update);
    super.initState();
  }

  void update() => setState(() {});

  @override
  void dispose() {
    controller.removeListener(update);
    controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFFEDF7FC),
      appBar: AppBar(
        title: Text(
          "Add New Card",
          style: TextStyle(fontSize: 12.0, color: Colors.black54),
        ),
        leading: IconButton(
            icon: const Icon(Icons.arrow_back, color: Colors.black),
            onPressed: () => Navigator.pop(context)),
        backgroundColor: Colors.white,
        elevation: 2.0,
        centerTitle: true,
      ),
      body: Padding(
        padding: const EdgeInsets.symmetric(horizontal: 16),
        child: Column(
          children: [
            const SizedBox(height: 20),
            CardFormField(
              controller: controller,
              enablePostalCode: false,
              backgroundColor: Colors.white,
            ),
            const SizedBox(height: 20),
            LoadingButton(
              onPressed: () async => await _handleAddNewCard(),
              text: "Add New Card",
            ),
          ],
        ),
      ),
    );
  }

  Future<void> _handleAddNewCard() async {
    if (!controller.details.complete) {
      dev.log("Not complete!");
      return;
    }
    /// Some omitted codes for saving payment method...
          final paymentMethod = await Stripe.instance
          .createPaymentMethod(const PaymentMethodParams.card());
     dev.log("Save payment method.");
  }
}
```

**Expected behavior**
Should be able to add payment method since the `enablePostalCode` field is set to `false`.

**Comment by remonh87** [comment]
@fernan542  thanks for the clear explanation, I am unfortunately  not able to reproduce it on the example app.  Can you print the output of: `controller.details.toJson()` ? I think something is missing there

**Comment by fernan542** [comment]
Thanks for your assistance @remonh87. This is what I got:
```
{complete: false, last4: null, expiryMonth: null, expiryYear: null, postalCode: null, brand: null, number: null, cvc: null, validExpiryDate: Unknown, validCVC: Unknown, validNumber: Unknown}
```

Also another info, I think it only occurs if the selected country is `United States`. Is it required to fill the `postalCode` if the selected country is US?

**Comment by jonasbark** [comment]
Yes, in some countries the postal code is a required field and I think US is amongst it

**Comment by fernan542** [comment]
Oks. Thanks.
So that means that the `enablePostalCode` can be override by the selected country.

What would be the valid reason to force the user to enter their postal code so we can at least put some hint about it? Is it because of tax or something?

**Comment by jonasbark** [comment]
I assume security reasons and anti-fraud detection - feel free to contact Stripe support for further questions.

**Comment by remonh87** [comment]
I asked Stripe support because got curious and this is their response:

"Sorry i don't see any doc/API that tells you if postal code is required for card payment. I'll suggest you to always display the postal code field in CardFiled so that your integration is more universal."

I will add some thing extra to the docs that disabling this setting can yield to incomplete card details.

**Comment by fernan542** [comment]
Many thanks sir @remonh87 for this. 
This issue might be connected: https://github.com/flutter-stripe/flutter_stripe/issues/568

**Comment by remonh87** [comment]
Ha there are also other things are of influences In the dashboard you can block payments if they do not comply with the postal code validation checks. https://stripe.com/docs/radar/rules#traditional-bank-checks. 

And in the payment intent there is a postcode check as well

```json
  "card": {
              "brand": "visa",
              "checks": {
                "address_line1_check": null,
                "address_postal_code_check": null,
                "cvc_check": "pass"
              },

```

So it looks like it is not country related but more Stripe config related. The referred issue looks a bit different since it seems to work on iOS
