### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by mknox10** [flutter-stripe/flutter_stripe#606]
**Describe the bug**
I'm getting this error when launching my app using 'flutter run':

`Note: /home/mknox10/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/device_info-2.0.3/android/src/main/java/io/flutter/plugins/deviceinfo/DeviceInfoPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /home/mknox10/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-2.5.4/android/src/main/java/io/flutter/plugins/firebase/firestore/streamhandler/TransactionStreamHandler.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /home/mknox10/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-1.4.1/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseAuthPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/mknox10/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-10.0.9/android/src/main/java/io/flutter/plugins/firebase/messaging/JobIntentService.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/mknox10/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/libphonenumber-2.0.2/android/src/main/java/com/codeheadlabs/libphonenumber/LibphonenumberPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
e: /home/mknox10/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/stripe_android-2.2.0/android/src/main/kotlin/com/flutter/stripe/StripeAubecsDebitPlatformViewFactory.kt: (13, 1): Class 'StripeAubecsDebitPlatformViewFactory' is not abstract and does not implement abstract base class member public abstract fun create(p0: Context?, p1: Int, p2: Any?): PlatformView defined in io.flutter.plugin.platform.PlatformViewFactory
e: /home/mknox10/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/stripe_android-2.2.0/android/src/main/kotlin/com/flutter/stripe/StripeAubecsDebitPlatformViewFactory.kt: (19, 5): 'create' overrides nothing
e: /home/mknox10/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/stripe_android-2.2.0/android/src/main/kotlin/com/flutter/stripe/StripeSdkCardFormPlatformViewFactory.kt: (13, 1): Class 'StripeSdkCardFormPlatformViewFactory' is not abstract and does not implement abstract base class member public abstract fun create(p0: Context?, p1: Int, p2: Any?): PlatformView defined in io.flutter.plugin.platform.PlatformViewFactory
e: /home/mknox10/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/stripe_android-2.2.0/android/src/main/kotlin/com/flutter/stripe/StripeSdkCardFormPlatformViewFactory.kt: (19, 5): 'create' overrides nothing
e: /home/mknox10/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/stripe_android-2.2.0/android/src/main/kotlin/com/flutter/stripe/StripeSdkCardPlatformViewFactory.kt: (12, 1): Class 'StripeSdkCardPlatformViewFactory' is not abstract and does not implement abstract base class member public abstract fun create(p0: Context?, p1: Int, p2: Any?): PlatformView defined in io.flutter.plugin.platform.PlatformViewFactory
e: /home/mknox10/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/stripe_android-2.2.0/android/src/main/kotlin/com/flutter/stripe/StripeSdkCardPlatformViewFactory.kt: (18, 5): 'create' overrides nothing
e: /home/mknox10/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/stripe_android-2.2.0/android/src/main/kotlin/com/flutter/stripe/StripeSdkGooglePayButtonPlatformViewFactory.kt: (13, 1): Class 'StripeSdkGooglePayButtonPlatformViewFactory' is not abstract and does not implement abstract base class member public abstract fun create(p0: Context?, p1: Int, p2: Any?): PlatformView defined in io.flutter.plugin.platform.PlatformViewFactory
e: /home/mknox10/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/stripe_android-2.2.0/android/src/main/kotlin/com/flutter/stripe/StripeSdkGooglePayButtonPlatformViewFactory.kt: (19, 5): 'create' overrides nothing 

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':stripe_android:compileDebugKotlin'.
> Compilation error. See log for more details`

**To Reproduce**
Run 'flutter run' from cmd line when 'flutter_stripe: ^2.2.0' is in pubspec.yaml file

**Smartphone / tablet**
 - OS: [Android]
 - Package version: [e.g. 2.2.0]
 - Flutter version [e.g. 2.11.0.0.pre.713]

**Additional context**
Updated from stripe_payment yesterday (2/27) and it worked fine. But as of today (2/28) it does not.

*** build.gradle info ***
ext.kotlin_version = 1.6.10
compileSdkVersion 31

**Comment by remonh87** [comment]
can you try to run `flutter clean` and `flutter pub get`?  In general this should fix most issue likes this.

**Comment by mknox10** [comment]
'flutter clean' and 'flutter pub get' did not work. I also tried deleting the pubspec.lock file after running 'flutter clean'  but that did not work either.

**Comment by jonasbark** [comment]
Try running `flutter packages pub upgrade stripe_android`

**Comment by mknox10** [comment]
Still getting the same error after running 'flutter packages pub upgrade flutter_stripe'. Also tried 'flutter pub upgrade --major-versions' which did not work either.

**Comment by remonh87** [comment]
what is the output of `flutter doctor` and which Gradle version are you using?

**Comment by mknox10** [comment]
flutter doctor output:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 2.11.0-0.0.pre.713, on Ubuntu 20.04.4 LTS 5.13.0-28-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code
[✓] Connected device (2 available)
[✓] HTTP Host Availability

I believe I'm using gradle version 6.7 which I see in the gradle-wrapper.properties file: distributionUrl=https\://services.gradle.org/distributions/gradle-6.7-all.zip

**Comment by remonh87** [comment]
Can you open the android folder of your app in Android studio and try building it from there? I just created a project from scratch and add no issues compiling it. However I see you are using a brand new flutter version. Also Can you try to switch to the flutter channel stable?

**Comment by mknox10** [comment]
Switching to flutter channel stable fixed my problems. @remonh87 Thank you!

**Comment by nerder** [comment]
We are having the same issue using `beta`

```
➜ flutter doctor -v
[✓] Flutter (Channel beta, 2.12.0-4.1.pre, on macOS 11.6.2 20G314 darwin-x64, locale en-ES)
    • Flutter version 2.12.0-4.1.pre at /Users/nerder/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 680962aa75 (7 days ago), 2022-03-16 13:46:03 -0700
    • Engine revision e9f57b5d0f
    • Dart version 2.17.0 (build 2.17.0-182.1.beta)
    • DevTools version 2.11.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/nerder/Library/Android/sdk
    • Platform android-31, build-tools 30.0.2
    • ANDROID_SDK_ROOT = /Users/nerder/Library/Android/sdk
    • Java binary at: /Users/nerder/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7935034/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/nerder/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7935034/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/nerder/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7784292/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3)
    • IntelliJ at /Users/nerder/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 63.2.4
    • Dart plugin version 213.5744.122

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3)
    • IntelliJ at /Users/nerder/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/213.5744.223/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.3)
    • IntelliJ at /Users/nerder/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/212.5457.46/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (3 available)
    • SM G975F (mobile) • R58M67B0S3Y • android-arm64  • Android 12 (API 31)
    • macOS (desktop)   • macos       • darwin-x64     • macOS 11.6.2 20G314 darwin-x64
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 99.0.4844.83

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by mizzb** [comment]
I am facing the same issue
