### ISSUE TITLE
Unsupported platforms

### ISSUE THREAD

**Issue by noahzig** [flutter-stripe/flutter_stripe#611]
Hi,

The supported platforms for this plugin are listed as Android, iOS, Linux, MacOS, and Windows.

This plugin does not support MacOS, and though I haven't checked, I suspect it doesn't support Linux or Windows either.

Is there any plan in place to support desktop platforms?

Thanks,
Noah

**Comment by LukasVitek** [comment]
![image](https://user-images.githubusercontent.com/9765987/162927384-ac29c9a9-e729-4500-8880-fb866f67dccd.png)

It's really confusing. I tried to implement stripe into Linux desktop app and it didn't work (according to description, desktp support is integrated).

I would welcome destop support.
