### ISSUE TITLE
How use stored card informations and auto complete paymentsheet fields

### ISSUE THREAD

**Issue by federico2390** [flutter-stripe/flutter_stripe#613]
How use stored card informations and auto complete paymentsheet fields?

**Comment by remonh87** [comment]
I recommend to follow the instructions here: https://docs.page/flutter-stripe/flutter_stripe/sheet

**Comment by federico2390** [comment]
> I recommend to follow the instructions here: https://docs.page/flutter-stripe/flutter_stripe/sheet
> 
> 

I already followed this guide, but nothing... paymentsheet show always empty fields. In which point of this guide i need to see better?
