### ISSUE TITLE
[BUG] Apple Pay keep asking to address be filled

### ISSUE THREAD

**Issue by Rioverde** [flutter-stripe/flutter_stripe#615]
Flutter 2.10
Stripe on IOS by Apple Pay keep asking User Billing Address, while on other aps Apple Pay works without it.

 await stripe.Stripe.instance.presentApplePay(
            stripe.ApplePayPresentParams(
              cartItems: [
                stripe.ApplePayCartSummaryItem(
                  label: 'xxxxx,
                  amount: total.toString(),
                ),
              ],
              country: 'xxxxx',
              currency: Environment.currency,
            ),
          );

Ssory for the bad screenshot, cannot create this case on emulator
On device it says 'Billing address is incorrect'
<img width="375" alt="Screenshot 2022-03-05 at 12 18 15 PM" src="https://user-images.githubusercontent.com/35552367/156871754-c74af2e8-aa2e-466d-975b-76d9481adaf4.png">

**Comment by jonasbark** [comment]
Hi! I recommend talking to the Stripe support on this issue - it's very likely that this is unrelated to the flutter plugin

**Comment by Rioverde** [comment]
@jonasbark thanks

**Comment by remonh87** [comment]
@Rioverde  I had this issue in the past as well and it is related to the configuration of the wallet on your phone. You can change it here:

Go to settings>Wallet & Apple Pay>transaction defaults>address
Go to Wallet app>tap on any card>tap three dots in corner>tap address 

What is curious is that in your code there is no billing address required so it should not complain in my opinion. Can you remove the billing address and try to pay?
