### ISSUE TITLE
How  use server for production

### ISSUE THREAD

**Issue by federico2390** [flutter-stripe/flutter_stripe#618]
Hi I dont have understand where put the server folder if i want to use it for production and how call the server file from flutter when I init the checkout... can someone explain me please?

**Comment by remonh87** [comment]
@federico2390  we use an example backend server that is standalone from the app. The only thing our SDK does is collecting payment information from the client. Server side is responsible for communicating with Stripe (e.g. through an API). I think this page https://docs.page/flutter-stripe/flutter_stripe/sheet is very helpful and provides specific links to the Stripe docs.

**Comment by federico2390** [comment]
@remonh87 ok but if i put the folder server online, i just need to cAll it with (for example) http plugin?

**Comment by remonh87** [comment]
yes you need to host the serve somewhere but keep in mind that it is a server pure designed as an example and I would be very cautious using it in a production system

**Comment by federico2390** [comment]
> yes you need to host the serve somewhere but keep in mind that it is a server pure designed as an example and I would be very cautious using it in a production system

Yes yes, i know that.
I want to know just for testing...

**Comment by hadi-14** [comment]
Where can I get it hosted for free and how?
