### ISSUE TITLE
Flutter autofillHints support

### ISSUE THREAD

**Issue by brokenicedeveloper** [flutter-stripe/flutter_stripe#620]
Hi, I searched a bit but I couldn't find anything.. I need the Flutter autofilHints support on CardField widget.
Expected behaviour: the system recognizes the card field type and display to the user the saved cards on his/her account.
Actual behaviour: the user has to manually fill the card field.

Thanks in advance!

**Comment by SasLuca** [comment]
Seems like this was already added in Android (see issue: https://github.com/stripe/stripe-android/pull/963, commit: https://github.com/stripe/stripe-android/commit/f8af3ec99472443cfd67f8720e4f7d222ec2fc77) but in Flutter when I used CardField I don't get that behavior still.

Anything extra I should be doing on the flutter side?

**Comment by jonasbark** [comment]
Check out the comment here: https://github.com/stripe/stripe-react-native/blob/master/android/src/main/java/com/reactnativestripesdk/CardFormView.kt#L48
This should be the reason why it's not available, yet

**Comment by SasLuca** [comment]
So it is because the ios-sdk does not have this feature as well?
Is there a reason why it couldn't be enabled just for android even if ios lacks it? Seems unfortunate to gatekeep this feature on android for this reason, unless I am misunderstanding.

**Comment by jonasbark** [comment]
No, I agree with you. Feel free to add your feedback to this issue: https://github.com/stripe/stripe-react-native/issues/563
