### ISSUE TITLE
how to connect google pay and apple pay  with  (flutter_stripe 2.3.0) ???? anyone?

### ISSUE THREAD

**Issue by Atiqrehman3054** [flutter-stripe/flutter_stripe#621]
**Describe the bug**

**To Reproduce**
1. Entering number 123-456-789 into the cardfield.
2. Tapping the confirm button.
3. Observe a failure with exception (including the part of the stack trace, belonging to this package) …

**Expected behavior**

**Smartphone / tablet**
 - Device: [e.g. iPhone X]
 - OS: [e.g. iOS 13, Android 10]
 - Package version: [e.g. 1.0.0]
 - Flutter version [e.g. 2.0.0.]

**Additional context**

**Comment by jonasbark** [comment]
Please provide a proper description of what information you need. The examples themselves should be good guidance here.

**Comment by Atiqrehman3054** [comment]
Hi sir nice to meet you so the issue is we are not finding any compatible package for apple pay and google pay via stripe. We want to integrate google pay and apple pay via stripe in our flutter app kindly guide us about this how can we do this integration.

**Comment by remonh87** [comment]
I recommend checking out: https://github.com/flutter-stripe/flutter_stripe/blob/main/example/lib/screens/wallets/apple_pay_screen.dart

https://github.com/flutter-stripe/flutter_stripe/blob/main/example/lib/screens/wallets/google_pay_stripe_screen.dart

and also check the official docs:https://stripe.com/docs/apple-pay?platform=ios

**Comment by Atiqrehman3054** [comment]
Awesome, thank you Sir.

**Comment by Atiqrehman3054** [comment]
Hi sir nice to meet you so the issue is we are not finding any compatible
package for apple pay and google pay via stripe. We want to integrate
google pay and apple pay via stripe in our flutter app kindly guide us
about this how can we do this integration.
