### ISSUE TITLE
Access to XMLHttpRequest has been blocked by CORS Stripe Flutter web

### ISSUE THREAD

**Issue by hiteshsapra** [flutter-stripe/flutter_stripe#623]
**Describe the bug**
Hello team.

Any one help me the below CORS policy issue in flutter web Stripe. We are using below the plugging for our project.

stripe_checkout: ^0.1.2

**To Reproduce**
1) implement Stripe Flutter web
2) Click on Payment button >> Here getting error
3) Android iOS working fine Flutter web getting error

**doctor --verbose**
[✓] Flutter (Channel stable, 2.10.0, on macOS 11.6 20G165 darwin-x64, locale en-GB)
• Flutter version 2.10.0 at /Users/baps/Documents/flutter
• Upstream repository https://github.com/flutter/flutter.git
• Framework revision https://github.com/flutter/flutter/commit/5f105a6ca7a5ac7b8bc9b241f4c2d86f4188cf5c (4 weeks ago), 2022-02-01 14:15:42 -0800
• Engine revision 776efd2034
• Dart version 2.16.0
• DevTools version 2.9.2

**Comment by jonasbark** [comment]
You will need to adjust the CORS handling server-side or at your cloud provider. The question is out of the scope of this plugin.
