### ISSUE TITLE
[flutter web] Dart version must at least 2.14

### ISSUE THREAD

**Issue by ayu8899** [flutter-stripe/flutter_stripe#630]
flutter_stripe_web minimum dart sdk  is 2.12, however when include flutter_stripe_web in pubspec.yaml, encountered following issue that actually required at least dart version 2.14

"_Because every version of flutter_stripe_web depends on freezed_annotation >=0.15.0 which requires SDK version >=2.14.0 <3.0.0, flutter_stripe_web is forbidden._"

@remonh87 , I am currently in dart 2.12,  flutter_stripe working fine in both android and IOS. when wanna do for web, i have the above issue, how to rectify this or need to upgrade to 2.14?

**Comment by remonh87** [comment]
This has nothing to do with our library but the fact freezed introduced a 2.14 constrained in their package: [link](https://github.com/rrousselGit/freezed/blob/master/packages/freezed_annotation/pubspec.yaml). I would personally recommend to upgrade to a new version of Flutter.
