### ISSUE TITLE
ideal not showing in paymentsheet

### ISSUE THREAD

**Issue by ayushin** [flutter-stripe/flutter_stripe#632]
It seems that #433 and #609 are related - the PaymentSheet won't show IDEAL in case returnUrl is not set.

I believe initPaymentSheet should take returnURL as well in order to support ideal?

**Comment by ayushin** [comment]
This fixes it:

https://github.com/flutter-stripe/flutter_stripe/pull/633

**Comment by remonh87** [comment]
I think I tested it only for Android and it looks like iOS needs a return url. We will ship this fix in the next version.

**Comment by ayushin** [comment]
this works for me on ios

**Comment by remonh87** [comment]
Shpped as part of  v 2.4.0
