### ISSUE TITLE
question: payment sheet support for web?

### ISSUE THREAD

**Issue by ayushin** [flutter-stripe/flutter_stripe#634]
Will this ever be supported in flutter_stripe_web?

**Comment by remonh87** [comment]
For the web we recommend using checkout which is in line with the official [stripe docs](https://stripe.com/docs/payments/accept-a-payment) . We have also a working checkout screen in our example app that you can use for reference. 

I do not think there will be a paymentsheet for the web but if Stripe will add it we will do the same.
