### ISSUE TITLE
Default payment setup shows "Pay" rather than "Setup" for Apple Pay or Google Pay

### ISSUE THREAD

**Issue by sowsan** [flutter-stripe/flutter_stripe#636]
Hello - 

We have implemented the option to users save their payment option for future usage. When we use a credit card, the plugin UI shows as "Set up", but when we use Apple Pay/ Google pay. This UI button is confusing as the user is not really paying anything at this point.

Credit Card
![IMG_0988](https://user-images.githubusercontent.com/11544153/158069686-e0d15e0c-839b-4b88-93de-2205629ff236.PNG)

Apple Pay
![IMG_0987](https://user-images.githubusercontent.com/11544153/158069684-29b3a2ac-0ef4-4f4d-a549-54717a1caa5b.PNG)

Thanks for your help!

**Comment by jonasbark** [comment]
Good point - I agree. Unfortunately, the UI in the payment sheet is out of the control of this plugin.

I suggest opening up a ticket at https://github.com/stripe/stripe-ios and we'll ensure the change will also be part of flutter_stripe.
