### ISSUE TITLE
Apple Pay payment with Stripe not processing

### ISSUE THREAD

**Issue by stocker88** [flutter-stripe/flutter_stripe#640]
I am trying to process an Apple Pay payment in Stripe, but I get the following error   'There was an unexpected error -- try again in a few seconds' when createApplePayToken is called.
      
I pulled the code from https://github.com/flutter-stripe/flutter_stripe/blob/2ae832a6b25b331616f6344efbe19d5c982cd89e/example/lib/screens/wallets/apple_pay_screen_plugin.dart#L74

I am using google pay package and passing the Apple Pay payment result in onApplePayResult

```
Future<void> onApplePayResult(paymentResult) async {
    try {
      //debugPrint(paymentResult.toString());
      // 1. Get Stripe token from payment result
      final token = await Stripe.instance.createApplePayToken(paymentResult);
      print(token.id);
      // 2. fetch Intent Client Secret from backend
      final params = PaymentMethodParams.cardFromToken(token: token.id);
      final response = await fetchPaymentIntentClientSecret('','','');
      final clientSecret = response['clientSecret'];
      // 3. Confirm Google pay payment method
      await Stripe.instance.confirmPayment(clientSecret, params);

      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
            content: Text('Apple Pay payment succesfully completed')),
      );
    } catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Error: $e')),
      );
    }
  }
```

**Comment by remonh87** [comment]
Did you follow the instructions as described in : https://stripe.com/docs/apple-pay?platform=react-native ? Especially on the iOS developer side there are some things you need to do (e.g. add a merchantID.

**Comment by stocker88** [comment]
yes, I have also revoked the old merchant id / certificate and did it again to make sure there is no bad caching happening

**Comment by stocker88** [comment]
I've tried again it looks like its working. I am guessing deleting and recreating the certificate made the difference...

However now I am having an issue with final url = Uri.parse('$kApiUrl/create-payment-intent');

Any idea what should kApiUrl be? Thanks!

**Comment by remonh87** [comment]
the kAPiUrl is the endpoint for your backend. Stripe works the following: your backend communicates with Stripe (e.g. creating payment intent and retrieving the success through a Webhook (there are also other ways) . The client is mainly user for collecting the data needed to complete the payment.

**Comment by Aarush-Acharya** [comment]
Hey @remonh87 it still does not work for me and gives the same error on stripe logs
