### ISSUE TITLE
stripe is not working in android 12 

### ISSUE THREAD

**Issue by pranavo72bex** [flutter-stripe/flutter_stripe#647]
**Describe the bug**
stripe is working perfectly fine in android 11 but not working in the android 12 emulator 

```
E/flutter ( 5802): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(flutter_stripe initialization failed, The plugin failed to initialize:
E/flutter ( 5802): Your theme isn't set to use Theme.AppCompat or Theme.MaterialComponents.
E/flutter ( 5802): Please make sure you follow all the steps detailed inside the README: https://github.com/flutter-stripe/flutter_stripe#android
E/flutter ( 5802): If you continue to have trouble, follow this discussion to get some support https://github.com/flutter-stripe/flutter_stripe/discussions/538, null, null)
```

**Smartphone / tablet**
 - Device: Pixel 2 emulator
 - OS:  Android 12
 - Package version:  flutter_stripe: ^2.0.1
 - Flutter version 2.10.3

**Comment by pranavo72bex** [comment]
> did you follow https://github.com/flutter-stripe/flutter_stripe#android ?
> 
> Also check you use the correct compile sdk and that you have updated all the styles.
> 
> You can also run our example app which works fine on Android 12.

My code works fine on android 11 devices but couldn't launch in android  12 due to strip ..if I miss any step then it wouldn't run on android 11 too .

**Comment by remonh87** [comment]
but google sometimes tend to add extra config to new android sdks. I would advice to try to run our example app on android12 because for me the example app and 2 customer projects work without issues on android 12. 

Also if you can give us a repro app we would be willing to help out

**Comment by pranavo72bex** [comment]
I follow the guide https://github.com/flutter-stripe/flutter_stripe/pull/575/commits/169a697c350f2f24a6ece59201031ec24d4a34cf
 but it wouldn't work for me ..can you explain to me why you use `mavenCentral()` instead of ` jcenter()` ..increasing kotline version is necessary?

**Comment by remonh87** [comment]
The Kotlin version is the advised version of the android gradle plugin that we use.  Also JCenter stopped working one year ago that's why we needed this repo for the library.

The issue is not related to a corrupt gradle cache and has nothing to do with our library. I would recommend to clean and rebuild your project + remove that partial aar file located at: `/home/pranav/.gradle/caches/transforms-3/26367cb12d3c0f0337fbe6cc4c860cc3/transformed/jetified-transport-api-3.0.0.aar.`

**Comment by pranavo72bex** [comment]
on android 11 it is throwing the same error https://github.com/defold/extension-facebook/issues/40

**Comment by pranavo72bex** [comment]
it didn't work for me

**Comment by pranavo72bex** [comment]
Finally it work . I have to update values-v31/styles.xml file too
