### ISSUE TITLE
Keyboard is not opened when interacting with the fields in stripe's web

### ISSUE THREAD

**Issue by nadpescador** [flutter-stripe/flutter_stripe#650]
Keyboard is not opened when interacting with the fields in stripe's web, as you can see here:
<img width="242" alt="image" src="https://user-images.githubusercontent.com/49540309/159731245-1688572a-9e43-4dc2-9ed4-79173c711cd3.png">

It's happening in the social security number field.
This happens only in some android devices, such as android 12.

**To Reproduce**
1. Get to this step 
2. Tap the field.
4. Observe a failure in the field that won't open the keyboard

**Expected behavior**
The keyboard should show up after tapping the textfield.

**Smartphone / tablet**
 - Device: Samsung 12
 - OS: Lastest OS
 - Package version: Stripe 2.3.0
 - Flutter version 2.10.2

**Additional context**
So the issue is that you can't complete and the signup can't be done entirely.

**Comment by remonh87** [comment]
can you explain me which widget you are using, Checkout?

**Comment by nadpescador** [comment]
> can you explain me which widget you are using, Checkout?
Currently it's a Web View that shows a Url

**Comment by remonh87** [comment]
I think that is an issue of the WebView plugin if you are not using a build in Stripe widget (e.g. paymentsheet, checkout etc). I am not sure I can do anything about this.  Can you try it without WebView but using `url_launcher` so we are sure it is using the native browser?

**Comment by nadpescador** [comment]
I will look into it as soon as possible and give feedback, thanks.
