### ISSUE TITLE
Is there a way to save a credit card for future purchases without making any payments?

### ISSUE THREAD

**Issue by javitrujillo99** [flutter-stripe/flutter_stripe#653]
I have seen that this package has some support for saving cards for future purchases but all the ways I have saw are while you are making a payment. I want an option in my app for saving credit cards in Stripe.

How can I save cards and then use them for the payments?

**Comment by remonh87** [comment]
Yes you can follow the: https://stripe.com/docs/payments/save-and-reuse?platform=react-native&ui=payment-sheet#react-native-collect-payment-details .

And make sure you use a `setupIntentClientSecret` in the paymentsheet.  If you are not using the paymentsheet (which is the easies integration). you can also check: https://github.com/flutter-stripe/flutter_stripe/blob/main/example/lib/screens/others/setup_future_payment_screen.dart . Hope this helps
