### ISSUE TITLE
stripe_checkout android show a white screen

### ISSUE THREAD

**Issue by jaumard** [flutter-stripe/flutter_stripe#657]
**Describe the bug**
Hello, I'm using only stripe_checkout 0.1.2 for Android and Web platforms, no issue on the web so far, but on Android it doesn't work.

It just shows a white screen and nothing happened.  

Here is what I do:

```
final sessionId = await store.getPaymentSessionId(e);
final result = await redirectToCheckout(
  context: context,
  sessionId: sessionId,
  publishableKey: kIsProductionMode ? kStripeProdKey : kStripeTestKey,
  successUrl: Config().baseUrl + '/${DonateSuccess.name}',
  canceledUrl: Config().baseUrl + '/${DonateCancelled.name}',
);
```

**Additional context**
Here is a video of the issue:

https://user-images.githubusercontent.com/2970449/160276021-8883eab1-2a35-4fe0-909c-e027fff65e8c.mov

No sure what I have to do more to have it working on Android. Please let me know.

**Comment by jaumard** [comment]
So I manage to make it work by moving the `redirectToCheckout ` elsewhere in my code, so my bad, but I got another issue I'll open another issue for that

**Comment by kduvignau** [comment]
@jaumard How did you fix your problem? I also have a white screen on Android, see => https://github.com/flutter-stripe/flutter_stripe/issues/683
