### ISSUE TITLE
ERROR:: AAPT: error: resource android:style/Theme.AppCompat.Light.NoActionBar not found.

### ISSUE THREAD

**Issue by samaliftech** [flutter-stripe/flutter_stripe#662]
**Describe the bug**

Payment Window not come out and this error comes out:

I/flutter (28572): exceptionPlatformException(flutter_stripe initialization failed, The plugin failed to initialize:
I/flutter (28572): Your theme isn't set to use Theme.AppCompat or Theme.MaterialComponents.
I/flutter (28572): Please make sure you follow all the steps detailed inside the README: https://github.com/flutter-stripe/flutter_stripe#android
I/flutter (28572): If you continue to have trouble, follow this discussion to get some support https://github.com/flutter-stripe/flutter_stripe/discussions/538, null, null)

but after changed the theme, this error come:

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     ERROR:: AAPT: error: resource android:style/Theme.AppCompat.Light.NoActionBar not found.
     error: resource android:style/Theme.AppCompat.Light.NoActionBar not found.
     error: resource android:style/Theme.MaterialComponents not found.
     error: resource android:style/Theme.MaterialComponents not found.
     error: failed linking references.

**Expected behavior**
Payment window/insert card info window come out.

**Smartphone / tablet**
 - Device: Redmi Note 5 Pro
 - OS: Android 10
 - Package version: latest
 - Flutter version 2.12.0

**Additional context**

**Comment by remonh87** [comment]
I think this has to do with some invalid caches on Android studio try file -> invalidates caches and restart

If you do not use android studio run `flutter clean` and try it again
