### ISSUE TITLE
Stripe payments throwing  hooks.stripe web middleware

### ISSUE THREAD

**Issue by aashayapps** [flutter-stripe/flutter_stripe#663]
**Describe the bug**
Every time I do stripe payments the plugin sends me to the browser for some time then navigates back to the application . How can I avoid this behavior?

**Expected behavior**
Payments should be seamless and on the same app instead of taking the user to the web for any kind of confirmations.

**Smartphone / tablet**
 - Device: Samsung Galaxy S20 FE, Pixel 2XL emulator
 - OS: Android 12

**Additional context**
Please checkout the video
https://user-images.githubusercontent.com/96315874/161415953-64cb5f71-7b1c-46a9-b318-20cedfd33d76.mp4

**Comment by jonasbark** [comment]
Hi! 
This is part of Stripe 3DS security measurements - they basically redirect (in some cases) to the verification pages of certain bank account providers. 
Read more about it here:
https://stripe.com/docs/payments/3d-secure

It's nothing we or you could change here, thus closing the issue.

**Comment by adnan-nazir** [comment]
@jonasbark Its working fine for me 3DS cards. Displaying a popup on web and webview on the mobile. I have not provided the return_url but it's returning me back to My App/website. 
**Question is: Do I need to provide return_url OR is there any chance it will take me outside the app and move to another app/website and will return in my app using return_url?**
