### ISSUE TITLE
Your card was declined

### ISSUE THREAD

**Issue by heshesh2010** [flutter-stripe/flutter_stripe#665]
Hi , 

i'm using latest verision :   flutter_stripe: ^2.4.0

i'm tested the example app and hit 

i got error : 

[log] StripeException(error: LocalizedErrorMessage(code: FailureCode.Failed, localizedMessage: Your card was declined, message: Your card was declined, stripeErrorCode: null, declineCode: null, type: null))
      StripeException(error: LocalizedErrorMessage(code: FailureCode.Failed, localizedMessage: Your card was declined, message: Your c...
      #0      ResultParser.parse (package:stripe_platform_interface/src/result_parser.dart:16:7)
      #1      MethodChannelStripe.createPaymentMethod (package:stripe_platform_interface/src/method_channel_stripe.dart:69:10)
      <asynchronous suspension>
      #2      Stripe.createPaymentMethod (package:flutter_stripe/src/stripe.dart:149:29)
      <asynchronous suspension>
      #3      _NoWebhookPaymentScreenState._handlePayPress (package:stripe_example/screens/card_payments/no_webhook_payment_screen.dart:105:11)
      <asynchronous suspension>
      #4      _LoadingButtonState._loadFuture (package:stripe_example/widgets/loading_button.dart:50:7)
      <asynchronous suspension>

screen shots : 
https://share.getcloudapp.com/wbuz8rJn

flutter doctor ;

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.3.1 21E258 darwin-x64, locale en-EG)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] Connected device (2 available)
    ! Error: iPhone 6s Plus is not connected. Xcode will continue when iPhone 6s Plus is connected. (code -13)
[✓] HTTP Host Availability

• No issues found!

**Comment by remonh87** [comment]
This is a message related coming from  Stripe SDK.  It means the card that you entered is a card that is not valid for some reason. I would recommend trying one of the test cards: e.g. `4242 4242 4242 4242`.  If the card is not declined I would recommend to contact Stripe support and they can help you with this.
