### ISSUE TITLE
Web - Klarna

### ISSUE THREAD

**Issue by deepthi-bhattachar** [flutter-stripe/flutter_stripe#667]
```
var  paymentMethodParams = PaymentMethodParams.klarna(billingDetails: billingDetails);
await Stripe.instance.confirmPayment(
          _bloc.payment_intent, paymentMethodParams,
        ).then((paymentIntent) =>
        ({
          if(paymentIntent.status == PaymentIntentsStatus.Succeeded){
            navigator.popBack(context: context),
            _bloc.paymentStatus = PaymentStatusTag.success,
            applicationBloc.dispatchEvent(PaymentSuccessEvent()),
            _bloc.dispatchEvent(OnPayPaymentCompleteEvent(_bloc.order_id)),
          } else {
              navigator.popBack(context: context),
              _bloc.paymentStatus = PaymentStatusTag.failed, setState(() {
              _bloc.paymentCompleted = true;
            })
            }
        })).catchError((error) => {
          if (error != null){
            navigator.popBack(context: context),
            _bloc.paymentStatus = PaymentStatusTag.failed,
            setState(() {
              _bloc.paymentCompleted = true;
            }),
          }
        });
```

**Describe the bug**
I am trying to integrate Klarna into my project. Klarna works fine on iOS, but on the Web I do not get a Klarna related web page.
SDK version:
flutter_stripe: ^2.4.0
flutter_stripe_web: ^0.1.3

I have added below like in index.html
<script src="https://js.stripe.com/v3/"></script>

**To Reproduce**
1. Implement Klarna as per example code provided by flutter_stripe

**Expected behavior**
Klarna web page should open up, so that users can input required fields in the Flutter web project.

**Smartphone / tablet**
 - Chrome browser

**Additional context**

**Comment by remonh87** [comment]
We discussed among ourselves and we decided to go for a very light weight version of the web.  I would recommend to look for checkout since that is the most smooth experience on the web.

**Comment by deepthi-bhattachar** [comment]
Thank you.
