### ISSUE TITLE
Misconfigured example AndroidManifest.xml causes GooglePay unavailable (fix inside)

### ISSUE THREAD

**Issue by pdivita** [flutter-stripe/flutter_stripe#668]
I'm trying to enable GooglePay payments in my flutter app, following the [official plugin example](https://github.com/flutter-stripe/flutter_stripe/tree/main/example).
Reading the [AndroidMainfest.xml](https://github.com/flutter-stripe/flutter_stripe/blob/main/example/android/app/src/main/AndroidManifest.xml) file, the meta-data tag that enable Google Pay 
```
<meta-data
    android:name="com.google.android.gms.wallet.api.enabled"
    android:value="true" />
```
is located inside the `activity` tag.

This (at least for me) is not working, as calling `Stripe.instance.isGooglePaySupported(IsGooglePaySupportedParams())` returns `false`.

Moving that block upper in the tree (that is inisde the `application` tag) and building again, fixed the issue.

Just to be clear I found that also the [official google-pay AndroidManifest.xml](https://github.com/google-pay/flutter-plugin/blob/main/pay_android/android/src/main/AndroidManifest.xml) put the metadata inside the application tag.

My suggestion is to update the example file and the homepage documentation.

Tested and working on my Xiaomi Mi Lite 5g with Android 11 and Emulator with Android 12.

Hope it helps

**Comment by remonh87** [comment]
Thanks will fix this 👍  . Also I will spend some time coming weeks in adding a bit more documentation for this part.

**Comment by canciloglu** [comment]
I can confirm this causes the issue, and suggested change fixes it.

**Comment by ShwetaChauhan18** [comment]
I am facing same issue
