### ISSUE TITLE
exception:PlatformException(flutter_stripe initialization failed, The plugin failed to initialize:

### ISSUE THREAD

**Issue by Zasaz** [flutter-stripe/flutter_stripe#670]
**Hello, i am facing this issue and i have done everything according to the documentation provided by the "flutter_stripe" on github.** 

//************************************************
**This is the issue that i face:**

I/flutter ( 4010): exception:PlatformException(flutter_stripe initialization failed, The plugin failed to initialize:
I/flutter ( 4010): Your Main Activity class com.app.chasescroll_flutter.MainActivity is not a subclass FlutterFragmentActivity.
I/flutter ( 4010): Please make sure you follow all the steps detailed inside the README: https://github.com/flutter-stripe/flutter_stripe#android
I/flutter ( 4010): If you continue to have trouble, follow this discussion to get some support https://github.com/flutter-stripe/flutter_stripe/discussions/538, null, null)#0      JSONMet
hodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:155:7)
I/flutter ( 4010): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:177:18)
I/flutter ( 4010): <asynchronous suspension>
I/flutter ( 4010): #2      MethodChannelStripe.initialise (package:stripe_platform_interface/src/method_channel_stripe.dart:43:5)
I/flutter ( 4010): <asynchronous suspension>
I/flutter ( 4010): #3      Stripe._initialise (package:flutter_stripe/src/stripe.dart:415:5)
I/flutter ( 4010): <asynchronous suspension>
I/flutter ( 4010): #4      Stripe.initPaymentSheet (package:flutter_stripe/src/stripe.dart:318:5)
I/flutter ( 4010): <

//************************************************

**This is my Manifest file:**

//************************************************
//************************************************

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.app.chasescroll_flutter"
    xmlns:tools="http://schemas.android.com/tools">
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-feature android:name="android.hardware.location.network" android:required="false" />
    <uses-feature android:name="android.hardware.location.gps" android:required="false"  />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE"/>
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_CONTACTS" />
    <uses-permission android:name="android.permission.WRITE_CONTACTS" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />

    <application
        tools:replace="android:label"
        android:usesCleartextTraffic="true"
        android:label="chasescroll_flutter"
        android:icon="@mipmap/ic_launcher"
        >
        

        <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id"/>
        <meta-data android:name="com.facebook.sdk.ClientToken" android:value="@string/facebook_client_token"/>

        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
            <intent-filter>
                <action android:name="FLUTTER_NOTIFICATION_CLICK" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                <data android:host="chasescroll.page/link" android:scheme="http"/>
                <data android:host="chasescroll.page/link" android:scheme="https"/>
            </intent-filter>
        </activity>
        <activity android:name="com.facebook.FacebookActivity"
            android:configChanges=
                "keyboard|keyboardHidden|screenLayout|screenSize|orientation"
            android:label="@string/app_name" />
        <activity
            android:name="com.facebook.CustomTabActivity"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="@string/fb_login_protocol_scheme" />
            </intent-filter>
        </activity>
        
        <activity
            android:name="com.aboutyou.dart_packages.sign_in_with_apple.SignInWithAppleCallback"
            android:exported="true"
            >
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data android:scheme="signinwithapple" />
                <data android:path="callback" />
            </intent-filter>
        </activity>
        <provider
            android:name="androidx.core.content.FileProvider"
            android:authorities="${applicationId}.fileProvider"
            android:exported="false"
            android:grantUriPermissions="true"
            tools:replace="android:authorities">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/filepaths"
                tools:replace="android:resource" />
        </provider>
        
        <meta-data
            android:name="flutterEmbedding"
            android:value="2"
            />
        
    </application>
</manifest>

//************************************************
//************************************************

**This is my MainActivity.kt file:**

package com.app.chasescroll_flutter

import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.android.FlutterFragmentActivity

class MainActivity: FlutterFragmentActivity() {
}

//************************************************
//************************************************

I have also changed my build.gradle/app and changed the kotlin version to 1.5.10 and upgraded my minSdkVersion to 21. I am astuck on this issue from 3 days and couldn't find any helping material from github/issues. Kindly guide me if there's any way to solve this. Thanks

**Comment by jonasbark** [comment]
Please continue here: https://github.com/flutter-stripe/flutter_stripe/discussions/538

It's possible that the `android:name=".MainActivity"` part does not point to the correct class
