### ISSUE TITLE
stripe_payment vs flutter_stripe

### ISSUE THREAD

**Issue by fabioselau077** [flutter-stripe/flutter_stripe#674]
### Discussed in https://github.com/flutter-stripe/flutter_stripe/discussions/673

<div type='discussions-op-text'>

<sup>Originally posted by **fabioselau077** April 10, 2022</sup>
Hello, I'm migrating an old code where I use the deprecated stripe_payment plugin.
There I do as follows:
1) Retrieve card data by inputs (name, number, expiration and cvv);
2) Create a CreditCard() with this data.
3) Used createTokenWithCard informing the CreditCard() created earlier.
4) After that, I sent the token and other information to my backend to charge Stripe.

I checked in the documentation that the createTokenWithCard() method was replaced by createToken, but I'm having trouble knowing how to do the same steps I did in the other package.

I don't want to use that native Flutter widget, I already have my widget ready to retrieve the card data.

Thanks</div>

**Comment by jonasbark** [comment]
Closing this in favor of the existing discussion
