### ISSUE TITLE
Lower case UK's postal codes are not accepted

### ISSUE THREAD

**Issue by matthewfx** [flutter-stripe/flutter_stripe#675]
**Describe the bug**.
Entering a postal code with lower case results in an error message that a transaction can not be authenticated

**To Reproduce**
Steps to reproduce the behaviour:
1. Entering a valid card number, date, and CVV into the card field.
3. Selecting the United Kingdon
3. Entering BH21 1BU' works but 'bh21 1bu' will fail
6. Observe an error message being displayed saying that your payment can not be authenticated. 

 - Device: One Plus Nord
 - OS: Need to confirm with the user
 - Package version: 2.2.0
 - Flutter version: 2.10.4
 
**Expected behaviour**
Both upper case and lower case postal codes should be working

**Additional info
Our app uses the setup intent and Stripe's UI elements. I haven't tried different payments methods.

**Comment by jonasbark** [comment]
Please follow the issue template and provide further information, such as device used, plugin version etc.

**Comment by matthewfx** [comment]
I've added missing info...
