### ISSUE TITLE
Support: Android initialization error: PlatformException(flutter_stripe initialization failed)

### ISSUE THREAD

**Issue by jim-2000** [flutter-stripe/flutter_stripe#681]
Exception has occurred.
PlatformException (PlatformException(flutter_stripe initialization failed, The plugin failed to initialize:
Your Main Activity class io.flutter.embedding.android.FlutterActivity is not a subclass FlutterFragmentActivity.
Please make sure you follow all the steps detailed inside the README: https://github.com/flutter-stripe/flutter_stripe#android
If you continue to have trouble, follow this discussion to get some support https://github.com/flutter-stripe/flutter_stripe/discussions/538, null, null))

// mainActive.kt
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.android.FlutterFragmentActivity

class MainActivity: FlutterFragmentActivity() {
}

// android build.gradlew 
 classpath 'com.android.tools.build:gradle:4.2.0'
//  gradlew wrapper
#Fri Jun 23 08:50:38 CEST 2017
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-7.0.2-all.zip

// 

why this error

**Comment by remonh87** [comment]
For paymentsheet it is required to have a fragmentactivity. To be PCI compliant we need to use the native screens an your activity needs to extend fragment activity. For support on how to configure I refer to https://github.com/flutter-stripe/flutter_stripe/discussions/538 and our extensive troubleshoot page.  https://docs.page/flutter-stripe/flutter_stripe/troubleshooting
