### ISSUE TITLE
Subscriptions with Apple Pay and fixed price

### ISSUE THREAD

**Issue by dragouf** [flutter-stripe/flutter_stripe#682]
**Is your feature request related to a problem? (please describe)**
I try to use apple pay for subscription. For that I would like to display apple pay button on payment sheet and when clicking on apple pay, display subscription price and recurrence. 

I did succeed to display apple pay bouton for recurrence with setup intent but instead of pricing it display "amount pending".
![variable subscription](https://developer.apple.com/design/human-interface-guidelines/apple-pay/images/ApplePaySheet-variablesubscription.png)

**Describe the solution you'd like**
I would like setup intent to be link to the subscription to display it's selected price:
![variable subscription](https://developer.apple.com/design/human-interface-guidelines/apple-pay/images/ApplePaySheet-fixedsubscription.png)

**Describe alternatives you've considered**
need to use stripe checkout in a webview ?

**Additional context**
My current flow:

- create setup intent backend side
- display setup sheet mobile side with presentPaymentSheet and setupIntentClientSecret
- when receive setup intent success backend side, create subscription with it

But it seems there is now way to attach subscription to setup before to present it mobile side to be able to display pricing correctly. 

What is the correct way to do that ?

**Comment by remonh87** [comment]
@dragouf  sorry for some reason we missed this. this is an advanced usecase and to be honest I have no idea. I would recommend asking Stripe for support on this and we can help you when questions arise in regard to specific Flutter code.

**Comment by dragouf** [comment]
According to my researches I find that you can’t implement it right now because it’s hard coded in stripe iOS library. Check this ticket here: https://github.com/stripe/stripe-ios/issues/1952

They answer it will be implemented so it may be reflected later in this library I guess. 

however I think it’s important since it may not be legal to display “pending amount” in some countries …

**Comment by oliveyew** [comment]
@dragouf  This will do the trick
[link](https://www.udemy.com/course/flutter-in-app-consumable-non-consumable-purchase-2022/?couponCode=NEW_USER_DISCOUNT)

**Comment by remonh87** [comment]
We now support the newest apple pay payment methods from version [4.0.0](https://pub.dev/packages/flutter_stripe/changelog#400) .

**Comment by kekko7072** [comment]
+ 1
