### ISSUE TITLE
[stripe_checkout] Unrecognized feature: 'payment' when calling redirectToCheckout

### ISSUE THREAD

**Issue by kduvignau** [flutter-stripe/flutter_stripe#683]
**Describe the bug**
I'm trying to use `stripe_checkout` package on Android to handle subscription creation, as `flutter_stripe`  does not seem to handle it.

When I call `redirectToCheckout`, I got a white screen and this error in my console : 
`I/chromium(19985): [INFO:CONSOLE(1)] "Unrecognized feature: 'payment'.", source: https://js.stripe.com/v3/ (1)`

Also, I don't know what to put in successUrl and cancelUrl 

**Expected behavior**
The webview should open correctly

**Additional context**
NB : I don't use any webview package
```
@override
  Widget build(BuildContext context, WidgetRef ref) {
    return Scaffold(
      body: SafeArea(
        child: TextButton(
          onPressed: () async {
            final callable =
                FirebaseFunctions.instance.httpsCallable('checkout');

            final session = await callable();

            if (session.data['success']) {
              await redirectToCheckout(
                context: context,
                sessionId: session.data['sessionId'],
                publishableKey: publicKey,
                successUrl: 'https://checkout.stripe.dev/success',
                canceledUrl: 'https://checkout.stripe.dev/cancel',
              );
            }
          },
          child: Text('Pay'),
        ),
      ),
    );
  }
```

The sessionId is generated from my backend, I use Firebase cloud function. Here is my cloud function  that creates the session : 

```
export const checkout = functions.https.onCall(async () => {
  try {
    const result = await stripe.checkout.sessions.create({
      payment_method_types: ["card"],
      mode: "subscription",
      line_items: [
        {
          price: "some_price_id",
          quantity: 1,
        },
      ],
      success_url: "https://checkout.stripe.dev/success",
      cancel_url: "https://checkout.stripe.dev/cancel",
    });

    return { success: true, sessionId: result.id };
  } catch (error) {
    functions.logger.error(error);
    throw new functions.https.HttpsError("invalid-argument", "Error while checkout");
  }
});
```

**To Reproduce**
- Generate a session Id with a backend 
- Create a StatelessWidget with the code above
- Click on Pay, a white screen should appear

**Smartphone / tablet**
 - Device: Pixel 2
 - OS: Android 9.0 (API 28)
 -  Package version: flutter_stripe: ^2.4.0 and stripe_checkout: ^0.1.2
 - Flutter version: 2.10.2

**Comment by kduvignau** [comment]
@jonasbark I'm trying to use stripe_checkout in a mobile context (Android/iOS) and not in web

**Comment by kduvignau** [comment]
Is this package still maintained? Should I post my problem somewhere else or should I use another one for my use case?

I would like to handle subscriptions with Stripe in iOS/Android. We offer a physical service so we don't have to use in-app subscriptions.

**Comment by remonh87** [comment]
@kduvignau  we just had a big update of the current package so unfortunately the web package is a bit lacking behind (also because it is in beta. We hope to spend some time on it the coming days but we are a bit stretched at the moment. Hope your understanding and we will come back to your ticket

**Comment by kduvignau** [comment]
Thanks for the reply! I'll wait then.

Could you just confirm that in theory, I can use stripe_checkout on mobile to handle subscriptions?

**Comment by jonasbark** [comment]
Yes, you can!

**Comment by kduvignau** [comment]
I runned the example app provided in the repository and I have the same error :

`I/chromium(19638): [INFO:CONSOLE(1)] "Unrecognized feature: 'payment'.", source: https://js.stripe.com/v3/ (1)`

**Comment by Zelfapp** [comment]
I'm also getting this `Unrecognized feature: 'payment'` error in the `redirectToCheckout` method. The [documentation for stripe_checkout](https://pub.dev/packages/stripe_checkout) is lacking. E.g. There is no link to the example (I think it is the example) for `stripe_checkout`, which is actually found in the `flutter_stripe` package.

`I/chromium( 8313): [INFO:CONSOLE(1)] "Unrecognized feature: 'payment'.", source: https://js.stripe.com/v3/ (1)`

E.g. where is the implementation. Is [this the implementation for stripe_checkout](https://github.com/flutter-stripe/flutter_stripe/blob/main/example/lib/screens/checkout/checkout_screen.dart)? If so, there is no mention of installing stripe_checkout_web.dart. I tried this in flutter app and it would not build because stripe_checkout_web doesn't exist. Again, no docs on this, if this is the example. Do I need to [install other packages like found here in the example pubspec.yaml](https://github.com/flutter-stripe/flutter_stripe/blob/main/example/pubspec.yaml) to get `stripe_checkout` to work on android/ios and web?

```dart
import 'platforms/stripe_checkout.dart'
    if (dart.library.js) 'platforms/stripe_checkout_web.dart';
```

![image](https://user-images.githubusercontent.com/11559805/167747382-dc2137e1-f1c9-4119-be1c-0af82324e3c8.png)

Currently, I'm testing on android in Android Studio emulator.

**Server code to create Stripe session id:**
```javascript
app.post('/create-checkout-session/:debug?', async (req, res) => {
  let debug = req.params.debug === 'debug'
  debug = true

  try {
    const stripeSecretKey = await getStripeSecretKey()
    const stripe = new Stripe(stripeSecretKey, {
      apiVersion: stripeApiVersion,
    })

    const { amount, show, successUrl, canceledUrl } = req.body

    if (!amount || !show || !successUrl || !canceledUrl) {
      functions.logger.error('Missing data', {
        amount,
        show,
        successUrl,
        canceledUrl,
      })
      throw Error('Missing data')
    }

    try {
      const session = await stripe.checkout.sessions.create({
        payment_method_types: ['card'],
        line_items: [
          {
            price_data: {
              currency: 'usd',
              product_data: {
                name: show,
              },
              unit_amount: amount,
            },
            quantity: 1,
          },
        ],
        mode: 'payment',
        success_url: successUrl,
        cancel_url: canceledUrl,
      })

      res.json({ id: session.id, payment_intent: session.payment_intent, url: session.url })
    } catch (e) {
      res.status(400).json({ error: { message: e.toString() } })
    }
  } catch (e) {
    if (debug) {
      functions.logger.error(e)
    }
    res.status(400).json({ error: { message: e.toString() } })
  }
})
```

Dart code
```dart
Future<String> _createCheckoutSession() async {
  String onRequestUri =
      'https://mydomain.cloudfunctions.net/create-checkout-session';

  /// If in debug mode add debug flag
  if (kDebugMode) {
    onRequestUri = '$onRequestUri/debug';
  }

  debugPrint(onRequestUri);

  final int amount = _convertTotalPriceFractionToCents();

  debugPrint(amount.toString());

  final Uri url = Uri.parse(onRequestUri);
  final double totalPriceDouble = _totalPrice();

  if (totalPriceDouble == 0) {
    throw CatException('Please check that you have selected a ticket for all '
        'of your selected seats.');
  }

  final response = await http.post(
    url,
    headers: {
      'Content-Type': 'application/json',
    },
    body: json.encode({
      'amount': amount,
      'show': 'A Play',
      'successUrl': 'https://mydomain.com/success',
      'canceledUrl': 'https://mydomain.com/cancel',
    }),
  );
  final Map<String, dynamic> bodyResponse = json.decode(response.body);

  debugPrint(bodyResponse.toString());

  if (!bodyResponse.containsKey('id')) {
    throw CatException('Could not obtain a session id for payment. Please '
        'try again.');
  }

  return bodyResponse['id'] as String;
}

Future<void> _getCheckout() async {
  try {
    final String sessionId = await _createCheckoutSession();
    final result = await redirectToCheckout(
      context: context,
      sessionId: sessionId,
      publishableKey:
          kDebugMode ? kStripePublishableTestKey : kStripePublishableKey,
      successUrl: 'https://mydomain.com/success',
      canceledUrl: 'https://mydomain.com/cancel',
    );

    if (mounted) {
      final text = result.when(
        success: () => 'Paid successfully',
        canceled: () => 'Checkout canceled',
        error: (e) => 'Error $e',
        redirected: () => 'Redirected successfully',
      );
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text(text)),
      );
    }
  } catch (e) {
    debugPrint(e.toString());
    rethrow;
  }
}
```

**Comment by kduvignau** [comment]
Since `stripe_checkout` doesn't seem to be the priority for now, would you recommend to use `flutter_stripe` to handle subscriptions instead?

As we can't use a payment intent directly, I would like to use the following flow :
- [server] Create a stripe customer
- [server] Initiate a setup intent (not a payment intent) 
- [client]  Use `Stripe.instance.initPaymentSheet(paymentSheetParameters: SetupPaymentSheetParameters(...))` to display the payment sheet and collect the payment method
- [server] Attach the payment method to the customer using the setup intent id
- [server] Create the subscription using the customer id only

Could you confirm this is the right way to handle subscriptions with `flutter_stripe` ?

**Comment by gbaccetta** [comment]
Hi @kduvignau, @remonh87 I had the same issue and found the issue.
Problem is simply that the template injecting the stripe js script has to be hosted over https and not declared as a variable:

this const is what cause the issue:
`const _htmlPage = '''
<!DOCTYPE html>
<html>
<script src="https://js.stripe.com/v3/"></script>
<head><title>Stripe Checkout</title></head>
<body>
</body>
</html>
''';`

this page ha to be hosted over https

**Comment by kduvignau** [comment]
Hi @gbaccetta , thanks for your answer!
We don't inject HTML anywhere, I guess `stripe_checkout` does this for us, so that's not in our hands right?
How can we apply your fix using `stripe.checkout.sessions.create` ?

**Comment by gbaccetta** [comment]
Hi @kduvignau yes, I’m talking about the thé stripe_checkout library. I forked it and changed the html code with the initial url of a page with the same html code (but hosted on my website) and now it all works like a charm

**Comment by xErik** [comment]
Solved the problem by modifying **app/src/main/AndroidManifest.xml**.

The error message persists, but the blank screen is gone and a checkout is possible.

```xml
<manifest ...>
    <application ...>
        <activity ...>
            
            <!-- ADD THIS -->
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="stripesdk" android:host="3ds.stripesdk.io" />
            </intent-filter>

        </activity>

    </application>

</manifest>
```

**Comment by oliveyew** [comment]
I find a new way to implement it [link](https://www.udemy.com/course/flutter-in-app-consumable-non-consumable-purchase-2022/?couponCode=NEW_USER_DISCOUNT)

**Comment by NitrofCG** [comment]
If you download the script and inject it, it's work.

```
http.Client _httpClient = http.Client();
              _httpClient.get(Uri.parse("https://js.stripe.com/v3/")).then((value) {                
                _webViewController!.loadHtmlString(_htmlPage.replaceAll("[[INJECT_JS]]", value.body), baseUrl: _baseUrl);
              });
```

with _htmlPage content:

```
<!DOCTYPE html>
<html>
<script>[[INJECT_JS]]</script>
<head><title>Stripe Checkout</title></head>
<body>
</body>
</html>
```

**Comment by kduvignau** [comment]
Thanks @NitrofCG and @gbaccetta, I managed to handle subscription without using `stripe_checkout`

**Comment by nerder** [comment]
@kduvignau subscriptions in not the only use-case for wanting to use checkout, so the bug is still valid I guess.

@gbaccetta did you manage to open a pull-request with the fix? What are the steps I should follow?

**Comment by nerder** [comment]
Hey @jamesblasco, I think can be closed as well at this point. 

Thank you so much for reviewing and merging it 🙏🏼

**Comment by MatteoAntolini** [comment]
The error `Unrecognized feature: 'payment' when calling redirectToCheckout` stems from the fact that the Payment Request API isn't supported in Flutter's WebView. This API allows for seamless payment procedures on websites, but it isn't universally compatible, especially with certain WebView environments. A potential workaround is to employ an external browser through a system like 'url_launcher', and then use a deep link to redirect back to the app post-payment. This allows your app to utilize the API's capabilities indirectly.

This issue is related to https://github.com/flutter-stripe/flutter_stripe/issues/993
Google Pay and Apple Pay are not visible because the webview can't support them.

**Comment by SayedMainUddin** [comment]
Android device: I am using android phone and when open secure checkout page I am getting this error.
I/chromium( 6004): [INFO:CONSOLE(1)] "Unrecognized feature: 'payment'.", source: https://js.stripe.com/v3 (1)

I/flutter ( 6004): StripeException(error: LocalizedErrorMessage(code: FailureCode.Failed, localizedMessage: , message: null, stripeErrorCode: null, declineCode: null, type: null))
Still getting this error. I am using latest stripe version.
Please somebody help me.
