### ISSUE TITLE
index out of range on paymentMethodTypes

### ISSUE THREAD

**Issue by benlrichards** [flutter-stripe/flutter_stripe#685]
When calling presentPaymentSheet, I get a fatal error:

Swift/ContiguousArrayBuffer.swift:580: Fatal error: Index out of range
2022-04-20 09:16:43.246365-0400 Runner[8110:61368] Swift/ContiguousArrayBuffer.swift:580: Fatal error: Index out of range

1. Create payment intent. (I ensured mine has payment method types.)
3. Call .initPaymentSheet, passing in the client secret from the intent.
4. Call .presentPaymentSheet();

My code: 
```
 String intentSecret = await OrderProvider()
          .createPaymentIntent((cartTotal.value * 100).toInt());


      await Stripe.instance.initPaymentSheet(
          paymentSheetParameters: SetupPaymentSheetParameters(
              paymentIntentClientSecret: intentSecret,
              testEnv: true,
              merchantCountryCode: 'US'));
      await Stripe.instance.presentPaymentSheet();
```

**Comment by jonasbark** [comment]
Can you run your app via xcode and post the full stack trace? The key information seems to be missing here

**Comment by benlrichards** [comment]
@jonasbark 2022-04-20 11:10:33.305095-0400 Runner[18290:166636] LOG ANALYTICS: ["pay_var": "legacy", "plugin_type": "flutter", "analytics_ua": "analytics.stripeios-1.0", "install": "C", "app_version": "1.0.0", "product_usage": ["PaymentSheet"], "apple_pay_enabled": 1, "is_development": true, "app_name": "skip_the_line_pos", "event": "mc_complete_init_default", "publishable_key": "pk_test_51KYWzF2K7Vbemuagcr53jpnad8TZjUpfsU1lil57SWCDNMTp9Zfye6HGfIz2wCrFUmv1LLsxWzXOqK1jlyNw4v1K00z6nERM1Z", "bindings_version": "21.12.0", "ocr_type": "none", "additional_info": [], "device_type": "x86_64", "os_version": "15.2"]
2022-04-20 11:10:33.443360-0400 Runner[18290:167737] [boringssl] boringssl_metrics_log_metric_block_invoke(151) Failed to log metrics
Swift/ContiguousArrayBuffer.swift:580: Fatal error: Index out of range
2022-04-20 11:10:33.720374-0400 Runner[18290:166636] Swift/ContiguousArrayBuffer.swift:580: Fatal error: Index out of range
