### ISSUE TITLE
call Apple Pay updateApplePaySummaryItems

### ISSUE THREAD

**Issue by dragouf** [flutter-stripe/flutter_stripe#686]
**Is your feature request related to a problem? (please describe)**
be able to update apple pay payment items on setup intent to display pricing

**Describe the solution you'd like**
I see a method here 'updateApplePaySummaryItems' : https://github.com/flutter-stripe/flutter_stripe/blob/d2f08cd61c5a3ce8c036787e4d3aacca8ccada9a/packages/stripe_ios/ios/Classes/StripePlugin.swift#L63

but I don't see any way to use it before displaying payment sheet.

it would be nice to be able to call it to pass it pricing, especially for Setup Intent. Without that Setup intent with apple pay display "Amount pending". Which is not legal in some countries and rejected at apple validation

**Describe alternatives you've considered**
maybe someone know how to call this method ?

**Additional context**
see apple documentation related to this method: 
https://developer.apple.com/documentation/passkit/pkpaymentrequest
https://developer.apple.com/documentation/passkit/pkrecurringpaymentsummaryitem

**Comment by remonh87** [comment]
yes good catch I will pick it up coming days

**Comment by remonh87** [comment]
@dragouf  it is quite difficult for me to test this method. Is it easy for you to test it on branch: `add-updateApplePaySummaryItems`? 

Else can you explain to me what I need to do in order to  trigger this method ?

**Comment by dragouf** [comment]
@remonh87 thanks for this PR. unfortunately after reading more deeply the code I think it cannot solve my problem. I mean, to update price on Setup Intent. According to what I can see in stripe-ios library it's hard coded for now and cannot be changed. I opened a ticket on stripe ios repository related to that: https://github.com/stripe/stripe-ios/issues/1952#issuecomment-1106967394

Anyway, exposing this method may be useful to someone else but I'm not sure how to test it as well since it's not what I'm trying to achieve.
