### ISSUE TITLE
#637 has been fixed. When can it be updated to fluent_ stripe: ^2.4.0

### ISSUE THREAD

**Issue by Yangpengtao** [flutter-stripe/flutter_stripe#687]
**Is your feature request related to a problem? (please describe)**
#637 issue I hope to update to pub.dev. I changed how to use the github library directly on Flutter

**Describe the solution you'd like**
#637 issue I hope to update to pub.dev. 
 

**Additional context**
Or instruct me on how to use the github library in Flutter

**Comment by jonasbark** [comment]
Will be released soon.
https://www.google.com/search?q=git+flutter+pub
