### ISSUE TITLE
AubecsFormField - BSB and Account Number fields are not receiving input on Android 12 specifically.

### ISSUE THREAD

**Issue by eneesolutions** [flutter-stripe/flutter_stripe#693]
**Describe the bug**
We are using the AUBecsDebit form as part of our app and on Android 12 devices the BSB and Account Number fields are not receiving any input at all. The form works as expected on iOS, as well as Android 11.

**To Reproduce**
1. Generate a AubecsFormField within Flutter app on Android 12.
2. Start typing in any field and validation will show as failed, even though you can still input name and email.
3. Trying to enter BSB or Account number will bring up the correct keyboard, but no input will be received in the form field.

**Expected behavior**
The bsb and account number would enter as expected.

**Smartphone / tablet**
 - Samsung Galaxy S20+ 5G
 - OS: Android 12
 - Package version: 2.2.0 (We are maintaining this version right now for stability, rather than 2.4.0. From reading changelog the issue I am having isn't fixed by most recent version.)
 - Flutter version: 2.10.4

**Additional context**
-

**Comment by jonasbark** [comment]
I can't confirm this on an Android emulator with API Level 31 (which would be Android 12), the latest version, and Flutter 2.10.4.
Is this a Samsung-specific bug?

**Comment by eneesolutions** [comment]
Can confirm that running with the example app and the latest version, this issue was no longer present. I will try to update to the latest flutter_stripe version for our project. Perhaps there was a fix for Android 12 devices that just wasn't visible in the change logs.
