### ISSUE TITLE
Freezed 2.0.0 and above are not supported

### ISSUE THREAD

**Issue by Yegorisa** [flutter-stripe/flutter_stripe#704]
**Describe the bug**
flutter_stripe 2.5.0 release notes state that it supports freezed version from 2.0 however it only supports 1.1.0

**To Reproduce**
1. Get Stripe of version 2.5.0 and freezed 2.0.0
2. Click pub get
3. See an error in a run terminal
![image](https://user-images.githubusercontent.com/21309131/166128471-3bbc3ee7-30ac-47c8-90ee-629bfcfb3648.png)

**Expected behavior**
No errors should be shown

**Comment by remonh87** [comment]
this is fixed now in version 2.5.0+1
