### ISSUE TITLE
App Store rejects the app.

### ISSUE THREAD

**Issue by Andres-98** [flutter-stripe/flutter_stripe#705]
I already tried to write in the 'plist' file that we don't use the camera. I also tried to explain that 'stripe' uses the camera to scan the cards but it keeps rejecting me.

ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSCameraUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).

**Comment by remonh87** [comment]
Even though you do not use it you need to provide the key `nsCameraUsageDescription` in info.plist. If you use the payment sheet you can use the following for example:
```xml
	<key>NSCameraUsageDescription</key>
	<string>You can use the camera to scan cards</string>
```
if you don't use payment sheet you can add:

```xml
	<key>NSCameraUsageDescription</key>
	<string>We do not use the camera.</string>
```
