### ISSUE TITLE
The link in the readme is wrong

### ISSUE THREAD

**Issue by otopba** [flutter-stripe/flutter_stripe#709]
> Using a descendant of Theme.AppCompat for your activity: [example](https://github.com/flutter-stripe/flutter_stripe/main/example/android/app/src/main/res/values/styles.xml#L15), [example night theme](https://github.com/flutter-stripe/flutter_stripe/blob/main/example/android/app/src/main/res/values-night/styles.xml#L16)

This link not found
https://github.com/flutter-stripe/flutter_stripe/main/example/android/app/src/main/res/values/styles.xml#L15

**Comment by remonh87** [comment]
I cannot reproduce the problem if you open the main page of the repo the link doesn;t work for you?
