### ISSUE TITLE
Set default keyboard type to TextInputType.number

### ISSUE THREAD

**Issue by ZaifSenpai** [flutter-stripe/flutter_stripe#71]
The keyboard opened in CardField() is TextInputType.text

The problem it is creating on my phone is that you have to press the numbers button on the bottom left every time you press a number. So you have to press 2 buttons to input 1 digit

https://user-images.githubusercontent.com/16265942/119507589-66a19700-bd88-11eb-84b4-2cc03eb0c55e.mp4

**Comment by jonasbark** [comment]
Hi Zarif - thanks for your feedback!
We are aware of this issue and tracking it here:
https://github.com/flutter-stripe/flutter_stripe/issues/14

It is caused by the Flutter framework and from what I'm hearing it may be fixed soon.
