### ISSUE TITLE
Problem adding a VISA card

### ISSUE THREAD

**Issue by diegobsit** [flutter-stripe/flutter_stripe#716]
**Describe the bug**
Hi! I'm facing an issue when I add a credit card with a `CardField`. I was able to go through the 3D Secure authentication process with an invalid expiration date and an invalid CVC. After going through the authentication process, I got stuck on a white screen inside the webview. No errors were thrown and the card wasn't added on my Stripe account.

This doesn't seem to happen with all card brands. For now we were only able to reproduce this issue with VISA cards from BNP Paribas Fortis (Belgian bank)

**To Reproduce**
1. Enter a valid credit card number.
2. Enter a wrong CVC or expiration date
3. `createPaymentMethod` > `setupPaymentMethod` > `confirmSetupIntent`
4. Complete the 3DS process

**Expected behavior**
The 3D Secure authentication should return an error when the provided card info isn't valid

**Smartphone / tablet**
 - Device: /
 - OS: iOS & Android
 - Package version: 2.5.0
 - Flutter version 2.5.10

**Comment by remonh87** [comment]
These are issues related to the Stripe sdk itself and I think it is related to #431 . See also https://github.com/stripe/stripe-react-native/issues/733.  I know they are working on a fix  but this is not something we can solve in our library. Let's use the mentioned issue as reference? 

If I am mistaken feel free to reopen it.
