### ISSUE TITLE
Support Flutter 3.0

### ISSUE THREAD

**Issue by remonh87** [flutter-stripe/flutter_stripe#718]
In #654  there is already a fix but I think we need to do more investigation since Flutter3 implements a new way for the platform bindings.  I think we need to do this

- Upgrade dependencies
- Fix compile issues
- Fix analyzer issues and warnings
- Test all the platformviews (apple pay button, cardfield, cardformfield, aubecsfield and google pay button).

**Comment by remonh87** [comment]
@jonasbark  I can start on this this evening

**Comment by asaarnak** [comment]
Errors after flutter 3 upgrade:
flutter_stripe-2.5.0/lib/src/widgets/card_field.dart:340:22: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
flutter_stripe-2.5.0/lib/src/widgets/card_field.dart:497:26: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
flutter_stripe-2.5.0/lib/src/widgets/card_form_field.dart:256:22: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
flutter_stripe-2.5.0/lib/src/widgets/card_form_field.dart:410:26: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.

**Comment by vikt0r40** [comment]
How to update temporary to 654 fix ?

**Comment by remonh87** [comment]
There is a pr + branch now but it breaks the cardfield on Android. Looks like the changes made in the native platformview has some regression in Flutter 3. We are investigating the issue and will contact the flutter team when necessary. For cardview and cardformview users I do not recommend to upgrade at the moment.

**Comment by remonh87** [comment]
Solved the issue and merged in #721
