### ISSUE TITLE
Support: Android initialization error: PlatformException(flutter_stripe initialization failed)

### ISSUE THREAD

**Issue by sirblazerx** [flutter-stripe/flutter_stripe#719]
### Discussed in https://github.com/flutter-stripe/flutter_stripe/discussions/538

<div type='discussions-op-text'>

<sup>Originally posted by **jamesblasco** January 15, 2022</sup>
Are you having trouble making the Flutter Stripe work on Android? This discussion is to give support for this specific problem.
We are aware that the process is a bit more complex than desired but it is out of our hands here. 

Please make sure you check again and follow all the steps in the [readme](https://github.com/flutter-stripe/flutter_stripe/) before posting here. 

</div>

Hi im getting this error after following all the steps needed for the plugin 

e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\stripe_android-2.5.0\android\src\main\kotlin\com\flutter\stripe\StripeAubecsDebitPlatformViewFactory.kt: (13, 1): Class 'StripeAubecsDebitPlatformViewFactory' is not abstract and does not implement abstract base class member public abstract fun create(p0: Context?, p1: Int, p2: Any?): PlatformView defined in io.flutter.plugin.platform.PlatformViewFactory
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\stripe_android-2.5.0\android\src\main\kotlin\com\flutter\stripe\StripeAubecsDebitPlatformViewFactory.kt: (19, 5): 'create' overrides nothing
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\stripe_android-2.5.0\android\src\main\kotlin\com\flutter\stripe\StripeSdkCardFormPlatformViewFactory.kt: (12, 1): Class 'StripeSdkCardFormPlatformViewFactory' is not abstract and does not implement abstract base class member public abstract fun create(p0: Context?, p1: Int, p2: Any?): PlatformView defined in io.flutter.plugin.platform.PlatformViewFactory
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\stripe_android-2.5.0\android\src\main\kotlin\com\flutter\stripe\StripeSdkCardFormPlatformViewFactory.kt: (18, 5): 'create' overrides nothing
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\stripe_android-2.5.0\android\src\main\kotlin\com\flutter\stripe\StripeSdkCardPlatformViewFactory.kt: (12, 1): Class 'StripeSdkCardPlatformViewFactory' is not abstract and does not implement abstract base class member public abstract fun 
create(p0: Context?, p1: Int, p2: Any?): PlatformView defined in io.flutter.plugin.platform.PlatformViewFactory
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\stripe_android-2.5.0\android\src\main\kotlin\com\flutter\stripe\StripeSdkCardPlatformViewFactory.kt: (18, 5): 'create' overrides nothing
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\stripe_android-2.5.0\android\src\main\kotlin\com\flutter\stripe\StripeSdkGooglePayButtonPlatformViewFactory.kt: (12, 1): Class 'StripeSdkGooglePayButtonPlatformViewFactory' is not abstract and does not implement abstract base class member public abstract fun create(p0: Context?, p1: Int, p2: Any?): PlatformView defined in io.flutter.plugin.platform.PlatformViewFactory
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\stripe_android-2.5.0\android\src\main\kotlin\com\flutter\stripe\StripeSdkGooglePayButtonPlatformViewFactory.kt: (18, 5): 'create' overrides nothing

This is my MainActivity.kt 

package com.example.gwcqp

import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.android.FlutterFragmentActivity

class MainActivity: FlutterFragmentActivity() {
}

My Styles xml 

<?xml version="1.0" encoding="utf-8"?>
<resources>
    
    <style name="LaunchTheme" parent="Theme.AppCompat.Light.NoActionBar">
        
        <item name="android:windowBackground">@drawable/launch_background</item>
    </style>
    
    <style name="NormalTheme" parent="Theme.MaterialComponents">
        <item name="android:windowBackground">?android:colorBackground</item>
    </style>
</resources>

My android manifest

<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.example.gwcqp"
    xmlns:tools="http://schemas.android.com/tools">
    <application android:label="gwcqp" android:name="${applicationName}" android:icon="@mipmap/ic_launcher" tools:replace="android:label">
        <activity android:name=".MainActivity" android:exported="true" android:launchMode="singleTop" android:theme="@style/LaunchTheme" android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode" android:hardwareAccelerated="true" android:windowSoftInputMode="adjustResize">
            
            <meta-data android:name="io.flutter.embedding.android.NormalTheme" android:resource="@style/NormalTheme" />

            <meta-data android:name="io.flutter.embedding.android.SplashScreenDrawable" android:resource="@drawable/launch_background" />

            <meta-data android:name="com.google.android.gms.wallet.api.enabled" android:value="true"/>
  

            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>

        </activity>

        
        <meta-data android:name="flutterEmbedding" android:value="2" />
    </application>
</manifest>

My Build.gradle

buildscript {
    ext.kotlin_version = '1.5.0'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.2.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.10'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**Comment by Mayb3Nots** [comment]
Having the same issue after upgrading to flutter 3.0

**Comment by wilpar** [comment]
> doing the above fixed the problem until the team update the package

Confirmed - appbundle compiles!  Appreciate this.
