### ISSUE TITLE
PlatformException(Failed, Payment not completed, null, null) payment cancel without obvious reason in 30% cases

### ISSUE THREAD

**Issue by Rioverde** [flutter-stripe/flutter_stripe#720]
**Describe the bug**
PlatformException(Failed, Payment not completed, null, null)  when client is trying to pay in 20-30% of cases (after failure he is able to make purchase, but it happens too frequent to ignore it)

**To Reproduce**
1.  Try to pay via apple pay.
2. Observe a failure with PlatformException(Failed, Payment not completed, null, null) exception in 30% of cases, once in 3 times  payment fails

**Expected behavior**
Apple payment goes well without exceptions

**Smartphone / tablet**
 - Device: iPhone 13

**Additional context**
In case of testing in test environment no problems occurs, but when it comes to production, a lot of users face the issue with apple pay

code example:

if (Platform.isIOS) {
          await stripe.Stripe.instance.presentApplePay(
            stripe.ApplePayPresentParams(
              cartItems: [
                stripe.ApplePayCartSummaryItem(
                  label: 'YallaMarket',
                  amount: total.toString(),
                ),
              ],
              country: 'AE',
              currency: Environment.currency,
            ),
          );

          await stripe.Stripe.instance.confirmApplePayPayment(stripeData?.paymentIntentClientSecret ?? '');
        } 
        
       also I make a sure that merchant id is not empty as well as key before I make payment:
       
       if (stripe.Stripe.publishableKey.isEmpty || stripe.Stripe.merchantIdentifier == null) {
        //initiating stripe
        stripe.Stripe.publishableKey = Config.env.stripeKey;
        stripe.Stripe.merchantIdentifier = 'xxxxx.app.xxxxxxx';
        await stripe.Stripe.instance.applySettings();
      }
      
      and before it, I Initialize the values when app starts, so it can not be empty anyway

Full example:

Stream<PaymentState> _pay(
    String stripeCustomerId,
    Address address,
    bool isNativePay,
  ) async* {
    try {
      if (stripe.Stripe.publishableKey.isEmpty || stripe.Stripe.merchantIdentifier == null) {
        //initiating stripe
        stripe.Stripe.publishableKey = Config.env.stripeKey;
        stripe.Stripe.merchantIdentifier = 'xxxxx.app.xxxxx';
        await stripe.Stripe.instance.applySettings();
      }
    } catch (e, s) {
      await Sentry.captureException(e, stackTrace: s);
    }
    try {
      if (isNativePay) {
        if (Platform.isIOS) {
          await stripe.Stripe.instance.presentApplePay(
            stripe.ApplePayPresentParams(
              cartItems: [
                stripe.ApplePayCartSummaryItem(
                  label: 'YallaMarket',
                  amount: total.toString(),
                ),
              ],
              country: 'AE',
              currency: Environment.currency,
            ),
          );

          await stripe.Stripe.instance.confirmApplePayPayment(stripeData?.paymentIntentClientSecret ?? '');
      }  ...

      
Observations:

When we observe results we see that information about payment comes to the dashboard (with client secret and etc data) but its greyed and saying that no payment was done, after if we try with the same card once more , it works and purchase goes well

**Comment by remonh87** [comment]
@Rioverde The Stripe native sdk throws this issue so I would recommend to contact Stripe what went wrong with the paymentintent . At this point there is little what we can do from our side.

I checked your code and the implementation looks good. Make sure that you apply the `merchantId` to the Stripe settings before calling present paymentsettings. It looks like some race condition

**Comment by remonh87** [comment]
CLosing this for now but feel free to reopen it. or adding a new issue if you found sth related to the library

**Comment by Rioverde** [comment]
> @Rioverde The Stripe native sdk throws this issue so I would recommend to contact Stripe what went wrong with the paymentintent . At this point there is little what we can do from our side.
> 
> I checked your code and the implementation looks good. Make sure that you apply the `merchantId` to the Stripe settings before calling present paymentsettings. It looks like some race condition

Here again , Stripe Engineer Responded me about this issue in following way 

Thank you for providing more details. I'm checking the log but it seems like the underlying error isn't present here. 
The error log is basically stripe-flutter plugin saying something went wrong, it doesn't exactly mention what went wrong and why the payment was cancelled.

I'm happy to look into it further once we can narrow down on the error thrown by Stripe's SDK (not stripe-flutter).
However, you'd need to work with the plugin developer to get there. 

Let me know if you have any follow up questions :)
John M.


Is there anything we can do about this ?
