### ISSUE TITLE
Support future payment for web

### ISSUE THREAD

**Issue by zengshan233** [flutter-stripe/flutter_stripe#723]
I'm using the method of "confirmSetupIntent"  to  save card for future payment in my website, but experiencing unimplemented error. Is there any plans to complete it ?

**Comment by remonh87** [comment]
Web is a bit lacking behind at the moment but I added it as an enhancement and will let you know when we start working on it

**Comment by michaelhwn** [comment]
@ @remonh87, I noticed the confirmSetupIntent function seems to be implemented in [here](https://github.com/flutter-stripe/flutter_stripe/blob/51b46cacad98410edc9373344b244197e4be213a/packages/stripe_web/lib/src/web_stripe.dart#L172) for web, is this function in a usable stage?

**Comment by oliveyew** [comment]
You can add it this way [link](https://www.udemy.com/course/flutter-in-app-consumable-non-consumable-purchase-2022/?couponCode=NEW_USER_DISCOUNT)

@zengshan233 @michaelhwn

**Comment by SeriousMonk** [comment]
I am getting the same error, but the payment method is being saved correctly on Stripe.

**Comment by PatrikGolubar** [comment]
@remonh87 Do you know when Future payment for web will be supported?

**Comment by remonh87** [comment]
@jamesblasco  can you answer above question? You have the best insight on the plans for the web

**Comment by jamesblasco** [comment]
I have been working this past weekend to make the flow work for web, it should be ready next week.

**Comment by PatrikGolubar** [comment]
@jamesblasco When update will be available?

**Comment by PatrikGolubar** [comment]
@jamesblasco: Do you have any new informations about this? It would be nice to have this update in next two weeks.

**Comment by PatrikGolubar** [comment]
> I have been working this past weekend to make the flow work for web, it should be ready next week.

Can you give us any information about this update ? It would be really nice to have it. I can't continue with app development without this. Please let me know. If you don't have time, please let me know how can I fix that by myself?

**Comment by jamesblasco** [comment]
Sorry for the delay. From the maintainers I am the one taking ownership of this. I am in the process of changing jobs so this last couple weeks I had too many things on my plate.

The current blocker right now is the way to handle javascript union types in dart. In the first release of this library I used a technique that I do not think it will work long term. I have been working on a new version for this that con support setup intents. I will push today what I have so far into https://github.com/flutter-stripe/flutter_stripe/pull/1079 so you can take a look. I will try to speed up this as much as possible.

**Comment by PatrikGolubar** [comment]
> Sorry for the delay. From the maintainers I am the one taking ownership of this. I am in the process of changing jobs so this last couple weeks I had too many things on my plate.
> 
> The current blocker right now is the way to handle javascript union types in dart. In the first release of this library I used a technique that I do not think it will work long term. I have been working on a new version for this that con support setup intents. I will push today what I have so far into #1079 so you can take a look. I will try to speed up this as much as possible.

I understand that you work in your spare time, so no problem for delay :) If I understand right, code which you pushed, will work now on web or does it need some changes?

**Comment by remonh87** [comment]
This is already part of latest web sdk

**Comment by sleewok** [comment]
> This is already part of latest web sdk

Fantastic. Thank you for getting this working. I will give it a try this week. Can you point me towards the commit that finished the implementation?
