### ISSUE TITLE
Card confirmPayment opens web hook after payment success

### ISSUE THREAD

**Issue by ShwetaChauhan18** [flutter-stripe/flutter_stripe#734]
**Once I complete payment through card, it's open webhook in google or safari.  Payment success done but it's open web hook screen in browser and I don't know it's bug from your side or something which I missed from my side.**

1. Payment Intent created from server
2. I used clientSecret and paymentMethodParam to confirm payment
3. final paymentIntent = await Stripe.instance
          .confirmPayment(clientSecret, paymentMethodParam);
4. Payment success done but it open web hook screen in browser 

**Expected behavior**
After payment success it should not open webhook in browser.

**Smartphone / tablet**
 - Device:  iPhone XS
 - Package version: 3.0.0
 - Flutter version: 3.0.0.
 - Platform: Both Android and iOS

**Comment by ShwetaChauhan18** [comment]
![Simulator Screen Shot - iPhone 11 - 2022-05-18 at 14 09 04](https://user-images.githubusercontent.com/34509457/168998428-2dca6ebf-749c-4724-856f-57fafd8da315.jpg) || ![Simulator Screen Shot - iPhone 11 - 2022-05-18 at 14 09 02](https://user-images.githubusercontent.com/34509457/168998436-14e2acbb-26b1-41cb-8fe5-7d58029f218d.jpg) || ![Simulator Screen Shot - iPhone 11 - 2022-05-18 at 14 09 18](https://user-images.githubusercontent.com/34509457/168998440-4cb67e2d-dd5f-4236-b2fd-0487f137f72e.jpg)

**Comment by remonh87** [comment]
The simplest way is using webhooks. One thing that is often overlooked is setting the deep link: [define scheme ](https://github.com/flutter-stripe/flutter_stripe/blob/51b46cacad98410edc9373344b244197e4be213a/example/lib/main.dart#L11) and  add it to the manifest like: [manifest](https://github.com/flutter-stripe/flutter_stripe/blob/main/example/android/app/src/main/AndroidManifest.xml) for iOS you need to add the url scheme.

If you do not like webhooks checkout this example: https://github.com/flutter-stripe/flutter_stripe/blob/main/example/lib/screens/card_payments/no_webhook_payment_screen.dart

**Comment by ShwetaChauhan18** [comment]
I agree I should use no_webhook_payment but on confirm payment using card why it's opens webhook screen?? 
Confirm payment using card is through webhook only???

or from server side which I made paymentIntent should only from 'pay-without-webhooks' this API??

Before version 3.0.0 it's working fine

**Comment by remonh87** [comment]
it opens webhook screen because what it does is it send a sucess to the webhook that is listening. You can also confirm it manually on the server. https://stripe.com/docs/payments/accept-a-payment-synchronously.  

This situation should only happen with the test backend + test keys but not in production.
