### ISSUE TITLE
Choose which payment method is preselected on presentPaymentSheet

### ISSUE THREAD

**Issue by mortenolsson** [flutter-stripe/flutter_stripe#737]
When creating a paymentIntent server side and using presentPaymentSheet with customerId and ephemeralKey on the client the user can select from her available cards and pay - this is fine.
What we would like to do is control which card is pre-selected when popping the paymentSheet - is this possible ?

**Comment by remonh87** [comment]
I do not think you can preselect the card as the user should be able to choose the card he or she wants. I think it is possible though to not accept certain card providers though but then no one can enter a card of that provider. 

Unfortunately this is outside the scope of our library and I would recommend asking Stripe if this is on the roadmap.
