### ISSUE TITLE
Play store rejecting app updates 

### ISSUE THREAD

**Issue by imofidul** [flutter-stripe/flutter_stripe#738]
Used flutter_stripe:2.5.0 in our project
and play store rejecting app updates by mentioning below reason 
[https://drive.google.com/file/d/1h60xlse_EP9lHfRtdJXCPpF42N7tzBZb/view?usp=sharing](url)

**Comment by remonh87** [comment]
for some payment methods the Stripe Sdk needs to capture the mobile number. So you need to make sure that you mention this in the data sharing section of your store listing. 

https://support.google.com/googleplay/android-developer/answer/9859455?hl=en

**Comment by albertolina** [comment]
Hello, we tried indicating that we are capturing the phone number but the app keeps getting rejected with this reason: 

_APK REQUIRES PROMINENT DISCLOSURE​
We’ve identified that your app is using Stripe SDK or library, which facilitates the transmission of collection of Installed Application and Phone Number information without meeting the prominent disclosure guidelines. If necessary, you can consult your SDK provider(s) for further information_

Any other help? We used the sdk for over an year and we haven't had any issue so far. Can you send a link to the payments methods that needs to capture the phone number?

Thank you

**Comment by fabios9702** [comment]
I  have the same problem, I've update the privacy policy and The data security, but the app was rejected again. And It's not possibile to update a new version until this problem is fixed. Anyone knows a solution?

**Comment by remonh87** [comment]
I found this issue:  https://github.com/stripe/stripe-android/issues/5013

Looks like the Stripe android sdk is violating some play policies

**Comment by remonh87** [comment]
You can try to downgrade to version: 2.4.0 but keep in mind that this version is not compatible with Flutter3

**Comment by albertolina** [comment]
Thank you for your prompt answer, unfortunately we tried downgrading to 2.4.0 and we keep having the issue. We are also afraid that Google could remove our app if we continue to send for review a version with this same issue over and over.

**Comment by MDSADABWASIM** [comment]
Any update on this issue @remonh87

**Comment by korzonkiee** [comment]
Our app struggles with the same issue. Everything was fine when the app was referencing flutte_stripe: 2.4.0. Once we upgraded to flutter_stripe: 2.5.0, we got the following message from Google Play:

![image](https://user-images.githubusercontent.com/26259846/172555148-a5f5f891-0ad6-46a0-aaf3-ffe85eff18cd.png)

We rolled back to flutter_stripe: 2.4.0, but the builds it still being rejected with the same message. It seems that the only way to overcome this is to implement a "prominent disclosure" about the data that is being collected (installed applications & phone numbers) as required by Google Play, although the Stripe SDK doesn't seem to collect those data as [per this comment](https://github.com/stripe/stripe-android/issues/5013#issuecomment-1135270070).

Please see [this](https://github.com/stripe/stripe-android/issues/5013) issue for more info.

**Comment by remonh87** [comment]
we cannot do anything about this besides awaiting how the discussion between Stripe and Google turns out. I suggest to subscribe to the issue linked above  from the stripe android sdk.

**Comment by remonh87** [comment]
Stripe solved the issues with google a while ago  so rejection shouldn't happen anymore
