### ISSUE TITLE
IOS: No payment sheet has been initialized

### ISSUE THREAD

**Issue by Musfick** [flutter-stripe/flutter_stripe#742]
I am facing this error from IOS devices
Error from Stripe: No payment sheet has been initialized yet

**init**
````
Stripe.publishableKey = "pk_live_";
  Stripe.merchantIdentifier = 'com.company.app'; //i m not sure about this. is it app identifier ? or i need to get it some where else
  await Stripe.instance.applySettings();
````

**Init Sheet**
````
await Stripe.instance.initPaymentSheet(
          paymentSheetParameters: SetupPaymentSheetParameters(
            applePay: true,
            googlePay: true,
            testEnv: false,
            merchantCountryCode: 'US',
            merchantDisplayName: 'MerchantName',
            customerId: paymentData.customerId,
            paymentIntentClientSecret: paymentData.clientSecret,
            customerEphemeralKeySecret: paymentData.ephemeralKey,
          ));
````

using
flutter_stripe: ^2.5.0
sdks:
  dart: ">=2.16.2 <3.0.0"
  flutter: ">=2.10.0"

**On Simulator(Iphone 13)**
ios 15.2

**Getting error on IOS**
Error from Stripe: No payment sheet has been initialized yet

**Comment by Musfick** [comment]
✅ Solved

Okay, the problem was in our backend response
when we were generating EphemeralKey, our backend dev was returning ephemeralKey["id"] instead of ephemeralKey["secret"] as a ephemeralKey.

wrong response was
```
{
  "client_secret":"---",
  "ephemeralKey": "ephkey_1L2qRfIx9gdhYQREVADTfAPa",
  "customerId": "---"
}
```

right response is
```
{
  "client_secret":"---",
  "ephemeralKey": "ek_test_YWNjdF8xSlQ3amtDVEFVRGpSTkZWLE1DWXQyYWpZa090WWZnMjZ4NEt1WkRXeWZhTXVmdEM_00IOZhx0yo",
  "customerId": "---"
}
```

see ephemeralKey is different.
ephemeralKey["id"] is work fine in android app for stripe payment but on IOS ephemeralKey["id"] will not working 
it was showing Error from Stripe: No payment sheet has been initialized yet

i changed ephemeralKey["id"] to ephemeralKey["secret"] as a ephemeralKey and now it working fine on both device.

here is my code
```
//in main function
Stripe.publishableKey ="pk_test_______";
await Stripe.instance.applySettings();
```

```
//initialize the payment sheet
await Stripe.instance.initPaymentSheet(
          paymentSheetParameters: SetupPaymentSheetParameters(
          paymentIntentClientSecret: paymentData.clientSecret,
          merchantDisplayName: '______',
          customerId: paymentData.customerId,
          customerEphemeralKeySecret: paymentData.ephemeralKey,
          style: ThemeMode.light,
          testEnv: true,
          merchantCountryCode: 'US',
        ),
);

await Stripe.instance.presentPaymentSheet();
```

**Comment by adzdeveloper** [comment]
> ✅ Solved
> 
> Okay, the problem was in our backend response when we were generating EphemeralKey, our backend dev was returning ephemeralKey["id"] instead of ephemeralKey["secret"] as a ephemeralKey.
> 
> wrong response was
> 
> ```
> {
>   "client_secret":"---",
>   "ephemeralKey": "ephkey_1L2qRfIx9gdhYQREVADTfAPa",
>   "customerId": "---"
> }
> ```
> 
> right response is
> 
> ```
> {
>   "client_secret":"---",
>   "ephemeralKey": "ek_test_YWNjdF8xSlQ3amtDVEFVRGpSTkZWLE1DWXQyYWpZa090WWZnMjZ4NEt1WkRXeWZhTXVmdEM_00IOZhx0yo",
>   "customerId": "---"
> }
> ```
> 
> see ephemeralKey is different. ephemeralKey["id"] is work fine in android app for stripe payment but on IOS ephemeralKey["id"] will not working it was showing Error from Stripe: No payment sheet has been initialized yet
> 
> i changed ephemeralKey["id"] to ephemeralKey["secret"] as a ephemeralKey and now it working fine on both device.
> 
> here is my code
> 
> ```
> //in main function
> Stripe.publishableKey ="pk_test_______";
> await Stripe.instance.applySettings();
> ```
> 
>  ```
> //initialize the payment sheet
> await Stripe.instance.initPaymentSheet(
>           paymentSheetParameters: SetupPaymentSheetParameters(
>           paymentIntentClientSecret: paymentData.clientSecret,
>           merchantDisplayName: '______',
>           customerId: paymentData.customerId,
>           customerEphemeralKeySecret: paymentData.ephemeralKey,
>           style: ThemeMode.light,
>           testEnv: true,
>           merchantCountryCode: 'US',
>         ),
> );
> 
> await Stripe.instance.presentPaymentSheet();
> ```
// In main Function before RunApp
**Need to   add Stripe.merchantIdentifier = 'any unique string name';// suggestion package name
**
