### ISSUE TITLE
Google Pay

### ISSUE THREAD

**Issue by ItayBarFaye** [flutter-stripe/flutter_stripe#748]
**Describe the bug**
I tried to implement google pay in our App, I added the google pay button and it works with isGooglePaySupported function.
When clicking the button initGoogle Function call and nothing happened no error crash nothing it's looks like it's waiting for response that never come (not jump to the next code line).

**To Reproduce**
1. Tapping the google pay button.
2. Observe nothing will happen

**Expected behavior**
After clicking google pay button success with initGooglePay function and createPaymentMethod or present google pay.

**Smartphone / tablet**
 - Device: Android
 - OS: 12
 - Flutter version 3.0.1

**Additional context**
![image](https://user-images.githubusercontent.com/106300092/170430982-a1b2fcba-fc3c-4a22-8581-81447e3d6f15.png)

**Comment by remonh87** [comment]
Did you receive some error in logcat and if so can you share the output with us?

**Comment by ItayBarFaye** [comment]
> Did you receive some error in logcat and if so can you share the output with us?

I didn't get any errors

**Comment by ItayBarFaye** [comment]
There is no output logs for the init function

**Comment by ItayBarFaye** [comment]
Hey again, can someone help about this issue?

**Comment by remonh87** [comment]
The latest version 3.1.0 of this library consists of more error handling that hopefully helps you fixing the issues. Closing it for now
