### ISSUE TITLE
Add scan option to CardField

### ISSUE THREAD

**Issue by mortenolsson** [flutter-stripe/flutter_stripe#75]
I'd love the "scan" button to be available for the CardField so that the card details can be entered by scanning the card with the device camera.

**Comment by jamesblasco** [comment]
It is only possible to use card scanning with the PaymentSheet on iOS devices. Stripe android does not implement

To enable it you have to add the camera permission description in Info.plist
<key>NSCameraUsageDescription</key>
<string>Scan your card to add it automatically</string>

For the card field, if we integrate it would only be for iOS. I will leave this issue open to track the demand of this feature

**Comment by mortenolsson** [comment]
All our actual payments are done with saved cards on the backend so all I really use Stripe for on the client is adding cards so the payment sheet isn't viable for us. Keeping my fingers crossed that the scan option is added to CardField - it would really make my day. 
It is not out of the realm of possibility that I would be willing to pay you for your time if you can get this done rather soon - let me know if this is a viable way forward.

**Comment by jonasbark** [comment]
Have you looked at alternatives, such as https://pub.dev/packages/card_scanner ? 
Adding this functionality is out of scope for the beta phase.

**Comment by mortenolsson** [comment]
That's not usable to me - we do use Stripe so what I need is to create a stripe payment method and confirm the setup intent so the card is registered properly with Stripe. As I said I'd be willing to pay you if you would be willing to move this feature into active development and have it done within a couple of weeks.

**Comment by mortenolsson** [comment]
Anyway - feel free to get in touch at mholsson@gmail.com - and thank you for the great work you've already done - this means the world to me.

**Comment by thorsten-stripe** [comment]
A quick lurk: the payment sheet now has a setup mode which we're planning to add to the RN SDK: https://github.com/stripe/stripe-react-native/issues/293

**Comment by remonh87** [comment]
@mortenolsson  we have integtated the seupIntent in the payment sheet see comment of @thorsten-stripe . Do you think this is sufficient ?

**Comment by mortenolsson** [comment]
@remonh87 I'll check it out and get back to you

**Comment by mortenolsson** [comment]
I see the issue was closed - I'll create new one - sorry for the noise.

**Comment by AristideVB** [comment]
Hi guys, I'd love to use https://pub.dev/packages/card_scanner but I haven't been able to update CardField with values other than those typed

I've tried different things :

```dart
  var _controller = CardEditController(
       initialDetails: const CardFieldInputDetails(
         complete: true,
        number: "5554 5552 6666 4443",
        expiryMonth: 05,
      expiryYear: 26,
      ),
      );


          _card = _card!.copyWith(number: "55");
                          _controller.context.updateCardDetails(
                              _card!.copyWith(number: "55"), _controller);

                          _controller.details = CardFieldInputDetails(
                              number: "55", complete: false);
                        });
```

none which have updated the field values
