### ISSUE TITLE
Qatar is not in the list of countries on iPhones devices.

### ISSUE THREAD

**Issue by kingkick2008** [flutter-stripe/flutter_stripe#750]
I'm using the [flutter_stripe package ](https://pub.dev/packages/flutter_stripe)for my flutter app.
Qatar is not in the list of countries on iPhones devices.
![169116626-5a7c5fbc-832d-43d5-aa17-55ccc37c66ce](https://user-images.githubusercontent.com/23032240/170634626-1b44f95a-35a0-441d-bba0-06b0ae502b89.png)

**Comment by jonasbark** [comment]
Same here:
https://github.com/flutter-stripe/flutter_stripe/issues/751#issuecomment-1139342293

Also, check if Qatar is supported at all by Stripe.
