### ISSUE TITLE
Arabic languages not supported on IOS devices

### ISSUE THREAD

**Issue by kingkick2008** [flutter-stripe/flutter_stripe#751]
I'm using the [flutter_stripe package ](https://pub.dev/packages/flutter_stripe)for my flutter app.
The translation does not support the Arabic language on the presentPaymentSheet. I have tested on many Android devices and iOS devices.
I changed the mobile settings to the Arabic language.
![169117236-34883a33-1d08-4c24-87e3-db4ed25ba21f](https://user-images.githubusercontent.com/23032240/170634953-942c303a-d7a0-44e7-9729-e32f929c5bd1.png)

**Comment by jonasbark** [comment]
Hi!
We do not have any leverage over the payment sheet. It's a predefined component from stripe-android and stripe-ios libraries - I recommend looking into those repositories instead.

**Comment by omar-selo** [comment]
This has already been [fixed in stripe-ios ](https://github.com/stripe/stripe-ios/issues/1967)but flutter-stripe needs to update the dependency

**Comment by kingkick2008** [comment]
That's why I'm opening the case here again.
