### ISSUE TITLE
could not find module 'Stripe' for target 'arm64-apple-ios-simulator'; found: x86_64-apple-ios-simulator, x86_64

### ISSUE THREAD

**Issue by DEAL0704** [flutter-stripe/flutter_stripe#756]
**Describe the bug**
Build runs fine until I install flutter_stripe with flutter pub add flutter_stripe

I can build and run my project on the simulator then
flutter pub add flutter_stripe
flutter clean
flutter run

Build fails

**To Reproduce**
1.) using 
Xcode 13.1
`flutter_stripe: ^2.5.0`
Flutter 2.8.1 • channel stable • https://github.com/flutter/flutter.git

2.) Build for any simulator
3.) Observe failed build

**Expected behavior**
Xcode Output:
`    /../../Library/Developer/Xcode/DerivedData/Runner-bnkahjzkfxdttubfkyxloyyzjuhb/Build/Intermediates.noindex/Pods.build/Debug-ipho
    nesimulator/stripe_ios.build/Objects-normal/arm64/AuBECSDebitFormFactory.dia:1:1: warning: Could not read serialized diagnostics file:
    error("Invalid diagnostics signature") (in target 'stripe_ios' from project 'Pods')
    Command CompileSwift failed with a nonzero exit code
    /../../flutter/.pub-cache/hosted/pub.dartlang.org/stripe_ios-2.5.0/ios/Classes/Stripe Sdk/AuBECSDebitFormView.swift:3:8: error:
    could not find module 'Stripe' for target 'arm64-apple-ios-simulator'; found: x86_64-apple-ios-simulator, x86_64, at:
    /../../../../../build/ios/Debug-iphonesimulator/Stripe/Stripe.framework/Modules/Stripe.swiftmodule
    import Stripe`

**Smartphone / tablet**
 - Device: Xcode Simulator - All
 - OS: ios15
 - Package version: 2.5
 - Flutter version 2.8.1

**Additional context**
I can then flutter pub remove flutter_stripe and successfully launch on simulator

**Comment by remonh87** [comment]
What is the Swift version in your project?  Check your project file and search for:  `SWIFT_VERSION`

Make sure to make it 5.0 or higher

**Comment by DEAL0704** [comment]
`SWIFT_VERSION = 5.0;`

**Comment by remonh87** [comment]
You are using an m1 right? 

I think there is something wrong in your  xcode cache.  I had the same a while ago. It is quite annoying but not something related to our library. Maybe this post helps: https://stackoverflow.com/questions/56957632/could-not-find-module-for-target-x86-64-apple-ios-simulator

**Comment by DEAL0704** [comment]
No I am running a 1.6 GHz Dual-Core Intel Core i5 Mac Air.

Thanks for the SO post, I have searched and searched including that post with no luck.

I am able to run it on a real iphone.  It is weird that this problem happens as soon as I add the library to the project.  I am assuming something in the library changes some settings that is causing this... as it is the only change that brings about the problem.  

If there is no known solution, do you have a solid preference of what version of Xcode to use with a specific version of your library?  I am okay downgrading, I wish I never upgrading my OS that forced me to use Xcode 13+.

Thanks a ton for your help @remonh87!

**Comment by remonh87** [comment]
For me everything works fine on xcode 13. I think is always good to use latest stable.  I would search stackoverflow because I saw a lot of people having these issues with emulators. Maybe totally removing your xcode cache can help as well. Closing it for now

**Comment by oliveyew** [comment]
@DEAL0704 this works for me [here](https://www.udemy.com/course/flutter-in-app-consumable-non-consumable-purchase-2022/?couponCode=NEW_USER_DISCOUNT)

**Comment by danbeechbloom** [comment]
Had this issue also, adding the following to podfile and re-running `pod install` fixed for me:

```
installer.pods_project.build_configurations.each do |config|
    # allows cocoapods targets to build for x86_64
    config.build_settings["ARCHS[sdk=iphonesimulator*]"] = "x86_64 arm64"
end
  ```
