### ISSUE TITLE
Stripe iOS issue 

### ISSUE THREAD

**Issue by vaibhav13062** [flutter-stripe/flutter_stripe#759]
**Describe the bug**
Facing issue to run app on iOS deployment target is 12.0 still facing this issue.

'maestro' is only available in iOS 12.0 or newer
../ios/Pods/StripeCore/StripeCore/StripeCore/Source/API%20Bindings/StripeAPI.swift:89:46

**Comment by remonh87** [comment]
did you also specify the min version in the podfile: e.g: `platform :ios, '12.0'
`

**Comment by NavneetTechlene** [comment]
**Error**
!] CocoaPods could not find compatible versions for pod "Stripe":
  In Podfile:
    stripe_ios (from `.symlinks/plugins/stripe_ios/ios`) was resolved to 0.0.1, which depends on
      Stripe (~> 22.3.0)

None of your spec sources contain a spec satisfying the dependency: `Stripe (~> 22.3.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
==================================================================== 

 [My Code](https://github.com/NavneetTechlene/stripeExample`)(`https://github.com/NavneetTechlene/stripeExample`)

 1.) using
Xcode Version 13.3.1 (13E500a)
flutter_stripe: ^3.0.2
Flutter 3.0.1• channel stable • https://github.com/flutter/flutter.git

2.) Build for Android success but for iphone

3.) arch -x86_64 pod install  with flutter_stripe: ^3.0.2 above error and with # flutter_stripe: ^3.0.2  in pubspec.yaml i can make ios ipa

**Comment by Jankeelol** [comment]
Deleting the .lock file and running pod install worked for me

**Comment by remonh87** [comment]
thanks for the update!

**Comment by NavneetTechlene** [comment]
> Deleting the .lock file and running pod install worked for me

not working for me

**Comment by sabaridev** [comment]
faced the same issue. did you find any solution @NavneetTechlene

**Comment by Jankeelol** [comment]
a common issue I faced was with the M1 Mac and pod install. 
I recommend verifying you are using iOS 12. or more as minimum requirements,  deleting .lock file, then running `pod install` then `flutter clean` and then `flutter build` or `flutter run`

for M1 (custom Apple CPU chips) possibly checking this might be of help:
[https://stackoverflow.com/questions/68168869/error-when-trying-to-run-my-flutter-app-with-my-m1-mac](url)

**Comment by oliveyew** [comment]
This works for me [here](https://www.udemy.com/course/flutter-in-app-consumable-non-consumable-purchase-2022/?couponCode=NEW_USER_DISCOUNT)

@vaibhav13062 @Jankeelol @sabaridev @NavneetTechlene
