### ISSUE TITLE
Add support for new Order API

### ISSUE THREAD

**Issue by eliezerp3** [flutter-stripe/flutter_stripe#763]
Please add support for the new stripe Order API so can support line items/discounts/stripe tax/shipping address/billing address.

https://stripe.com/docs/orders
https://stripe.com/docs/orders/adding-orders-to-payment-intents

**Comment by remonh87** [comment]
this looks like some backend functionality and I think you can use it already. Just add the order to the payment intent and use our library to pay the intent. OR am I something missing here?

**Comment by eliezerp3** [comment]
Nope. My bad. I thought it was a way to integrate discounts/automatic taxes and other stripe features directly into the payment sheet (like checkout but directly in app) but seems it all has to be done manually and then add total to payment sheet. Thanks anyway

**Comment by eliezerp3** [comment]
@remonh87 I've been trying to get this to work for a bit and can't. I took a working version of payment sheet with payment intent and just changed the paymentIntentClientSecret for the client secret I was getting from creating my order and I keep getting an error that my payment sheet is not initialized (which is the same message you get if have invalid init params).

**Comment by oliveyew** [comment]
@eliezerp3 I added it this way [here](https://www.udemy.com/course/flutter-in-app-consumable-non-consumable-purchase-2022/?couponCode=NEW_USER_DISCOUNT)
