### ISSUE TITLE
Backwards support for flutter 2

### ISSUE THREAD

**Issue by DDavidPrime** [flutter-stripe/flutter_stripe#764]
Hello @remonh87 .

We are currently using flutter 2 with the latest flutter_stripe version of `2.5.0`. We're however experiencing some issues with it which seem to be addressed in the latest version. However we are not able to use the latest version since we'd need to migrate to flutter 3. Due to some dependencies in our project we are stuck with flutter 2, however.

The issue that we (and most of the flutter community) are experiencing is related to nullable and non-nullable instances of some singletons (such as `WidgetsBinding.instance`,...) which happened between the two different flutter versions. There is however [this solution](https://docs.flutter.dev/development/tools/sdk/release-notes/release-notes-3.0.0#your-code) that could help with providing backwards support (for flutter 2), which I think could prove useful for a lot of developers using this package.

**Comment by remonh87** [comment]
Fixed with release 3.1.0 thanks for the fix!
