### ISSUE TITLE
Google pay button showing on Payment Sheet only when testEnv = false

### ISSUE THREAD

**Issue by luchongk** [flutter-stripe/flutter_stripe#767]
I'm using flutter 2.10.5

Google pay button on PaymentSheet does NOT show when googlePay = true AND testEnv = true.
but it DOES show when googlePay = true AND testEnv = false.

I'm trying to get Google's approval to use G pay integration in production mode. But I'm supposed to submit my app while in TEST environment, so the button is supposed to show up when testEnv = true.

I saw other issues talk about AndroidManifest.xml. That didn't work for me, as my problem is specifically when testEnv = true and the other issues were about the button not showing up at all regardless of env value

**Comment by remonh87** [comment]
can you try with latest version? Stripe added lots of exception handling for Google pay. Hopefully we get a meaningful message here so we can triage it further.

**Comment by luchongk** [comment]
Ok so, I tried with version 3.1.0 of flutter_stripe and unfortunately its even worse. There's still no G pay button but now it also looks like this:

![image](https://user-images.githubusercontent.com/11742153/172494257-a91f4bd2-3a7a-4b5d-9367-39bcf09968c2.png)

The logs do show the following error, but I think its more related to the graphical bug than to the Google pay stuff. I'll paste it here anyways, maybe it helps:

````
D/EGL_emulation(11275): app_time_stats: avg=221.93ms min=3.76ms max=2990.00ms count=14
D/EGL_emulation(11275): app_time_stats: avg=92.27ms min=3.65ms max=1406.50ms count=17
D/EGL_emulation(11275): app_time_stats: avg=6.03ms min=3.17ms max=19.05ms count=47
W/Bundle  (11275): Key borderWidth expected Float but value was a java.lang.Integer.  The default value 4.0 was returned.
W/Bundle  (11275): Attempt to cast generated internal exception:
W/Bundle  (11275): java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Float
W/Bundle  (11275): 	at android.os.BaseBundle.getFloat(BaseBundle.java:1145)
W/Bundle  (11275): 	at android.os.Bundle.getFloat(Bundle.java:892)
W/Bundle  (11275): 	at com.reactnativestripesdk.PaymentSheetAppearanceKt.getFloatOr(PaymentSheetAppearance.kt:107)
W/Bundle  (11275): 	at com.reactnativestripesdk.PaymentSheetAppearanceKt.buildShapes(PaymentSheetAppearance.kt:62)
W/Bundle  (11275): 	at com.reactnativestripesdk.PaymentSheetAppearanceKt.buildPaymentSheetAppearance(PaymentSheetAppearance.kt:16)
W/Bundle  (11275): 	at com.reactnativestripesdk.PaymentSheetFragment.onViewCreated(PaymentSheetFragment.kt:63)
W/Bundle  (11275): 	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3019)
W/Bundle  (11275): 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:551)
W/Bundle  (11275): 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
W/Bundle  (11275): 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
W/Bundle  (11275): 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1758)
W/Bundle  (11275): 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
W/Bundle  (11275): 	at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:488)
W/Bundle  (11275): 	at android.os.Handler.handleCallback(Handler.java:938)
W/Bundle  (11275): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/Bundle  (11275): 	at android.os.Looper.loopOnce(Looper.java:201)
W/Bundle  (11275): 	at android.os.Looper.loop(Looper.java:288)
W/Bundle  (11275): 	at android.app.ActivityThread.main(ActivityThread.java:7839)
W/Bundle  (11275): 	at java.lang.reflect.Method.invoke(Native Method)
W/Bundle  (11275): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
W/Bundle  (11275): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
D/EGL_emulation(11275): app_time_stats: avg=921.61ms min=3.02ms max=28421.03ms count=31
D/EGL_emulation(11275): app_time_stats: avg=12.66ms min=3.38ms max=140.13ms count=44
D/EGL_emulation(11275): app_time_stats: avg=7.95ms min=0.97ms max=136.96ms count=44
````

Furthermore, changing testEnv to false does nothing now, everything shows exactly the same as above (including the "TEST MODE" tag).

**Comment by luchongk** [comment]
Ok, first, I'm sorry, I didn't realize there was a new 'appearance' setting for the payment sheet. I commented that out and that brought back the style to how it was before.

But on the other hand, the testEnv variable is still not working. It doesn't do anything.
And the G pay button does not show regardless of any setting I change.

**Comment by jonasbark** [comment]
Did you follow the steps described in https://stripe.com/docs/google-pay?
In particular adjusting the AndroidManifest.xml. 

You can also try to use initGooglePay and presentGooglePay to find out what might be wrong.

**Comment by filipenadai** [comment]
Same issue here...
