### ISSUE TITLE
PaymentMethod Sofort / Klarna not working on Android

### ISSUE THREAD

**Issue by warin123** [flutter-stripe/flutter_stripe#768]
Creating a payment method Sofort / Klarna fails every time on Android with the error 'Card details not complete'. The error message does not make any sense to me as no card details can be provided using those payment methods.

final paymentMethodDataSofort = stripe.PaymentMethodDataSofort(country: 'de');
final paymentMethodSofort = stripe.PaymentMethodParams.sofort(paymentMethodData: paymentMethodDataSofort);
final paymentMethod = await stripe.Stripe.instance.createPaymentMethod(paymentMethodSofort);

**Comment by remonh87** [comment]
can you send me more details about klarna? because for me it is working.  Remember that for klarna you need to provide email and country in the billingdetails

**Comment by warin123** [comment]
I use flutter_stripe: ^3.1.0 and my flutter version is 3.0.1.

```
final billingDetails = BillingDetails(
      email: userEmail,
      address: Address(
        country: userCountry,
        postalCode: '',
        city: '',
        state: '',
        line1: '',
        line2: '',
      ),
    );
final paymentMethod = await Stripe.instance.createPaymentMethod(
      stripe.PaymentMethodParams.klarna(
            paymentMethodData: PaymentMethodData(
                  billingDetails: billingDetails,
       ),
);```

This code runs without any problems on iOS only on android it does not work...

**Comment by remonh87** [comment]
I can reproduce it something is wrong in the plugin on the Android side

**Comment by jonasbark** [comment]
a fix is bound to be released soon https://github.com/stripe/stripe-react-native/pull/987/files
