### ISSUE TITLE
Stripe Financial Connections

### ISSUE THREAD

**Issue by changdaniel** [flutter-stripe/flutter_stripe#769]
**Describe the solution you'd like**
A Flutter implementation for the "[Collect a Financial Connections account](https://stripe.com/docs/financial-connections/other-data-powered-products?platform=web#collect-an-account)" flow, which implements the IOS, Android and Web SDKs.

**Additional context**
Link to associated flows on [Web, IOS and Android](https://stripe.com/docs/financial-connections/other-data-powered-products?platform=web)

**Comment by remonh87** [comment]
Thanks for the feature request. I asked  Stripe what the plans are for implementing this feature. https://github.com/stripe/stripe-react-native/issues/978  .

**Comment by remonh87** [comment]
This is releases in version 5.0.0
