### ISSUE TITLE
(PlatformException(paymentCanceled, User canceled payment authorization, null, null))

### ISSUE THREAD

**Issue by amitmishra7** [flutter-stripe/flutter_stripe#770]
Hi. I have initialised all the required params as required in the package. Still I am facing this issue. I am able to run it successfully on emulator but only getting this on real device. (iPhone X 15.4.1)

**To Reproduce**

```
Stripe.merchantIdentifier=MERCHANT_ID;
Stripe.publishableKey=PUBLISHABLE_KEY;
 
await Stripe.instance.applySettings();
```

**Expected behavior**
The transaction is never complete. Whenever I pass name and last name, it asks to double click to complete payment. After that I get this error. I have tested using the sandbox user from US region. 

**Smartphone / tablet**
 - Device: Iphone X

**Additional Info**
Below is my apple_pay.json in the assets folder. 

`{
  "provider": "apple_pay",
  "data": {
    "merchantIdentifier": "xxx.xxx.xxx.xxx",
    "displayName": "My Awesome Project",
    "merchantCapabilities": [
      "3DS",
      "debit",
      "credit"
    ],
    "supportedNetworks": [
      "amex",
      "visa",
      "discover",
      "masterCard"
    ],
    "countryCode": "US",
    "currencyCode": "USD",
    "requiredBillingContactFields": ["post"],
    "requiredShippingContactFields": ["post", "phone", "email", "name"]
  }
}`

**Comment by remonh87** [comment]
Did you follow the steps as described in: https://github.com/flutter-stripe/flutter_stripe/blob/61ecb7c52a09b57f675e54c2f9b3273a36020838/example/lib/screens/wallets/apple_pay_screen_plugin.dart#L77 ?

**Comment by amitmishraxendit** [comment]
I have already tried it. But that didn't work. 

```
void onApplePayResult(paymentResult) async {
    print("apple pay token");
    var token;
   
    final tokenID =
        await stripe.Stripe.instance.createApplePayToken(paymentResult);
    print(tokenID.id);
    token = tokenID.id;
}
```

**Comment by jonasbark** [comment]
Closing this due to lack of response
