### ISSUE TITLE
Activity doesn't exist yet. You can safely retry this method.

### ISSUE THREAD

**Issue by ShwetaChauhan18** [flutter-stripe/flutter_stripe#771]
**Describe the bug**
After updating version "3.1.0", getting below error.

Error: StripeException(error: LocalizedErrorMessage(code: FailureCode.Failed, localizedMessage: null, message: Activity doesn't exist yet. You can safely retry this method., stripeErrorCode: null, declineCode: null, type: null))

**To Reproduce**
1. Update stripe version
2. Create payment method
3. On confirm payment
4. Getting error: Error: StripeException(error: LocalizedErrorMessage(code: FailureCode.Failed, localizedMessage: null, message: Activity doesn't exist yet. You can safely retry this method., stripeErrorCode: null, declineCode: null, type: null))

**Expected behavior**
It should works as it's work previously.

**Smartphone / tablet**
 - Device: [Android emulator]
 - OS: [Android 10]
 - Package version: [3.1.0]
 - Flutter version [3.0.0.]

**Comment by loicgeek** [comment]
I am also having this issue:
```
 flutter_stripe: ^3.1.0
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.1 21C52 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.67.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!

```

**Comment by jonasbark** [comment]
Does is still work for you on Version 3.0?
Please provide a reproducible example app or code

**Comment by ShwetaChauhan18** [comment]
I have same case which @juleshyacinthe describe.

It's happens when we confirm payment using intent's secret and for this I am using `CardField` and `Stripe.instance.createPaymentMethod`, and sending the payment method details to my server.

**Comment by kekko7072** [comment]
+ 1

**Comment by ShwetaChauhan18** [comment]
Any solution??

**Comment by n3rdkid** [comment]
Facing the same issue while using `handleNextAction` for 3d Secure.

**Comment by easeccy** [comment]
Having the same issue on `confirmSetupIntent`.

**Comment by accek-cosmose** [comment]
It looks like in [quite a few places `stripe-react-native` casts `context.currentActivity` to `AppCompatActivity`](https://github.com/stripe/stripe-react-native/search?q=AppCompatActivity) to access the fragment manager. It looks like with the newest Flutter, its `FlutterFragmentActivity` is not a subclass of `AppCompatActivity` and these casts probably should be changed to `FragmentActivity`.

**Comment by loicgeek** [comment]
this code produce that error: 
```
 const billingDetails = BillingDetails(
                    email: 'ngounoubosseloic@gmail.com',
                    phone: '+48888000888',
                    address: Address(
                      city: 'Houston',
                      country: 'US',
                      line1: '1459  Circle Drive',
                      line2: '',
                      state: 'Texas',
                      postalCode: '77063',
                    ),
                  );

                  var subscriptionsRepository =
                      locator.get<SubscriptionsRepository>();

                  String clientSecret =
                      await subscriptionsRepository.getUserClientSecret();

                  var setupIntent = await Stripe.instance.confirmSetupIntent(
                    clientSecret,
                    const PaymentMethodParams.card(
                      paymentMethodData: PaymentMethodData(
                        billingDetails: billingDetails,
                      ),
                    ),
                  );

                  // create payment method
                  final paymentMethod = setupIntent.paymentMethodId;

```

**Comment by SlickSlime** [comment]
@kekko7072 downgrading to `3.0.0` worked for me. I also had to explicitly set `stripe_android` and other stripe packages in `pubspec.lock` to `3.0.0` too.

**Comment by kekko7072** [comment]
> @kekko7072 downgrading to `3.0.0` worked for me. I also had to explicitly set `stripe_android` and other stripe packages in `pubspec.lock` to `3.0.0` too. 

I was trying to downgrade oy on pubspec.yaml file and it was not working then I went back to the previous git commit and I saw that I need to change the Android as you mentioned, but I'm particular were I need to change them?

**Comment by ShwetaChauhan18** [comment]
I still not able to complete payment after downgrading version to 3.0.0.

Getting below error:

```
../../flutter/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_stripe-3.0.0/lib/src/stripe.dart:276:27: Error: The method 'handleCardAction' isn't defined for the class 'StripePlatform'.
 - 'StripePlatform' is from 'package:stripe_platform_interface/src/stripe_platform_interface.dart' ('../../flutter/flutter/.pub-cache/hosted/pub.dartlang.org/stripe_platform_interface-3.1.0/lib/src/stripe_platform_interface.dart').
Try correcting the name to the name of an existing method, or defining a method named 'handleCardAction'.
          await _platform.handleCardAction(paymentIntentClientSecret);
```

**Comment by jonasbark** [comment]
Fixed with stripe_android 3.1.1

**Comment by jjsebastianfuertes** [comment]
Any idea when 3.1.1 will be ready to consume?

**Comment by jonasbark** [comment]
it is ready. You just need to update stripe_android to it. 
`flutter packages pub update stripe_android`

**Comment by MaksimZdanchuk** [comment]
confirmSetupIntent stripe error when u used test card once for payment.

**Comment by accek-cosmose** [comment]
> it is ready. You just need to update stripe_android to it. `flutter packages pub update stripe_android`

3.1.1 does not seem to be published yet, we don't see it in pub.dev, and `flutter pub get` doesn't see it either:

```
❯ flutter pub get
Because example depends on flutter_stripe ^3.1.1 which doesn't match any versions, version solving failed.
```

Any idea, when it would be available?

**Comment by jonasbark** [comment]
only stripe_android was updated - flutter_stripe remains on 3.1.0.

**Comment by loicgeek** [comment]
@accek-cosmose  use dependecies overrides for stripe_android only

**Comment by Profhameed** [comment]
still facing the same problem with 3DS2.

**Comment by Profhameed** [comment]
handleNextAction returns "StripeException(error: LocalizedErrorMessage(code: FailureCode.Canceled, localizedMessage: null, message: null, stripeErrorCode: null, declineCode: null, type: null))" with 3DS2

**Comment by oliveyew** [comment]
Checkout this easy way [here](https://www.udemy.com/course/flutter-in-app-consumable-non-consumable-purchase-2022/?couponCode=NEW_USER_DISCOUNT)

@Profhameed @loicgeek @accek-cosmose @MaksimZdanchuk @jjsebastianfuertes

**Comment by AskAnkit** [comment]
I am using pay plugin and stripe together and this is i am getting when i tried to call
`await Stripe.instance.createApplePayToken(paymentResult);`

StripeException(error: LocalizedErrorMessage(code: FailureCode.Failed, localizedMessage: There was an unexpected error -- try again in a few seconds, message: There was an unexpected error -- try again in a few seconds, stripeErrorCode: null, declineCode: null, type: null))

**Comment by hateshkumar** [comment]
> I am using pay plugin and stripe together and this is i am getting when i tried to call `await Stripe.instance.createApplePayToken(paymentResult);`
> 
> StripeException(error: LocalizedErrorMessage(code: FailureCode.Failed, localizedMessage: There was an unexpected error -- try again in a few seconds, message: There was an unexpected error -- try again in a few seconds, stripeErrorCode: null, declineCode: null, type: null))

same issues I am facing
