### ISSUE TITLE
Can I find logs related to Stripe SDK ?

### ISSUE THREAD

**Issue by Rioverde** [flutter-stripe/flutter_stripe#775]
Stripe Engineer Responded me about this issue:
https://github.com/flutter-stripe/flutter_stripe/issues/720
in following way

Thank you for providing more details. I'm checking the log but it seems like the underlying error isn't present here.
The error log is basically stripe-flutter plugin saying something went wrong, it doesn't exactly mention what went wrong and why the payment was cancelled.

I'm happy to look into it further once we can narrow down on the error thrown by Stripe's SDK (not stripe-flutter).
However, you'd need to work with the plugin developer to get there.

Let me know if you have any follow up questions :)
John M.

Is there any way I can find deeper logs related to Stripe SDK ?

**Comment by remonh87** [comment]
I really do not know what he means by deeper logs. If you run it on Android you can see some logcat output that the stripe sdk shows. Maybe you need to send him this? We use the react native sdk output and every action will result in a success or error. In case of an error this is what we show.

**Comment by jonasbark** [comment]
Closing this due to lack of response
