### ISSUE TITLE
Why you are using Tencent TBS SDK? Please everybody report this package. Don't use this.

### ISSUE THREAD

**Issue by ABmamunHoneybee** [flutter-stripe/flutter_stripe#782]
For this package google play store always rejected our apps.
You are all Mother F*****K.

**Comment by remonh87** [comment]
We do not use tencent in our sdk only you can add for wechat pay. Before becoming so aggressive just file an a support ticket and we always help you out. btw I will report your abusive content to GitHub . Have a nice day

**Comment by oliveyew** [comment]
This new way works for me [here](https://www.udemy.com/course/flutter-in-app-consumable-non-consumable-purchase-2022/?couponCode=NEW_USER_DISCOUNT)


@ABmamunHoneybee
