### ISSUE TITLE
Tax calculation in Flutter

### ISSUE THREAD

**Issue by krosigkm** [flutter-stripe/flutter_stripe#783]
Hi, I am using flutter_stripe to process payments in Flutter but I cannot work out how to enable the tax calculation. Shouldn't there be a parameter in "SetupPaymentSheetParameters" through which I can add this? 
Thank you for your help!

**Comment by krosigkm** [comment]
Thank you for your help!

**Comment by remonh87** [comment]
Thanks @eliezerp3  for answering this question. will close it for now.

**Comment by eliezerp3** [comment]
@remonh87 No problem. Any way you can take a look at #791 as doesn’t seem order API beta is currently supported with this package

**Comment by krosigkm** [comment]
Thank you, I will check it out!

**Comment by oliveyew** [comment]
This new way works for me [here](https://www.udemy.com/course/flutter-in-app-consumable-non-consumable-purchase-2022/?couponCode=NEW_USER_DISCOUNT)

@eliezerp3 @krosigkm

**Comment by krosigkm** [comment]
Thanks for the tip! Is this your course?
