### ISSUE TITLE
Activity doesn't exist yet. You can safely retry this method. 

### ISSUE THREAD

**Issue by MalikTuseef** [flutter-stripe/flutter_stripe#789]
await Stripe.instance.confirmSetupIntent(
        clientSecret!,
        PaymentMethodParams.card(
            paymentMethodData: PaymentMethodData(
              billingDetails: BillingDetails(name: fullName),
            ),
            options: const PaymentMethodOptions(
                setupFutureUsage: PaymentIntentsFutureUsage.OffSession)),
      );

device detail:
Mi poco m3 pro
android 12

Main Activity:

class MainActivity: FlutterFragmentActivity() {
}

style.xml(values, values-night,values-31):

 <style name="NormalTheme" parent="Theme.MaterialComponents">
        <item name="android:windowBackground">?android:colorBackground</item>
    </style>

build.gradle:
    ext.kotlin_version = '1.5.31'

 dependencies {
        classpath 'com.android.tools.build:gradle:4.2.2'
        //......
    }

gradle-wrapper.properties

distributionUrl=https\://services.gradle.org/distributions/gradle-6.7.1-all.zip

**Comment by jonasbark** [comment]
https://github.com/flutter-stripe/flutter_stripe/issues/771

**Comment by MalikTuseef** [comment]
thx its upgrade android-stripe version to solve my problem

**Comment by oliveyew** [comment]
@hayahyts i found a easy way to add stripe [here](https://www.udemy.com/course/stripe-one-time-payment-subscription-in-flutter-app-2022/?couponCode=NEW_USER_DISCOUNT)
