### ISSUE TITLE
confirmPayment can't be false

### ISSUE THREAD

**Issue by LastxTemplar** [flutter-stripe/flutter_stripe#79]
**Describe the bug**
setting the `confirmPayment` parameter to false results in the Payment Sheet not appearing on the screen and no errors appearing in the console.
```
await Stripe.instance.presentPaymentSheet(
    parameters: PresentPaymentSheetParameters(
        clientSecret: _paymentSheetData['paymentIntentClientSecret'],
        confirmPayment: false,
    )
);
```

**To Reproduce**
Use the Payment Sheet method in the example app provided by the package and change the `confirmPayment` parameter to false

**Expected behavior**
The payment sheet should appear as usual in order to input the card details

**Smartphone / tablet**
 - Device: Pixel 4 XL
 - OS: Android 11
 - Package version: flutter_stripe: ^1.0.1+2
 - Flutter version: Flutter 2.0.6 • channel stable

**Comment by remonh87** [comment]
Good catch we found out that the parameters: 
`confirmPayment` on present paymentsheet and `customFlow` on initPaymentSheet need to be in sync.

So you need to make sure of the following:
if `customFlow = true` then `confirmPayment = false`
if `customFlow = false` then `confirmPayment = true`

We will update the docs and add an assert.
