### ISSUE TITLE
CardField Widget issue for UI

### ISSUE THREAD

**Issue by pg598595** [flutter-stripe/flutter_stripe#790]
**Screen view getting Blur when using CardField Widget**
I am trying to used CardField to add a Card from Stripe, but when I use this Widget the background view gets blurred.
Also, I want to make the Card field Come in the next line with custom UI, Is there any way possible for that? 

**To Reproduce**
![imgpsh_fullsize_anim](https://user-images.githubusercontent.com/25722093/173892156-49e90c7c-da72-41f5-a97e-e4f3237b349e.jpeg)

1. Add CardField Widget in the UI

**Smartphone / tablet**
 - Device: [e.g. iPhone X]
 - OS: [e.g. iOS 13, Android 10]
 - Package version: 2.5.0
 - Flutter version 2.5.3

Can anyone please help with this issue?

**Comment by remonh87** [comment]
Can you give me the code of how you initialise the cardfield? It looks like you open it in a modal...

**Comment by pg598595** [comment]
Hello @remonh87, 
Here is the code how I have used the CardField in the View.
I am displaying this Widget in Dialog.

Widget card() {
    return ConstrainedBox(
      constraints:
          BoxConstraints(maxHeight: double.infinity, maxWidth: double.infinity),
      child: Container(
        padding: EdgeInsets.only(top: 0),
        margin: EdgeInsets.only(top: 0),
        decoration: BoxDecoration(
          color: Colors.white,
          shape: BoxShape.rectangle,
        ),
        child: Form(
          key: _formKey,
          child: Column(
            mainAxisSize: MainAxisSize.min, // To make the card compact
            children: <Widget>[
              SizedBox(height: 10),
              Container(
                padding: EdgeInsets.only(left: 0.0, right: 0.0),
                child: Column(
                  children: [
                    Row(
                      children: [
                        GestureDetector(
                          onTap: () {
                            Navigator.pop(context);
                          },
                          child: Padding(
                            padding: const EdgeInsets.only(right: 10),
                            child: Icon(
                              Icons.clear,
                              color: Colors.black,
                              size: 30,
                            ),
                          ),
                        ),
                      ],
                      mainAxisAlignment: MainAxisAlignment.end,
                    ),
                    SizedBox(height: 15),
                   
                    CardField(
                      decoration: InputDecoration(),
                      enablePostalCode: true,
                      dangerouslyGetFullCardDetails: true,
                      onCardChanged: (card) {
                        print(card);
                      },
                    ),
                    TextButton(
                      onPressed: () async {
                        // create payment method
                        final paymentMethod = await Stripe.instance
                            .createPaymentMethod(PaymentMethodParams.card());
                        print("Payment Method is ==== $paymentMethod");
                      },
                      child: Text('pay'),
                    ),
                    getCancelSubmitButtons(context),
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

**Comment by jonasbark** [comment]
Hi! Based on your code alone I've been unable to reproduce this, as the 'blurring' code is missing. Even if it would be available your issue would be unrelated to the plugin.

**Comment by oliveyew** [comment]
hi, @pg598595 i found a easy way to do it [here](https://www.udemy.com/course/stripe-one-time-payment-subscription-in-flutter-app-2022/?couponCode=NEW_USER_DISCOUNT)
