### ISSUE TITLE
Use beta version of stripe

### ISSUE THREAD

**Issue by eliezerp3** [flutter-stripe/flutter_stripe#791]
Hi. I’m trying to migrate from the payment intent api to the new order api. I passed in the order client secret instead of the payment intent client secret but I am getting an error that payment sheet wasn’t initialized. I am thinking the issue may be that I have to explicitly use the beta version of the stripe api as shown [here](https://stripe.com/docs/orders/quickstart) 

`
const stripe = Stripe("pk…", {
  betas: ["process_order_beta_1"],
  apiVersion: "2020-08-27; orders_beta=v3"
});
`

Is there any way to change the api version?

[I am not positive if this is what is causing the issue but it is the only thing I can think of]

**Comment by jonasbark** [comment]
Hi! There's no way to change the API version, as it's dependent on the Android + iOS native libraries and what they are using.

**Comment by oliveyew** [comment]
@eliezerp3  You can try this new approach [here](https://www.udemy.com/course/stripe-one-time-payment-subscription-in-flutter-app-2022/?couponCode=NEW_USER_DISCOUNT)

**Comment by eliezerp3** [comment]
@jonasbark I would recommend you ban @oliveyew from posting (if ur able to); he has been spamming a link to his udemy course on every issue in this package.
