### ISSUE TITLE
P24 not showing up on IOS

### ISSUE THREAD

**Issue by juliuszmandrosz** [flutter-stripe/flutter_stripe#796]
Hi, I am creating payment intent with card and P24 as payment methods. On Android everything works fine and I can see P24 method, however on IOS it is not showing up, I will be grateful for any help!

<img width="305" alt="image" src="https://user-images.githubusercontent.com/59540350/174312794-d175e363-a7b6-4bb4-b99a-5451fc0bf06e.png">

<img width="231" alt="image" src="https://user-images.githubusercontent.com/59540350/174313842-9cdf98a8-86de-4e85-9234-3023f297d203.png">

<img width="573" alt="image" src="https://user-images.githubusercontent.com/59540350/174312957-395d5827-a03c-41a2-a0b6-b3b769f8f930.png">

<img width="595" alt="image" src="https://user-images.githubusercontent.com/59540350/174313716-468e6116-6bb3-4ece-a4d0-c870d15ce880.png">

**To Reproduce**
1. Add P24 to payment methods creating payment intent in API
2. Present payment sheet on client side

**Expected behavior**
Payment sheet should show P24 payment method

 - Device: Iphone SE Simulator
 - OS: IOS 15.5
 - Package version: 3.1.0
 - Flutter version 3.0.2

**Comment by remonh87** [comment]
Thank you for the excellent problem description. I can reproduce the behavior and I see a crash on iOS  related to this. I will create a ticket on the stripe sdk repo.

**Comment by grzesebe** [comment]
Hi, I have exact same issue using https://github.com/capacitor-community/stripe
I've changed stripe pod version to 21.13.0. It should be compatible with p24 but it didn't help.

Only using p24

**Comment by remonh87** [comment]
So I got it working when you specify a return url in the `initPaymentSheet` parameters. This is a workaround for the time being . 

Example: 

```dart
await Stripe.instance.initPaymentSheet(
        paymentSheetParameters: SetupPaymentSheetParameters(
          // Main params
          paymentIntentClientSecret: data['paymentIntent'],
          merchantDisplayName: 'Flutter Stripe Store Demo',
          // Customer params
          customerId: data['customer'],
          returnURL: 'flutterstripe://safepay',
}
```

**Comment by juliuszmandrosz** [comment]
Thank you, it works perfectly. By the way, what this parameter is responsible for? The documentation does not explain much about it

**Comment by remonh87** [comment]
The return url is: to redirect your customer back to after they authenticate or cancel their payment on the payment method’s app or site. For example on P24 and also iDeal you will enter an external web page where the customer handles the payment. When completed you ideally want to close the webview and make the user return to your app.

**Comment by remonh87** [comment]
Did you also add the deeplink in flutter like: https://docs.flutter.dev/development/ui/navigation/deep-linking ?

**Comment by juliuszmandrosz** [comment]
Yes, I did it, but the problem is not with the app itself, when payment is successful I can just see infinite loader on P24 page

**Comment by remonh87** [comment]
last versions (try 5.0.0) incorporated some fixes for deeplinking if the issue still persists ping me and I will further investigate it.
