### ISSUE TITLE
PaymentMethod.fromJson - Deserializing issue

### ISSUE THREAD

**Issue by cosmoarunn** [flutter-stripe/flutter_stripe#799]
This is in relation to the issue [](https://github.com/flutter-stripe/flutter_stripe/issues/81)

I tried hard casting to typos but after the following

          pmMethod['billingDetails'] = pmMethod['billing_details'];
          pmMethod['Card'] = pmMethod['card'];

 i still get an error on SepaDebit which is not in my payment method list.
          `new _$_SepaDebit.fromJson (package:stripe_platform_interface/src/models/payment_methods.freezed.dart:1949:7)`

I'am using 3.1.0 and I also tried 2.5.0.

Here's the code block 

```
try {
      final results = await jsonDecode(response.body);
      final _paymentMethods = results['payment_methods'];

      List<PaymentMethod> _paymentMethodsList = _paymentMethods.map((pmMethod) {
        
        if (pmMethod['billing_details'] != null) {
          //pmMethod['billingDetails'] = pmMethod['billing_details'];
          //pmMethod['Card'] = pmMethod['card'];
        }
        return PaymentMethod.fromJson(pmMethod);
      }).toList();

    } on FormatException catch (_, fe) {
      print("**** Format Exception caught ****");
      return [];
    }
```

could someone help me please, where it's gone wrong?

**Comment by jonasbark** [comment]
The model classes are for internal plugin use only. You'll need to adjust your server code or parse it using your own model classes.
