### ISSUE TITLE
Support custom fonts in CardField

### ISSUE THREAD

**Issue by tudor07** [flutter-stripe/flutter_stripe#80]
Custom fonts are not working in `CardField` widget.

```
CardField(
  style: const TextStyle(
        fontFamily: 'my-custom-font', // <- not working
      ),
),
```

**Comment by jamesblasco** [comment]
Only color and fontSize are the only params available right now for customizing the card.

We are now focused on fixing issues and making the package the most stable possible. After i will try to work on this. 

Will keep this open to see the demand

**Comment by tudor07** [comment]
@jamesblasco Please consider giving this a higher priority. A lot of apps are using custom fonts, not many that use the default. It's very easy for the user to notice that the card input looks different than everything else in the app. This has a big negative impact since that's the step when they give their money so it's really important for them to feel safe and have trust.

**Comment by jonasbark** [comment]
Font Family can now be adjusted with the Style attribute: 
https://github.com/flutter-stripe/flutter_stripe/blob/main/packages/stripe/lib/src/widgets/card_field.dart#L19
Please test it :)

**Comment by tudor07** [comment]
@jonasbark it does not work. It still uses the default font. I am using version `1.1.0`.

**Comment by jonasbark** [comment]
@tudor07 please share more details, such as the fontfamily you're trying to use and the device you're testing it

**Comment by jamesblasco** [comment]
Indeed it is not implemented for iOS. I will reopen and assign it to myself

**Comment by remonh87** [comment]
@jamesblasco  I think in the latest version we said it cannot work for iOS right? can you confirm and close it?

**Comment by remonh87** [comment]
Closed for now as I do not see how we can fix this properly on iOS. It is a lmitation we have to live with for now .

**Comment by iampato** [comment]
Could this also be added on `CardFormField` ?
