### ISSUE TITLE
Flutter Checkout Success / Cancel URLs encode hashtags (#) as %23. 

### ISSUE THREAD

**Issue by xErik** [flutter-stripe/flutter_stripe#800]
**Describe the bug**

Flutter Checkout Success / Cancel URLs encode hashtags (#) as %23. 

But Flutter Web expects URLs with an hashtag (#).

**To Reproduce**

```
flutter_stripe: ^3.1.0
flutter_stripe_web: ^1.1.0
stripe_checkout: ^1.0.0
```

```dart
import 'package:flutter_stripe/flutter_stripe.dart';
import 'package:stripe_checkout/stripe_checkout.dart';

final result = await redirectToCheckout(  
  context: context,
  sessionId: sessionId,
  publishableKey: Stripe.publishableKey,
  successUrl: 'http://example.com/#/payment/stripe/success',
  canceledUrl: 'http://example.com/#/payment/stripe/cancel',
    );
```

Upon success, Stripe returns to this URL:

`http://example.com/%23/payment/stripe/success`

**Expected behavior**

Upon success, Stripe should return to this URL:

`http://example.com/#/payment/stripe/success`

**Smartphone / tablet**

Chrome Desktop Browser.

**Additional context**

**Comment by jonasbark** [comment]
Hi! This is a server issue. stripe_checkout never sets the success or canceled URL. You'll need to adjust your server logic to send the correct URLs via Checkout.

**Comment by xErik** [comment]
The only elements involved in this step are the Flutter plugin and Stripe server. 

I only generate the `sessionId` on the Firebase server before this step.
