### ISSUE TITLE
Card details not complete on Android (ok on ios)

### ISSUE THREAD

**Issue by davemg3** [flutter-stripe/flutter_stripe#808]
**Describe the bug**

> Error StripeException(error: LocalizedErrorMessage(code: FailureCode.Failed, localizedMessage: Card details not complete, message: Card details not complete, stripeErrorCode: null, declineCode: null, type: null))

Error on Android (ok on ios) since version 3.1.0 (everything was ok in version 2.5.0)

In my case i let the user save some cards and later on I list them in order to select one to achieve payment
Payment method creation, PaymentIntent creation and confirmation are done on client app (seems it is not covered on your 4 examples).

(By the way : 
I feel the 4 below Repository examples usage are not clear and need some clarification on objectives and what is called webhook (is it Stripe webhook? ) 

> custom_card_payment_screen.dart
> no_webhook_payment_cardform_screen.dart
> no_webhook_payment_screen.dart
> webhook_payment_screen.dart)

**To Reproduce**
  // 1. I Gather customer billing information (ex. email) on client app
```
` final billingDetails = BillingDetails(
        email: 'email@stripe.com',
        phone: '+48888000888',
        address: Address(
          city: 'Houston',
          country: 'US',
          line1: '1459  Circle Drive',
          line2: '',
          state: 'Texas',
          postalCode: '77063',
        ),
      );`
```
  // 2. I create paymentMethodParams on client app
```
`  context.read<PaymentData>().paymentMethodParams =
          PaymentMethodParams.card(
        options: PaymentMethodOptions(
            setupFutureUsage: PaymentIntentsFutureUsage.OnSession),
        paymentMethodData: PaymentMethodData(billingDetails: billingDetails),
      );

```
  // 3. I create paymentMethod on client
```
      final paymentMethod = await Stripe.instance.createPaymentMethod(
          context.read<PaymentData>().paymentMethodParams!);`
```

//4 I save PaymentMethod on server for later usage : 
```
`  const setupIntent = await stripe.setupIntents.create({
                payment_method_types: ['card'],
                customer: stripeCustomerId,
                payment_method: paymentMethId,
                usage: 'on_session',
            });`

```
Later  on : 
//5 i call getCustomerPaymentMethodsList later on to get all the customer payment method , for one to be selected : 
```
` const paymentMethods = await stripe.paymentMethods.list({
      customer: stripeCustomerId,
      type: 'card',
    });`
```

--- from this section all the code is the same as your code is NoWebHookPaymentScreen

//6 . after one payment method is selected, i call API to create PaymentIntent
   
```
 Map<String, dynamic> paymentIntentResult = await createPaymentIntent(
          paymentMethodId: paymentMethod.id,
          customerId: context.read<Customer>().id,
          amount: 25,
          currency: context.read<PaymentData>().currency);
      if (paymentIntentResult['error'] != null) {
        // Error during creating or confirming Intent
        ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(content: Text('Error: ${paymentIntentResult['error']}')));
        return;
      }
```

and after all check, i confirm with 
```
`final paymentIntent =
                              await Stripe.instance.confirmPayment(
                            paymentIntentSecret!,
                            paymentMethodParams!,`
```

The only weird thing done as i dont  create cards in the same moment i want to use them is that : 
 paymentMethodParams is needed when creating payment method at the beginning 'createPaymentMethod'
> paymentMethodParams =
          PaymentMethodParams.card(
        options: PaymentMethodOptions(
            setupFutureUsage: PaymentIntentsFutureUsage.OnSession),
        paymentMethodData: PaymentMethodData(billingDetails: billingDetails),
      )

 paymentMethodParams is again needed as requested as argument when i 'confirmPayment'
>  paymentMethodParams =
          PaymentMethodParams.card(
        options: PaymentMethodOptions(
            setupFutureUsage: PaymentIntentsFutureUsage.OnSession),
        paymentMethodData: PaymentMethodData(billingDetails: billingDetails),
      )

Flutter doctor : 
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.4 21F79 darwin-x64, locale en-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.68.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

**Comment by jonasbark** [comment]
Can you try version 3.2.0?

**Comment by davemg3** [comment]
@jonasbark , i am sorry but the bug is still open...
ok on IOS, not working on Android
Can you point me in a direction of investigation?

**Comment by davemg3** [comment]
@jonasbark , i have noticed something i didnt have before 3.2.0 on Android but might still direct your investigation.

**Comment by oliveyew** [comment]
@davemg3 you can try this new approach [link](https://www.udemy.com/course/stripe-one-time-payment-subscription-in-flutter-app-2022/?couponCode=NEW_USER_DISCOUNT)

**Comment by bubbler3** [comment]
@jonasbark , this issue is still open and should not be closed yet...do you have any direction in thought to look for the bug?

**Comment by davemg3** [comment]
@romatallinn, @jonasbark 
Since version 4.0.0 and resolution of https://github.com/flutter-stripe/flutter_stripe/issues/792 , the "card details not complet on Android" error disappear with above code for straight payment but still there with setup payment (code was working on previous 3.1.0 version)
Did you happen to make it work with setup intent?

**Comment by romatallinn** [comment]
> Did you happen to make it work with setup intent?

Yes, I am using it for Setup Intents. Seems to work. Have a look at #382, coz it was a problem for me that was uncovered after the problem that 4.0.0 solves.

**Comment by davemg3** [comment]
@romatallinn 
When saving a card on a `Add a Card Screen`
- From my client I create paymentMethodParams with billingDetails
- From my client i create payment method,  save it on  my server which send me back a setup intent secret
- From my client i confirm the setup intent with secret and paymentMethodParams  

When using a card later on a` Payment Screen`
- From my client I get the paymentMethod from a list of payment method from my server which retrieves it from stripe using stripeCustomerId
- From my client I need to create again paymentMethodParams with billingDetails ( as it is needed below)
- From my client I call creation of PaymentIntent on my server and get a secret with action (in Europe, it requests me confirmation)
- From my client I confirmPayment with secret and paymentMethodParams

I get sure this time to have all steps for `Payment Screen` to be managed by button into the widget tree and not using a bottom sheet or dialog.
And it gives me the exception `Card details not complete.`

It makes me crazy as i know this code was working before version 3.3.0
As said above, it is working currently if i create card for an immediate payment as in the code examples

Is your implementation similar?
