### ISSUE TITLE
Disable paymentMethod removal when there is an active setupIntent with that paymentMethod

### ISSUE THREAD

**Issue by SpoonJoon** [flutter-stripe/flutter_stripe#818]
**Is your feature request related to a problem? (please describe)**
I am trying to save a payment method within a setup intent. But I noticed that when a payment method is deleted via the edit button on the payment sheet, it automatically detaches the payment method from the customer as well as the live setup intent. Which disables the ability to charge the user later on

**Describe the solution you'd like**
Alike the checkout process, to stop the detachment of all the payment methods for a customer and leave at least one payment method if there is an active setup intent using that payment method.

**Describe alternatives you've considered**
Disabling the edit button on the payment sheet, migrating to checkout.

**Additional context**
The process of detaching a payment method with a live setup intent
![Simulator Screen Shot - iPhone 13 - 2022-07-01 at 11 48 48](https://user-images.githubusercontent.com/54812775/176946654-f117cb53-1791-4b48-9ae7-bdc8a730d385.png)
![Simulator Screen Shot - iPhone 13 - 2022-07-01 at 11 48 40](https://user-images.githubusercontent.com/54812775/176946660-aee58228-9311-4695-8bb2-8e2d8e081a51.png)
![Simulator Screen Shot - iPhone 13 - 2022-07-01 at 11 48 28](https://user-images.githubusercontent.com/54812775/176946664-8a63a3b7-b899-4d0f-bc26-4e8229986636.png)
![Simulator Screen Shot - iPhone 13 - 2022-07-01 at 11 48 19](https://user-images.githubusercontent.com/54812775/176946666-51df62a8-6544-4321-97ba-333dcab1e17f.png)

**Comment by jonasbark** [comment]
The payment sheet is out of control of our plugin - we don't have any means of adjusting that behavior.

I recommend contacting Stripe support or opening an issue at https://github.com/stripe/stripe-android/ or https://github.com/stripe/stripe-ios/

**Comment by oliveyew** [comment]
Hi @SpoonJoon you can try this way [here](https://www.udemy.com/course/stripe-one-time-payment-subscription-in-flutter-app-2022/?couponCode=NEW_USER_DISCOUNT)

**Comment by SpoonJoon** [comment]
@oliveyew neither really fits my need, I could just implement stripes checkout as a webview.

**Comment by SpoonJoon** [comment]
@jonasbark Thanks, Stripe support also suggested I do the same as your suggestion.
