### ISSUE TITLE
(PlatformException(Failed, Payment not completed, null, null))

### ISSUE THREAD

**Issue by ShwetaChauhan18** [flutter-stripe/flutter_stripe#823]
Hi. I have initialised all the required params as required in the package. Still I am facing this issue. I am able to run it successfully on emulator but only getting this on real device. 

```
void initStripe() async {
    Stripe.publishableKey = PUBLISHABLE_KEY;
    Stripe.merchantIdentifier = MERCHANT_ID;

    await Stripe.instance.applySettings();
 }
```

Also, I my app is going to live so, I have followed below step. 

- [Register for an Apple Merchant ID](https://stripe.com/docs/apple-pay#merchantid)
- [Create a new Apple Pay certificate](https://stripe.com/docs/apple-pay#csr)
- [Integrate with Xcode](https://stripe.com/docs/apple-pay#setup)

**To Reproduce**
1. Add ApplePayButton.
2. presentApplePay on click of button with require data
3. Get clientSecret from server
4. confirmApplePayPayment using clientSecret or prndingSentupIntent

**Expected behavior**

**Smartphone / tablet**
 - Device: [iPhone XS]
 - OS: [iOS 15.5]
 - Package version: [3.2.0]
 - Flutter version [3.0.0.]

**Some code**

1. presentApplePay on click of button

```
await Stripe.instance.presentApplePay(
        ApplePayPresentParams(
          cartItems: [
            ApplePayCartSummaryItem(
              label: "name", 
              amount: "500.0",
            ),
          ],
          shippingMethods: [
            ApplePayShippingMethod(
              amount: "500.0",
              identifier: MERCHANT_ID,
              label: "name",       
            )
          ],
          country: AppConstants.countryCodeISO,
          currency: currency,
        ),
      );
```

2. Confirm ApplePay with clientSecret

```
 Future<void> confirmApplePayPayment(
      BuildContext context, String clientSecret) async {
    try {
      await Stripe.instance.confirmApplePayPayment(clientSecret);
    } on Exception catch (stripeException) {
      if (stripeException is StripeException) {
        debugLog('Error7: $stripeException');
      } else {
        debugLog('Error8: $stripeException');
      }
    }
  }
```

**Comment by ShwetaChauhan18** [comment]
Yes, I already did. Recently, I found for our US user it's working fine.

**Comment by efraespada** [comment]
This is still happening in iOS. Please reopen this issue.

Version: 6.0.0

**Comment by remonh87** [comment]
@efraespada  please provide a reproducable scenario so we can help you out. Did you buy any chance add a shipping address to apple pay? If so this will be fixed in the next release

**Comment by efraespada** [comment]
@remonh87 

I'm doing all the tests with a real iPhone SE.

I've already added a test credit card to my sandbox test account. The shipping info was configured too.

Everything is ready to proceed with the payment 👌🏼 

When tapping with the finger, looks like the payment is being processed but the final result is **"Payment not complete"** and this exception appears:

```
PlatformException(Failed, Payment not completed, null, null)
```


I'm not sure what's going on, but when testing with the [`pay`](https://pub.dev/packages/pay) flutter plugin all the payments work as expected.

This is my piece of code:

```dart
// initState() ......
 Stripe.publishableKey = '......'
 Stripe.merchantIdentifier = 'merchant.com.....';
 await Stripe.instance.applySettings();


// makePayment() ....
await Stripe.instance.presentApplePay(
   ApplePayPresentParams(
     cartItems: [
       ....
     ],
     country: 'ES',
     currency: 'eur',
     requiredBillingContactFields: [
       ApplePayContactFieldsType.name,
       ApplePayContactFieldsType.emailAddress,
     ],
   ),
 );

 await Stripe.instance.confirmApplePayPayment(
   value['client_secret'],
 );
```

Thank you for your help ❤️

**Comment by SebghatYusuf** [comment]
@efraespada 
I hope this tip would be helpful for you, I had the same problem with testing Apple Pay with Stripe on a real device as it was working on Simulator. 
I had several discussion with Stripe support team on Discord any finally they suggested to use real card and real payment using apple pay with Stripe as the Sandbox account wasn't working as expected. Surprisingly it worked as expected and was able to successfully do a payment.

**Comment by efraespada** [comment]
@SebghatYusuf thanks for your tip. I've tried it but I got the same result with a real card: **Payment not complete**

**Comment by SebghatYusuf** [comment]
@efraespada Okay, I'd suggest to contact Stripe support team on their official discord. they're pretty responsive and may find a solution for this.

**Comment by VStudio4125** [comment]
Hi,
Did you ever manage to fix it ?
