### ISSUE TITLE
Is flutter_stripe for web stable?

### ISSUE THREAD

**Issue by eliezerp3** [flutter-stripe/flutter_stripe#828]
Hi. I want to use flutter_stripe on the web but I see that it said in the docs that flutter_stripe for web is highly experimental. The issue is that it has said this for over 6 months. Is this just bec there hasn’t been extensive testing done or is there known issues with it? What does it mean that only a subset of features are supported? And lastly, is there a plan on getting it production ready?

Appreciate all the work done here. Thank you

**Comment by remonh87** [comment]
To be honest,  there is at the moment not a good way of updating the library to the latest stripe sdk. It is a tedious manual process. We are  trying to discuss with stripe how we can improve this but I think we will end up with a light version for the web. For now I think checkout is by far the best solution for the web.

**Comment by eliezerp3** [comment]
@remonh87 What exactly do you mean by a light version? Is it documented somewhere what the limitations are on the web?

**Comment by eliezerp3** [comment]
@jonasbark O. Thanks. Any chance payment sheet will get supported soon or I shouldn’t hold my breath. I can’t really use stripe checkout as my backend uses the new stripe order api.

**Comment by jonasbark** [comment]
There is no payment sheet for the Web. There's only the https://stripe.com/docs/payments/payment-element - which is already (sort of) supported in flutter_stripe_web.

**Comment by eliezerp3** [comment]
Are you referring to the Card element or the payment element as I don’t see the latter one documented [here](https://github.com/flutter-stripe/flutter_stripe/blob/main/packages/stripe_web/lib/src/web_stripe.dart).
