### ISSUE TITLE
Scroll view does not automatically scroll to CardView on focus

### ISSUE THREAD

**Issue by easeccy** [flutter-stripe/flutter_stripe#833]
When using `CardView` in a scroll view, unlike other input fields, scroll view does not scroll to the `CardView` on focus. This causes an annoying UI issue where user clicks the `CardView` and open the keyboard, keyboard is drawn over the `CardView` field thus it's invisible to the user.

**Comment by remonh87** [comment]
the problem is that we do not have control over the cardview as it is a native screen hosted on the Flutter canvas. What I would recommend to do is wrap the widget in a safe area. The CardView is really a big workaround since hosting native views in Flutter has its limitations. For the best and most easy solution I would really push for the use of PaymentSheet which is also the recommended integration from Stripe.

**Comment by faisal-ibrahim** [comment]
@easeccy probably it's too late for you, but I got a workaround using scroll controller ( mixed ideas from several SO answer):

`class PlayGround extends StatelessWidget {
  PlayGround({super.key});

  //ScrollController
  final ScrollController _controller = ScrollController();

  @override
  Widget build(BuildContext context) {
    var bottom = MediaQuery.of(context).viewInsets.bottom;
    WidgetsBinding.instance.addPostFrameCallback(
      (_) {
        //Add adjustment if there is more elements at the bottom
        //This is just try and see how much adjustment is needed
        double adjustment = 0.0;

        //Scroll up from bottom
        _controller.animateTo(
          bottom + adjustment,
          duration: const Duration(milliseconds: 30),
          curve: Curves.easeOut,
        );
      },
    );

    return Scaffold(
      body: SingleChildScrollView(
        controller: _controller,
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: const [
            //Mimic the other fields on the top of the card
            SizedBox(
              height: 700,
            ),
            CardField(
              numberHintText: "Card Number",
            )
          ],
        ),
      ),
    );
  }
}`
