### ISSUE TITLE
StripeApplePay

### ISSUE THREAD

**Issue by macuser79** [flutter-stripe/flutter_stripe#839]
Using XCode 14, and IOS 16, we encounter the following problem:

StripeApplePay -> STPApplePayContext -> "Argument of '#selector' does not refer to an '@objc' method, property, or initializer"

Below is the line of code where the problem is encountered

let pk_didSelectShippingMethod = #selector (
            (PKPaymentAuthorizationControllerDelegate.paymentAuthorizationController (
                _: didSelectShippingMethod: handler :)) as! pkDidSelectShippingMethodSignature)

**Comment by remonh87** [comment]
This should be fixed in the latest version that we just published :-)

**Comment by Anonymousgaurav** [comment]
@devloe did you got solution?
