### ISSUE TITLE
How to add additional pay network?

### ISSUE THREAD

**Issue by SebghatYusuf** [flutter-stripe/flutter_stripe#845]
**Describe the bug**
Currently the plugin supports major Payment networks (VISA, MasterCard, Amex,...), but how can we add another pay network. on iOS it's possible to add using something like `additionalEnabledApplePayNetworks to [.interac]` (stated by Stripe dev team).

**Comment by remonh87** [comment]
Add the moment the Stripe react native library doesn't support adding additional payment methods I will create a ticket on their repo. I have created #846  since only JCB is supported as additional payment method on Apple pay for the moment.
