### ISSUE TITLE
No payment sheet has been initialized yet.

### ISSUE THREAD

**Issue by Alfaizkhan** [flutter-stripe/flutter_stripe#850]
**main.dart**
```
  WidgetsFlutterBinding.ensureInitialized();
  Stripe.publishableKey = stripePublishableKey;
  Stripe.merchantIdentifier = 'emailID';
  await Stripe.instance.applySettings();
```

 **Initiate Payment**

  ```
Future<void> initPaymentSheet({
    required String? price,
  }) async {
    try {
     await Stripe.instance.initPaymentSheet(
        paymentSheetParameters: SetupPaymentSheetParameters(
          // Main params
          paymentIntentClientSecret: clientSecret,
          customerId: customerId,
          customerEphemeralKeySecret: ephemeralKey,
          // Merchant Name
          merchantDisplayName: 'TEST',
          // Extra params
          applePay: const PaymentSheetApplePay(
            merchantCountryCode: 'US',
          ),
          googlePay: const PaymentSheetGooglePay(
            merchantCountryCode: 'US',
            testEnv: true,
          ),
          style: ThemeMode.system,
        ),
      );
    } catch (e) {
      rethrow;
    }
  }


  /// Display the payment sheet.
  Future<void> confirmPayment({required String price}) async {
    try {
      await initPaymentSheet(price: price);
      // Present Payment sheet to user for payment
      await Stripe.instance.presentPaymentSheet();

      // Book the request.
      bookingRequest();
    } on Exception catch (e) {
      if (e is StripeException) {
        // displaySnackBar(
        //     'Error!', 'Error from Stripe: ${e.error.localizedMessage}');
        log('Error from Stripe: ${e.error.localizedMessage}');
        print('Error from Stripe: ${e.error.localizedMessage}');
        displaySnackBar('Error!', 'Something went wrong!, \nPlease try again.');
      } else {
        log('Error from Stripe: $e');
        displaySnackBar('Error!', 'Something went wrong!, \nPlease try again.');
      }
    }
  }

```
  
 - This **confirmPayment()** is called on Button click.
 - It will wait for Init the payment sheet.
 - After that **presentPaymentSheet** called to present the Payment sheet.

  **In Android, It's working fine.
  In iOS, it's showing error like: No payment sheet has been initialized yet**

**Comment by jaxnz** [comment]
I have the same issue - works in Android.

Not the same as #742

**Comment by remonh87** [comment]
and what if you put a small delay between init and present paymentsheet?

**Comment by Alfaizkhan** [comment]
@remonh87 
Already tried with 10 seconds delayed.

**Comment by remonh87** [comment]
I did try to reproduce it on our example app but it runs fine in both instances. I also checked the app I am working on currently and no issues there as well. This issue mostly occurs due to incorrect configuration. Since it only happens on apple can you try the paymentsheet without providing an apple pay object and see if this works?

**Comment by Alfaizkhan** [comment]
@remonh87 
Removed the "Apple pay object" and "Google pay object" and Test with android and iOS devices.

It is working fine in android and still giving same error in iOS simulator as well as physical device.

It is strange that your plugin example is working fine in both platform.

**Comment by Alfaizkhan** [comment]
@remonh87 

✅ **Solved:**

Okay, the problem was in our backend response
when we were generating EphemeralKey, our backend dev was returning ephemeralKey["id"] instead of ephemeralKey["secret"] as a ephemeralKey.

I changed the EphemeralKey

from this
` paymentIntentDTO.setEphemeralKey(ephemeralKey.getId());`

to this
`paymentIntentDTO.setClientSecret(paymentIntent.getClientSecret());`

@remonh87 
Thank you for your quick responses.
Appreciated 👍🏼

**Comment by jaxnz** [comment]
My issue isn't because of the backend:

`res.json({
        paymentIntent: paymentIntent.client_secret,
        ephemeralKey: ephemeralKey.secret,
        customer: customerID,
        publishableKey: 'pk_test_xxxx'
    });`

I have added a delay with no luck. Still getting `No Payment sheet has been initialized yet` - but works on android perfectly.

**Comment by remonh87** [comment]
@jaxnz  can you initialize the paymentsheet without the customerid + ephemeralKey ?

**Comment by Alfaizkhan** [comment]
@remonh87 
I create a medium blog on your plugin that how to integrate with flutter application.
Hope you'll like it.

 https://medium.com/@i_m_alfaizkhan/exploring-the-stripe-payment-gateway-in-flutter-e8524a0ade75

**Comment by jaxnz** [comment]
> @jaxnz can you initialize the paymentsheet without the customerid + ephemeralKey ? I think it is some config that is going wrong I agree the error is not super clear.

Yes I can on Android, still not working on iOS - getting same `No payment sheet has been initialized yet` error

**Comment by jaxnz** [comment]
Found my issue is I hadn't set merchantIdentifier - added PR with an assertion.

**Comment by Alfaizkhan** [comment]
Since this issue is solved  If still exists, I will reopen

**Comment by Alfaizkhan** [comment]
@remonh87 
Since problem is our side and it is solved, I am closing the issue.
