### ISSUE TITLE
Question: Accessing Payment Information

### ISSUE THREAD

**Issue by jaxnz** [flutter-stripe/flutter_stripe#855]
I am implementing `paymentsheet` I was wondering whether it's possible to access payment information from that payment made in the payment sheet.

`await Stripe.instance.presentPaymentSheet(); `

Once this is called, it doesn't return any information - I was hoping to access the `description` to log against our database.

**Comment by remonh87** [comment]
No it is not possibile to retrieve that info on the client. You can however get some information on your backend service while interacting with the Stripe API. See: https://stripe.com/docs/api/payment_intents
