### ISSUE TITLE
What is the Difference Between confirmPayment and confirmApplePayPayment method 

### ISSUE THREAD

**Issue by shahryar-cmyk** [flutter-stripe/flutter_stripe#856]
What is the Difference Between confirmPayment and confirmApplePayPayment method

**Comment by remonh87** [comment]
Good question. In fact the confirmpayment and comfirmApplePay do kind of the similar thing namely after the user entered the necessary information confirm the payment towards stripe.  However confirm apple pay is used in combination with our native apple pay implementation (so if you use `presentApplePay` you need to use `confirmApplePay`). The other is used when you use other payment methods (e.g. ideal). Hope this clarifies the behavior.

**Comment by shahryar-cmyk** [comment]
Thank you.
