### ISSUE TITLE
Failed to handle method call

### ISSUE THREAD

**Issue by anmolguptach** [flutter-stripe/flutter_stripe#859]
Running "flutter pub get" in stripe_payment...
Launching lib/main.dart on sdk gphone64 arm64 in debug mode...
Running Gradle task 'assembleDebug'...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Debug service listening on ws://127.0.0.1:51952/jX83Pv9UFvo=/ws
Syncing files to device sdk gphone64 arm64...
E/MethodChannel#flutter/platform_views(21736): Failed to handle method call
E/MethodChannel#flutter/platform_views(21736): kotlin.UninitializedPropertyAccessException: lateinit property stripeSdk has not been initialized
E/MethodChannel#flutter/platform_views(21736): 	at com.flutter.stripe.StripeAndroidPlugin.getStripeSdk(StripeAndroidPlugin.kt:33)
E/MethodChannel#flutter/platform_views(21736): 	at com.flutter.stripe.StripeAndroidPlugin$onAttachedToEngine$1.invoke(StripeAndroidPlugin.kt:56)
E/MethodChannel#flutter/platform_views(21736): 	at com.flutter.stripe.StripeAndroidPlugin$onAttachedToEngine$1.invoke(StripeAndroidPlugin.kt:56)
E/MethodChannel#flutter/platform_views(21736): 	at com.flutter.stripe.StripeSdkCardPlatformView.<init>(StripeSdkCardPlatformView.kt:27)
E/MethodChannel#flutter/platform_views(21736): 	at com.flutter.stripe.StripeSdkCardPlatformViewFactory.create(StripeSdkCardPlatformViewFactory.kt:24)
E/MethodChannel#flutter/platform_views(21736): 	at io.flutter.plugin.platform.PlatformViewsController$1.createForTextureLayer(PlatformViewsController.java:197)
E/MethodChannel#flutter/platform_views(21736): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:122)
E/MethodChannel#flutter/platform_views(21736): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
E/MethodChannel#flutter/platform_views(21736): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#flutter/platform_views(21736): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#flutter/platform_views(21736): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#flutter/platform_views(21736): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#flutter/platform_views(21736): 	at android.os.Handler.handleCallback(Handler.java:938)
E/MethodChannel#flutter/platform_views(21736): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#flutter/platform_views(21736): 	at android.os.Looper.loopOnce(Looper.java:201)
E/MethodChannel#flutter/platform_views(21736): 	at android.os.Looper.loop(Looper.java:288)
E/MethodChannel#flutter/platform_views(21736): 	at android.app.ActivityThread.main(ActivityThread.java:7842)
E/MethodChannel#flutter/platform_views(21736): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/platform_views(21736): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/MethodChannel#flutter/platform_views(21736): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/flutter (21736): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(error, lateinit property stripeSdk has not been initialized, null, kotlin.UninitializedPropertyAccessException: lateinit property stripeSdk has not been initialized
E/flutter (21736): 	at com.flutter.stripe.StripeAndroidPlugin.getStripeSdk(StripeAndroidPlugin.kt:33)
E/flutter (21736): 	at com.flutter.stripe.StripeAndroidPlugin$onAttachedToEngine$1.invoke(StripeAndroidPlugin.kt:56)
E/flutter (21736): 	at com.flutter.stripe.StripeAndroidPlugin$onAttachedToEngine$1.invoke(StripeAndroidPlugin.kt:56)
E/flutter (21736): 	at com.flutter.stripe.StripeSdkCardPlatformView.<init>(StripeSdkCardPlatformView.kt:27)
E/flutter (21736): 	at com.flutter.stripe.StripeSdkCardPlatformViewFactory.create(StripeSdkCardPlatformViewFactory.kt:24)
E/flutter (21736): 	at io.flutter.plugin.platform.PlatformViewsController$1.createForTextureLayer(PlatformViewsController.java:197)
E/flutter (21736): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:122)
E/flutter (21736): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
E/flutter (21736): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/flutter (21736): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter (21736): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/flutter (21736): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter (21736): 	at android.os.Handler.handleCallback(Handler.java:938)
E/flutter (21736): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter (21736): 	at android.os.Looper.loopOnce(Looper.java:201)
E/flutter (21736): 	at android.os.Looper.loop(Looper.java:288)
E/flutter (21736): 	at android.app.ActivityThread.main(ActivityThread.java:7842)
E/flutter (21736): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (21736): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/flutter (21736): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/flutter (21736): )
E/flutter (21736): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter (21736): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
E/flutter (21736): <asynchronous suspension>
E/flutter (21736): #2      TextureAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1134:18)
E/flutter (21736): <asynchronous suspension>
E/flutter (21736): #3      AndroidViewController.create (package:flutter/src/services/platform_views.dart:762:5)
E/flutter (21736): <asynchronous suspension>
E/flutter (21736): #4      TextureAndroidViewController.setSize (package:flutter/src/services/platform_views.dart:1062:7)
E/flutter (21736): <asynchronous suspension>
E/flutter (21736): #5      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:179:29)
E/flutter (21736): <asynchronous suspension>
E/flutter (21736):

**Comment by jaxnz** [comment]
Have you setup your android project as per:
https://github.com/flutter-stripe/flutter_stripe#android

**Comment by jonasbark** [comment]
Closing this due to a lack of response. Feel free to reopen it with more information.
