### ISSUE TITLE
Paymentsheet is always dark on Android

### ISSUE THREAD

**Issue by remonh87** [flutter-stripe/flutter_stripe#86]
**Describe the bug**
No matter which value of style you add the payment sheet on Android is always dark. On iOS I can change the styling.

**To Reproduce**
1. configure paymentsheet
```dart
 await Stripe.instance.initPaymentSheet(
      paymentSheetParameters: SetupPaymentSheetParameters(
        paymentIntentClientSecret: paymentIntentClientSecret,
        customerId: customerId,
        customerEphemeralKeySecret: customerEphemeralKeySecret,
        style: ThemeMode.light,
        applePay: false,
        googlePay: false,
        customFlow: false,
        testEnv: true,
      ),
    );
```
2.call  presentPaymentSheet and notice it is always represented in dark theme. 

**Expected behavior**
In my example it should display the payment sheet in light theme.

**Smartphone / tablet**
- Pixel 4a android 11.

**Additional context**
My app theme is: `Theme.AppCompat.Light.NoActionBar`

**Comment by remonh87** [comment]
I will assign it to myself was planning to fix another issue in the paymentsheet

**Comment by remonh87** [comment]
Waiting for answer on: https://github.com/stripe/stripe-react-native/issues/285

**Comment by UsamaKarim** [comment]
I am using system-wide light theme on my physical device & the Payment sheet is light whichever option I use. I am using example app

Smartphone / tablet

Mi 9T android 11.

**Comment by michelleb-stripe** [comment]
@remonh87 I just posted a comment on: https://github.com/stripe/stripe-react-native/issues/285.  

We do have worked planned to update our styling soon, but I don't have exact dates when anything would be available.

**Comment by remonh87** [comment]
with the new customisation issues this is no longer an issue
