### ISSUE TITLE
Google Pay button is not accepted by Google Pay support team. 

### ISSUE THREAD

**Issue by panchalAlpit** [flutter-stripe/flutter_stripe#862]
Hello Stripe,
I have implement the Google pay in my Application and it's working fine in Test mode, but when set the Live mode, So need to submit our App for review. After submission getting feedback by Google Pay support team to use [Google Pay branding button](https://developers.google.com/pay/api/android/guides/brand-guidelines#payment-buttons). but I'm using the as [Stripe plugin provided Google pay button](https://github.com/flutter-stripe/flutter_stripe/blob/bbe90604d41c2c51cc0f4a66b7c89fedd2b8d068/example/lib/screens/wallets/google_pay_stripe_screen.dart).

I'm getting this type of [mail](https://prnt.sc/-3CuhbtseuKv) from Google Pay support team.

 **So my question is Stripe plugin by provided Google pay button is not full fill all required point for Google pay button.**   

Please help me or suggest for this issue. 

Thank you.

**Comment by elmdecoste** [comment]
We are experiencing the same issue with Google review while trying to deploy our integration

**Comment by remonh87** [comment]
Google changed their brand guidelines. This is addressed in the underlying stripe sdk and will be fixed with: https://github.com/stripe/stripe-react-native/issues/1068 . I will also double check if the branding for the native component will be picked up with that ticket.

**Comment by JlUgia** [comment]
Hi @panchalAlpit , version `1.0.8` in `pay_android` contains the new styles and spec for the Google Pay button.
If you are using the `pay` package, `1.0.11` uses the latest version of `pay_android`.
Let me know if you experience additional trouble.
