### ISSUE TITLE
Migrate from React Native

### ISSUE THREAD

**Issue by dorsamet** [flutter-stripe/flutter_stripe#864]
**Is your feature request related to a problem? (please describe)**
At the moment depending on this library seems like adding a 3rd party dependency on ReactNative, as the library opens up a React Native window that displays the elements.

**Describe the solution you'd like**
Migrate to using native elements as supplied by the Android and iOS Stripe elements

**Describe alternatives you've considered**
We could use a webview in the interim and then feed the information in via JSObjects

**Comment by remonh87** [comment]
Can you elaborate on where you see the react native view?

**Comment by jonasbark** [comment]
Closing this due to a lack of response. No React Native is used in the Plugin, apart from some self-written wrapper classes.
