### ISSUE TITLE
Please Fix IOS CardFormStyle Not Updating For CardFormField

### ISSUE THREAD

**Issue by VindictiveHosting** [flutter-stripe/flutter_stripe#869]
I understand IOS doesn't update any CardFormStyle for IOS but works on Android. Is there any work around this issue?

**Comment by jonasbark** [comment]
This will be fixed with https://github.com/flutter-stripe/flutter_stripe/commit/54dc5d07a036f8e9de92842d3ac422ccf27d3940

**Comment by VindictiveHosting** [comment]
@jonasbark Thank you for the update! Does this fix work on the Flutter package flutter_stripe 4.0.0?

**Comment by jonasbark** [comment]
no, the fixed version is not released yet

**Comment by VindictiveHosting** [comment]
@jonasbark Thank you for informing me on that. Do you know when the fixed version for this issue will be released or do you know if there is a way I can modify the source code myself? I appreciate all of your hard work & time!
