### ISSUE TITLE
disabling scanning card issue,even when NSCameraUsageDescription removed.

### ISSUE THREAD

**Issue by hooshyar** [flutter-stripe/flutter_stripe#879]
**Describe the bug**
I'm trying to disable the card scanning on the payment sheet, I don't have the camera usage permission on my info.plist but still the button appears, is there any kind of option to disable the card scanning? 

**To Reproduce**
1. just check the payment bottom sheet on iOS

**Expected behavior**
Not to have the scanning card feature when I don't have the permission on info.plist

**Smartphone / tablet**
 - Device: iPhone X
 - OS: iOS 15
 - Package version: ^3.3.0
 - Flutter version 3.0.5

**Comment by jonasbark** [comment]
There is no such functionality available:
https://github.com/stripe/stripe-ios/issues/1944#issuecomment-1076889356

 Please double-check that the compiled app really does not have the camera usage permission set. Sometimes it's added via a Cocoapods post-install hook.
