### ISSUE TITLE
SEPA Debit and iDeal payment methods

### ISSUE THREAD

**Issue by abel-123** [flutter-stripe/flutter_stripe#88]
Awesome job on this guys!
For my app I'm looking for 2 payment methods on top of credit cards:
- iDEAL payments (bank redirect)
- Subscription based (recurring) payments through SEPA direct debit

The readme refers to this page which lists both methods: https://stripe.com/docs/payments/payment-methods/overview

I've tried to adjust the example code to work with the methods above, but not sure if it is even possible. Are these methods currently supported?
If the answer is no, please consider this feature request.
If it is already supported, some pointers on how to get started with these payment methods would be much appreciated!

**Comment by jonasbark** [comment]
Hi! 

We're working on better documentation 👍  Ideal and SEPA Debit are supported.
You can see all supported payment methods here:
https://github.com/flutter-stripe/flutter_stripe/blob/main/packages/stripe_platform_interface/lib/src/models/payment_methods.dart#L51

**Comment by oliveyew** [comment]
@abel This will do the trick [link](https://www.udemy.com/course/flutter-in-app-consumable-non-consumable-purchase-2022/?couponCode=NEW_USER_DISCOUNT)
