### ISSUE TITLE
FlutterFragmentActivity can't able to get Activity context

### ISSUE THREAD

**Issue by sami79031** [flutter-stripe/flutter_stripe#880]
**Describe the bug**
When FlutterFragmentActivity is extended, doesn't seem to find the app context.

**To Reproduce**
In the MainActivity try to get the context via either context or activity (getActivity())

**Comment by jonasbark** [comment]
Please provide proper information. I'm not sure what you mean and where the error is and how it is related to this plugin.

**Comment by sami79031** [comment]
I don't see why this information wouldn't be clear enough, but here it's the breakdown for you.

In your documentation, you insist to use the FlutterFragmentActivity instead of FlutterActivity in MainActivity.kt
https://github.com/flutter-stripe/flutter_stripe/blob/79b201a2e9b827196d6a97bb41e1d0e526632a5a/example/android/app/src/main/kotlin/com/flutter/stripe/example/MainActivity.kt#L6

When I do that, though, I'm unable to access the activity's context. I tried with the APIs `getContext()/ context`, `getActivity()/activity`. Nothing worked. The compiler is not able to recognize these keywords.

Hope that helps.

Thanks.

**Comment by jonasbark** [comment]
The MainActivity is already the "activity's context", so just use `this`...

**Comment by sami79031** [comment]
Weird, per the docs
`public class FlutterFragmentActivity extends androidx.fragment.app.FragmentActivity`

and one would think the above would work.
Thanks
