### ISSUE TITLE
Build failed in IOS at Link StripeCore Step 

### ISSUE THREAD

**Issue by lohitbura07** [flutter-stripe/flutter_stripe#881]
Build is failing in IOS and showing following  error - 

can't open file, errno=1 file '/Users/daffolapmac-153/Library/Developer/Xcode/DerivedData/Runner-crjdlfvpkyuhuefdntdfrmehspqc/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/StripeCore.build/Objects-normal/x86_64/StripeFile.o'

can't open file, errno=1 file '/Users/daffolapmac-153/Library/Developer/Xcode/DerivedData/Runner-crjdlfvpkyuhuefdntdfrmehspqc/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/StripeCore.build/Objects-normal/arm64/StripeFile.o'

**Versions -** 

Flutter 3.0.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f1875d570e (5 weeks ago) • 2022-07-13 11:24:16 -0700
Engine • revision e85ea0e79c
Tools • Dart 2.17.6 • DevTools 2.12.2

**Stripe Version**

flutter_stripe : 4.0.0

**Flutter Doctor Info**

[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-x64, locale
    en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!

Although  its working fine in Android .

**Comment by jonasbark** [comment]
Please try removing the derived data and try again.

**Comment by lohitbura07** [comment]
@jonasbark I removed the derived data but still facing the same issue

**Comment by jonasbark** [comment]
Can you provide an example app where this is reproducible?
To me, it seems like a file cache issue and unrelated to the plugin.

**Comment by lohitbura07** [comment]
I am using it in my Org. porject so I won't be able to share the code . But can you please give me an idea how can I completely remove it from my system and start again so that File cache issue will get resolved .
Thanks

**Comment by jamesblasco** [comment]
Could you try to execute `flutter clean`?.  This will clear cache files related to this project so you can build the project next time from scratch

**Comment by remonh87** [comment]
closed due to inactivty feel free to reopen it or create a new issue if you still experience problems
