### ISSUE TITLE
presentPaymentSheet future never completes after selecting Apple Pay

### ISSUE THREAD

**Issue by amanxnanda** [flutter-stripe/flutter_stripe#883]
**Describe the bug**

**To Reproduce**
1. Select Apple Pay on the bottom sheet
2. Press pay
3. The future is never completes. It just goes on

**Expected behavior**
Payment successful

**Smartphone / tablet**
 - Device: iPhone SE -2nd gen
 - OS: iOS 15.5
 - Package version: 4.0.0
 - Flutter version 3.0.5

**Additional context**
I did try running the example app on flutter_stripe, and it works as expected.

**Comment by jonasbark** [comment]
Please post a video of the issue and include the logs while trying. It seems to be a configuration issue, maybe the merchant display name is wrong.

**Comment by amanxnanda** [comment]
Here's the video
https://user-images.githubusercontent.com/34944818/185066285-fbffc5a5-f042-48b0-bee7-9f3685fd6b21.mp4


Please tell me what logs I need to include. TIA @jonasbark

**Comment by jonasbark** [comment]
When you're using Xcode then the log output, otherwise the log output when running your Flutter application. Typically there should be indications when there's a configuration issue.

**Comment by amanxnanda** [comment]
There is nothing in debug console
<img width="981" alt="Screenshot 2022-08-17 at 13 47 29" src="https://user-images.githubusercontent.com/34944818/185069859-eb32f17e-5b7e-467e-ab8b-855c57efec24.png">

**Comment by amanxnanda** [comment]
@jonasbark, please have a look.

(Sorry 🙏  for mentioning you like this)

**Comment by jonasbark** [comment]
Try running it with Xcode - there should be a lot more information

**Comment by remonh87** [comment]
closing now due to inactivity feel free to reopen or create a new issue in case this is not solved
