### ISSUE TITLE
WebUnsupportedError: initPaymentSheet is not supported for Web

### ISSUE THREAD

**Issue by jaxnz** [flutter-stripe/flutter_stripe#886]
**Describe the bug**
Using `Stripe.instance.initPaymentSheet` on web returns `WebUnsupportedError: initPaymentSheet is not supported for Web`

**To Reproduce**
Initialising Payment sheet after creating payment intent 

**Expected behavior**
Payment sheet should appear

**Versions**
  flutter_stripe: ^4.0.0
  flutter_stripe_web: ^1.2.0
  Flutter 3.0.5 - Stable Channel

**Additional context**
The error returned isn't a `StripeException`

**Comment by remonh87** [comment]
the paymentsheet is not supported on the web because it doesn't exist. We recommend using `stripe_checkout` for the web.

**Comment by jaxnz** [comment]
Can `CardField` or `CardForm` be used in the web? I would prefer to stick with one package across platforms.

**Comment by chukovskid** [comment]
I just tried it with the latest version and it seems like it's not implemented for web.  
If someone has solved this please provide us some info.

**Comment by debjeetdebnath** [comment]
@chukovskid Hey, I tried out this method [youtube video](https://www.youtube.com/watch?v=yYxIWEQgOe4&ab_channel=Fidev-MakeBeautifulApps) but it was 2 years old and i think this will work.
there is a GitHub link is also there of the project. When I run it on flutter web it shows me this error **IntegrationError: No such plan: 'plan_EBttg1ziShQ51I'** this error comes when not adding the product_id in stripe but I am not getting how to add product_id. If you found anything please let me know.

**Comment by jaxnz** [comment]
@debjeetdebnath Unfortunately it doesn't work on web. Looks like they aren't willing to support it either.

**Comment by debjeetdebnath** [comment]
@jaxnz I talked with stripe customer care today and they told me that there are no docs for flutter web. They told me to ask the flutter community to help. 
I am trying hard to integrate stripe payment into flutter web and you also give a try.
if you find anything please share here. Thanks in advance
