### ISSUE TITLE
Donate with Apple Pay

### ISSUE THREAD

**Issue by powerofpercy** [flutter-stripe/flutter_stripe#889]
Not sure if this is a feature request, do we currently have a way to change Apple Pay button to 'Donate with Apple Pay'? The app I'm trying to develop collects donations for a charity organisation and seems like Apple requires the Pay button to say 'Donate with Apple Pay' instead. Here's the Apple Developer link https://developer.apple.com/apple-pay/nonprofits/

**Comment by jonasbark** [comment]
Did you try to use a different type?
https://github.com/flutter-stripe/flutter_stripe/blob/main/packages/stripe/lib/src/widgets/apple_pay_button.dart#L19
https://github.com/flutter-stripe/flutter_stripe/blob/main/packages/stripe/lib/src/widgets/apple_pay_button.dart#L150

**Comment by powerofpercy** [comment]
> Did you try to use a different type?
> https://github.com/flutter-stripe/flutter_stripe/blob/main/packages/stripe/lib/src/widgets/apple_pay_button.dart#L19
> https://github.com/flutter-stripe/flutter_stripe/blob/main/packages/stripe/lib/src/widgets/apple_pay_button.dart#L150

Thanks for the reply, do I need to use a customised payment sheet to change the button type?

**Comment by jonasbark** [comment]
Oh, you're talking about the payment sheet.

You already did the right thing by checking in the stripe-ios repository, so I'm going to close this ticket as there is nothing we can do ourselves.

https://github.com/stripe/stripe-ios/issues/2000
