### ISSUE TITLE
Apple pay recurring subscription

### ISSUE THREAD

**Issue by DziugasMolis** [flutter-stripe/flutter_stripe#89]
Hello,

I am currently looking into this package and cannot find an example or solution to make subscriptions with Apple pay.

So far it seems it is impossible to do it with the current version or am I wrong?

Thanks in advance.

**Comment by jamesblasco** [comment]
It should be possible, but I haven't tried yet and we haven't created an example. This is what the official stripe docs say.

![image](https://user-images.githubusercontent.com/19904063/119953342-2fa4ce80-bf9e-11eb-858c-4192ddd8113c.png).
 

I will try to take a deeper look in the coming days.

Notice that the availability of using Stripe subscriptions instead of In-App Purchases is limited to small use-cases. See  https://stripe.com/docs/apple-pay?platform=ios#create-automatic-payment-intent

**Comment by jamesblasco** [comment]
Thank you for sharing it @thorsten-stripe  💙

**Comment by DziugasMolis** [comment]
So one issue still remains... I found that example before and when doing:
Future<PaymentIntent> retrievePaymentIntent(...);

So my logic was: 

1. Present Apple pay
2. Fetch Intent Client Secret from backend
3. Stripe.instance.retrievePaymentIntent(clientSecret);
4. Create payment method on backend

But on third step I get:
Assertion failed: `secret` format does not match expected client secret formatting.: file Stripe/STPAPIClient.swift, line 636
 Maybe someone could guide me where I am wrong? I think it will help others too.

**Comment by DziugasMolis** [comment]
Okay, so long story short. Found stripe IRC channel and had a talk with stripe development team, the above comment is useless... One option that they suggested is to get apple pay or google pay token and call Stripe API.

curl -u sk_test_123: https://api.stripe.com/v1/tokens \
  -d pk_token=<PKPaymentToken.paymentData decoded as JSON> \
  -d pk_token_instrument_name=<PKPaymentToken.paymentInstrumentName> \
  -d pk_token_payment_network=<PKPaymentToken.paymentNetwork> \
  -d pk_token_transaction_id=<PKPaymentToken.transactionIdentifier>
  
  and then follow their documentation to bind to that Stripe token to specific customer.
  When I will try that I will update with the result.

**Comment by DziugasMolis** [comment]
So finally I made it... 

1. So with the example code I created stripe token from apple pay token. (https://www.irccloud.com/pastebin/yy7TvGZ2/)
2. I got clientSecret from backend
3. Did a confirm on setup intent and passed that created stripe token with it (that token property is not visible in Stripe documentation but it works)
```
final confirmSetupIntentReq = {
        'payment_method_data[type]': 'card',
        'payment_method_data[card][token]': stripeToken['id'],
        'client_secret': clientSecret
      };
```
4. Got customer id
5. Created payment method with customerId and setup Intent payment_method id

Works like a charm. I hope it helps to others find some useful information because all of this information was only available on their IRC channel and contacting devs directly.

**Comment by werdlv** [comment]
@DziugasMolis hey! I am looking for the same :) We need to add recurring donations to the app. Any chance You could share some code examples for the puzzle pieces to make it work? :)

**Comment by DziugasMolis** [comment]
@werdlv So Basically if for my use case in the end we had to use in_app_payments flutter package.... and following apple guidelines we can not use other payment provider than apple because we give to user more functionality with our subscriptions.....

**Comment by werdlv** [comment]
@DziugasMolis could You please provide the URL for the library You mentioned? :) Can`t seem to find the one.

**Comment by DziugasMolis** [comment]
https://github.com/flutter/plugins/tree/master/packages/in_app_purchase

**Comment by mockturtl** [comment]
re: https://github.com/flutter-stripe/flutter_stripe/issues/89#issuecomment-851259809

@DziugasMolis Thanks!  One note for posterity:

> `curl -u sk_test_123: https://api.stripe.com/v1/tokens`
> `  -d pk_token=<PKPaymentToken.paymentData decoded as JSON>`

Most of the paymentData fields are base64 strings, which may contain `+` characters. `curl -d` will turn these into a space, leading to `invalid_request_error, Your payment information is formatted improperly`.

The `pk_token` needs to be passed with [`--data-urlencode`](https://curl.se/docs/manpage.html#--data-urlencode) instead of just `--data`.

**Comment by joknjokn** [comment]
@thorsten-stripe, do you plan to add ApplePayToken->StripeToken support in the plugin so we can add ApplePay as payment method for subscriptions?

**Comment by niklaesAtMonta** [comment]
Any news on this? 👍 
Could be a nice feature

**Comment by oliveyew** [comment]
This works for me [link](https://www.udemy.com/course/flutter-in-app-consumable-non-consumable-purchase-2022/?couponCode=NEW_USER_DISCOUNT)
