### ISSUE TITLE
Payment sheet button text modify

### ISSUE THREAD

**Issue by ShwetaChauhan18** [flutter-stripe/flutter_stripe#890]
**Is your feature request related to a problem? (please describe)**
Can we change payment sheet button text?? Currently, payment sheet button text is either "setup" or "Pay {some price}". 

**Describe the solution you'd like**
I want to change that button text from my side when payment sheet init. Is it possible that user can pass??

<img width="386" alt="stripe" src="https://user-images.githubusercontent.com/34509457/186622009-c3996c9e-0537-45ac-bdc8-cc42c65eb942.png">

**Comment by jonasbark** [comment]
No, it's not possible to change it. But you can open a ticket on https://github.com/stripe/stripe-android/ and https://github.com/stripe/stripe-ios/ and maybe they will add this in the future.
