### ISSUE TITLE
Setup Intent is not working with Gpay in PaymentSheet

### ISSUE THREAD

**Issue by ShwetaChauhan18** [flutter-stripe/flutter_stripe#895]
**Describe the bug**
Whenever I do payment using GPAY in PaymentSheet it's working only if payment price is more than 0. For 0 Rs payment we are using setup intent and it's not working with GPay. It's shows "An internal error occurred'. I have attached image for that.

**To Reproduce**
1.  Create SetupPayment Intent
2. Using SetupPaymentIntent's ClientSecret open Payment sheet
3. Try to do payment using card -> It's working fine 
4. Instead of card try to do payment using Gpay -> It shows "An internal error occurred"

**Expected behavior**
Gpay should work with setup payment intent. It was working when I did custom flow by putting pay button.

**Smartphone / tablet**
 - Device: [Android Moto G5 Plus]
 - OS: [Android 8.1.0]
 - Package version: [4.0.0]
 - Flutter version [3.0.0]

![Screenshot_20220826-110515](https://user-images.githubusercontent.com/34509457/186831539-bbd917ec-2b23-4268-b281-f68f3fc53f07.png)

**Comment by ShwetaChauhan18** [comment]
Issue solved.

We have to pass 'currencyCode'.

```
PaymentSheetGooglePay(
        merchantCountryCode: AppConstants.countryCodeISO,
        currencyCode: currency?.toUpperCase(),
        testEnv: true, //ToDo remove this on production
)
```

**Comment by lohitbura07** [comment]
@ShwetaChauhan18 Can you share your code so that I can cross check how you have done the implementation in Stripe for Google pay

**Comment by Nik8110** [comment]
not working...
