### ISSUE TITLE
Android Theme docs are out of sync

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter-stripe/flutter_stripe#896]
The README states that you should:

> Using a descendant of Theme.AppCompat for your activity: [example](https://github.com/flutter-stripe/flutter_stripe/main/example/android/app/src/main/res/values/styles.xml#L15), [example night theme](https://github.com/flutter-stripe/flutter_stripe/blob/main/example/android/app/src/main/res/values-night/styles.xml#L16)

1. These links do not seem to work on Pub (they do work on GitHub).
2. In [the linked files](https://github.com/flutter-stripe/flutter_stripe/blob/c0718d4db9b31e1c9bd953bd3c696ca92c94ceac/example/android/app/src/main/res/values-night/styles.xml#L16), `Theme.MaterialComponents` is used rather than `AppCompat`.
3. In [the night styles](https://github.com/flutter-stripe/flutter_stripe/blob/c0718d4db9b31e1c9bd953bd3c696ca92c94ceac/example/android/app/src/main/res/values-night/styles.xml#L5), `Theme.AppCompat.Light.NoActionBar` (light theme) is used.

**Comment by remonh87** [comment]
Good point we will make it consistent.

**Comment by creativecreatorormaybenot** [comment]
@remonh87 It looks like the PR only addressed point 3. What about 1. and 2.?
