### ISSUE TITLE
SetupIntentClientSecret  payment not working

### ISSUE THREAD

**Issue by expertdev-designer** [flutter-stripe/flutter_stripe#898]
I have to save the user card info for future payment. 
I'm following the stripe doc https://stripe.com/docs/payments/save-and-reuse

but facing  issue with SetupIntentClientSecret . I got the following exception from stripe 

StripeException(error: LocalizedErrorMessage(code: FailureCode.Failed, localizedMessage: The client_secret provided does not match any associated SetupIntent on this account., message: The client_secret provided does not match any associated SetupIntent on this account., stripeErrorCode: null, declineCode: null, type: null)).

but when i do the payment using  paymentIntentClientSecret then payment flow works. 

here is my code 

 await Stripe.instance
          .initPaymentSheet(
              paymentSheetParameters: SetupPaymentSheetParameters(
                 // paymentIntentClientSecret:paymentIntentClientSecret ,
                  setupIntentClientSecret: paymentSetupIntentClientSecret,
                  customerEphemeralKeySecret: ephemeralKey,
                  customerId: userStripeID,
                  applePay: true,
                  googlePay: true,
                  testEnv: true,
                  merchantCountryCode: "US",
                  customFlow: false,
                  allowsDelayedPaymentMethods: true,
                  style: ThemeMode.dark,
                  merchantDisplayName: 'Indigo Donation'))
                  
                  Please let me know whats i'm doing wrong here

**Comment by remonh87** [comment]
The message that we get come straight from the Stripe sdk (we only forward it), normally this message has to do with the fact that the secret provided is not of a SetupIntent. I recommend checking the backend implementation.

**Comment by remonh87** [comment]
closed due to inactivity feel free to create a new ticket in case you still have issues.
