### ISSUE TITLE
Stripe.instance.confirmSetupIntent throws PaymentMethodError.cardPaymentMissingParams on iOS only

### ISSUE THREAD

**Issue by asaarnak** [flutter-stripe/flutter_stripe#900]
**To reproduce:** Works on Android. Throws on iOS.
```dart
      await Stripe.instance.confirmSetupIntent(
        'paymentIntentClientSecret',
        PaymentMethodParams.cardFromMethodId(
          paymentMethodData: PaymentMethodDataCardFromMethod(
            paymentMethodId: 'paymentMethodId',
          ),
        ),
      );
```

**Probably a bug is here:**
Currently we only check for `paymentMethodData?["token"]` in line 159.
And then `PaymentMethodError.cardPaymentMissingParams` is thrown in line 166.
We should add similar check for `paymentMethodData?["paymentMethodId"]` like token check in lane 159.

https://github.com/flutter-stripe/flutter_stripe/blob/6e26f1c756439622664169916e7a4f92ce684f10/packages/stripe_ios/ios/Classes/Stripe%20Sdk/PaymentMethodFactory.swift#L159-L167

**Comment by remonh87** [comment]
Will be waiting on https://github.com/stripe/stripe-react-native/issues/1124 to be fixed.

**Comment by fabioselau077** [comment]
same here... update?

**Comment by fabioselau077** [comment]
> Will be waiting on [stripe/stripe-react-native#1124](https://github.com/stripe/stripe-react-native/issues/1124) to be fixed.

I have the same error but in a different function
`await Stripe.instance.createPaymentMethod(PaymentMethodParams.card())`

**Comment by jonasbark** [comment]
@asaarnak it's been merged, but not released as of yet. We will release a new version once they do.

**Comment by remonh87** [comment]
should be solved in latests releases
