### ISSUE TITLE
Version 5.0.0 - error: no suitable constructor found for ReadableMap(HashMap<Object,Object>)

### ISSUE THREAD

**Issue by ShwetaChauhan18** [flutter-stripe/flutter_stripe#903]
**Describe the bug**
stripe_android-5.0.0/android/src/main/kotlin/com/facebook/react/bridge/WritableNativeMap.java:22: error: no suitable constructor found for ReadableMap(HashMap<Object,Object>)

I think it's not compatible with other library

**To Reproduce**
1. Update stripe with latest version
2. Android compileSdkVersion = 33
3. Clear pub cache
4. Run flutter clean
5. Run flutter pub get  
6. Run you app -> Getting this error -> stripe_android-5.0.0/android/src/main/kotlin/com/facebook/react/bridge/WritableNativeMap.java:22: error: no suitable constructor found for ReadableMap(HashMap<Object,Object>)

**Expected behavior**
Latest stripe version should work

**Smartphone / tablet**
 - Package version: [e.g. 5.0.0]
 - Flutter version [e.g. 3.0.0.]

**Additional context**
I already use android compileSdkVersion and targetSdkVersion 33

**Comment by jonasbark** [comment]
can you post the complete error output?

**Comment by ShwetaChauhan18** [comment]
```
/Users/shwetachauhan/Desktop/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/stripe_android-5.0.0/android/src/main/kotlin/com/facebook/react/bridge/WritableNativeMap.java:22: error: no suitable constructor found for ReadableMap(HashMap<Object,Object>)
        super(new HashMap<>());
        ^
    constructor ReadableMap.ReadableMap(JSONObject) is not applicable
      (argument mismatch; HashMap<Object,Object> cannot be converted to JSONObject)
    constructor ReadableMap.ReadableMap(Map<String,Object>) is not applicable
      (argument mismatch; HashMap<Object,Object> cannot be converted to Map<String,Object>)
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':stripe_android:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 19s
Exception: Gradle task assembleEuDevDebug failed with exit code 1
```

**Comment by ShwetaChauhan18** [comment]
#Fri Jun 23 08:50:38 CEST 2017
```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-6.6.1-all.zip
```

**Comment by jonasbark** [comment]
try upgrading to e.g.

distributionUrl=https\://services.gradle.org/distributions/gradle-7.4-all.zip

**Comment by ShwetaChauhan18** [comment]
No, it's not working. I think I have other dependency in my project and because of that this conflict issue come

**Comment by troy-oxstreet** [comment]
Upgrade the gradle build tool in android/build.gradle will fix this issue
```
dependencies {
        classpath 'com.android.tools.build:gradle:7.2.1'
}
```

**Comment by ShwetaChauhan18** [comment]
@troy-oxstreet : Thanks. After updating tools build Gradle it's working

**Comment by Priyank3032** [comment]
Thanks it's working me.
