### ISSUE TITLE
example server does not run

### ISSUE THREAD

**Issue by sk92129** [flutter-stripe/flutter_stripe#904]
**Describe the bug**
The example server written in javascript does not run.

src/index.ts:680:32 - error TS2339: Property 'financialConnections' does not exist on type 'Stripe'.

680   const session = await stripe.financialConnections.sessions.create({

**To Reproduce**
Set the server/.env values
Ran the "npm install"
Ran the "npm start"

**Expected behavior**
Expected the server to run and wait for RESTful requests.

**Additional context**

(base) SeanMacBookProPersonal:~ sean$ npm --version
8.11.0
(base) SeanMacBookProPersonal:~ sean$ node --version
v16.16.0

**Comment by jonasbark** [comment]
@remonh87 can you check this? I *think* that the npm lockfile needs to be updated

**Comment by remonh87** [comment]
ah yes I didn't do it actually we shouldn't commit the lock file I noticed stripe doesn't do this as well.  @sk92129  if you remove the lock file and run `npm install` it you should be fine. or run `npm update`

**Comment by sk92129** [comment]
deleting the node_modules completely, and removing the locks, and ONLY the yarn install works.
The npm install or npm update does not work --> meaning that the correct dependency is fetched and the line with :
const session = await stripe.financialConnections.sessions.create({
is resolvable.

**Comment by remonh87** [comment]
hmm that is interesting because for me it worked with npm install. Maybe we should move to yarn anyway which is also what Stripe is using .

**Comment by sk92129** [comment]
The git repo that I have is:

(base)  sean$ git log --pretty=format:'%h' -n 1
1f1100b
