### ISSUE TITLE
SEPA DD is not working in Subscription with PaymentSheet

### ISSUE THREAD

**Issue by ShwetaChauhan18** [flutter-stripe/flutter_stripe#909]
Describe the bug
When I try to create one time payment and using client secret if I open PaymentSheet I am able to get all payment method which is enable. e.g. Card, SEPA Debit Direct.

Now, when I try to do same thing for Subscription then not getting SEPA Direct Debit payment method.

To Reproduce

1. Create Intent for Subscription
2. Get Client Secret
3. Using that client secret open Payment Sheet
4. SEPA Debit Direct payment method should available in payment sheet
5. But only getting Card and Gpay payment method.

Expected behavior
- All payment method which is enable should show in PaymentSheet for Subscription.

Version
- Package version: [5.0.0]
- Flutter version [3.3.0]

Can you please try using this paymentIntentClientSecret and customerID.

```
    allowsDelayedPaymentMethods: true,
    merchantDisplayName: 'Flutter Stripe Store Demo',
    paymentIntentClientSecret: 'pi_3LeZNeGVrxoPH8K024F9PNkt_secret_TkcnsoHgrmgntO3Cmieyk1BCc',
    customerId: 'cus_MJcqkLF2BE29I1',
```

See here, you can see SEPA DD is available and when I click on this link it will ask detail for SEPA DD: https://invoice.stripe.com/i/acct_1GkcatGVrxoPH8K0/test_YWNjdF8xR2tjYXRHVnJ4b1BIOEswLF9NTksxOVJIdndKWnpiam5Fa0RYenY0QTAzZnhqcUlYLDUyOTEwMDY402005u8UlzDK?s=db

<img width="1335" alt="image" src="https://user-images.githubusercontent.com/34509457/188415162-5f70f511-646b-4822-bbd8-46c82e616461.png">

In Mobile payment sheet, It's crashing when only SEPA DD payment option available.

So, my concern is, will it work in PaymentSheet for subscription??? Just need confirmation.

_Originally posted by @ShwetaChauhan18 in https://github.com/flutter-stripe/flutter_stripe/issues/897#issuecomment-1236752123_

**Comment by jamesblasco** [comment]
Could you display the code you use to create the payment intent?

Currently Payment Sheet only supports card for payment intents that require saving payment methods for later use. Same for SetupIntents only card is supported for Payment Sheet.

<img width="690" alt="Screenshot 2022-12-10 at 18 49 43" src="https://user-images.githubusercontent.com/19904063/206869150-3faeae6f-6dd1-4d3f-a567-1ebaf0ccd259.png">

https://stripe.com/docs/payments/save-during-payment
https://stripe.com/docs/payments/save-and-reuse

If this changes in the future we will make sure it is updated in the plugin

**Comment by remonh87** [comment]
should be solved in latest releases with adding setupintent to the paymentsheet.
