### ISSUE TITLE
setting PaymentIntentsFutureUsage in PaymentMethodOptions is not saving card 

### ISSUE THREAD

**Issue by DavidEcclesPH** [flutter-stripe/flutter_stripe#911]
**Describe the bug**
I have set up the paymentMethod options as follows: 

`PaymentMethodOptions saveOptions = const PaymentMethodOptions(
      setupFutureUsage: PaymentIntentsFutureUsage.OnSession,
    );`

and use this option when confirming a payment via: 

`paymentIntent = await Stripe.instance.confirmPayment(
          secret,
          PaymentMethodParams.card(
            options: saveOptions,
            paymentMethodData: PaymentMethodData(
              billingDetails: billing,
            ),
          ),
        );`

however when looking at the payment in Stripe console, although the payment succeeds, the "setup_future_usage" parameter is never set in the `/v1/payment_intents/pi_.../confirm` API call, and so the card details are never saved. I can see that this is successfully set to "setup_future_usage": "on_session", when paying via our working web integration.

**To Reproduce**
1. we create paymentIntent via our api, which returns secret/publishable_key.
2. set publishable_key/merchantIdentifier on Stripe.instace.
3. attempt to confrim payment using Stripe.instance.confirmPayment() as above.
4. payment succeeds but does not save card details for future use.

**Expected behavior**
"setup_future_usage" to be set and card to appear in customer's Payment Methods 

**Smartphone / tablet**
 - Device: ios simulator (iphone11 / ios 15.5) & iPhone 11 (ios 15.6.1)
 - OS:ios 15.5
 - Package version: 5.0.0
 - Flutter version 3.0.5

**Additional context**
Hopefully I have configured something wrongly, although I was able to save cards previously with this method (maybe!) 🤔

**Comment by remonh87** [comment]
You need to add a ephermal key + customer id in order to save previously used cards. See https://docs.page/flutter-stripe/flutter_stripe/troubleshooting#the-stored-cards-are-not-being-displayed-on-the-payment_sheet

**Comment by DavidEcclesPH** [comment]
thanks for the reply @remonh87 👍 will try this today

**Comment by DavidEcclesPH** [comment]
Hi @remonh87 I think our work flow must be slightly different to the example you linked.

We create the payment intent with stripe via our api, this returns the publishable key which I set on the stripe instance and the client secret which I use in the Stripe.instance.confirmPayment() method. This method does not have the option to set the customerID/customerEphemeralKeySecret?

I have looked through the differences between the flutter logic and our (released & working) iOS logic and they seem to be using the same parameters. 

From looking at the back end logic our server is passing a customer to the Stripe SDK when creating the payment intent, although this is nullable and the cards are still being saved when the customer is null in iOS but not in Flutter. Any ideas?

**Comment by remonh87** [comment]
@DavidEcclesPH  the customerId is used for linking the payment to the customer but  as I always understood is you need the ephermal key in order to access the customer object (which is protected normally).  See also: https://stripe.com/docs/payments/accept-a-payment?platform=ios&ui=payment-sheet#add-server-endpoint .   If this is not possible I would recommend contacting Stripe support because I am not familiar with your specific use case.

**Comment by DavidEcclesPH** [comment]
Hi @remonh87 thanks for the reply. I have looked at this at length with one of our back end guys. You are right we are linking the customer to the payment method once we receive the payment intent success webhook from stripe, however... This hinges on the on "setup_future_usage: on_session" parameter being present and we can see from looking at the resulting calls in the Stripe dashboard that the flutter instance is not setting this param via the confirm payment methods despite including it in the PaymentMethodOptions:
![image](https://user-images.githubusercontent.com/94359534/190103231-3045c20d-c901-46c4-9a3e-4cbb224659f8.png)

**Comment by remonh87** [comment]
Ok thanks for the investigation. I will try to find some time coming days to investigate what is going wrong there.

**Comment by DavidEcclesPH** [comment]
Morning @remonh87 I know you will be a busy man, but have you had any time to take a look at this, or if not do you an estimate of when you might be able to so I know when to check back in? Many thanks 👍

**Comment by remonh87** [comment]
I am moving this week but hope to come back with an answer next Monday

**Comment by DavidEcclesPH** [comment]
thanks @remonh87 👍

**Comment by DavidEcclesPH** [comment]
morning @remonh87 👋 Just checking in on this 👍

**Comment by remonh87** [comment]
I think I start to see the problem in the plugin will try to test more and create fix in the weekend

**Comment by DavidEcclesPH** [comment]
@remonh87 thanks chief, much appreciated  🙏👍 looking forward to trying it out, just had a glance at the PR looks like quite a chunky change?

**Comment by remonh87** [comment]
It feels like chunky but it is due to the fact that freezed generates a ton of code. It was a relative small fix with a big diff

**Comment by DavidEcclesPH** [comment]
morning @remonh87 how's things? Just checking in, I had a look at the PR and looked like some tests are failing?
