### ISSUE TITLE
build not working

### ISSUE THREAD

**Issue by dvird** [flutter-stripe/flutter_stripe#914]
stripe_android-5.0.0/android/src/main/kotlin/com/reactnativestripesdk/CardFormView.kt: (31, 71): Unresolved reference: style

**Comment by dvird** [comment]
https://github.com/flutter-stripe/flutter_stripe/discussions/538#discussioncomment-2645392

**Comment by dvird** [comment]
please help @remonh87

**Comment by remonh87** [comment]
what is the gradle-wrapper version + compile sdk of your app?

**Comment by dvird** [comment]
distributionUrl=https\://services.gradle.org/distributions/gradle-7.4-all.zip
        classpath 'com.android.tools.build:gradle:7.1.2'
@remonh87

**Comment by jonasbark** [comment]
Can you please post the full build log?
Does the example app work for you?
