### ISSUE TITLE
Card Details not complete when default country is UnitedStates

### ISSUE THREAD

**Issue by icodelifee** [flutter-stripe/flutter_stripe#921]
**Describe the bug**
Card Details are not complete in CardFormField, if the default country is the United States.
You have to select a different country and then select back United States to show the postal code field.
![Screenshot 2022-09-14 at 6 32 04 PM](https://user-images.githubusercontent.com/18023153/190161092-536d6f97-ce0b-4e89-8ce3-dd9e0b4b4aa6.png)
![Screenshot 2022-09-14 at 6 33 04 PM](https://user-images.githubusercontent.com/18023153/190161275-7b648b7d-73d7-4a0f-9fbb-1c38065cb3a9.png)
![Screenshot 2022-09-14 at 6 33 23 PM](https://user-images.githubusercontent.com/18023153/190161344-25f3a6a2-8b27-46e9-8eb0-4c5f9c5fff1e.png)

**To Reproduce**
1. Enter card details in CardFormField. [enablePostCode: false]
2. Default Country is UnitedStates, but cardController.complete is false
3. Change to a different country and change back to the United States
4. Only then the postcode field shows up

**Expected behavior**
Postal code field should show up if the default country is the United States

**Smartphone / tablet**
 - Device: Oneplus Nord
 - OS: Android 12
 - Package version: 4.0.0
 - Flutter version  3.0.5

**Comment by jonasbark** [comment]
The postal code is indeed a requirement for united states, so I'm wondering why you are setting enablePostCode: false then?
I'm not surprised that the complete is false when the postcode is missing.

If your goal is to only show the postal code when the selected country is US then this is indeed something we do not support at the moment.

**Comment by icodelifee** [comment]
> The postal code is indeed a requirement for united states, so I'm wondering why you are setting enablePostCode: false then? I'm not surprised that the complete is false when the postcode is missing.
> 
> If your goal is to only show the postal code when the selected country is US then this is indeed something we do not support at the moment.

Yes, United States required post code but other countries don't, but in the case of United States which is selected by default it doesn't show the Post Code text field until I select a different country and change it back to United States

**Comment by remonh87** [comment]
this should be solved now in the latest releases of the library. If the issue still persist please reopen it.
