### ISSUE TITLE
Xcode 14 update causes issues, appears when build iOS for Release.

### ISSUE THREAD

**Issue by xSuperMu** [flutter-stripe/flutter_stripe#923]
After updating my Xcode to Xcode 14, this happened

When I run the debug version, everything works just fine, 
But when Building for release (flutter build ios --release) command
This happens

![Screen Shot 2022-09-14 at 9 21 05 PM](https://user-images.githubusercontent.com/17935590/190244463-9152fd1c-d85a-473c-84db-e61dbb7c0a63.png)

Here's my flutter doctor
`
❯ flutter doctor -v
[✓] Flutter (Channel stable, 3.3.1, on macOS 12.6 21G115 darwin-x64, locale en-US)
    • Flutter version 3.3.1 on channel stable at /Users/muhammadelsayed/Documents/PRO/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4f9d92fbbd (8 days ago), 2022-09-06 17:54:53 -0700
    • Engine revision 3efdf03e73
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/muhammadelsayed/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (4 available)
    • CPH1989 (mobile)                    • adb-TOCEA6MB5LOJYDCI-cTGp5h._adb-tls-connect._tcp. • android-arm64  • Android 11 (API 30)
    • iPhone SE (3rd generation) (mobile) • 08796A9A-245D-4483-913F-BEDF1A864B8B               • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-0
      (simulator)
    • macOS (desktop)                     • macos                                              • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)                        • chrome                                             • web-javascript • Google Chrome 105.0.5195.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
`

**Comment by remonh87** [comment]
This is not an issue on our library but on Cocoapods: https://github.com/CocoaPods/CocoaPods/issues/11402 . I fixed it manually but you can also use the work around in this issue.
