### ISSUE TITLE
doc not include video sample.

### ISSUE THREAD

**Issue by emznShivam** [flutter-stripe/flutter_stripe#925]
please, add video sample.

**Comment by igdmitrov** [comment]
@emznShivam It's not an official video from Stripe.
I recorded the short video about it and published it on my YouTube channel:
https://youtu.be/tu4FN4BEWGw

Hope it will be helpful for you.

**Comment by debjeetdebnath** [comment]
@igdmitrov please make a video for flutter web also

**Comment by remonh87** [comment]
instead of video samples we created more elaborate [docs](https://docs.page/flutter-stripe/flutter_stripe/sheet)
