### ISSUE TITLE
Create payment method without CardField

### ISSUE THREAD

**Issue by ldemyanenko** [flutter-stripe/flutter_stripe#927]
Hello. I'm trying to migrate my app from [flutter_stripe_payment](https://github.com/jonasbark/flutter_stripe_payment).
How can I create payment method without using a CardField.
We have custom UI in app for entering card details and it was compatible with flutter_stripe_payment.
Here I can't figure out how to use plugin without CardField in order to create payment method and confirm setup intent with this payment method id. If someone could point me or share a simple example of code it would be supper helpful.

**Comment by jonasbark** [comment]
https://github.com/flutter-stripe/flutter_stripe/blob/main/example/lib/screens/card_payments/custom_card_payment_screen.dart
