### ISSUE TITLE
Swift Compiler Error (Xcode): Stored properties cannot be marked potentially unavailable with '@available'

### ISSUE THREAD

**Issue by thulasipandiaraja** [flutter-stripe/flutter_stripe#932]
Swift Compiler Error (Xcode): Stored properties cannot be marked potentially unavailable with '@available'
AppName/ios/Pods/Stripe/Stripe/CardDetailsEditView.swift:72:5

Swift Compiler Error (Xcode): Stored properties cannot be marked potentially unavailable with '@available'
AppName/ios/Pods/Stripe/Stripe/STPAddCardViewController.swift:117:5

Before working fine. After update XCode 14.0 and Flutter upgrade these errors coming.

**Smartphone / tablet**
 - Device: Iphone 14
 - OS:  iOS 14.0
 - Package version: iOS and macOS (Xcode 14.0)
 - Flutter version 3.3.2

Could not build the application for the simulator.
Error launching application on iPhone 14.

**Comment by AndreHaueisen** [comment]
This fixed it for me
1- Make sure you are using at least version 5.0.0 of `flutter_stripe`
2- Go to your ios folder and run: `pod repo update` and then `pod update`

**Comment by jonasbark** [comment]
Yes, that should do it indeed - thanks @AndreHaueisen
