### ISSUE TITLE
Google Pay Button In PaymentSheet not compliant with Google Brand Guidelines

### ISSUE THREAD

**Issue by matloughnane** [flutter-stripe/flutter_stripe#934]
Google Pay Button in PaymentSheet not compliant with Google Brand Guidelines

1. Implemented the payment sheet with default settings
2. Submitted screenshots for review to Google (https://pay.google.com/business/console) 
3. Received the following in a rejection email:

> Our brand guidelines for Android have recently been updated. The [Google Pay button](https://developers.google.com/pay/api/android/guides/brand-guidelines#payment-buttons) is now only available in one color and is rounded.  
> Please make the appropriate updates, and re-submit your integration again through the Google Pay & Wallet Console.

See images below for comparison.

**Smartphone / tablet**
 - Device: Android Devices
 - Package version: 5.0.0
 - Flutter version: 3.3.2

**Additional context**
Not sure if this is something that is managed by the Pay plugin or the Stripe Flutter team, but thought it was worth raising

## Images

Current GPay button using `flutter_stripe 5.0.0`

<img src="https://user-images.githubusercontent.com/1440617/191068813-0998b29c-210d-4f0a-955a-3fd985dac56c.jpeg" width="400" height="390">

Expected look:
![image](https://user-images.githubusercontent.com/1440617/191068326-2a36c77d-ad26-4cff-8389-7d1e31e375d3.png)

**Comment by jonasbark** [comment]
https://github.com/flutter-stripe/flutter_stripe/issues/862
a fix is pending with https://github.com/flutter-stripe/flutter_stripe/pull/929

**Comment by matloughnane** [comment]
Ah cheers @jonasbark - should I close? Or leave for other devs.

**Comment by remonh87** [comment]
Fixed in version 5.1.0

**Comment by JlUgia** [comment]
To avoid needing to update the assets in the future, consider using the [graphics-only button widget (`RawGooglePayButton`) from the pay_android package](https://github.com/google-pay/flutter-plugin/tree/main/pay_android).

Note also that this button uses vector only graphics defined on the Flutter end, so there's no need to have Android using nine patches and raster files.
