### ISSUE TITLE
Internal error when use setupIntent for Google Pay on payment sheet

### ISSUE THREAD

**Issue by acgacgacgacg** [flutter-stripe/flutter_stripe#935]
**Describe the bug**
Internal error happens when use setupIntent for Google Pay.

**To Reproduce**
Use the example app's payment sheet.
Here is a video describe the bug.
[google_pay_setup.webm](https://user-images.githubusercontent.com/10584507/191399376-4767746f-5979-4700-bcb8-8c26c3f8e8b4.webm)

When use `paymentIntent`, there is no problem.

Here is the flutter code:
```dart
await Stripe.instance.initPaymentSheet(
        paymentSheetParameters: SetupPaymentSheetParameters(
          allowsDelayedPaymentMethods: true,
          setupIntentClientSecret: data['setupIntent'],
          merchantDisplayName: 'Flutter Stripe Store Demo',
          // Customer params
          customerId: data['customer'],
          // customerEphemeralKeySecret: data['ephemeralKey'],
          // Extra params
          applePay: PaymentSheetApplePay(
            merchantCountryCode: 'JP',
          ),
          googlePay: PaymentSheetGooglePay(
            merchantCountryCode: 'JP',
            testEnv: true,
          ),
          ...
          billingDetails: billingDetails,
        ),
      );
```

The setupIntent server side code:
```typescript
const setupIntent = await stripe.setupIntents.create({
    customer: customer.id,
  });
return res.json({
    setupIntent: setupIntent.client_secret,
    ephemeralKey: ephemeralKey.secret,
    customer: customer.id,
  });
```

**Expected behavior**
No error should occur and the setupIntent should be confirmed.

**Smartphone / tablet**
 - Device: emulator
 - OS: Android api 32
 - Package version: 5.0.0
 - Flutter version 3.3.0

**Additional context**
There are similar issues in the past, but not sure they are resolved or not.
If we use `presentGooglePay` instead of payment sheet, Google Pay can be properly saved as setupIntent
```dart
await Stripe.instance.initGooglePay(GooglePayInitParams(
            testEnv: true,
            merchantName: "Example Merchant Name",
            countryCode: 'jp'));

  await Stripe.instance.presentGooglePay(
    PresentGooglePayParams(
        clientSecret: clientSecret,
        forSetupIntent: true,
        currencyCode: "jpy"),
  );
```

**Comment by jonasbark** [comment]
An internal error sounds interesting. I have been unable to confirm this in our example app and server, so I assume it might be a configuration issue in your server or Stripe itself.

You might want to contact Stripe support on this.

**Comment by acgacgacgacg** [comment]
Problem solved.
Need to add currency code to `PaymentSheetGooglePay` like below.
```dart
googlePay: PaymentSheetGooglePay(
            merchantCountryCode: 'JP',
            currencyCode: "JPY",
            testEnv: true,
          ),
```
