### ISSUE TITLE
Blank page when accesing for second time

### ISSUE THREAD

**Issue by AnKorIO** [flutter-stripe/flutter_stripe#940]
**Describe the bug**
When you open the web view is opened a second time the form isn't loaded.

**To Reproduce**
1. Open a checkout
2. Cancel it
3. Open again just when is closed

**Expected behavior**
The web form shuld load

**Smartphone / tablet**
 - Device: Xiaomi Mi A1
 - OS: Android 9
 - Package version: 1.0.0
 - Flutter version 3.0.1 

**Additional context**
I soved it adding this code on **_CheckoutPageState** inside **onPageFinished**
` else if(url == "about:blank"){
                _webViewController!.loadHtmlString(_htmlPage, baseUrl: _baseUrl);
              }`

**Comment by smanojarun** [comment]
@AnKorIO  : I'm also facing the same issue. Have you found any solution ?

I have edited as per your solution but that's not working for me. Any thoughts or suggestions ?

**Comment by remonh87** [comment]
I cannot reproduce this issue more on latest flutter stable so I assume it is fixed now. Feel free to reopen and ping if the issue still persist
