### ISSUE TITLE
SCA authentication web page doesn't close automatically on IOS

### ISSUE THREAD

**Issue by ldemyanenko** [flutter-stripe/flutter_stripe#942]
On Android this page close automatically. On IOS user needs to tap close button manually and the page doesn't look good in the end.
Is there a way to configure same behaviour of IOS as per Android?
![File (3)](https://user-images.githubusercontent.com/22637733/191990591-7d11eb45-e9da-4d39-9648-51bb25cfa155.jpg)

![IMG_5787](https://user-images.githubusercontent.com/22637733/191988511-d80f6e26-e87a-4270-90c8-a4c7e87b970f.png)

**Comment by jonasbark** [comment]
This should be fixed by https://github.com/flutter-stripe/flutter_stripe/pull/939

**Comment by remonh87** [comment]
fixed in version 5.1.0

**Comment by ldemyanenko** [comment]
I've checked the 5.1.0 version and it works the same as before. Should I add some configuration here to make it work?
