### ISSUE TITLE
Run xcode. Unhandled exception: Command "rsync -8 -av --delete --filter - .DS_Store

### ISSUE THREAD

**Issue by thulasipandiaraja** [flutter-stripe/flutter_stripe#943]
I try to run my application. I got error like this. 

Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    Writing result bundle at path:
        /var/folders/gg/mv7q5yr92p3cs1tztc6sx3c40000gn/T/flutter_tools.bzJlzW/flutter_ios_build_temp_dir5eUoeC/temporary_xcresult_bundle

    rsync: link_stat "/Users/raja/Desktop/Thulasi/CustomerApp/build/ios/Debug-iphonesimulator/App.framework" failed: No such file or directory (2)
    rsync error: some files could not be transferred (code 23) at
    /AppleInternal/Library/BuildRoots/a0876c02-1788-11ed-b9c4-96898e02b808/Library/Caches/com.apple.xbs/Sources/rsync/rsync/main.c(996) [sender=2.6.9]
    rsync: link_stat "/Users/raja/Desktop/Thulasi/CustomerApp/build/ios/Debug-iphonesimulator/App.framework" failed: No such file or directory (2)
    rsync error: some files could not be transferred (code 23) at
    /AppleInternal/Library/BuildRoots/a0876c02-1788-11ed-b9c4-96898e02b808/Library/Caches/com.apple.xbs/Sources/rsync/rsync/main.c(996) [sender=2.6.9]

    Unhandled exception:
    Exception: Command "rsync -8 -av --delete --filter - .DS_Store /Users/raja/Desktop/Thulasi/CustomerApp/build/ios/Debug-iphonesimulator/App.framework
    /Users/raja/Desktop/Thulasi/CustomerApp/build/ios/Debug-iphonesimulator/Runner.app/Frameworks" exited with code 23
    #0      Context.runSync (file:///opt/homebrew/Caskroom/flutter/2.2.3/flutter/packages/flutter_tools/bin/xcode_backend.dart:105:7)
    #1      Context.embedFlutterFrameworks (file:///opt/homebrew/Caskroom/flutter/2.2.3/flutter/packages/flutter_tools/bin/xcode_backend.dart:190:5)
    #2      Context.run (file:///opt/homebrew/Caskroom/flutter/2.2.3/flutter/packages/flutter_tools/bin/xcode_backend.dart:61:9)
    #3      main (file:///opt/homebrew/Caskroom/flutter/2.2.3/flutter/packages/flutter_tools/bin/xcode_backend.dart:17:5)
    #4      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
    #5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Building targets in dependency order
    warning: Run script build phase 'Thin Binary' will be run during every build because it does not specify any outputs. To address this warning, either add
    output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in
    target 'Runner' from project 'Runner')

    Result bundle written to path:
        /var/folders/gg/mv7q5yr92p3cs1tztc6sx3c40000gn/T/flutter_tools.bzJlzW/flutter_ios_build_temp_dir5eUoeC/temporary_xcresult_bundle

Could not build the application for the simulator.
Error launching application on iPhone 14.

what's wrong with it? anybody can help me?

**Comment by jonasbark** [comment]
There's no indication that it is caused by the stripe plugin. I recommend doing flutter clean, removing derived data etc

**Comment by thulasipandiaraja** [comment]
Thank you so much.
