### ISSUE TITLE
CardFormField does not display, payment information is incomplete

### ISSUE THREAD

**Issue by HatsuneMikuV** [flutter-stripe/flutter_stripe#944]
**Describe the bug**
After jumping to the new interface to edit the CardFormField information, return to the payment page. At this time, the CardFormField is not displayed, and the payment is directly invalid. The error message: "Card details not complete"

If the CardFormField is displayed on the payment page, the payment is normal

But the same operation process, there is no such problem on iOS, the payment is normal

After checking the location of the error report, I found that because Android uses the card information to read from the UI, the UI no longer exists at this time, as shown in the following figure
![20220924-194143](https://user-images.githubusercontent.com/14038743/192096040-d4ba892d-d0f7-4076-bd8c-c81672538824.jpeg)
![20220924-194139](https://user-images.githubusercontent.com/14038743/192096049-6ddfc5c2-addd-4f67-8d2b-12810a62851b.jpeg)

Please, can this problem be fixed? Keep the same logic as iOS?

**Comment by remonh87** [comment]
Android works fundamentally different than iOS unfortunately and this is part of the Stripe sdk. I still struggle to understand what is the issue here. can you provide more additional repo steps?  @jonasbark  since you know the most about android do you see what is happening?

**Comment by jonasbark** [comment]
Indeed the card form has to still be displayed on the screen in order to use its data.
