### ISSUE TITLE
error: 'Flutter/Flutter.h' file not found when flutter build on iOS

### ISSUE THREAD

**Issue by thulasipandiaraja** [flutter-stripe/flutter_stripe#948]
After flutter upgrade my project fails to build in Xcode with the following error:

Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    Writing result bundle at path:
        /var/folders/gg/mv7q5yr92p3cs1tztc6sx3c40000gn/T/flutter_tools.Nof8e6/flutter_ios_build_temp_dirTveyRC/temporary_xcresult_bundle

    /Users/raja/Desktop/Thulasi/CustomerApp/ios/Runner/Runner-Bridging-Header.h:1:9: note: in file included from
    /Users/raja/Desktop/Thulasi/CustomerApp/ios/Runner/Runner-Bridging-Header.h:1:
    #import "GeneratedPluginRegistrant.h"
            ^
    /Users/raja/Desktop/Thulasi/CustomerApp/ios/Runner/GeneratedPluginRegistrant.h:10:9: error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^
    1 error generated.
    <unknown>:0: error: failed to emit precompiled header
    '/Users/raja/Library/Developer/Xcode/DerivedData/Runner-ehmkizsapnabsuefcjkqagfojrxu/Build/Intermediates.noindex/PrecompiledHeaders/Runner-Bridging-Heade
    r-swift_E353VELBY9KT-clang_3BEPZ5UA4L5B5.pch' for bridging header '/Users/raja/Desktop/Thulasi/CustomerApp/ios/Runner/Runner-Bridging-Header.h'
    /Users/raja/Desktop/Thulasi/CustomerApp/ios/Runner/Runner-Bridging-Header.h:1:9: note: in file included from
    /Users/raja/Desktop/Thulasi/CustomerApp/ios/Runner/Runner-Bridging-Header.h:1:
    #import "GeneratedPluginRegistrant.h"
            ^
    2 errors generated.
    note: Building targets in dependency order
    note: Run script build phase 'Thin Binary' will be run during every build because the option to run the script phase "Based on dependency analysis" is
    unchecked. (in target 'Runner' from project 'Runner')
    note: Run script build phase 'Run Script' will be run during every build because the option to run the script phase "Based on dependency analysis" is
    unchecked. (in target 'Runner' from project 'Runner')

    Result bundle written to path:
        /var/folders/gg/mv7q5yr92p3cs1tztc6sx3c40000gn/T/flutter_tools.Nof8e6/flutter_ios_build_temp_dirTveyRC/temporary_xcresult_bundle

Error (Xcode): 'Flutter/Flutter.h' file not found
/Users/raja/Desktop/Thulasi/CustomerApp/ios/Runner/GeneratedPluginRegistrant.h:9:8

Error (Xcode): failed to emit precompiled header
'/Users/raja/Library/Developer/Xcode/DerivedData/Runner-ehmkizsapnabsuefcjkqagfojrxu/Build/Intermediates.noindex/PrecompiledHeaders/Runner-Bridging-Header-sw
ift_E353VELBY9KT-clang_3BEPZ5UA4L5B5.pch' for bridging header '/Users/raja/Desktop/Thulasi/CustomerApp/ios/Runner/Runner-Bridging-Header.h'

Encountered error while building for device.

what's wrong with it? anybody can help me?

**Comment by remonh87** [comment]
This has nothing to do with our library . I would advise run `flutter clean` then `flutter pub get` and finally go to iOS folder and run `pod install`.

**Comment by thulasipandiaraja** [comment]
I tried not working for me. same errors appeared.
