### ISSUE TITLE
Error when updating XCode to 14.0.1

### ISSUE THREAD

**Issue by kwstasarva** [flutter-stripe/flutter_stripe#953]
Hello,

As the title indicates, there is an error when archiving our project since the XCode was updated to 14.0.1. 
Specifically in STPApplePayContext.swift:240. 

```
let pk_didSelectShippingMethod = #selector(
            (PKPaymentAuthorizationControllerDelegate.paymentAuthorizationController(
                _:didSelectShippingMethod:handler:)) **as pkDidSelectShippingMethodSignature**)
```
The casting at the end _**as pkDidSelectShippingMethodSignature**_ is the problem. 

We are using flutter_stripe 2.5.0 and unfortunately we cannot update since we're still @ flutter 2.10.4

Is there anything we can do?

Thank you for your help

**Comment by jonasbark** [comment]
STPApplePayContext.swift is a class from Stripes' iOS SDK. There's nothing we can do about it.
You will have to downgrade Xcode or update your Flutter version.

**Comment by Anonymousgaurav** [comment]
@kwstasarva did you got any solution?
