### ISSUE TITLE
WebView doesn't close after upgrade to version 5.0.0

### ISSUE THREAD

**Issue by anderscheow** [flutter-stripe/flutter_stripe#955]
**Describe the bug**
After done payment with credit card or FPX, the WebView doesn't close itself

**To Reproduce**
1. Select payment with credit card or FPX
2. Wait WebView to prompt
3. WebView keep showing

**Expected behavior**
WebView should close itself

**Smartphone / tablet**
 - Device: iOS and Android devices
 - OS: iOS 15, Android 13
 - Package version: 5.0.1
 - Flutter version: 3.3.3

**Additional context**
[PR #399](https://github.com/flutter-stripe/flutter_stripe/pull/939/files#diff-335935de2fba34ebb3a33a5da02ec269fe95700b281249c2d846499d171c2df8L135)
I added the lines of code, but get removed from this PR

**Comment by jonasbark** [comment]
Are you using the handleURLCallback from 5.0.1?

**Comment by anderscheow** [comment]
Got any tutorial on how to use that method?

**Comment by anderscheow** [comment]
@jonasbark By using the `handleURLCallback`, I need to add one dependency [app_links](https://pub.dev/packages/app_links) to listen the deep link callback.

**Comment by remonh87** [comment]
this should be fixed now in later releases of the library. Feel free to reopen it if the issue still persist
