### ISSUE TITLE
confirmSetupIntent on Android returns "Card details not complete"

### ISSUE THREAD

**Issue by simranjeet09** [flutter-stripe/flutter_stripe#957]
Error Message: StripeException(error: LocalizedErrorMessage(code: FailureCode.Failed, localizedMessage: Card details not complete, message: Card details not complete, stripeErrorCode: null, declineCode: null, type: null))

**Steps to reproduce:**
1. Generate secret  using web api 
2.  Confirm setup intent using **confirmSetupIntent** method
3. Error in android **Card details not complete,**. 
4. in iOS works as expected.

**Expected behavior**
it should save the card and return paymentmethod id and status. 

**Smartphone / tablet**
 - Device: Samsung a22
 - OS:Android 11
 - Package version:  5.1.0
 - Flutter version  
 - Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.1 21C52 darwin-arm, locale en-CA)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.71.2)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

• No issues found!
simranjeet.dev@Simranjeets-MacBook-Pro

for ios  , I have left billing and shipping details blank but it works as expected however during debugging I saw a comment of stripe member on react native repo that this error could be due to missing billing details. 

UI is handled by GetX and stateless widget. 

Code block which is returning error. 
//details masked( I have removed actual address from the fields)

        final response = await Stripe.instance.confirmSetupIntent(
          secrete,
          const PaymentMethodParams.card(
            paymentMethodData: PaymentMethodData(
                //TODO hit and trial for android
                /*    billingDetails: BillingDetails(
                phone: "",
                email: "simranjeet@email.org",
                name: "Simranjeet",
                address:  a.Address(city: " ", country: " ", line1: " ",  : " ", postalCode: " ", state: " "),
              ),
              shippingDetails: ShippingDetails(
                phone: " ",
                name: "Simranjeet",
                carrier: "In",
                trackingNumber: "bla bla",
                address:  a.Address(city: " ", country: " ", line1: " ", line2: " ", postalCode: " ", state: " "),
              )*/
                ),
            options: PaymentMethodOptions(
              setupFutureUsage: PaymentIntentsFutureUsage.OffSession,
            ),
          ),
        );

**Comment by A7mdFathi** [comment]
I have got The same issue happened with Apple pay

**Comment by sherkot** [comment]
Same issue

**Comment by fahadappguy** [comment]
Hey, I have tried it in a very simple way and it's working fine on Android but not working for Web. May be it will help you.

```
 CardField(
          enablePostalCode: true,
          postalCodeHintText: 'Postal code',
          countryCode: AppData.countryCode??'US',
          onCardChanged: (_card) {
            card = _card;
          },
        ),
```
```
 final paymentIntent = await Stripe.instance.confirmSetupIntent(
                clientSecret,
                const PaymentMethodParams.card(
                  paymentMethodData: PaymentMethodData(),
                  options: PaymentMethodOptions(),
                ),
              );
```

**Comment by debjeetdebnath** [comment]
@fahadappguy have you successfully implemented stripe on flutter web ?

**Comment by simranjeet09** [comment]
> Hey, I have tried it in a very simple way and it's working fine on Android but not working for Web. May be it will help you.
> 
> ```
>  CardField(
>           enablePostalCode: true,
>           postalCodeHintText: 'Postal code',
>           countryCode: AppData.countryCode??'US',
>           onCardChanged: (_card) {
>             card = _card;
>           },
>         ),
> ```
> 
> ```
>  final paymentIntent = await Stripe.instance.confirmSetupIntent(
>                 clientSecret,
>                 const PaymentMethodParams.card(
>                   paymentMethodData: PaymentMethodData(),
>                   options: PaymentMethodOptions(),
>                 ),
>               );
> ```

It did not worked for me. Also I need to save card off session.. so that is a requirement.

**Comment by A7mdFathi** [comment]
After a lot of searching, we found that our publish key changed after we change our code it work well.

> I have got The same issue happened with Apple pay

**Comment by mohitmarfatia** [comment]
I've got the same issue for android, works well for ios, and haven't checked for web because it isn't a requirement for now.

**Comment by jamesblasco** [comment]
Maybe related to https://github.com/flutter-stripe/flutter_stripe/issues/944

**Comment by DavidEcclesPH** [comment]
Hi @jamesblasco wondering if there has been any progress on this issue? Came across this today, don't know if it's relevant but this works on iOS but fails on android at the point where the 3rd party bank verification launches? Not sure what triggers this, but it doesn't trigger on android and we get the 'Card details not complete' error.

**Comment by DavidEcclesPH** [comment]
> Hey @jamesblasco
> 
> My Apologies for replying late on this ticket. This issue seems to be related to some of the fields like billing address or zip code basically which are optional but should't be. After putting all the details it worked fine. There was also a bug related to this issue which was fixed in an update a long ago. So I am not entirely sure that it was due to the optional fields or due to some internal bug. I am closing this ticket for now and will reopen if I observe the same again.
> 
> Thanks.

Hi @simranjeet09 I'm not sure I agree with this as I tested with the example code that James linked to above and adding all possible billing details I still got the same error. Any other suggestions? thanks!
