### ISSUE TITLE
Bottom Sheet BillingDetail not posted on stripe dashboard

### ISSUE THREAD

**Issue by alisidhu** [flutter-stripe/flutter_stripe#964]
BillingDetail not posting on stripe dashboard on payment succeed response..

**To Reproduce**
1. Stripe.instance
          .initPaymentSheet(
          paymentSheetParameters: SetupPaymentSheetParameters(
              style: ThemeMode.dark,
              customFlow: false,
              merchantDisplayName: 'cba',
              paymentIntentClientSecret: paymentIntentModel.clientSecret,
              customerId: customerId,
              billingDetails: getBillingDetail()));

  BillingDetails? getBillingDetail() {

    return BillingDetails(
      name: username,
      email: email,
      phone: phoneNo,
    );
  }
2. Entering number 123-456-789 into the cardfield.
3. Tapping the confirm button.
5. Data not posted STRIPE DASHBOARD:
"billing_details": {
            "address": {
              "city": null,
              "country": "US",
              "line1": null,
              "line2": null,
              "postal_code": "12332",
              "state": null
            },
            "email": null,
            "name": null,
            "phone": null
          },

**Expected behavior**

**Smartphone / tablet**
 - Device: Iphone13
 - OS: [e.g. iOS 15.6,]
 - Package version: [e.g. 5.1.0]
 - Flutter version [e.g. 3.0.0.]

**Additional context**

**Comment by remonh87** [comment]
This is a bit confusing but unfortunately how Stripe works. If you check our documentation for that particular field we mention: 

```
    /// Default billing information of the customer.
    ///
    /// Use this field to already prefill the customers billingDetails in the payment sheet.
    /// For example when you supply a country the country will be set on the payment sheet +
    /// alternative localization options. This does not set the billingDetails on the
    /// paymentIntent since the customer can change those.
```
