### ISSUE TITLE
Flutter example App, PayPal payment error.

### ISSUE THREAD

**Issue by paricleu** [flutter-stripe/flutter_stripe#971]
**Describe the bug**
When I try to test PayPal Payment in the flutter example app the following error is thrown.
![paypal](https://user-images.githubusercontent.com/48349235/195313844-b5426309-6fb9-4532-8143-efa9fb3d78a1.png)

**To Reproduce**

1. Follow readme, start server and "flutter run" in emulator device.
2. Pick PayPal payment option, enter email and tab "Pay"-
3. Observe a failure with exception as per image. 

**Expected behavior**

**Smartphone**
 - Device: Pixel 4 API 31 Emulator
 - OS: Android 12
 - Package version: 5.1.0
 - Flutter version: 3.3.4

**Additional context**
Does Stripe even support PayPal? I find conflicting information online and I can't find documentation in Stripes docs about PayPal but then why does the example app contain the paypal payment type?

**Comment by jonasbark** [comment]
PayPal is in private beta - you need to contact stripe Support in order to get access
