### ISSUE TITLE
Problem Report for Runner

### ISSUE THREAD

**Issue by thulasipandiaraja** [flutter-stripe/flutter_stripe#975]
After upgrading to Xcode and IOS I am unable to run any ios app on my M1 macbook. What is the issue here?

Problem Report from Runner

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Incident Identifier: 9B2FD8F5-008B-4ABF-90C9-89215689B073
CrashReporter Key:   CD4F9FC7-090D-4A02-9C2F-BFEB7D59ECE0
Hardware Model:      MacBookAir10,1
Process:             Runner [3023]
Path:                /Users/USER/Library/Developer/CoreSimulator/Devices/68D543F0-893F-4714-BB8C-D0B98B63DC35/data/Containers/Bundle/Application/62F99240-5E16-4E14-B486-35EB9F3D38C1/Runner.app/Runner
Identifier:          com.abs.customer
Version:             2.0.1 (30)
Code Type:           X86-64 (Native)
Role:                Foreground
Parent Process:      launchd_sim [846]
Coalition:           com.apple.CoreSimulator.SimDevice.68D543F0-893F-4714-BB8C-D0B98B63DC35 [842]
Responsible Process: SimulatorTrampoline [826]

Date/Time:           2022-10-16 14:22:08.8887 +0400
Launch Time:         2022-10-16 14:22:08.2006 +0400
OS Version:          macOS 12.6 (21G115)
Release Type:        User
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: DYLD 1 Library missing
Library not loaded: @rpath/Flutter.framework/Flutter
Referenced from: <7109B01E-5366-3062-A547-EF5993D2BC37> /Users/USER/Library/Developer/CoreSimulator/Devices/68D543F0-893F-4714-BB8C-D0B98B63DC35/data/Containers/Bundle/Application/62F99240-5E16-4E14-B486-35EB9F3D38C1/Runner.app/Runner
Reason: tried: '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/Flutter.framework/Flutter' (errno=2), '/usr/lib/swift/Flutter.framework/Flutter' (errno=2, no dyld cache), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/Flutter.framework/Flutter' (errno=2), '/usr/lib/swift/Flutter.framework/Flutter' (errno=2, no dyld cache), '/Users/raja/Library/Developer/CoreSimulator/Devices/68D543F0-893F-4714-BB8C-D0B98B63DC35/data/Containers/Bundle/Application/62F99240-5E16
(terminated at launch; ignore backtrace)

Triggered by Thread:  0

Kernel Triage:
VM - pmap_enter failed with resource shortage
VM - pmap_enter failed with resource shortage
VM - pmap_enter failed with resource shortage
VM - pmap_enter failed with resource shortage
VM - pmap_enter failed with resource shortage

Thread 0 Crashed:
0   ???                           	       0x1021d7940 ???
1   <translation info unavailable>	       0x1022678bc ???
2   dyld                          	       0x202415a72 abort_with_payload_wrapper_internal + 80
3   dyld                          	       0x202415aa4 abort_with_payload + 9
4   dyld_sim                      	       0x10a97a593 abort_with_payload + 26
5   dyld_sim                      	       0x10a927f1e dyld4::halt(char const*) + 375
6   dyld_sim                      	       0x10a925f75 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 3928
7   dyld_sim                      	       0x10a9261a0 _dyld_sim_prepare + 442
8   dyld                          	       0x2023bfb78 dyld4::prepareSim(dyld4::RuntimeState&, char const*) + 1265
9   dyld                          	       0x2023be70e dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 244
10  dyld                          	       0x2023be4e4 start + 388

Thread 1:: com.apple.rosetta.exceptionserver
0   ???                           	    0x7ff7ffd8e944 ???
1   ???                           	    0x7ff7ffda71f0 ???

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000006  rbx: 0x00000000000000e8  rcx: 0x0000000000000001  rdx: 0x00000003073d24f0
  rdi: 0x00000020073d21e8  rsi: 0x00000003073d2760  rbp: 0x0000000000000000  rsp: 0x00000003073d20f0
   r8: 0x00000003073d20f0   r9: 0x0000000000000000  r10: 0x00000000000000e8  r11: 0xfefefefefefefeff
  r12: 0x00000000000000e8  r13: 0x00000003073d24f0  r14: 0x0000000000000001  r15: 0x0000000000000006
  rip: <unavailable>       rfl: 0x0000000000000283
 tmp0: 0xffffffffffffffff tmp1: 0x00000001021d7914 tmp2: 0x0000000202415a72

Binary Images:
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
       0x2023b9000 -        0x202424fff dyld (*) <71febccd-d9dc-3599-9971-2b3407c588a8> /usr/lib/dyld
       0x10a924000 -        0x10a983fff dyld_sim (*) <db2ea9eb-03d5-3b81-a6ce-26ec4dd81b07> /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/dyld_sim

Error Formulating Crash Report:
dyld_process_snapshot_get_shared_cache failed

EOF

-----------
Full Report
-----------

{"app_name":"Runner","timestamp":"2022-10-16 14:22:10.00 +0400","app_version":"2.0.1","slice_uuid":"7109b01e-5366-3062-a547-ef5993d2bc37","build_version":"30","platform":7,"bundleID":"com.abs.customer","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.6 (21G115)","incident_id":"9B2FD8F5-008B-4ABF-90C9-89215689B073","name":"Runner"}
{
  "uptime" : 150,
  "procLaunch" : "2022-10-16 14:22:08.2006 +0400",
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookAir10,1",
  "procStartAbsTime" : 3584546896,
  "coalitionID" : 842,
  "osVersion" : {
    "train" : "macOS 12.6",
    "build" : "21G115",
    "releaseType" : "User"
  },
  "captureTime" : "2022-10-16 14:22:08.8887 +0400",
  "incident" : "9B2FD8F5-008B-4ABF-90C9-89215689B073",
  "bug_type" : "309",
  "pid" : 3023,
  "procExitAbsTime" : 3600934923,
  "translated" : true,
  "cpuType" : "X86-64",
  "procName" : "Runner",
  "procPath" : "\/Users\/USER\/Library\/Developer\/CoreSimulator\/Devices\/68D543F0-893F-4714-BB8C-D0B98B63DC35\/data\/Containers\/Bundle\/Application\/62F99240-5E16-4E14-B486-35EB9F3D38C1\/Runner.app\/Runner",
  "bundleInfo" : {"CFBundleShortVersionString":"2.0.1","CFBundleVersion":"30","CFBundleIdentifier":"com.abs.customer"},
  "storeInfo" : {"deviceIdentifierForVendor":"5BF546A9-1E5C-5156-ACB4-826F718F133B","thirdParty":true},
  "parentProc" : "launchd_sim",
  "parentPid" : 846,
  "coalitionName" : "com.apple.CoreSimulator.SimDevice.68D543F0-893F-4714-BB8C-D0B98B63DC35",
  "crashReporterKey" : "CD4F9FC7-090D-4A02-9C2F-BFEB7D59ECE0",
  "responsiblePid" : 826,
  "responsibleProc" : "SimulatorTrampoline",
  "sip" : "enabled",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":1,"flags":518,"namespace":"DYLD","indicator":"Library missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Library not loaded: @rpath\/Flutter.framework\/Flutter","Referenced from: <7109B01E-5366-3062-A547-EF5993D2BC37> \/Users\/USER\/Library\/Developer\/CoreSimulator\/Devices\/68D543F0-893F-4714-BB8C-D0B98B63DC35\/data\/Containers\/Bundle\/Application\/62F99240-5E16-4E14-B486-35EB9F3D38C1\/Runner.app\/Runner","Reason: tried: '\/Applications\/Xcode.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/Runtimes\/iOS.simruntime\/Contents\/Resources\/RuntimeRoot\/usr\/lib\/swift\/Flutter.framework\/Flutter' (errno=2), '\/usr\/lib\/swift\/Flutter.framework\/Flutter' (errno=2, no dyld cache), '\/Applications\/Xcode.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/Runtimes\/iOS.simruntime\/Contents\/Resources\/RuntimeRoot\/usr\/lib\/swift\/Flutter.framework\/Flutter' (errno=2), '\/usr\/lib\/swift\/Flutter.framework\/Flutter' (errno=2, no dyld cache), '\/Users\/raja\/Library\/Developer\/CoreSimulator\/Devices\/68D543F0-893F-4714-BB8C-D0B98B63DC35\/data\/Containers\/Bundle\/Application\/62F99240-5E16"]},
  "ktriageinfo" : "VM - pmap_enter failed with resource shortage\nVM - pmap_enter failed with resource shortage\nVM - pmap_enter failed with resource shortage\nVM - pmap_enter failed with resource shortage\nVM - pmap_enter failed with resource shortage\n",
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":16250,"threadState":{"flavor":"x86_THREAD_STATE","rbp":{"value":0},"r12":{"value":232},"rosetta":{"tmp2":{"value":8627772018},"tmp1":{"value":4330453268},"tmp0":{"value":18446744073709551615}},"rbx":{"value":232},"r8":{"value":13006348528},"r15":{"value":6},"r10":{"value":232},"rdx":{"value":13006349552},"rdi":{"value":137560400360},"r9":{"value":0},"r13":{"value":13006349552},"rflags":{"value":643},"rax":{"value":6},"rsp":{"value":13006348528},"r11":{"value":18374403900871474943},"rcx":{"value":1},"r14":{"value":1},"rsi":{"value":13006350176}},"frames":[{"imageOffset":4330453312,"imageIndex":0},{"imageOffset":4331043004,"region":"<translation info unavailable>","imageIndex":0},{"imageOffset":379506,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":80,"imageIndex":1},{"imageOffset":379556,"symbol":"abort_with_payload","symbolLocation":9,"imageIndex":1},{"imageOffset":353683,"symbol":"abort_with_payload","symbolLocation":26,"imageIndex":2},{"imageOffset":16158,"symbol":"dyld4::halt(char const*)","symbolLocation":375,"imageIndex":2},{"imageOffset":8053,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":3928,"imageIndex":2},{"imageOffset":8608,"symbol":"_dyld_sim_prepare","symbolLocation":442,"imageIndex":2},{"imageOffset":27512,"symbol":"dyld4::prepareSim(dyld4::RuntimeState&, char const*)","symbolLocation":1265,"imageIndex":1},{"imageOffset":22286,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":244,"imageIndex":1},{"imageOffset":21732,"symbol":"start","symbolLocation":388,"imageIndex":1}]},{"id":16251,"name":"com.apple.rosetta.exceptionserver","frames":[{"imageOffset":140703126055236,"imageIndex":0},{"imageOffset":140703126155760,"imageIndex":0}]}],
  "usedImages" : [
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 8627392512,
    "size" : 442368,
    "uuid" : "71febccd-d9dc-3599-9971-2b3407c588a8",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4472324096,
    "size" : 393216,
    "uuid" : "db2ea9eb-03d5-3b81-a6ce-26ec4dd81b07",
    "path" : "\/Applications\/Xcode.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/Runtimes\/iOS.simruntime\/Contents\/Resources\/RuntimeRoot\/usr\/lib\/dyld_sim",
    "name" : "dyld_sim"
  }
],
  "vmSummary" : "ReadOnly portion of Libraries: Total=210.6M resident=0K(0%) swapped_out_or_unallocated=210.6M(100%)\nWritable regions: Total=157.3M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=157.3M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nRosetta Arena                     4096K        2 \nRosetta Generic                    852K      210 \nRosetta IndirectBranch              32K        1 \nRosetta JIT                      128.0M        1 \nRosetta Return Stack                20K        2 \nRosetta Thread Context              20K        2 \nStack                             8176K        1 \nStack Guard                       56.0M        1 \nVM_ALLOCATE                       13.4M        8 \nVM_ALLOCATE (reserved)              20K        2         reserved VM address space (unallocated)\n__DATA                            7492K      112 \n__DATA_CONST                      9184K       44 \n__DATA_DIRTY                         8K        2 \n__FONT_DATA                          4K        1 \n__LINKEDIT                        90.2M       87 \n__LLVM_COV                          32K        1 \n__TEXT                           120.4M       85 \ndyld private memory               1280K        2 \nmapped file                        6.1G       37 \n===========                     =======  ======= \nTOTAL                              6.5G      601 \nTOTAL, minus reserved VM space     6.5G      601 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "5fc94383418129005b4e9ae0",
      "factorPackIds" : {

      },
      "deploymentId" : 240000498
    },
    {
      "rolloutId" : "5ffde50ce2aacd000d47a95f",
      "factorPackIds" : {

      },
      "deploymentId" : 240000207
    }
  ],
  "experiments" : [

  ]
},
  "reportNotes" : [
  "dyld_process_snapshot_get_shared_cache failed"
]
}

Model: MacBookAir10,1, BootROM 7459.141.1, proc 8:4:4 processors, 8 GB, SMC 
Graphics: Apple M1, Apple M1, Built-In
Display: Color LCD, 2560 x 1600 Retina, Main, MirrorOff, Online
Memory Module: LPDDR4
AirPort: Wi-Fi, wl0: Mar 23 2022 19:57:59 version 18.60.27.0.7.8.129 FWID 01-570be953
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB31Bus
Thunderbolt Bus: MacBook Air, Apple Inc.
Thunderbolt Bus: MacBook Air, Apple Inc.

flutter doctor -v
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.6 21G115 darwin-arm, locale en-AE)
    • Flutter version 3.3.4 on channel stable at /Users/raja/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (11 days ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/raja/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.72.2)
    • VS Code at /Users/raja/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • 68D543F0-893F-4714-BB8C-D0B98B63DC35 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 106.0.5249.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

How can i fix this one? can anybody help me?

**Comment by remonh87** [comment]
I would recommend taking this up with the flutter team. If you have issues with Stripe library feel free to raise a new issue. My two cents is that you need to clear some cache or check your podfile.

**Comment by thulasipandiaraja** [comment]
Thank you for your reply.
