### ISSUE TITLE
Dark GooglePayButton

### ISSUE THREAD

**Issue by psenakv** [flutter-stripe/flutter_stripe#986]
**Describe the bug**
GooglePayButtonType.pay_dark and GooglePayButtonType.standard_dark is missing

**To Reproduce**
1. Flutter pub get version 5.1.0

**Expected behavior**
GooglePayButtonType.pay_dark and GooglePayButtonType.standard_dark  available

**Additional context**
[Changelog](https://pub.dev/packages/flutter_stripe/changelog) for 5.0.0 says "Added support for pay_dark and standard_dark to the GooglePayButton component. This allows you to display the dark Google Pay button.", but that support is missing

**Comment by remonh87** [comment]
We added support but they are removed from version `5.1.0` as part of the sync with Stripe react native: https://github.com/stripe/stripe-react-native/releases/tag/v0.19.0
