### ISSUE TITLE
Apple Pay "Payment not completed" when requesting shipping address

### ISSUE THREAD

**Issue by omar-selo** [flutter-stripe/flutter_stripe#988]
**Describe the bug**
When adding `ApplePayContactFieldsType.postalAddress` to `requiredShippingAddressFields`, `presentApplePay` opens Apple pay native UI and shows "Processing" in the bottom for a while before showing "Payment not completed" and closing the payment sheet without any user input. Note that this issue doesn't occur if I remove `ApplePayContactFieldsType.postalAddress` requirement. For reference the error returned is `PlatformException(Canceled, The payment has been canceled, null, null)`.

**Smartphone / tablet**
 - Device: iPhone 8 physical device
 - OS: iOS 15.5
 - Package version: 5.1.0
 - Flutter version 3.3.3

**Comment by remonh87** [comment]
Thanks for the context I could reproduce it. It looks like sth is wrong in the Stripe sdk and I created https://github.com/stripe/stripe-react-native/issues/1189 .

**Comment by remonh87** [comment]
Update from my side I pushed a fix to our sync branch and we expect to release a new version the coming days.

**Comment by remonh87** [comment]
fixed in version 7.0
