### ISSUE TITLE
Add support for Stripe Identity

### ISSUE THREAD

**Issue by rlee1990** [flutter-stripe/flutter_stripe#991]
Will this support more of stripes futures such as identity? Stripe already supports this for mobile.
It would be nice to see more of Stripes features supported instead of having to send it to a browser or other workarounds.

**Comment by remonh87** [comment]
We are dependent on the implementation of the official stripe react native sdk to implement the native bindings. Once that is done we will implement it.

**Comment by rlee1990** [comment]
> We are dependent on the implementation of the official stripe react native sdk to implement the native bindings. Once that is done we will implement it. 

Okay cool.

**Comment by leidig54** [comment]
Hi. Any update on this? Or an ETA? Looking at ways to implement identity verification in my app. Would rather wait for this if it's close to being implemented.

**Comment by rlee1990** [comment]
@leidig54 As a workaround I use webhooks and server functions to use the link option.

**Comment by leidig54** [comment]
Do you mean using the VerificationSession API from the "No Code" section? I'll take a look. 

Would be great to get a native implementation if possible down the line for the best UX.

**Comment by rlee1990** [comment]
@leidig54 Yes that's what we are using as a workaround until a native solution

**Comment by pshanmukha** [comment]
> We are dependent on the implementation of the official stripe react native sdk to implement the native bindings. Once that is done we will implement it. 

Any update on this?

**Comment by sjprograms** [comment]
> We are dependent on the implementation of the official stripe react native sdk to implement the native bindings. Once that is done we will implement it.

@remonh87 Have you looked into this recently? As mentioned previously, Stripe has documentation for Identity using a React SDK. We are looking to integrate Stripe Identity into an app we are building now but our Flutter developer has suggested using the web SDK instead.

**Comment by g-30** [comment]
Will Stripe Identity support flutter any time soon?

**Comment by remonh87** [comment]
I will take a look next month see what can be done. Btw I am not working for Stripe so it will best effort, no guarantees.

**Comment by remonh87** [comment]
Me and @jonasbark  are the only maintainers of this library at the moment and do this in our free time (besides having both our own companies). Stripe is a huge sdk and it cost us a lot of time maintaining this sdk on 3 platforms, so we do not want to add an extra maintenance burden. We encourage the community to implement an sdk for this and we are happy to provide some help.
