### ISSUE TITLE
can't decode onApplePayResult dynamic value

### ISSUE THREAD

**Issue by heshesh2010** [flutter-stripe/flutter_stripe#992]
Hi , my apple pay button works great and return the token but i just need these values from onApplePayResult :

    transactionId,
    ephemeralPublicKey,
    publicKeyHash,
    data,
    signature,
    version,
    transactionIdentifier,
    network,
    displayName,
    type,

i'm using this code 

  void onApplePayResult(paymentResult) {

    if (paymentResult is String) {
      Fluttertoast.showToast(
          msg: "String",
          toastLength: Toast.LENGTH_LONG,
          gravity: ToastGravity.TOP);
    }

    if (paymentResult is Map) {
      Fluttertoast.showToast(
          msg: "map",
          toastLength: Toast.LENGTH_LONG,
          gravity: ToastGravity.TOP);
    }

    Map result = jsonDecode(paymentResult); // give me error 

    //  String transactionIdentifier = jsonDecode(paymentResult["transactionIdentifier"]);

    String network = result['token']['network'];
    String displayName = result['token']['displayName'];
    String type = result['token']['type'].toString();

    String version = result['token']['version'].toString();
    String data = result['token']['data'];
    String signature = result['token']['signature'];
    String ephemeralPublicKey = result['header']['ephemeralPublicKey'];
    String publicKeyHash = result['header']['publicKeyHash'];
    String transactionId = result['header']['transactionId'].toString();

    
  }

**Comment by remonh87** [comment]
Can you explain more why you need this information? You normally get this data when the backend creates a payment intent.

The token is encrypted so you cannot decode it using json decode. For more info see: https://developer.apple.com/documentation/passkit/apple_pay/payment_token_format_reference
