### ISSUE TITLE
Integrate Stripe Elements in Stripe checkout

### ISSUE THREAD

**Issue by MatteoAntolini** [flutter-stripe/flutter_stripe#993]
Is it possible to add google pay and apple pay in the checkout session?

I have them configured on my account, but they don't show in the checkout session. 

https://stripe.com/docs/payments/accept-a-payment?platform=web&ui=checkout#testing-apple-pay-google-pay

I have a saved card on google pay and tried with and without `payment_method_types: ['card']`, but it doesn't show it. Is this related to the in-app browser?

**Comment by remonh87** [comment]
we currently have integrated the stripe web element in `flutter_stripe_web`

**Comment by SayedMainUddin** [comment]
i am getting this error in android : I/chromium( 6145): [INFO:CONSOLE(1)] "Unrecognized feature: 'payment'.", source: https://js.stripe.com/v3 (1)
