### ISSUE TITLE
"presentForPaymentIntent() may only be called when Google Pay is available on this device." is thrown when Google Pay is available on the device

### ISSUE THREAD

**Issue by ovchars2** [flutter-stripe/flutter_stripe#995]
Hi! We have noticed an issue using flutter_stripe v5.1.0. I tried to reproduce the same issue in the latest example application, and the behavior is the same:

**Description**
On some devices (Nokia 2.4, Nokia 5.3), when trying to pay using Google Pay wallet from Stripe plugin (`google_pay_stripe_screen.dart`), `Stripe.instance.isGooglePaySupported` method returns the value of `true`. But when the `Stripe.instance.presentGooglePay` method is called, it throws `StripeException(error: LocalizedErrorMessage(code: FailureCode.Failed, localizedMessage: presentForPaymentIntent() may only be called when Google Pay is available on this device.))`.

**To Reproduce**
1. Clone, configure and start flutter_stripe example application
2. Navigate to Wallets->Google Pay screen (`google_pay_stripe_screen.dart`)
3. Tap the Google Pay button

**Expected behavior**
Should open the Google Pay bottom sheet if Google Pay is available, or return false on `Stripe.instance.isGooglePaySupported` method if Google Pay is not supported for payments without using the `pay` plugin

**Smartphone / tablet**
 - Device: Nokia 2.4, Nokia 5.3
 - OS: Android 11
 - Package version: 5.1.0, package from`main` branch
 - Flutter version 3.0.2

**Additional context**
On other devices it seems to work as expected, and no issues were noticed during testing. When Google Pay - Pay plugin option is used (on the same Nokia devices that are affected by this issue), Google Pay payments are successful

**Comment by remonh87** [comment]
It took me some time to look into it and the code is coming from the Stripe native android sdk.  What is weird is that  the check is the same as `isGooglePaySupported` . Do you use the same payment profile (name card etc ? ) on the nokias as on the other devices?

**Comment by ovchars2** [comment]
Yes, payment profiles were the same on every device (Same google account, same card, address etc).

I have just noticed that for some reason Google Play Services update crashes when I am trying to open Google Wallet on the Nokia device, it is possible that it has something to do with the issue, I will look into that and get back to you when I have a result.

Tried reproducing the issue with the `3.2.0` version of `flutter_stripe`, and I see that this issue also appears on older package versions as well, so library update had nothing to do with the bug.

**Comment by didnteven** [comment]
I am also getting the error:
"StripeException(error: LocalizedErrorMessage(code: FailureCode.Failed, localizedMessage: presentForPaymentIntent() may only be called when Google Pay is available on this device., message: presentForPaymentIntent() may only be called when Google Pay is available on this device., stripeErrorCode: null, declineCode: null, type: null))"

On S8 and S7 devices (only devices tested so far)
flutter_stripe 6.0.0 and 7.0.0

When using a phone with one google account and no payment method attached.
This error gets shown, doesn't show to add card like it should.
Also google pay shows as available.

Works fine if payment method is attached prior to opening app.

Why could this be?

**Comment by remonh87** [comment]
this should now be solved with the improved native payment method integration
