### ISSUE TITLE
Stripe.instance.createPaymentMethod() doesn't work on Flutter Web and produces an UnimplementedError message

### ISSUE THREAD

**Issue by saedkhaled** [flutter-stripe/flutter_stripe#998]
Stripe.instance.createPaymentMethod() function doesn't work on Flutter Web and produces an UnimplementedError message as follows:
Error: UnimplementedError
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49  throw_
packages/flutter_stripe_web/src/web_stripe.dart 67:5                          createPaymentMethod
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54            runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5            _async
packages/flutter_stripe_web/src/web_stripe.dart 55:44                         createPaymentMethod
packages/flutter_stripe/src/stripe.dart 166:27                                createPaymentMethod
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50            <fn>
dart-sdk/lib/async/zone.dart 1653:54                                          runUnary
dart-sdk/lib/async/future_impl.dart 147:18                                    handleValue
dart-sdk/lib/async/future_impl.dart 766:44                                    handleValueCallback
dart-sdk/lib/async/future_impl.dart 795:13                                    _propagateToListeners
dart-sdk/lib/async/future_impl.dart 430:9                                     callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15           <fn>

1. Just use the create payment method with PaymentMethodParams.card as params

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.4, on macOS 13.0 22A380 darwin-arm, locale en-TR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.2)
[✓] VS Code (version 1.71.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

 - Device: Macbook Pro 14'', 2021
 - OS: MacOS 13.0
 - Browser: Google Chrome 106.0.5249.119
 - Stripe Web Package version: 2.0.0
 - Stripe Package version: 6.0.0
 - Flutter version: 3.3.4

I searched a little bit in the package code and found that you are using the wrong field name in web_stripe.dart line 59 when getting the field from the JSON object you are searching for a field called "type" while you should get the "paymentMethodType" field instead. you can check it i already tried modifying the file and it worked normally. can you please check and fix it as soon as possible?
Thank you

**Comment by remonh87** [comment]
the web is very limited at the moment. we are working at the moment to find a good solution. For the moment I recommend using checkout.

**Comment by saedkhaled** [comment]
@remonh87 i know it is limited but it was working on previous versions, and i already found the solution to this bug and suggested the solution above.
