### ISSUE TITLE
CVC to CVV

### ISSUE THREAD

**Issue by jeemon-k-j** [flutter-stripe/flutter_stripe#999]
**Describe the bug**
Notchange the CVC field to CVV.

**To Reproduce**
1. Entering CVV code into the codefeild.

**Expected behavior**
Change the code field to CVC/CVV as per card
**Smartphone / tablet**
 - Device: [ iPhone 11]
 - OS: [iOS 16, Android 11]
 - Package version: [leatest]
 - Flutter version [3.6.6.]

**Additional context**

**Comment by jeemon-k-j** [comment]
Please help me to fix this issue.

if we try to add a random number it is also taken as a valid card in the card  number field and code field

**Comment by remonh87** [comment]
Can you explain me the problem a bit more? If you use the stripe test cards it doesn't matter which cvc code you add. There is no difference between CVC and CVV (only the network is different VISA vs Mastercard). Normally cvc is used .

**Comment by remonh87** [comment]
I just tested on master the cardfield with card 4000 0000 0000 0127 (any cvc and exp date), press pay. I receive back an error from Stripe that the CVC is not correct.  I think there is something wrong in your implementation.  I advise in test mode to use this card and see that you get back the error. In order to help you further I need to have a reproduction scenario.

**Comment by jeemon-k-j** [comment]
In live mode, I have tested with a valid visa card and a different CVV  I got an error from the bank side but payment was made successfully

**Comment by jeemon-k-j** [comment]
one more thing can I change the CVC label to CVV

is it possible

**Comment by jeemon-k-j** [comment]
we just tried with 4242424242424242 (any CVC and exp date), and I didn't get any error

**Comment by jeemon-k-j** [comment]
and also tried with my MasterCard valid card number and expiry date and different CVC and pressed pay, but I don't get back any error

**Comment by jeemon-k-j** [comment]
Sometimes it only shows loading but no error returning,

**Comment by remonh87** [comment]
I would recommend asking these questions to Stripe support, they can help you more with integration questions. We only provide a dart wrapper around the stipe client sdks . It looks like the data is passed correctly to stripe and what happens after that is out of our hands.
